### ISSUE TITLE
No substring rule on attributes in the OpenLDAP FreeRADIUS schema

### ISSUE THREAD

**Issue by bgmilne** [FreeRADIUS/freeradius-server#1003]
In some cases, when RADIUS accounts are stored in an LDAP directory, it may be desireable to have substring indexes on some of the RADIUS attributes.

At present, the OpenLDAP schema file (doc/schemas/ldap/openldap/freeradius.schema) doesn't define substring rules for any of the FreeRADIUS attributes, which prevents enabling substr indexes in OpenLDAP:

/etc/openldap2.4/slapd.conf: line 303: substr index of attribute "radiusFramedIPAddress" disallowed

The schema should define appropriate substring indexing rules, in order to allow the administrator to decide whether it is appropriate to enable substring indexes or not.

The attributes that I use that I believe should have a SUBSTR rule assigned would be at least:
- radiusGroupName
- radiusFramedRoute
but a few more may be appropriate.

Additionally, for any attributes of type integer (1.3.6.1.4.1.1466.115.121.1.27) should probably have an ORDERING rule assigned (so that a filter of .e.g (radiusSimultaneousUse>=1) would work).

If agreement is reached on which attributes should have SUBSTR rules assigned, I am happy to prepare a pull request.

**Comment by arr2036** [comment]
Please send a full list of the attributes, with the ones you think should have substrings, marked.

**Comment by mpcathey** [comment]
At least these...

radiusFramedIpAddress
radiusAttribute
freeradiusDhcpGatewayAddr
radiusFramedRoute

**Comment by arr2036** [comment]
No one asked you @mpcathey :P

**Comment by arr2036** [comment]
freeradiusDhcpGatewayAddr already has substring match.
