### ISSUE TITLE
Move PW_TYPE field into value_data_t

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1012]
Hi @arr2036,

I have noticed that some parts of code we can improve the use of talloc.

Below is an example.

```
            if (datafmt.namelen > 0) {
-                   MEM(p = talloc_array(names, char, (size_t)datafmt.namelen + 1));
-                   strlcpy(p, datafmt.name, (size_t)datafmt.namelen + 1);
-                   names[i] = p;
+                   names[i] = talloc_strndup(handle, datafmt.name, datafmt.namelen);
            }
```

What do you think about that? I believe that can improve the performance and viewing. I worked on this around of the rlm_sql and If you like i can make a pull-request about that.

**Comment by arr2036** [comment]
Agreed, though for equivalence it'd be ``MEM(names[i] = talloc_strndup(handle, datafmt.name, datafmt.namelen));``. the MEM macro causes the server to exit if the allocation fails. Pull request would be appreciated, thanks!

**Comment by jpereira** [comment]
Great that you agree. I believe that after that could be a kind of 'good practice'.

I'll submit as soon.

**Comment by arr2036** [comment]
TBH a lot of that code will be going away though. The better solution is for the drivers to produce an array of value_data_t structs, and the rest of the code to be updated to use those.

In the not too distant future, the drivers could then be updated to write values out in native formats, and avoid a lot of the integer-> string -> integer conversions which go on now.

Don't know if you'd be interested in tackling that instead?

**Comment by arr2036** [comment]
Also for this particular case best practice would be to use ``talloc_bstrndup`` instead of ``talloc_strndup``, then we're binary safe and slightly more efficient.

**Comment by jpereira** [comment]
Something like that is used in PW_TYPE? (data->strvalue, data->intvalue, ... )?

about the talloc_bstrndup(), is a internal function. looks like nice.

**Comment by arr2036** [comment]
yes, exactly.

First stage is to allocate ``value_data_t`` array instead of ``char *`` array. the rest of the code can assume that it's always a string value (``data->strvalue``).

Second stage is to modify ``value_data_t`` to contain ``PW_TYPE``, but that requires lots of reworking of library functions, so i'll handle that.

Third stage is to modify rlm_sql to use ``http://doc.freeradius.org/value_8c.html#acf0daac84fc691ddb32aa7cebe9e8575`` (value_data_cast) to convert elements of the value_data_t array to the types needed by VALUE_PAIRs

Final stage is to modify drivers, so they create ``value_data_t`` with types native(ish) to the driver, like data->integer/integer64.

**Comment by arr2036** [comment]
This is similar to some work i'm doing in my repo, to add an rlm_cache_redis driver.

https://github.com/arr2036/freeradius-server/commit/3b507516d7032fd1fe886e0b299c1b259a12da38#diff-0f5206431c3de43f94182928afc03b98R188

**Comment by jpereira** [comment]
That first impression that is a good idea. I could handle the adjustments in the rlm_sql, but what
the best approach? in this case after you finish the reworking in the library function?

**Comment by arr2036** [comment]
The first stage can be done before my modifications. The rlm_sql code should assume the value_data_t is of type PW_TYPE_STRING

**Comment by jpereira** [comment]
Great! When you finish, please ping back here for I continue the improvements.

**Comment by jpereira** [comment]
Hi @arr2036 , have finished the work in the PW_TYPE?

**Comment by arr2036** [comment]
No *sigh*, maybe tomorrow.
