### ISSUE TITLE
Suggestion for add $raddbdir/proxies-available and $raddbdir/proxies-enabled

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1017]
Hi @arr2036  and @alandekok,

  What do you think to change the proxy.conf to become like $raddbdir/sites-enabled? I have used like this and i can say that it is a perfect way to handler tens of external clients (roaming partenrs)

**Comment by alandekok** [comment]
I think it starts confusing people.  There's no "servers available" and "servers enabled" split for proxy.  Just the enabled ones.

What specifically do you propose?

**Comment by arr2036** [comment]
hm, i'm against. I think we should be moving more in the direction of dynamic home servers and proxying which may have the same effect when the dynamic realms are defined in files.

**Comment by jpereira** [comment]
I believe that when you have more than 10 home server, it is the begin of madness to handle the config files. And if you can split in directories this should be more easy to enable/disable each server rather than comment the lines with '#'.

My propose @alandekok is create $raddbdir/proxies-available and $raddbdir/proxies-enabled and reference in the radiusd.conf with:

$INCLUDE proxies-enabled/

**Comment by alandekok** [comment]
I don't think the list of home servers changes that often.  And because the home servers are tied to pools and realms, you can't just comment out a home server.  You have to update the pool, too.

It's much better to have dynamic home servers.  Put them into a DB, and let FR pull them from the DB, or expire them, as needed.

**Comment by jpereira** [comment]
Good point @alandekok , you convinced me! :+1:
