### ISSUE TITLE
Add glob() support in $INCLUDE

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1018]
Hi @alandekok/@arr2036 ,

What do you think about the $INCLUDE support glob() ?

e.g: $INCLUDE sites-enabled/*.conf

**Comment by arr2036** [comment]
What do you mean exactly? $INCLUDE already supports wildcards? Do you mean changing it to restrict includes to .conf files only?

**Comment by jpereira** [comment]
@arr2036 exactly... support wildcards! like the idea?

**Comment by arr2036** [comment]
It already does IIRC

**Comment by alandekok** [comment]
There's no call to glob() in src/main/conffile.c.

Globs would be nice, but not *required*.

**Comment by arr2036** [comment]
In that case I support adding globs.

**Comment by jpereira** [comment]
[root@jpereira-desktop freeradius]# tail -2 radiusd.conf 

$INCLUDE teste/*.conf
[root@jpereira-desktop freeradius]# ls -l $PWD/teste/
total 0
-rw-r--r-- 1 root freerad 0 Mai 20 16:38 exemplo
-rw-r--r-- 1 root freerad 0 Mai 20 16:38 exemplo.conf
[root@jpereira-desktop freeradius]# strace -e open /usr/sbin/freeradius -XXXxxx 2>&1 | tail -4
open("/etc/freeradius/teste/*.conf", O_RDONLY) = -1 ENOENT (No such file or directory)
Wed May 20 16:42:04 2015 : Error: Unable to open file "/etc/freeradius/teste/*.conf": No such file or directory
Wed May 20 16:42:04 2015 : Error: Errors reading or parsing /etc/freeradius/radiusd.conf
+++ exited with 1 +++
[root@jpereira-desktop freeradius]#

**Comment by jpereira** [comment]
@arr2036 I have added support about that!

**Comment by arr2036** [comment]
It's useful. If only Alan didn't hate file extensions so much...

**Comment by jpereira** [comment]
sure! I am excited to read the @alandekok blessing the idea... but we have big chances to him confirm that hate it! haha!

**Comment by arr2036** [comment]
any progress on this?

**Comment by jpereira** [comment]
@arr2036 I'll push this week.
