### ISSUE TITLE
Broken links in online man pages

### ISSUE THREAD

**Issue by DougHockin** [FreeRADIUS/freeradius-server#1020]
On this page:

http://freeradius.org/radiusd/man/radiusd.html

These links are broken:

http://freeradius.org/radiusd/man/huntgroups.html

http://freeradius.org/radiusd/man/hints.html

**Comment by DougHockin** [comment]
On this page:

http://freeradius.org/radiusd/man/naslist.html

This link is broken:

http://freeradius.org/radiusd/man5/clients.5.html

On this page:

http://freeradius.org/radiusd/man/dictionary.html

This link is broken:

http://www.iana.org/enterprise-numbers.txt

**Comment by arr2036** [comment]
In future can you firstly, not post issues if you can easily fix them yourself by sending a pull request, secondly post them to the right repo https://github.com/FreeRADIUS/www.freeradius.org.

Thanks!

**Comment by arr2036** [comment]
Fixed all the links you reported.
