### ISSUE TITLE
OpenSSL version mismatch

### ISSUE THREAD

**Issue by Compizfox** [FreeRADIUS/freeradius-server#1025]
Hi,

When I rebooted my server (Debian Stretch) today, FreeRADIUS didn't come up. The error I'm getting is:

    libssl version mismatch.  built: 100010bf linked: 1000201f

Since I'm running Debian (which has ancient FreeRADIUS packages in their repos) I built FreeRADIUS from source. So I thought downloading and building the newest version (3.0.8) would fix the problem.

Unfortunately this is not the case, even after recompiling the error persists.

The OpenSSL installed on my system is:

    OpenSSL 1.0.2a 19 Mar 2015

**Comment by arr2036** [comment]
> On 29 May 2015, at 14:32, Lars Veldscholte <notifications@github.com> wrote:
> 
> Hi,
> 
> When I rebooted my server (Debian Stretch) today, FreeRADIUS didn't come up. The error I'm getting is:
> 
> libssl version mismatch.  built: 100010bf linked: 1000201f
> 
> Since I'm running Debian (which has ancient FreeRADIUS packages in their repos) I'm built FreeRADIUS from source. So I thought downloading and building the newest version (3.0.8) would fix the problem.
> 
> Unfortunately this is not the case, even after recompiling the error persists.

Check the configure output at compile time, which version does it show?

Arran Cudbard-Bell <a.cudbardb@freeradius.org>
FreeRADIUS development team

FD31 3077 42EC 7FCD 32FE 5EE2 56CF 27F9 30A8 CAA2

**Comment by arr2036** [comment]
Also, this isn't really a bug, so it should be discussed on the mailing list, not using the github issue tracker

**Comment by Compizfox** [comment]
I'm sorry, I thought this was a bug.

This is reported when I run configure:

    checking for OpenSSL version >= 0.9.7... yes
    checking OpenSSL library and header version consistency... library: 1000201f header: 1000201f... yes

Also note that I do not normally run `./configure`, I use `dpkg-buildpackage -b -uc` since I want to build Debian packages.

**Comment by arr2036** [comment]
It's ok, just for future reference.

I'm not convinced the new binary is being executed. Check the output of ``radiusd -Xv``, it should show a git commit hash matching the head of the branch you're building.

**Comment by Compizfox** [comment]
Sorry, this was indeed not a bug. I was being a moron by forgetting to upgrade libfreeradius (I only updated the freeradius* packages).

You can close this one.

**Comment by arr2036** [comment]
ah, yes, easily done. Unfortunately there's not a good way to encode the commit hash in the package versions :/
