### ISSUE TITLE
FreeRADIUS-build breaks when disabling SSL version check

### ISSUE THREAD

**Issue by qnet-herwin** [FreeRADIUS/freeradius-server#1030]
At least, that's what it does in my 32-bit systems (tested on Debian Jessie and Ubuntu Vivid) on branch `v3.0.x` and `v3.1.x`. Building fails with this message:

```
...
CC src/main/pair.c
CC src/main/xlat.c
build/lib/local/.libs/libfreeradius-eap.so: undefined reference to `fr_tls_status_table'
collect2: error: ld returned 1 exit status
make: *** [build/bin/local/radeapclient] Error 1
```

**Comment by alandekok** [comment]
Yes... OSX is a little more forgiving about undefined references.

In this case, the status table is defined in the server core.  Libraries can't really reference functions in the server core.  They have to reference functions in other libraries.

**Comment by arr2036** [comment]
It also builds on travis, and there must be something in place to allow eap modules to use the functions in tls.c (which is where the table is defined).
