### ISSUE TITLE
More indexes for accounting on/off statements

### ISSUE THREAD

**Issue by alandekok** [FreeRADIUS/freeradius-server#1037]
The standard indexes work for the normal auth/acct queries.  But when the server receives an Accouting-On packet, that query devolves to a table scan.

All of the modules in raddb/sql/main/ should have indexes added for accounting on/off.

Postgresql has it:

    -- For use by onoff-
    CREATE INDEX radacct_bulk_close ON radacct (NASIPAddress, AcctStartTime) WHERE AcctStopTime IS NULL;

but the other modules don't have it.  The poor people using MySQL should be using indexes, too.

**Comment by arr2036** [comment]
not every other DB is as fancy as PG, with its conditional indexes, so they'll need ``NASIPAddress, AcctStartTime, AcctStopTime``
