### ISSUE TITLE
Memleaks with inner-tunnel and PEAP

### ISSUE THREAD

**Issue by qnet-herwin** [FreeRADIUS/freeradius-server#1039]
With branch `v3.0.x` (haven't tested `v3.1.x`), with the user `bob`/`hello` enabled as only change to the vanilla config, PEAP authentications will be performed using the `inner-tunnel` virtual server. I've used the following file for `eapol_test`:

```
network={
  ssid="example"
  key_mgmt=WPA-EAP
  eap=PEAP
  identity="bob"
  anonymous_identity="anonymous"
  password="hello"
  phase2="autheap=MSCHAPV2"
}
```

When running multiple instances of `eapol_test` looped, you can see the memory usage of radiusd growing. After stopping this clients the memory usage doesn't drop down.

**Comment by alandekok** [comment]
I've checked this will talloc and valgrind.  Once the server cleans up all of the old requests, there is no outstanding allocated memory reported by talloc or valgrind.

When I do this on OSX, the memory is returned to the system.

**Comment by alandekok** [comment]
I've pushed some changes to command.c

Start the server, and run radmin with the commands:

    stats memory total
    stats memory blocks

* Run the server for a while in your tests.
* Wait for it to print "Ready to process requests".
* Wait 60s for the EAP session cache to completely time out
* run one eapol_test for PEAP
* wait 5 seconds for that to clean up, and the server to print "Ready to process requests"

Then run the "stats" commands again.  You should see the same numbers

The difference between the "stats" command and the output of "top" is that memory is allocated by the process, but isn't being returned to the OS when the memory is free'd.  This is normal.
