### ISSUE TITLE
radclient: free() invalid pointer

### ISSUE THREAD

**Issue by alvaro83** [FreeRADIUS/freeradius-server#1040]
Hi,

I'm using radclient (version 3.0.3, built on Aug 3 2014) in a Suse12 environment in the following way:

echo Acct-Status-Type=Stop, Acct-Session-ID=\"52:54:00:3C:CB:6F\", NAS-IP-Address=1.2.3.4 | radclient -x 192.168.60.42 acct testing123

Curiously, the Radius message is correctly sent and received by the server, but the radclient aborts with return code 134 and with the following error message:

*** Error in `radclient': free(): invalid pointer: 0x00007fd1250c7b00 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x730bf)[0x7fd122df90bf]
/lib64/libc.so.6(+0x7892e)[0x7fd122dfe92e]
/lib64/libc.so.6(+0x79636)[0x7fd122dff636]
/usr/lib64/freeradius/libfreeradius-radius.so(fr_hash_table_free+0x67)[0x7fd1241f6d37]
/usr/lib64/freeradius/libfreeradius-radius.so(dict_free+0x19)[0x7fd1241f1d89]
radclient(main+0xcbc)[0x7fd12464368c]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fd122da7b05]
radclient(+0x3ecd)[0x7fd124643ecd]
======= Memory map: ========
7fd121774000-7fd12178a000 r-xp 00000000 00:20 8496                       /lib64/libgcc_s.so.1
7fd12178a000-7fd121989000 ---p 00016000 00:20 8496                       /lib64/libgcc_s.so.1
7fd121989000-7fd12198a000 r--p 00015000 00:20 8496                       /lib64/libgcc_s.so.1
7fd12198a000-7fd12198b000 rw-p 00016000 00:20 8496                       /lib64/libgcc_s.so.1
7fd12198b000-7fd121992000 r-xp 00000000 00:20 7678                       /lib64/librt-2.19.so
7fd121992000-7fd121b91000 ---p 00007000 00:20 7678                       /lib64/librt-2.19.so
7fd121b91000-7fd121b92000 r--p 00006000 00:20 7678                       /lib64/librt-2.19.so
7fd121b92000-7fd121b93000 rw-p 00007000 00:20 7678                       /lib64/librt-2.19.so
7fd121b93000-7fd121c93000 r-xp 00000000 00:20 7654                       /lib64/libm-2.19.so
7fd121c93000-7fd121e92000 ---p 00100000 00:20 7654                       /lib64/libm-2.19.so
7fd121e92000-7fd121e93000 r--p 000ff000 00:20 7654                       /lib64/libm-2.19.so
7fd121e93000-7fd121e94000 rw-p 00100000 00:20 7654                       /lib64/libm-2.19.so
7fd121e94000-7fd121ea7000 r-xp 00000000 00:20 40595                      /usr/lib64/libudev.so.1.4.0
7fd121ea7000-7fd1220a6000 ---p 00013000 00:20 40595                      /usr/lib64/libudev.so.1.4.0
7fd1220a6000-7fd1220a7000 r--p 00012000 00:20 40595                      /usr/lib64/libudev.so.1.4.0
7fd1220a7000-7fd1220a8000 rw-p 00013000 00:20 40595                      /usr/lib64/libudev.so.1.4.0
7fd1220a8000-7fd1220ee000 r-xp 00000000 00:20 8592                       /lib64/libdbus-1.so.3.8.7
7fd1220ee000-7fd1222ed000 ---p 00046000 00:20 8592                       /lib64/libdbus-1.so.3.8.7
7fd1222ed000-7fd1222ee000 r--p 00045000 00:20 8592                       /lib64/libdbus-1.so.3.8.7
7fd1222ee000-7fd1222ef000 rw-p 00046000 00:20 8592                       /lib64/libdbus-1.so.3.8.7
7fd1222ef000-7fd12230b000 r-xp 00000000 00:20 8294                       /usr/lib64/libnl-3.so.200.18.0
7fd12230b000-7fd12250a000 ---p 0001c000 00:20 8294                       /usr/lib64/libnl-3.so.200.18.0
7fd12250a000-7fd12250c000 r--p 0001b000 00:20 8294                       /usr/lib64/libnl-3.so.200.18.0
7fd12250c000-7fd12250d000 rw-p 0001d000 00:20 8294                       /usr/lib64/libnl-3.so.200.18.0
7fd12250d000-7fd122512000 r-xp 00000000 00:20 8298                       /usr/lib64/libnl-genl-3.so.200.18.0
7fd122512000-7fd122712000 ---p 00005000 00:20 8298                       /usr/lib64/libnl-genl-3.so.200.18.0
7fd122712000-7fd122713000 r--p 00005000 00:20 8298                       /usr/lib64/libnl-genl-3.so.200.18.0
7fd122713000-7fd122714000 rw-p 00006000 00:20 8298                       /usr/lib64/libnl-genl-3.so.200.18.0
7fd122714000-7fd12272a000 r-xp 00000000 00:20 40826                      /usr/lib64/libusb-1.0.so.0.1.0
7fd12272a000-7fd122929000 ---p 00016000 00:20 40826                      /usr/lib64/libusb-1.0.so.0.1.0
7fd122929000-7fd12292a000 r--p 00015000 00:20 40826                      /usr/lib64/libusb-1.0.so.0.1.0
7fd12292a000-7fd12292b000 rw-p 00016000 00:20 40826                      /usr/lib64/libusb-1.0.so.0.1.0
7fd12292b000-7fd122940000 r-xp 00000000 00:20 8041                       /lib64/libz.so.1.2.8
7fd122940000-7fd122b3f000 ---p 00015000 00:20 8041                       /lib64/libz.so.1.2.8
7fd122b3f000-7fd122b40000 r--p 00014000 00:20 8041                       /lib64/libz.so.1.2.8
7fd122b40000-7fd122b41000 rw-p 00015000 00:20 8041                       /lib64/libz.so.1.2.8
7fd122b41000-7fd122b83000 r-xp 00000000 00:20 40917                      /usr/lib64/libpcap.so.1.5.3
7fd122b83000-7fd122d82000 ---p 00042000 00:20 40917                      /usr/lib64/libpcap.so.1.5.3
7fd122d82000-7fd122d84000 r--p 00041000 00:20 40917                      /usr/lib64/libpcap.so.1.5.3
7fd122d84000-7fd122d85000 rw-p 00043000 00:20 40917                      /usr/lib64/libpcap.so.1.5.3
7fd122d85000-7fd122d86000 rw-p 00000000 00:00 0
7fd122d86000-7fd122f24000 r-xp 00000000 00:20 7646                       /lib64/libc-2.19.so
7fd122f24000-7fd123124000 ---p 0019e000 00:20 7646                       /lib64/libc-2.19.so
7fd123124000-7fd123128000 r--p 0019e000 00:20 7646                       /lib64/libc-2.19.so
7fd123128000-7fd12312a000 rw-p 001a2000 00:20 7646                       /lib64/libc-2.19.so
7fd12312a000-7fd12312e000 rw-p 00000000 00:00 0
7fd12312e000-7fd123146000 r-xp 00000000 00:20 7674                       /lib64/libpthread-2.19.so
7fd123146000-7fd123345000 ---p 00018000 00:20 7674                       /lib64/libpthread-2.19.so
7fd123345000-7fd123346000 r--p 00017000 00:20 7674                       /lib64/libpthread-2.19.so
7fd123346000-7fd123347000 rw-p 00018000 00:20 7674                       /lib64/libpthread-2.19.so
7fd123347000-7fd12334b000 rw-p 00000000 00:00 0
7fd12334b000-7fd12334e000 r-xp 00000000 00:20 7652                       /lib64/libdl-2.19.so
7fd12334e000-7fd12354d000 ---p 00003000 00:20 7652                       /lib64/libdl-2.19.so
7fd12354d000-7fd12354e000 r--p 00002000 00:20 7652                       /lib64/libdl-2.19.so
7fd12354e000-7fd12354f000 rw-p 00003000 00:20 7652                       /lib64/libdl-2.19.so
7fd12354f000-7fd123563000 r-xp 00000000 00:20 7676                       /lib64/libresolv-2.19.so
7fd123563000-7fd123762000 ---p 00014000 00:20 7676                       /lib64/libresolv-2.19.so
7fd123762000-7fd123763000 r--p 00013000 00:20 7676                       /lib64/libresolv-2.19.so
7fd123763000-7fd123764000 rw-p 00014000 00:20 7676                       /lib64/libresolv-2.19.so
7fd123764000-7fd123766000 rw-p 00000000 00:00 0
7fd123766000-7fd12377b000 r-xp 00000000 00:20 7656                       /lib64/libnsl-2.19.so
7fd12377b000-7fd12397a000 ---p 00015000 00:20 7656                       /lib64/libnsl-2.19.so
7fd12397a000-7fd12397b000 r--p 00014000 00:20 7656                       /lib64/libnsl-2.19.so
7fd12397b000-7fd12397c000 rw-p 00015000 00:20 7656                       /lib64/libnsl-2.19.so
7fd12397c000-7fd12397e000 rw-p 00000000 00:00 0
7fd12397e000-7fd12398c000 r-xp 00000000 00:20 8091                       /usr/lib64/libtalloc.so.2.1.1
7fd12398c000-7fd123b8b000 ---p 0000e000 00:20 8091                       /usr/lib64/libtalloc.so.2.1.1
7fd123b8b000-7fd123b8c000 r--p 0000d000 00:20 8091                       /usr/lib64/libtalloc.so.2.1.1
7fd123b8c000-7fd123b8d000 rw-p 0000e000 00:20 8091                       /usr/lib64/libtalloc.so.2.1.1
7fd123b8d000-7fd123bea000 r-xp 00000000 00:20 9014                       /lib64/libssl.so.1.0.0
7fd123bea000-7fd123de9000 ---p 0005d000 00:20 9014                       /lib64/libssl.so.1.0.0
7fd123de9000-7fd123ded000 r--p 0005c000 00:20 9014                       /lib64/libssl.so.1.0.0
7fd123ded000-7fd123df4000 rw-p 00060000 00:20 9014                       /lib64/libssl.so.1.0.0
7fd123df4000-7fd123fbb000 r-xp 00000000 00:20 9013                       /lib64/libcrypto.so.1.0.0
7fd123fbb000-7fd1241bb000 ---p 001c7000 00:20 9013                       /lib64/libcrypto.so.1.0.0
7fd1241bb000-7fd1241d5000 r--p 001c7000 00:20 9013                       /lib64/libcrypto.so.1.0.0
7fd1241d5000-7fd1241e2000 rw-p 001e1000 00:20 9013                       /lib64/libcrypto.so.1.0.0
7fd1241e2000-7fd1241e6000 rw-p 00000000 00:00 0
7fd1241e6000-7fd12421b000 r-xp 00000000 00:20 57268                      /usr/lib64/freeradius/libfreeradius-radius.so
7fd12421b000-7fd12441a000 ---p 00035000 00:20 57268                      /usr/lib64/freeradius/libfreeradius-radius.so
7fd12441a000-7fd12441b000 r--p 00034000 00:20 57268                      /usr/lib64/freeradius/libfreeradius-radius.so
7fd12441b000-7fd12441c000 rw-p 00035000 00:20 57268                      /usr/lib64/freeradius/libfreeradius-radius.so
7fd12441c000-7fd12441d000 rw-p 00000000 00:00 0
7fd12441d000-7fd12443d000 r-xp 00000000 00:20 7639                       /lib64/ld-2.19.so
7fd1245be000-7fd1245f3000 r--s 00000000 00:12 11568                      /run/nscd/services
7fd1245f3000-7fd124628000 r--s 00000000 00:12 11567                      /run/nscd/dbbDJbUg (deleted)
7fd124628000-7fd124632000 rw-p 00000000 00:00 0
7fd124639000-7fd12463d000 rw-p 00000000 00:00 0
7fd12463d000-7fd12463e000 r--p 00020000 00:20 7639                       /lib64/ld-2.19.so
7fd12463e000-7fd12463f000 rw-p 00021000 00:20 7639                       /lib64/ld-2.19.so
7fd12463f000-7fd124640000 rw-p 00000000 00:00 0
7fd124640000-7fd124648000 r-xp 00000000 00:20 57801                      /usr/bin/radclient
7fd124848000-7fd124849000 r--p 00008000 00:20 57801                      /usr/bin/radclient
7fd124849000-7fd12484a000 rw-p 00009000 00:20 57801                      /usr/bin/radclient
7fd125056000-7fd1251d7000 rw-p 00000000 00:00 0                          [heap]
7fffaef1f000-7fffaef40000 rw-p 00000000 00:00 0                          [stack]
7fffaefa5000-7fffaefa7000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
      4838 Aborted

The same happens if the message cannot be sent to the server. After the 3rd attempt, the program exits with the same error.

Does someone know why this is happening or if this is a known bug?

Thanks!

**Comment by alandekok** [comment]
3.0.3 is many months old.  We're not going to debug issues which have been found an fixed months ago.

Try again with 3.0.8.  If it's still a problem, please open a new issue.  Otherwise, the problem was alreay solved.
