### ISSUE TITLE
unexpected radclient change of behaviour (3.0.x)

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1041]
hi,

with the 3.0.8 radclient, when doing eg

echo "Message-Authenticator = 0x00, FreeRADIUS-Statistics-Type = 1" |radclient -t 3 -r 1 remote.server:1812 status super_secret 

we only get this output:

Sent Status-Server Id 84 from 0.0.0.0:33363 to 192.168.1.1:1812 length 50
	Message-Authenticator = 0x00
	FreeRADIUS-Statistics-Type = Authentication

(unlike 2.2.x where you get the stats...and not the debug...)

however, if you add -x (for debug) to 3.0.8  you then get the stats (Reply-Message attributes) AND also the debug. was/is this a deliberate change in behaviour??

also, 

radclient -v

output nothing (unlike 2.2.x where is prints the version...)

you have to do 

radclient -x -v

alan

**Comment by arr2036** [comment]
Did you check v3.0.x HEAD, I think this is already fixed?

**Comment by arr2036** [comment]
with the status-server case, yes, outputting the contents of the request was deliberate (if that was your issue). Are you saying that the server is no longer returning statistics?

**Comment by alandekok** [comment]
On Jun 9, 2015, at 2:33 PM, Alan Buxey <notifications@github.com> wrote:
> radclient -v
> 
> output nothing (unlike 2.2.x where is prints the version...)
> 
> you have to do
> 
> radclient -x -v

  I don't see this in v3.0.x head.

**Comment by alanbuxey** [comment]
i'll verify the HEAD behaviour...or try to:

git clone git@github.com:FreeRADIUS/freeradius-server.git
Initialized empty Git repository in /usr/src/freeradius-server/.git/
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by alandekok** [comment]
$ git clone https://github.com/FreeRADIUS/freeradius-server.git

  This is a standard github issue...

**Comment by alanbuxey** [comment]
right....worth updating the GIT document on http://freeradius.org/git/ ?

**Comment by alanbuxey** [comment]
confirmed that the -v works without debug having to also be flagged (3.0.9 (git #1d9fa92) )... however, the previous output behaviour is no longer present (VSA/TLV being printed out).  also, in debug mode, the VSA/TLV are now printed out with ' quotes rather than " quotes.  not sure of the reason for that change but our scripts have had to be changed to accommodate this change of output.

**Comment by ruyrybeyro** [comment]
hi,

Not only that, strings in detail files also changed from " to ', and we
also changed our PT federation scripts to deal with that.

On 9 June 2015 at 23:06, Alan Buxey <notifications@github.com> wrote:

> confirmed that the -v works without debug having to also be flagged (3.0.9
> (git #1d9fa92) )... however, the previous output behaviour is no longer
> present (VSA/TLV being printed out). also, in debug mode, the VSA/TLV are
> now printed out with ' quotes rather than " quotes. not sure of the reason
> for that change but our scripts have had to be changed to accommodate this
> change of output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeRADIUS/freeradius-server/issues/1041#issuecomment-110518922>
> .
>



-- 
Regards,

--
Rui Ribeiro
Senior Sysadm
ISCTE-IUL
https://www.linkedin.com/pub/rui-ribeiro/16/ab8/434

**Comment by arr2036** [comment]
' is the correct quoting.

**Comment by arr2036** [comment]
sounds like everything is fixed in 3.0.9 anyway? so closing this issue...
