### ISSUE TITLE
Add callback validation in the CONF_PARSER 

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1042]
Hi,

I would like to suggest a new field in the CONF_PARSER, that could be a callback used to validate the expected field.

My idea is:

1) Add a new datatype like "conf_parser_validator_t" in the conffile.h

e.g: typedef bool (*conf_parser_validator_t)(void *data);

2) Add the new field "cb_validate" in the  CONF_PARSER, It will be NULL by default. but when not null will be called to validate the "*data".

3) @alandekok , if you blessed the idea, where you prefer to call the callback?

p.s1: I have talked with @arr2036 and he told me to ask you @alandekok. What do you think? blessed the idea?

ps2:The reason & motivation of this. because, I got a terrible problem during the setup of rlm_redis with the field "server" filled with blank-space at end of line. And if we had the possibility/option to validate the fields in the CONF_PARSER. Certainly could improve validations!

**Comment by alandekok** [comment]
That's a lot of work, and a lot of changes.  It means every single CONF_PARSER entry would change.  And that most CONF_PARSER entries would need a validation function... and the validation functions would be small.  i.e. ~5-8 lines each.

  I'm not inclined to add ~300 5 line functions.  The current method isn't perfect, but is a reasonable compromise.

**Comment by jpereira** [comment]
@alandekokI get it your points. But, I believe that at first we can set all entries to NULL. And the validation It will be made on demand. 

first step:

1) Add the new field in the CONF_PARSER
2) Add the ", NULL " in end of CONF_PARSER $module_config[]" declaration each modules.

And.... the validation it will be made in the course of time. In this case, we have less changes.

**Comment by alandekok** [comment]
Sure, but try doing:

    git grep _BOUND_CHECK src/ 

 You'll get 46 uses.  Many of which will become new 5 line functions.  That's less efficient than the current method, TBH.

**Comment by jpereira** [comment]
interesting...

So, the other way will be create something like FR_HOSTNAME_BOUND_CHECK, and call where receive fields like 'hostname'?

**Comment by arr2036** [comment]
Sure. Though for that particular case we could just mark the field as PW_TYPE_IPADDR and have the server perform DNS resolution, and write the IP address to instance data.

**Comment by jpereira** [comment]
@arr2036 The PW_TYPE_IPADDR support only IP address, I can't use a FQDN.

**Comment by arr2036** [comment]
That's not true. See cf_item_parse and the PW_TYPE_IPV4_ADDR case (it used to be called PW_TYPE_IPADDR), it calls fr_pton4 with the resolve argument set to true, which means fr_pton4 will use inet_hton to resolve a hostname to an IPv4 address.

The type for both address families is PW_TYPE_COMBO_IP_ADDR,  which also has the option to resolve a string to an IP address, but will produce either IPv4 or IPv6 addresses depending on the records available.

**Comment by arr2036** [comment]
If it's not working how I described, then it's a bug as we should look at that...

**Comment by jpereira** [comment]
@arr2036  I will check!
