### ISSUE TITLE
mod_auth_radius segmentation fault.

### ISSUE THREAD

**Issue by research4545** [FreeRADIUS/freeradius-server#1056]
hi, 
I am having some issues with mod_auth_radius causing apache2 to segmentation fault.
after some successful authentication (via basic_auth) i get a segmentation fault error:

```
[debug] mod_auth_radius-2.0.c(1216): no cookie found. Trying RADIUS authentication.\n
[notice] child pid 2267 exit signal Segmentation fault (11)
```

i used apache2.2.22-13 with libapache2-mod-auth-radius1.5.8-1.1 on Debian 7.7.
restart service and rebooting system didn't solve my problem.

**Comment by arr2036** [comment]
This is not a freeradius-server issue, please open a ticket in the correct issue tracker.
