### ISSUE TITLE
Radius Daemon dies at segfault at 31322d72

### ISSUE THREAD

**Issue by acarames** [FreeRADIUS/freeradius-server#1065]
Hello,

We saw a strange behavior on one of our customers server.
It seems that the freeradius Daemon dies after the following error message:

The /var/log/messages output looks as follows:

 Jun 13 15:21:25 ckpng-isarflow1 kernel: [24902698.528501]
radiusd[23025]: segfault at 31322d72 ip 00007f002bd50e8e sp
00007fff7f0b9f70 error 4 in
libfreeradius-radius-2.1.1.so[7f002bd39000+20000]

the radius.log stat output below:

stat radius.log
  File: `radius.log'
  Size: 222120          Blocks: 440        IO Block: 4096   regular file
Device: fd02h/64770d    Inode: 268797647   Links: 1
Access: (0640/-rw-r-----)  Uid: (  111/ radiusd)   Gid: (  114/ radiusd)
Access: 2015-06-22 07:15:27.465587389 +0000
Modify: 2015-06-13 15:21:14.683273139 +0000
Change: 2015-06-13 15:21:14.683273139 +0000
 Birth: -

We use SuSE SLE 11 path 3 and the freeradius server version is:

rpm -qa |grep freeradius
freeradius-server-2.1.1-7.16.7
freeradius-server-utils-2.1.1-7.16.7
freeradius-server-doc-2.1.1-7.16.7
freeradius-server-libs-2.1.1-7.16.7

So it seems  that the radius Daemon dies after that segfault issue.

We would like to know if this version of freeradius is affected by the
following:
bug#810605 Segfault with freeradius-perl threading

And if our error message is a behavior related to the above BUG.

Best regards,

Alberto

**Comment by arr2036** [comment]
We won't investigate this until you can reproduce it with a 3.0.x version. 2.2.x is now security fix only, and that version is many years out of date.

**Comment by alandekok** [comment]
Really? 2.1.1?  Why are you wasting our time with this?  It's 5 years old, and there have been many stable versions released since then.

> We saw a strange behavior on one of our customers server.

If you're getting paid to support the server, then *you* should fix it.  Don't expect us to help you for free.

**Comment by arr2036** [comment]
Regarding the version, you're welcome to grep through the release notes...

**Comment by acarames** [comment]
Hi,

how can I get a greater detail from the logs.
In other words how can I revving the log level???

Please need some kind of help, since it is not so easy to make an upgrade of this part of the software due the critical mission of this server...

thanks.

**Comment by acarames** [comment]
Hi,

I also would like tto know if I upgrade from 2.1.1 to 2.2.x if their where greater changes in the conf files.

Or what I have to care of, before I made such a change.

Thanks,

Alberto

**Comment by alanbuxey** [comment]
2.1.1 to 2.2.x can be doe via just a new version upgrade... no need to
change configuration files... however, if you do that then you will miss
all the new features as you'll have config files that dont mention them
 best to take the current configuration and migrate it to a vanilla 2.2.x
install - after all, you ARE being paid support to do this sort of work.
