### ISSUE TITLE
rlm_redis ideas

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1074]
Hi,

I have feeling necessity to have something like a batch queue in the rlm_redis. because sometimes is necessary to PUT a lot of keys... and I guess if we make an option/feature to do like BEGIN, END during the use of them.

We can improve the quantities of calls to redis/server. like the "mass insert"

http://redis.io/topics/mass-insert

What do you think @arr2036 ?

**Comment by arr2036** [comment]
Yes, but v3.1.x only and I was planing to do that anyway to support maintaining multiple indexes. There's no way we can really queue multiple accounting requests for insertion into redis, within the servers.

That's best left to an external script.

**Comment by jpereira** [comment]
May we can do something using the foreach() in the v3.0.x? I can't figure out 'how'! but you are the xlat/Ninja, may could have some idea!

**Comment by arr2036** [comment]
if you want to concatenate multiple commands you can use foreach, sure, but you're still limited to a single request. you can't buffer many requests worth of redis data for insert.

The best way to do this is to implement accounting properly in rlm_redis and not use the xlat. Then you can use hiredise's command buffering features, so only one command packet gets sent to the redis server per request.

**Comment by jpereira** [comment]
I got it! I believe that can be added with a option query_buffered.... using like

```
redis redis_normal {
    server =  redis-intranet.ok
    port = 6379
    database = 1
    pool {
        .......
    }
}

redis redis_async {
    mode_async = true
    server =  redis-intranet.ok
    port = 6379
    database = 2
    pool {
          ...
    }
}
```

And.... using normally the mode 'normal'

```
"%{redis_normal:HSET MyKey0 State true}"
"%{redis_normal:HSET MyKey0 State true}"
```

But when has the 'mod_async' we can do.

```
"%{redis_async:BEGIN}"
"%{redis_async:HSET MyKey0 State true}"
"%{redis_async:HSET MyKey0 State true}"
"%{redis_async:COMMIT}"
```

And.... into the rlm_redis.c catch the 'commands' to use the buffered mode. make sense for you?

**Comment by arr2036** [comment]
> On Jun 26, 2015, at 1:23 PM, Jorge Pereira <notifications@github.com> wrote:
> 
> I got it! I believe that can be added with a option query_buffered.... using like
> 
> redis redis_normal {
>     server =  redis-intranet.ok
>     port = 6379
>     database = 1
>     pool {
>         .......
>     }
> }
> 
> redis redis_async {
>     mode_async = true
>     server =  redis-intranet.ok
>     port = 6379
>     database = 2
>     pool {
>           ...
>     }
> }
> 
> And.... using normally the mode 'normal'
> 
> "%{redis_normal:HSET MyKey0 State true}"
> "%{redis_normal:HSET MyKey0 State true}"
> 
> But when has the 'mod_async' we can do.
> 
> "%{redis_async:BEGIN}"
> "%{redis_async:HSET MyKey0 State true}"
> "%{redis_async:HSET MyKey0 State true}"
> "%{redis_async:COMMIT}"
> 
> And.... into the rlm_redis.c catch the 'commands' to use the buffered mode. make sense for you

That won't work. The connection is released every time the xlat finishes executing. There's no guarantee you'll get the same connection handle for each of the xlat calls.

You could check libhiredis and see if there's any kind of command delimitation char.

-Arran

**Comment by alandekok** [comment]
The issue is that the connections are used per request.  In order to do something like this, we�d have to modify the connection pool API.  So that there were �get� and �release� function callbacks.  The rlm_redis code could then do:

get() - check if it�s the first use, if so do �BEGIN�
     otherwise, increment usage counter

release() if counter is greater than X, do �COMMIT�

  BUT that will work only if all uses of the connection pool are for the *same* query.  If the queries are different, then all bets are off�

  This may be useful, but there may be dangerous side effects.  We�d need to be *very* sure that it works correctly all of the time before enabling it.

**Comment by arr2036** [comment]
Yeah you have to have a failsafe to ensure any connection bound to the request is released if the connection is freed

**Comment by arr2036** [comment]
Easier just to write the whole transaction in one xlat format string

**Comment by jpereira** [comment]
@alandekok  This is the EXACTLY idea!

**Comment by arr2036** [comment]
@jpereira it's an unnecessary and overly complicated idea.

**Comment by jpereira** [comment]
If my setup get problems with a lot of swapping between radius and another points of system... I will try to fork the rlm_redis and create a rlm_redisbuffered with the idea. But this will be my LAST way.... btw, thanks guys!

**Comment by jpereira** [comment]
@arr2036 I saw only now. I can run like:

```
myvar += "HSET MyKey0 State true;"
myvar += "HSET MyKey2 State true;"
myvar += "HSET MyKey2 State true;"
```

and 

```
"%{redis_async:%{myvar}}"
```

?

**Comment by arr2036** [comment]
No idea, I was saying to check libhiredis to see if it had a command delimiter :)

**Comment by jpereira** [comment]
@arr2036 haha! I misunderstood! :+1:
