### ISSUE TITLE
FreeRADIUS 1.1.8 not around

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1102]
hi,

i know...its old...move on... but the web page:

http://freeradius.org/download.html

says 1.1.8 was the last 1.1.x release.....and if you go to 

http://freeradius.org/getting.html

its listed..... but it doesnt exist at all in the 

ftp://ftp.freeradius.org/pub/freeradius/old/

directory

cheers

alan

**Comment by alandekok** [comment]
It's in ftp://ftp.freeradius.org/pub/freeradius/
