### ISSUE TITLE
The field 'nas' isn't filled in the %{client:nas_type}

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1108]
Hi,

 I have tried to use the field 'nas' (nas_type), but have had no success when loaded from SQL.

tried

```
 "%{client:nas_type}"
 "%{control:FreeRADIUS-Client-NAS-Type}"
 "%{request:FreeRADIUS-Client-NAS-Type}"
```

below some evidences.

```
Tue Jun 30 20:39:39 2015 : Debug: %{client:nas_type}
Tue Jun 30 20:39:39 2015 : Debug: Parsed xlat tree:
Tue Jun 30 20:39:39 2015 : Debug: xlat --> client
Tue Jun 30 20:39:39 2015 : Debug: {
Tue Jun 30 20:39:39 2015 : Debug:       literal --> nas_type
Tue Jun 30 20:39:39 2015 : Debug: }
Tue Jun 30 20:39:39 2015 : Debug: (0)     EXPAND %{client:nas_type}
Tue Jun 30 20:39:39 2015 : Debug: (0)        -->
Tue Jun 30 20:39:39 2015 : Debug: %{control:FreeRADIUS-Client-NAS-Type}
Tue Jun 30 20:39:39 2015 : Debug: Parsed xlat tree:
Tue Jun 30 20:39:39 2015 : Debug: attribute --> FreeRADIUS-Client-NAS-Type
Tue Jun 30 20:39:39 2015 : Debug: (0)     EXPAND %{control:FreeRADIUS-Client-NAS-Type}
Tue Jun 30 20:39:39 2015 : Debug: (0)        -->
Tue Jun 30 20:39:39 2015 : Debug: %{request:FreeRADIUS-Client-NAS-Type}
Tue Jun 30 20:39:39 2015 : Debug: Parsed xlat tree:
Tue Jun 30 20:39:39 2015 : Debug: attribute --> FreeRADIUS-Client-NAS-Type
Tue Jun 30 20:39:39 2015 : Debug: (0)     EXPAND %{request:FreeRADIUS-Client-NAS-Type}
Tue Jun 30 20:39:39 2015 : Debug: (0)        -->
```

**Comment by jpereira** [comment]
just to register. I will try to fix it.

**Comment by alandekok** [comment]
If it's not being expanded, it's because there's no "nas_type" in the "client" section.

**Comment by jpereira** [comment]
@alandekok If there has the "%{client:shortname}", I guess that could have the "%{client:nas_type}". the problem is only when is loaded from SQL... may be during the set of section '%{client:}'

I have talked with @arr2036 and the suspect is in client_afrom_query.

**Comment by arr2036** [comment]
Yeah the code's not there. It needs fixing. client_afrom_query needs to die, should use the same mechanism as all the other modules that provide dynamic clients. 

It'd actually be nice to redo it as a mapping section. It'd be more flexible that the current position based code. Then you could define arbitrary clients in SQL, like you can with couchbase.
