### ISSUE TITLE
Show the path of object magic number mismatch

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1113]
Hi,

I think that we can improve the error messages during " like below example.

```
/etc/raddb/mods-enabled/always[35]: Application and rlm_always magic number (version) mismatch.  application: 30008 module: 30004
```

could be better to show the complete path of module rlm_always.so

**Comment by arr2036** [comment]
We don't know the complete path to rlm_always.so?

**Comment by arr2036** [comment]
http://pubs.opengroup.org/onlinepubs/9699919799/

There's no way to get the path of the .so if we didn't specifying it using an absolute path

**Comment by jpereira** [comment]
during the build we have the paths.... we can assume that $prefix/freeradius/lib/ .... something like that. what do you think?

**Comment by jpereira** [comment]
@arr2036 I think that the address handler should be found in /proc/<pid>/map_files I am not sure!

**Comment by alandekok** [comment]
On Jul 2, 2015, at 3:24 PM, Jorge Pereira <notifications@github.com> wrote:
> during the build we have the paths.... we can assume that $prefix/freeradius/lib/ .... something like that. what do you think?

  The dynamic linker searches many paths at run time.  Printing a *wrong* message is bad.  It's better to have *no* message about paths.

**Comment by arr2036** [comment]
Agreed. The best we could do, is if libdir was specified in radiusd.conf, and the dlopen succeeded on the first call (with the full path), we could indicate that, otherwise indicate that the shared object had been loaded using the search path.

Assuming dlopen doesn't do something completely stupid and use its search path anyway, even will a full path.

**Comment by jpereira** [comment]
@alandekok and @arr2036. The name is ```dladdr()```, is the guy that we want to use!

e.g:

```
void say_myname(void) {
    Dl_info dl_info;
    dladdr((void *)say_myname, &dl_info);
    fprintf(stderr, "module %s loaded\n", dl_info.dli_fname);
}
```

**Comment by arr2036** [comment]
It's not POSIX, please add autoconf checks.

**Comment by alandekok** [comment]
It's available on Linux and *BSD.  So that's good enough for now.

**Comment by jpereira** [comment]
in MacOSx also!

**Comment by arr2036** [comment]
Because OSX is BSD :P
