### ISSUE TITLE
The rlm_redis could provide a log_file option

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1114]
Hi,

The rlm_redis could provide a log_file option like found in the rlm_sql. this could be
great to help the depuration.

**Comment by arr2036** [comment]
Sure, feel free to write the code for v3.1.x.  It's not very complex.

**Comment by jpereira** [comment]
It should be closed as it was refused in https://github.com/FreeRADIUS/freeradius-server/pull/3932
