### ISSUE TITLE
The rlm_rest could return a attr "REST-HTTP-Code" with last http request.

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1115]
Hi @arr2036,

As we talked, the idea is that rlm_rest set the attribute "REST-HTTP-Status" with the last status of HTTP request. this could be nice to better handler of error messages during rest request.

**Comment by arr2036** [comment]
It could, pleas send a pull request :)

**Comment by jpereira** [comment]
@arr2036 done! :beer:
