### ISSUE TITLE
libpam-radius-auth should pass on current password even on success

### ISSUE THREAD

**Issue by dorchain** [FreeRADIUS/freeradius-server#1132]
Hello,

In order to be able to stack libpam-radius-auth with other
modules (e.g. for challenging the same password with multiple
modules), libpam-radius-auth needs to pass on the current
password not only on failure, but also on success.

Trivial patch included. Thanks for considering.

Bye,

Joerg

--- pam_radius_auth.c.orig	2015-06-18 11:04:04.000000000 +0200
+++ pam_radius_auth.c	2015-06-18 11:04:46.000000000 +0200
@@ -1201,13 +1201,13 @@
     retval = PAM_SUCCESS;
   } else {
     retval = PAM_AUTH_ERR;	/* authentication failure */
+  }
 
   error:
     /* If there was a password pass it to the next layer */
     if (password && *password) {
       pam_set_item(pamh, PAM_AUTHTOK, password);
     }
-  }
 
   if (ctrl & PAM_DEBUG_ARG) {
     _pam_log(LOG_DEBUG, "authentication %s"

**Comment by alandekok** [comment]
This really should be an issue in https://github.com/FreeRADIUS/pam_radius.  But I've pushed a fix.

**Comment by dorchain** [comment]
On Thu, Jul 09, 2015 at 07:11:59AM -0700, Alan DeKok wrote:
> 
> This really should be an issue in https://github.com/FreeRADIUS/pam_radius.

I am sorry, you are right.

> But I've pushed a fix.

Thanks a lot!

Bye,

Joerg
