### ISSUE TITLE
freeradius 3 checks only first group in radbgroupcheck table

### ISSUE THREAD

**Issue by sinnerkem** [FreeRADIUS/freeradius-server#1136]
Hello.
i'am using freeradius 3.0.4. I've created a user with two group. But when radius checks user's membership and fails to match with attribute at first group , radius doesn't try to check second one. 
This fuctions works well in 2.x version, but doesn't with 3.0.4.
 Any ideas?

MariaDB [radius]> select * from radusergroup;
+----------+-------------+----------+
| username | groupname   | priority |
+----------+-------------+----------+
| admin    | REJECT      |        3 |
| admin    | globaladmin |        2 |
+----------+-------------+----------+
2 rows in set (0.01 sec)

MariaDB [radius]> select * from radgroupcheck;
+----+-------------+----------------+----+--------+
| id | groupname   | attribute      | op | value  |
+----+-------------+----------------+----+--------+
|  1 | globaladmin | NAS-IP-Address | =~ | ^172   |
|  2 | REJECT      | Auth-Type      | := | Reject |
+----+-------------+----------------+----+--------+
2 rows in set (0.00 sec)

MariaDB [radius]> select * from radgroupreply;
+----+-------------+--------------+----+---------------------+
| id | groupname   | attribute    | op | value               |
+----+-------------+--------------+----+---------------------+
|  2 | globaladmin | Service-Type | =  | Administrative-User |
+----+-------------+--------------+----+---------------------+
1 row in set (0.01 sec)

rlm_sql (sql): Executing query: 'SELECT id, username, attribute, value, op FROM radcheck WHERE                                                                                                        username = 'admin' ORDER BY id'
(2)  sql : User found in radcheck table
(2)  sql : Check items matched
(2)  sql : EXPAND SELECT id, username, attribute, value, op FROM radreply WHERE username = '%{                                                                                                       SQL-User-Name}' ORDER BY id
(2)  sql :    --> SELECT id, username, attribute, value, op FROM radreply WHERE username = 'ad                                                                                                       min' ORDER BY id
rlm_sql (sql): Executing query: 'SELECT id, username, attribute, value, op FROM radreply WHERE                                                                                                        username = 'admin' ORDER BY id'
(2)  sql : EXPAND SELECT groupname FROM radusergroup WHERE username = '%{SQL-User-Name}' ORDER                                                                                                        BY priority
(2)  sql :    --> SELECT groupname FROM radusergroup WHERE username = 'admin' ORDER BY priorit                                                                                                       y
rlm_sql (sql): Executing query: 'SELECT groupname FROM radusergroup WHERE username = 'admin' O                                                                                                       RDER BY priority'
(2)  sql : User found in the group table
(2)  sql : EXPAND SELECT id, groupname, attribute, Value, op FROM radgroupcheck WHERE groupnam                                                                                                       e = '%{Sql-Group}' ORDER BY id
(2)  sql :    --> SELECT id, groupname, attribute, Value, op FROM radgroupcheck WHERE groupnam                                                                                                       e = 'globaladmin' ORDER BY id
rlm_sql (sql): Executing query: 'SELECT id, groupname, attribute, Value, op FROM radgroupcheck                                                                                                        WHERE groupname = 'globaladmin' ORDER BY id'
rlm_sql (sql): Released connection (4)
rlm_sql (sql): 0 of 1 connections in use.  Need more spares
rlm_sql (sql): Opening additional connection (5)
rlm_sql_mysql: Starting connect to MySQL server
(2)   [sql] = ok
(2)   [expiration] = noop
(2)   [logintime] = noop

[root@localhost ~]# radtest admin XXX 127.0.0.1 1812 testing123
Sending Access-Request Id 178 from 0.0.0.0:59753 to 127.0.0.1:1812
        User-Name = 'admin'
        User-Password = 'XXX'
        NAS-IP-Address = 127.0.0.1
        NAS-Port = 1812
        Message-Authenticator = 0x00
Received Access-Accept Id 178 from 127.0.0.1:1812 to 127.0.0.1:59753 length 20

**Comment by alandekok** [comment]
Read the documentation.  http://wiki.freeradius.org/modules/Rlm_sql
