### ISSUE TITLE
Add string replace mechanism

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1140]
Hi guys,

I know that we can do the replacement using regex/temp variable. But, I would like to suggest to create a extend the xlat to support something like: 

```
%{VARIABLE/old_string/new_string}

%{VARIABLE//old_string/new_string} #double slash will be all matches.
```

Something like found in the bash[1]. what do you think?

[1] http://tldp.org/LDP/abs/html/string-manipulation.html

**Comment by arr2036** [comment]
Take a look at the xlat code and see if your proposed scheme would work

**Comment by alandekok** [comment]
I'm inclined to avoid re-implementing "sed".    But if we do, it should re-implement sed, and not something else.

**Comment by jpereira** [comment]
@alandekok I think that can be followed the idea of string-replace of Bash. sounds like more fit, what do you think?

**Comment by jpereira** [comment]
@alandekok I don't know if you like the idea. But we can based on mod_sed from apache. https://github.com/omnigroup/Apache/tree/master/httpd/modules/filters and create a new rlm_sed...

**Comment by arr2036** [comment]
We used to have and attr rewrite module which could do string substitution.  It was a PITA to configure and difficult to understand.

If we don't want to write it into unlang it fits best in xlat with something like:

``"%{edit:<input> ([s]|[tr])/fo(o)/bar\1/[gi]}"``. 

Hopefully all the fixes made to escapes means that ``\1`` won't be messed with.

**Comment by arr2036** [comment]
Input in this case is either an expansion or an attribute

**Comment by arr2036** [comment]
Googling reveals no library that implements all the sed commands, so probably best we just emulate what perl does.

**Comment by arr2036** [comment]
Still doesn't work with strings containing embedded nulls though, which might break @jpereira's unstated use case. Guess we'll just have to fix the xlat code.

**Comment by jpereira** [comment]
I like your idea @arr2036. about the library, i think that the mechanism used by Apache is very nice. I guess that could become in a library and we can use.

**Comment by arr2036** [comment]
Picking out the APR bits would be a significant amount of work.

**Comment by jpereira** [comment]
@arr2036 agree with you. but, in this case will be rlm_edit?

**Comment by arr2036** [comment]
No, we only add new modules if the xlats being registered need to be configured, in this case an edit xlat wouldn't take any configuration.

**Comment by jpereira** [comment]
Ok, I got it!

**Comment by arr2036** [comment]
This is done! Woohoo! See ``%{sub:/<regex>/[flags] <replace> <subject>}``

**Comment by jpereira** [comment]
Omg @arr2036, it was 2015!
