### ISSUE TITLE
Better SQL printer

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1142]
Hi,

   We can improve the SQL print-debug using some mechanism like http://stackoverflow.com/questions/5939613/format-sql-query-in-c. this should solve the bad printing of '\\' back-slashes.

This is very useful when may you have problems in a query.

**Comment by arr2036** [comment]
can you expand on this? Is there a function we should be calling or do you just want to print out the SQL statements in a formatted way?

**Comment by arr2036** [comment]
Going to close this, if you remember what it was about, please feel free to re-open :)
