### ISSUE TITLE
Problems with server as listen::type=detail

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1149]
Hi,

I tried to use the example "site-available/buffered-sql" that the option filename point to the destination with not-exactly path. (my acct/detail files in */var/log/freradius/radacct/[nas-ip]/detail-yyyyddmm*)

e.g: 

```
# grep -v -E "^(.*#|$)" sites-available/buffered-sql-accounting
server buffered-sql-accouting {
        listen {
                type = detail
                filename = "${radacctdir}/*/detail-*"
                load_factor = 10
                poll_interval = 300
                retry_interval = 30
        }
        preacct {
        }
        accounting {
                -sql_accounting
        }
}
#
```

And during try to use the buffered-sql, I get this messages.

```
Thu Jul 16 22:33:17 2015 : Debug: Listening on detail file /var/log/freeradius/radacct/*/detail-* as server buffered-sql-accouting
Thu Jul 16 22:33:17 2015 : Debug: Listening on status address 127.0.0.1 port 18121 bound to server status
Thu Jul 16 22:33:17 2015 : Debug: Opening new proxy socket 'proxy address * port 0'
Thu Jul 16 22:33:17 2015 : Debug: Listening on proxy address * port 37007
Thu Jul 16 22:33:17 2015 : Info: Ready to process requests
Thu Jul 16 22:33:17 2015 : Debug: detail (/var/log/freeradius/radacct/*/detail-*): Polling for detail file
Thu Jul 16 22:33:17 2015 : Debug: detail (/var/log/freeradius/radacct/*/detail-*): Renaming /var/log/freeradius/radacct/10.1.2.128/detail-20150622 -> /var/log/freeradius/radacct/*/detail.work
Thu Jul 16 22:33:17 2015 : Error: detail (/var/log/freeradius/radacct/*/detail-*): Failed renaming /var/log/freeradius/radacct/10.1.2.128/detail-20150622 to /var/log/freeradius/radacct/*/detail.work: No such file or directory
Thu Jul 16 22:33:17 2015 : Debug: detail (/var/log/freeradius/radacct/*/detail-*): Detail listener state unopened waiting 5.248880 sec

```

I believe that during set of destination file detail.work is necessary to call dirname() in the source file /var/log/freeradius/radacct/10.1.2.128/detail-20150622

**Comment by alandekok** [comment]
OK... the issue is that filename_work is created from the input filename... which may contain `*`

The solution is to create filename_work from the filename we got from glob()

**Comment by jpereira** [comment]
@alandekok I believe that this isn't the best way. because the idea of buffered-sql isn't compatible with the strategy of "detail" using glob/xlat parameters.

**Comment by jpereira** [comment]
Come on @alandekok, Let's fix that! :+1:

**Comment by alandekok** [comment]
Yes, the buffered sql is compatible with using glob().  The only issue (and this is documented) is that all of the detail files *must* be in the same directory

allowed:
    foo/bar/detail-*

disallowed:
    foo/*/detail

**Comment by jpereira** [comment]
You agree with the support for "foo/*/detail-*"? If yes, i will fix it.
