### ISSUE TITLE
FreeRadius 3.0.9 tries to open more and more sockets for proxy server until crash

### ISSUE THREAD

**Issue by serge-komaroff** [FreeRADIUS/freeradius-server#1155]
Hello,

FreeRadius 3.0.9 builded from a source on CentOS 6 and FreeBSD tries to open more and more sockets for udp connections to proxy CoA messages.

Log part:
<B>Info:  ... adding new socket proxy address * port 47837</B>
<B>Info:  ... adding new socket proxy address * port 39518</B>

Then I can monitor connections with this:
 netstat -na | grep udp | wc -l

number slowly goes up and with load it happen faster and faster. As soon as the number overcome 256 FreeRadius quits from running with this error:

<B>Error: Failed adding event handler for socket: Too many readers</B>

If anyone could make a patch to 3.0.9 I will be happy. 
Thank you in advance for your help!

Best Regards, Serge Komaroff

I'm using 1500 clients and CoA home servers in configuration like this:

```
#clients.conf

client wlc_174 {
        ipaddr = 10.56.33.174
        $template client_wlc
        coa_server = wlc_174
}

client wlc_190 {
        ipaddr = 10.56.33.190
        $template client_wlc
        coa_server = wlc_190
}

   ....................
```

```
#proxy.conf


home_server wlc_174 {
        ipaddr = 10.56.33.174
        $template home_server
}

home_server wlc_190 {
        ipaddr = 10.56.33.190
        $template home_server
}
          ................................
home_server_pool 10.56.33.174 {
        home_server = wlc_174
        }

home_server_pool 10.56.33.190 {
        home_server = wlc_190
        }
        ...................................
```

```
#templates.conf

client_wlc {
                secret = secret
                nas_type = cisco
        }

home_server {
        type = coa
        port = 1700
        secret = ctrhtn
        require_message_authenticator = no
        response_window = 10
        zombie_period = 40
        revive_interval = 120
        status_check = none
        check_interval = 60
        num_answers_to_alive = 1
                coa {
                    irt = 2
                    mrt = 5
                    mrc = 5
                    mrd = 10
                    }
        }

```

```
#sites/enabled coa

listen {
        type = coa
        ipaddr = *
        port = 3799
        virtual_server = coa
}

server coa {
        #  When a packet is received, it is processed through the
        #  recv-coa section.  This applies to *both* CoA-Request and
        #  Disconnect-Request packets.
        recv-coa {
                #  CoA && Disconnect packets can be proxied in the same
                #  way as authentication or accounting packets.
                #  Just set Proxy-To-Realm, or Home-Server-Pool, and the
                #  packets will be proxied.

                #  Do proxying based on realms here.  You don't need
                #  "IPASS" or "ntdomain", as the proxying is based on
                #  the Operator-Name attribute.  It contains the realm,
                #  and ONLY the realm (prefixed by a '1')
                suffix
                update control {
                        Home-Server-Pool := &NAS-IP-Address
                        }
                ok
                }

        #  When a packet is sent, it is processed through the
        #  recv-coa section.  This applies to *both* CoA-Request and
        #  Disconnect-Request packets.
        send-coa {
                #  Sample module.
                ok
        }
}
```

P.S. Second issue I have and I can't avoid is: I can't send CoA proxy packets to Dst-IP / Dst-Port in case if home server in configuration or not - doesn't matter FR sends packet to default CoA port only or to random port instead of defined by Dst-Port section. But this issue is not so critical as first one.

**Comment by serge-komaroff** [comment]
Same with 3.0.10...

**Comment by jpereira** [comment]
@serge-komaroff could you please follow the steps describe in http://wiki.freeradius.org/project/bug-reports and paste the output of "bt" command into the gdb?

**Comment by jpereira** [comment]
@serge-komaroff if possible, you can fetch the HEAD from branch v3.0.x and apply this patch [1] whose proposal to display the error messages.

[1] https://github.com/FreeRADIUS/freeradius-server/pull/1169

**Comment by serge-komaroff** [comment]
Hello!


Will do my best to try and report back to you about results. Thank you for
your help!


Regards, Serge Komaroff

**Comment by arr2036** [comment]
I don't currently have time to look at defects, and Alan is AFK for an extended time.

If you want an immediate workaround you can use something like this to call out to radclient:

```
redundant {
	group {
		update request {
			&Tmp-String-0 := `/bin/sh -c "/bin/echo 'NAS-IP-Address = %{control:NAS-IP-Address}, Alc-Subsc-ID-Str = %{control:Alc-Subsc-ID-Str}' | /usr/bin/radclient -r 1 -t 1 %{control:NAS-IP-Address}:3799 disconnect %{getclient:%{control:NAS-IP-Address}.secret}"`
		}
	}
	ok
}
```

**Comment by alandekok** [comment]
Please try v3.0.x.  I've put in commit edfefde62e78 which helps for me.

**Comment by alandekok** [comment]
Please try this again.  Unless you say it's fixed, I will close the issue soon.

**Comment by serge-komaroff** [comment]
Hello Alan,

Unfortunately I can't check it right now, I was forced to use some workaround so I do external CoA sender. Anyway I hope it will help a lots of people. Let's close the issue.Thank you for your help! 
In case you would visit Moscow I'm indebted. )

Serge
