### ISSUE TITLE
Weird behaviour for [#]

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#1171]
Expected to get last attribute, but that's not implemented for attribute references.

Did multivalued comparison instead. Should error out if [#] is found in attribute ref.

**Comment by alandekok** [comment]
Attribute references start at 0.  So for 3 attributes, they're addresses as [0], [1], [2].  And [#] == 3.

So you can't get the last attribute that way. :(

**Comment by arr2036** [comment]
Attribute refs can't produce new values (like xlats can), I tried once, and it ugglied up the code significantly.  So in this case [#] could mean the last instance of the attribute.  If we don't support that, then we should catch the use of [#] for attribute refs and error out.

**Comment by arr2036** [comment]
Ah I added ``[n]`` for last attribute :)

**Comment by arr2036** [comment]
We should still error out instead of doing weird shit..
