### ISSUE TITLE
Issue with radius_db connection string for rlm_sql_postgresql

### ISSUE THREAD

**Issue by kbirkeland** [FreeRADIUS/freeradius-server#1172]
In mods-available/sql, the docs state:

        # If you're using postgresql this can also be used instead of the connection info parameters
    #   radius_db = "dbname=radius host=localhost user=radius password=raddpass"

However, this is not the current behavior as of 3.0.9.  If radius_db is defined but host is not defined, the default value of "host='localhost'" will be appended to the end of the connection string.  This causes the connection to fail if the user specified a remote host in radius_db.  

For example:

    radius_db = "dbname=radius host=10.250.250.250 user=radiusd password=<REDACTED> connect_timeout=2"

Produces the following in the debug logs:

    rlm_sql_postgresql: Connecting using parameters: dbname=radius host=10.250.250.250 user=radiusd password=<REDACTED> connect_timeout=2 host='localhost'

This can be remedied by setting host in the connection info parameters, but the docs specifically say radius_db can be used instead of the connection info parameters.  Not sure if the docs are wrong and this is expected behavior or the other way around.

**Comment by arr2036** [comment]
It should have worked, except the rlm_sql code set 'localhost' as the default for the server config item, i've fixed that, and added additional checks to prevent duplicate options being added.

**Comment by arr2036** [comment]
A temporary workaround would be to set ``server = ''``
