### ISSUE TITLE
radclient: Received reply to request we did not send. (id=? socket ?)

### ISSUE THREAD

**Issue by aliquid** [FreeRADIUS/freeradius-server#1177]
Running "radclient -F -x -P tcp 127.0.0.1:18120 auth secret" on FreeRADIUS Version 3.0.9 in jail on FreeNAS (FreeBSD 9.3-RELEASE-p16) getting response;
>Sent Access-Request Id 171 from 127.0.0.1:19352 to 127.0.0.1:18120 length 43
>        User-Name = "foo"
>        User-Password = "bar"
>        Cleartext-Password = "bar"
>Received Access-Accept packet from socket 3, id=27, length=20
>radclient: Received reply to request we did not send. (id=27 socket 3)

which does not make sense, the socket and id are just fine and so are the IP addresses and ports.

Suggested fix, fr_packet_list_find_byreply() in packet.c;
```c
        if (ps->src_any) {
                my_request.src_ipaddr = reply->dst_ipaddr; // was ps->src_ipaddr, crazy imho
        } else {
                my_request.src_ipaddr = ps->src_ipaddr; // was reply->dst_ipaddr
        }
```
What do you think?

Best,
--cb

ps. Seems to be old bug; http://lists.freebsd.org/pipermail/freebsd-jail/2013-November/002458.html ds.

**Comment by alandekok** [comment]
On Aug 4, 2015, at 1:42 AM, aliquid <notifications@github.com> wrote:

> Running "radclient -F -x -P tcp 127.0.0.1:18120 auth secret" in jail on FreeNAS (FreeBSD 9.3-RELEASE-p16) getting response;
> 
> Sent Access-Request Id 171 from 127.0.0.1:19352 to 127.0.0.1:18120 length 43
> User-Name = "foo"
> User-Password = "bar"
> Cleartext-Password = "bar"
> Received Access-Accept packet from socket 3, id=27, length=20
> radclient: Received reply to request we did not send. (id=27 socket 3)
> 
> which does not make sense, the socket and id are just fine and so are the IP addresses and ports.

  Not entirely.  This is FreeBSD, and a jail.  The code THINKS it binds to one address, but in reality, FreeBSD binds the socket to ANOTHER address.  Read src/main/listen.c.  Look for "FreeBSD jail issues".

> Suggested fix, fr_packet_list_find_byreply() in packet.c;
> 
>         if
>  (ps->src_any) {
>                 my_request.
> src_ipaddr = reply->dst_ipaddr; // was ps->src_ipaddr, crazy imho

  a) we're all retarded and this code never worked anywhere

  b) it's a problem specific to your platform.

  Pick one.

>         } 
> else
>  {
>                 my_request.
> src_ipaddr = ps->src_ipaddr; // was reply->dst_ipaddr

  Those addresses should be identical.

>         }
> 
> What do you think?

  I think it's rude to insinuate that people are stupid.

  Please supply a fix for FreeBSD which doesn't break things on other platforms.  In case it wasn't apparent, the server builds (and runs) on non-FreeBSD systems.

**Comment by aliquid** [comment]
Apologizing my rudeness, picking b going forward.

Spent some hours debugging, client_ipaddr is always 0 which is fine for UDP but breaks for TCP in FreeBSD jail. I worked around with below. Your pointer on listen.c sheds light on why it breaks, requesting 0.0.0.0 getting x.x.x.x, and shows that it has alread been worked around on server side (but not on client side).

Theoretical problem with below workaround might be when reading packets from multiple files, in which case there are multiple calls to fr_socket_client_tcp() and if interfaces goes up&down then binding might change and recv_one_packet() is hardwired to the one client_ipaddr. Perhaps always update client_ipaddr, but that felt like a stretch.

But I believe below is good enough for my usecase, and also it is very similar to the already existing workaround that you pointed out which adds comfort. (It is similar but not identical because below checks only for TCP, not UDP since that is working.)

Thnx for your pointer and feedback, appreciate it.

'''
--- src/main/radclient.c.orig   2015-07-08 17:41:25.000000000 +0200
+++ src/main/radclient.c        2015-08-04 13:48:21.810242695 +0200
@@ -1482,7 +1482,21 @@

 #ifdef WITH_TCP
        if (proto) {
+               struct sockaddr_storage src;
+               socklen_t               sizeof_src;
+
                sockfd = fr_socket_client_tcp(NULL, &server_ipaddr, server_port, false);
+
+               sizeof_src = sizeof(src);
+               memset(&src, 0, sizeof_src);
+               if (getsockname(sockfd, (struct sockaddr *) &src,
+                               &sizeof_src) < 0) {
+                       fr_strerror_printf("%s", fr_syserror(errno));
+                       sizeof_src = 0;
+               }
+               if (!fr_sockaddr2ipaddr(&src, sizeof_src, &client_ipaddr, &client_port)) {
+                       fr_strerror_printf("Failed to get IP");
+               }
        } else
 #endif
        sockfd = fr_socket(&client_ipaddr, client_port);
'''

**Comment by alandekok** [comment]
The real solution is to not do src/dst IP/port checking for TCP sockets.  The socket is already bound to a particular set of IPs and ports.  Additional checks and/or work-arounds are pointless.

**Comment by aliquid** [comment]
There's an "int proto" on the struct radius_packet that could be take into consideration by fr_packet_cmp()//packet.c. Another vector would be to set reply->dst_port=-1 in recv_one_packet()//radclient.c (or simply client_port=-1), using that as cue. New flag would probably be safer if proto won't do. Don't know the implications when it comes to inner-tunnel, proxy etc, you know better than me. =)

Anyways, we got my problem solved. Thnx.
