### ISSUE TITLE
DialupAdmin doesn't work with PHP5.5 due to import_request_variables('GPC')

### ISSUE THREAD

**Issue by pappbj** [FreeRADIUS/freeradius-server#1178]
The above mentioned bug exists in the latest version of dialupadmin, is this on the roadmap to get it working with the latest php versions?

Thanks,
Balazs Kovacs

**Comment by alandekok** [comment]
Sure. Feel free to send a patch. 

  We haven't done development for dialup admin for a while now. If it works, great. Otherwise, please send a patch.

**Comment by arr2036** [comment]
Please open this against the dialup admin repo, this is not a freeradius issue.
