### ISSUE TITLE
You probably need to lower \"min\" message in the connection pool is annoying and not useful

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#1182]
'min' is useful as it ensures that a certain number of connections remain open.

In the case of a standby server warning users that they probably need to lower min is wrong.  FreeRADIUS should keep 'min' connections open, so that when a failover event occurs, it can cope with the sudden increase in traffic.

At a minimum I think the min warning should have greater hysteresis than cleanup_delay/cleanup_interval, but i'm for removing the message entirely, or adding a 'pedantic_warnings' option to the connection pool to enable/disable similar such warnings.

Filling the main server log with useless crap when the configuration is correct is the wrong thing to do.

**Comment by alandekok** [comment]
I'm OK with moving the message to be debug-only.
