### ISSUE TITLE
Arbitrary length xlats

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#1185]
We now have to deal with large blocks of text being used as the input to maps.

```text
(1)         Sending HTTP GET to "http://127.0.0.1:8080/wra/accounts/00000000005"
(1)         Processing response header
(1)           Status : 200 (OK)
(1)           Type   : json (application/json)
(1)         ERROR: Insufficient space to write HTTP response, needed 2720 bytes, have 2048 bytes
```

We could keep expanding the buffer size, but allocating 8K on the heap every time we want to call an xlat function seems pretty wasteful.

A simple and easy to implement fix would be:

Change

```c
int		xlat_register(char const *module, xlat_func_t func, xlat_escape_t escape,
			      void *instance);
```

to

```c
int		xlat_register(char const *module, xlat_func_t func, size_t buf_len, xlat_escape_t escape,
			      void *instance);
```

Change xlat_funct_t from

```c
typedef ssize_t (*xlat_func_t)(void *instance, REQUEST *, char const *fmt, char *out, size_t out_len);
```

to

```c
typedef ssize_t (*xlat_func_t)(void *instance, REQUEST *, char const *fmt, char **out, size_t out_len);
```

Where xlat's buf_len > 0, caller allocates buffer of size buf_len, passes pointer to it in out.

Where xlat's buf_len == 0, caller allocates no buffer *out == NULL.  xlat allocates buffer of appropriate size, using request as the context.

Minimal changes required to existing xlat functions.  Allows migration from pre-allocated buffers to variable length buffers over time.

**Comment by arr2036** [comment]
@alandekok feedback today would be appreciated, so I can implement the changes on Monday.  This is currently blocking testing and implementing the config to talk to the customer's API.

**Comment by alandekok** [comment]
I think that's ok. The main goal is minimal changes, and have a migration path to something  better.
