### ISSUE TITLE
Solaris 10 .configure: error: pam_modules.h not found

### ISSUE THREAD

**Issue by larryhollis** [FreeRADIUS/freeradius-server#1186]
configure: WARNING: security/pam_modules.h: present but cannot be compiled
configure: WARNING: security/pam_modules.h:     check for missing prerequisite headers?
configure: WARNING: security/pam_modules.h: see the Autoconf documentation
configure: WARNING: security/pam_modules.h:     section "Present But Cannot Be Compiled"
configure: WARNING: security/pam_modules.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------------- ##
configure: WARNING:     ## Report this to http://bugs.freeradius.org ##
configure: WARNING:     ## ----------------------------------------- ##
checking for security/pam_modules.h... no
checking pam/pam_modules.h usability... no
checking pam/pam_modules.h presence... no
checking for pam/pam_modules.h... no
configure: error: pam_modules.h not found
some how issue got closed, I still have the issue.

**Comment by arr2036** [comment]
1) This has been opened against the freeradius-server repo, not the pam repo. https://github.com/FreeRADIUS/pam_radius/issues
2) No one on the development team has a solaris box.  So there's not a whole lot we can do to help.  Check config.log to see exactly why autoconf thinks the headers are bad.
