### ISSUE TITLE
Session-Timeout not returned in Access-Accept msg

### ISSUE THREAD

**Issue by miondrek** [FreeRADIUS/freeradius-server#1199]
Hi All,
I am testing FreeRadius-2.1.12-6.el6.i686 with Aruba controller and according wireshark data it looks like that Radius is not sending session timeout attribute in Access-Accept msg for 802.1x EAP TLS users (it send this info just in first Access-Challenge msg). In case I am using L3 authentication (Captive portal authentication), everything works fine, because controller can see session timeout in Access-Accept message and session timeout is then intercepted by controller.

If needed, I can provide also wireshark capture files.

THX for help.
Miroslav Ondrek

**Comment by arr2036** [comment]
Use the mailing list for support requests please.

**Comment by miondrek** [comment]
I am sorry, but I am new here. What mailing list do you mean exactly?
THX

**Comment by arr2036** [comment]
http://freeradius.org/list/users.html
