### ISSUE TITLE
FR 3.0 PROXY UDP PORT Question

### ISSUE THREAD

**Issue by dhpark21** [FreeRADIUS/freeradius-server#1210]
Hi.
when FR2.x start radius then 
udp        0      0 0.0.0.0:1812                0.0.0.0:*
udp        0      0 0.0.0.0:1813                0.0.0.0:*
udp        0      0 0.0.0.0:1814                0.0.0.0:*

but FR3.0.x start radius then
udp        0      0 0.0.0.0:1812                0.0.0.0:*
udp        0      0 0.0.0.0:1813                0.0.0.0:*
udp        0      0 0.0.0.0:57242               0.0.0.0:*  < did not fix proxy port[FR2.x 1814] but ackt proxy port

my firewall is allow only udp 1812,1813,1814
but FR3.0.x did not fix udp 1814, when start time random port assign

How can i fix at FR3.0 Proxy port to UDP 1814?
Thanks

**Comment by arr2036** [comment]
https://github.com/FreeRADIUS/freeradius-server/blob/v3.1.x/CONTRIBUTING
