### ISSUE TITLE
FR 3.0 PROXY port problem. [type=proxy]

### ISSUE THREAD

**Issue by dhpark21** [FreeRADIUS/freeradius-server#1213]
Hi.
 when FR2.x start radius then 
 udp 0 0 0.0.0.0:1812 0.0.0.0:*
 udp 0 0 0.0.0.0:1813 0.0.0.0:*
 udp 0 0 0.0.0.0:1814 0.0.0.0:*

but FR3.0.x start radius then
 udp 0 0 0.0.0.0:1812 0.0.0.0:*
 udp 0 0 0.0.0.0:1813 0.0.0.0:*
 udp 0 0 0.0.0.0:57242 0.0.0.0:* < did not fix proxy port[FR2.x 1814] but ackt proxy port

my firewall is allow only udp 1812,1813,1814
 but FR3.0.x did not fix udp 1814, when start time random port assign

so add default file

listen {
 type = proxy
 ipaddr = *
 port = 1814
 }

but when statrt[radiusd -X] below error happen.
"Error: listen type "proxy" Cannot appear in a virtual server section"

What's wrong?

 Thanks

**Comment by dhpark21** [comment]
I was found error code at 
listen.c
#ifdef WITH_PROXY
        /*
         *      We were passed a virtual server, so the caller is
         *      defining a proxy listener inside of a virtual server.
         *      This isn't allowed right now.
         */
        else if (type == RAD_LISTEN_PROXY) {
                ERROR("Error: listen type \"proxy\" Cannot appear in a virtual server section");
                return NULL;
        }
#endif

So, how can i use proxy start port 1814[udp] ?
Thanks.

**Comment by alandekok** [comment]
Questions belong on the freeradius-users list.  And if you want to know how to fix the problem, read the error message you posted here.  Honestly, this isn't difficult.
