### ISSUE TITLE
rlm_sql_postgresql: Status: PGRES_FATAL_ERROR rlm_sql_postgresql: 42703: UNDEFINED COLUMN

### ISSUE THREAD

**Issue by dnybz** [FreeRADIUS/freeradius-server#1215]
I compiled using FreeRadius 3.0.9 on FreeBSD 10, when configured PostgreSQL database user authentication and found a BUG,
1, rlm_sql_postgresql: 42703: UNDEFINED COLUMN
2, rlm_sql_postgresql: 42703: UNDEFINED COLUMN

The reason is the cause of this BUG /usr/local/etc/raddb/mods-config/sql/main/postgresql directory of

queries.conf documents in the database queries and create mismatches schema.sql
INSERT INTO radacc xxx
UPDATE radacct SET xxx

Hoping to get repaired, thank you.

(13) sql: EXPAND UPDATE radacct SET FramedIPAddress = NULLIF('%{Framed-IP-Address}', '')::inet, AcctSessionTime = %{%{Acct-Session-Time}:-NULL}, AcctInterval = (%{integer:Event-Timestamp} - EXTRACT(EPOCH FROM (COALESCE(AcctUpdateTime, AcctStartTime)))), AcctUpdateTime = TO_TIMESTAMP(%{integer:Event-Timestamp}), AcctInputOctets = (('%{%{Acct-Input-Gigawords}:-0}'::bigint << 32) + '%{%{Acct-Input-Octets}:-0}'::bigint), AcctOutputOctets = (('%{%{Acct-Output-Gigawords}:-0}'::bigint << 32) + '%{%{Acct-Output-Octets}:-0}'::bigint) WHERE AcctUniqueId = '%{Acct-Unique-Session-Id}' AND AcctStopTime IS NULL
(13) sql:    --> UPDATE radacct SET FramedIPAddress = NULLIF('10.1.1.3', '')::inet, AcctSessionTime = 3603, AcctInterval = (1441792122 - EXTRACT(EPOCH FROM (COALESCE(AcctUpdateTime, AcctStartTime)))), AcctUpdateTime = TO_TIMESTAMP(1441792122), AcctInputOctets = (('0'::bigint << 32) + '1237347'::bigint), AcctOutputOctets = (('0'::bigint << 32) + '559292'::bigint) WHERE AcctUniqueId = 'f5876ce84f022881f96b50df28f77392' AND AcctStopTime IS NULL
(13) sql: Executing query: UPDATE radacct SET FramedIPAddress = NULLIF('10.1.1.3', '')::inet, AcctSessionTime = 3603, AcctInterval = (1441792122 - EXTRACT(EPOCH FROM (COALESCE(AcctUpdateTime, AcctStartTime)))), AcctUpdateTime = TO_TIMESTAMP(1441792122), AcctInputOctets = (('0'::bigint << 32) + '1237347'::bigint), AcctOutputOctets = (('0'::bigint << 32) + '559292'::bigint) WHERE AcctUniqueId = 'f5876ce84f022881f96b50df28f77392' AND AcctStopTime IS NULL
rlm_sql_postgresql: Status: PGRES_FATAL_ERROR
rlm_sql_postgresql: 42703: UNDEFINED COLUMN
(13) sql: rlm_sql_postgresql: ERROR:  column "acctupdatetime" does not exist
(13) sql: rlm_sql_postgresql: LINE 1: ...rval = (1441792122 - EXTRACT(EPOCH FROM (COALESCE(AcctUpdate...
(13) sql: rlm_sql_postgresql:                                                              ^
(13) sql: SQL query returned: need alt query
(13) sql: Trying next query...
(13) sql: EXPAND INSERT INTO radacct (AcctSessionId, AcctUniqueId, UserName, Realm, NASIPAddress, NASPortId, NASPortType, AcctStartTime, AcctUpdateTime, AcctStopTime, AcctSessionTime, AcctAuthentic, ConnectInfo_start, ConnectInfo_Stop, AcctInputOctets, AcctOutputOctets, CalledStationId, CallingStationId, AcctTerminateCause, ServiceType, FramedProtocol, FramedIpAddress) VALUES('%{Acct-Session-Id}', '%{Acct-Unique-Session-Id}', '%{SQL-User-Name}', NULLIF('%{Realm}', ''), '%{%{NAS-IPv6-Address}:-%{NAS-IP-Address}}', NULLIF('%{%{NAS-Port-ID}:-%{NAS-Port}}', ''), '%{NAS-Port-Type}', TO_TIMESTAMP(%{integer:Event-Timestamp}), TO_TIMESTAMP(%{integer:Event-Timestamp}), NULL, %{%{Acct-Session-Time}:-NULL}, '%{Acct-Authentic}', '%{Connect-Info}', NULL, (('%{%{Acct-Input-Gigawords}:-0}'::bigint << 32) + '%{%{Acct-Input-Octets}:-0}'::bigint), (('%{%{Acct-Output-Gigawords}:-0}'::bigint << 32) + '%{%{Acct-Output-Octets}:-0}'::bigint), '%{Called-Station-Id}', '%{Calling-Station-Id}', NULL, '%{Service-Type}', '%{Framed-Protocol}', NULLIF('%{Framed-IP-Address}', '')::inet)
(13) sql:    --> INSERT INTO radacct (AcctSessionId, AcctUniqueId, UserName, Realm, NASIPAddress, NASPortId, NASPortType, AcctStartTime, AcctUpdateTime, AcctStopTime, AcctSessionTime, AcctAuthentic, ConnectInfo_start, ConnectInfo_Stop, AcctInputOctets, AcctOutputOctets, CalledStationId, CallingStationId, AcctTerminateCause, ServiceType, FramedProtocol, FramedIpAddress) VALUES('1788521-pt1', 'f5876ce84f022881f96b50df28f77392', 'test', NULLIF('', ''), '59.108.91.134', NULLIF('1', ''), 'Virtual', TO_TIMESTAMP(1441792122), TO_TIMESTAMP(1441792122), NULL, 3603, 'RADIUS', '', NULL, (('0'::bigint << 32) + '1237347'::bigint), (('0'::bigint << 32) + '559292'::bigint), '', '60.190.244.158', NULL, 'Framed-User', 'PPP', NULLIF('10.1.1.3', '')::inet)
(13) sql: Executing query: INSERT INTO radacct (AcctSessionId, AcctUniqueId, UserName, Realm, NASIPAddress, NASPortId, NASPortType, AcctStartTime, AcctUpdateTime, AcctStopTime, AcctSessionTime, AcctAuthentic, ConnectInfo_start, ConnectInfo_Stop, AcctInputOctets, AcctOutputOctets, CalledStationId, CallingStationId, AcctTerminateCause, ServiceType, FramedProtocol, FramedIpAddress) VALUES('1788521-pt1', 'f5876ce84f022881f96b50df28f77392', 'test', NULLIF('', ''), '59.108.91.134', NULLIF('1', ''), 'Virtual', TO_TIMESTAMP(1441792122), TO_TIMESTAMP(1441792122), NULL, 3603, 'RADIUS', '', NULL, (('0'::bigint << 32) + '1237347'::bigint), (('0'::bigint << 32) + '559292'::bigint), '', '60.190.244.158', NULL, 'Framed-User', 'PPP', NULLIF('10.1.1.3', '')::inet)
rlm_sql_postgresql: Status: PGRES_FATAL_ERROR
rlm_sql_postgresql: 42703: UNDEFINED COLUMN
(13) sql: rlm_sql_postgresql: ERROR:  column "acctupdatetime" of relation "radacct" does not exist
(13) sql: rlm_sql_postgresql: LINE 1: ...IPAddress, NASPortId, NASPortType, AcctStartTime, AcctUpdate...
(13) sql: rlm_sql_postgresql:

**Comment by arr2036** [comment]
You're using an old schema with a recent version of the server.  AcctUpdateTime is included in the default schema that ships with all v3.0.x versions it was not included in v2.x.x.

https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/mods-config/sql/main/postgresql/schema.sql#L27
