### ISSUE TITLE
Problems with dots in policy statements

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1237]
Hi,

After upgrade to HEAD, the use of dots is not supported anymore?

```
alcatel.captive_redirect {
     update {
         &Alc-Wlan-Portal-Url := "${mconf.setup.portal_url}"
         &Alc-Portal-Url := "%{reply:Alc-Wlan-Portal-Url}"
         &Alc-Wlan-Portal-Redirect := "PortalRedirect"
         &Reply-Message := "Redirected to Captive Portal"
         &Client-DNS-Pri := "%{config:mconf.setup.dns_primary}"
         &Client-DNS-Sec := "%{config:mconf.setup.dns_secondary}"
     }
}
```

after replace '.' for '_' works. but, I always used the '.'

**Comment by arr2036** [comment]
Should be fixed before v3.0.10 is released.  This will break lots of configurations.  Using dots in policy names has been supported since policies were introduced. Only a ``.<section name>`` suffix should result in the policy being treated specially.

**Comment by jpereira** [comment]
exactly... I have tens of policies using dots.

**Comment by alandekok** [comment]
OK.  I'll look at it later today.  The change is probably due to the fixes Arran wanted for load balancing sections.
