### ISSUE TITLE
DHCP relay can't relay between two interfaces

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#1261]
Code uses FD of listener socket which may be bound to specific address.  If relay is not reachable via bound IP interface we get `(0) WARNING: State function returned error (-1): dhcp_send_socket: Can't assign requested address`.

This is probably going to be a massive pain to fix, and require us to define home servers for DHCP relays, unless we want to open/close sockets for each packet being relayed.

Simple workaround is to bind listener to '*' (INADDR_ANY), then all works as expected.

**Comment by alandekok** [comment]
Yes, we really need a separate proxy state for DHCP packets.  This should be fixed once we have parent->child relationships in the server core.  We can then have a state machine for DHCP server, and a separate one for DHCP client.

The simplest solution in the short term might be to just define DHCP home servers.  That way the rest of the proxy code should work as-is...

**Comment by alandekok** [comment]
v3.1.x now has parent-child relationships for requests.  The next step is to fix the interpreter so that it does:

    unlang_intepret(REQUEST *request, CONF_SECTION *cs)

While also moving all of the protocol-specific work to plugin modules.

**Comment by alandekok** [comment]
We're not going to fix this in v3.0.x, sorry.

**Comment by alandekok** [comment]
The solution in v4 is to have a separate outbound `rlm_dhcp` module, like the new `rlm_radius` module.  The code would be substantially similar.

**Comment by arr2036** [comment]
Agreed.  Splitting out relay/proxying functionality as modules makes all this stuff so much simpler.

**Comment by alandekok** [comment]
We know what to do here, so there isn't a lot of point in having this issue open.
