### ISSUE TITLE
secret exposed in debug mode

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1267]
usually, shared secrets are ``<<<secret>>>`` when running in the basic -X debug mode.

however, if an entry in proxy.conf is using
```
authhost = 
accthost =
```
method, then the shared_secret gets exposed!
```
realm donkey.com {
        authhost        = 192.168.200.10
        secret  = your_shared_secret
        status_check = status-server
        nostrip
}
```
debug:
```
 realm donkey.com {
	nostrip
	authhost = 192.168.200.10
	secret = your_shared_secret
 }
```

but:
```
realm donkey.com {
        type = auth
        ipaddr  = 192.168.200.10
        secret  = your_shared_secret
        status_check = status-server
        nostrip
}
```

debug:
```
 realm donkey.com {
	nostrip
 }
```

hmmm....why doesnt it print the method, ipaddr etc?

**Comment by alandekok** [comment]
> hmmm....why doesnt it print the method, ipaddr etc?

Because they're not allowed in a "realm" section.  See the docs and examples.

There is no `status_check` or `ipaddr` or `type` in a `realm` section.
