### ISSUE TITLE
Freeradius-rest debian package is empty

### ISSUE THREAD

**Issue by qnet-herwin** [FreeRADIUS/freeradius-server#1289]
```
$ lintian freeradius-rest_3.0.10+git_i386.deb
W: freeradius-rest: empty-binary-package
```

And indeed, the package contains only the following files
```
./usr/share/doc/freeradius-rest/changelog.gz
./usr/share/doc/freeradius-rest/copyright
./usr/share/doc/freeradius-rest/changelog.Debian.gz
```

Currently rlm_rest is included in the main packages of freeradius. I'm not completely sure if this should be fixed for 3.0, because it may break existing installations that haven't installed the rest package, but are using it. Any opinions on this?

**Comment by alandekok** [comment]
I'd leave it for 3.0.  And fix it for 3.1

**Comment by arr2036** [comment]
You'd leave the packaging broken for v3.0.x?  That doesn't really make sense.

**Comment by alandekok** [comment]
I wouldn't break peoples existing systems.

If they use rlm_rest, and upgrade the server... they will get cranky when rlm_rest disappears.  It may be hard to figure out that they need to install an rlm_rest package.

**Comment by arr2036** [comment]
We're preparing the packages for inclusion by Debian - That's what all the PRs are for.  The package is broken.  It's unlikely the correct dependencies will be installed without the rlm_rest package being installed, so if you did try and use rlm_rest, you'd just get obscure linker errors.

**Comment by arr2036** [comment]
It either needs to be fixed by removing the rlm_rest package, or fixing the rlm_rest package, leaving it broken like this is shit.

**Comment by arr2036** [comment]
We're either forcing debian to roll their own packaging files, or patch ours to fix a bug that we refuse to fix.  Having working packages that are included in debian and ubuntu is VASTLY more useful than not breaking the absolutely tiny number of systems running v3.0.x with their own packages built from our bundled debian packaging files.

**Comment by arr2036** [comment]
Hmm I appear to have *accidentally* pulled across the change from v3.1.x that fixes this issue.
