### ISSUE TITLE
Incorrect auth-ok message with NAS-Port > 65535 

### ISSUE THREAD

**Issue by EllezDi** [FreeRADIUS/freeradius-server#1300]
There is a problem logging access-requests, which have NAS-Port > 65535 

Access-Request:
```
User-Name = "xx" 
User-Password = "yy"
NAS-IP-Address =  10.10.10.10
NAS-Port =  16973824
```
In FR 2.x we have in log:
```
Auth: Login OK: [xx/yy] (from client localhost port 16973824)
```
in FR 3.0.9:
```
Login OK: [xx/yy] (from client localhost port 0)
```
Refers to dictionary.rfc2865 , NAS-Port in an 32-bit integer
The problem is in src/main/auth.c 
49270a89ace977843f69daada6b391a8c30ecbfc

preprocess module partially solve this problem (with ascend hack is on)
```
Login OK: [xx/yy] (from client localhost port 874)
```
@arr2036, @alandekok what do you think ?

**Comment by arr2036** [comment]
yeah, weird it should be 32bits

**Comment by alandekok** [comment]
I think I think you have the versions backwards, but OK.

Fixed by commit 2990a2
