### ISSUE TITLE
Add support to print "dhcp data" in print_abinary()

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1306]
Hi,

Just to register: we need to implement the filter to handle "binary data" like the "Alc-ToServer-Dhcp-Options"

**Comment by arr2036** [comment]
What do you mean by that?  You should be able to filter it using a hex string?

**Comment by jpereira** [comment]
Mean like to print the dhcp fields. what do you think?

**Comment by arr2036** [comment]
Like the functionality that's already present in the server to do that and has been for at least three years now?

**Comment by arr2036** [comment]
see dhcp_options xlat

**Comment by arr2036** [comment]
:)

**Comment by jpereira** [comment]
hahahahahaha!! come on @arr2036, My idea is to print in %{debug_attr:request:} :hammer:

**Comment by arr2036** [comment]
right....

```
"%{dhcp_options:Alc-ToServer-Dhcp-Options}"
"%{debug_attr:request:}"
```

**Comment by arr2036** [comment]
if you want to avoid the overhead I think there's an xlat for getting the current debug level

**Comment by jpereira** [comment]
My idea is to identifier the dhcp-packet type in print_abinary() as like 

```
/*
	*	Handle IP filters
	*/
	if (filter->type == RAD_FILTER_IP) {
..........
		/*
		 *	Handle IPX filters
		 */
	} else if (filter->type == RAD_FILTER_IPX) {
................
```

**Comment by jpereira** [comment]
btw, the xlat debug_attr it's awesome! help a lot!

**Comment by arr2036** [comment]
Yeah :) I got tired of trying to work out what the contents of the various lists were, or what that unknown VSA could be.

**Comment by arr2036** [comment]
Alan and I discussed about adding special attribute types to allow automatic decoding of DHCP attributes.  The problem is we're trying to break apart the different protocols, so that all the types/encoders/decoders would be registered by proto_dhcp.  Quick hacks like that just add to the amount of code we have to undo.

The current xlats work fine, right?  You'd just like it to be more automated...

**Comment by jpereira** [comment]
hmmmm! the idea of proto_dhcp sounds good! It would be something like a hookings?

**Comment by arr2036** [comment]
yeah a bunch of callbacks for different operations.  Some of it's already there.  I started working on cleaning up listen.c yesterday, once that's done and we formalise the protocol interface we can look at adding special attribute types with decode/encode callbacks.

**Comment by jpereira** [comment]
So, we will have: proto_{auth,coa,acct,dhcp,....} ?

**Comment by arr2036** [comment]
yes

**Comment by arr2036** [comment]
more proto_radius and proto_dhcp

**Comment by jpereira** [comment]
In this case, we can close this issue. after wall, We'll have a place to do!

**Comment by arr2036** [comment]
ok!
