### ISSUE TITLE
EAP loop detection prevents TLS-tunneled sessions from using a pool's virtual fallback server

### ISSUE THREAD

**Issue by skids** [FreeRADIUS/freeradius-server#1311]
(Sorry I couldn't get to this pre-3.0.10, time just did not allow.)

Fallback servers (which must be virtual) cannot serve tunneled requests because,
they false-detect an EAP loop.  To reproduce, take the stock configuration and make
these changes:

proxy.conf:
1) set the home server's port to something ridiculous to emulate it being down
2) Activate/define the virtual.example.com home_server and server sections.
    Note you can't just use the commented out text since it has bitrotted: the
    default server has a listen stanza in it now which will self-conflict.
3) remove the suffix calls from virtual.example.com just to eliminate any
    possibility that a second suffix realm route after fallback is to blame (same results
    either way)
4) uncomment/activate virtual.example.com as the fallback for the my_auth_failover
    pool
5)  In inner tunnel auth update control { &Cleartext-Password := testing123 } for a quick
    and dirty test user
6) make an eapol-test template file:
network={
        ssid="example"
        key_mgmt=WPA-EAP
        eap=PEAP
        identity="iiiiii"
        anonymous_identity="oooooo"
        password="pppppp"
        phase1="peaplabel=0"
        phase2="auth=MSCHAPV2"
}
7) Make a script to use it:

#!/bin/sh

EAPOL_TEST='/sbin/eapol_test'
TESTPWD="testing123"

echo -n "Test1..."
cat eapol_test_peap_mschap.conf | perl -pne 's/oooooo/anon\@example.com/; s/iiiiii/buguser\@example.com/; s/pppppp/'$TESTPWD'/;' > eapol_test_scratch.conf
$EAPOL_TEST -c eapol_test_scratch.conf -a 127.0.0.1 -p 1812 -s testing123 -Md4:00:00:00:00:01 -N4:x:0x7f000001 -N30:s:00-01-02-03-04-03:example
#| grep -q 'MS-MPPE-Recv-Key' && echo "win." || echo "FAIL!"
echo -n > eapol_test_scratch.conf

8) Run the script once, wait for the server with the bogus port to be declared dead, then
run it again.  In the below ouput the session starting at number (14) eventually
fails at '(21) eap: Multiple levels of TLS nesting is invalid' (which as an aside should
probably be a colorized error message.)

Debug output at
https://gist.github.com/skids/17869d1a528c8134959a

Other folks have managed to get themselves into this pickle before but may have been doing
something unusual -- I don't think it's very unusual to want a fallback server, though, and those are required to be virtual.  Here are links to old ML threads:

   http://lists.freeradius.org/pipermail/freeradius-users/2008-October/032231.html
   http://marc.info/?l=freeradius-users&m=127242177232523&w=2

**Comment by skids** [comment]
Thanks Alan!  I'll give that a spin later today.

**Comment by skids** [comment]
Unfortunately that does not seem to have quite nailed it -- after/before diff of debug:


    1793c1873
    <  eap: ERROR: Multiple levels of TLS nesting are invalid
    ---
    >  eap: Multiple levels of TLS nesting is invalid
    1807c1887
    <          &Module-Failure-Message := &request:Module-Failure-Message -> 'eap: Multiple levels of TLS nesting are invalid'
    ---
    >          No attributes updated
    1823c1903
    <  eap: EAP session adding &reply:State = 0x528d2fb8558536bc
    ---
    >  eap: EAP session adding &reply:State = 0xf679a215f171bb01
    1829,1830d1908
    <  session-state: Saving cached attributes
    <    Module-Failure-Message := "eap: Multiple levels of TLS nesting are invalid"

**Comment by alandekok** [comment]
Try changing it to:

**Comment by alandekok** [comment]
Try changing it to:

	if (!handler->request->home_server &&
	    handler->request->parent && 
	    !handler->request->parent->home_server &&
	    handler->request->parent->parent) {
		RERROR("Multiple levels of TLS nesting are invalid");

		return EAP_INVALID;
	}

If that works, I'll push a patch.

**Comment by skids** [comment]
No such luck.  Tomorrow I'll try adding some debug prints in there to see what we've got to work with.

**Comment by skids** [comment]
Looks like the grandparent request has a home server and a pool but the offspring do not.  Would checking request->parent->parent->home_server be right?

eap: home_server is (nil)
eap: server is inner-tunnel
eap: Home pool is (nil)
eap: Parent:
eap: home_server is (nil)
eap: server is virtual.example.com
eap: Home pool is (nil)
eap: Grandparent:
eap: home_server is 0x7f537c2cdaa0
eap: server is default
eap: Home pool is 0x7f537c2d13e0

**Comment by skids** [comment]
I did try out this:

    if (handler->request->parent
            && handler->request->parent->parent
            && !handler->request->parent->parent->home_server) 

...and that "worked", but I'm unsure how to test to see if it still blocks
actual EAP loops.

Also a tangentially related thing which I can open a separate issue on if it is
not just an obvious fix.  fr_state_get_vps destructively move-copies
attributes out of the cached state list.  In certain situations where a request
proxies back to the same process, the state list will be found-but-empty on the
second time in.  This seems to fix that issue, and the server does seem to delete
the entries later on as appropriate:

    @@ -401,4 +401,4 @@ void fr_state_get_vps(REQUEST *request, RADIUS_PACKET *packet)
            if (entry) {
    -               fr_pair_list_mcopy_by_num(request, &request->state, &entry->vps, 0, 0, TAG_ANY);
    -               RDEBUG2("session-state: Found cached attributes");
    +               request->state = fr_pair_list_copy(request, entry->vps);
    +               RDEBUG2("session-state: Found cached attributes %p", entry);
                    rdebug_pair_list(L_DBG_LVL_1, request, request->state, NULL);


   

And, while I was trying that out, I noticed that fr_pair_list_copy_by_num is not
checking the documented 0 wildcard condition on attr and it neither documents nor
checks for a wildcard on vendor -- some code may relay on the latter, and both may be
intentional, in which case the docs in the comments just need to remove the wildcard.
