### ISSUE TITLE
Problems with \0 (null) terminators in string/regex

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1312]
Hi,

I think that we have a new issue related to string/regex. Probably a better debug message or a wrong behavior? I using v3.0.x/HEAD

```
Wed Oct  7 22:04:24 2015 : Debug: %{string: &ADSL-Agent-Circuit-Id}
Wed Oct  7 22:04:24 2015 : Debug: Parsed xlat tree:
Wed Oct  7 22:04:24 2015 : Debug: xlat --> string
Wed Oct  7 22:04:24 2015 : Debug: {
Wed Oct  7 22:04:24 2015 : Debug:       literal -->  &ADSL-Agent-Circuit-Id
Wed Oct  7 22:04:24 2015 : Debug: }
Wed Oct  7 22:04:24 2015 : Debug: (0)         EXPAND %{string: &ADSL-Agent-Circuit-Id}
Wed Oct  7 22:04:24 2015 : Debug: (0)            --> 38:c8:5c:b4:1a:06\000#MY-SSID\000o
Wed Oct  7 22:04:24 2015 : Debug: (0)         if (&ADSL-Agent-Circuit-Id) {
Wed Oct  7 22:04:24 2015 : Debug: (0)         if (&ADSL-Agent-Circuit-Id)  -> TRUE
Wed Oct  7 22:04:24 2015 : Debug: (0)         if (&ADSL-Agent-Circuit-Id)  {
Wed Oct  7 22:04:24 2015 : Debug: (0)           if (&ADSL-Agent-Circuit-Id =~ /^(.+)\000(.+)\000(.+)$/) {
Wed Oct  7 22:04:24 2015 : Debug: Clearing 4 matches
Wed Oct  7 22:04:24 2015 : Debug: (0)           if (&ADSL-Agent-Circuit-Id =~ /^(.+)\000(.+)\000(.+)$/)  -> FALSE
Wed Oct  7 22:04:24 2015 : Debug: (0)         } # if (&ADSL-Agent-Circuit-Id)  = noop
Wed Oct  7 22:04:24 2015 : Debug: (0)       } # policy mcare-parse.set_mobicare_ssid_options = noop
Wed Oct  7 22:04:24 2015 : Debug: (0)     } # policy mcare-parse.run = noop
```

The ADSL-Agent-Circuit-Id data.

```
ADSL-Agent-Circuit-Id = 0x33383a63383a35633a62343a31613a303600234e45542d4232423243006f
```

**Comment by jpereira** [comment]
1) I using the regex 

eg_mac = "^(.*)\0\0(.*)\0\0(.*)$"

2) The ```regex_compile``` receives.

```
Breakpoint 1, regex_compile (ctx=ctx@entry=0x969e60, out=out@entry=0x7fffffffdaa8,
    pattern=pattern@entry=0x969000 "^(.*)\\0\\0(.*)\\0\\0(.*)$", len=0x16, ignore_case=0x0, multiline=0x0,
    subcaptures=subcaptures@entry=0x1, runtime=runtime@entry=0x0) at src/lib/regex.c:84
84      in src/lib/regex.c
(gdb)
```

3) Looking for pcre documentation says that "\0 = Null character"

Looks like some wrong behavior.

**Comment by alandekok** [comment]
Regular expressions don't deal well with embedded NULL characters.  I don't think that this is a problem in FreeRADIUS.

**Comment by jpereira** [comment]
Yes! is a problem, because in another FreeRadius 3.0.4 in production works well!

**Comment by jpereira** [comment]
btw, I didn't found the email... but you gave me the tip about the regex with null terminator.

**Comment by arr2036** [comment]
It's a problem.  FreeRADIUS makes use of both pcre, and the BSD regex functions which take length parameters.  In both these cases the regex functions are able to deal with embedded \0s fine.

In the case of a string containing an embedded \0 and one of the none \0 safe regular functions being used, condition evaluation fails.

**Comment by jpereira** [comment]
Something was changed and affects the behavior. problem is because the regex has \0\0 and the xlat transform in \\0\\0 like my backtrace.

the pcre expect \0 as said in the pcre docs

**Comment by jpereira** [comment]
the github strip my "\ \ 0"

**Comment by jpereira** [comment]
I can't figure out where the scape is made... but! I give up to fix this. :-1:

**Comment by jpereira** [comment]
I can't figure out where the scape is made... but! I give up to fix this. come on @alandekok, revert your commit that scape the null chars!

**Comment by alandekok** [comment]
Just testing this.  The regex which is compiled is:

    ^(.+)\000(.+)\000(.+)$

that looks correct.  No extra escaping.

At run time. the attribute is expanded like this:

    (0)     EXPAND %{string:&ADSL-Agent-Circuit-Id}
    (0)        --> 38:c8:5c:b4:1a:06\000#NET-B2B2C\000o

Which is correct.  The output of the xlat expansion is a *printable* string.  Embedded zeros are not allowed.  The xlat expansion is *not* binary safe.

I would suggest instead looking at the *binary* data:

    if (&ADSL-Agent-Circuit-Id =~ /^0x((..)+)00((..)+)00((..)+)$/) { 

And then count braces.  You'll need the expansions %{1}, %{3}, and %{5}.  Their contents will be hex, so you need to convert them back to printable strings.

In the end, I don't think that this can be made to work the way you want.  The only way to fix it is to update the xlat code so that it takes a string *and* a length for everything.  Then, all of the APIs (callers and callees) of the xlat functions need to be checked that they are binary safe.
