### ISSUE TITLE
Why Session Ticket(RFC4507) option decided by "SSL_OP_NO_TICKET" Macro

### ISSUE THREAD

**Issue by xbguo** [FreeRADIUS/freeradius-server#1315]
"src/main/tls.c" 3192 lines --79%--  
2543 
2544 #ifdef SSL_OP_NO_TICKET
2545     ctx_options |= SSL_OP_NO_TICKET;
2546 #endif
2547 

SSL_OP_NO_TICKET is defined by the openssl in the header file "ssl.h"

 400 /* Don't use RFC4507 ticket extension */
 401 # define SSL_OP_NO_TICKET                    0x00004000L

I think this macro always defined in new version openssl. 
Is this means free-radius always telling  openssl not using "Session Ticket"?

**Comment by alandekok** [comment]
Don't ask questions here.

**Comment by xbguo** [comment]
I think there something wrong.But I'm not so sure, so I use the interrogative mood.

**Comment by alandekok** [comment]
If you don't understand, ask a question on the freeradius-devel mailing list.

**Comment by xbguo** [comment]
Okey, Thanks a lot






在 2015-10-09 00:21:39，"Alan DeKok" <notifications@github.com> 写道：


If you don't understand, ask a question on the freeradius-devel mailing list.
