### ISSUE TITLE
Problems with %{explode:}

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1317]
Hi,

We have problems with %{explode: } like the below examples.

```
develop_override = "Called-Station-Id,My-SSID-Name,My-SSID-Vlan"

"%{explode:%{config:policy.develop_override} ,}"

"%{explode:${policy.develop_override} ,}"

```

It would be cool if it works as below too.
```
"%{explode:Called-Station-Id,My-SSID-Name,My-SSID-Vlan ,}"

"%{explode: Called-Station-Id,My-SSID-Name,My-SSID-Vlan ,}"
```

**Comment by arr2036** [comment]
And it will... in v3.1.x when we move to passing xlat nodes into functions, and can distinguish between expansions and other things.  In the mean time, the performance impact is tiny, so not really a priority.
