### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by antonen76** [FreeRADIUS/freeradius-server#1325]
Hi 

we use a freeradius 3.0.10 with eap_peap mschapv2 for eduroam autentication with two ldap server (one for staff and the other for student) as backend and a sql oracle db for accounting.

Due to our query that matches two users with homonyms radius fails at the beginnings of INSERT query in the db.

These are the last output debug:
-User-Name})(utenteattivo=TRUE))(&(edupersonprincipalname=%{Stripped-User-Name})(utenteattivo=TRUE)))
(1690) studenti_EC:    --> (|(&(mail=xxxxx@mydomain.it)(utenteattivo=TRUE))(&(uid=xxxxx)(utenteattivo=TRUE))(&(edupersonprincipalname=xxxxx)(utenteattivo=TRUE)))
(1690) studenti_EC: Performing search in "dc=mydomain,dc=it" with filter "(|(&(mail=xxxx@mydomain.it)(utenteattivo=TRUE))(&(uid=xxxx)(utenteattivo=TRUE))(&(edupersonprincipalname=xxxx)(utenteattivo=TRUE)))", scope "sub"
(1690) studenti_EC: Waiting for search result...
(1690) studenti_EC: ERROR: Ambiguous search result, returned 2 unsorted entries (should return 1 or 0).  Enable sorting, or specify a more restrictive base_dn, filter or scope
(1690) studenti_EC: ERROR: The following entries were returned:
(1690) studenti_EC:   ERROR: uid=xxxx,ou=studenti,dc=uniparthenope,dc=it
(1690) studenti_EC:   ERROR: uid=xxxx,ou=studenti,dc=uniparthenope,dc=it
ORA-24550: signal received: [si_signo=6] [si_errno=0] [si_code=-6] [si_int=0] [si_ptr=(nil)] [si_addr=0x3ea000039ac]

*** Error in `/usr/local/sbin/radiusd': double free or corruption (fasttop): 0x0000000001ab2840 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x730bf)[0x7f11f140c0bf]
/lib64/libc.so.6(+0x7892e)[0x7f11f141192e]
/lib64/libc.so.6(+0x79636)[0x7f11f1412636]
/usr/local/lib/rlm_ldap.so(rlm_ldap_find_user+0x217)[0x7f11f094c087]
/usr/local/lib/rlm_ldap.so(+0x5ad9)[0x7f11f0947ad9]
/usr/local/sbin/radiusd[0x42683f]
/usr/local/sbin/radiusd[0x425969]
/usr/local/sbin/radiusd[0x425b3e]
/usr/local/sbin/radiusd[0x425969]
/usr/local/sbin/radiusd[0x425b3e]
/usr/local/sbin/radiusd(modcall+0x43)[0x426d53]
/usr/local/sbin/radiusd(indexed_modcall+0x9d)[0x421c4d]
/usr/local/sbin/radiusd(rad_authenticate+0x3c6)[0x411cc6]
/usr/local/sbin/radiusd[0x434442]
/usr/local/sbin/radiusd[0x4306c4]
/usr/local/sbin/radiusd(request_receive+0x347)[0x431d57]
/usr/local/sbin/radiusd[0x41cc16]
/usr/local/sbin/radiusd[0x42ee0b]
/usr/local/lib/libfreeradius-radius.so(fr_event_loop+0x2fc)[0x7f11f311514c]
/usr/local/sbin/radiusd(main+0x70a)[0x410c5a]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f11f13bab05]
/usr/local/sbin/radiusd[0x410f9e]
======= Memory map: ========

**Comment by arr2036** [comment]
Authentication will still error out for those users though.  You need to follow the advice in the log
