### ISSUE TITLE
Base DN cannot be specified via server URL

### ISSUE THREAD

**Issue by huzzoid** [FreeRADIUS/freeradius-server#1329]
I've updated from 3.0.6 to 3.0.10 and got an error:

=================================================
radiusd -X
...
 # Instantiating module "ldap" from file /usr/local/etc/raddb/mods-enabled/ldap
rlm_ldap: libldap vendor: OpenLDAP, version: 20440
   accounting {
   	reference = "%{tolower:type.%{Acct-Status-Type}}"
   }
   post-auth {
   	reference = "."
   }

/usr/local/etc/raddb/mods-enabled/ldap[8]: Base DN cannot be specified via server URL
/usr/local/etc/raddb/mods-enabled/ldap[8]: Instantiation failed for module "ldap"

=============================================================

I've tried on debian7 and debian8. 

There is my ldap module config:
cat /usr/local/etc/raddb/mods-enabled/ldap | grep -v "#"

===============================================

ldap {
        server = 'ldaps://10.10.10.10/'
        identity = 'cn=radius,ou=users,dc=ldap,dc=example,dc=com'
        password = mypassword
        base_dn = 'dc=ldap,dc=example,dc=com'
        sasl {}

	update {
	        control:Password-With-Header	+= 'userPassword'
		control:			+= 'radiusControlAttribute'
		request:			+= 'radiusRequestAttribute'
		reply:				+= 'radiusReplyAttribute'
	}

	user {
		base_dn = "dc=ldap,dc=example,dc=com"
		filter = "(uid=%{%{Stripped-User-Name}:-%{User-Name}})"
		sasl {
		}
        }

	group {
		base_dn = ""
		filter = '(objectClass=posixGroup)'
		membership_attribute = 'memberOf'
	}

	profile {
	}
	client {
		base_dn = "${..base_dn}"
		filter = '(objectClass=radiusClient)'
		template {
		}
		attribute {
			ipaddr				= 'radiusClientIdentifier'
			secret				= 'radiusClientSecret'
		}
	}
	accounting {
		reference = "%{tolower:type.%{Acct-Status-Type}}"
		type {
			start {
				update {
					description := "Online at %S"
				}
			}

			interim-update {
				update {
					description := "Last seen at %S"
				}
			}
			stop {
				update {
					description := "Offline at %S"
				}
			}
		}
	}

	post-auth {
		update {
			description := "Authenticated at %S"
		}
	}

	options {
		chase_referrals = yes
		rebind = yes
		use_referral_credentials = no
         	res_timeout = 10
		srv_timelimit = 3
		idle = 60
		probes = 3
		interval = 3
		ldap_debug = 0x0028
	}

	tls {
	}

	pool {
		start = ${thread[pool].start_servers}
		min = ${thread[pool].min_spare_servers}
		max = ${thread[pool].max_servers}
		spare = ${thread[pool].max_spare_servers}
		uses = 0
		retry_delay = 30
		lifetime = 0
		idle_timeout = 60
		connect_timeout = 3.0
	}
}

===========================================

Sorry if it is incorrect place for this question.

**Comment by arr2036** [comment]
Remove the trailing slash as per the default config
