### ISSUE TITLE
Add field 'operator_name' in 'nas' SQL scheme.

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1337]
I think that could be necessary to add the field 'operator_name'  (like optional) in the 'nas' SQL-Scheme. that main idea is to fill the Operator-Name client section.

**Comment by alanbuxey** [comment]
the SQL client code is quite nasty. you cant just add things to the
database IIRC - you need to change the SQL import code which assumes fixed
locations for
each field...

**Comment by arr2036** [comment]
Yes, that's why in v3.1.x we added an additional method to the drivers to allow mapping by column name.  In theory, if someone writes the glue code, we can have arbitrary fields in SQL clients too, but this is planned for already and doesn't require another ticket
