### ISSUE TITLE
Some fields isn't updated in 'radmin> stats home_server acct'

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1339]
Hi,

   I noticed that always when i receive the message

```
Fri Oct 23 05:25:42 2015 : ERROR: (463) ERROR: Failing proxied request for user "ec:88:92:86:06:12", due to lack of any response from home server 10.1.2.4 port 1
```

The field 'invalid or malformed' isn't updated in "radmin stats".

```
# radmin
radmin> stats home_server acct
requests        865
responses       857
dup             0
invalid         0
malformed       0
bad_authenticator       0
dropped         0
unknown_types   0
timeouts        0
last_packet     1445578085
elapsed.1us     0
elapsed.10us    0
elapsed.100us   0
elapsed.1ms     853
elapsed.10ms    62
elapsed.100ms   1
elapsed.1s      0
elapsed.10s     0
#
```

**Comment by arr2036** [comment]
Why would you expect it to be?

**Comment by jpereira** [comment]
I noticed that don'`t exist this code... Only to: 

```
src/main/listen.c:	FR_STATS_TYPE_INC(client->auth.total_requests);
src/main/listen.c:	FR_STATS_TYPE_INC(client->auth.total_requests);
src/main/listen.c:	FR_STATS_TYPE_INC(client->acct.total_requests);
.......
```

**Comment by jpereira** [comment]
@arr2036 It is helpful to collect metrics about "who" home_server has X invalid/... packets.

**Comment by jpereira** [comment]
@arr2036 It is helpful to collect metrics about "who" home_server has X invalid/... packets. And if something wrong happens... Like timeout/invalid/... during the Proxy over home_server.... I think that is necessary to increase some field.

Or we can add a new field like "failed". What do you think?

**Comment by jpereira** [comment]
In my example you can notice that has a gap between requests and response.

```
requests        865
responses       857
dup             0
invalid         0
malformed       0
bad_authenticator       0
dropped         0
unknown_types   0
timeouts        0
```

After check the code, I noticed that could be better to add a new field "failed".

**Comment by alandekok** [comment]
> On Oct 23, 2015, at 1:30 AM, Jorge Pereira <notifications@github.com> wrote:
> 
> Hi,
> 
> I noticed that always when i receive the message
> 
> Fri Oct 23 05:25:42 2015 : ERROR: (463) ERROR: Failing proxied request for user "ec:88:92:86:06:12", due to lack of any response from home server 10.1.2.4 port 1
> 
> The field 'invalid or malformed' isn't updated in "radmin stats".

  Because those fields have pre-defined meaning.  And timeout isn't part of their meaning.

   The "elapsed" fields are defined by FreeRADIUS

  See the RADIUS MIB RFCs for definitions of the rest of the fields.

**Comment by jpereira** [comment]
@alandekok I know about "elapsed.*", I said about handle the stats isn't count the error packets like:

```
Fri Oct 23 05:25:42 2015 : ERROR: (463) ERROR: Failing proxied request for user "ec:88:92:86:06:12", due to lack of any response from home server 10.1.2.4 port 1
```

You can notice that

```
  [-] Status Home-Server para: acct
requests        83525
responses       57782
dup             0
invalid         0
malformed       0
bad_authenticator       0
dropped         0
unknown_types   0
timeouts        0
last_packet     1445601846
elapsed.1us     0
elapsed.10us    0
elapsed.100us   0
elapsed.1ms     17161
elapsed.10ms    40781
elapsed.100ms   305
elapsed.1s      0
elapsed.10s     0
```

exist a gap between 83525 and 57782. But isn't counted by no field.

**Comment by alanbuxey** [comment]
errm, but your events are not error packets. they are not invalid packets.
 they are a different thing altogether.  the counters ARE working
correctly...you want counters for something else
entirely. your error message doesnt mean its invalid, error, unknown_type
or dropped. you;ve got a dodgy remote RADIUS server thus a new counter
needed 'no response' perhaps?

**Comment by jpereira** [comment]
I agree with you @alanbuxey! make sense! @alandekok and @arr2036, what do you think?

What we can do about the "Proxy .* due lack packets"?
We can add a new field? I believe that "no_response" sounds good! agree?

**Comment by alandekok** [comment]
The "lack of response" message increments the "timeouts" field.  See the code in process.c

**Comment by alandekok** [comment]
https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/main/process.c#L3924

**Comment by jpereira** [comment]
I found the

```
[jpereira@jpereira-desktop freeradius-server.git]$ grep "proxy_.*_stats" -r src/include/stats.h
extern fr_stats_t       proxy_auth_stats;
extern fr_stats_t       proxy_acct_stats;
extern fr_stats_t       proxy_coa_stats;
extern fr_stats_t       proxy_dsc_stats;
[jpereira@jpereira-desktop freeradius-server.git]$
```

@alandekok This case will be a new section in "radmin" to print the "proxy status". agree?

**Comment by jpereira** [comment]
@alandekok ok, but maybe we have a bug. check the below output and notice that exist a gap between request x response. should be the timeouts?

```
  [-] Status Home-Server para: acct
requests        83525
responses       57782
dup             0
invalid         0
malformed       0
bad_authenticator       0
dropped         0
unknown_types   0
timeouts        0
last_packet     1445601846
elapsed.1us     0
elapsed.10us    0
elapsed.100us   0
elapsed.1ms     17161
elapsed.10ms    40781
elapsed.100ms   305
elapsed.1s      0
elapsed.10s     0
```

**Comment by jpereira** [comment]
I found the

```
[jpereira@jpereira-desktop freeradius-server.git]$ grep "proxy_.*_stats" -r src/include/stats.h
extern fr_stats_t       proxy_auth_stats;
extern fr_stats_t       proxy_acct_stats;
extern fr_stats_t       proxy_coa_stats;
extern fr_stats_t       proxy_dsc_stats;
[jpereira@jpereira-desktop freeradius-server.git]$
```

@alandekok This case will be a new section in "radmin" to print the "proxy status". agree?

**Comment by alandekok** [comment]
Yes, the timeouts should be printed.

**Comment by jpereira** [comment]
Nice! I will push the "proxy" print.

**Comment by alandekok** [comment]
> Nice! I will push the "proxy" print.

Done.

**Comment by jpereira** [comment]
@alandekok this make sense?

```C
260     switch (request->proxy->code) {
261     case PW_CODE_ACCESS_REQUEST:
// why increase proxy_auth_stats.total_requests += request->num_proxied_requests;
262         proxy_auth_stats.total_requests += request->num_proxied_requests;
263         request->home_server->stats.total_requests += request->num_proxied_requests;
264         break;
265
266 #ifdef WITH_ACCOUNTING
267     case PW_CODE_ACCOUNTING_REQUEST:
// And here?
268         proxy_acct_stats.total_requests++;
269         request->home_server->stats.total_requests += request->num_proxied_requests;
270         break;
271 #endif
```

auth-packets increase

**Comment by jpereira** [comment]
@alandekok https://github.com/FreeRADIUS/freeradius-server/pull/1343

**Comment by jpereira** [comment]
@alandekok I found another issue.... more critical! #1346

**Comment by jpereira** [comment]
I have checked about the numbers, and now after our fixes. It's completely correct! nice job! :)
