### ISSUE TITLE
Minor problem with conditional xlat of reply:Packet-Type

### ISSUE THREAD

**Issue by skids** [FreeRADIUS/freeradius-server#1358]
The specific attribute reply:Packet-Type (perhaps some others) does not behave nicely in
conditional unlang xlat constructs when called before there is a reply, e.g. when logging initial
Access-Request packets.  It return a truthy "0" instead of falling over to the other
side of the disjunction.

This is no big deal for me; just was worth noting.  As a workaround I use this:

linelog track_log {
    # If there is no reply, reply:Packet-Type is "0" rather than a value
    # that can be used as a condition, unfortunately.  Future-proof it against
    # any bugfixes which may make reply:Packet-Type false.
    reference = "messages.%{%{reply:Packet-Type}:-0}-%{Virtual-Server}"
    messages {
       0-main  = "blah"
       ...
    }
}

**Comment by arr2036** [comment]
Mmm I can see why that might be.  Should be easy to fix...

**Comment by arr2036** [comment]
v3.1.x only.  Because this would be a breaking change.
