### ISSUE TITLE
Radius server Crashes Often

### ISSUE THREAD

**Issue by als90767** [FreeRADIUS/freeradius-server#1360]
Freeradius server crases often with the below error, 

Oct 28 12:44:38  kernel: radiusd[25932]: segfault at 00002b43360b5000 rip 00000038ea47b4bb rsp 00002b43360b29b8 error 4

Please let me know how to fix this.

We currently use FreeRADIUS Version 2.1.11. Do we need to upgrade to get rid of these errors?

**Comment by arr2036** [comment]
yes

**Comment by als90767** [comment]
to which version shall i upgrade as i already use this for a huge set of VPN users integrated with Cisco and Checkpoint VPN devices.

**Comment by arr2036** [comment]
http://freeradius.org/download.html 2.2.9 if you want to maintain compatibility, 3.0.10 if you don't mind reworking your config files.

**Comment by jpereira** [comment]
@als90767 v3.0.x is really awesome!

**Comment by als90767** [comment]
Thanks for your suggestions everyone!
