### ISSUE TITLE
Unable to authorize on freeradius when get users from openldap md5

### ISSUE THREAD

**Issue by marius111** [FreeRADIUS/freeradius-server#1376]
I have problem with freeradius, when I try login with MD5 or another crypt, I can't login to WiFi. When I use Cleartext-Password then I can login. Users are in openldap. In another system I can login with ldap when is Cleartext-Password or MD or another crypt.

http://stackoverflow.com/questions/33550233/unable-to-authorize-on-freeradius-when-get-users-from-openldap-md5

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
