### ISSUE TITLE
Problems with option log { request = .... }

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1384]
Hi,

   If enabled the option

```
#  The attribute that the value is assigned to is unimportant,
#  and should be a "throw-away" attribute with no side effects.
#
requests = ${logdir}/radiusd-%{%{Virtual-Server}:-DEFAULT}-%Y%m%d.log
 
```

We get the behavior

```
root@lab:/etc/freeradius# freeradius -C
radiusd: Error: Failed to parse log{} section.
root@lab:/etc/freeradius# 
```

**Comment by arr2036** [comment]
Want to send a patch? :)  Happy to explain any areas of the code that are confusing...

**Comment by alandekok** [comment]
It works for me in 3.0 and 3.1.

Use `radiusd -XC` to get more error messages.

**Comment by arr2036** [comment]
I've reproduced it

**Comment by jpereira** [comment]
Its the point. Using the -XC dont reproduce error, but the server not start.

**Comment by gyx1000** [comment]
Requests param is flagged as deprecated.
https://github.com/FreeRADIUS/freeradius-server/blob/v3.1.x/src/main/mainconfig.c#L112

Section parsing fail for this.

**Comment by alandekok** [comment]
The simple solution is to remove that configuration item from the default configuration file.

**Comment by alandekok** [comment]
Fixed.
