### ISSUE TITLE
dictionary problem

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1397]
have following entries in  /etc/raddb/dictionary

ATTRIBUTE       Network-Type            3000    string
ATTRIBUTE       User-Type               3001    string

(distor provided 3000/3001 commented out)

have this error:

Errors reading /etc/raddb/dictionary: fr_dict_init: /etc/raddb/dictionary[51]: fr_dict_attr_add: Failed adding 'Network-Type': Attributes must have value between 1..255

**Comment by alanbuxey** [comment]
and same happens with default:

Errors reading /etc/raddb/dictionary: fr_dict_init: /etc/raddb/dictionary[47]: fr_dict_attr_add: Failed adding 'My-Local-String': Attributes must have value between 1..255

ATTRIBUTE	My-Local-String		3000	string
ATTRIBUTE	My-Local-IPAddr		3001	ipaddr
ATTRIBUTE	My-Local-Integer	3002	integer

**Comment by arr2036** [comment]
they should be marked up as internal. Maybe it's a dictionary mismatch?

**Comment by arr2036** [comment]
Ah, no they're just missing the internal flag, i'll push a fix.

**Comment by arr2036** [comment]
The internal flag allows the full 32bit attribute numbers to be used.  Once we've finished redoing the infrastructure to allow per-protocol dictionaries (it's almost there) we can remove the flag again.

**Comment by jpereira** [comment]
@alandekok please, cherry-pick in v3.0.x

**Comment by arr2036** [comment]
@jpereira we don't use the internal flag in v3.0.x

**Comment by jpereira** [comment]
(y)
