### ISSUE TITLE
Exec-Program output: Reply-Message="NAS not found!"

### ISSUE THREAD

**Issue by bgobi1991** [FreeRADIUS/freeradius-server#1408]
Hi Team,

When i run the debug mode, i will displaying "NAS not found!". How can i fix this ?

**Comment by alandekok** [comment]
Questions belong on freeradius-users mailing list.

**Comment by bgobi1991** [comment]
Hi Team,
Can you exact link ? Please share the solution

**Comment by alanbuxey** [comment]
Questions belong on freeradius-users mailing list.  not here.
