### ISSUE TITLE
Problems to use the libfreeradius-radius with distributed headers

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1412]
Hi,

  I created a sample using libfreeradius-radius and the distribuitted headers. but, isn't possible to build. I believe that is necessary to review the policies of headers.

```
[jpereira@jpereira-desktop sample]$ cat radius-sample1.c
#include <freeradius/libradius.h>
#include <freeradius/conf.h>
#include <freeradius/radpaths.h>

static char  const *radius_dir = RADDBDIR;
static char  const *dict_dir = DICTDIR;

int main() {
        printf("Using libfreeradius-radius.so\n");

        if (fr_check_lib_magic(RADIUSD_MAGIC_NUMBER) < 0) {
                fr_perror("radclient");
                return 1;
        }

        if (dict_init(dict_dir, RADIUS_DICTIONARY) < 0) {
                fr_perror("radclient");
                return 1;
        }

        if (dict_read(radius_dir, RADIUS_DICTIONARY) == -1) {
                fr_perror("radclient");
                return 1;
        }
        printf("done\n");
        return 0;
}
[jpereira@jpereira-desktop sample]$ cat Makefile
all:
        gcc -o radius-sample1 radius-sample1.c -lfreeradius-radius -L/usr/lib/freeradius -Wl,-R/usr/lib/freeradius
[jpereira@jpereira-desktop sample]$
```

Can't build
```
[jpereira@jpereira-desktop sample]$ make
gcc -o radius-sample1 radius-sample1.c -lfreeradius-radius -L/usr/lib/freeradius -Wl,-R/usr/lib/freeradius
In file included from /usr/include/freeradius/libradius.h:32:0,
                 from radius-sample1.c:9:
/usr/include/freeradius/build.h:13:64: fatal error: freeradius/autoconf.h: No such file or directory
compilation terminated.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
[jpereira@jpereira-desktop sample]$
```

p.s: I have bypassed this problem, pointing directly to the source-dir.

**Comment by jpereira** [comment]
@arr2036 and @alandekok

**Comment by jpereira** [comment]
@alandekok and @arr2036, What do you think about to change the sdk/headers dir to "$incdir/libfreeradius"?

**Comment by jpereira** [comment]
It's possible to use a single ```#include <freeradius-devel/libradius.h>``` using the patch #1414 

About the path, My bypass is: 

```
# cd /usr/include
# ln -fs freeradius freeradius-devel
```

**Comment by arr2036** [comment]
Including autoconf.h is bad practice, if you look in missing.h the header there performs substitutions based on the values in autoconf.h.  Really all values used from autoconf.h used in libfreeradius should be there.

I think autoconf.h was originally only included in build.h, and build.h was only passed in to the compiler. If either build.h or autoconf.h is included explicitly, that should be removed.

**Comment by jpereira** [comment]
I got it and agree with you. I sent the pull request #1414 that fix some issues. I will check the behavior when remove the build.h

**Comment by jpereira** [comment]
now works fine!
