### ISSUE TITLE
rlm_python module problem

### ISSUE THREAD

**Issue by lark** [FreeRADIUS/freeradius-server#1413]
When adding customized OTP (using challenge) logic, it's clear that rlm_python module is incomplete and not much useful:
1. document is sparse and incomplete, mostly guess work.
2. no state support
3. tuple is not easy to use, and not intuitive

I used rlm_perl to fulfil the task. I suggest that either nuke rlm_python or improve it. For people who are familiar with python, they would begin with rlm_python and waste much time in the end.

For me, I am more familiar with perl and fine with perl, only concerned about memory usage and leakage (my concern may be outdated), so I began with rlm_python.

**Comment by arr2036** [comment]
You understand that this is an open source project, and so you are expected to help improve it if you find it's lacking?

**Comment by alandekok** [comment]
I suggest submitting patches to fix it.
