### ISSUE TITLE
Ignoring request to authentication address * port 1812 from unknown client 127.0.0.1 port 32808

### ISSUE THREAD

**Issue by bgobi1991** [FreeRADIUS/freeradius-server#1436]
Hi Team,

When i connect the user it showing: radtest user 1111 127.0.0.1 1812 secret123

Ignoring request to authentication address * port 1812 from unknown client 127.0.0.1 port 32808

**Comment by swoga** [comment]
Hello,

do you have added 127.0.0.1 to the clients.conf?

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.

**Comment by bgobi1991** [comment]
Hi Team,

No i didn't added.
