### ISSUE TITLE
rmauth.c line 615

### ISSUE THREAD

**Issue by bgobi1991** [FreeRADIUS/freeradius-server#1450]
Hi Team,

When i Run the radius in debug mode it was returned,

rmauth.c line 615: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 1' at line 1

How can i fix this ?

![Uploading image.png…]()
![error](https://cloud.githubusercontent.com/assets/9972138/11765906/fe8aa66e-a192-11e5-87c1-4dc0ff348188.png)

**Comment by alanbuxey** [comment]
use the freeradius users mailing list , not the GIT system for such queries

on the list, provide your debug output and the config bit where it is
failing , from the output it looks like you've messed up your SQL query
exactly as the server is telling you.

alan

**Comment by alandekok** [comment]
It's ridiculous to post  a screenshot instead of just the debug text.  Is it really that hard to cut & paste text?

And Buxey is right.  Questions about misconfigurations belong on the mailing list.  This isn't an appropriate issue for github.
