### ISSUE TITLE
Python module inserts extra " in string attribute values

### ISSUE THREAD

**Issue by alejandro-perez** [FreeRADIUS/freeradius-server#1452]
For instance, when you receive the User-Name attribute, you get the following:
('User-Name', '"alex@um.es"')

The reason is found in rlm_python.c, where either 	vp_prints_value(buf, sizeof(buf), vp, '"'); (3.0.x) or 	fr_pair_value_snprint(buf, sizeof(buf), vp, '"'); (3.1.x) is used. 

Why is the quote character being given? I think passing 0 (no quote char) would be better.

Regards

**Comment by alejandro-perez** [comment]
In fact, is passing a "printed" version of a string value the best choice for passing string attributes to python modules?

**Comment by herwinw** [comment]
I think the scariest thing about this is how this is used within the `prepaid.py` example

```
  # Build and log the SQL statement
# radiusd puts double quotes (") around the string representation of
# the RADIUS packet.
sql = 'select passwd, maxseconds from users where username = ' +  userName
```

**Comment by alejandro-perez** [comment]
Right. At the end it is just an example, but I cannot understand when did this sound like a good idea :). 
In my module, I have to attribute = attribute[1:-1] just to remove the trailing and tailing ".

**Comment by alejandro-perez** [comment]
Also, and related to the same issue, string values are passed escaped, with \" for any inner quotation character. And binary data is passed as a string, with leading "\x" and hexadecimal representation. Is this intended?

**Comment by alandekok** [comment]
It's accidental.  It should be fixed.

**Comment by alandekok** [comment]
Is this fixed with the recent re-write of rlm-python?

**Comment by arr2036** [comment]
Yes
