### ISSUE TITLE
OP codes in rlm_python radiusd module do not match those from token.h 

### ISSUE THREAD

**Issue by alejandro-perez** [FreeRADIUS/freeradius-server#1467]
They are out of sync, thus produce mistaken results. In particular, the '++' operator was missing, hence everything after that value has shifted.

They should be 
```
OP={       '{':2,   '}':3,   '(':4,   ')':5,   ',':6,   ';':7,  '++': 8, '+=':9,  '-=':10,  ':=':11,
  '=':12, '!=':13, '>=':14,  '>':15, '<=':16,  '<':17, '=~':18, '!~':19, '=*':20, '!*':21,
 '==':22 , '#':23 }
```

**Comment by arr2036** [comment]
Want to send a PR?

**Comment by arr2036** [comment]
or maybe @mcnewton can ;)

**Comment by herwinw** [comment]
https://github.com/herwinw/freeradius-server/commit/61d471669e1998acc30663fa2aca35ce510b4435

That commit (and all other commits from #1459) can safely be backported to v3.0.x, and that would solve the problem too.

The whole array was kind of ridiculous: it exists in a file that "should only be used when testing modules, Inside freeradius, the 'radiusd' Python module is created by the C module and the definitions are automatically created.) but that part wasn't. Its only use was to allow an easy was to convert operations to lists (`Tmp-String-0 := foo`) to the format that was understood by `rlm_python` (`('Tmp-String-0', 10, 'foo')`).  The linked commit makes the required format easier (`(Tmp-String-0`, ':=', 'foo')`) and removes the need for this constant.

**Comment by alejandro-perez** [comment]
Great, thanks!

**Comment by arr2036** [comment]
@herwinw can you open a pull request to backport the relevant commits?

**Comment by alandekok** [comment]
commit 61d4716 doesn't apply cleanly.  We'd like to release 3.0.11 soon, so having these fixes back-ported would be great.

**Comment by arr2036** [comment]
They're now all backported
