### ISSUE TITLE
sql database table 'attribute' column problem

### ISSUE THREAD

**Issue by peterwillcn** [FreeRADIUS/freeradius-server#1472]
```
+-----------+------------------+------+-----+---------+----------------+
| Field     | Type             | Null | Key | Default | Extra          |
+-----------+------------------+------+-----+---------+----------------+
| id        | int(11) unsigned | NO   | PRI | NULL    | auto_increment |
| attribute | varchar(64)      | NO   |     |         |                |
......
+-----------+------------------+------+-----+---------+----------------+

The four table has' attribute '   attribute varchar(64)  NOT NULL default '',
# Table structure for table 'radcheck'
# Table structure for table 'radgroupcheck'
# Table structure for table 'radgroupreply'
# Table structure for table 'radreply'
```
In some languages is a reserved word, can change (**attribute**) a name to (such as: **attr**)?
such as see https://github.com/rails/rails/issues/22810

**Comment by alandekok** [comment]
You're free to change the schema and queries yourself.

If other languages get confused by SQL column names, then those languages are broken.

**Comment by peterwillcn** [comment]
@alandekok  Cool....Yeah..freeradius-server is a great software..... great great great great
I find solve it at $INCLUDE ${modconfdir}/${.:name}/main/${dialect}/queries.conf
#authorize_check_query = "\
#	SELECT id, username, attribute, value, op \
#	FROM ${authcheck_table} \
#	WHERE username = BINARY '%{SQL-User-Name}' \
#	ORDER BY id"

#authorize_reply_query = "\
#	SELECT id, username, attribute, value, op \
#	FROM ${authreply_table} \
#	WHERE username = BINARY '%{SQL-User-Name}' \
#	ORDER BY id"

**Comment by emrahyildirim** [comment]
Hello there,

Are we going to make the same changes to schema.sql. Or is it just me

respects
