### ISSUE TITLE
Escaping attributes expanded in to a regex

### ISSUE THREAD

**Issue by nicklowe** [FreeRADIUS/freeradius-server#1474]
I have been working to iterate and improve the spoofing protection implemented in policy.d/filter
Work in progress here: 
[filter.txt](https://github.com/FreeRADIUS/freeradius-server/files/74921/filter.txt)

One aspect that concerns me is expanding a user supplied value in to a regular expression and ensuring that appropriate escaping has taken place to do this safely.

In Alan's code we have:
(&Inner-Realm-Name !~ /\\.%{Outer-Realm-Name}$/)) {

Outer-Realm-Name here should be escaped before being used in the regex.
When we look at the expansion, however, we see domain.com$ and not domain\\.com$

The issue here is that the value must be escaped to do this safely and reliably.

This engenders two questions:

If an attribute is expanded in to a regex, should it be escaped automatically for safety?

If not, should there be an equivalent that can be called?

Escaping should be something akin to Microsoft's Regex.Escape (.NET):
https://msdn.microsoft.com/en-gb/library/system.text.regularexpressions.regex.escape(v=vs.110).aspx

**Comment by alandekok** [comment]
The xlat expansion has provisions for an escape function.  The regex code should pass a "regex escape" function, which escapes all of the special regex characters: `.`, `$`, `[`, etc.

**Comment by arr2036** [comment]
Yep, agreed, and allow /&ref/ for completeness.

**Comment by alandekok** [comment]
/&ref/ can be done in a future commit.
