### ISSUE TITLE
Case statements should allow regex matches

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#1486]
If we're going to allow all kinds of crazyness in case statements (instead of just literal values)  they should be created as templates, and the code updated to allow things like regex comparisons.

e.g,

``` text
switch &DHCP-Subscriber-Id {
    case /(abc)$/ {
        update control {
            &Pool-Name := “abc"
        }
    }
    case {
        update control {
            &Pool-Name := “def"
        }
    }
}
```

Hopefully they're all compiled as conditions already, which would make this enhancement quite easy.

**Comment by alandekok** [comment]
compile_modcase() calls tmpl_afrom_str().  Which should handle regexes.

The parser won't allow `/foo/` as name2 for CONF_SECTIONs, so that needs fixing.

modcall_switch() should then handle the regex with no changes.

**Comment by alandekok** [comment]
conffile.c calls getword(), which returns T_BARE_WORD, T_BACK_QUOTED_STRING, or T_DOUBLE_QUOTED_STRING.  It doesn't do regex parsing.  So we'll have to update the parser to look for "case", then '/', and do regex parsing from there.

**Comment by alandekok** [comment]
If we're going to allow multiple `case` statements e.g. #1324 or regex matches... we might as well just allow the "case" statements to have conditions:

    case (a || b || c || d) {
        ...
    }

Which makes them entirely equivalent to "if" statements.

TBH, I'm inclined to close both this issue and #1324 as "nice, but not necessary".

**Comment by arr2036** [comment]
FWIW I'm against allowing anything except comparison against literals in case statements.

**Comment by alandekok** [comment]
After some further discussion, this is a bad idea.  We now use `tries`, or `hash` or `rbtrees` for the values of the `case` statements.
