### ISSUE TITLE
Ip address pool defined between a plurality of sets

### ISSUE THREAD

**Issue by houhuijian** [FreeRADIUS/freeradius-server#1490]
Defines several default groups freeradius of user files, including group 1, group 2, group 1 is assigned the Framed-IP-Address = 192.168.70.241+, Group 2 is assigned the Framed-IP-Address = 192.168.80.253+ after two user logon group 2 were assigned 192.168.80.253 and 192.168.80.254, in the case of group 2 users have been online, a user group 1 Log, arguably should allocate 192.168.70.241, but get real address has turned out 192.168.70.243, will this case there is no solution? Then I thought of using ippool, I define ippool file in a pool, the name is yunwei, refer to the ippool files in user group 1: yunwei, but the situation is not right, I set the range-start: 192.168.70.240 , range-stop: 192.168.70.245, but in the case of group 2 users continue to log on, the address of a user group 1 is obtained after login 192.168.70.250, this case is there any solution?

**Comment by arr2036** [comment]
https://github.com/FreeRADIUS/freeradius-server/blob/v3.1.x/CONTRIBUTING
