### ISSUE TITLE
graceful shutdown

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1497]
when shutting down FreeRADIUS, it would be good if the shutdown (not kill -9 stuff) could act in a graceful way with some form of timer.

I was thinking

1) server stops responding to Status-Server  (remote sites then stop talking)

2) any requests that come through - server checks if its part of an ongoing conversation (EAP), if so, deal with it so authentication completes, if not, no not respond.

3) close down of sockets/connections

4) snmp-traps and/or other external script can be fired off to allow site admin to cook other things up upon the server going (eg change/update keepalived et al....)

**Comment by arr2036** [comment]
You can do a lot of that today via an external script.  Certainly controlling responses to status-server requests can be done via the radmin socket.  So stop it responding, wait 30 seconds for LB to mark as down, stop server.

@alandekok and I have discussed a future design for the server that would make a lot of this redundant, so don't really want to invest much effort into it.

**Comment by alandekok** [comment]
> 2) any requests that come through - server checks if its part of an ongoing conversation (EAP), if so, deal with it so authentication completes, if not, no not respond.

This would also mean ignoring any new packets.  Which makes the NAS think that the server is down.

i.e. "graceful shutdown" is almost impossible to do.

> ) snmp-traps and/or other external script can be fired off to allow site admin to cook other things up upon the server going (eg change/update keepalived et al....)

The server already has a "shutdown" SNMP trap.  See raddb/trigger.conf

I think any "clean" shutdown is almost impossible.  The server just can't respond to "ongoing" requests, while ignoring "new" requests.  RADIUS just doesn't work that way.
