### ISSUE TITLE
github release marker still pointing at 3.0.9

### ISSUE THREAD

**Issue by sthen** [FreeRADIUS/freeradius-server#1506]
Hi, on https://github.com/FreeRADIUS/freeradius-server/releases there's a "latest release" marker which is still pointing at 3.0.9 with the newer releases being hidden behind a [+] on the page by default. I'm not entirely sure (and github's documentation is poor on this), but I think this may be because the newer ones don't have release notes whereas 3.0.11 does.

**Comment by arr2036** [comment]
Fixed, thanks.
