### ISSUE TITLE
Can we get Freeradius 3.x on Trusty without building from source?

### ISSUE THREAD

**Issue by iblazevic** [FreeRADIUS/freeradius-server#1508]
Hi,

we are using freeradius in our latest project and I noticed that apt-get installs older version that is clearly not maintained anymore from the docs.

I'm wondering can we expect the latest version (3.x) being in the package manager soon or is building from source only option to get latest. We are using trusty(ubuntu 14.04).

We can build it from source but just wondering if we can avoid that.

Thanks

**Comment by alandekok** [comment]
Please ask the Ubuntu people about their packages.  We don't control them.
