### ISSUE TITLE
When using dialog 'mssql', receiving Invalid column name 'priority'

### ISSUE THREAD

**Issue by gbeaudoin78** [FreeRADIUS/freeradius-server#1513]
When using the 'mssql' dialog, SQL queries in queries.conf references an inexisting column priority in table radusergroup.

ERROR: (8) sql: ERROR: rlm_sql_freetds: Server msg from "MSSQL": severity(207), number(16), origin(1), layer(1), procedure "none": Invalid column name 'priority'

**Comment by arr2036** [comment]
Could you send a patch to add it to the default schema? :+1:

**Comment by gbeaudoin78** [comment]
Thanks you so much! I'm happy to see FreeTDS getting the stable status too, it's a nice bonus.
