### ISSUE TITLE
Issue with rlm_sql_sqlite.c

### ISSUE THREAD

**Issue by als90767** [FreeRADIUS/freeradius-server#1515]
Hello Experts,

I'm installing the latest freeradius(3.0.11) and I have got the below exception. Can you please help me on resolving this?

src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c:48: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘sqlite_int64’
src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c: In function ‘_sql_greatest’:
src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c:514: error: ‘sqlite3_int64’ undeclared (first use in this function)
src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c:514: error: (Each undeclared identifier is reported only once
src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c:514: error: for each function it appears in.)
src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c:514: error: expected ‘;’ before ‘value’
src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c:517: error: ‘value’ undeclared (first use in this function)
src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c:518: error: ‘max’ undeclared (first use in this function)
make: *** [build/objs/src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.lo] Error 1

**Comment by herwinw** [comment]
```
#ifndef HAVE_SQLITE3_INT64
typedef sqlite3_int64 sqlite_int64;
#endif
...
sqlite3_int64 value;
```

Looks like that typedef has gotten  its argument in the wrong order. But building with a more recent version of sqlite will probably fix your build too.

**Comment by als90767** [comment]
that did the trick! Thanks a lot!
