### ISSUE TITLE
FreeBSD: Recognizes 10 as 1

### ISSUE THREAD

**Issue by matsimon** [FreeRADIUS/freeradius-server#1517]
aclocal.m4 wrongly detects FreeBSD 10 as FreeBSD 1, but since it's an issue that many FreeBSD ports were hit with an auto-fix has existed in the ports tree for a longer period.

The auto-applied fix is as follows:
```
--- aclocal.m4  2016-01-25 19:27:03.000000000 +0100
+++ aclocal.m4.freebsd10        2016-02-02 09:09:41.933878851 +0100
@@ -2392,7 +2392,7 @@
   shlibpath_var=LD_LIBRARY_PATH
   ;;

-freebsd1*)
+freebsd1.*)
   dynamic_linker=no
   ;;

@@ -2403,7 +2403,7 @@
     objformat=`/usr/bin/objformat`
   else
     case $host_os in
-    freebsd[[123]]*) objformat=aout ;;
+    freebsd[[123]].*) objformat=aout ;;
     *) objformat=elf ;;
     esac
   fi
@@ -5096,7 +5096,7 @@
       _LT_TAGVAR(hardcode_shlibpath_var, $1)=no
       ;;

-    freebsd1*)
+    freebsd1.*)
       _LT_TAGVAR(ld_shlibs, $1)=no
       ;;

@@ -6119,7 +6119,7 @@
         esac
         ;;

-      freebsd[[12]]*)
+      freebsd[[12]].*)
         # C++ shared libraries reported to be fairly broken before
        # switch to ELF
         _LT_TAGVAR(ld_shlibs, $1)=no
```

I'm not familiar with autotools but aclocal.m4 says that it was generated with aclocal. However the aclocal.m4 generated by simply executing _aclocal_ (1.15) is not only much shorter but removes all the references to different operating systems, leaving me with the guess that something else must be done. (I just don't know how and haven't easily found a reference)

aclocal.m4 wasn't touched for a number of years and it might be better to properly regenerate it for the longer run but the diff already works around the issue. What do you prefer?

**Comment by alandekok** [comment]
Does the `configure` script do anything wrong?

As best I can tell, the aclocal.m4 file isn't used for anything.  We can probably delete it, and call it done.

**Comment by arr2036** [comment]
might be used as an implicit include when regenerating the configure script

**Comment by matsimon** [comment]
Concerning the question of @alandekok - it doesn't seem so. However when I executed ```autoreconf``` before building  _configure_ and _aclocal.m4_ get regenerated therefore I think @arr2036 is guessing in the right direction.

I tried following:
- v3.0.x branch passes ```configure --prefix=/tmp/tempbuild```, ```gmake```  and ```gmake install```
  - As is and regenerated _configure_  (based on 9280f695db5d893ffce950089dc1f0a49c06fe15)
- v3.1.x passes ```configure```, but fails at ```gmake``` 
  - Bot same with source as is and regenerated _configure_ (based on 34dbd26a2e6b363c5a028c1cd6964d95fa0769c6)
```
CC src/lib/cursor.c
CC src/lib/debug.c
CC src/lib/dict.c
In file included from /usr/include/_ctype.h:94:0,
                 from /usr/include/ctype.h:46,
                 from src/lib/dict.c:30:
/usr/include/runetype.h:92:22: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'const'
 extern _Thread_local const _RuneLocale *_ThreadRuneLocale;
                      ^
/usr/include/runetype.h: In function '__getCurrentRuneLocale':
/usr/include/runetype.h:96:6: error: '_ThreadRuneLocale' undeclared (first use in this function)
  if (_ThreadRuneLocale)
      ^
/usr/include/runetype.h:96:6: note: each undeclared identifier is reported only once for each function it appears in
scripts/boiler.mk:635: recipe for target 'build/objs/src/lib/dict.lo' failed
gmake: *** [build/objs/src/lib/dict.lo] Error 1
```

As I initially wrote, I'm definitely far from being familiar with the whole autotools family.
Is it causing build failure as is? Not visibly to me right now but lots of software fails typically if identified as FreeBSD 1 on FreeBSD 10 since the historical version didn't support dynamic linking.

If it doesn't break things, what about regenerating configure scripts anyway after some years?

**Comment by alandekok** [comment]
`autoreconf` re-generates a bunch of things.  We don't use them all, though.  Looking at the contents of `aclocal.m4`, it seems to mainly contain libtool-specific things.  And we don't use libtool.  I'm pretty sure that we can just delete `aclocal.m4` and move on with our lives.

The build error is something different.  The `_Thread_local` definition is found in another header file.  Which one, I don't know.

**Comment by matsimon** [comment]
I see, so what about me executing just ```aclocals```` which regenerates _aclocal.m4_ and offering a pull request (after doing build tests on FreeBSD and Debian, that's what I can offer)?
This would remove those very old references anyway.

The FreeBSD guys are trying to filter out and once in a day trying to remove that auto-patching thing in their ports tree that's why :-)

**Comment by alandekok** [comment]
A pull request like that would be appreciated.

**Comment by matsimon** [comment]
OK, aclocal 1.14.1 (as in Debian jessie) was executed inside the source 
 * of 3.0.x at 39149cb2537fa29c018527b26e470ea70ff04679
 * of 3.1.x at  bb066b54df49d1848d579c5d6f1fcec67885c6e0

Then a quick build with configure prefix =/opt/aclocal-3[0|1] and a trying to launch "radiusd -X" check was done on:

* FreeBSD 10.2-RELEASE-p12, as the one being mentioned in this issue
  * v3.1.x build fails with the earlier mentioned error (better handled in another bugreport)
  * v3.0.x builds and runs. 
* Debian jessie, gcc 4.9.2 (representing a rather conservative Linux distribution)
 * Builds and runs on both branches

I wanted to give OmniOS (illumos based, "Solarish" OS) a try but given the instructions for Oracle Solaris already contain some extra hoops I didn't go further. If you want to see an additional distribution or OS, I'll see what I can do.

It doesn't seem that this has shown negative impact. If you think that this is sufficient, I'll go ahead an open pull requests against both branches.
