### ISSUE TITLE
International chars (unicode) in pwd fail when remote

### ISSUE THREAD

**Issue by cuph62** [FreeRADIUS/freeradius-server#1522]
Hello,
I am having issues with international, accented characters like éèçà€  in authenticating via rlm_perl
eg using password Azértè01:
When testing locally (on same box as freeradius server) with radclient this works fine:

rlm_perl: urlparam pass = Azértè01    ---> ok
====
When I do the same using a remote tool (eg Cisco AnyConnect , NTRadping) 
I receive:

rlm_perl: urlparam pass = Az\351rt\35001 ---> nok

Has anybody experienced this too -
Is this a unicode issue, that I should tackle in the perl module ?

kind regards,
Herman

**Comment by alandekok** [comment]
FreeRADIUS is UTF-8 clean.  Other software isn't.

If radclient works and the other software doesn't work, the other software is broken.
