### ISSUE TITLE
radnas table (sql) reload

### ISSUE THREAD

**Issue by giulianozorzi** [FreeRADIUS/freeradius-server#1534]
Hi,
i've search but I've found no recent answers to the (old) question about reloading the naslist from sql without restarting the whole server. Is there any news about that ? I'm ok with a realtime check so I can use fb stored functions to decide if the nas is enabled or not (like number of authentications per day or something similar)

thanks

giuliano

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.

And this *is* documented.
