### ISSUE TITLE
Could not link driver rlm_sql_mysql

### ISSUE THREAD

**Issue by kuertianshi** [FreeRADIUS/freeradius-server#1539]
System:Centos 6.6
freeradius 3.1.X
mysql 5.6.15

How to fix this? I cant find rlm_sql_mysql.so in system.

log:
rlm_sql (sql) - Could not link driver rlm_sql_mysql: /usr/local/freeradius/lib/rlm_sql_mysql.so: cannot open shared object file: No such file or directory : rlm_sql_mysql.so: cannot open shared object file: No such file or directory
rlm_sql (sql) - Make sure it (and all its dependent libraries!) are in the search path of your system's ld
/usr/local/freeradius/etc/raddb/mods-enabled/sql[19]: Instantiation failed for module "sql"

**Comment by alandekok** [comment]
This is documented.  Usability questions belong on the freeradius-users mailing list.

**Comment by stevejohn82** [comment]
"This is documented. Usability questions belong on the freeradius-users mailing list."
link please?
I got the same error

**Comment by alanbuxey** [comment]
http://freeradius.org/list/users.html

**Comment by stevejohn82** [comment]
thnx alanbuxey

**Comment by alvin-kiveu** [comment]
how did you fix this cause am also getting the same error Could not link driver rlm_sql_mysql: libmariadb.so.3: cannot open shared object file: No such file or directory
Make sure it (and all its dependent libraries!) are in the search path of your system's ld
/etc/raddb/mods-enabled/sql[27]: Instantiation failed for module "sql"
