### ISSUE TITLE
Typo in deny_realms policy example

### ISSUE THREAD

**Issue by wichert** [FreeRADIUS/freeradius-server#1543]
I saw this in FreeRADIUS 2, but I am guessing this still holds for FreeRADIUS 2. 

raddb/policy.d/filter contains this example:

```
deny_realms {
	if (&User-Name && (&User-Name =~ /@|\\/)) {
		reject
	}
}
```

Trying to use that policy gives this result:

```
++- entering policy deny_realms {...}
+++? if (User-Name =~ /@|\\/)
ERROR: Failed compiling regular expression: Trailing backslash
++- policy deny_realms returns ok
```

The error here is that doubly-escaping is necessary here: once for unlang processing, and another for the regexp itself. 

The corrected version is:

```
deny_realms {
	if (&User-Name && (&User-Name =~ /@|\\\\/)) {
		reject
	}
}
```

**Comment by alandekok** [comment]
That's a typo in v2.  I'll fix it there.  In v3, it's correct.  We've gone through and fixed all of the escaping problems in v3.

**Comment by matsimon** [comment]
If I read this bug report, this issue should be resolved by Alan's commit. -> Close?
