### ISSUE TITLE
mschap: Unpacked MS-CHAP-NT-Enc-PW length > 516

### ISSUE THREAD

**Issue by etokaoru** [FreeRADIUS/freeradius-server#1549]
I got this error when changing password with PEAP(MS-CHAPv2) on freeradius 3.0.11.

But, my 'MS-CHAP-NT-Enc-PW length' **equals** 516.
  
From rlm_mschap.c　line 1728 is as follows
`if ((new_nt_enc_len + nt_enc->vp_length - 4) >= sizeof(new_nt_encrypted)) {`

But I guess it should be
`if ((new_nt_enc_len + nt_enc->vp_length - 4) > sizeof(new_nt_encrypted)) {`

Please confirm if it’s correct.

I'm sorry for my poor English.

**Comment by alandekok** [comment]
Fixed by commit 5ca86674969
