### ISSUE TITLE
ldap Problem with cn

### ISSUE THREAD

**Issue by lrafg** [FreeRADIUS/freeradius-server#1553]
OS: Debian 8.3
freeraidus Package  2.2.5+dfsg-0.2
Active Directory Windows Server 2008 R2

Problem: If authorization with ldap against Active Directory is configured freeradius doesn't find the user in the corresponding group.

Cause:
After some tests I found out that the problem occures if the cn of the user object has the syntax "lastname, firstname" without the quotes for example : "Miller, John"

In the case Active Directory ldap saves this dn of the user object  "CN=Miller\, John,OU=Users,OU=company,DC=example,DC=local" with that backslash!
In the AD Group the member attribute has the same value "CN=Miller\,  John,OU=Users,OU=company,DC=example,DC=local"

freeradius does the ldap request that proves the group object for a member attribute with the corresponding user dn.
I only show the part that is relevant for the problem:
(member\3dCN\3dMiller\5c\5c\2c John\2cOU\3dUsers\2cOU\3dcompany\2cDC\3dexample\2cDC\3dlocal)

I found out that the request must be with 3 backslashes
(member\3dCN\3dMiller\5c\5c\5c\2c John\2cOU\3dUsers\2cOU\3dcompany\2cDC\3dexample\2cDC\3dlocal)

If I change the dn of the user object in a value aithout comma the ldap check succeeded.

Would you please fix that?

regards

Ralph

**Comment by alandekok** [comment]
Version 2.2 is EOL.  The only issues we're fixing are critical security ones.

If you upgrade to 3.0, this problem is fixed there.
