### ISSUE TITLE
Freeradius compile error

### ISSUE THREAD

**Issue by MrDini123** [FreeRADIUS/freeradius-server#1554]
Hi!

I have got an arm5 based nas, a ZyXEL NSA320S. I compiled the freeradius-server-3.0.11.

I'm using this with a MySQL database.

It works nice, when I run a radtest, but when I try to connect to my router it shows the following:

http://pastebin.com/raw/xUhG1WtR

_talloc: double free error - first free may be at src/modules/rlm_eap/mem.c:71

Bad talloc magic value - double free

talloc abort: Bad talloc magic value - double free

Aborted_

What's wrong?

Thanks!

Ps.: sorry for my bad English...

Mod: Here is the gdb's output:

http://pastebin.com/raw/sEaY8BTX

**Comment by MrDini123** [comment]
Nobody Can help me?

Or I missed some information? In this case please tell me, what's missing and I'll attach it.

Thanks!

**Comment by arr2036** [comment]
You need to provide an actual backtrace with ``bt``

**Comment by MrDini123** [comment]
Thanks for your quick reply! :)

Here it is:

http://pastebin.com/raw/TR6miicw

**Comment by arr2036** [comment]
Can you reproduce this reliably?  I'm willing to bet it doesn't occur in v3.1.x.  All that code changed...

**Comment by MrDini123** [comment]
Hi!

Sorry for the late reply, but I was very busy on this week...

So I tried to compile and install the latest source from git, but it says this:

root@HomeServer:# radiusd -X
A newer kernel is required to run this binary. (__kernel_cmpxchg64 helper)
Aborted (core dumped)

Yes, I have 2.6.31.8 kernel. Is it possible to use freeradius on it? I hope this is just a configure mkstake.

Thanks!

**Comment by arr2036** [comment]
Probably have to recompile.  That error is definitely not coming from us.

**Comment by arr2036** [comment]
Ah, or maybe that's a C11 thing.

**Comment by arr2036** [comment]
Need to do what it says then ;)

**Comment by arr2036** [comment]
Hunting around, you need a kernel version >= 3.1.  Out of interest, is this on an embedded system?

**Comment by arr2036** [comment]
Yes, it is.  OK so the ARM architecture probably doesn't support the required atomic instructions, so the compiler is falling back to some kind of kernel emulation.

**Comment by alandekok** [comment]
Honestly for embedded systems... use 2.2.9.  You probably don't need the new features in 3.0.  And the compilers on embedded systems typically lag those on desktops.

**Comment by MrDini123** [comment]
I have got a zyxel nas with ffp. This nas has arm5 processor...

I Can't change the kernel on it without a ttl cable based reflash...

So is there a way to compile it without C11?

I have the latest gcc and uClibc installed if it is needed.

**Comment by MrDini123** [comment]
@alandekok

Ok, I will try to compile it.

Thanks!

**Comment by MrDini123** [comment]
Wow! The freeradius 2.2.8 works perfectly! :)

**Comment by alanbuxey** [comment]
..and 2.2.9 which *is* the latest 2.2.x release..... ?

**Comment by MrDini123** [comment]
Yes, nice question! :)

That was my first try, but it not worked. It sent reject for the first time and thr second time try it crashed without error message...

So I compiled the 2.2.8 which is works So cool! (All of the features)

**Comment by alanbuxey** [comment]
2.2.9 crashed?  send in bug report...or others will hit same error and
2.2.10 when released for security issues etc will have same bug....

alan

**Comment by MrDini123** [comment]
Sorry, but I already removed it, because it didn't said anything as I wrote.

And this is working now, So I don't want to remove it... But if I reinstall the nas, I'll try it and will come back with a bug report.
