### ISSUE TITLE
commit 8a7f6e330f45439d333f61dde7ee0982ebcc2a29 breaks Windows PEAP on 4.0.x

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1566]
commit 8a7f6e330f45439d333f61dde7ee0982ebcc2a29
Author: Arran Cudbard-Bell a.cudbardb@freeradius.org
Date:   Sun Dec 6 00:34:21 2015 -0500

```
Add additional debugging so we can track TLS fragments sent
```

:100644 100644 084fb69... aa50e65... M  src/modules/rlm_eap/libeap/eap_tls.c
:100644 100644 a9ce517... 800fc77... M  src/modules/rlm_eap/libeap/eap_tls.h
:100644 100644 cb0a560... 8d64335... M  src/modules/rlm_eap/libeap/eapcommon.c
:100644 100644 b418f31... 87fd937... M  src/modules/rlm_eap/rlm_eap.c
:100644 100644 becfa6c... 504ed01... M  src/modules/rlm_eap/types/rlm_eap_peap/peap.c
:100644 100644 887d0d1... 5958f0d... M  src/modules/rlm_eap/types/rlm_eap_peap/rlm_eap_peap.c

works (Windows PEAP/EAP-PEAP using either ntlm_auth or winbind) immediately before this commit, doesn’t work after.

MacOSX/wpa_supplicant etc all work after this commit which is probably the reason that this hasn't been noted before(!)

**Comment by arr2036** [comment]
Good find, thanks!

**Comment by alandekok** [comment]
We're rewriting all of this, or have already re-written this.
