### ISSUE TITLE
Sqlite driver: freezes the system

### ISSUE THREAD

**Issue by matahr** [FreeRADIUS/freeradius-server#1568]
> bad english

I do not know the reason but my system freezes in "authorize" stage; I added the following line in rlm_sql_sqlite.c resolves the failure.

handle- > row = NULL;

rlm_sql_sqlite.c  rlm_sql_postgres.c and comparing is the only thing different;

```
652 char **row;
653
654 *out = NULL;`
655
656 handle->row = NULL;
```
please check!

**Comment by alandekok** [comment]
I have no idea where this code is supposed to go.  Please include a patch.

**Comment by matahr** [comment]
```
--- a/src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c
+++ b/src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c
@@ -654,6 +654,8 @@ static sql_rcode_t sql_fetch_row(rlm_sql_row_t *out, rlm_sql_handle_t *handle, r
 
        *out = NULL;
 
+       handle->row = NULL;
+
        /*
         *      Executes the SQLite query and interates over the results
         */
```

**Comment by alandekok** [comment]
Which version of the server is this for?  There is no similar code in the v3.0.x branch.

Please try using the v3.0.x branch.  The problem appears to have been fixed a long time ago.

**Comment by matahr** [comment]
> Which version of the server is this for? There is no similar code in the v3.0.x branch.
> 
> Please try using the v3.0.x branch. The problem appears to have been fixed a long time ago.

 v3.1.x branch

https://github.com/FreeRADIUS/freeradius-server/blob/v3.1.x/src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c#L656
