### ISSUE TITLE
freeradius 3 segmentation fault

### ISSUE THREAD

**Issue by tkgit1** [FreeRADIUS/freeradius-server#1580]
``<junk from bash trace>``

**Comment by mcnewton** [comment]
That's an strace of bash running the init script, which doesn't help.

Please see the instructions to get a backtrace on http://wiki.freeradius.org/project/bug-reports

**Comment by tkgit1** [comment]
sorry

[root@vps ~]# gdb radiusd
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-83.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/radiusd...Reading symbols from /usr/lib/debug/usr/sbin/radiusd.debug...done.
done.
(gdb) run -xfl stdout
Starting program: /usr/sbin/radiusd -xfl stdout
[Thread debugging using libthread_db enabled]
radiusd: FreeRADIUS Version 3.0.3, for host i686-redhat-linux-gnu, built on Jun 10 2015 at 13:14:32
Copyright (C) 1999-2014 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
Starting - reading configuration files ...

Program received signal SIGSEGV, Segmentation fault.
talloc_chunk_from_ptr (ptr=0x81e, location=0xb7fd432c "src/main/conffile.c:1006") at ../talloc.c:349
349             if (unlikely((tc->flags & (TALLOC_FLAG_FREE | ~0xF)) != TALLOC_MAGIC)) {

**Comment by arr2036** [comment]
Version 3.0.3 has many known issues, if you're able to reproduce the defect with 3.0.11 then please open a new ticket.

Alternatively if you wish to only use RedHat supported versions of FreeRADIUS, then i'd suggest contacting them for support.
