### ISSUE TITLE
Failed to link to module 'rlm_couchbase'

### ISSUE THREAD

**Issue by fiftysoft** [FreeRADIUS/freeradius-server#1582]
I have this error when I run freeradius -X

/etc/freeradius/mods-enabled/couchbase[1]: Failed to link to module 'rlm_couchbase': /usr/lib/freeradius/rlm_couchbase.so: cannot open shared object file: No such file or directory

**Comment by arr2036** [comment]
https://github.com/FreeRADIUS/freeradius-server/blob/v3.1.x/.github/contributing.md
