### ISSUE TITLE
Build fails due to /lib/ -> /lib/local substitution

### ISSUE THREAD

**Issue by milidam** [FreeRADIUS/freeradius-server#1585]
Hi, 

# Issue type
- [x] Defect - Unexpected behaviour (obvious or verified by project member).

# Defect description
I have a project where I let freeradius to be build by jenkins.
My `JENKINS_HOME` is `/var/lib/jenkins`.
Due to [this line](https://github.com/FreeRADIUS/freeradius-server/blob/v3.1.x/scripts/libtool.mk#L224), apparently, all instances of `lib` in the paths are replaced by `lib/local`; so, in my case, all absolute paths are rewritten into `/var/lib/local/jenkins/...`, what breaks the build.
 
## Output of ``make`` showing issue ocurring
```text
make[2]: *** No rule to make target `/var/lib/local/jenkins/[...]/freeradius-server-3.0.11/build/lib/local/libfreeradius-eap.la', needed by `/var/lib/jenkins/[...]/freeradius-server-3.0.11/build/lib/local/rlm_eap.la'.  Stop.
```

Any idea how I could circumvent this?
Do I need to patch, or should the proper config do the trick?

Thanks in advance.

**Comment by alandekok** [comment]
Change the line to:

            $${TGT}_LOCAL_PRLIBS := $$(subst $${BUILD_DIR}/lib/,$${BUILD_DIR}/lib/${LOCAL},$${$${TGT}_PRLIBS})


and it should work.  If so, I'll commit a fix.

**Comment by milidam** [comment]
Hi Alan,
Thanks for the quick response !
I can confirm that the change you proposed fixes my problem.
Thanks!
