### ISSUE TITLE
Radsniff high write out statistics interval time result muting stats

### ISSUE THREAD

**Issue by Renj-FR** [FreeRADIUS/freeradius-server#1599]
# Issue type
Radsniff does not accept high write out statistics interval time and return muting stats.
When I use radsniff with 5 seconds interval and run radtest request, I have this error.

On the other hand, when I use radsniff with 1 second interval, the output is correct:

######### Stats Iteration 7 #########
Interface capture rate:
	eth0      : 0.000/s
	eth1      : 0.000/s
	lo        : 0.000/s
Access-Accept counters:
	Total     : 1.000/s
	Linked    : 1.000/s
	Unlinked  : 0.000/s
Access-Accept latency:
	High      : 163.022ms
	Low       : 163.022ms
	Average   : 163.022ms
	MA        : 190.823ms

# Defect/Feature description
## How to reproduce issue
radsniff -x -W 5
radtest -4 -x [[login]] [[password]] [[ip]]:1812 1 [[secret]]
(repeat the last command to process requests)
 
## Output showing issue occurring
radsniff -x -W 5
Logging all events
Defaulting to capture on all interfaces
Sniffing on (eth0 eth1 lo)
radsniff: eth1 dropped 1 packets: Buffer exhaustion
radsniff: Muting stats for the next 5200 milliseconds
...

**Comment by arr2036** [comment]
If it's saying it dropped packets, that means libpcap is reporting it dropped packets.  Can you reliably produce this issue with -W 5? I'm guessing you can't.

**Comment by alandekok** [comment]
If there's no further response, I will close this issue.
