### ISSUE TITLE
commit e2bd9cb3d143d7ff835b04c1cf519861744dc075 breaks rlm_python on 3.0.x

### ISSUE THREAD

**Issue by pwiatrowski** [FreeRADIUS/freeradius-server#1606]
Hi,

this commit breaks rlm_python.

During compilation there's a warning:
`CC src/modules/rlm_python/rlm_python.c
src/modules/rlm_python/rlm_python.c:124:2: warning: initialization makes pointer from integer without a cast [enabled by default]
  { "cext_compat", FR_CONF_OFFSET(PW_TYPE_BOOLEAN, rlm_python_t, cext_compat), .dflt = true },
  ^
src/modules/rlm_python/rlm_python.c:124:2: warning: (near initialization for ‘module_config[25].dflt’) [enabled by default]`

the compilation continues but later when I tried starting FreeRADIUS with the python module enabled - it didn't start - Segmentation Fault.

When I changed line 124 in rlm_python.c everything compiled without any warnings and FreeRADIUS started normally.

Working line: rlm_python.c line 124:
`{ "cext_compat", FR_CONF_OFFSET(PW_TYPE_BOOLEAN, rlm_python_t, cext_compat), .dflt = false },`

**Comment by arr2036** [comment]
Fixed, thanks for the report.
