### ISSUE TITLE
latest HEAD is finding false duplicate

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1612]
when trying to run with radiusd -X I get

Tue May 17 13:52:27 2016 : Error : (null)[0]: Duplicate configuration section Auth-Type eduroam-eap

there is no duplicate,  only one 'Auth-Type eduroam-eap' defined in virtual server 'eduroam' - and thats it.

**Comment by alandekok** [comment]
It would help to have the contents of the `authenticate` section.

I can't reproduce this on my system no matter how I mangle the configuration.

**Comment by alanbuxey** [comment]
the output seems to have lost details of what its reading in...so i dont know which VS etc its reading - is this change in behaviour?   anyway, relevant VS  (the *only* one with that Auth-Type defined:

authenticate {

	#
	#  Allow EAP authentication.
	eduroam-eap

	#
	#  The older configurations sent a number of attributes in
	#  Access-Challenge packets, which wasn't strictly correct.
	#  If you want to filter out these attributes, uncomment
	#  the following lines.
	#
	Auth-Type eduroam-eap {
		eduroam-eap {
			handled = 1
		}
		if (handled && (Response-Packet-Type == Access-Challenge)) {
			attr_filter.access_challenge.post-auth
			handled  # override the "updated" code from attr_filter
		}
	}
}

**Comment by alandekok** [comment]
That configuration is wrong, and has always been wrong.

You *cannot* use the same thing twice in an `authenticate` section.  Under the scenes, a bare `eduroam-eap` is treated exactly the same as:

    Auth-Type eduroam-eap {
        eduroam-eap
    }

Your configuration is *not* doing what you think it's doing.  It's wrong, and you need to fix it.

Just delete the bare `eduroam-eap` line, and it will work.

**Comment by alanbuxey** [comment]
...but but..but....its pretty much a duplicate of the config in most older
default server releases (I've just noticed the 3.1.x version of default
has now changed...... ;-) )  e.g.

#

#  Allow EAP authentication.

eap


#

#  The older configurations sent a number of attributes in

#  Access-Challenge packets, which wasn't strictly correct.

#  If you want to filter out these attributes, uncomment

#  the following lines.

#

# Auth-Type eap {

# eap {

# handled = 1

# }

# if (handled && (Response-Packet-Type == Access-Challenge)) {

# attr_filter.access_challenge.post-auth

# handled  # override the "updated" code from attr_filter

# }

# }

}



(we're just using a named instance of eap -   this config has always worked
until the latest commit - so if its always been wrong...wonder how many
sites have such things lurking...


alan

**Comment by arr2036** [comment]
Knowing the internals @alandekok is right, and using both would produce undefined behaviour.  Or more the first instance would probably be used.

The validation checks are definitely correct.  If this breaks sites then that's unfortunate, but the way EAP inners are handled between v3.0.x and v3.1.x is pretty different anyway, and will require EAP module instances to be re-arranged in most cases.

**Comment by alanbuxey** [comment]
its fair enough - and I can see that its wrong. got caught out because
thats the subtle old way thats been adjusted....  (I can see from the
recent commits what expansion/unlang compiling stuff caused this error to
surface

**Comment by mcnewton** [comment]
Actually the mistake in the (now old) default config file you quoted is only really to not say "... and also comment out 'eap' above". The config is correct because the second block is commented out, it just wasn't 100% clear that you shouldn't have both enabled...

If you really want to know who caused the 'problem' in the first case check out the author of 26e99a37 :-)

**Comment by alanbuxey** [comment]
;)

Well, wanted it to be used rather than just sitting there pretty :)
ideally my commit would have been noted to clash with the naked 'eap'  :)

alan
