### ISSUE TITLE
how to connect mssql in freeradius V3?

### ISSUE THREAD

**Issue by wufengyi** [FreeRADIUS/freeradius-server#1621]
Hi,

Earlier this year,I used freeradius V2 to connect mssql database,it is ok.

but I want to turn to freeradius V3,and I have installed freetds and unixODBC on my linux server.the freetds can connect my mssql server succeffully.but I want to know how to configure the new freeradius version to make the connection work

Thanks

**Comment by arr2036** [comment]
https://github.com/FreeRADIUS/freeradius-server/blob/v3.1.x/.github/contributing.md
