### ISSUE TITLE
unable to build RedHat RPM - winbind.mk (lack of)

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1629]
reporting an issue reported to me:

"I have Scientific Linux's devtoolset-3 versions of gcc and gcc-c++ installed.
The build doesn't seem to get past running the configure script, and fails when processing the rlm_winbind module.

                checking for x86_64-redhat-linux-gnu-gcc... no
                checking for gcc... gcc
                checking whether the C compiler works... no
                configure: error: in `/home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0/src/modules/rlm_winbind':
                configure: error: C compiler cannot create executables
                See `config.log' for more details
                make: *** [src/modules/rlm_winbind/rlm_winbind.mk] Error 77
                error: Bad exit status from /var/tmp/rpm-tmp.Q8rOeP (%build)
               
               
                RPM build errors:
                    bogus date in %changelog: Wed Sep 22 2013 Alan DeKok <aland@freeradius.org> - 3.0.0
                    Bad exit status from /var/tmp/rpm-tmp.Q8rOeP (%build)
                [mjl23@radserv2 ~]$
               

The configure scripts appears to create config.log files for each rlm module. The errors in /home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0/src/modules/rlm_winbind/config.log are:

                configure:2157: $? = 0
                configure:2146: gcc -v >&5
                Using built-in specs.
                COLLECT_GCC=gcc
                COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/lto-wrapper
                Target: x86_64-redhat-linux
                Configured with: ../configure --prefix=/opt/rh/devtoolset-3/root/usr --mandir=/opt/rh/devtoolset-3/root/usr/share/man --infodir=/opt/rh/devtoolset-3/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
                Thread model: posix
                gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC)
                configure:2157: $? = 0
                configure:2146: gcc -V >&5
                gcc: error: unrecognized command line option '-V'
                gcc: fatal error: no input files
                compilation terminated.
                configure:2157: $? = 4
                configure:2146: gcc -qversion >&5
                gcc: error: unrecognized command line option '-qversion'
                gcc: fatal error: no input files
                compilation terminated.
                configure:2157: $? = 4
                configure:2177: checking whether the C compiler works
                configure:2199: gcc -I/home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0 -I/home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0/src -include /home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0/src/freeradius-devel/autoconf.h -include /home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0/src/freeradius-devel/build.h -include /home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0/src/freeradius-devel/features.h -include /home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0/src/freeradius-devel/radpaths.h -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fpic -std=c1x -Wall -D_GNU_SOURCE -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -DOPENSSL_NO_KRB5 -DNDEBUG -DIS_MODULE=1    -Wl,--build-id conftest.c  >&5
                In file included from <command-line>:0:0:
                /usr/include/stdc-predef.h:40:1: fatal error: /home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0/src/freeradius-devel/autoconf.h: No such file or directory

It's not clear to me whether the build fails because the devtoolset-3 version of gcc I'm using doesn't support the options the configure script is trying to use, or because it's looking for files in directory /home/mjl23/rpmbuild/BUILD/freeradius-server-3.1.0/src/freeradius-devel (like autoconf.h) when freeradius-devel doesn't exist. Am I missing source code for a freeradius-devel RPM?"

**Comment by mcnewton** [comment]
rlm_winbind.mk is autogenerated at configure time from rlm_winbind.mk.in, so if it's not there then the configure stage broke.

The errors about -V, -qversion etc not working are just configure trying to find a "-v" option to the C compiler. It found "-v" above, so they are irrelevant.

Is this being built in a compltely clean source tree? That would be my first guess as to the problem.

**Comment by spaetow** [comment]
A bogus date is upsetting RPM? Awww. Then perhaps we should fix that in the SPEC file...

**Comment by mcnewton** [comment]
I've managed to reproduce it (eugh, RedHat & RPMs are as horrid as I remember) but not look at it yet. Building RPM gives error, but the same 'configure' run manually works fine.

**Comment by alanbuxey** [comment]
yep.

**Comment by mcnewton** [comment]
It's because rlm_winbind is not listed in `src/modules/stable`. Looking at a different fix (not adding it to 'stable' just yet...)

**Comment by mcnewton** [comment]
Should be OK now.
