### ISSUE TITLE
error: FreeRADIUS requires support for the C11 _Generic keyword

### ISSUE THREAD

**Issue by ollakalla** [FreeRADIUS/freeradius-server#1636]
So i download the repository 
`git clone https://github.com/FreeRADIUS/freeradius-server.git`
When i run 
`./configure`
I have this error
`error: FreeRADIUS requires support for the C11 _Generic keyword`
Although i installed the last version of gcc 4.8 on Centos 7

**Comment by mcnewton** [comment]
You need gcc at least 4.9 with C11 support to build development branches (v3.1.x or v4.0.x).

To build the latest stable versions you need to

     git checkout release_3_0_11

or

     git checkout v3.0.x

for the latest `HEAD`.

**Comment by alanbuxey** [comment]
install devtoolset-3 or devtoolset-4 packages for your system - CentOS 7,
even new, is behind the times for GCC and C11 support.

its a simple fix

**Comment by arr2036** [comment]
For reference llvm (clang) has supported most C11 features since 2011!  GCC is *really* behind the times.
