### ISSUE TITLE
tls - Refusing to start with libssl version OpenSSL 1.0.1e-fips 11 Feb 2013 0x1000105f (1.0.1e release) (in range 1.0.1 dev - 1.0.1f release)

### ISSUE THREAD

**Issue by ollakalla** [FreeRADIUS/freeradius-server#1637]
After i installation is complete and run 
`radiusd -X`
i have this error `tls - Refusing to start with libssl version OpenSSL 1.0.1e-fips 11 Feb 2013 0x1000105f (1.0.1e release) (in range 1.0.1 dev - 1.0.1f release)`
Although i install openssl-devel befor installing radius  
and i can't find `allow_vulnerable_openssl` in radiusd.conf.in for freeradius version 3.1

**Comment by mcnewton** [comment]
https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/.github/contributing.md#github-issue-tracker
