### ISSUE TITLE
no stats output with radclient

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1639]
when using radclient against the status virtual server, the radclient does not show stats... freeradius debug clearly shows stats:

echo "Message-Authenticator = 0x00, FreeRADIUS-Statistics-Type = 63" | radclient -s localhost:18121 status adminsecret
Sent Status-Server Id 2 from 0.0.0.0:60320 to 127.0.0.1:18121 length 50
Received Access-Accept Id 2 from 127.0.0.1:18121 to 0.0.0.0:0 length 332

no further output :(

but the server debug is showing the data being generated...

(3) Received Status-Server Id 146 from 127.0.0.1:37308 to 127.0.0.1:18121 length 50
(3)   Message-Authenticator = 0x2f9e63e8c0f3a4bc9174d43d2191481f
(3)   FreeRADIUS-Statistics-Type = 63
(3) # Executing group from file /usr/local/etc/raddb/sites-enabled/status
(3)   Autz-Type Status-Server {
(3)     [ok] = ok
(3)   } # Autz-Type Status-Server = ok
(3) Sent Access-Accept Id 146 from 127.0.0.1:18121 to 127.0.0.1:37308 length 0
(3)   FreeRADIUS-Total-Access-Requests = 4
(3)   FreeRADIUS-Total-Access-Accepts = 0
(3)   FreeRADIUS-Total-Access-Rejects = 1
(3)   FreeRADIUS-Total-Access-Challenges = 0
(3)   FreeRADIUS-Total-Auth-Responses = 1
(3)   FreeRADIUS-Total-Auth-Duplicate-Requests = 0
(3)   FreeRADIUS-Total-Auth-Malformed-Requests = 0
(3)   FreeRADIUS-Total-Auth-Invalid-Requests = 0
(3)   FreeRADIUS-Total-Auth-Dropped-Requests = 0
(3)   FreeRADIUS-Total-Auth-Unknown-Types = 0
(3)   FreeRADIUS-Total-Accounting-Requests = 0
(3)   FreeRADIUS-Total-Accounting-Responses = 0
(3)   FreeRADIUS-Total-Acct-Duplicate-Requests = 0
(3)   FreeRADIUS-Total-Acct-Malformed-Requests = 0
(3)   FreeRADIUS-Total-Acct-Invalid-Requests = 0
(3)   FreeRADIUS-Total-Acct-Dropped-Requests = 0
(3)   FreeRADIUS-Total-Acct-Unknown-Types = 0
(3)   FreeRADIUS-Stats-Start-Time = "Jul  1 2016 11:40:32 CEST"
(3)   FreeRADIUS-Stats-HUP-Time = "Jul  1 2016 11:40:32 CEST"
(3)   FreeRADIUS-Queue-Len-Internal = 0
(3)   FreeRADIUS-Queue-Len-Proxy = 0
(3)   FreeRADIUS-Queue-Len-Auth = 0
(3)   FreeRADIUS-Queue-Len-Acct = 0
(3)   FreeRADIUS-Queue-Len-Detail = 0
(3)   FreeRADIUS-Queue-PPS-In = 0
(3)   FreeRADIUS-Queue-PPS-Out = 0
(3) Finished request

**Comment by alanbuxey** [comment]
update....works if I add debug option to radclient (-x) - shouldn't need to though....should I ? never used to need that flag.   for now, -x works as a work around...

**Comment by alandekok** [comment]
It's always behaved this way.

**Comment by alanbuxey** [comment]
no..it hasnt - as many of the google results showing the use of radclient
with the status server virtual server show

**Comment by mcnewton** [comment]
I was looking at radclient and radtest a few months ago and was sure that something with -x wasn't quite right or had maybe changed at some point, but never studied it more. Not sure if it's the same as this issue though.

**Comment by alanbuxey** [comment]
with 3.1.x GIT it doesnt even seem to print with the -x .....
