### ISSUE TITLE
mschap: ERROR: FAILED: No NT/LM-Password.  Cannot perform authentication

### ISSUE THREAD

**Issue by wanggaolin** [FreeRADIUS/freeradius-server#1646]
i usage openldap auth,error message:

(8) suffix: No '@' in User-Name = "t1", looking up realm NULL
(8) mschap: ERROR: FAILED: No NT/LM-Password.  Cannot perform authentication
(8) mschap: ERROR: MS-CHAP2-Response is incorrect
(8)   MS-CHAP-Error = "\010E=691 R=1 C=c8e50c3ee3fb4b3c951f17252099f261 V=3 M=Authentication failed"
(8) eap_peap:   MS-CHAP-Error = "\010E=691 R=1 C=c8e50c3ee3fb4b3c951f17252099f261 V=3 M=Authentication failed"
(8) eap_peap:   MS-CHAP-Error = "\010E=691 R=1 C=c8e50c3ee3fb4b3c951f17252099f261 V=3 M=Authentication failed"
(9)   User-Name = "t1"
(9) suffix: No '@' in User-Name = "t1", looking up realm NULL
(9) eap: ERROR: Failed continuing EAP PEAP (25) session.  EAP sub-module failed

How can I solve it?

**Comment by arr2036** [comment]
https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/.github/contributing.md
