### ISSUE TITLE
3.1 HEAD doesnt build (rlm_winbind)

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1658]
bang. oops  ;-)

CC src/modules/rlm_winbind/rlm_winbind.c
In file included from /usr/local/src/freeradius-server/src/freeradius-devel/radiusd.h:58:0,
                 from src/modules/rlm_winbind/rlm_winbind.c:30:
src/modules/rlm_winbind/rlm_winbind.c: In function ‘winbind_group_cmp’:
/usr/local/src/freeradius-server/src/freeradius-devel/tmpl.h:350:11: error: ‘_Generic’ selector of type ‘void *’ is not compatible with any association
  _Generic((_ptr), \
           ^
/usr/local/src/freeradius-server/src/freeradius-devel/tmpl.h:368:47: note: in expansion of macro ‘PW_TYPE_FROM_PTR’
         _request, _vpt, _escape, _escape_ctx, PW_TYPE_FROM_PTR(_out))
                                               ^
src/modules/rlm_winbind/rlm_winbind.c:103:9: note: in expansion of macro ‘tmpl_expand’
   len = tmpl_expand(NULL, buffer, sizeof(buffer) - 1, request, inst->wb_domain, NULL, NULL);
         ^
/usr/local/src/freeradius-server/src/freeradius-devel/tmpl.h:350:11: error: ‘_Generic’ selector of type ‘void *’ is not compatible with any association
  _Generic((_ptr), \
           ^
/usr/local/src/freeradius-server/src/freeradius-devel/tmpl.h:368:47: note: in expansion of macro ‘PW_TYPE_FROM_PTR’
         _request, _vpt, _escape, _escape_ctx, PW_TYPE_FROM_PTR(_out))
                                               ^
src/modules/rlm_winbind/rlm_winbind.c:125:9: note: in expansion of macro ‘tmpl_expand’
   len = tmpl_expand(NULL, ptr, sizeof(buffer) - domain_len - 1, request, inst->group_username, NULL, NULL);
         ^
make: *** [build/objs/src/modules/rlm_winbind/rlm_winbind.lo] Error 1

**Comment by arr2036** [comment]
You've got a mix of v3.1.x and v4.0.x in the same working copy.  Those changes were never ported to v3.1.x.

It's conceivable that problem exists in v4.0.x

**Comment by mcnewton** [comment]
3.1.x HEAD compiles perfectly (with rlm_winbind) for me.

4.0.x does have this problem.... I blame @arr2036 for changing tmpl_to_type from "To force copying to buff, out should be NULL." to "Must not be NULL." :-P

**Comment by mcnewton** [comment]
Looks like rlm_winbind will need updating to do the strcpy that tmpl_to_type sometimes did before. It used out==NULL to fill the buffer with the expanded data and build up the username in a couple of passes (domain then username), but now will need to copy that into another buffer in case *out doesn't point to the same buffer.

I'll take a look, but may be a couple of days.

**Comment by arr2036** [comment]
Yeah yeah.  I'll fix it *grumble grumble*.  I found in most instances it should have always been tmpl_aexpand.  When passing the request as the context, allocating memory is pretty cheap (cheaper than malloc), so there's usually not much point in using stack buffers unless the string length is restricted, or it's in something ultra high performance like Redis.

**Comment by alanbuxey** [comment]
hmmm, this might be the case. how? I dont know....will just grab a fresh
clone.

alan

**Comment by mcnewton** [comment]
Nice one, that's much tidier. Thanks.
