### ISSUE TITLE
systemd unit files should support reload

### ISSUE THREAD

**Issue by eheydrick** [FreeRADIUS/freeradius-server#1662]
# Issue type
- [x] Feature request.
# Defect/Feature description

The systemd unit files should support the reload action so that the daemon can be HUP'd when config files are updated. The SysV init scripts supports reloading and the systemd files should too.

**Comment by arr2036** [comment]
The architectural changes required for HUP to work correctly are massive.  They're only likely to be able in v4.0.x even then you might be waiting until v4.2.x.  Until it can work properly, in a way that everyone expects, FreeRADIUS should be restarted not reloaded.

**Comment by eheydrick** [comment]
I've been using reload with 3.0.x and it *seems* to work. At least I haven't noticed any issues with my usage. Looking forward to proper reload support.

**Comment by alandekok** [comment]
I've pushed a patch for v3.  HUP there is minimal, but it should be allowed.

The larger discussion for v4 should be in a separate issue.
