### ISSUE TITLE
spelling in files

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#1700]
not issue, more of a query so we can standardize. 

tunnelled, or tunneled?  :)

alan

**Comment by qnet-herwin** [comment]
My 2 cents: RFC5281 is about TTLS and uses tunneled.

**Comment by arr2036** [comment]
Autocorrect likes tunnelled

**Comment by arr2036** [comment]
Hmm, but dictionary.com indicates tunneled is correct

**Comment by arr2036** [comment]
In the code we've standardised on English/Canadian spelling.  With v4.0.x authorize is going away +1
