### ISSUE TITLE
Binaries without manpage: dhcpclient, rad_counter

### ISSUE THREAD

**Issue by stapelberg** [FreeRADIUS/freeradius-server#1734]
While working on the 3.x Debian packaging, I noticed that the following binaries don’t have a corresponding manpage:

* [src/modules/proto_dhcp/dhcpclient.c](https://github.com/FreeRADIUS/freeradius-server/blob/9f4db6476d7c148b5bd19310f02de3b057f2e585/src/modules/proto_dhcp/dhcpclient.c)
* src/modules/rlm_counter/rad_counter (deleted in 4.x — should we even ship `rlm_counter` in the 3.x Debian packages?)

Could you please clarify whether these binaries are not supposed to be shipped in the Debian package or whether they are indeed lacking a manpage? If they’re not supposed to be installed, then why does `make install` install them? :)

Thanks!

**Comment by arr2036** [comment]
yes, rlm_counter should be shipped in v3.0.x.  It was removed in v4.0.x because there's an SQL based version, and no one really uses the old GDBM based modules anymore.

**Comment by stapelberg** [comment]
dhcpclient and rad_counter still don’t have a manpage. Are you saying you’re not interested in having one for these binaries?

Would you accept a PR which adds one? It’s Debian policy that every binary has a corresponding manpage, so if you’re not writing one, I’ll need to anyways.

**Comment by arr2036** [comment]
ah, are you working on the Debian packaging with a view to getting FR >= 3 included in a Debian release?

**Comment by arr2036** [comment]
Man pages would be useful, but I wouldn't expend too much effort on the ones for rad_counter.

**Comment by stapelberg** [comment]
> ah, are you working on the Debian packaging with a view to getting FR >= 3 included in a Debian release?

Yes. I’ll submit a PR with my changes once I’m done (only a few minor issues to resolve at this point).

**Comment by arr2036** [comment]
Excellent 👍

**Comment by alandekok** [comment]
Honestly, just don't install dhcpclient.  It's there for testing, and no one needs to use it.

We can put a tiny man page for rlm_counter.  *don't use this.*

**Comment by stapelberg** [comment]
commit https://github.com/FreeRADIUS/freeradius-server/commit/f60d334cdd30531bd820e7a8486858a79199d9e8 and https://github.com/FreeRADIUS/freeradius-server/commit/9b74635a3efae2983ea3ae093cd30407f3d5e99c add manpages for the binaries in question.

**Comment by alanbuxey** [comment]
yes...i did these to ease the passage of the new versions into Debian  :)

**Comment by stapelberg** [comment]
Thanks for that. I only discovered these by chance, though, so it’d be good if you referenced the corresponding bugs (in case you were aware of this bug) in the future. Thanks!
