### ISSUE TITLE
src/tests/rbmonkey.c installed?

### ISSUE THREAD

**Issue by stapelberg** [FreeRADIUS/freeradius-server#1735]
While working on the 3.x Debian packaging, I noticed that src/tests/rbmonkey.c is not only compiled when using `./configure && make install`, but also installed to `{prefix}/bin`. This is also the case in 4.x.

Installing test code seems unintentional to me, but perhaps I’m misunderstanding the situation?

In case it’s unintentional, could we change the makefiles to no longer install that binary?

**Comment by arr2036** [comment]
shouldn't be installed, you're welcome to send a PR to fix it.
