### ISSUE TITLE
make -j8 install: man pages incorrectly don’t depend on jlibtool

### ISSUE THREAD

**Issue by stapelberg** [FreeRADIUS/freeradius-server#1740]
In a clean checkout:

```
$ ./configure --prefix=/tmp/mfr
[…]

$ make -n /tmp/mfr/share/man/man8/rlm_redis_ippool_tool.8
INSTALL -d -m 755 /tmp/mfr/share/man/man8
make: build/make/jlibtool: Command not found
scripts/boiler.mk:656: recipe for target '/tmp/mfr/share/man/man8' failed
make: *** [/tmp/mfr/share/man/man8] Error 127

$ VERBOSE=1 make -n /tmp/mfr/share/man/man8/rlm_redis_ippool_tool.8             
mkdir -p build/tests/auth
rm -f build/tests/auth/depends.mk
for x in src/tests/auth/password_without_header src/tests/auth/md5_password src/tests/auth/wimax src/tests/auth/password_with_header src/tests/auth/user_password src/tests/auth/digest src/tests/auth/chap src/tests/auth/chap_header; do \
	y=`grep 'PRE: ' $x | sed 's/.*://;s/  / /g;s, , build/tests/auth/,g'`; \
	if [ "$y" != "" ]; then \
		z=`echo $x | sed 's,src/,build/',`; \
		echo "$z: $y" >> build/tests/auth/depends.mk; \
		echo "" >> build/tests/auth/depends.mk; \
	fi \
done
mkdir -p build/tests/keywords
echo INSTALL -d -m 755 /tmp/mfr/share/man/man8
build/make/jlibtool --silent --mode=install /tmp/upstream/4/install-sh -c -d -m 755 /tmp/mfr/share/man/man8
echo INSTALL rlm_redis_ippool_tool.8
build/make/jlibtool --silent --mode=install /tmp/upstream/4/install-sh -c -c -m 644 src/modules/rlm_redis_ippool/rlm_redis_ippool_tool.8  /tmp/mfr/share/man/man8/
```

It seems to me like build/make/jlibtool is not declared as a dependency, but should be. Is my assessment of the problem correct?

Taking a step back, I’m wondering why we install manpages using libtool in the first place. Shouldn’t using `install(1)` be sufficient?

**Comment by alandekok** [comment]
sounds right.  install should be sufficient, *but* it's broken on many systems.  just use jlibtool.

**Comment by stapelberg** [comment]
Thanks for confirming, I’ll work on a PR.

Out of curiosity, what sort of breakage did you observe with `install(1)`, and on which systems specifically?

I’m using `install(1)` directly in the i3 window manager, which has users on a number of platforms and we’ve never had reports about issues with `install(1)`.

**Comment by alandekok** [comment]
I don't recall what the issues were with install.  Many hacks in the server have bene there since 1999, and are there to work around breakage on certain platforms.  Given that it's 2016, I'm inclined to say that broken platforms are no longer supported.
