### ISSUE TITLE
EAP-FAST and TLS 1.2

### ISSUE THREAD

**Issue by alandekok** [FreeRADIUS/freeradius-server#1756]
# Issue type
- [x] Feature request.
# Defect/Feature description

EAP-FAST requires `disable_tlsv1_2 = yes`, because the PRF label used in FAST is forbidden by the RFCs.  And, the PRF function in TLS 1.2 is different from the PRF function in earlier versions of TLS.

The solution is to re-implement the TLS 1.2 PRF function in FreeRADIUS, and then make EAP-FAST use it.  For example code, see `tls_connection_prf()` in the hostap repo.

**Comment by jimdigriz** [comment]
Supported by 70dbb66

**Comment by jimdigriz** [comment]
Fixed by https://github.com/FreeRADIUS/freeradius-server/commit/6ae4f72727957909ed9e4b5e80df7be6030dd737

Can now be closed.
