### ISSUE TITLE
Debian-style freeradius-config package includes sites-enabled/{default,inner-tunnel} symlinks, overwriting local configuration if it is not a symlink

### ISSUE THREAD

**Issue by gclinch** [FreeRADIUS/freeradius-server#1764]
# Issue type
- [x] Defect - Unexpected behaviour (obvious or verified by project member).

# Defect description

Rather than editing the server configuration in sites-available (thus destroying the original, clean, configuration), I prefer to remove the symlinks in sites-enabled and copy sites-available/default to sites-enabled and edit from there.

However the freeradius-config debian package (as built from freeradius source, not the package in the debian project) includes the sites-enabled/default & sites-enabled/inner-tunnel symlinks as a standard file, thus my changes are overwritten during upgrades.  Tested with the head of 3.1.x & 4.0.x.

```
$ dpkg-deb -c freeradius-config_3.1.0+git_amd64.deb  | fgrep sites-enabled
drwxr-xr-x root/root         0 2016-10-01 18:04 ./etc/freeradius/sites-enabled/
lrwxrwxrwx root/root         0 2016-10-01 18:04 ./etc/freeradius/sites-enabled/default -> ../sites-available/default
lrwxrwxrwx root/root         0 2016-10-01 18:04 ./etc/freeradius/sites-enabled/inner-tunnel -> ../sites-available/inner-tunnel
```

Note that freeradius.postinst already has logic to create these symlinks on install but not upgrade (why is this not in freeradius-config.postinst instead?)

The debian project itself appears to have worked around this issue in their experimental package (version 3.0.11+dfsg-1) in the debian/rules override_dh_install section:
```
        # We create the mods-enabled links in freeradius-config.postinst so
        # that they are not re-created when users upgrade to a newer version.
        rm debian/tmp/etc/freeradius/mods-enabled/*
```

I've stolen their idea and cleaned it up to match the standard freeradius rules file:
```
--- debian/rules.old	2016-10-01 13:39:19.000000000 +0100
+++ debian/rules	2016-10-01 17:59:44.361734732 +0100
@@ -156,6 +156,9 @@
 	mv $(freeradius_dir)/usr/sbin/radiusd $(freeradius_dir)/usr/sbin/$(package)
 	mv $(freeradius_dir)/$(mandir)/man8/radiusd.8 $(freeradius_dir)/$(mandir)/man8/$(package).8
 
+	# sites-enabled links are created by postinst, so don't include them in the package
+	rm $(freeradius_dir)/etc/freeradius/sites-enabled/*
+
 	dh_install -i --sourcedir=$(freeradius_dir)
 	dh_install --sourcedir=$(freeradius_dir) -p libfreeradius3
 	dh_install --sourcedir=$(freeradius_dir) -p libfreeradius-dev
```

and it works for me...
```
$ dpkg-deb -c freeradius-config_3.1.0+git-20161001172817_amd64.deb  | fgrep sites-enabled
drwxr-xr-x root/root         0 2016-10-01 18:08 ./etc/freeradius/sites-enabled/
```

Please consider applying the diff above to debian/rules.

The same situation is also the case for mods-enabled, but that is not (currently) affecting me.  That would require both the removal of mods-enabled/* before dh_install AND the writing of additional postinst tasks that, on install only, create the appropriate default symlinks.

**Comment by arr2036** [comment]
Looks good, but can you please resubmit as a PR.
