### ISSUE TITLE
Dependency on autocommit for MySQL

### ISSUE THREAD

**Issue by xcorp** [FreeRADIUS/freeradius-server#1769]
When using MySQL driver, it is assumed that the server has autocommit=1.
I haven't found any documentation about this anywhere, this could be solved either by actually committing each query, or the lazy way by setting autocommit in the connection.

I haven't tried with PostgreSQL, but looking at the source I assume it's a problem there as well.

**Comment by arr2036** [comment]
Because that's the default. What would be the solution? and what's the advantage of running with autocommit=0?

**Comment by alandekok** [comment]
The usual way for SQL servers to work is that an `UPDATE` does the update.  There is no need to do `START / END TRANSACTION`.

This is the way that FreeRADIUS is designed.  And this is the way it's worked since 2000.  So far, no one has seen any problem with this.

Please explain why this is a problem.  Submitting a bug report saying "needs autocommit" is not useful.  It's content free, and doesn't explain WHY it's a problem.

**Comment by xcorp** [comment]
It is the default yes, but for PostgreSQL it wasn't default for a long time, and in my opinion, just assuming that the default-value will be kept without listing it as a prerequisite  isn't a very good approach. One advantage is that it forces the programmer to actually know how to use the database.

The original problem comes from me taking over a newly installed database where autocommit was turned off, when I then migrated over my radius-instance nothing worked, and with no trace in the logs since the insert/update went fine but wasn't actually commited.

**Comment by alandekok** [comment]
Then submit a patch against the documentation.  Which *explains* the issue, what you saw, and how to fix it.

Don't open a content-free bug report saying "needs autocommit=1" with no content, and then only give the *real* explanation when we ask for it.

And no, the default in postgres was *not* "autocommit=0".  Normal SQL connections (i.e. FreeRADIUS use-case) were automatically committed.  The default for *stored procedures*, and *only* stored procedures was "autocommit=0".

If you'll note my earlier message, FreeRADIUS has worked well with the current design for 16 years.  You are the first person *ever* to run into this problem.  So while it may be useful to add documentation for this issue, it's not important enough for me to go do it myself.
