### ISSUE TITLE
Freeradius 3.0.12 compilation error on Debian Jessie

### ISSUE THREAD

**Issue by cmiscloni** [FreeRADIUS/freeradius-server#1773]
Hi,

I have  a problem to compile the version 3.0.12 of Freeradius with Debian Jessie (8.5) x64
Error is 
patching file raddb/all.mk
Hunk #1 FAILED at 8.
1 out of 1 hunk FAILED -- rejects in file raddb/all.mk
Patch disable-dhcp-by default.diff does not apply (enforce with -f)

Thanks for your help.

**Comment by arr2036** [comment]
Already fixed, use v3.0.x.

**Comment by mcnewton** [comment]
All noted in the build instructions... http://wiki.freeradius.org/building/Debian
