### ISSUE TITLE
Calling-Station-Id empty expression error

### ISSUE THREAD

**Issue by styleofglobal** [FreeRADIUS/freeradius-server#1796]
# Issue type
- Authentication issue.

I am having issue with (FreeRADIUS Version 3.0.12, for host x86_64-redhat-linux-gnu, built on Sep 29 2016 at 18:26:26). the issue is with the sql operator =~ using in radcheck table Calling-Station-Id attribute, problem is when the value is empty it returns an error stating empty expression error as shown in logs below.

`(56) suffix: No such realm "NULL"
(56)     [suffix] = noop
(56) eap: No EAP-Message, not doing EAP
(56)     [eap] = noop
(56) files: users: Matched entry DEFAULT at line 181
(56)     [files] = ok
(56) sql: EXPAND %{User-Name}
(56) sql:    --> test
(56) sql: SQL-User-Name set to 'test'
rlm_sql (sql): Reserved connection (33)
(56) sql: EXPAND SELECT id, username, attribute, value, op FROM radcheck WHERE username = '%{SQL-User-Name}' ORDER BY id
(56) sql:    --> SELECT id, username, attribute, value, op FROM radcheck WHERE username = 'test' ORDER BY id
(56) sql: Executing select query: SELECT id, username, attribute, value, op FROM radcheck WHERE username = 'test' ORDER BY id
(56) sql: User found in radcheck table
(56) sql: ERROR:
(56) sql: ERROR: ^ Empty expression
rlm_sql (sql): Released connection (33)
rlm_sql (sql): Need 1 more connections to reach 10 spares
rlm_sql (sql): Opening additional connection (34), 1 of 30 pending slots used
rlm_sql_mysql: Starting connect to MySQL server
rlm_sql_mysql: Connected to database 'test' on Localhost via UNIX socket, server version 5.5.53, protocol version 10
(56)     [sql] = noop
(56)     [expiration] = noop
(56)     [logintime] = noop
(56) pap: WARNING: No "known good" password found for the user.  Not setting Auth-Type
(56) pap: WARNING: Authentication will fail unless a "known good" password is available
(56)     [pap] = noop
(56)   } # authorize = ok
(56) ERROR: No Auth-Type found: rejecting the user via Post-Auth-Type = Reject
(56) Failed to authenticate the user
(56) Using Post-Auth-Type Reject
(56) # Executing group from file /etc/raddb/sites-enabled/default
(56)   Post-Auth-Type REJECT {
(56) sql: EXPAND .query
(56) sql:    --> .query
(56) sql: Using query template 'query'
rlm_sql (sql): Reserved connection (32)
(56) sql: EXPAND %{User-Name}
(56) sql:    --> test
(56) sql: SQL-User-Name set to 'test'
(56) sql: EXPAND INSERT INTO radpostauth (username, pass, reply, authdate) VALUES ( '%{SQL-User-Name}', '%{%{User-Password}:-%{Chap-Password}}', '%{reply:Packet-Type}', '%S')
(56) sql:    --> INSERT INTO radpostauth (username, pass, reply, authdate) VALUES ( 'test', 'test', 'Access-Reject', '2016-10-19 12:55:42')
(56) sql: Executing query: INSERT INTO radpostauth (username, pass, reply, authdate) VALUES ( 'test', 'test', 'Access-Reject', '2016-10-19 12:55:42')
(56) sql: SQL query returned: success
(56) sql: 1 record(s) updated
rlm_sql (sql): Released connection (32)
(56)     [sql] = ok
(56) attr_filter.access_reject: EXPAND %{User-Name}
(56) attr_filter.access_reject:    --> test
(56) attr_filter.access_reject: Matched entry DEFAULT at line 11
(56)     [attr_filter.access_reject] = updated
(56)     [eap] = noop
(56)     policy remove_reply_message_if_eap {
(56)       if (&reply:EAP-Message && &reply:Reply-Message) {
(56)       if (&reply:EAP-Message && &reply:Reply-Message)  -> FALSE
(56)       else {
(56)         [noop] = noop
(56)       } # else = noop
(56)     } # policy remove_reply_message_if_eap = noop
(56)   } # Post-Auth-Type REJECT = updated
(56) Delaying response for 1.000000 seconds`

When I specify Calling-Station-Id value it connects. But what I want is to keep it empty for user to connect and when the user is connected it stores the MAC Address and remembers it till we clear it.
we haven't changed any thing in the config other then sql configuration 

I have another running server using ( FreeRADIUS Version 2.2.6, for host x86_64-redhat-linux-gnu, built on Sep 22 2015 at 15:27:25) everything is working fine, The expression is empty for the first time, I'am using the same operator (=~) and it doesnt return any errors and user connects, I just want the new version to do the same process, maybe I'm missing something in the new version which changed or missing.

Any help would be appreciated.

Thank you.

**Comment by alandekok** [comment]
Instead of updating the field, just update the entire row to add "Calling-Station-Id =~ value".

3.0 has a lot more sanity checks than version 2.  In this case, doing a regular expression comparison against *nothing* is a syntax error.  And it should be a syntax error.
