### ISSUE TITLE
Rationale for freeradius-config Debian package

### ISSUE THREAD

**Issue by stapelberg** [FreeRADIUS/freeradius-server#1821]
Commit https://github.com/FreeRADIUS/freeradius-server/commit/b2bfb69183f580613405364f51d4dfb199346fe4 split the configuration into a freeradius-config package.

I tried following that approach in the upstream package, but cleanly migrating from Debian’s FreeRADIUS 2 packaging to the FreeRADIUS 3 packaging is a major headache due to conffiles moving between packages *and* moving location (specifically /etc/freeradius/hints moving to /etc/freeradius/mods-config/preprocess/hints). See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839931 for details.

I’m inclined to revert that change and keep the configuration in the `freeradius` package.

What is the rationale for having the freeradius-config package in the first place? The description says “This package should be used as a base for a site local packages to configure the FreeRADIUS server.”, but I’m not familiar with this pattern. Can you explain please?

**Comment by mcnewton** [comment]
The recommendation everywhere is that the FR3 config should be built from scratch. So the new package shouldn't try and upgrade any of the config. Or even treat it as the same config; it's not.

Can you not either
 - make freeradius-config conflict with FreeRADIUS <= 2, or
 - install the fr3 config in /etc/radius or /etc/freeradius3 so there is no clash?

I seem to remember way back PostgreSQL went through a similar situation with new version moving all the config of the old version (possibly with a transitional package)? So there may be an example of what's been done before out there.

I think the idea behind the config split is you can install the software but not the config, and use your own. But @arr2036 will probably have a better idea. It may just make sense as another 'component' so in another package just like the other packages.

There is another issue with both packaging methods for the config - e.g. LDAP config should probably be in the freeradius-ldap package so people don't get confused by the config being there but not the libraries so it doesn't work. I sometimes wonder whether following the exim model (simple and heavy) would be better.

Matthew

**Comment by mcnewton** [comment]
Really nice to see some work on progressing FR in Debian though :-)

**Comment by alandekok** [comment]
On Nov 4, 2016, at 4:56 AM, Michael Stapelberg <notifications@github.com> wrote:
> I tried following that approach in the upstream package, but cleanly migrating from Debian’s FreeRADIUS 2 packaging to the FreeRADIUS 3 packaging is a major headache due to conffiles moving between packages and moving location (specifically /etc/freeradius/hints moving to /etc/freeradius/mods-config/preprocess/hints). See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839931 for details.

  Please don't allow people to upgrade configurations from one major release to another. It's just not going to work.

> I’m inclined to revert that change and keep the configuration in the freeradius package.
> 
> What is the rationale for having the freeradius-config package in the first place? The description says “This package should be used as a base for a site local packages to configure the FreeRADIUS server.”, but I’m not familiar with this pattern. Can you explain please?

  The idea is that if you have local configuration pushed to many machines, you can do so via a package.  You just don't install the "official" freeradius-config package.

**Comment by arr2036** [comment]
We should use the major version number as part of the directory structure like PG does, and have ``/etc/freeradius/3.0/`` ``/etc/freeradius/3.1/`` ``/etc/freeradius/4.0/``.

You will never be able to upgrade between major version numbers without changes to the config.  If/when we develop a migration tool, it should convert the config from the previous version and write it out to a new location to allow quick reversion.

**Comment by arr2036** [comment]
ah I see @mcnewton already suggested the same thing :)

**Comment by arr2036** [comment]
and yes the config package is setup so you can have your own package provide freeradius-config and install that instead, and not have to trash/dig out the default config.

**Comment by stapelberg** [comment]
Thanks for the details. I’ve opted to move the configuration to `/etc/freeradius/3.0` in https://anonscm.debian.org/cgit/pkg-freeradius/freeradius.git/commit/?id=db1a39fcca4e9c8a50615094b91d77e3fb452c58
