### ISSUE TITLE
Radius status response is empty

### ISSUE THREAD

**Issue by lfdominguez** [FreeRADIUS/freeradius-server#1840]
Hello, I compile the freeradius with this id (ea009158375c517c05a94a773fa08741b719d24b) v 4.0.0 and only activate the status support (status_server = yes) in radiusd.conf and enable the site (with ln -s sites........). The server is running OK, but to obtain the status information of the server this happend..

`root@radius:~/FREERADIUS/freeradius-server-4.0.x# echo "Message-Authenticator = 0x00, FreeRADIUS-Statistics-Type = 1, Response-Packet-Type = Access-Accept" | radclient -x 127.0.0.1:18121 status "adminsecret"
Sent Status-Server Id 226 from 0.0.0.0:59761 to 127.0.0.1:18121 length 50
        Message-Authenticator = 0x00
        FreeRADIUS-Statistics-Type = Authentication
        Response-Packet-Type = Access-Accept
Received Access-Accept Id 226 from 127.0.0.1:18121 to 0.0.0.0:0 via lo length 20`

And in the server show this
`(1)  Received Status-Server Id 226 from 127.0.0.1:59761 to 127.0.0.1:18121 via lo length 50
(1)    Message-Authenticator = 0xf415f3ca91f8a7685bbde94ed1dc8b91
(1)    FreeRADIUS-Statistics-Type = Authentication
(1)  Running Autz-Type Status-Server from file /usr/etc/raddb/sites-enabled/status
(1)  Autz-Type Status-Server {
(1)    ok (ok)
(1)  } # Autz-Type Status-Server (ok)
(1)  Processing SNMP stats request
(1)  Running section post-auth from file /usr/etc/raddb/sites-enabled/status
(1)  post-auth {
(1)    ok (ok)
(1)  } # post-auth (ok)
(1)  Sent Access-Accept Id 226 from 127.0.0.1:18121 to 127.0.0.1:59761 via lo length 0
(1)  Finished request
(1)  Cleaning up request packet ID 226 with timestamp +167`

As you can see the server don't respond with the statics so what happend???

thanks and sorry for my bad english

**Comment by arr2036** [comment]
That interface is no longer supported in version 4.

**Comment by lfdominguez** [comment]
And how i can get the stats of the servers?? I need it for monitoring into zabbix, thanks...

**Comment by alandekok** [comment]
use radmin.
