### ISSUE TITLE
Can not find suitable object file for build/objs/src/modules/rlm_eap/types/rlm_eap_fast/.lo

### ISSUE THREAD

**Issue by dhpark21** [FreeRADIUS/freeradius-server#1847]
when today git 3.0
Error happen  below
build/objs/src/modules/rlm_eap/types/rlm_eap_fast/.lo <- I think correct is rlm_eap_fast.lo 

check it please.
Thanks

--
LINK build/lib/rlm_eap.la
CC src/modules/rlm_eap/types/rlm_eap_fast/eap_fast.c
CC src/modules/rlm_eap/types/rlm_eap_fast/eap_fast_crypto.c
Can not find suitable object file for build/objs/src/modules/rlm_eap/types/rlm_eap_fast/.lo
make: *** [build/lib/local/.la] Error 1
--

**Comment by alandekok** [comment]
re-run `configure` and re-build.

**Comment by dhpark21** [comment]
I do but same problem hapen.
also again get git, same.. Hum...

Thanks
