### ISSUE TITLE
[Feature] Review the CRL handling

### ISSUE THREAD

**Issue by bigbig6** [FreeRADIUS/freeradius-server#1858]
# Issue type
- [ x] Feature request.

See [here](https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/doc/bugs) for debugging instructions.

Hi,

In Freeradius, the use of CRL is not really simple.

We need to merge the CRL with the root certificate, AND to restart FreeRadius.
And that a each new CRL. If we generate a new CRL every hours, it could be very hard.

Is it possible to have a directory where CRL are generated, and FreeRadius will look for CRL in files of this directory, without the need of a restart the process.

In some case we need to revoke certificates before they expires, and we can't stop the service all the time.

Thanks'.

Regards,

Olivier

**Comment by arr2036** [comment]
That'd be the feature there's already a pull request for:

	https://github.com/FreeRADIUS/freeradius-server/pull/1577

**Comment by alandekok** [comment]
See #1831.  This is being tracked.

**Comment by bigbig6** [comment]
Sorry, didn't found these seem to respond tothe need.

Thanks'!

Olivier
