### ISSUE TITLE
Access-Accept from eduroam NRPS with four MS-MPPE

### ISSUE THREAD

**Issue by emilio1980** [FreeRADIUS/freeradius-server#1868]
Hi,

i receive four MS-MPPE keys in Access-Accept from foreign authentication.

rad_recv: Access-Accept packet from host x.x.x.x port 1812, id=74, length=274
	User-Name = "XXXXXXXXX@XXXXXXX"
	MS-MPPE-Send-Key = 0x21affd40b998841513dc495ddd8a33f4
	MS-MPPE-Recv-Key = 0x445bfd3934f2091a4b8ba07f5d6a545d
	Message-Authenticator = 0xbc7659393cc88c490b4568398ba91b1e
	MS-MPPE-Recv-Key = 0x1081007c1f41ada3ee092812aa930bdcdde73796edab905e7b319470eea015c1
	MS-MPPE-Send-Key = 0xf3b79edab516cb68d5e24c1583a2e3cb369e4bd19769150e508da4031a3a8ac5
	EAP-Message = 0x035c0004
	Proxy-State = 0x323534

The client does not send a dhcp discover.

Thanks

Emilio

**Comment by arr2036** [comment]
Please use the FreeRADIUS users list for support queries http://freeradius.org/list/users.html
