### ISSUE TITLE
Variable expansion for SQL attributes

### ISSUE THREAD

**Issue by javiermatos** [FreeRADIUS/freeradius-server#1870]
# Issue type
- [ x ] Feature request.

# Defect/Feature description
I have FreeRADIUS running with a sql database in production. I am using the sql database to set user's check and reply attributes. The problem I have is that there are some attributes that I need to set them depending on the NAS identity (or any other FreeRADIUS variable), so I have to edit the configuration file and do something like this:

```Some-Attribute := "%{variable}-something-else"```

The thing I want is to be able to use variables in the sql database. Then, when FreeRADIUS get the attributes from the sql database it has to expand or evaluate those variables and then continue as usual. I don't want to modify the configuration file to store any user's configuration.

Will that feature make sense? I can help in programming it or even make a donation to have someone help me in doing this.

**Comment by mcnewton** [comment]
Questions like this belong on the freeradius-users list, not in GitHub. See SQL xlat expansion ``%{sql:SELECT ...}``.
