### ISSUE TITLE
acctuniqueid is not really unique

### ISSUE THREAD

**Issue by luis-sanmiguel** [FreeRADIUS/freeradius-server#1871]
From http://freeradius.org/radiusd/man/rlm_acct_unique.txt:

acct_unique {
		   key = "User-Name, Acct-Session-Id, NAS-IP-Address, NAS-Port"

When NAS crash, may begin re-using session IDs for the same user generating the same key:

(8) sql: Executing query: INSERT INTO radacct (acctsessionid,           acctuniqueid,           username, realm,                        nasipaddress,          nasportid, nasporttype,          acctstarttime,          acctupdatetime, acctstoptime,           acctsessiontime,        acctauthentic, connectinfo_start,      connectinfo_stop,        acctinputoctets, acctoutputoctets,      calledstationid,        callingstationid, acctterminatecause,   servicetype,            framedprotocol, framedipaddress) VALUES ('4D2BB8AC-00000098', '3c39ff3dddea80147fd9243fd6531675', 'admin', '', '127.0.0.1', '0', 'Wireless-802.11', FROM_UNIXTIME(1482435946), FROM_UNIXTIME(1482435946), NULL, '0', 'RADIUS', 'CONNECT 48Mbps 802.11b', '', '0', '0', '00-02-6F-AA-AA-AA:My Wireless', '00-1C-B3-AA-AA-AA', '', '', '', '')
(8) sql: rlm_sql_mysql: ERROR 1062 **(Duplicate entry '3c39ff3dddea80147fd9243fd6531675' for key 'acctuniqueid')**: 23000
(8) sql: SQL query returned: need alt query
(8) sql: Trying next query...
(8) sql: EXPAND UPDATE radacct SET acctstarttime        = FROM_UNIXTIME(%{integer:Event-Timestamp}), acctupdatetime     = FROM_UNIXTIME(%{integer:Event-Timestamp}), connectinfo_start = '%{Connect-Info}' WHERE AcctUniqueId = '%{Acct-Unique-Session-Id}'
(8) sql:    --> UPDATE radacct SET acctstarttime        = FROM_UNIXTIME(1482435946), acctupdatetime     = FROM_UNIXTIME(1482435946), connectinfo_start = 'CONNECT 48Mbps 802.11b' WHERE AcctUniqueId = '3c39ff3dddea80147fd9243fd6531675'
(8) sql: Executing query: UPDATE radacct SET acctstarttime      = FROM_UNIXTIME(1482435946), acctupdatetime     = FROM_UNIXTIME(1482435946), connectinfo_start = 'CONNECT 48Mbps 802.11b' WHERE AcctUniqueId = '3c39ff3dddea80147fd9243fd6531675'
rlm_sql_mysql: Rows matched: 1  Changed: 1  Warnings: 0
(8) sql: SQL query returned: success
(8) sql: 1 record(s) updated

The problem is that the UPDATE statement really does not update the acctstoptime field resulting into this:

| radacctid | acctsessionid     | acctuniqueid                     | username | groupname | realm | nasipaddress | nasportid | nasporttype     | acctstarttime       | acctupdatetime      | acctstoptime        | acctinterval | acctsessiontime | acctauthentic | connectinfo_start      | connectinfo_stop       | acctinputoctets | acctoutputoctets | calledstationid               | callingstationid  | acctterminatecause | servicetype | framedprotocol | framedipaddress |
+-----------+-------------------+----------------------------------+----------+-----------+-------+--------------+-----------+-----------------+---------------------+---------------------+---------------------+--------------+-----------------+---------------+------------------------+------------------------+-----------------+------------------+-------------------------------+-------------------+--------------------+-------------+----------------+-----------------+
|         3 | 4D2BB8AC-00000098 | a372e9c58d26e9c497f9e5623b311182 | alice    |           |       | 127.0.0.1    | 0         | Wireless-802.11 | 2016-12-22 21:09:14 | 2016-12-22 21:09:14 | **2016-12-22 21:09:00** |         NULL |              30 | RADIUS        | CONNECT 48Mbps 802.11b | CONNECT 48Mbps 802.11b |            3407 |              867 | 00-02-6F-AA-AA-AA:My Wireless | 00-1C-B3-AA-AA-AA | User-Request       |             |                |                 |

Queries for simul_count_query fail because the expect 'acctstoptime' field to be NULL (/etc/raddb/mods-config/sql/main/mysql/queries.conf):

simul_count_query = "\
        SELECT COUNT(*) \
        FROM ${acct_table1} \
        WHERE username = '%{SQL-User-Name}' \
        AND acctstoptime IS NULL"

Users can login as many times as they want ignoring the limit from 'Simultaneous-Use' field:

|  2 | alice    | Cleartext-Password | := | pass  |
|  3 | alice    | Simultaneous-Use   | := | 1     |
+----+----------+--------------------+----+-------+

My english is completly rusty but I thing you will understand.

**Comment by alandekok** [comment]
> When NAS crash, may begin re-using session IDs for the same user generating the same key:

The NAS is broken.  Throw it in the garbage and buy one that works.

https://tools.ietf.org/html/rfc2866#section-5.1

The NAS is supposed to send an accounting packet with `Acct-Status-Type = Accounting-On`.  That tells FreeRADIUS that the NAS has rebooted.  FreeRADIUS then clears out all active connections for that NAS.

> Queries for simul_count_query fail because the expect 'acctstoptime' field to be NULL (/etc/raddb/mods-config/sql/main/mysql/queries.conf):

`acctstoptime` is `NULL` only for active sessions.  If the NAS reboots, those sessions aren't active.  But the server has no idea, because the NAS has violated the RFCs.

> Users can login as many times as they want ignoring the limit from 'Simultaneous-Use' field:

How?  If you have `acctstoptime == NULL`, then `Simultaneous-Use` will think that a session is already active.  It will then deny the new login.

Unless you can show me *how* users can login multiple times, then I'm going to close this issue.  The NAS is broken, and is violating the RFCs.  Fix it, or buy a NAS that works.

**Comment by alandekok** [comment]
I'm closing this as there has been no further feedback.
