### ISSUE TITLE
Bad talloc magic value - unknown value

### ISSUE THREAD

**Issue by penguinhakan** [FreeRADIUS/freeradius-server#1872]
Linux Version : Linux xxxx 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Radius Version : radiusd: FreeRADIUS Version 3.0.12, for host x86_64-redhat-linux-gnu, built on Sep 29 2016 at 18:26:26
FreeRADIUS Version 3.0.12

Database : PostgreSQL 9.5.0.5

Radius gives below error a few hours after radius is starting...

Sat Dec 31 19:15:28 2016 : Info: rlm_sql (sql): Need 1 more connections to reach 10 spares
Sat Dec 31 19:15:28 2016 : Info: rlm_sql (sql): Opening additional connection (533), 1 of 22 pending slots used
Bad talloc magic value - unknown value

talloc abort: Bad talloc magic value - unknown value

**Comment by arr2036** [comment]
The issue template exists for a reason.
