### ISSUE TITLE
Freeradius latest version installation issues on RHEL OS

### ISSUE THREAD

**Issue by shashankganguly** [FreeRADIUS/freeradius-server#1873]
I am trying to install freeradius version 3 on RHEL 5 OS but getting some issues due to missing dependant files. Do I need to get OS upgraded to RHEL 6.5 from current version so as to install the freeradius version 3, or it can be installed on RHEL 5 OS also???

rpm -ivh freeradius-3.0.3-1.2.x86_64.rpm
warning: freeradius-3.0.3-1.2.x86_64.rpm: Header V3 RSA/SHA1 signature: NOKEY, key ID d364d346
error: Failed dependencies:
        libcrypto.so.10()(64bit) is needed by freeradius-3.0.3-1.2.x86_64
        libcrypto.so.10(OPENSSL_1.0.1)(64bit) is needed by freeradius-3.0.3-1.2.x86_64
        libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit) is needed by freeradius-3.0.3-1.2.x86_64
        libcrypto.so.10(libcrypto.so.10)(64bit) is needed by freeradius-3.0.3-1.2.x86_64
        libpcap.so.1()(64bit) is needed by freeradius-3.0.3-1.2.x86_64
        libreadline.so.6()(64bit) is needed by freeradius-3.0.3-1.2.x86_64
        libssl.so.10()(64bit) is needed by freeradius-3.0.3-1.2.x86_64
        libssl.so.10(libssl.so.10)(64bit) is needed by freeradius-3.0.3-1.2.x86_64
        rpmlib(FileDigests) <= 4.6.0-1 is needed by freeradius-3.0.3-1.2.x86_64
        rpmlib(PayloadIsXz) <= 5.2-1 is needed by freeradius-3.0.3-1.2.x86_64

**Comment by spaetow** [comment]
Look at the repo where you downloaded it. If it says it's a CentOS/RHEL 6 repo, then yes, you need to upgrade. If there is no RHEL 5 repo for you to use, you'll need to spin your own, and it should not be too difficult provided RHEL 5 has the appropriate tools for it.

**Comment by alandekok** [comment]
The template exists for a reason.  Ignoring it, and it's instructions, is antisocial.
