### ISSUE TITLE
Problem with User-Name attribute in preprocessing

### ISSUE THREAD

**Issue by loopholdgit** [FreeRADIUS/freeradius-server#1874]
# Issue type

- [x] Defect - Unexpected behaviour (obvious or verified by project member).

# Defect/Feature description
## How to reproduce issue

Prepocessing does not work as expected with hints file.

We are trying to add the domain name domain.loc automatically using preprocessing with hints file. However based on the below entries in the hints file, the radius server completely removes the "User-Name" attribute instead of appending the domain.loc name to it. 
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

```text
Received Access-Request Id 0 from x.x.x.x:1047 to x.x.x.x:1812 length 98
        NAS-Identifier = 'IDENTIFIER'
        Service-Type = Login-User
        User-Password = 'password'
        User-Name = 'radiususer'
        Calling-Station-Id = 'x.x.x.x'
(0) Received Access-Request packet from host x.x.x.x port 1047, id=0, length=98
(0)     NAS-Identifier = 'IDENTIFIER'
(0)     Service-Type = Login-User
(0)     User-Password = 'password'
(0)     User-Name = 'radiususer'
(0)     Calling-Station-Id = 'x.x.x.x'
(0) # Executing section authorize from file /etc/raddb/sites-enabled/default
(0)   authorize {
(0)   filter_username filter_username {
(0)     if (!&User-Name)
(0)     if (!&User-Name)  -> FALSE
(0)     if (&User-Name =~ / /)
(0)     if (&User-Name =~ / /)  -> FALSE
(0)     if (&User-Name =~ /@.*@/ )
(0)     if (&User-Name =~ /@.*@/ )  -> FALSE
(0)     if (&User-Name =~ /\\.\\./ )
(0)     if (&User-Name =~ /\\.\\./ )  -> FALSE
(0)     if ((&User-Name =~ /@/) && (&User-Name !~ /@(.+)\\.(.+)$/))
(0)     if ((&User-Name =~ /@/) && (&User-Name !~ /@(.+)\\.(.+)$/))   -> FALSE
(0)     if (&User-Name =~ /\\.$/)
(0)     if (&User-Name =~ /\\.$/)   -> FALSE
(0)     if (&User-Name =~ /@\\./)
(0)     if (&User-Name =~ /@\\./)   -> FALSE
(0)   } # filter_username filter_username = notfound
(0)  preprocess : hints: Matched DEFAULT at 39
(0)  preprocess : EXPAND %{User-Name}@domain.loc
(0)  preprocess :    --> @domain.loc
```

hint file entry:

```text
DEFAULT NAS-Identifier == "IDENTIFIER"
       User-Name := "%{User-Name}@domain.loc" 
```

**Comment by alandekok** [comment]
Which version is this?

And honestly.. this can better be done in an unlang policy.

    if (NAS-Identifier == "foo") {
        update request {
            User-Name := "%{User-Name}@domain.loc"
        }
    }

**Comment by loopholdgit** [comment]
The version of freeradius server is: freeradius-3.0.4-6.el7.x86_64

 

If I try to put your statement below in the hints file, the server does not start anymore and shows the following error:

 

reading pairlist file /etc/raddb/mods-config/preprocess/hints

/etc/raddb/mods-config/preprocess/hints[39]: Parse error (check) for entry if: Invalid attribute name

rlm_preprocess: Error reading /etc/raddb/mods-config/preprocess/hints

/etc/raddb/mods-enabled/preprocess[13]: Instantiation failed for module "preprocess"

 

 

Please advise.

**Comment by alandekok** [comment]
> The version of freeradius server is: freeradius-3.0.4-6.el7.x86_64

Then upgrade to a recent version.

> If I try to put your statement below in the hints file, 

That is entirely the wrong thing to do.

It goes into `raddb/sites-enabled/default`.

**Comment by loopholdgit** [comment]
Thank you! 

Putting the command in  raddb/sites-enabled/default works.
