### ISSUE TITLE
freeradius segfaults when using rlm_python

### ISSUE THREAD

**Issue by hhabjan** [FreeRADIUS/freeradius-server#1884]
Hi.

First post here. :-)

I'm using freeradius 2.2.9, on x64 Linux (centos 6.8), packaged python. This worked well, but suddenly freeradius started to crash. As far as i know, nothing changed on server itself.

Using gdb and backtracking, segfault was at src/modules/rlm_python/rlm_python.c, line 415 - this is:

my_thread_state = PyThreadState_New(inst->main_thread_state->interp);

More investigation with gdb revealed that when this broke, inst->main_thread_state is actually "NULL", and reference from NULL pointer causes segfault.

Now, this is very odd - how it could happen that this is null? Python module is defined as:

python my-onlinestatus1 {
        mod_instantiate = online_status1
        func_instantiate = instantiate

        mod_post_auth = online_status1
        func_post_auth = post_auth
}

Python code itself have defined both "instantiate" and "post_auth" functions.

Looking  at radiusd -X does not reveal any problems - when flow need to enter python module, sigsegv is generated.

The fix is simple, but potentially dangerous - in line before, i just added check if inst->main_thread_state is null, and if it is, initiate it as it was dine in python_init function (rlm_python.c). I would post a patch, but this is very clear:

NOTE: PATCHES GO IN PULL REQUESTS.  IF YOU SUBMIT A DIFF HERE, THE DEVELOPMENT TEAM WILL HUNT YOU DOWN AND BEAT YOU OVER THE HEAD WITH YOUR OWN KEYBOARD. 

Can you provide any insight what is happening here? python_init should be called before do_python - is it possible that there is a case when this can be skipped?

This is production platform so proper debugging is not easily done ...

Regards,

H.

**Comment by alandekok** [comment]
On Jan 20, 2017, at 6:39 AM, Hrvoje <notifications@github.com> wrote:
> 
> First post here. :-)
> 
> I'm using freeradius 2.2.9,

  Version 2 is end of life.  Please upgrade to version 3.

> The fix is simple, but potentially dangerous - in line before, i just added check if inst->main_thread_state is null, and if it is, initiate it as it was dine in python_init function (rlm_python.c).

  That's a work-around.  Not a fix.  A fix would be to find the cause of the problem, and then fix that.

> I would post a patch, but this is very clear:
> 
> NOTE: PATCHES GO IN PULL REQUESTS. IF YOU SUBMIT A DIFF HERE, THE DEVELOPMENT TEAM WILL HUNT YOU DOWN AND BEAT YOU OVER THE HEAD WITH YOUR OWN KEYBOARD.
> 
> Can you provide any insight what is happening here? python_init should be called before do_python - is it possible that there is a case when this can be skipped?

  No idea.  Version 2 is end of life.  We're not going to debug problems with code that's not supported.

> This is production platform so proper debugging is not easily done ...

  It's 2017.  You should be able to spin up a VM for testing.

**Comment by alandekok** [comment]
https://freeradius.org/download.html

*The 2.2.x release series is now End Of Life. Only security fixes will be applied to 2.2.x. Users of 2.2.x are encouraged to migrate to the latest 3.0.x series release.*

**Comment by arr2036** [comment]
A significant amount of work has gone into the rlm_python in version >= v3.0.x to make it work correctly with thread specific variables and multiple instances of the module.  We will not be back porting that work to v2.2.x.

I stand by the comment in the contributions notes.  GitHub is designed to make accepting contributions to open source projects easier, but it only does that if people use it correctly.

For simple patches GitHub's built in editor allows you to submit pull requests from the website, no forking/branching or use of Git required.

**Comment by hhabjan** [comment]
Hi.

Yes, switching over to 3.x is in TODO ... I needed a work-around fast.

I'll try to speed up migration to 3.x, and report back ...

H.
