### ISSUE TITLE
radacct folder (and table) empty

### ISSUE THREAD

**Issue by lcipriani** [FreeRADIUS/freeradius-server#1889]
# Issue type
I installed freeradius 3.0.12 version from source code, I enabled details and sql modules, on accounting section.
But don't see any log  in radacct folder and in radacct table. Is it a version problem? 

Thanks

**Comment by arr2036** [comment]
Please ask questions on the FreeRADIUS users list. Github is not used for support questions.

http://freeradius.org/list/users.html

**Comment by lcipriani** [comment]
many thanks

**Comment by rdumitru** [comment]
@lcipriani , I am having a similar issue, just curious if you remember the solution to this. I get Post-Auth logs in my "radpostauth" table, but I get nothing in "radacct". I enabled the sql module for both accounting and post-auth in sites-enabled/default.
