### ISSUE TITLE
`cipher_list` primed for EAP-FAST rather than `DEFAULT`

### ISSUE THREAD

**Issue by jimdigriz** [FreeRADIUS/freeradius-server#1897]
Back in commit 8cbb88793728ce61a8c15ef9669723ce7f9835bd a sample EAP-FAST snippet was added, but then commented out in 17fb58f22b59664028efb83fe6e87cb1883c0133.  `cipher_list` though retained being set to the EAP-FAST recommendation of `ALL:!EXPORT:!eNULL:!SSLv2` rather than `DEFAULT`.

This an oversight, as now NULL encryption is permitted by default, unless I misunderstand something?

s/encryption/authentication/

**Comment by alandekok** [comment]
The `cipher_list` should be what works for most protocols.  IIRC, EAP-FAST has different requirements, and should have a different cipher list.  So the default should probably be for everything *but* EAP-FAST.

**Comment by alandekok** [comment]
I think the config now has `cipher_list = DEFAULT`, so that should be fine.
