### ISSUE TITLE
Radsniff-Load test -Stop packet processing and <Cleaning up request packet ID> console log

### ISSUE THREAD

**Issue by mmanoj** [FreeRADIUS/freeradius-server#1899]
Dear Team,

I'm running load test to simulate the load for radsniff tool with tcpreplay and replaying captured pcap file with radius traffic. While I'm doing with 25 PPS rate I observed below logs in console. Same time radsniffer stop processing the data.

Seeking your advice to fix this issue. I' compiled from source <version -3.1.0>

Step 1: sudo ./radsniff -i wlp1s0 -x

Step: sudo ./tcpreplay --pps=25 --intf1=wlp1s0 /opt/radius/radius_live_2016.pcap

Logs in the console:
```
2017-02-07 00:18:53.728483 (58) Cleaning up request packet ID 145
2017-02-07 00:18:53.728511 (60) Cleaning up request packet ID 208
2017-02-07 00:18:53.728518 (61) Cleaning up request packet ID 212
2017-02-07 00:18:53.728573 (64) Cleaning up request packet ID 109
2017-02-07 00:18:53.728579 (65) Cleaning up request packet ID 113
2017-02-07 00:18:53.728586 (67) Cleaning up request packet ID 120
2017-02-07 00:18:53.728592 (66) Cleaning up request packet ID 114
2017-02-07 00:18:53.728604 (73) ** norsp ** Access-Request Id 121 wlp1s0:10.30.30.59:53810 -> 10.30.30.52:1812
2017-02-07 00:18:53.728604 (73) Cleaning up request packet ID 121
```

**Comment by arr2036** [comment]
This is normal output from radsniff? Also radsniff can operate directly on .pcap files you don't need to use tcpreplay.

If you still think there's a problem run radsniff under gdb and break where you think the issue is occurring, and post the backtrace.

**Comment by mmanoj** [comment]
Hi, This is observed while tcpreplay, normal sniff with pcap file it's fine. I'm try to load with radperf and test the same.

Basically I need to test radsniff with the 10k PPS. Please advice the way forward.

**Comment by alandekok** [comment]
> Basically I need to test radsniff with the 10k PPS. Please advice the way forward.

Send patches to increase it's performance.

I'm not even sure a plain vanilla PCAP will process 10K packets/s, while doing application-level checks on the packets.

**Comment by mmanoj** [comment]
@alandekok  & @arr2036 

Thanks for the quick response, Yes I also not think just pcap reading will five 10K PPS. I try to simulate but not much clue to make it this level.

However while I using TCPreplay I saw "(58) Cleaning up request packet ID 145" console and freeze packet processing.

This is the point I have dough if increase load will hang the sniffer processing packets ?

**Comment by mmanoj** [comment]
Also suggest if any tool can generate this type of load to radsniffer. I try radperf but sniffer not get any traffic.

Thanks in advance.

**Comment by alandekok** [comment]
If you want 10K pps, you'll need to buy a commercial product.  Or, submit patches to make radsniff  process 10K pps.

This kind of issue is a very low priority for us.  It's a rare requirement, and it's hard to fix.

If you really need 10K pps, you're probably working for a large company that can afford to put resources into fixing the problem.

**Comment by mmanoj** [comment]
Hi, 
I'm freelance researcher and doing performance analysis as per the documentation shows sniffer can handle 30K PPS, so I just check the possibility of handling 10K PPS. So I can see the resource utilization and bottlenecks if any.

As Volunteer effort I can look in to the possible patch to improve the performance if you can guide me areas of the code base I have to look in to.

Thank you,

**Comment by mmanoj** [comment]
Also indicate what is the tested max supported PPS for sniffer in open source version. As per below doc it support 30K PPS
https://wiki.freeradius.org/guide/stats-with-radsniff

**Comment by arr2036** [comment]
If you run it on a 486DX it's not going to achieve 30K PPS.  If you want to continue this discussion please do it on the users mailing list: https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/.github/contributing.md#github-issue-tracker
