### ISSUE TITLE
Sending POST data using rlm_rest with application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by ddavtian** [FreeRADIUS/freeradius-server#1903]
Hello,

I have been scratching my head for a few hours on this, I am hoping someone can point me in the right direction?

I am trying to POST application/x-www-form-urlencoded data to a REST endpoint. The requirement is to POST username and password. This is what I have done so far in my rest config.

```
        authorize {
                uri = "${..cmx_uri}/cas/v1/tickets"
                method = 'post'
                body = 'post'
                data = '"username=david"&"password=davo"'
        }
        authenticate {
                uri = "${..cmx_uri}/cas/v1/tickets"
                method = 'post'
                body = 'post'
                data = '"username=david"&"password=davo"'
        }
```

The REST endpoint is kicking me back with the following error.

```
(0) Wed Feb  8 19:43:05 2017: ERROR: rest-cmx-glplum: Server returned:
(0) Wed Feb  8 19:43:05 2017: ERROR: rest-cmx-glplum: Invalid payload. 'username' and 'password' form fields are required.
```

**Comment by arr2036** [comment]
http://freeradius.org/list/users.html

https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/.github/contributing.md#github-issue-tracker
