### ISSUE TITLE
TACACS+ 'arg' support

### ISSUE THREAD

**Issue by jimdigriz** [FreeRADIUS/freeradius-server#1908]
# Issue type
- [ ] Defect - Crash or memory corruption.
- [X] Defect - Non compliance with a standards document, or incorrect API usage.
- [ ] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect/Feature description

TACACS+ supports bidirectional arbitrary key/values [on authorisation and accounting packets (sections 5 and 6)](https://datatracker.ietf.org/doc/draft-ietf-opsawg-tacacs/?include_text=1), that I have so far quietly ignored.

FR does support non-dictionary attributes, starting place to look is `dict_read_process_named_attribute()`.

**Comment by arr2036** [comment]
During decode can check to see if they're in the dictionary with ``fr_dict_attr_by_name``, and then we'll need a new dictionary function to allocate an unknown attribute with a specific name, ``attr == 0`` and parented from the tacacs root da.

That won't allow the unknowns to be referenced in unlang, or encoded in a foreign protocol like RADIUS or DIAMETER but never mind.

**Comment by alandekok** [comment]
We really also need a TACACS+ module, which implements TACACS+ ACLs in the way that people are used to.  That module would care about names, not numbers...

**Comment by jimdigriz** [comment]
Do all DNS servers *have* to use a BIND9 compatible zone format?  In the case of TACACS+ ACLs are people using them because they want to, or because they have to?  Having glanced at [some](http://www.shrubbery.net/tac_plus/) [examples](http://www.cisco.com/c/en/us/support/docs/security-vpn/terminal-access-controller-access-control-system-tacacs-/13852-http-1.html?mdfid=279970612#tac) [online](https://networkjutsu.com/tacacs/) I find it hard to believe it is the former...

I suspect there is quite a lot of carrot moving to FreeRADIUS, and the unlang probably does not make for much of a stick?

I suspect a number of unlang/helper modules will be needed, but probably they will jsut take the form of `policy.d` files?

**Comment by alandekok** [comment]
> Do all DNS servers have to use a BIND9 compatible zone file format?

The point is to lower the cost of switching software products.  Supplying a Perl script to convert TACACS+ ACLs to FreeRADIUS format (whatever that is) is a good start.  An even better thing would be to just use the existing formats, no matter how horrific they are.

Once people have switched to better product, they can then start using real policies, databases, etc.

**Comment by alandekok** [comment]
The server core and TACACS+ now permit random / arbitrary values for TACACS `ARGV`
