### ISSUE TITLE
Calling ORACLE stored proc raises ORA-24333: zero iteration count

### ISSUE THREAD

**Issue by ibaguio** [FreeRADIUS/freeradius-server#1932]
I've compiled and configured my freeradius (3.0.4) to work with **Oracle XE 11g** using rlm_sql_oracle, out of the box, everything works fine as it should. But when i start calling stored procedures via the SQL modifier, I get a **ERROR: rlm_sql_oracle: ORA-24333: zero iteration count**.

I've played around with different configurations on the sites-enabled file

        if (&User-Name == 'test') {
                %{sql:execute STORED_PROC()}    # does not work
                %{sql:STORED_PROC()}                  # does not work                
                %{sql:execute STORED_PROC() by oracle}    # does not work
        }

All attempts lead to the following error

    (0)       Executing select query: execute STORED_PROC()
    rlm_sql_oracle: query failed in sql_select_query
    rlm_sql_oracle: OCI_SERVER_NORMAL
    (0)       ERROR: rlm_sql_oracle: ORA-24333: zero iteration count
    (0)       ERROR: SQL query failed: <INVALID>
    rlm_sql (sql): Released connection (0)
    rlm_sql (sql): Need 5 more connections to reach 10 spares
    rlm_sql (sql): Opening additional connection (5), 1 of 27 pending slots used
    (0)       EXPAND %{sql:execute STORED_PROC()}
    (0)          --> 

I've verified that *STORED_PROC* is valid and works correctly as it should, the stored proc, if working/called correctly, should inserts a row to the table, which lets me know that it works, but no data is inserted when called from freeradius.

Prior to Oracle, i've had stored procedures working with MySQL without a problem, and can't seem to understand how to make them work in Oracle

**Comment by alandekok** [comment]
I believe this is fixed a year ago in the main v3.0.x branch.  Please see 3.0.13.  If it isn't fixed, please re-open the issue.

**Comment by ibaguio** [comment]
@alandekok, thanks for the response, as per checking on my freeradius version, I am running **3.0.12**, and not **3.0.4** as initially reported; I have 2 radius binaries installed, one 3.0.4 (installed via yum install), and the other 3.0.12 (compiled from source). I will update to 3.0.13 and do more tests. Thanks

**Comment by Turin86** [comment]
I'm having the same problem.
Other SQL drivers work fine. It seems an Oracle driver issue.

FreeRADIUS Version 3.0.17, for host x86_64-unknown-linux-gnu

```
rlm_sql (sql_oracle_dscorp): Reserved connection (0)
(0)       Executing select query: CALL whatever('param1', 'param2')
rlm_sql_oracle: query failed in sql_select_query
rlm_sql_oracle: OCI_SERVER_NORMAL
(0)       ERROR: rlm_sql_oracle: ORA-24333: zero iteration count 
(0)       ERROR: SQL query failed: <INVALID>
rlm_sql (sql_oracle_dscorp): Released connection (0)
```
