### ISSUE TITLE
Possible NULL-pointer dereference in cache_merge

### ISSUE THREAD

**Issue by spbnick** [FreeRADIUS/freeradius-server#1935]
# Issue type
- [x] Defect - Crash or memory corruption.
- [ ] Defect - Non compliance with a standards document, or incorrect API usage.
- [ ] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect/Feature description

Clang-scan has reported the following issue in v3.0.13:

    1. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:152:28: warning: Access to field 'vps' results in a dereference of a null pointer (loaded from field 'packet')
    #                 vp = fr_pair_find_by_num(request->packet->vps, PW_CACHE_ENTRY_HITS, 0, TAG_ANY);
    #                                          ^
    4. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:254:30: note: Left side of '&&' is false
    #         if ((inst->max_entries > 0) && inst->module->count &&
    #                                     ^
    7. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:261:6: note: Assuming 'c' is non-null
    #         if (!c) return RLM_MODULE_FAIL;
    #             ^~
    10. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:261:2: note: Taking false branch
    #         if (!c) return RLM_MODULE_FAIL;
    #         ^
    13. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:274:25: note: Assuming 'map' is equal to null
    #         for (map = inst->maps; map != NULL; map = map->next) {
    #                                ^~~~~~~~~~~
    16. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:274:2: note: Loop condition is false. Execution continues on line 336
    #         for (map = inst->maps; map != NULL; map = map->next) {
    #         ^
    19. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:337:9: note: Left side of '&&' is false
    #         if (vp && (vp->vp_integer == 0)) merge = false;
    #                ^
    22. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:339:2: note: Taking true branch
    #         if (merge) cache_merge(inst, request, c);
    #         ^
    25. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:339:13: note: Calling 'cache_merge'
    #         if (merge) cache_merge(inst, request, c);
    #                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    28. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:122:9: note: Left side of '&&' is false
    #         if (vp && (vp->vp_integer == 0)) {
    #                ^
    31. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:127:2: note: Left side of '||' is true
    #         RDEBUG2("Merging cache entry into request");
    #         ^
    34. freeradius-server-3.0.13/src/include/log.h:238:45: note: expanded from macro 'RDEBUG2'
    # #define RDEBUG2(fmt, ...)       if (rad_debug_lvl || request->log.lvl) radlog_request(L_DBG, L_DBG_LVL_2, request, fmt, ## __VA_ARGS__)
    #                                                   ^
    37. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:127:2: note: Value assigned to field 'packet'
    #         RDEBUG2("Merging cache entry into request");
    #         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    40. freeradius-server-3.0.13/src/include/log.h:238:66: note: expanded from macro 'RDEBUG2'
    # #define RDEBUG2(fmt, ...)       if (rad_debug_lvl || request->log.lvl) radlog_request(L_DBG, L_DBG_LVL_2, request, fmt, ## __VA_ARGS__)
    #                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    43. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:129:6: note: Left side of '&&' is true
    #         if (c->packet && request->packet) {
    #             ^
    46. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:129:6: note: Assuming pointer value is null
    #         if (c->packet && request->packet) {
    #             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    49. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:129:2: note: Taking false branch
    #         if (c->packet && request->packet) {
    #         ^
    52. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:134:15: note: Left side of '&&' is false
    #         if (c->reply && request->reply) {
    #                      ^
    55. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:139:2: note: Taking false branch
    #         if (c->control) {
    #         ^
    58. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:144:2: note: Taking false branch
    #         if (c->state) {
    #         ^
    61. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:150:2: note: Taking true branch
    #         if (inst->stats) {
    #         ^
    64. freeradius-server-3.0.13/src/modules/rlm_cache/rlm_cache.c:152:28: note: Access to field 'vps' results in a dereference of a null pointer (loaded from field 'packet')
    #                 vp = fr_pair_find_by_num(request->packet->vps, PW_CACHE_ENTRY_HITS, 0, TAG_ANY);
    #                                          ^        ~~~~~~
    #   150|   	if (inst->stats) {
    #   151|   		rad_assert(request->packet != NULL);
    #   152|-> 		vp = fr_pair_find_by_num(request->packet->vps, PW_CACHE_ENTRY_HITS, 0, TAG_ANY);
    #   153|   		if (!vp) {
    #   154|   			vp = fr_pair_afrom_num(request->packet, PW_CACHE_ENTRY_HITS, 0);

Ultimately, the idea here I think is that request->packet can be NULL in
principle in cache_merge, nothing checks for that exclusively, and then the
code tries to access request->packet->vps. However, I'm not sure how such
condition should be handled, so I can't suggest a fix.

**Comment by alandekok** [comment]
We already run v3 through coverity pretty regularly.  The issue with coverity is that it doesn't know about the assumptions in the code.  e.g. `request->packet` is never NULL.

**Comment by spbnick** [comment]
Well, even if it truly can't be NULL, it might be a good idea to silence the warning, to leave some attention space for the important ones.

Also, wanted to verify with you that this line checking request->packet not being NULL doesn't mean it can be NULL after all: https://github.com/FreeRADIUS/freeradius-server/blob/d35e9b3549fc75938316336031f47709c82d1d00/src/modules/rlm_cache/rlm_cache.c#L129
