### ISSUE TITLE
Call of if (SQL-Group == "%{Some-Attribute}") ignores the attribute and always returns FALSE

### ISSUE THREAD

**Issue by bitak1** [FreeRADIUS/freeradius-server#1947]
# Issue type
- [ ] Defect - Crash or memory corruption.
- [ ] Defect - Non compliance with a standards document, or incorrect API usage.
- [x] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect description
I'm using some custom code in authorize section for a site. When I call virtual attribute SQL-Group with hardcoded string everything works correctly. If I use an attribute which needs to be expanded, SQL-Group doesn't work anymore.
## How to reproduce issue
For example I'm trying to athorize a user, who is member of the group with name Pokus. I have an attribute Called-Station-SSID and I've following code in: /etc/freeradius/sites-available/default in authorize section:
    
    authorize {
       filter_username
       preprocess
       rewrite_calling_station_id
       rewrite_called_station_id
       chap
       mschap
       digest
       suffix
       eap {
               ok = return
       }
       sql
       
       # here I print attribute Called-Station-SSID, just be sure, it's set
       "%{Called-Station-SSID}"
       
       # following test works as expected, the if block returns correctly if the user is part of a group Pokus 
       if (SQL-Group == "Pokus") {
               # ok to login
       }
       else {
               reject
       }
       # following test is defective
       # the if block returns always FALSE despite of the attribute Called-Station-SSID has value Pokus
       if (SQL-Group == "%{Called-Station-SSID}") {
               # ok to login
       }
       else {
               reject
       }

       files
       expiration
       logintime
       pap
    }

 
## Output of ``freeradius -X`` showing issue occurring

```text
...OUTPUT OMITTED...
(1)     EXPAND %{Called-Station-SSID}
(1)        --> Pokus
(1)     if (SQL-Group == "Pokus") {
(1)     sql_groupcmp
(1)     EXPAND %{User-Name}
(1)        --> pokususer
(1)     SQL-User-Name set to 'pokususer'
rlm_sql (sql): Reserved connection (2)
(1)     EXPAND SELECT groupname FROM radusergroup WHERE username = '%{SQL-User-Name}' ORDER BY priority
(1)        --> SELECT groupname FROM radusergroup WHERE username = 'pokususer' ORDER BY priority
(1)     Executing select query: SELECT groupname FROM radusergroup WHERE username = 'pokususer' ORDER BY priority
(1)     sql_groupcmp finished: User is a member of group Pokus
rlm_sql (sql): Released connection (2)
(1)     if (SQL-Group == "Pokus")  -> TRUE
(1)     (SQL-Group == "Pokus")  { ... } # empty sub-section is ignored
(1)     ... skipping else: Preceding "if" was taken
(1)     if (SQL-Group == "%{Called-Station-SSID}") {
(1)     EXPAND %{Called-Station-SSID}
(1)        --> Pokus
(1)     if (SQL-Group == "%{Called-Station-SSID}")  -> FALSE
(1)     else {
(1)       [reject] = reject
(1)     } # else = reject
(1)   } # authorize = reject
(1) Invalid user: [pokususer/<via Auth-Type = eap>] (from client pokus port 0 cli 44-85-00-00-83-EA)
(1) Using Post-Auth-Type Reject
(1) # Executing group from file /etc/freeradius/sites-enabled/default
(1)   Post-Auth-Type REJECT {
(1) sql: EXPAND .query
(1) sql:    --> .query
(1) sql: Using query template 'query'
rlm_sql (sql): Reserved connection (3)
...OUTPUT OMITTED...
```
info about my system:
```text
root@radius:~# freeradius -v
radiusd: FreeRADIUS Version 3.0.12, for host x86_64-pc-linux-gnu, built on Dec  3 2016 at 15:55:32
FreeRADIUS Version 3.0.12
Copyright (C) 1999-2016 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
root@radius:~# mysql --version
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
root@radius:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by alandekok** [comment]
Please give more information as documented https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/doc/bugs.md

Right now, this report doesn't contain enough information for us to track down the problem and fix it.

**Comment by alandekok** [comment]
Never mind.. I'll take a look

**Comment by krm3** [comment]
I've probably the same issue:

I'm using FreeRADIUS Version 3.0.12.

I'm doing EAP-TTLS/PAP and I have the following policy in the
authorize section of the inner tunnel virtual server (same behaviour
when it's in post-auth):

w2vgroupcheck {
    if("%{Stripped-User-Domain}" =~ /^([^\.]+)\.w2v\.kit\.edu$/) {
        if ("%{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}" > 0) {
            if (LDAP-Group == "%{sql:SELECT group_name FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}") {
                update reply {
                    Tunnel-Private-Group-Id := "%{sql:SELECT vlan_id FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}"
                    Tunnel-Type := VLAN
                    Tunnel-Medium-Type := IEEE-802
                }
            }
            else {
                reject
            }
        }
    }
}

Which results in:

(8)       policy w2vgroupcheck {                                                                                                                                                                  
(8)         if ("%{Stripped-User-Domain}" =~ /^([^\.]+)\.w2v\.kit\.edu$/) {                                                                                                                       
(8)         EXPAND %{Stripped-User-Domain}                                                                                                                                                        
(8)            --> vlan-1.w2v.kit.edu                                                                                                                                                        
(8)         if ("%{Stripped-User-Domain}" =~ /^([^\.]+)\.w2v\.kit\.edu$/)  -> TRUE                                                                                                                
(8)         if ("%{Stripped-User-Domain}" =~ /^([^\.]+)\.w2v\.kit\.edu$/)  {                                                                                                                      
(8)           if ("%{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}" > 0) {                                                      
rlm_sql (sql): Reserved connection (0)                                                                                                                                                            
(8)           Executing select query: SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('vlan-1.w2v.kit.edu', '\.w2v\.kit\.edu$', '')                                                  
rlm_sql_postgresql: Status: PGRES_TUPLES_OK                                                                                                                                                       
rlm_sql_postgresql: query affected rows = 1 , fields = 1                                                                                                                                          
rlm_sql (sql): Released connection (0) 
(8)           EXPAND %{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}
(8)              --> 1     
(8)           if ("%{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}" > 0)  -> TRUE
(8)           if ("%{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}" > 0)  {
(8)             if (LDAP-Group == "%{sql:SELECT group_name FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}") {
rlm_sql (sql): Reserved connection (1)                                       
(8)             Executing select query: SELECT group_name FROM w2v WHERE vlan_name=regexp_replace('vlan-1.w2v.kit.edu', '\.w2v\.kit\.edu$', '')
rlm_sql_postgresql: Status: PGRES_TUPLES_OK                                        
rlm_sql_postgresql: query affected rows = 1 , fields = 1
rlm_sql (sql): Released connection (1)                          
(8)             EXPAND %{sql:SELECT group_name FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}
(8)                --> KIT-Group-1
(8)             if (LDAP-Group == "%{sql:SELECT group_name FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}")  -> FALSE
(8)             else {                    
(8)               [reject] = reject
(8)             } # else = reject                                                    
(8)           } # if ("%{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}" > 0)  = reject
(8)         } # if ("%{Stripped-User-Domain}" =~ /^([^\.]+)\.w2v\.kit\.edu$/)  = reject
(8)       } # policy w2vgroupcheck = reject


So the SQL expansion works but then
there is no try to do the LDAP group check. It just says FALSE
and rejects. When I replace 
(LDAP-Group == "%{sql:SELECT group_name FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}") 
with
(LDAP-Group == "KIT-Group-1")
it works:

(8)       policy w2vgroupcheck {                                                                                                                                                         [50/1950]
(8)         if ("%{Stripped-User-Domain}" =~ /^([^\.]+)\.w2v\.kit\.edu$/) {                                                                                                                       
(8)         EXPAND %{Stripped-User-Domain}                                                                                                                                                        
(8)            --> vlan-1.w2v.kit.edu                                                                                                                                                        
(8)         if ("%{Stripped-User-Domain}" =~ /^([^\.]+)\.w2v\.kit\.edu$/)  -> TRUE                                                                                                                
(8)         if ("%{Stripped-User-Domain}" =~ /^([^\.]+)\.w2v\.kit\.edu$/)  {
(8)           if ("%{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}" > 0) {
rlm_sql (sql): Reserved connection (0)
(8)           Executing select query: SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('vlan-1.w2v.kit.edu', '\.w2v\.kit\.edu$', '')
rlm_sql_postgresql: Status: PGRES_TUPLES_OK                                              
rlm_sql_postgresql: query affected rows = 1 , fields = 1
rlm_sql (sql): Released connection (0)
(8)           EXPAND %{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}
(8)              --> 1                                                                          
(8)           if ("%{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}" > 0)  -> TRUE
(8)           if ("%{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}" > 0)  {
(8)             if (LDAP-Group == "KIT-Group-1") {                          
(8)             Searching for user in group "KIT-Group-1"                                                                                                                               
rlm_ldap (ldap): Reserved connection (1)
(8)             Using user DN from request "uid=abc123,ou=People,ou=unix,ou=IDM,dc=kit,dc=edu"
(8)             Checking for user in group objects
(8)               EXPAND (&(cn=KIT-Group-1)(objectClass=posixGroup)(memberUid=%{%{Stripped-User-Name}:-%{User-Name}}))
(8)                  --> (&(cn=KIT-Group-1)(objectClass=posixGroup)(memberUid=abc123))
(8)               Performing search in "ou=unix,ou=IDM,dc=kit,dc=edu" with filter "(&(cn=KIT-Group-1)(objectClass=posixGroup)(memberUid=abc123))", scope "sub"
(8)               Waiting for search result...
(8)             User found in group object "ou=unix,ou=IDM,dc=kit,dc=edu"
rlm_ldap (ldap): Released connection (1)
(8)             if (LDAP-Group == "KIT-Group-1")  -> TRUE
(8)             if (LDAP-Group == "KIT-Group-1")  {
(8)               update reply {
rlm_sql (sql): Reserved connection (1)
(8)                 Executing select query: SELECT vlan_id FROM w2v WHERE vlan_name=regexp_replace('vlan-1.w2v.kit.edu', '\.w2v\.kit\.edu$', '')
rlm_sql_postgresql: Status: PGRES_TUPLES_OK                                          
rlm_sql_postgresql: query affected rows = 1 , fields = 1
rlm_sql (sql): Released connection (1)                                                                                       
(8)                 EXPAND %{sql:SELECT vlan_id FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}
(8)                    --> 22                                                                                                                                                                    
(8)                 Tunnel-Private-Group-Id := 22
(8)                 Tunnel-Type := VLAN       
(8)                 Tunnel-Medium-Type := IEEE-802
(8)               } # update reply = noop
(8)             } # if (LDAP-Group == "KIT-Group-1")  = noop             
(8)             ... skipping else: Preceding "if" was taken
(8)           } # if ("%{sql:SELECT COUNT(*) FROM w2v WHERE vlan_name=regexp_replace('%{Stripped-User-Domain}', '\.w2v\.kit\.edu$', '')}" > 0)  = noop
(8)         } # if ("%{Stripped-User-Domain}" =~ /^([^\.]+)\.w2v\.kit\.edu$/)  = noop
(8)       } # policy w2vgroupcheck = noop

**Comment by arr2036** [comment]
Confirmed fixed by @krm3.
