### ISSUE TITLE
Module rlm_raw

### ISSUE THREAD

**Issue by pperzyna** [FreeRADIUS/freeradius-server#1948]
I would like to use rlm_raw for dynamic client ? Is avalaible for version 4 ?

**Comment by alandekok** [comment]
rlm_raw is not part of FreeRADIUS.  Ask the authors of rlm_raw about it.

And don't use version 4.  It's in major development, and is not intended to be used as part of normal installs.  In fact, there is just no reason to use v4, unless you're a FreeRADIUS developer.

The current supported release is 3.0.13.

**Comment by arr2036** [comment]
@pperzyna the client system for v4 should allow similar functionality (once complete) in that all attributes in the request may be used to query for client information.  Though one clients are added, the IP address is the only data used to identify the client, so you can't have multiple clients behind a NAT.

**Comment by arr2036** [comment]
@alandekok made the point (OOB) that the plan is to use UDP connected sockets, so in fact, multiple clients may work behind a NAT.
