### ISSUE TITLE
RADIUS VSA 26-10 and 26-11 Ingress/Egress-Policy-Name

### ISSUE THREAD

**Issue by MarijnvG** [FreeRADIUS/freeradius-server#1958]
Hello,

I'm trying to get subscriber management with dynamic filtering and policing working on my Juniper MX router, but it seems that it keeps saying that it's missing the inet filter name in the RADIUS logs.

Now, in the /usr/share/freeradius directory I cannot find any dictionairy with VSA's 26-10 (Ingress-Policy-Name) and 26-11 (Egress-Policy-Name). Can anybody tell me what's going on with this?

Now there is a dictionairy.unisphere (with attributes 10 and 11) but I think 26-10 and 26-11 are supposed to be used. Where can I find those or how would I use those attributes in the RADIUS server?

Thanks!

**Comment by spaetow** [comment]
Use the Unisphere-Ingress-Policy-Name and *-Egress-Policy-Name attributes in FreeRADIUS. See https://www.juniper.net/techpubs/software/junos/junos114/radius-dictionary/unisphereDictionary_for_JUNOS_v11-4.dct 

Also, for questions you should be using the FreeRADIUS Users mailing list, not open an issue on GitHub.

**Comment by MarijnvG** [comment]
Thanks spaetow, I've already opened a question on the mailing list.
