### ISSUE TITLE
Can't login to wiki.freeradius.org

### ISSUE THREAD

**Issue by C0rn3j** [FreeRADIUS/freeradius-server#1970]
The freeradius.org repo doesn't have an open issue tracker so I'm posting here, as I don't know where else I should.

Trying to log in always gives me the same error as on the screenshot.

http://i.imgur.com/BPtwqrN.png

**Comment by arr2036** [comment]
You need to designate a public email address:

![screen shot 2017-04-24 at 5 54 06 pm](https://cloud.githubusercontent.com/assets/791758/25360424/1252bd3c-2917-11e7-8231-8e16637878f5.png)

**Comment by C0rn3j** [comment]
Oh, I see, thanks a lot!
