### ISSUE TITLE
Dhcpclient in v3.0.13 doesn't accept port number

### ISSUE THREAD

**Issue by spbnick** [FreeRADIUS/freeradius-server#2000]
# Issue type
- [ ] Defect - Crash or memory corruption.
- [ ] Defect - Non compliance with a standards document, or incorrect API usage.
- [x] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect/Feature description
Despite being mentioned in the man page and in online help message,
`dhcpclient` from v3.0.13 release doesn't accept port number after server
hostname/address.

I'm not sure what should be fixed here: dhcpclient or documentation.

## How to reproduce issue

    $ dhcpclient -x localhost:67 discover
    dhcpclient: Failed resolving "localhost:67" to IPv4 address: Name or service not known
    $ dhcpclient -x 127.0.0.1:67 discover
    dhcpclient: Failed resolving "127.0.0.1:67" to IPv4 address: Name or service not known

**Comment by spbnick** [comment]
Also, do I get a prize for a round issue number :)?

**Comment by alandekok** [comment]
No prize.  Just the satisfaction of a job well done.

**Comment by spbnick** [comment]
That will do :) Thanks, Alan!
