### ISSUE TITLE
freeradius coa with fortigate

### ISSUE THREAD

**Issue by starking8b** [FreeRADIUS/freeradius-server#2015]
I want to send disconnect request to disconnect one user but when I send this request using radclient I have error that say "unsupported Attribute "
Nas is fortigate with ip 192.168.3.1
freeradius ip is 192.168.3.3

 
` cat packet.txt | radclient -x 192.168.3.1  disconnect  muh
Sending Disconnect-Request of id 53 to 192.168.3.1 port 3799
        User-Name = "zaib"
        NAS-IP-Address = 192.168.3.1
rad_recv: Disconnect-NAK packet from host 192.168.3.1 port 3799, id=53, length=50
        Error-Cause = Unsupported-Attribute
        Event-Timestamp = "Jul  4 2017 10:15:28 +03"
        Message-Authenticator = 0xb6f793d4fca17ca07bde2a7bf63312af
`

content of packet.txt is 
  User-Name = "zaib"
        NAS-IP-Address = 192.168.3.1

I don't know where is my wrong 
plz help me 
thank you very much

**Comment by mcnewton** [comment]
https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/.github/contributing.md#github-issue-tracker

But this isn't relevant for freeradius-users either. You need to ask Fortigate what attributes they expect.
