### ISSUE TITLE
Strange behaviour on -X mode

### ISSUE THREAD

**Issue by fattalgazi** [FreeRADIUS/freeradius-server#2016]
Hello all,

I'm using a VPN solution with radiusDB support for authentication and accounting. 

I am executing a PHP script in authorize section of default site configuration.

```
update control { 
        Auth-Type := `/usr/bin/php -f /var/www/html/bla.com/apiv10.php /vpn/login '%{User-Name}' '%{User-Password}' '%{Client-IP-Address}'`
    }
````

I added ```sleep(6);``` in my PHP for testing purposes because it connects a remote MySQL to check authentication and sometimes it may takes long time in production mode in high traffic as I guess.

I start freeRadius with -X option (to see logs) and I'm trying to connect VPN on my iPhone, everything works fine, freeRadius executes my PHP and waits a ACCEPT or REJECT message from it, after 2-3 seconds, VPN sends another Access-Request because of timeout, after 2-3 seconds sends another too. I see these in logs;

```
Sending Access-Accept Id 195 from 127.0.0.1:1812 to 127.0.0.1:49161
(6) Finished request
Received Access-Request Id 195 from 127.0.0.1:49161 to 127.0.0.1:1812 length 158
Sending Access-Accept Id 195 from 127.0.0.1:1812 to 127.0.0.1:49161
Waking up in 999542.9 seconds.
Received Access-Request Id 195 from 127.0.0.1:49161 to 127.0.0.1:1812 length 158
Sending Access-Accept Id 195 from 127.0.0.1:1812 to 127.0.0.1:49161
Waking up in 999542.9 seconds.
```

so it is basicly rejecting other two duplicated Access-Request as expected. All is good for now.

But when I try to connect VPN with 2 iPhones with 2 different accounts at the same time;

1- freeRadius waits for first PHP answer (6 seconds), does not analyze second Access-Request , it does not work simultaneously, so my first phone connects to VPN after 6 seconds, the other phone connects the VPN after first phone is connected , 12 seconds later from the start.

2- freeRadius accepts all duplicate Access-Requests from VPN, it executes the PHP 3 times for user1, 3 times for user2.

These problems not occurs when I start freeRadius as daemon (not with -X param);

It does not wait PHP's answer to continue to analyze new incoming Access-Requests. 

It rejects other 2 Access-Requests coming from VPN, so PHP is executed once for user1 and once for user2.

It takes one day from me to notice everything works fine in daemon mode.

Is this a normal behaviour in -X mode?

Thanks.

**Comment by mcnewton** [comment]
Running with -X is single threaded, so this is normal. You need to use -sfxx -l stdout instead. Artificial delays is never going help things.

Questions like this should go on the freeradius-users list. https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/.github/contributing.md#github-issue-tracker
