### ISSUE TITLE
'filename' does not work in 'log' config item of radiusd.conf

### ISSUE THREAD

**Issue by Britaliope** [FreeRADIUS/freeradius-server#2017]
The 2.x to 3.x upgrade guide explains that `file` is depreciated and  `filename` may be used instead. 

However on the `log`section of the `radiusd.conf` does not understand 'filename' config item; the service can start correctly but the log is putted in in `/usr/var/log/radius.log`. 

With file all is good.

**Comment by alandekok** [comment]
The `log` section of `radiusd.conf` says to use `file`.  So it works as documented.

**Comment by Britaliope** [comment]
Well ...
Tho the config upgrade guide for radiusd.conf should be upgraded : 
`Many names used by configuration items were inconsistent in earlier versions of the server. These names have been unified in version 3.0.

If a file is being referenced or created the config item filename is used.`

`The configuration items 'file' [...] is deprecated`
