### ISSUE TITLE
inclusion of mods-enabled/ with inter-dependent modules (sql & sqlcounter)

### ISSUE THREAD

**Issue by duskCoder** [FreeRADIUS/freeradius-server#2020]
# Issue type
- [x] Defect - Unexpected behaviour

# Defect/Feature description

Since FreeRADIUS server version 3, depending on external factors, enabling the two following modules: _sql_ and _sqlcounter_ can prevent the server from starting.

Because _sqlcounter_ uses variables that are supposed to be defined in _sql_, the _sql_ module should be loaded **before** _sqlcounter_.

The following directive does not permit to choose the order of inclusion of the files in the _mods-enabled/_ directory:

```text
$INCLUDE mods-enabled/
```

## How to reproduce issue
- Enable the _sql_ and _sqlcounter_ modules:

```text
$ cd mods-enabled
$ ln -s ../mods-available/sql
$ ln -s ../mods-available/sqlcounter
```
- Start the server. It will either fail with the following output:

```text
/etc/freeradius/3.0/mods-enabled/sqlcounter[43]: Reference "${modules.sql.dialect}" not found
/etc/freeradius/3.0/mods-enabled/sqlcounter[52]: Reference "${modconfdir}/sql/counter/${dialect}/${.:instance}.conf" points to a variable which has not been expanded.
Errors reading or parsing /etc/freeradius/3.0/radiusd.conf
```
(I'm using the version of freeradius packaged in debian 9. Thus, the prefix being _/etc/freeradius/3.0/_).

or if it does not fail, re-try multiple times with a different name for the symlink (the goal is to make the server load _sqlcounter_ before _sql_). 
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

```text
including files in directory /etc/freeradius/3.0/mods-enabled/
including configuration file /etc/freeradius/3.0/mods-enabled/detail.log
including configuration file /etc/freeradius/3.0/mods-enabled/echo
including configuration file /etc/freeradius/3.0/mods-enabled/soh
including configuration file /etc/freeradius/3.0/mods-enabled/files
including configuration file /etc/freeradius/3.0/mods-enabled/logintime
including configuration file /etc/freeradius/3.0/mods-enabled/radutmp
including configuration file /etc/freeradius/3.0/mods-enabled/cache_eap
including configuration file /etc/freeradius/3.0/mods-enabled/dynamic_clients
including configuration file /etc/freeradius/3.0/mods-enabled/always
including configuration file /etc/freeradius/3.0/mods-enabled/realm
including configuration file /etc/freeradius/3.0/mods-enabled/sqlcounter
/etc/freeradius/3.0/mods-enabled/sqlcounter[43]: Reference "${modules.sql.dialect}" not found
/etc/freeradius/3.0/mods-enabled/sqlcounter[52]: Reference "${modconfdir}/sql/counter/${dialect}/${.:instance}.conf" points to a variable which has not been expanded.
Errors reading or parsing /etc/freeradius/3.0/radiusd.conf
```
## Debugging with strace

Here is an excerpt of output from strace showing that the order of inclusions of the file is given by the _getdents_ system call.

```text
$ strace -e getdents freeradius -X
getdents(4, [{d_ino=5243436, d_off=810430172035437911, d_reclen=32, d_name="sql_deps",
d_type=DT_DIR}, {d_ino=5117894, d_off=1025256476367996288, d_reclen=32, d_name="detail.log",
d_type=DT_LNK}, {d_ino=5117898, d_off=1502737639351788492, d_reclen=24, d_name="echo",
d_type=DT_LNK}, {d_ino=5117913, d_off=1817466549698138278, d_reclen=24, d_name="soh",
d_type=DT_LNK}, {d_ino=5117902, d_off=1961935853697035245, d_reclen=32, d_name="files",
d_type=DT_LNK}, {d_ino=5117904, d_off=2244278311165158239, d_reclen=32, d_name="logintime",
d_type=DT_LNK}, {d_ino=5113693, d_off=2309305634981588990, d_reclen=40,
d_name=".include_sql_deps", d_type=DT_REG}, {d_ino=5117910, d_off=2401683915124329632,
d_reclen=32, d_name="radutmp", d_type=DT_LNK}, {d_ino=5117891, d_off=2443545490887481161,
d_reclen=32, d_name="cache_eap", d_type=DT_LNK}, {d_ino=5117896, d_off=2607116669983001093,
d_reclen=40, d_name="dynamic_clients", d_type=DT_LNK}, {d_ino=5117889,
d_off=2614555895217433522, d_reclen=32, d_name="always", d_type=DT_LNK}, {d_ino=5117911,
d_off=2630940827133685764, d_reclen=32, d_name="realm", d_type=DT_LNK}, {d_ino=5118902,
d_off=2779482212314771018, d_reclen=32, d_name="sqlcounter", d_type=DT_LNK}, {d_ino=5117907,
d_off=2913445672390605562, d_reclen=24, d_name="pap", d_type=DT_LNK}, {d_ino=5117899,
d_off=3245935088362369175, d_reclen=24, d_name="exec", d_type=DT_LNK}, {d_ino=5117916,
d_off=3334343313499289544, d_reclen=32, d_name="unpack", d_type=DT_LNK}, {d_ino=5117906,
d_off=3442177983645487090, d_reclen=32, d_name="ntlm_auth", d_type=DT_LNK}, {d_ino=5117909,
d_off=3596473013229815397, d_reclen=32, d_name="preprocess", d_type=DT_LNK}, {d_ino=5117905,
d_off=3672606785340944660, d_reclen=32, d_name="mschap", d_type=DT_LNK}, {d_ino=5117914,
d_off=3787683813675646432, d_reclen=32, d_name="sradutmp", d_type=DT_LNK}, {d_ino=5117895,
d_off=3839437027725360108, d_reclen=32, d_name="digest", d_type=DT_LNK}, {d_ino=5117917,
d_off=3982218072551873743, d_reclen=24, d_name="utf8", d_type=DT_LNK}, {d_ino=5117903,
d_off=4044624629018093151, d_reclen=32, d_name="linelog", d_type=DT_LNK}, {d_ino=5117900,
d_off=4428934728157494853, d_reclen=32, d_name="expiration", d_type=DT_LNK}, {d_ino=5117912,
d_off=5413763147859788320, d_reclen=32, d_name="replicate", d_type=DT_LNK}, {d_ino=5117901,
d_off=5540002208286560739, d_reclen=24, d_name="expr", d_type=DT_LNK}, {d_ino=4067005,
d_off=6287446710852958152, d_reclen=24, d_name="..", d_type=DT_DIR}, {d_ino=5117893,
d_off=6501153691499108921, d_reclen=32, d_name="detail", d_type=DT_LNK}, {d_ino=5117890,
d_off=7288092027200727583, d_reclen=32, d_name="attr_filter", d_type=DT_LNK}, {d_ino=5117676,
d_off=7971398812500517060, d_reclen=24, d_name=".", d_type=DT_DIR}, {d_ino=5117892,
d_off=8234362623052306805, d_reclen=24, d_name="chap", d_type=DT_LNK}, {d_ino=5118513,
d_off=8672036425251907862, d_reclen=24, d_name="sql", d_type=DT_LNK}, {d_ino=5117915,
d_off=9032435365683246004, d_reclen=24, d_name="unix", d_type=DT_LNK}, {d_ino=5117908,
d_off=9203212575883714472, d_reclen=32, d_name="passwd", d_type=DT_LNK}, {d_ino=5117897,
d_off=9223372036854775807, d_reclen=24, d_name="eap", d_type=DT_LNK}], 32768) = 1040
```
Thank you by advance for any help/guidance.

**Comment by alandekok** [comment]
Read `raddb/radiusd.conf`, and look for the `instantiate` section.  It is designed to (and documented as) address these issues.

**Comment by fistronico** [comment]
Hi, I have been bitten by this bug on Debian 9 using the sql and sqlcounter modules. As duskCoder points out freeradius does not start due to the order the modules are loaded. I have added to the instantiate section the modules sql and sqlcounter in order but it still does not start. ¿Can you explain a bit more what I have to do to bypass this bug? ¿It is a problem specific of the debian version of freeradius(is based in 3.0.12?
Looking for a solution I have found the following message:
http://lists.freeradius.org/pipermail/freeradius-users/2015-February/075889.html
It seems that even using the instantiate section the problem can not be resolved. Is the patch present in the source given in the email of the freeradius-users mailing list  present in the 3.0.12 version of freeradius?

**Comment by alanbuxey** [comment]
can you provide your debug/error log ?

alan

**Comment by alandekok** [comment]
@fistronico This issue has been closed.  Either open a new issue (with useful information), or ask a question on the freeradius-users mailing list.

**Comment by bsbudhwar** [comment]
simple solution is juts edit your sqlcounter file like below 

sqlcounter dailycounter {
	sql_module_instance = sql
#	dialect = ${modules.sql.dialect}

	counter_name = Daily-Session-Time
	check_name = Max-Daily-Session
	reply_name = Session-Timeout

	key = User-Name
	reset = daily

	$INCLUDE ${modconfdir}/sql/counter/mysql/${.:instance}.conf
}

sqlcounter monthlycounter {
	sql_module_instance = sql
# 	dialect = ${modules.sql.dialect}

	counter_name = Monthly-Session-Time
	check_name = Max-Monthly-Session
	reply_name = Session-Timeout
	key = User-Name
	reset = monthly

	$INCLUDE ${modconfdir}/sql/counter/mysql/${.:instance}.conf
}

sqlcounter noresetcounter {
	sql_module_instance = sql
#	dialect = ${modules.sql.dialect}

	counter_name = Max-All-Session-Time
	check_name = Max-All-Session
	key = User-Name
	reset = never

	$INCLUDE ${modconfdir}/sql/counter/mysql/${.:instance}.conf
}

#
#  Set an account to expire T seconds after first login.
#  Requires the Expire-After attribute to be set, in seconds.
#  You may need to edit raddb/dictionary to add the Expire-After
#  attribute.
sqlcounter expire_on_login {
	sql_module_instance = sql
#	dialect = ${modules.sql.dialect}

	counter_name = Expire-After-Initial-Login
	check_name = Expire-After
	key = User-Name
	reset = never

	$INCLUDE ${modconfdir}/sql/counter/mysql/${.:instance}.conf
}

**Comment by Alexsandr-Random** [comment]
Hello, I also ran into this problem, in your case you just need to enable the module in the main sql configuration file BEFORE all other modules. Because it is in this module that the variable you need is contained. 

`nano radiusd.conf`

and edit section "modules" like this:

`modules {
$INCLUDE ${confdir}/mods-enabled/sql
$INCLUDE ${confdir}/mods-enabled/
}`

Hope, this solution help someone.

**Comment by DenoGeek** [comment]
> 

This solution worked best for me too
