### ISSUE TITLE
100 Continue Error - Module: rlm_rest

### ISSUE THREAD

**Issue by attybro** [FreeRADIUS/freeradius-server#2027]
# Issue Type
- [x] Defect - Unexpected behaviour in managing 100 Continue mesage 
# Defect/Feature description
I am working with FreeRadius 3.0.12 and it is configured in order to manage AAA with the rest module. Using the radclient tool,  I send an accounting message (i.e. STOP msg), but I get an error. The packet sent to the API, because of its size, is "managed" with 100 continue and the the response is not properly parsed by FreeRadius. Using tcp flow I can see that the request from FreeRadius->API has this structure  
```text
POST /myAPI/accounting HTTP/1.1
Host: 192.168.56.1:8080
User-Agent: FreeRADIUS 3.0.12
Accept: */*
Content-Type: application/json
X-FreeRADIUS-Section: accounting
X-FreeRADIUS-Server: rest
Content-Length: 1267
Expect: 100-continue
```
Then my API server (Undertow) automatically manages the handshake in this way:
```text
HTTP/1.1 100 Continue
Content-Length: 0
```
At this point FreeRadius provides me this error:
```text
(0) rest: Processing response header
(0) rest:   Status : 100 (Continue)
(0) rest: Continuing...
(0) rest: Processing response header
(0) rest: ERROR: Malformed HTTP header: Missing HTTP version
(0) rest: ERROR: Received 19 bytes of response data: Content-Length: 0
(0) rest: ERROR: Request failed: 23 - Failed writing received data to disk/application
(0) rest: ERROR: Server returned no data
rlm_rest (rest): Released connection (0
```
Looking at the source code I see that Freeradius loops over all the headers and it doesn't take into account if in the first-one has a valid header ("HTTP/1.1 100 Continue"), but it continues to evaluate this filed for all the other values. As final result, for FreeRadius, the response has not a valid header.
```code
	if (ctx->code == 100) {
		RDEBUG2("Continuing...");
		ctx->state = WRITE_STATE_INIT;
	}
```
Maybe this part of code should be modified in order to allow more than one header. Commenting this part and recompiling it the issue looks like solved and so this part seems unuseful or "dangerous".

**Comment by arr2036** [comment]
Could you find the appropriate RFC/Section that describes what to do when 100-continue is received, then we can implement the correct behaviour.

**Comment by heruan** [comment]
I confirm this behaviour: as per RFC 2616 §-[8.2.3](https://tools.ietf.org/html/rfc2616#section-8.2.3) a response with status code 100 isn't different from other responses and nothing in the RFC states the absence of additional headers; in fact, a `Date` or `X-Powered-By` headers could be present and should not interfere.

I don't understand the purpose of this conditional at [src/modules/rlm_rest/rest.c#L1706](https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/modules/rlm_rest/rest.c#L1706):

```c
if (ctx->code == 100) {
    RDEBUG2("Continuing...");
    ctx->state = WRITE_STATE_INIT;
}
```
since `libcurl` should handle status code 100 automatically, i.e. providing the request body.

For what I can understand this conditional just assume there are no headers in the response and resets the context state, but doing so the presence of any header will throw an error.

**Comment by arr2036** [comment]
@heruan @attybro as I understand it, RFC2616 describes this flow:

- Client: Sends request, includes Expect: 100-Continue header.  This request is absent body data.
- Server: Responds with 100 Status code, or 417 status code.
- Client: Sends body data.
- Server: Responds with real status code 200, 404 etc...

Do you agree with this interpretation? If not I can start citing sections/paragraphs...

**Comment by heruan** [comment]
I agree, that is the flow.

**Comment by arr2036** [comment]
Note: In ``rest_response_header`` (at least in v4.0.x), we return the value of t, which is ``size_t const t = (size * nmemb);``

That should indicate to curl that we processed the complete header, and that it should proceed on to sending the body data:

```c
	/*
	 *  If we got a 100 Continue, we need to send additional payload data.
	 *  reset the state to WRITE_STATE_INIT, so that when were called again
	 *  we overwrite previous header data with that from the proper header.
	 */
	if (ctx->code == 100) {
		RDEBUG2("Continuing...");
		ctx->state = WRITE_STATE_INIT;
	}

	return t;
```

**Comment by heruan** [comment]
It's simple: if the endpoint responds with

```
HTTP/1.1 100 Continue
Date: Mon, 24 Jul 2017 08:12:31 GMT
```

the module fails to process the response, as after parsing the status line the context is set to `WRITE_STATE_INIT` and when parsing the header if fails with `ERROR: Malformed HTTP header: Missing HTTP version`.

**Comment by arr2036** [comment]
@heruan OK, got it.  Moved where we change the parser state.  That should fix the issue.  Can @attybro or @heruan test and confirm?  You should still hopefully see the "Continuing..." debug output.

**Comment by attybro** [comment]
@arr2036 I have just tested it and I confirm that this fix works properly

**Comment by arr2036** [comment]
@attybro thanks for confirming.
