### ISSUE TITLE
Radcrypt Missing?

### ISSUE THREAD

**Issue by lepianoman** [FreeRADIUS/freeradius-server#2037]
I don't see radcrypt in the latest versions of Freeradius--downloaded tarballs off the internet and looked and I didn't see it.

freeradius -v
freeradius: FreeRADIUS Version 2.2.8

whereis radcrypt
radcrypt: /usr/share/man/man8/radcrypt.8.gz

I see a man-page but no binary. Thanks! I'm using Ubuntu's repo version (with freeradius-common and freeradius-utils) but I don't see this binary in any of the tarballs.

Is there a better way to do radcrypt now? Thanks!

**Comment by alandekok** [comment]
radcrypt is installed in the default release of v2.  It's installed by scripts/Makefile.

This seems to be an Ubuntu / debian problem.

**Comment by lepianoman** [comment]
You're right, I thought it wasn't working but it is working in v3 I installed from the website--sorry about the false alarm and thanks.
