### ISSUE TITLE
Problem with run time variable in freeradius 3.0.15

### ISSUE THREAD

**Issue by vladancolakovic** [FreeRADIUS/freeradius-server#2038]
I have problem with run time variable in freeradius 3.0.15.
I used user defined variable Daily-Total-Limit in:

update reply {
Reply-Message := "User reached maximum bandwidth limit of %{check:Daily-Total-Limit} bytes".
}

In freeradius release 3.0.15 i get error on key word **check**.

What about this?

**Comment by alandekok** [comment]
$ man unlang

It hasn't been `check` for many years.

**Comment by arr2036** [comment]
Should be control
