### ISSUE TITLE
Freeradius's authentication still successed when OpenLDAP uid's password was locked with pwdplicy

### ISSUE THREAD

**Issue by wuyish** [FreeRADIUS/freeradius-server#2042]
OpenLDAP uid's  password was locked with pwdplicy attribute pwdAccountLockedTime , and used openldap-client to bind uid would get message :ldap_bind: Invalid credentials (49) account was locked.

But authentication with freeradius still successed.
I didn't why? And how to solve?

Environment：
CentOS Linux release 7.3.1611 (Core)
Linux raidus.3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
##
freeradius-ldap-3.0.4-8.el7_3.x86_64
freeradius-3.0.4-8.el7_3.x86_64
freeradius-utils-3.0.4-8.el7_3.x86_64

##
openldap-2.4.40-13.el7.x86_64
openldap-servers-2.4.40-13.el7.x86_64
openldap-clients-2.4.40-13.el7.x86_64

**Comment by arr2036** [comment]
Please ask questions on the FreeRADIUS users list.  The GitHub issue tracker is not for support (and this is expected behaviour, not a bug).

http://lists.freeradius.org/mailman/listinfo/freeradius-users
