### ISSUE TITLE
3.0.x (and 4.0.x) - overflow of allocated memory in rlm_rest module - server aborts

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#2051]
# Issue type
- [ ] Defect - Crash or memory corruption.

# Defect description

The code of function rest_response_body (rest.c) is wrong.
See:
https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/modules/rlm_rest/rest.c#L1783

There is an overflow of allocated memory.
Here "t" is the size of the current chunk of data, received through libcurl (not including a terminal '\0').
"ctx->alloc" is the memory allocated.
"ctx->used" should be the memory used, but it is wrong because it does not account for the terminal '\0'.

So the first time rest_response_body function is called, enough memory is allocated, but the "used" counter is wrong.
At a subsequent call to rest_response_body, the following can happen:
t = ctx->alloc - ctx->used
So FreeRADIUS thinks there is enough memory allocated to append the new data.
But there isn't actually. It will overflow (on the next malloc chunk) by one octet to write the terminal '\0'.
Consequently when, later, we try to free this next chunk, all hell breaks loose in the malloc API (Memory corruption detected, the server aborts. But it takes some time to happen, depends on what is received through libcurl, and likely there must be multiple threads involved. But still, it happens quite often - at least once a week in our setup).

In addition, in each subsequent call to rest_response_body, (t + 1) new octets are allocated. But we really only need t (there's only one terminal '\0', since it's only one string). So "alloc - used" is drifting by 1 at each call.

 
## A proposed fix

The following code fixes the issue for 3.0.x (original code included commented out for reference).
Note: in 4.0.x talloc is used instead of malloc, but the issue is the same (although it may manifest differently).

```text
	default:
/*
		if (t > (ctx->alloc - ctx->used)) {
			ctx->alloc += ((t + 1) > REST_BODY_INIT) ? t + 1 : REST_BODY_INIT;

			tmp = ctx->buffer;

			ctx->buffer = rad_malloc(ctx->alloc);

			// If data has been written previously
			if (tmp) {
				strlcpy(ctx->buffer, tmp, (ctx->used + 1));
				free(tmp);
			}
		}
		strlcpy(ctx->buffer + ctx->used, p, t + 1);
		ctx->used += t;

		break;
	}
*/

		bool first_alloc = (ctx->buffer == NULL); // For sake of clarity.
		RDEBUG2("rest_response_body: first_alloc=%s, t=%zu, alloc=%zu, used=%zu", first_alloc?"yes":"no", t, ctx->alloc, ctx->used);

		if (   (first_alloc)
		    || (t > ctx->alloc - ctx->used)
		   ) {
			ctx->alloc += t;
			if (first_alloc) ctx->alloc += 1; // count the terminal '\0' only on first allocation.

			// Note: we don't really care about preallocating REST_BODY_INIT octets. So we just won't do it.
			// Let FreeRADIUS team do this differently if they wish :)

			tmp = ctx->buffer;

			ctx->buffer = rad_malloc(ctx->alloc);

			// If data has been written previously
			if (tmp) {
				strlcpy(ctx->buffer, tmp, ctx->used); // this will always be '\0' terminated.
				free(tmp);
			}
		}
		if (first_alloc) {
			strlcpy(ctx->buffer, p, t + 1);
			ctx->used += (t + 1);
		} else {
			strlcpy(ctx->buffer + ctx->used - 1, p, t + 1); // start writing on the previous terminal '\0'.
			ctx->used += t;
		}

		RDEBUG2("rest_response_body: after update: alloc=%zu, used=%zu", ctx->alloc, ctx->used);
		break;
	}
```

**Comment by alandekok** [comment]
I think the simplest solution is to just change the comparison to match the allocation:

		if ((t + 1) > (ctx->alloc - ctx->used) {
			ctx->alloc += ((t + 1) > REST_BODY_INIT) ? t + 1 : REST_BODY_INIT;

We then keep `ctx->used` as the amount of data in the buffer, and always do comparisons / allocs with `+1` to account for the trailing zero.

**Comment by alandekok** [comment]
Please confirm that this fixes the issue.

**Comment by nchaigne** [comment]
That should fix the main issue, however you're still allocating one more octet (t + 1) than necessary at each call (beyond the first one), with this:

ctx->alloc += ((t + 1) > REST_BODY_INIT) ? t + 1 : REST_BODY_INIT;

So the "alloc - used" is drifting.
While not technically an issue, I find it confusing.

**Comment by alandekok** [comment]
I think a clearer solution is this:

            size_t needed;
            ... 
		needed = ctx->used + t + 1;
		if (needed > ctx->alloc) {
			if (needed < REST_BODY_INIT) needed = REST_BODY_INIT;
			ctx->alloc = needed;

**Comment by nchaigne** [comment]
That's much easier to read, I'm not a fan of overusing the ternary if. :)

That said, I don't know the purpose of "REST_BODY_INIT" here... if this is to reduce the number of allocations, this won't do, 1024 is way too small (MTU is 1500 octets).

**Comment by alandekok** [comment]
`REST_BODY_INIT` is a libcurl requirement for minimum allocation.

**Comment by alandekok** [comment]
I think this is fixed, so I'll close it.

**Comment by nchaigne** [comment]
No problem on Production since a month, so yes it is fixed. Thanks!
This "small" overflow was causing both of our issues: the server abort, and all the threads freezing. I'm not sure to understand exactly how for the second case, but... I'm glad it's gone :)
