### ISSUE TITLE
./configure --without-rlm_eap_fast has no effect in 3.x

### ISSUE THREAD

**Issue by kakash1hatake** [FreeRADIUS/freeradius-server#2052]
Hello.
Trying to build 3.0.16 version from repositry gives an error:

./configure \
                --prefix=/usr/local \
                --exec-prefix=/usr/local \
                --mandir=$mandir \
                --sysconfdir=/etc \
                --libdir=$libdir \
                --datadir=/usr/local/share \
                --localstatedir=/var \
                --with-raddbdir=${raddbdir} \
                --with-logdir=/var/log/${package} \
                --enable-ltdl-install=no --enable-strict-dependencies \
                --with-large-files --with-udpfromto --with-edir \
                --enable-developer \
                --config-cache \
                --without-rlm_eap_tnc --without-rlm_sql_mysql --without-rlm_cache_memcached --without-rlm_couchbase --without-rlm_eap_fast --without-rlm_idn --without-rlm_opendirectory --without-rlm_redis --without-rlm_rediswho \
                --without-rlm_sql_postgresql --without-rlm_counter --without-rlm_dbm --without-rlm_ippool --without-rlm_krb5 --without-rlm_pam --without-rlm_python --without-rlm_sql_iodbc --without-rlm_rest --without-rlm_ruby \
                --with-oracle-lib-dir=/opt/oracle/product/10.2.0_aclient/lib \
                --with-oracle_include_dir=/opt/oracle/product/10.2.0_aclient/rdbms/public \
                --without-rlm_eap_ikev2 --without-rlm_securid --without-rlm_sql_unixodbc --without-rlm_ldap --without-rlm_sql_db2 --without-rlm_sql_firebird --without-rlm_sql_freetds --without-rlm_sql_sqlite --without-rlm_unbound \
                --with-system-libtool \
                --with-system-libltdl

make

...
CC src/modules/rlm_eap/libeap/eapcommon.c
CC src/modules/rlm_eap/libeap/eapcrypto.c
CC src/modules/rlm_eap/libeap/eap_chbind.c
CC src/modules/rlm_eap/libeap/eapsimlib.c
CC src/modules/rlm_eap/libeap/fips186prf.c
CC src/modules/rlm_eap/libeap/comp128.c
CC src/modules/rlm_eap/libeap/eap_tls.c
CC src/modules/rlm_eap/libeap/mppe_keys.c
LINK build/lib/libfreeradius-eap.la
CC src/modules/rlm_eap/rlm_eap.c
CC src/modules/rlm_eap/eap.c
CC src/modules/rlm_eap/mem.c
LINK build/lib/rlm_eap.la
CC src/modules/rlm_eap/types/rlm_eap_fast/eap_fast.c
In file included from src/modules/rlm_eap/types/rlm_eap_fast/eap_fast.c:26:
src/modules/rlm_eap/types/rlm_eap_fast/eap_fast.h:134: error: ‘EVP_GCM_TLS_TAG_LEN’ undeclared here (not in a function)
src/modules/rlm_eap/types/rlm_eap_fast/eap_fast.c: In function ‘openssl_get_keyblock_size’:
src/modules/rlm_eap/types/rlm_eap_fast/eap_fast.c:55: warning: passing argument 1 of ‘EVP_MD_CTX_md’ from incompatible pointer type
/usr/include/openssl/evp.h:484: note: expected ‘const struct EVP_MD_CTX *’ but argument is of type ‘const struct EVP_MD *’
src/modules/rlm_eap/types/rlm_eap_fast/eap_fast.c:59: error: ‘struct <anonymous>’ has no member named ‘new_mac_secret_size’
make: *** [build/objs/src/modules/rlm_eap/types/rlm_eap_fast/eap_fast.lo] Error 1

But if I delete **all.mk** after running configure from src/modules/rlm_eap/types/rlm_eap_fast that I don't want to build the process succeeds.

I'm trying to build 3.x version with openSSL 0.9.8o

**Comment by alandekok** [comment]
> I'm trying to build 3.x version with openSSL 0.9.8o

That is severely unsupported.  That version of OpenSSL is old, broken, and insecure.

**Comment by kakash1hatake** [comment]
But the problem is that configure doesn't respect the flag. And not the OpenSSL version.

**Comment by alandekok** [comment]
The problem is that OpenSSL 0.9.8 is unsupported and insecure.  If you use it, you're on your own.

**Comment by kakash1hatake** [comment]
Yes, I know that version is too old and vulnerable.
But we don't really need to do SSL in freeradius.
And the environment where the daemon runs is Debian 5 (that is also too old).
So new versions of SSL are not provided officially via deb package and we need to build it oureselves.

**Comment by arr2036** [comment]
Use the configure flags to disable OpenSSL entirely.  I think it's ``--without-openssl`` (check the output of ``./configure --help``).

**Comment by felna** [comment]
I would like to reopen this issue, and remind the @alandekok to read the question again. The ./configure command does not work as --help suggests. We have tried two mehods:

1.
./configure --with-rlm_yubikey=no --with-rlm_unix=no --with-rlm_sql_map=no --with-rlm_sqlcounter=no --with-rlm_sqlippool=no --with-rlm_sqlcounter=no --with-rlm_rediswho=no --with-rlm_redis=no --with-rlm_sql=no --with-rlm_realm=no --with-rlm_radutmp=no --with-rlm_python=no  --with-rlm_perl=no --with-rlm_pam=no --with-rlm_mschap=no --with-rlm_ldap=no --with-rlm_krb5=no --with-rlm_ippool=no --with-rlm_eap=no --with-rlm_counter=no --with-rlm_cache=no --with-rlm_cache_memcached=no  --with-openssl-lib-dir=/opt/apache/lib/ssl/lib/ --with-openssl-include-dir=/opt/apache/lib/ssl/include/ --prefix=/home/freja/radius_test --enable-strict-dependencies

2.
./configure --without-rlm_yubikey --without-rlm_unix --without-rlm_sql_map --without-rlm_sqlcounter --without-rlm_sqlippool --without-rlm_sqlcounter --without-rlm_rediswho --without-rlm_redis --without-rlm_sql --without-rlm_realm --without-rlm_radutmp --without-rlm_python  --without-rlm_perl --without-rlm_pam --without-rlm_mschap --without-rlm_ldap --without-rlm_krb5 --without-rlm_ippool --without-rlm_eap --without-rlm_counter --without-rlm_cache --without-rlm_cache_memcached  --with-openssl-lib-dir=/opt/apache/lib/ssl/lib/ --with-openssl-include-dir=/opt/apache/lib/ssl/include/ --prefix=/home/freja/radius_test --enable-strict-dependencies

Both ways, all of the modues we explicitly want to avoid get compiled and installed. We even tried manualy removing modules from Makefile after ./configure, they still get installed.

**Comment by alandekok** [comment]
@felna You can do `rm -rf src/modules/rlm_eap/types/rlm_eap_fast` if you want, as a work-around.

**Comment by predators46** [comment]
hy @alandekok I managed to make freeradius2 using openssl-1.1.1

` Tue Jun 15 07:02:02 2021 : Info: radiusd: FreeRADIUS Version 2.2.9, for host mipsel-openwrt-linux-gnu, built on Sep  6 2020 at 16:19:39
Tue Jun 15 07:02:02 2021 : Debug: Server was built with: 
Tue Jun 15 07:02:02 2021 : Debug:   accounting
Tue Jun 15 07:02:02 2021 : Debug:   authentication
Tue Jun 15 07:02:02 2021 : Debug:  WITH_DHCP
Tue Jun 15 07:02:02 2021 : Debug:  WITH_VMPS
Tue Jun 15 07:02:02 2021 : Debug: Server core libs:
Tue Jun 15 07:02:02 2021 : Debug:   ssl: OpenSSL 1.1.1k  25 Mar 2021
Tue Jun 15 07:02:02 2021 : Info: Copyright (C) 1999-2015 The FreeRADIUS server project and contributors.
Tue Jun 15 07:02:02 2021 : Info: There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
Tue Jun 15 07:02:02 2021 : Info: PARTICULAR PURPOSE.
Tue Jun 15 07:02:02 2021 : Info: You may redistribute copies of FreeRADIUS under the terms of the
Tue Jun 15 07:02:02 2021 : Info: GNU General Public License.
Tue Jun 15 07:02:02 2021 : Info: For more information about these matters, see the file named COPYRIGHT.
Tue Jun 15 07:02:02 2021 : Info: Starting - reading configuration files ...
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/radiusd.conf
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/clients.conf
Tue Jun 15 07:02:02 2021 : Debug: including files in directory /etc/freeradius2/modules/
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/logintime
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/always
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/echo
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/attr_rewrite
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/detail
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/chap
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/ldap
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/expiration
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/files
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/radutmp
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/sradutmp
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/exec
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/realm
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/expr
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/preprocess
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/passwd
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/inner-eap
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/mschap
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/attr_filter
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/modules/pap
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/eap.conf
Tue Jun 15 07:02:02 2021 : Debug: including files in directory /etc/freeradius2/sites/
Tue Jun 15 07:02:02 2021 : Debug: including configuration file /etc/freeradius2/sites/default
Tue Jun 15 07:02:02 2021 : Debug: main {
Tue Jun 15 07:02:02 2021 : Debug: allow_core_dumps = no
Tue Jun 15 07:02:02 2021 : Debug: }
Tue Jun 15 07:02:02 2021 : Debug: including dictionary file /etc/freeradius2/dictionary
Tue Jun 15 07:02:03 2021 : Debug: main {
Tue Jun 15 07:02:03 2021 : Debug: name = "radiusd"
Tue Jun 15 07:02:03 2021 : Debug: prefix = "/usr"
Tue Jun 15 07:02:03 2021 : Debug: localstatedir = "/var"
Tue Jun 15 07:02:03 2021 : Debug: sbindir = "/usr/sbin"
Tue Jun 15 07:02:03 2021 : Debug: logdir = "/var/log"
Tue Jun 15 07:02:03 2021 : Debug: run_dir = "/var/run"
Tue Jun 15 07:02:03 2021 : Debug: libdir = "/usr/lib/freeradius2"
Tue Jun 15 07:02:03 2021 : Debug: radacctdir = "/var/db/radacct"
Tue Jun 15 07:02:03 2021 : Debug: hostname_lookups = no
Tue Jun 15 07:02:03 2021 : Debug: max_request_time = 30
Tue Jun 15 07:02:03 2021 : Debug: cleanup_delay = 5
Tue Jun 15 07:02:03 2021 : Debug: max_requests = 1024
Tue Jun 15 07:02:03 2021 : Debug: pidfile = "/var/run/radiusd.pid"
Tue Jun 15 07:02:03 2021 : Debug: checkrad = "/usr/sbin/checkrad"
Tue Jun 15 07:02:03 2021 : Debug: debug_level = 0
Tue Jun 15 07:02:03 2021 : Debug: proxy_requests = no
Tue Jun 15 07:02:03 2021 : Debug:  log {
Tue Jun 15 07:02:03 2021 : Debug:  stripped_names = no
Tue Jun 15 07:02:03 2021 : Debug:  auth = no
Tue Jun 15 07:02:03 2021 : Debug:  auth_badpass = no
Tue Jun 15 07:02:03 2021 : Debug:  auth_goodpass = no
Tue Jun 15 07:02:03 2021 : Debug:  }
Tue Jun 15 07:02:03 2021 : Debug:  security {
Tue Jun 15 07:02:03 2021 : Debug:  max_attributes = 200
Tue Jun 15 07:02:03 2021 : Debug:  reject_delay = 1
Tue Jun 15 07:02:03 2021 : Debug:  status_server = yes
Tue Jun 15 07:02:03 2021 : Debug:  }
Tue Jun 15 07:02:03 2021 : Debug: }
Tue Jun 15 07:02:03 2021 : Debug: radiusd: #### Loading Realms and Home Servers ####
Tue Jun 15 07:02:03 2021 : Debug: radiusd: #### Loading Clients ####
Tue Jun 15 07:02:03 2021 : Debug:  client localhost {
Tue Jun 15 07:02:03 2021 : Debug:  ipaddr = 192.168.1.1
Tue Jun 15 07:02:03 2021 : Debug:  require_message_authenticator = noTue Jun 15 07:02:03 2021 : Debug:  secret = "Edca3cdk45"
Tue Jun 15 07:02:03 2021 : Debug:  nastype = "other"
Tue Jun 15 07:02:03 2021 : Debug:  }
Tue Jun 15 07:02:03 2021 : Debug: radiusd: #### Instantiating modules ####Tue Jun 15 07:02:03 2021 : Debug:  instantiate {
Tue Jun 15 07:02:03 2021 : Debug:  }
Tue Jun 15 07:02:03 2021 : Debug: radiusd: #### Loading Virtual Servers ####
Tue Jun 15 07:02:03 2021 : Debug: server { # from file /etc/freeradius2/radiusd.conf
Tue Jun 15 07:02:03 2021 : Debug:  modules {
Tue Jun 15 07:02:03 2021 : Debug:  Module: Checking authenticate {...} for more modules to load
Tue Jun 15 07:02:03 2021 : Debug:     (Loaded rlm_pap, checking if it's valid)
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to module rlm_pap
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating module "pap" from file /etc/freeradius2/modules/pap
Tue Jun 15 07:02:03 2021 : Debug:   pap {
Tue Jun 15 07:02:03 2021 : Debug:   encryption_scheme = "auto"
Tue Jun 15 07:02:03 2021 : Debug:   auto_header = yes
Tue Jun 15 07:02:03 2021 : Debug:   }
Tue Jun 15 07:02:03 2021 : Debug:     (Loaded rlm_chap, checking if it's valid)
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to module rlm_chap
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating module "chap" from file /etc/freeradius2/modules/chap
Tue Jun 15 07:02:03 2021 : Debug:     (Loaded rlm_mschap, checking if it's valid)
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to module rlm_mschap
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating module "mschap" from file /etc/freeradius2/modules/mschap
Tue Jun 15 07:02:03 2021 : Debug:   mschap {
Tue Jun 15 07:02:03 2021 : Debug:   use_mppe = yes
Tue Jun 15 07:02:03 2021 : Debug:   require_encryption = no
Tue Jun 15 07:02:03 2021 : Debug:   require_strong = no
Tue Jun 15 07:02:03 2021 : Debug:   with_ntdomain_hack = no
Tue Jun 15 07:02:03 2021 : Debug:   allow_retry = yes
Tue Jun 15 07:02:03 2021 : Debug:   }
Tue Jun 15 07:02:03 2021 : Debug:     (Loaded rlm_eap, checking if it's valid)
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to module rlm_eap
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating module "eap" from file /etc/freeradius2/eap.conf
Tue Jun 15 07:02:03 2021 : Debug:   eap {
Tue Jun 15 07:02:03 2021 : Debug:   default_eap_type = "peap"
Tue Jun 15 07:02:03 2021 : Debug:   timer_expire = 60
Tue Jun 15 07:02:03 2021 : Debug:   ignore_unknown_eap_types = no
Tue Jun 15 07:02:03 2021 : Debug:   cisco_accounting_username_bug = noTue Jun 15 07:02:03 2021 : Debug:   max_sessions = 1024
Tue Jun 15 07:02:03 2021 : Debug:   }
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to sub-module rlm_eap_tls
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating eap-tls
Tue Jun 15 07:02:03 2021 : Debug:    tls {
Tue Jun 15 07:02:03 2021 : Debug:    rsa_key_exchange = no
Tue Jun 15 07:02:03 2021 : Debug:    dh_key_exchange = yes
Tue Jun 15 07:02:03 2021 : Debug:    rsa_key_length = 512
Tue Jun 15 07:02:03 2021 : Debug:    dh_key_length = 512
Tue Jun 15 07:02:03 2021 : Debug:    verify_depth = 0
Tue Jun 15 07:02:03 2021 : Debug:    CA_path = "/etc/freeradius2/certs"Tue Jun 15 07:02:03 2021 : Debug:    pem_file_type = yes
Tue Jun 15 07:02:03 2021 : Debug:    private_key_file = "/etc/freeradius2/certs/server.pem"
Tue Jun 15 07:02:03 2021 : Debug:    certificate_file = "/etc/freeradius2/certs/server.pem"
Tue Jun 15 07:02:03 2021 : Debug:    CA_file = "/etc/freeradius2/certs/ca.pem"
Tue Jun 15 07:02:03 2021 : Debug:    private_key_password = "whatever"
Tue Jun 15 07:02:03 2021 : Debug:    dh_file = "/etc/freeradius2/certs/dh"
Tue Jun 15 07:02:03 2021 : Debug:    fragment_size = 1024
Tue Jun 15 07:02:03 2021 : Debug:    include_length = yes
Tue Jun 15 07:02:03 2021 : Debug:    check_crl = no
Tue Jun 15 07:02:03 2021 : Debug:    check_all_crl = no
Tue Jun 15 07:02:03 2021 : Debug:    cipher_list = "DEFAULT"
Tue Jun 15 07:02:03 2021 : Debug:    ecdh_curve = "prime256v1"
Tue Jun 15 07:02:03 2021 : Debug:     verify {
Tue Jun 15 07:02:03 2021 : Debug:     }
Tue Jun 15 07:02:03 2021 : Debug:     ocsp {
Tue Jun 15 07:02:03 2021 : Debug:     enable = no
Tue Jun 15 07:02:03 2021 : Debug:     override_cert_url = yes
Tue Jun 15 07:02:03 2021 : Debug:     url = "http://127.0.0.1/ocsp/"
Tue Jun 15 07:02:03 2021 : Debug:     use_nonce = yes
Tue Jun 15 07:02:03 2021 : Debug:     timeout = 0
Tue Jun 15 07:02:03 2021 : Debug:     softfail = no
Tue Jun 15 07:02:03 2021 : Debug:     }
Tue Jun 15 07:02:03 2021 : Debug:    }
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to sub-module rlm_eap_peap
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating eap-peap
Tue Jun 15 07:02:03 2021 : Debug:    peap {
Tue Jun 15 07:02:03 2021 : Debug:    default_eap_type = "mschapv2"
Tue Jun 15 07:02:03 2021 : Debug:    copy_request_to_tunnel = yes
Tue Jun 15 07:02:03 2021 : Debug:    use_tunneled_reply = yes
Tue Jun 15 07:02:03 2021 : Debug:    proxy_tunneled_request_as_eap = noTue Jun 15 07:02:03 2021 : Debug:    soh = no
Tue Jun 15 07:02:03 2021 : Debug:    }
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to sub-module rlm_eap_mschapv2
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating eap-mschapv2
Tue Jun 15 07:02:03 2021 : Debug:    mschapv2 {
Tue Jun 15 07:02:03 2021 : Debug:    with_ntdomain_hack = no
Tue Jun 15 07:02:03 2021 : Debug:    send_error = no
Tue Jun 15 07:02:03 2021 : Debug:    }
Tue Jun 15 07:02:03 2021 : Debug:  Module: Checking authorize {...} for more modules to load
Tue Jun 15 07:02:03 2021 : Debug:     (Loaded rlm_files, checking if it's valid)
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to module rlm_files
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating module "files" from file /etc/freeradius2/modules/files
Tue Jun 15 07:02:03 2021 : Debug:   files {
Tue Jun 15 07:02:03 2021 : Debug:   usersfile = "/etc/freeradius2/users"
Tue Jun 15 07:02:03 2021 : Debug:   acctusersfile = "/etc/freeradius2/acct_users"
Tue Jun 15 07:02:03 2021 : Debug:   preproxy_usersfile = "/etc/freeradius2/preproxy_users"
Tue Jun 15 07:02:03 2021 : Debug:   compat = "no"
Tue Jun 15 07:02:03 2021 : Debug:   }
Tue Jun 15 07:02:03 2021 : Debug: reading pairlist file /etc/freeradius2/users
Tue Jun 15 07:02:03 2021 : Debug: reading pairlist file /etc/freeradius2/acct_users
Tue Jun 15 07:02:03 2021 : Debug: reading pairlist file /etc/freeradius2/preproxy_users
Tue Jun 15 07:02:03 2021 : Debug:  Module: Checking accounting {...} for more modules to load
Tue Jun 15 07:02:03 2021 : Debug:     (Loaded rlm_exec, checking if it's valid)
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to module rlm_exec
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating module "exec" from file /etc/freeradius2/modules/exec
Tue Jun 15 07:02:03 2021 : Debug:   exec {
Tue Jun 15 07:02:03 2021 : Debug:   wait = no
Tue Jun 15 07:02:03 2021 : Debug:   input_pairs = "request"
Tue Jun 15 07:02:03 2021 : Debug:   shell_escape = yes
Tue Jun 15 07:02:03 2021 : Debug:   timeout = 10
Tue Jun 15 07:02:03 2021 : Debug:   }
Tue Jun 15 07:02:03 2021 : Debug:  Module: Checking session {...} for more modules to load
Tue Jun 15 07:02:03 2021 : Debug:     (Loaded rlm_radutmp, checking if it's valid)
Tue Jun 15 07:02:03 2021 : Debug:  Module: Linked to module rlm_radutmp
Tue Jun 15 07:02:03 2021 : Debug:  Module: Instantiating module "radutmp" from file /etc/freeradius2/modules/radutmp
Tue Jun 15 07:02:03 2021 : Debug:   radutmp {
Tue Jun 15 07:02:03 2021 : Debug:   filename = "/var/db/radacct/radutmp"
Tue Jun 15 07:02:03 2021 : Debug:   username = "%{User-Name}"
Tue Jun 15 07:02:03 2021 : Debug:   case_sensitive = yes
Tue Jun 15 07:02:03 2021 : Debug:   check_with_nas = yes
Tue Jun 15 07:02:03 2021 : Debug:   perm = 384
Tue Jun 15 07:02:03 2021 : Debug:   callerid = yes
Tue Jun 15 07:02:03 2021 : Debug:   }
Tue Jun 15 07:02:03 2021 : Debug:  } # modules
Tue Jun 15 07:02:03 2021 : Debug: } # server
Tue Jun 15 07:02:03 2021 : Debug: radiusd: #### Opening IP addresses and Ports ####
Tue Jun 15 07:02:03 2021 : Debug: listen {
Tue Jun 15 07:02:03 2021 : Debug:  type = "auth"
Tue Jun 15 07:02:03 2021 : Debug:  ipaddr = *
Tue Jun 15 07:02:03 2021 : Debug:  port = 0
Tue Jun 15 07:02:03 2021 : Debug: }
Tue Jun 15 07:02:03 2021 : Debug: listen {
Tue Jun 15 07:02:03 2021 : Debug:  type = "acct"
Tue Jun 15 07:02:03 2021 : Debug:  ipaddr = *
Tue Jun 15 07:02:03 2021 : Debug:  port = 0
Tue Jun 15 07:02:03 2021 : Debug: }
Tue Jun 15 07:02:03 2021 : Debug: Listening on authentication address * port 1812
Tue Jun 15 07:02:03 2021 : Debug: Listening on accounting address * port 1813
Tue Jun 15 07:02:03 2021 : Info: Ready to process requests.
rad_recv: Access-Request packet from host 192.168.1.1 port 36566, id=181, length=48
User-Name = "malgosia"
User-Password = "alamakota123"
Tue Jun 15 07:04:01 2021 : Info: # Executing section authorize from file /etc/freeradius2/sites/default
Tue Jun 15 07:04:01 2021 : Info: +group authorize {
Tue Jun 15 07:04:01 2021 : Info: [eap] No EAP-Message, not doing EAP
Tue Jun 15 07:04:01 2021 : Info: ++[eap] = noop
Tue Jun 15 07:04:01 2021 : Info: [files] users: Matched entry malgosia at line 204
Tue Jun 15 07:04:01 2021 : Info: ++[files] = ok
Tue Jun 15 07:04:01 2021 : Info: ++[pap] = updated
Tue Jun 15 07:04:01 2021 : Info: +} # group authorize = updated
Tue Jun 15 07:04:01 2021 : Info: Found Auth-Type = PAP
Tue Jun 15 07:04:01 2021 : Info: # Executing group from file /etc/freeradius2/sites/default
Tue Jun 15 07:04:01 2021 : Info: +group PAP {
Tue Jun 15 07:04:01 2021 : Info: [pap] login attempt with password "alamakota123"
Tue Jun 15 07:04:01 2021 : Info: [pap] Using clear text password "alamakota123"
Tue Jun 15 07:04:01 2021 : Info: [pap] User authenticated successfully
Tue Jun 15 07:04:01 2021 : Info: ++[pap] = ok
Tue Jun 15 07:04:01 2021 : Info: +} # group PAP = ok
Tue Jun 15 07:04:01 2021 : Info:   WARNING: Empty post-auth section.  Using default return values.
Sending Access-Accept of id 181 to 192.168.1.1 port 36566
Tue Jun 15 07:04:01 2021 : Info: Finished request 0.
Tue Jun 15 07:04:01 2021 : Debug: Going to the next request
Tue Jun 15 07:04:01 2021 : Debug: Waking up in 4.9 seconds.
Tue Jun 15 07:04:06 2021 : Info: Cleaning up request 0 ID 181 with timestamp +118
Tue Jun 15 07:04:06 2021 : Info: Ready to process requests. `

**Comment by alandekok** [comment]
@predators46 Please follow the issue guidelines.

* don't hijack someone else's issue with unrelated text
* don't ping me by name.  I already read the issues
* ask questions on the freeradius-users mailing list.  Github is for bugs, not for configuration questions
* version 2 is end of life.  There's no reason to use it.  Upgrade to v3.
* it should be pretty obvious that your "cut and paste" of debug output is entirely useless.  If you don't care enough for format it correctly, we don't care enough to read it.

**Comment by predators46** [comment]
> @predators46 Please follow the issue guidelines.
> 
> * don't hijack someone else's issue with unrelated text
> * don't ping me by name.  I already read the issues
> * ask questions on the freeradius-users mailing list.  Github is for bugs, not for configuration questions
> * version 2 is end of life.  There's no reason to use it.  Upgrade to v3.
> * it should be pretty obvious that your "cut and paste" of debug output is entirely useless.  If you don't care enough for format it correctly, we don't care enough to read it.

Sory
