### ISSUE TITLE
freeradius 3.0.16 can't load dictionary

### ISSUE THREAD

**Issue by kakash1hatake** [FreeRADIUS/freeradius-server#2053]
Hello.
First I found that server doesn't start when module dhcp is enabled.
The version is 3.0.16 from repository.

The error message was:
`dict_init: /usr/local/share/freeradius/dictionary.dhcp[211]: Invalid attribute identifier: Attribute cannot have TLVs`

After some investigation I found this in dict.c:
```cpp
	/*
	 *	Check the vendor.  Only RFC format attributes can have TLVs.
	 */
	if (*pvendor) {
		DICT_VENDOR const *dv = NULL;

		dv = dict_vendorbyvalue(*pvendor);
		if (dv && (dv->type != 1)) {
			if (*pvalue || (tlv_depth != 0)) {
				fr_strerror_printf("Attribute cannot have TLVs");
				return -1;
			}

			if (!sscanf_i(ptr, &attr)) {
				fr_strerror_printf("Invalid data '%s' in attribute identifier", ptr);
				return -1;
			}

			if ((dv->type < 3) && (attr > (unsigned int) (1 << (8 * dv->type)))) {
				fr_strerror_printf("Number '%s' out of allowed range in attribute identifier", ptr);
				return -1;
			}
			
			*pvalue = attr;

#ifdef WITH_DHCP
			/*
			 *	DHCP attributes can have TLVs. <sigh>
			 */
			if (*pvendor == 54) goto dhcp_skip;
#endif
			goto done;
		}
	}
```

And in dictionary.dhcp vendor is defined with `format=2,1`
So it has `type=2` and the condition `(dv && (dv->type != 1))` is evaluated as `true`.

To fix this I suggest moving the later check `(*pvendor == 54)` that doesn't work now inside the first condition:
```cpp
if (dv && (dv->type != 1) && (*pvendor != 54)) {
			if (*pvalue || (tlv_depth != 0)) {
				fr_strerror_printf("Attribute cannot have TLVs");
				return -1;
			}
```

After fixing it I got another error:
`dict_init: /usr/local/share/freeradius/dictionary.dhcp[35]: Invalid attribute identifier: Number '256' out of allowed range in attribute identifier`

and I decided to hack 2 more conditions to add dhcp exclusion:
```cpp
			if ((dv->type < 3) && (attr > (unsigned int) (1 << (8 * dv->type))) && (*pvendor != 54)) {
				fr_strerror_printf("Number '%s' out of allowed range in attribute identifier", ptr);
				return -1;
			}
```
and
```cpp
		if ((attr > fr_attr_mask[tlv_depth]) && (*pvendor != 54)) {
			fr_strerror_printf("Number '%s' out of allowed range in attribute identifier", ptr);
			return -1;
		}
```

After that the server was still unable to start, the log showed another error text:
`Errors reading dictionary: dict_init: /usr/local/share/freeradius/dictionary.dhcp[211]: sub-tlv has invalid attribute number`
Again line 211!
In the dictionary it stands for the **DHCP-Agent-Circuit-Id**
```
BEGIN-TLV       DHCP-Relay-Agent-Information

ATTRIBUTE       DHCP-Agent-Circuit-Id                   1       octets
ATTRIBUTE       DHCP-Agent-Remote-Id                    2       octets

# 3 is reserved and shouldn't be used for anything
ATTRIBUTE       DHCP-Docsis-Device-Class                4       integer
ATTRIBUTE       DHCP-Relay-Link-Selection               5       ipaddr
ATTRIBUTE       DHCP-Subscriber-Id                      6       string

# AGH!  RADIUS inside of DHCP!
ATTRIBUTE       DHCP-RADIUS-Attributes                  7       octets

# Horribly complicated
ATTRIBUTE       DHCP-Authentication-Information         8       octets
ATTRIBUTE       DHCP-Vendor-Specific-Information        9       octets
ATTRIBUTE       DHCP-Relay-Agent-Flags                  10      byte
ATTRIBUTE       DHCP-Server-Identifier-Override         11      ipaddr
END-TLV         DHCP-Relay-Agent-Information
```

again digging into code and hacking:
```cpp
        if (block_tlv) {
                /*
                 *      TLV's can be only one octet.
                 */
                if (((value == 0) || ((value & ~fr_attr_mask[tlv_depth]) != 0)) && (vendor != 54)) {
                        fr_strerror_printf( "dict_init: %s[%d]: sub-tlv has invalid attribute number",
                                            fn, line);
                        return -1;
                }
```

And why the message says `attribute number` when the comment explains that the code deals with the length of sub-tlv attribute?

Do you think it was the last probem to solve? No.
`dict_init: /usr/local/share/freeradius/dictionary.microsoft[26]: The "encrypt=1" flag MUST be used with an explicit length for 'octets' data type`

line 26  stands for **MS-CHAP-MPPE-Keys**
```
ATTRIBUTE       MS-CHAP-MPPE-Keys                       12      octets  encrypt=1
ATTRIBUTE       MS-BAP-Usage                            13      integer
ATTRIBUTE       MS-Link-Utilization-Threshold           14      integer # values are 1-100
ATTRIBUTE       MS-Link-Drop-Time-Limit                 15      integer
ATTRIBUTE       MS-MPPE-Send-Key                        16      octets  encrypt=2
ATTRIBUTE       MS-MPPE-Recv-Key                        17      octets  encrypt=2
```
and there are some more encrypted with type octets.

Ok, I commented out the include in `/usr/local/share/freeradius/dictionary` ... and got a "new" error:
`dict_init: /usr/local/share/freeradius/dictionary.wimax[66]: sub-tlv has invalid attribute number`

So I commented out **dictionary.wimax** too.
Only after that I managed to start the daemon.

**Comment by alandekok** [comment]
> line 26 stands for MS-CHAP-MPPE-Keys
> ATTRIBUTE       MS-CHAP-MPPE-Keys                       12      octets  encrypt=1

You have installed multiple versions of the server.  Don't do that.

i.e. you have 3.0.16 installed, and another (older) version of the server.  That line in dictionary.mschap changed TWO YEARS ago:

$ git annotate share/dictionary.microsoft  | grep Keys
00f041d6	(Alan T. DeKok	2015-09-14 08:50:00 -0400	35)ATTRIBUTE	MS-CHAP-MPPE-Keys			12	octets[24]  encrypt=1

This entire problem is caused by your local system.  The default build works, so long as you don't mix multiple versions of the server on the same machine.

**Comment by kakash1hatake** [comment]
Yeah, I have 2.x and 3.x installations on the same machine.
Finally I got it when was recheckin the dictionary files from the repo.
Sorry for bothering.
