### ISSUE TITLE
We should probably do an OpenSSL version check in main configure script

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#2054]
As per title.

https://www.openssl.org/source/

> Note: The latest stable version is the 1.1.0 series. The 1.0.2 series is our Long Term Support (LTS) release, supported until 31st December 2019. The 0.9.8, 1.0.0 and 1.0.1 versions are now out of support and should not be used.

Seems like 1.0.2 would be a good minimum for v3.0.x and v4.0.x? First release on the 1.0.2 branch was only 19th March 2015 though. 1.0.1 was 14th of March 2012, 1.0.0 was 1st Jun 2010.

**Comment by alandekok** [comment]
I agree.

**Comment by alanbuxey** [comment]
1.0.2 should be a good minimum - the only trouble is those darn LTS-based
distros which are still stuck on 1.0.1 (usually release e or f  :( )

**Comment by spaetow** [comment]
@alanbuxey Plus patches... *gag*

**Comment by alandekok** [comment]
In "master".  from configure.ac:

```
    AC_MSG_CHECKING([for OpenSSL version >= 1.0.2])
```
