### ISSUE TITLE
radiusTunnelPassword should not be SINGLE-VALUE

### ISSUE THREAD

**Issue by rgrant** [FreeRADIUS/freeradius-server#2061]
The OpenLDAP schema supplied with FreeRADIUS in:

freeradius-server-3.0.15/doc/schemas/ldap/openldap

should be modified to conform with RFC2868, and allow multiple radiusTunnelPassword entries.

Despite the RFC, the Tunnel-Password packet MUST be passed to the trusted Proxy, in order for a remote L2TP Access Concentrator (LAC) to obtain authentication details to login to an L2TP Network Server (LNS).

Using only one radiusTunnelPassword entry results in only the FIRST Tunnel-Server-Endpoint working.

Please modify the sample schema to remove the SINGLE-VALUE specification.

**Comment by arr2036** [comment]
Agreed. Please send a pull request.
