### ISSUE TITLE
share/freeradius/dictionary.juniper

### ISSUE THREAD

**Issue by gouthamreddy8055** [FreeRADIUS/freeradius-server#2066]
# Issue type

Juniper attribute needs to be updated. profiles is marked as profile and causing auth failure.

exisitng:
ATTRIBUTE       Juniper-Junosspace-Profile             11      string 

update with:
ATTRIBUTE       Juniper-Junosspace-Profiles             11      string

https://www.juniper.net/documentation/en_US/junos-space13.3/platform/topics/task/configuration/platform-radius-server-configuring.html

**Comment by arr2036** [comment]
Um, nope. Not how RADIUS attributes work.  String names don't leave the RADIUS server.  Check packet traces if you don't believe me.
