### ISSUE TITLE
install doesn't create symlinks in (sites-|mods-)enabled, but copies instead

### ISSUE THREAD

**Issue by egroeper** [FreeRADIUS/freeradius-server#2074]
# Issue type
- [x] Defect - Unexpected behaviour (obvious or verified by project member).

## How to reproduce issue

```
./configure --prefix=/usr/local
make
make install
```

## Actual Result
 
In /usr/local/etc/raddb/(sites-|mods-)enabled are real files (copies) instead of symlinks to the files in (sites-|mods-)available.
So changing files in (sites-|mods-)available doesn't have any effect.

## Expected result
default config in $PREFIX/etc/raddb/ with symlinks in (sites-|mods-)enabled to the specific files in (sites-|mods-)available (as stated in the docs).

**Comment by alandekok** [comment]
This works from a clean install.

What's likely happened is that someone on your system copied the files there before you re-installed the server.  FreeRADIUS *will not* over-write an existing installation.

**Comment by egroeper** [comment]
You are correct. Sorry. It was my Ansible playbook, that messed things up...
