### ISSUE TITLE
configcheck not executed before stop/restart (systemd)

### ISSUE THREAD

**Issue by sts** [FreeRADIUS/freeradius-server#2080]
The `freeradius.service` file which is supplied with the Freeradius Debian package restarts Freeradius regardless whether the configuration test succeeds. This behaviour changed when switching to systemd as the old [sysvinit script returned](https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/debian/freeradius.init#L70), before the running daemon was killed in case the current configuration didn't succeed the configcheck.

The systemd service file facilitates the `ExecStartPre` option, to run a config check, but `ExecStartPre` is only executed before service start, which is IMO the init action where such a check is least useful.

Other things, like the freeradius Puppet module, assumes the old sysvinit behaviour to avoid service outages in case a broken configuration gets deployed.
https://github.com/djjudas21/puppet-freeradius/blob/master/manifests/init.pp#L255

Now, the bad news is that systemd obviously doesn't provide a way to run a config check before stop and restart. One could maybe use the workaround used with ExecReloadPre and we could switch the Puppet module to do a reload instead:
https://github.com/systemd/systemd/issues/2175

**Comment by alandekok** [comment]
This is fixed now in v3.
