### ISSUE TITLE
Default list in update sections with dynamic LHS isn't applied

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#2090]
# Issue type
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect/Feature description

Default list in update section doesn't work if the LHS is a dynamic attribute reference.

Explicitly setting the list does work.

i.e.

## Works (attribute added to control list)
```
update  {
	"&control:%{attr_by_oid:26.44318.%{1}}" := "%{2}"
}
```

## Doesn't work (attribute added to request list)
```
update control  {
	"%{attr_by_oid:26.44318.%{1}}" := "%{2}"
}
```

This is a minor defect but should be fixed at some point before v4.0.x is released.

**Comment by ndptech** [comment]
`update` is removed now in v4
