### ISSUE TITLE
3.0.15 crashing

### ISSUE THREAD

**Issue by jodyjamesgreen** [FreeRADIUS/freeradius-server#2117]
# Issue type
- [ x] Defect - Crash or memory corruption.
- [ ] Defect - Non compliance with a standards document, or incorrect API usage.
- [ ] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect/Feature description
Radiusd crashing constantly after upgrade.

Running with raduisd -X I get the following.  Sorry, I'm new to all this github stuff.

*** Error in `/usr/local/sbin/radiusd': malloc(): memory corruption: 0x00000000022d7b40 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7dd7d)[0x7faef94ddd7d]
/lib64/libc.so.6(__libc_malloc+0x4c)[0x7faef94e010c]
/lib64/libtalloc.so.2(_talloc_zero+0x18c)[0x7faefa51444c]
/usr/local/lib/libfreeradius-server.so(+0x1f9c5)[0x7faefb25a9c5]
/usr/local/lib/libfreeradius-server.so(+0x1fee7)[0x7faefb25aee7]
/usr/local/lib/libfreeradius-server.so(radius_xlat+0x13)[0x7faefb25c363]
/usr/local/lib/rlm_linelog.so(+0x1071)[0x7faef6a57071]
/usr/local/sbin/radiusd[0x425f3f]
/usr/local/sbin/radiusd[0x425079]
/usr/local/sbin/radiusd[0x42524e]
/usr/local/sbin/radiusd(modcall+0x43)[0x426453]
/usr/local/sbin/radiusd(indexed_modcall+0x9d)[0x4211ad]
/usr/local/sbin/radiusd(rad_postauth+0x71)[0x4105b1]
/usr/local/sbin/radiusd(rad_virtual_server+0x398)[0x411628]
/usr/local/lib/rlm_eap_peap.so(eappeap_process+0xa9d)[0x7faef501085d]
/usr/local/lib/rlm_eap_peap.so(+0x1b8a)[0x7faef500eb8a]
/usr/local/lib/rlm_eap.so(+0x3772)[0x7faef706a772]
/usr/local/lib/rlm_eap.so(eap_method_select+0x2d3)[0x7faef706ac93]
/usr/local/lib/rlm_eap.so(+0x2a99)[0x7faef7069a99]
/usr/local/sbin/radiusd[0x425f3f]
/usr/local/sbin/radiusd[0x425079]
/usr/local/sbin/radiusd[0x42524e]
/usr/local/sbin/radiusd(modcall+0x43)[0x426453]
/usr/local/sbin/radiusd(indexed_modcall+0x9d)[0x4211ad]
/usr/local/sbin/radiusd(rad_authenticate+0x736)[0x411016]
/usr/local/sbin/radiusd[0x433ea2]
/usr/local/sbin/radiusd[0x42ffe4]
/usr/local/sbin/radiusd(request_receive+0x347)[0x431737]
/usr/local/sbin/radiusd[0x41c066]
/usr/local/sbin/radiusd[0x42e72b]
/usr/local/lib/libfreeradius-radius.so(fr_event_loop+0x2fc)[0x7faefb02604c]
/usr/local/sbin/radiusd(main+0x6ea)[0x40fb8a]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7faef9481c05]
/usr/local/sbin/radiusd[0x40feba]
======= Memory map: ========
00400000-00463000 r-xp 00000000 fd:00 102163904                          /usr/local/sbin/radiusd
00662000-00665000 r--p 00062000 fd:00 102163904                          /usr/local/sbin/radiusd
00665000-00669000 rw-p 00065000 fd:00 102163904                          /usr/local/sbin/radiusd
00669000-0066b000 rw-p 00000000 00:00 0
01f7a000-0233a000 rw-p 00000000 00:00 0                                  [heap]
7faef0000000-7faef0021000 rw-p 00000000 00:00 0
7faef0021000-7faef4000000 ---p 00000000 00:00 0
7faef4bf2000-7faef4c07000 r-xp 00000000 fd:00 270444                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7faef4c07000-7faef4e06000 ---p 00015000 fd:00 270444                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7faef4e06000-7faef4e07000 r--p 00014000 fd:00 270444                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7faef4e07000-7faef4e08000 rw-p 00015000 fd:00 270444                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7faef4e08000-7faef4e0c000 r-xp 00000000 fd:00 2940452                    /usr/local/lib/rlm_eap_mschapv2.so
7faef4e0c000-7faef500b000 ---p 00004000 fd:00 2940452                    /usr/local/lib/rlm_eap_mschapv2.soCAUGHT SIGNAL: Aborted
Calling: gdb -silent -x /usr/local/etc/raddb/panic.gdb /usr/local/sbin/radiusd 18638 2>&1 | tee /usr/local/var/log/radius/gdb-radiusd-18638.log
Temporarily setting PR_DUMPABLE to 1
Reading symbols from /usr/local/sbin/radiusd...done.
Attaching to program: /usr/local/sbin/radiusd, process 18638
Reading symbols from /usr/local/lib/libfreeradius-server.so...done.
Loaded symbols for /usr/local/lib/libfreeradius-server.so
Reading symbols from /usr/local/lib/libfreeradius-radius.so...done.
Loaded symbols for /usr/local/lib/libfreeradius-radius.so
Reading symbols from /usr/local/lib/libfreeradius-eap.so...done.
Loaded symbols for /usr/local/lib/libfreeradius-eap.so
Reading symbols from /lib64/libcrypto.so.10...Reading symbols from /lib64/libcrypto.so.10...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypto.so.10
Reading symbols from /lib64/libssl.so.10...Reading symbols from /lib64/libssl.so.10...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libssl.so.10
Reading symbols from /lib64/libtalloc.so.2...Reading symbols from /lib64/libtalloc.so.2...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libtalloc.so.2
Reading symbols from /lib64/libpcre.so.1...Reading symbols from /lib64/libpcre.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libpcre.so.1
Reading symbols from /lib64/libnsl.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnsl.so.1
Reading symbols from /lib64/libresolv.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libresolv.so.2
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libcrypt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypt.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/libz.so.1...Reading symbols from /lib64/libz.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libz.so.1
Reading symbols from /lib64/libgssapi_krb5.so.2...Reading symbols from /lib64/libgssapi_krb5.so.2...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libgssapi_krb5.so.2
Reading symbols from /lib64/libkrb5.so.3...Reading symbols from /lib64/libkrb5.so.3...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libkrb5.so.3
Reading symbols from /lib64/libcom_err.so.2...Reading symbols from /lib64/libcom_err.so.2...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libcom_err.so.2
Reading symbols from /lib64/libk5crypto.so.3...Reading symbols from /lib64/libk5crypto.so.3...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libk5crypto.so.3
Reading symbols from /lib64/libfreebl3.so...Reading symbols from /lib64/libfreebl3.so...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libfreebl3.so
Reading symbols from /lib64/libkrb5support.so.0...Reading symbols from /lib64/libkrb5support.so.0...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libkrb5support.so.0
Reading symbols from /lib64/libkeyutils.so.1...Reading symbols from /lib64/libkeyutils.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libkeyutils.so.1
Reading symbols from /lib64/libselinux.so.1...Reading symbols from /lib64/libselinux.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libselinux.so.1
Reading symbols from /lib64/libnss_files.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_files.so.2
Reading symbols from /lib64/libnss_sss.so.2...Reading symbols from /lib64/libnss_sss.so.2...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_sss.so.2
Reading symbols from /usr/local/lib/rlm_always.so...done.
Loaded symbols for /usr/local/lib/rlm_always.so
Reading symbols from /usr/local/lib/rlm_attr_filter.so...done.
Loaded symbols for /usr/local/lib/rlm_attr_filter.so
Reading symbols from /usr/local/lib/rlm_cache.so...done.
Loaded symbols for /usr/local/lib/rlm_cache.so
Reading symbols from /usr/local/lib/rlm_date.so...done.
Loaded symbols for /usr/local/lib/rlm_date.so
Reading symbols from /usr/local/lib/rlm_detail.so...done.
Loaded symbols for /usr/local/lib/rlm_detail.so
Reading symbols from /usr/local/lib/rlm_eap.so...done.
Loaded symbols for /usr/local/lib/rlm_eap.so
Reading symbols from /usr/local/lib/rlm_expr.so...done.
Loaded symbols for /usr/local/lib/rlm_expr.so
Reading symbols from /usr/local/lib/rlm_files.so...done.
Loaded symbols for /usr/local/lib/rlm_files.so
Reading symbols from /usr/local/lib/rlm_linelog.so...done.
Loaded symbols for /usr/local/lib/rlm_linelog.so
Reading symbols from /usr/local/lib/rlm_mschap.so...done.
Loaded symbols for /usr/local/lib/rlm_mschap.so
Reading symbols from /lib64/libwbclient.so.0...Reading symbols from /usr/lib/debug/usr/lib64/samba/wbclient/libwbclient.so.0.13.debug...done.
done.
Loaded symbols for /lib64/libwbclient.so.0
Reading symbols from /usr/lib64/samba/libwinbind-client-samba4.so...Reading symbols from /usr/lib/debug/usr/lib64/samba/libwinbind-client-samba4.so.debug...done.
done.
Loaded symbols for /usr/lib64/samba/libwinbind-client-samba4.so
Reading symbols from /usr/lib64/samba/libreplace-samba4.so...Reading symbols from /usr/lib/debug/usr/lib64/samba/libreplace-samba4.so.debug...done.
done.
Loaded symbols for /usr/lib64/samba/libreplace-samba4.so
Reading symbols from /usr/local/lib/rlm_preprocess.so...done.
Loaded symbols for /usr/local/lib/rlm_preprocess.so
Reading symbols from /usr/local/lib/rlm_realm.so...done.
Loaded symbols for /usr/local/lib/rlm_realm.so
Reading symbols from /usr/local/lib/rlm_soh.so...done.
Loaded symbols for /usr/local/lib/rlm_soh.so
Reading symbols from /usr/local/lib/rlm_unpack.so...done.
Loaded symbols for /usr/local/lib/rlm_unpack.so
Reading symbols from /usr/local/lib/rlm_utf8.so...done.
Loaded symbols for /usr/local/lib/rlm_utf8.so
Reading symbols from /usr/local/lib/rlm_cache_rbtree.so...done.
Loaded symbols for /usr/local/lib/rlm_cache_rbtree.so
Reading symbols from /usr/local/lib/rlm_eap_tls.so...done.
Loaded symbols for /usr/local/lib/rlm_eap_tls.so
Reading symbols from /usr/local/lib/rlm_eap_ttls.so...done.
Loaded symbols for /usr/local/lib/rlm_eap_ttls.so
Reading symbols from /usr/local/lib/rlm_eap_peap.so...done.
Loaded symbols for /usr/local/lib/rlm_eap_peap.so
Reading symbols from /usr/local/lib/rlm_eap_mschapv2.so...done.
Loaded symbols for /usr/local/lib/rlm_eap_mschapv2.so
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
0x00007faef951edbc in waitpid () from /lib64/libc.so.6
No symbol table info available.
No symbol table info available.

Thread 1 (Thread 0x7faefb66a840 (LWP 18638)):
#0  0x00007faef951edbc in waitpid () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007faef94a1cc2 in do_system () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007faefb00afa8 in fr_fault (sig=<optimized out>) at src/lib/debug.c:725
        disable = true
        cmd = "gdb -silent -x /usr/local/etc/raddb/panic.gdb /usr/local/sbin/radiusd 18638 2>&1 | tee /usr/local/var/log/radius/gdb-radiusd-18638.log", '\000' <repeats 397 times>
        out = 0x7ffe09fc5572 ".log"
        left = 402
        ret = <optimized out>
        p = <optimized out>
        q = 0x0
        code = <optimized out>
#3  <signal handler called>
No symbol table info available.
#4  0x00007faef94951f7 in raise () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007faef94968e8 in abort () from /lib64/libc.so.6
No symbol table info available.
#6  0x00007faef94d4f47 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#7  0x00007faef94ddd7d in _int_malloc () from /lib64/libc.so.6
No symbol table info available.
#8  0x00007faef94e010c in malloc () from /lib64/libc.so.6
No symbol table info available.
#9  0x00007faefa51444c in _talloc_zero () from /lib64/libtalloc.so.2
No symbol table info available.
#10 0x00007faefb25a9c5 in xlat_tokenize_literal (ctx=ctx@entry=0x22d73b0, fmt=fmt@entry=0x22f8300 "messages.%{%{reply:Packet-Type}:-default}", head=head@entry=0x7ffe09fc6790, brace=brace@entry=false,
    error=error@entry=0x7ffe09fc6798) at src/main/xlat.c:1402
        p = <optimized out>
        node = <optimized out>
#11 0x00007faefb25aee7 in xlat_tokenize_literal (error=0x7ffe09fc6798, brace=false, head=0x7ffe09fc6790, fmt=0x22f8300 "messages.%{%{reply:Packet-Type}:-default}", ctx=0x22d73b0) at src/main/xlat.c:2575
No locals.
#12 xlat_tokenize_request (head=0x7ffe09fc6790, fmt=0x2245cb0 "messages.%{%{reply:Packet-Type}:-default}", request=request@entry=0x22d73b0) at src/main/xlat.c:1795
        tokens = 0x22f8300 "messages.%{%{reply:Packet-Type}:-default}"
        error = 0x0
#13 xlat_expand (out=out@entry=0x7ffe09fc67e8, outlen=outlen@entry=4095, request=request@entry=0x22d73b0, fmt=0x2245cb0 "messages.%{%{reply:Packet-Type}:-default}",
    escape=escape@entry=0x7faef6a57580 <linelog_escape_func>, escape_ctx=escape_ctx@entry=0x0) at src/main/xlat.c:2556
        len = <optimized out>
        node = 0x0
#14 0x00007faefb25c363 in radius_xlat (out=out@entry=0x7ffe09fc7011 "", outlen=outlen@entry=4095, request=request@entry=0x22d73b0, fmt=<optimized out>,
    escape=escape@entry=0x7faef6a57580 <linelog_escape_func>, ctx=ctx@entry=0x0) at src/main/xlat.c:2630
No locals.
#15 0x00007faef6a57071 in mod_do_linelog (instance=0x2245850, request=0x22d73b0) at src/modules/rlm_linelog/rlm_linelog.c:194
        ci = <optimized out>
        cp = <optimized out>
        fd = -1
        inst = 0x2245850
        value = 0x2245c20 "This is a log message for %{User-Name}"
        gid = 0
        endptr = 0x0
        path = "\200\371%\373\256\177\000\000E\351%\373\256\177\000\000\000\000ession@\264\201\371\256\177\000\000\000\000\000\000\000\000\000\000@h\374\t\376\177\000\000\200\371%\373\256\177\000\000\000\000\000\000\000\000\000\000v", '\000' <repeats 15 times>, "\200\371%\373\256\177\000\000E\351%\373\256\177\000\000P\227\374\t\376\177\000\000@\264\201\371\256\177\000\000\360~-\002\000\000\000\000pi\374\t\376\177\000\000\020\000\000\000\000\000\000\000y\000\000\000\000\000\000\000\300\253D\000\000\000\000\000!\315$\373\256\177\000\000pi\374\t\376\177\000\000\240i\374\t\376\177\000\000\020\000\000\000\000\000\000\000y\000\000\000\000\000\000\000\360~-\002\000\000\000\000"...
        line = '\000' <repeats 16 times>, "\210\211J\371", '\000' <repeats 28 times>, "\210\211J\371\256\177\000\000\000\000\000\000\256\177\000\000-80:edur", '\000' <repeats 16 times>, "\362u\245\366\256\177\000\000\377\377\377\377\060\000\000\000 w\374\t\376\177\000\000`v\374\t\376\177\000\000@\264\201\371\256\177\000\000\000\000\000\000\000\000\000\000 up request packet ID 187 with timestamp +152\000er'\000\000\000\000\000\000\000`\237-\002\000\000\000\000"...
#16 0x0000000000425f3f in call_modsingle (request=0x22d73b0, sp=0x22a1270, component=MOD_POST_AUTH) at src/main/modcall.c:302
        blocked = <optimized out>
        indent = 6
#17 modcall_recurse (request=<optimized out>, component=MOD_POST_AUTH, depth=1, entry=entry@entry=0x7ffe09fc8478, do_next_sibling=true) at src/main/modcall.c:578
        if_taken = false
        was_if = false
        c = 0x22a1270
        priority = -1
        result = RLM_MODULE_UNKNOWN
#18 0x0000000000425079 in modcall_child (request=<optimized out>, component=<optimized out>, depth=<optimized out>, entry=0x7ffe09fc8460, c=<optimized out>, result=0x7ffe09fc82d4, do_next_sibling=true)
    at src/main/modcall.c:408
        next = 0x7ffe09fc8478
#19 0x000000000042524e in modcall_recurse (request=request@entry=0x22d73b0, component=component@entry=MOD_POST_AUTH, depth=depth@entry=0, entry=entry@entry=0x7ffe09fc8460,
    do_next_sibling=do_next_sibling@entry=true) at src/main/modcall.c:789
        if_taken = false
        was_if = false
        c = 0x22a1170
        priority = -1
        result = RLM_MODULE_UNKNOWN
#20 0x0000000000426453 in modcall (component=component@entry=MOD_POST_AUTH, c=c@entry=0x22a1170, request=request@entry=0x22d73b0) at src/main/modcall.c:1134
        stack = {{result = RLM_MODULE_NOOP, priority = 0, unwind = 0, c = 0x22a1170}, {result = RLM_MODULE_NOOP, priority = 0, unwind = 0, c = 0x22a1270}, {result = 36766032, priority = 0,
            unwind = -89826709, c = 0x68}, {result = 16, priority = 0, unwind = 36697848, c = 0x2310150}, {result = 16, priority = 805306368, unwind = 167544080, c = 0x22d73f8}, {result = 36543760,
            priority = 0, unwind = 0, c = 0x0}, {result = RLM_MODULE_REJECT, priority = 0, unwind = -81401531, c = 0x7ffe09fc87c0}, {result = 4182589881, priority = 32686, unwind = -72515583,
            c = 0x7ffe09fc87c0}, {result = 167544768, priority = 32766, unwind = 167544768, c = 0x7ffe09fc87c0}, {result = 167544786, priority = 32766, unwind = 167545023, c = 0x7ffe09fc87c0}, {
            result = 167545023, priority = 32766, unwind = 0, c = 0x0}, {result = RLM_MODULE_REJECT, priority = 0, unwind = 0, c = 0x0}, {result = 167544848, priority = 0, unwind = 167544866,
            c = 0x7ffe09fc0000}, {result = RLM_MODULE_REJECT, priority = 0, unwind = 167545103, c = 0x0}, {result = RLM_MODULE_REJECT, priority = 0, unwind = 0, c = 0x0}, {result = RLM_MODULE_REJECT,
            priority = 0, unwind = -1, c = 0x0}, {result = RLM_MODULE_REJECT, priority = 32, unwind = -108940224, c = 0x0}, {result = 36656496, priority = 0, unwind = -167544447, c = 0x0}, {
            result = RLM_MODULE_HANDLED, priority = 0, unwind = 0, c = 0x5bffffffff}, {result = 167544448, priority = 32766, unwind = 0, c = 0x7faef981b440 <_IO_strn_jumps>}, {result = 36734384,
            priority = 0, unwind = 167544768, c = 0x100}, {result = 36533168, priority = 0, unwind = 4466343, c = 0x7}, {result = 36293440, priority = 0, unwind = 36311408, c = 0x229cb78}, {
            result = 4213493456, priority = 32686, unwind = -81401531, c = 0x3000000020}, {result = 167544688, priority = 32766, unwind = 167544496, c = 0x7ffe09fc8780}, {result = 167544512,
            priority = 32766, unwind = 0, c = 0x2}, {result = 4466343, priority = 0, unwind = 35542816, c = 0x7faefb25e945}, {result = 167544768, priority = 32766, unwind = 34, c = 0xee}, {
            result = 4213565765, priority = 32686, unwind = -83791315, c = 0x7ffe00000022}, {result = 4211120582, priority = 32686, unwind = 167544672, c = 0x3f6}, {result = RLM_MODULE_REJECT,
            priority = 0, unwind = -128, c = 0x2308e40}, {result = 4322816, priority = 0, unwind = 36533168, c = 0x22d73b0}}
#21 0x00000000004211ad in indexed_modcall (comp=comp@entry=MOD_POST_AUTH, idx=idx@entry=0, request=request@entry=0x22d73b0) at src/main/modules.c:1028
        rcode = <optimized out>
        list = 0x22a1170
        server = <optimized out>
#22 0x000000000042233f in process_post_auth (postauth_type=postauth_type@entry=0, request=request@entry=0x22d73b0) at src/main/modules.c:2241
No locals.
#23 0x00000000004105b1 in rad_postauth (request=request@entry=0x22d73b0) at src/main/auth.c:317
        result = <optimized out>
        postauth_type = 0
        vp = <optimized out>
#24 0x0000000000411628 in rad_virtual_server (request=request@entry=0x22d73b0) at src/main/auth.c:824
        vp = <optimized out>
        result = 0
#25 0x00007faef501085d in eappeap_process (handler=handler@entry=0x2314690, tls_session=tls_session@entry=0x22e20c0, auth_type_eap=16775716) at src/modules/rlm_eap/types/rlm_eap_peap/peap.c:1024
        t = <optimized out>
        fake = <optimized out>
        vp = <optimized out>
        rcode = RLM_MODULE_REJECT
        data = 0x22e6210 "\032\003\t"
        data_len = <optimized out>
        header = 0
        request = <optimized out>
        eap_ds = <optimized out>
#26 0x00007faef500eb8a in mod_process (arg=0x226dac0, handler=0x2314690) at src/modules/rlm_eap/types/rlm_eap_peap/rlm_eap_peap.c:335
        rcode = <optimized out>
        status = <optimized out>
        inst = 0x226dac0
        tls_session = 0x22e20c0
        peap = 0x22f5320
        request = 0x22d7ef0
#27 0x00007faef706a772 in eap_module_call (handler=handler@entry=0x2314690, module=<optimized out>, module=<optimized out>) at src/modules/rlm_eap/eap.c:194
        rcode = 1
        request = 0x22d7ef0
        caller = 0x223ee60 "eap"
#28 0x00007faef706ac93 in eap_method_select (inst=inst@entry=0x223f7c0, handler=handler@entry=0x2314690) at src/modules/rlm_eap/eap.c:457
        type = 0x22f5190
        request = 0x22d7ef0
        next = PW_EAP_PEAP
        vp = <optimized out>
#29 0x00007faef7069a99 in mod_authenticate (instance=0x223f7c0, request=0x22d7ef0) at src/modules/rlm_eap/rlm_eap.c:288
        inst = 0x223f7c0
        handler = 0x2314690
        eap_packet = 0x0
        status = <optimized out>
        rcode = <optimized out>
#30 0x0000000000425f3f in call_modsingle (request=0x22d7ef0, sp=0x228ef40, component=MOD_AUTHENTICATE) at src/main/modcall.c:302
        blocked = <optimized out>
        indent = 4
#31 modcall_recurse (request=<optimized out>, component=MOD_AUTHENTICATE, depth=1, entry=entry@entry=0x7ffe09fc8f98, do_next_sibling=true) at src/main/modcall.c:578
        if_taken = false
        was_if = false
        c = 0x228ef40
        priority = -1
        result = RLM_MODULE_UNKNOWN
#32 0x0000000000425079 in modcall_child (request=<optimized out>, component=<optimized out>, depth=<optimized out>, entry=0x7ffe09fc8f80, c=<optimized out>, result=0x7ffe09fc8df4, do_next_sibling=true)
    at src/main/modcall.c:408
        next = 0x7ffe09fc8f98
#33 0x000000000042524e in modcall_recurse (request=request@entry=0x22d7ef0, component=component@entry=MOD_AUTHENTICATE, depth=depth@entry=0, entry=entry@entry=0x7ffe09fc8f80,
    do_next_sibling=do_next_sibling@entry=true) at src/main/modcall.c:789
        if_taken = false
        was_if = false
        c = 0x228ee40
        priority = -1
        result = RLM_MODULE_UNKNOWN
#34 0x0000000000426453 in modcall (component=component@entry=MOD_AUTHENTICATE, c=c@entry=0x228ee40, request=request@entry=0x22d7ef0) at src/main/modcall.c:1134
        stack = {{result = RLM_MODULE_REJECT, priority = 0, unwind = 0, c = 0x228ee40}, {result = RLM_MODULE_REJECT, priority = 0, unwind = 0, c = 0x228ef40}, {result = RLM_MODULE_OK, priority = 0,
            unwind = 0, c = 0x0}, {result = RLM_MODULE_NOTFOUND, priority = 0, unwind = 0, c = 0x0}, {result = 167548295, priority = 32766, unwind = 234, c = 0x22d9f60}, {result = 34, priority = 0,
            unwind = 36544304, c = 0x7ffe09fc9180}, {result = 256, priority = 0, unwind = 167547264, c = 0x2e38360030303331}, {result = 775173426, priority = 53, unwind = 4514332, c = 0x2}, {
            result = 167547264, priority = 32766, unwind = 167547216, c = 0x7faefb25e945}, {result = 36670656, priority = 0, unwind = -79250592, c = 0x0}, {result = 36235040, priority = 0,
            unwind = 36290592, c = 0x7ffe09fc9370}, {result = 4213493456, priority = 32686, unwind = 167547872, c = 0x3000000020}, {result = 167547248, priority = 32766, unwind = 167547056, c = 0x22}, {
            result = 234, priority = 0, unwind = -81401531, c = 0x7faefb01722d <vp_prints_value+93>}, {result = 36453408, priority = 0, unwind = 4504659, c = 0x7ffe09fc94ed}, {result = 167547184,
            priority = 32766, unwind = 167547632, c = 0x7ffe09fc9130}, {result = 4213580732, priority = 32686, unwind = 167547608, c = 0x1}, {result = 1023, priority = 0, unwind = 167547632,
            c = 0x7faef956d615 <__vsnprintf_chk+149>}, {result = 4222451713, priority = 0, unwind = 167547632, c = 0x7ffe09fc92f0}, {result = 167547632, priority = 32766, unwind = 167547632,
            c = 0x7ffe09fc92fd}, {result = 167548655, priority = 32766, unwind = 167547632, c = 0x7ffe09fc96ef}, {result = 36536048, priority = 0, unwind = 0, c = 0x0}, {result = 36235040, priority = 0,
            unwind = 36236864, c = 0x663760 <section_type_value>}, {result = 4213493456, priority = 32686, unwind = 0, c = 0x3000000020}, {result = 167547536, priority = 32766, unwind = 167547344,
            c = 0xfffa24}, {result = 4215716704, priority = 32686, unwind = 1, c = 0x7ffe09fc93e0}, {result = 35560352, priority = 0, unwind = 27, c = 0x0}, {result = 32, priority = 48, unwind = 167547616,
            c = 0x7ffe09fc9220}, {result = RLM_MODULE_FAIL, priority = 0, unwind = -83839938, c = 0x1f9b950}, {result = 4211147081, priority = 32686, unwind = 34783044,
            c = 0x7faefb01ec7a <rbtree_find+74>}, {result = 167547552, priority = 32766, unwind = 36536048, c = 0xfffa24}, {result = RLM_MODULE_REJECT, priority = 0, unwind = 36235040,
            c = 0x7faefb01ed19 <rbtree_finddata+9>}}
#35 0x00000000004211ad in indexed_modcall (comp=comp@entry=MOD_AUTHENTICATE, idx=idx@entry=16775716, request=request@entry=0x22d7ef0) at src/main/modules.c:1028
        rcode = <optimized out>
        list = 0x228ee40
        server = <optimized out>
#36 0x000000000042227c in process_authenticate (auth_type=auth_type@entry=16775716, request=request@entry=0x22d7ef0) at src/main/modules.c:2169
No locals.
#37 0x0000000000411016 in rad_check_password (request=0x22d7ef0) at src/main/auth.c:252
        cursor = {first = 0x22d7f38, found = 0x22d99c0, last = 0x0, current = 0x0, next = 0x0}
        auth_type_pair = <optimized out>
        auth_type = 16775716
        auth_type_count = 1
        result = <optimized out>
#38 rad_authenticate (request=0x22d7ef0) at src/main/auth.c:583
        check_item = <optimized out>
        module_msg = <optimized out>
        tmp = <optimized out>
        result = <optimized out>
        autz_retry = <optimized out>
        autz_type = <optimized out>
#39 0x0000000000433ea2 in request_running (request=0x22d7ef0, action=<optimized out>) at src/main/process.c:1536
        __FUNCTION__ = "request_running"
#40 0x000000000042ffe4 in request_queue_or_run (request=request@entry=0x22d7ef0, process=process@entry=0x433ce0 <request_running>) at src/main/process.c:1024
No locals.
#41 0x0000000000431737 in request_receive (ctx=ctx@entry=0x22d7be0, listener=listener@entry=0x22d2cc0, packet=0x22d7c40, client=client@entry=0x22286a0, fun=fun@entry=0x4108e0 <rad_authenticate>)
    at src/main/process.c:1792
        count = <optimized out>
        packet_p = <optimized out>
        request = <optimized out>
        now = {tv_sec = 1510305255, tv_usec = 883147}
        sock = <optimized out>
#42 0x000000000041c066 in auth_socket_recv (listener=0x22d2cc0) at src/main/listen.c:1571
        rcode = <optimized out>
        code = 1
        src_port = 32775
        packet = <optimized out>
        fun = 0x4108e0 <rad_authenticate>
        client = 0x22286a0
        src_ipaddr = {af = 2, ipaddr = {ip4addr = {s_addr = 100575424}, ip6addr = {__in6_u = {__u6_addr8 = "\300\250\376\005", '\000' <repeats 11 times>, __u6_addr16 = {43200, 1534, 0, 0, 0, 0, 0, 0},
                __u6_addr32 = {100575424, 0, 0, 0}}}}, prefix = 32 ' ', scope = 0}
        ctx = 0x22d7be0
#43 0x000000000042e72b in event_socket_handler (xel=<optimized out>, fd=<optimized out>, ctx=<optimized out>) at src/main/process.c:4593
        listener = <optimized out>
#44 0x00007faefb02604c in fr_event_loop (el=0x222b230) at src/lib/event.c:649
        ef = 0x222b280
        i = 1
        rcode = <optimized out>
        when = {tv_sec = 1510305258, tv_usec = 823977}
        wake = <optimized out>
        maxfd = 15
        read_fds = {fds_bits = {128, 0 <repeats 15 times>}}
        master_fds = {fds_bits = {65440, 0 <repeats 15 times>}}
#45 0x00000000004352c1 in radius_event_process () at src/main/process.c:5668
No locals.
#46 0x000000000040fb8a in main (argc=<optimized out>, argv=0x7ffe09fc9d08) at src/main/radiusd.c:585
        rcode = 0
        status = <optimized out>
        argval = <optimized out>
        spawn_flag = false
        display_version = false
        flag = 0
        from_child = {-1, -1}
        p = <optimized out>
        state = 0x6699e0 <global_state>
        autofree = 0x1f7a070
A debugging session is active.

        Inferior 1 [process 18638] will be detached.

Quit anyway? (y or n) [answered Y; input not from terminal]
Resetting PR_DUMPABLE to 0
Panic action exited with 0
[root@eduroam-rad-1 localadmin]#

**Comment by alandekok** [comment]
That's weird.  Can you try the v3.0.x branch from github?

https://github.com/FreeRADIUS/freeradius-server/archive/v3.0.x.zip

That has a number of fixes over 3.0.15, which should help.

**Comment by jodyjamesgreen** [comment]
Hi Alan,

I’ll get one of our Linux guys on it.  Is it simple to install?

**Comment by alandekok** [comment]
It's no harder than 3.0.15.
