### ISSUE TITLE
Variable Expansion and LDAP

### ISSUE THREAD

**Issue by J4yD4n** [FreeRADIUS/freeradius-server#2120]
# Issue type
Defect - Unexpected behaviour (obvious or verified by project member).
Version - 3.0.13

# Defect/Feature description
## How to reproduce issue
Within authorize section of default site:
authorize {
    ...*anything you need before*...
    -ldap   #Collect LDAP information
    #Collect SSID (format MAC:SSID)
    if (Called-Station-Id =~ /[0-9a-f]{2}[-][0-9a-f]{2}[-][0-9a-f]{2}[-][0-9a-f]{2}[-][0-9a-f]{2}[-][0-9a-f]{2}[:](.*)/i) {
        update reply {
            Tunnel-Type = VLAN
            Tunnel-Medium-Type = 6
        }
        if (LDAP-Group == "${1} VLAN 2") {
            update reply {
                Tunnel-Private-Group-ID = 2
            }
        }
    }
    ...*anything you need after*...
}

Debug:
if (LDAP-Group == "%{1} VLAN 3") {
EXPAND %{1} VLAN 3
   --> **SSID Name** VLAN 3
if (LDAP-Group == "%{1} VLAN 3")  -> FALSE

Result when not using a variable:
if (LDAP-Group == "**SSID Name** VLAN 3") {
Searching for user in group "**SSID Name** VLAN 3"
if (LDAP-Group == "**SSID Name** VLAN 3")  -> TRUE

**Comment by J4yD4n** [comment]
This functionality was working in version 3.0.4 and logins were being accepted while using the variable as the SSID Name. It was only after updating to 3.0.13 that I had to hard code in the SSID Name.

**Comment by alandekok** [comment]
Found and fixed already in #1947
