### ISSUE TITLE
Apache 2.4 AddRadiusAuth not working for non localhost IP

### ISSUE THREAD

**Issue by ribellusmt** [FreeRADIUS/freeradius-server#2124]
# Issue type
- [ ] Defect - Unexpected behaviour (obvious or verified by project member).

# Defect/Feature description
On Centos7 (Apache 2.4) with mod_auth_xradius 1.6.0 apache don't communication with the Radius server if the IP is not localhost. tcpdump don't show any Radius connection attemps to the remote IP.

# Works
AddRadiusAuth  127.0.0.1:1812 secretkey

# Doesn't work
AddRadiusAuth  10.10.100.10:1812 secretkey

**Comment by alandekok** [comment]
>  mod_auth_xradius

I didn't write that and I know nothing about it.  Go ask the authors of mod_auth_xradius how it works.

**Comment by ribellusmt** [comment]
Hello Alan,

Sorry it’s an error from my side with the name. It’s one of your module : https://freeradius.org/sub_projects/

The module is mod_auth_radius.
Can you please reOpen the case?

**Comment by arr2036** [comment]
That's mod_auth_radius not mod_auth_xradius.

**Comment by arr2036** [comment]
No, you're opening issues on the wrong issue tracker.  Use the one for mod_auth_radius if you are indeed using mod_auth_radius.

**Comment by arr2036** [comment]
It's highly likely it's a configuration issue on your side though.
