### ISSUE TITLE
issue setting DHCP-Your-Client-IP-Address as reply attribute with new sqlippool module

### ISSUE THREAD

**Issue by maximumG** [FreeRADIUS/freeradius-server#2126]
Related to issue #2094 I tried use the "attribute_name" with a value of DHCP-Your-Client-IP-Address.

However as of the code we wrote, we cannot use vendor attribute as VSA. Would it be acceptable to remove this lock in order to use a vendor VSA, line 438 of the code (e.g : DHCP dictionary) ?

By doing this, we would eliminate some code in the policy.d/dhcp file where we convert 'Framed-IP-Address' to 'DHCP-Your-Client-IP-Address'

I can propose a simple pull request if you are interested in ?

**Comment by alandekok** [comment]
Check the code.  It's been updated to allow VSAs.

**Comment by maximumG** [comment]
Many thanks for the reactivity !
