### ISSUE TITLE
Error: [sql] Error

### ISSUE THREAD

**Issue by jgamos** [FreeRADIUS/freeradius-server#2128]
Sun Nov 19 14:36:49 2017 : Error: [sql] Error processing groups; rejecting user
Sun Nov 19 14:36:49 2017 : Error: [sql] Error retrieving check pairs for group 1Month-5Mbps
Sun Nov 19 14:36:49 2017 : Error: rlm_sql (sql): Error getting data from database
Sun Nov 19 14:36:49 2017 : Error: rlm_sql: Failed to create the pair: Unknown attribute "Max-All-Session" requires a hex string, not "2678400"

Above is my issue using freeRADIUS, can anyone explain how to solve this?

**Comment by arr2036** [comment]
Yeah you're using an attribute that's not defined in the dictionaries.  Define the attribute as an integer type in ``/etc/raddb/dictionary``.
