### ISSUE TITLE
ZTE dictionary error

### ISSUE THREAD

**Issue by maximumG** [FreeRADIUS/freeradius-server#2130]
The ZTE vendor dictionary has 2 errors from line 14 to 15 for DNS assignation over RADIUS.
```
ATTRIBUTE       ZTE-Client-DNS-Pri                      1       integer
ATTRIBUTE       ZTE-Client-DNS-Sec                      2       integer
```
These 2 attributes are basically strings (ipv4 addresses) and should be changed to
```
ATTRIBUTE       ZTE-Client-DNS-Pri                      1       string
ATTRIBUTE       ZTE-Client-DNS-Sec                      2       string
```

**Comment by alandekok** [comment]
Do you have a reference or packet trace from ZTE to show this?

**Comment by maximumG** [comment]
Hello,

Here is an output of Wireshark with the actual format of ZTE-Client-DNS-Pri  & ZTE-Client-DNS-Sec
![capture du 2018-01-12 16-28-02](https://user-images.githubusercontent.com/4469833/34882118-cf49d318-f7b5-11e7-9f80-8bf964ee2256.png)

We are using the string format and its working just fine and accepted by ZTE devices

**Comment by dannyZhou** [comment]
May be 
```
ATTRIBUTE       ZTE-Client-DNS-Pri                      1       ipaddr
ATTRIBUTE       ZTE-Client-DNS-Sec                      2       ipaddr
```
is right.
