### ISSUE TITLE
 chap: ERROR: &control:Cleartext-Password is required for authentication

### ISSUE THREAD

**Issue by antoniovalenzuela** [FreeRADIUS/freeradius-server#2132]
After upgrade to v3.0 failed chap authentication with coovachilli.

 Auth-Type CHAP {
(7) chap: ERROR: &control:Cleartext-Password is required for authentication

module mysql OK
in DB Cleartext-Password op :=

[debug.txt](https://github.com/FreeRADIUS/freeradius-server/files/1500435/debug.txt)

Please help

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
