### ISSUE TITLE
Freeradius 3.0.12: ldap config parser uses lower case parameters but CA_file parameter in doc is in upper case

### ISSUE THREAD

**Issue by igloo777** [FreeRADIUS/freeradius-server#2151]
# Issue type
Freeradius in Debian 9 repository (version 3.0.12+dfsg-5+deb9u1)
- [x] Defect - Non compliance with a standards document, or incorrect API usage.
- [x] Defect - Unexpected behaviour (obvious or verified by project member).

# Defect/Feature description
In process of migration from Radius v2 to v3, i wasted 2 days to find that ldap config parser uses lower case parameters, but ``CA_file`` parameter in documentation is in UPPER case:

src/include/ldap/connection.c:
```
#ifdef HAVE_LDAP_START_TLS_S
        /*
         *      Set all of the TLS options
         */
        if (config->tls_mode) do_ldap_option(LDAP_OPT_X_TLS, "tls_mode", &(config->tls_mode));

        maybe_ldap_option(LDAP_OPT_X_TLS_CACERTFILE, "ca_file", config->tls_ca_file);
        maybe_ldap_option(LDAP_OPT_X_TLS_CACERTDIR, "ca_path", config->tls_ca_path);

        /*
         *      Set certificate options
```

From http://networkradius.com/doc/3.0.10/raddb/tls/tls-config_tls-common.html 
```
3.8.1 TLS - Config - common
Directives

CA_file
Syntax
CA_file = string
Default
${cadir}/ca.pem

CA_path
Syntax
CA_path = string
Default
${cadir}
```

## How to reproduce issue
- add into ldap config
```
  tls {
    CA_file = ${cadir}/ca.pem
    start_tls = no
  }
```
and TLS will not be established
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring
```text
Fri Jan  5 15:49:42 2018 : Info: rlm_ldap (ldap): Opening additional connection (0), 1 of 32 pending slots used
Fri Jan  5 15:49:42 2018 : Debug: rlm_ldap (ldap): Connecting to ldaps://ldap1.test.domain:636
ldap_create
ldap_url_parse_ext(ldaps://ldap1.test.domain:636)
Fri Jan  5 15:49:42 2018 : Debug: rlm_ldap (ldap): New libldap handle 0x55f8032400f0
ldap_bind
ldap_simple_bind
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP ldap1.test.domain:636
ldap_new_socket: 3
ldap_prepare_socket: 3
ldap_connect_to_host: Trying 10.101.0.254:636
ldap_pvt_connect: fd: 3 tm: 1 async: 0
ldap_ndelay_on: 3
attempting to connect: 
connect errno: 115
ldap_int_poll: fd: 3 tm: 1
ldap_is_sock_ready: 3
ldap_ndelay_off: 3
ldap_pvt_connect: 0
TLS: peer cert untrusted or revoked (0x42)
TLS: can't connect: (unknown error code).
ldap_err2string
Fri Jan  5 15:49:42 2018 : Error: rlm_ldap (ldap): Bind with (anonymous) to ldaps://ldap1.test.domain:636 failed: Can't contact LDAP server
```

- change to
```
  tls {
    ca_file = ${cadir}/ca.pem
    start_tls = no
  }
```

```
Fri Jan  5 16:05:33 2018 : Debug: rlm_ldap (ldap): Waiting for bind result...
ldap_result ld 0x559a848a6490 msgid 1
wait4msg ld 0x559a848a6490 msgid 1 (timeout 10000000 usec)
wait4msg continue ld 0x559a848a6490 msgid 1 all 1
** ld 0x559a848a6490 Connections:
* host: ldap1.test.domain  port: 636  (default)
  refcnt: 2  status: Connected
  last used: Fri Jan  5 16:05:33 2018


** ld 0x559a848a6490 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x559a848a6490 request count 1 (abandoned 0)
** ld 0x559a848a6490 Response Queue:
   Empty
  ld 0x559a848a6490 response count 0
ldap_chkResponseList ld 0x559a848a6490 msgid 1 all 1
ldap_chkResponseList returns ld 0x559a848a6490 NULL
ldap_int_select
read1msg: ld 0x559a848a6490 msgid 1 all 1
read1msg: ld 0x559a848a6490 msgid 1 message type bind
read1msg: ld 0x559a848a6490 0 new referrals
read1msg:  mark request completed, ld 0x559a848a6490 msgid 1
request done: ld 0x559a848a6490 msgid 1
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_result
ldap_msgfree
Fri Jan  5 16:05:33 2018 : Debug: rlm_ldap (ldap): Bind successful
Fri Jan  5 16:05:33 2018 : Debug: rlm_ldap (ldap): Adding pool reference 0x559a83be4ae0 to config item "ldap.pool"
```

Please, fix documentation, do not force a people to read a source code, to understand why parameters from documentation doesnt work...
It will save your carma.

**Comment by alandekok** [comment]
The example in the `raddb/mods-available/ldap` file, is documented as `ca_file`.

i.e. if you *read the file you are editing*, you would see the correct configuration option.

**Comment by igloo777** [comment]
I didn't edit example files. I edited my old v2 configs, based on the
documentation on site. Why i should edit examples?

5 янв. 2018 г. 20:44 пользователь "Alan DeKok" <notifications@github.com>
написал:

**Comment by alandekok** [comment]
The server comes with documentation.  This documentation includes text files, *and* example configuration in the `raddb` directory.

If you're porting your configuration from v2 to v3, you *must* read the v3 documentation and sample configuration.  Anything else is wasting your time, and mine.

**Comment by igloo777** [comment]
Read text files in ssh session on server..  in 2018? Ok, i got your
position. Thanks.

5 янв. 2018 г. 8:57 ПП пользователь "Alan DeKok" <notifications@github.com>
написал:

**Comment by alanbuxey** [comment]
WHY are you trying to use v2 configs on a v3 box? you need to start with
the v3 configs - and the v3 documentation

..if any complaint then it'd be things missing from
http://networkradius.com/doc/current/raddb/mods-available/ldap.html

WHY do you think http://networkradius.com/doc/3.0.10/raddb/tls/tls-config_
tls-common.html (EAP TLS client stuff)  should be for server LDAP
(or SQL etc) connections?

alan

**Comment by alandekok** [comment]
> WHY are you trying to use v2 configs on a v3 box? you need to start with
the v3 configs - and the v3 documentation

Because he's an idiot.

He's opening a bug report on the FreeRADIUS repo, for a documentation file that's hosted on a corporate site.

He doesn't start with the v3 configs as recommended in all of the documentation.

He's upset that I asked him to read the documentation that comes with v3.

He thinks that using SSH in a terminal is stupid in 2018.

He's too stupid to read the example files in... github... where he opened the PR.

And now he's blocked from the FR repo.
