### ISSUE TITLE
Integrate freeradius with hotel database 

### ISSUE THREAD

**Issue by starking8b** [FreeRADIUS/freeradius-server#2163]
I wish to integrate freeradius with ready hotel database which will be sql or oracle database .
I integrated freeradius with mysql and every things go fine, but now my customer asked me to make authentication depending on room number and username .
that mean when user want to access internet he must insert room number and his name .
how can I do that ?

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
