### ISSUE TITLE
apt remove does not clean up properly

### ISSUE THREAD

**Issue by ozzi-** [FreeRADIUS/freeradius-server#2170]
# Issue type
- [ ] Defect - Crash or memory corruption.
- [ ] Defect - Non compliance with a standards document, or incorrect API usage.
- [ -] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect/Feature description
## How to reproduce issue
```apt install freeradius
apt remove freeradius
apt install freeradius
...
Jan 30 10:43:01 hinserv freeradius[2156]:  * Starting FreeRADIUS daemon freeradius
Jan 30 10:43:01 hinserv freeradius[2156]:    ...fail!
Jan 30 10:43:01 hinserv systemd[1]: freeradius.service: Control process exited, code=exited status=1
Jan 30 10:43:01 hinserv systemd[1]: Failed to start LSB: Radius Daemon.
...
radiusd: #### Loading Virtual Servers ####
server { # from file /etc/freeradius/radiusd.conf
 modules {
/etc/freeradius/sites-enabled/default[252]: No such attribute Auth-Type
```

Solution:
```cd /var/lib/dpkg/info/
rm -rf freeradiu*
apt install freeradius
```

**Comment by alandekok** [comment]
This is how `apt` works.  See the Debian FAQ, and the "purge" command:

https://www.debian.org/doc/manuals/debian-faq/ch-pkgtools.en.html
