### ISSUE TITLE
BUG with nas ip address and SQL database

### ISSUE THREAD

**Issue by imperituroard** [FreeRADIUS/freeradius-server#2172]
[freeradius_bug.txt](https://github.com/FreeRADIUS/freeradius-server/files/1683852/freeradius_bug.txt)

Hello !

I'd like to add additional check with NAS-IP-ADDRESS from MySQL database.
I modified SQL for checking user account and created additional column nasip in the radcheck table.
Here is my sql:
	authorize_check_query = "SELECT id, username, attribute, value, op \
          FROM ${authcheck_table} \
          WHERE username = '%{SQL-User-Name}' and nasip = '%{NAS-IP-Address}' \
          ORDER BY id"

And it's not working, because in some iterations freeradius not insert NAS-IP-Address.
You can see it in attach debug file.
for example here is all good:
rad_recv: Access-Request packet from host 10.24.1.20 port 49750, id=223, length=150
        Service-Type = Framed-User
        Framed-MTU = 1400
        User-Name = "test"
        NAS-Port-Id = "wlan1"
        NAS-Port-Type = Wireless-802.11
        Calling-Station-Id = "6C-AB-31-3D-38-98"
        Called-Station-Id = "64-D1-54-7D-A9-D9:MikroTik-7DA9D9"
        EAP-Message = 0x020000090174657374
        Message-Authenticator = 0x2e179e238a58a9f261ee1fa8b2f64a11
        NAS-Identifier = "MikroTik"
        NAS-IP-Address = 10.24.1.20
[sql]   expand: SELECT id, username, attribute, value, op           FROM radcheck           WHERE username = '%{SQL-User-Name}' and nasip = '%{NAS-IP-Address}'          ORDER BY id -> SELECT id, username, attribute, value, op           FROM radcheck           WHERE username = 'test' and nasip = '10.24.1.20'          ORDER BY id

and here is no NAS-IP:

rad_recv: Access-Request packet from host 10.24.1.20 port 43157, id=239, length=253
        Service-Type = Framed-User
        Framed-MTU = 1400
        User-Name = "test"
        State = 0x23325c762522459e3575f837286e8063
        NAS-Port-Id = "wlan1"
        NAS-Port-Type = Wireless-802.11
        Calling-Station-Id = "6C-AB-31-3D-38-98"
        Called-Station-Id = "64-D1-54-7D-A9-D9:MikroTik-7DA9D9"
        EAP-Message = 
0x0210005e190017030300533736782a7ad7f2c77b8dc2783deef16d11a872edbf7d754ad460f78f12a7c23abb2126d0b8cb138cd5981036c383218b2e1dcc4551b8971f58c9
a40dd0f05b5cf18aa7483293f0c6d8283b94c304a83e3e82b0
        Message-Authenticator = 0xf342eab2f115f1f5a20a2b7068683611
        NAS-Identifier = "MikroTik"
        NAS-IP-Address = 10.24.1.20
[sql]   expand: SELECT id, username, attribute, value, op           FROM radcheck           WHERE username = '%{SQL-User-Name}' and nasip = '%{NAS-IP-Address}'          ORDER BY id -> SELECT id, username, attribute, value, op           FROM radcheck           WHERE username = 'test' and nasip = ''          ORDER BY id

this is the same request but different iterations

This is not problem for me, because i found workaround like this:
	authorize_check_query = "SELECT id, username, attribute, value, op \
          FROM ${authcheck_table} \
          WHERE username = '%{SQL-User-Name}' and (nasip = '%{NAS-IP-Address}' or nasip1 = '%{NAS-IP-Address}') \
          ORDER BY id"

but i think, you should know about this issue.

**Comment by arr2036** [comment]
FreeRADIUS 2.2.8 is no longer supported, upgrade to 3.0.16.
