### ISSUE TITLE
LDAP SHA512 Base64 ApacheDS

### ISSUE THREAD

**Issue by TobiasLogiline** [FreeRADIUS/freeradius-server#2174]
I am trying to connect FreeRADIUS Version 3.0.15 with ApacheDS LDAP Server. The Password is SHA512 encoded.

I get this error using TTLS/PAP:
pap: "known good" digest length (90) does not match output length of any SHA-2 digests

Before i can see this:

pap: Converted: &control:Password-With-Header = '{SHA512}+PnyObpTopB6TrrFEjUwz7w3GvM3GlK8aDmPcOowacgh9JFjJUtNCxoQBSNYPGmA92Y8iFWCFUh/  /qVJzhOKpA==' -> &control:SHA2-Password = '0x2b506e794f6270546f70423654727246456a55777a37773347764d33476c4b3861446d50634f6f7761636768394a466a4a55744e43786f5142534e5950476d4139325938694657434655682f0d0a2f71564a7a684f4b70413d3d'

The Password seems not to be Base64 decoded. The normalize option is set to yes. It seems like, if there are quotings in the Base64 string, the base64 detection fails, because of the length check.

**Comment by alandekok** [comment]
`'{SHA512}+PnyObpTopB6TrrFEjUwz7w3GvM3GlK8aDmPcOowacgh9JFjJUtNCxoQBSNYPGmA92Y8iFWCFUh/ /qVJzhOKpA==`

What is that format?  It's not hex.  It does look to be base64 decoded.

How was it created?  What tool did you use?

**Comment by arr2036** [comment]
Yeah except base64 doesn't include spaces ``Uh/ /qV``

**Comment by arr2036** [comment]
So that's the issue, removing the space creates a valid base64 string which decodes to ``F8F9F239BA53A2907A4EBAC5123530CFBC371AF3371A52BC68398F70EA3069C821F49163254B4D0B1A100523583C6980F7663C88558215487FFEA549CE138AA4``

...which is 64 bytes and correct.  The hex output is the original Base64 string sans header.

What's happened is the base64/hex heuristic didn't mark the string up for decoding because it wasn't a valid base64 string, and just copied everything after the header into the SHA2-Password attribute.

**Comment by arr2036** [comment]
We question is whether the original string in the LDAP directory had that space, or whether it was added internally due to some misapplied escaping.

**Comment by TobiasLogiline** [comment]
The spaces were not inside Apache Directory Studio. But possible that ApacheDS transfers the datas incorrect. ApacheDS is a little bit buggy ;) I not have the problem with any other LDAP user. So changing the password helps.

**Comment by arr2036** [comment]
Yeah right, you'd probably only see it with that specific base64 sequence *sigh*.  If you can figure out whether the space was added by apache or not, then we could look into it, otherwise the vast majority of xlat string expansion issues will be fixed in v4.

**Comment by arr2036** [comment]
and generally have been, so closing this issue
