### ISSUE TITLE
radiusReplyMessage attribute from LDAP is not xlat'ed

### ISSUE THREAD

**Issue by lsenecaux** [FreeRADIUS/freeradius-server#2176]
I try to get reply message from ldap directory.
The attribute is correctly returned, but it is not xlat'ed.

In my ldap module file, I have:
```
update {
                [...]
                control:NT-Password             := 'sambaNTPassword'
                reply:Reply-Message           += "radiusReplyMessage"
                reply:Tunnel-Type               := 'radiusTunnelType'
                reply:Tunnel-Medium-Type        := 'radiusTunnelMediumType'
                reply:Tunnel-Private-Group-ID   := 'radiusTunnelPrivategroupId'
                [...]
```

In my ldap server, I have:
```
dn: cn=staff,cn=radius,dc=example,dc=com
objectClass: radiusObjectProfile
objectClass: radiusprofile
objectClass: top
radiusReplyMessage: %{User-Name} is allowed to connect to wireless network
```

I use FreeRadius 3.0.16.
Thanks

**Comment by herwinw** [comment]
I don't think that is a bug, just blindly passing data from every external source through xlat would open a can full of information disclosure issues. `rlm_rest` has an option `do_xlat` to mark fields as having to be xlatted, but that is not really a suitable interface to use within LDAP.

I think the best option here would to have an eval/xlat/expand xlat method, so you could manually mark a return value as having to pass through xlat, like this:

```
update {
  &reply:Reply-Message = "%{eval:reply:Reply-Message}"
}
```

I don't think an xlat method like that exists, at least I couldn't find anything.

**Comment by arr2036** [comment]
It's called ``%{xlat:}`` it's in v4, you're welcome to send a pull request if you want it backported.  And no this is not a bug.  Double quotes around an attribute name would make the dynamic name itself an expansion.
