### ISSUE TITLE
mod_detail header not parsing \n

### ISSUE THREAD

**Issue by hannibal87** [FreeRADIUS/freeradius-server#2178]
When customizing the header in modules-enabled/detail.log the control characters won't getting parsed when "correct_escapes = true"
The header looks like:

Tue Jan 30 23:32:35 2018\n\tfor:User-Name = BOB\n\tto:NAS-IP =1.2.3.4\n\tdelivered-reply-items:
 
Header Config line:
        header = "%t\n\tfor:User-Name = %{User-Name}\n\tto:NAS-IP = %{NAS-IP-Address}\n\tdelivered-reply-items:"

When I change correct_escapes to  "correct_escapes = false" the header will be parsed as whished and the corresponding newlines are in the logfile

Freeradius-Version: 3.0.13

**Comment by alandekok** [comment]
You need to use two backslashes.

**Comment by hannibal87** [comment]
This doesn't fix it:
Header Config:
header = "%t\\n\\tfor:User-Name = %{User-Name}\\n\\tto:NAS-IP = %{NAS-IP-Address}\\n\\tdelivered-reply-items:"

correct_escapes=true

Result no newlines:
Tue Feb  6 09:51:35 2018\\n\\tfor:User-Name =BOB\\n\\tto:NAS-IP = 1.2.3.4\\n\\tdelivered-reply-items:
