### ISSUE TITLE
Endless recursive call in log.c [fr_syserror]

### ISSUE THREAD

**Issue by dscvejl** [FreeRADIUS/freeradius-server#2201]
# Endless recursive call in log.c fr_syserror in branch 3.0.x

https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/lib/log.c

The fr_syserror is call it self in case of an error:

char const *fr_syserror(int num)
{
....
		ret = fr_thread_local_set(fr_syserror_buffer, buffer);
		if (ret != 0) {
			fr_perror("Failed setting up TLS for system error buffer: %s", fr_syserror(ret)); 
...
}

**Comment by arr2036** [comment]
I do wonder if you ever actually saw this.  It's exceedingly unlikely that setting a thread local variable would ever fail.

**Comment by alandekok** [comment]
I don't think this was an issue (or ever will be).  But out of general principle, sure, we can change it.

**Comment by arr2036** [comment]
Yeah it was already fixed in v4

**Comment by dscvejl** [comment]
Thanks for having a look at the issue  :+1:
