### ISSUE TITLE
Provide environmental variable for setting path to config directory

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#2213]
For customers who have the raddb dir in a non-standard location, it'd be good to read in the default value from environmental variables so it doesn't need to be passed on the command line to utilities like radmin.

Something like ``RADDB_DIR`` or ``RADDB_PATH``?

**Comment by alandekok** [comment]
Maybe `FREERADIUS_DIR` to make it clear that it's for FreeRADIUS?

**Comment by arr2036** [comment]
FREERADIUS_CONF_DIR? FREERADIUS_DICT_DIR is used in radperf.
