### ISSUE TITLE
PAM missing in FreeRadius 3 w/ Debian 9

### ISSUE THREAD

**Issue by servernemesis** [FreeRADIUS/freeradius-server#2217]
Hello, 

I just installed FreeRadius 3.0.12 on Stretch in order to provide a Google Authenticator gateway (https://www.techdrabble.com/citrix/14-2factor-with-google-authenticator-and-netscaler), but I'm unable to start the FreeRadius service, here is the debug log :

Apr 23 11:22:34 2018 : Error: /etc/freeradius/3.0/sites-enabled/default[489]: Failed to find "pam" as a module or policy.
Mon Apr 23 11:22:34 2018 : Error: /etc/freeradius/3.0/sites-enabled/default[489]: Please verify that the configuration exists in /etc/freeradius/3.0/mods-enabled/pam.
Mon Apr 23 11:22:34 2018 : Error: /etc/freeradius/3.0/sites-enabled/default[452]: Errors parsing authenticate section. 

Of course there is no "/etc/freeradius/3.0/mods-enabled/pam"

Someone had the same problem with Ubuntu 17.10 and FreeRadius 3 before reverting to an older version (https://enterpriseadmins.org/blog/virtualization/build-your-own-two-factor-authentication-server/)

Regards

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
