### ISSUE TITLE
FreeRadius 4 rlm_sql and rlm_pam Default Issue

### ISSUE THREAD

**Issue by jpt** [FreeRADIUS/freeradius-server#2220]
# Issue type
- [ ] Defect - Crash or memory corruption.
- [x] Defect - Non compliance with a standards document, or incorrect API usage.
- [ ] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect/Feature description
## How to reproduce issue

Compile and install FreeRADIUS on Ubuntu 16 from source with the following packages:

build-essential libtalloc-dev libkqueue-dev libssl-dev libpam0g-dev libmysqlclient-dev
 
Enable SQL for accouting. FreeRADIUS will break on any attempted connection that uses PAP authentication:

## Output of ``[radiusd|freeradius] -X`` showing issue occurring
(you may need to run ``[radiusd|freeradius] -fxx -l stdout`` if using eg RADIUS with TLS)
*REMOVE SECTION IF FEATURE REQUEST*

```text

(0)    sql (ok)
(0)    expiration (noop)
(0)    logintime (noop)
(0)    pap (updated)
(0)  } # recv Access-Request (updated)
(0)  ERROR: No 'authenticate PAP' section found: rejecting the user

```

This is an issue due to capitalization and one solution is a simple change to `raddb/sites-available/deafault`

Replace:

```
authenticate pap {
        pap
}
```

with:

```
authenticate PAP {
        pap
}
```

However this to me seems like an issue with the software interpreting the default config file, and not the config file itself, so maybe a PR to `sites-available/default` with that replacement would be unhelpful?

Let me know how I can help,
Jeremy

**Comment by jpt** [comment]
@arr2036 Just recompiled and actually the same issue is coming up. If the config isn't changed to `authenticate PAP` from `authenticate pap` it still says `(0)  ERROR: No 'authenticate PAP' section found: rejecting the user`

**Comment by alandekok** [comment]
Are you sure you're starting with the default configuration?  It's been `authenticate pap` for almost a year.  It works for me, for the travis tests, and for everywhere else it's been installed.

I suspect you have a local configuration which sets `Auth-Type := PAP`, and that causes the problem.

**Comment by alandekok** [comment]
If I have `authenticate pap`, and manually set `Auth-Type := PAP`, it works for me.  The debug output shows:


```
(2)    update control {
(2)      Auth-Type := pap
(2)    } # update control (noop)
(2)  } # recv Access-Request (ok)
(2)  Running 'authenticate pap' from file ./raddb/sites-enabled/default
(2)  authenticate pap {
(2)    pap - Login attempt with password
(2)    pap - Comparing with "known good" Cleartext-Password
(2)    pap - User authenticated successfully
(2)    pap (ok)
(2)  } # authenticate pap (ok)
```

Even when the configuration says `Auth-Type := PAP`.

So you're not running the latest v4.0.x head.  Or, something else weird is going on.

Check that you're running v4.0.x.

**Comment by arr2036** [comment]
> On 27 Apr 2018, at 00:17, Alan DeKok <notifications@github.com> wrote:
> 
> Are you sure you're starting with the default configuration? It's been authenticate pap for almost a year. It works for me, for the travis tests, and for everywhere else it's been installed.
> 
> I suspect you have a local configuration which sets Auth-Type := PAP, and that causes the problem.
> 
I’m suspicious that it’s an old dictionary entry or something like that, I don’t think we allow creation of enum values during pass2?  So that alias must have been created by parsing a dictionary or by being registered by a module.

**Comment by jpt** [comment]
@alandekok The source was obtained from this repo, the output from `radiusd -v` is:

`Info  : radiusd: DEVELOPER BUILD - FreeRADIUS version 4.0.0-14236 (git #6d9f5ab), for host x86_64-unknown-linux-gnu, built on Apr 26 2018 at 05:37:32`

One small thing I noticed is that `inner-tunnel` and `default` have different opinions on the capitalization of `pap` by default, not sure if that could have anything to do with it.

**Comment by arr2036** [comment]
Ah, yep, that's going to be it.  When the inner tunnel is parsed it'll add the enum with an upper case value, and because every other check is case insensitive it won't be added with the lower case variant. The problem here is that section lookups are case sensitive, i'm not really convinced they should be but there'd need to be consensus from @alandekok to change that, so for now i'll just change the case in the inner-tunnel, and if you change it to lowercase PAP all should be well.

The changes in ``rlm_pap`` were necessary anyway, so no effort wasted at least.

**Comment by jpt** [comment]
Glad to hear it, those changes didn't look trivial. Thank you both for taking care of the issue!
