### ISSUE TITLE
v4 rlm_sql group_attribute not expanding properly

### ISSUE THREAD

**Issue by jpt** [FreeRADIUS/freeradius-server#2221]
# Issue type
- [ ] Defect - Crash or memory corruption.
- [ ] Defect - Non compliance with a standards document, or incorrect API usage.
- [x] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect/Feature description
## How to reproduce issue

Compile, set up rlm_sql, run radius. 
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

```text
/usr/local/etc/raddb/mods-config/sql/main/mysql/queries.conf[128]: Failed parsing expansion string:
/usr/local/etc/raddb/mods-config/sql/main/mysql/queries.conf[128]: ...M radgroupcheck WHERE groupname = '%{sql-sql-Group}' ORDER BY id
/usr/local/etc/raddb/mods-config/sql/main/mysql/queries.conf[128]:      
```

This is fixable by changing `mods-available/default`, replacing `group_attribute = "${.:instance}-${.:name}-Group"` with `group_attribute = "SQL-Group"` but I do not believe this is intended default behavior.

Let me know if I can be of any assistance

Cheers
Jeremy

**Comment by arr2036** [comment]
Yeah the ``${.:name}`` is unnecessary I'll go fix that
