### ISSUE TITLE
Error when launching radius v3 in debug mode

### ISSUE THREAD

**Issue by EvergreenGOD** [FreeRADIUS/freeradius-server#2222]
# Issue type
- [ ] Defect - Unexpected behaviour (obvious or verified by project member).

# Defect/Feature description
## How to reproduce issue
Hello everybody.
I had to upgrade my FreeRadius from the Version 2.2.5 to the third one.
for this, I used [this tutorial](http://blog.deadcode.net/build-freeradius-3-on-raspberry-pi/)

The problem is that when I try to launch my radius in debugging mode, it can not start because of a strange issue..
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring
Here is the result of the radiusd -X command line :+1: 

```text
root@raspberrypi:/home/pi# /etc/freeradius3/sbin/radiusd -X
FreeRADIUS Version 3.0.16
Copyright (C) 1999-2017 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
Starting - reading configuration files ...
including dictionary file /etc/freeradius3/share/freeradius/dictionary
including dictionary file /etc/freeradius3/share/freeradius/dictionary.dhcp
including dictionary file /etc/freeradius3/share/freeradius/dictionary.vqp
including dictionary file /etc/freeradius3/etc/raddb/dictionary
including configuration file /etc/freeradius3/etc/raddb/radiusd.conf
including configuration file /etc/freeradius3/etc/raddb/proxy.conf
including configuration file /etc/freeradius3/etc/raddb/clients.conf
including files in directory /etc/freeradius3/etc/raddb/mods-enabled/
including configuration file /etc/freeradius3/etc/raddb/mods-enabled/unbound
including configuration file /etc/freeradius3/etc/raddb/mods-enabled/README.rst
/etc/freeradius3/etc/raddb/mods-enabled/README.rst[1]: Expecting section start brace '{' after "Modules in"
Errors reading or parsing /etc/freeradius3/etc/raddb/radiusd.conf
```

I tried to had the section start brace in the file README.rst but after that, the ClI told me that another '{' was expected in another place of the same file..

Does one of you know this problem and how to fix it?
Thanks in advance

**Comment by arr2036** [comment]
You've symlinked everything in mods-available to mods-enabled, including the documentation (``README.rst``), remove the symlink to README.rst from mods-enabled.
