### ISSUE TITLE
raddb/certs/bootstrap creates server-unreadable key files in absence of make

### ISSUE THREAD

**Issue by mzabaluev** [FreeRADIUS/freeradius-server#2223]
# Issue type
- [ ] Defect - Crash or memory corruption.
- [ ] Defect - Non compliance with a standards document, or incorrect API usage.
- [x] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect/Feature description
## How to reproduce issue

Run the bootstrap script in an environment that does not have make (e.g. a container).

With Docker, this should be reproducible by building an image from this Dockerfile:

```
FROM registry.fedoraproject.org/fedora:28

RUN dnf -y install freeradius && dnf clean all
```

Then try to run radiusd in the same environment.

## Output of ``[radiusd|freeradius] -X`` showing issue occurring

```text
tls: Failed reading certificate file "/etc/raddb/certs/server.pem"
tls: error:0200100D:system library:fopen:Permission denied
tls: error:20074002:BIO routines:file_ctrl:system lib
tls: error:140DC002:SSL routines:use_certificate_chain_file:system lib
rlm_eap_tls: Failed initializing SSL context
rlm_eap (EAP): Failed to initialise rlm_eap_tls
/etc/raddb/mods-enabled/eap[14]: Instantiation failed for module "eap"
```

## Probable cause

~The bootstrap script [sets umask 027](https://github.com/FreeRADIUS/freeradius-server/blob/42b2e584b012dadf64926ab2f350ea9481664ed3/raddb/certs/bootstrap#L13) before generating the files.~ When there is a workable make to delegate the work to, the Makefile actions take care to set usable permissions.

**Comment by mzabaluev** [comment]
Actually, the umask is correct, it's likely the newly tightened openssl tool behavior.

**Comment by alandekok** [comment]
What permissions does OpenSSL set?

**Comment by mzabaluev** [comment]
> What permissions does OpenSSL set?

In Fedora 28, it appears to set 0600 for private keys and similar, and 0640 for public certificates.

**Comment by alandekok** [comment]
OK, the issue is that for security, the config files are owned by `root`, but readable by the `radiusd` user.  OpenSSL also wants to be secure, so it makes the "secret" data readable only by the current user.

The short solution is to just `chmod` them after the files have been created.

We can fix the scripts on our end, but there's likely work to do on the RedHat packages, too.  Please also file a bug report with them and reference this one.

**Comment by alandekok** [comment]
See also commit 29add135, which fixed this.  At this point, there's nothing more to do on our end.

Fedora has to update it's docker images to not be broken.

**Comment by dozo2** [comment]
HI ! please help me i 've this in my freeradius output 

tls: Failed reading certificate file "/etc/freeradius/3.0/certs/server@gmail.com-cert.pem"
tls: error:0200100D:system library:fopen:Permission denied
tls: error:20074002:BIO routines:file_ctrl:system lib
tls: error:140DC002:SSL routines:use_certificate_chain_file:system lib
rlm_eap_tls: Failed initializing SSL context
rlm_eap (EAP): Failed to initialise rlm_eap_tls
/etc/freeradius/3.0/mods-enabled/eap[14]: Instantiation failed for module "eap"

**Comment by mcnewton** [comment]
@dozo2 questions belong on the freeradius-users mailing list. Your certificate file permissions are set incorrectly, as the error says.
