### ISSUE TITLE
Issue in compiling V3.3.x with mysql

### ISSUE THREAD

**Issue by faizatahir94** [FreeRADIUS/freeradius-server#2235]
# Issue type
- Error while compiling v3.0.x with mysql
***
- Defect - Error while compiling the code with mysql module

# Defect/Feature description
## 
I am compililng freeradius v3.0.x with mysql. The code has been compiled and the setup for mysql has been made and so is the necessary configurations. Upon running radiusd -X , however I get the following error after creating a symbolic link.

**Comment by arr2036** [comment]
https://freeradius.org/support/
