### ISSUE TITLE
We should use UPSERT for accounting to Postgresql

### ISSUE THREAD

**Issue by alandekok** [FreeRADIUS/freeradius-server#2244]
We currently have the config do manual `UPDATE`, and if that fails, do `INSERT`.

PostgreSQL 9.3 and later supports `UPSERT`: https://www.postgresql.org/docs/current/static/sql-insert.html

The default configuration should be updated to use this.

For v3, the `UPSERT` should be commented out by default.

For v4, the `UPSERT` should be the default configuration.  And the old-style `INSERT` / `UPDATE` should be commented out by default.

`UPSERT` can likely increase performance in high load situations.

**Comment by arr2036** [comment]
> We currently have the config do manual UPDATE, and if that fails, do INSERT.
> 
> PostgreSQL 9.3 and later supports UPSERT: https://www.postgresql.org/docs/current/static/sql-insert.html
> 
Yeah I thought this was new(ish). You used to have to use a stored procedure with a loop. If you wanted to do this server side.
> The default configuration should be updated to use this.
> 
> For v3, the UPSERT should be commented out by default.
> 
> For v4, the UPSERT should be the default configuration. And the old-style INSERT / UPDATE should be commented out by default.
> 
> UPSERT can likely increase performance in high load situations.
> 
Agreed.

-Arran

**Comment by arr2036** [comment]
I believe this is now done, so closing this issue.
