### ISSUE TITLE
[3.0.x] build error - tls.c - TLS1_2_VERSION / TLS1_1_VERSION not defined

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#2247]
# Issue type

- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect
## How to reproduce the issue

Try to build FreeRADIUS (3.0.17 or 3.0.x HEAD) with TLS1_2_VERSION and TLS1_1_VERSION  not defined.

Output:

CC src/main/tls.c
src/main/tls.c: In function ‘tls_init_ctx’:
src/main/tls.c:2989: error: ‘TLS1_2_VERSION’ undeclared (first use in this function)
src/main/tls.c:2989: error: (Each undeclared identifier is reported only once
src/main/tls.c:2989: error: for each function it appears in.)
src/main/tls.c:2992: error: ‘TLS1_1_VERSION’ undeclared (first use in this function)
At top level:
cc1: warning: unrecognized command line option "-Wno-date-time"

**Comment by arr2036** [comment]
You're using an ancient version of OpenSSL?

**Comment by nchaigne** [comment]
Quite ancient yes (version is: 1.0.0-27.el6_4.2 from 2013).
