### ISSUE TITLE
Error getting check attributes

### ISSUE THREAD

**Issue by fwilborn** [FreeRADIUS/freeradius-server#2250]
Hallo dear RADIUS community, 

I am getting an error that seemingly should only occur when the result set is less than zero.

(see https://doc.freeradius.org/rlm__sql_8c_source.html 
 1259                 rows = sql_getvpdata(request, inst, request, &handle, &check_tmp, expanded);
 1260                 TALLOC_FREE(expanded);
 1261                 if (rows < 0) {
 1262                         REDEBUG("**Error getting check attributes**");
 1263                         rcode = RLM_MODULE_FAIL;
 1264                         goto error;
 1265                 }
)

The error occurs following a modified "authorize_check_query": (active added as a kind of state )
...
rlm_sql (sql1): Reserved connection (2)
(2) sql1: EXPAND SELECT id, username, attribute, value, op FROM radcheck WHERE username = '%{SQL-User-Name}' AND active < '3' ORDER BY id ASC
(2) sql1:    --> SELECT id, username, attribute, value, op FROM radcheck WHERE username = '000bcd97xxxx' AND active < '3' ORDER BY id ASC
(2) sql1: Executing select query: SELECT id, username, attribute, value, op FROM radcheck WHERE username = '000bcd97xxxx' AND active < '3' ORDER BY id ASC
(2) sql1: ERROR: **Unknown error**
(2) sql1: ERROR: **Error getting check attributes**
rlm_sql (sql1): Released connection (2)
(2)       [sql1] = fail
...

The user exists on both servers (redundancy), so the result set should always be greater than zero.

I am running freeradius 3.0.17 built from tarball on and for suse (openSUSE 15.0)
Both SQL servers are of the MySQL flavor.

When queried from the radserv manually using the login set up for radius_user (plus "USE radius;") they deliver results as expected.. i.e. for the e.g. above:

nac-rad3:/usr/local/etc/raddb # mysql -h172.16.255.*** -uradius_user -p -e"USE radius; SELECT id, username, attribute, value, op FROM radcheck WHERE username = '000bcd97xxxx' AND active < '3' ORDER BY id ASC;"
Enter password: ******
+------+--------------+--------------------+--------------+----+
| id   | username     | attribute          | value        | op |
+------+--------------+--------------------+--------------+----+
| 7369 | 000bcd97xxxx | Cleartext-Password | 000bcd97xxxx | := |
+------+--------------+--------------------+--------------+----+
nac-rad3:/usr/local/etc/raddb #  

Any ideas? How to approach this?

Thanks, 
Felix

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
