### ISSUE TITLE
Acess reject dropped by freeradius 2.2.1

### ISSUE THREAD

**Issue by shobana2** [FreeRADIUS/freeradius-server#2263]
Hi,
        My problem is i am not getting Access-Reject from freeradius to
jradius.

        When i give correct credentials for a user authentication i am
correctly getting Access-Accept packet from freeradius to jradius.

        But when i give correct credentials for a user authentication i am
not getting Access-Reject packet from freeradius to jradius, even though
reject packet has come from the ground.

 Is there some configuration for freeradius to send access reject
packets to jradius?

          Please help me with this.

**Comment by mcnewton** [comment]
Questions belong on the freeradius-users list.
https://freeradius.org/support/
http://wiki.freeradius.org/list-help
