### ISSUE TITLE
Use different User files in eap authentication

### ISSUE THREAD

**Issue by cph1c06** [FreeRADIUS/freeradius-server#2265]
I would like to create two virtual servers to authenticate users for different services, e.g., wifi and vpn.
The servers for wifi authentication listens to port 1812.
The servers for vpn authentication listens to port 1822.

However, I got difficulties in configuring the inner-tunnel services as it is responsible for eap communication.

Can anyone share any insight?

Thanks a lot!

**Comment by arr2036** [comment]
https://freeradius.org/support/
