### ISSUE TITLE
Rlm_perl RAD_REQUEST_PROXY_REPLY replaces has_tag - FreeRADIUS  v2.2.2

### ISSUE THREAD

**Issue by Djo91** [FreeRADIUS/freeradius-server#2266]
Hi, sorry for my english, i'm French :).

I use perl module to my freeradius proxy server.
A Freeradius server send me correctly attributes with has_tag, example : 
Tunnel-Server-Endpoint:2 = "172.16.X.X"
Tunnel-Assignment-Id:2 = "Secours"
Tunnel-Medium-Type:2 = IPv4
Tunnel-Type:2 = L2TP
Tunnel-Preference:2 = 200
Tunnel-Assignment-Id:0 = "l2tp-lab"
Tunnel-Server-Endpoint:1 = "172.16.Y.Y"
Tunnel-Assignment-Id:1 = "Nominal"
Tunnel-Medium-Type:1 = IPv4
Tunnel-Type:1 = L2TP
Tunnel-Preference:1 = 100

When i use $RAD_REQUEST_PROXY_REPLY to add attributes like Alc-SLA-Prof-Str, the server rewrites the has_tag of all attributes.

Code : 
        $RAD_REQUEST_PROXY_REPLY{'Alc-SLA-Prof-Str'} = $sla;
        $RAD_REQUEST_PROXY_REPLY{'Alc-Subsc-Prof-Str'} = $sub;

Proxy reply : 
Tunnel-Server-Endpoint:0 += "172.16.X.X"
Tunnel-Server-Endpoint:0 += "172.16.Y.Y"
Tunnel-Type:0 += L2TP
Tunnel-Type:0 += L2TP
Tunnel-Medium-Type:0 += IPv4
Tunnel-Medium-Type:0 += IPv4
Tunnel-Preference:0 += 200
Tunnel-Preference:0 += 100
Tunnel-Assignment-Id:0 += "Secours"
Tunnel-Assignment-Id:0 += "l2tp-lab"
Tunnel-Assignment-Id:0 += "Nominal"
Alc-SLA-Prof-Str = "FTTHGP-SLA3"
Alc-Subsc-Prof-Str = "GP-1000M-300M"

Is it caused by Freeradius version or a bad use of RAD_REQUEST_PROXY_REPLY ?

**Comment by alandekok** [comment]
Install 2.2.10.

**Comment by Djo91** [comment]
Thx for your reply. I'll install 2.2.10 and give you a feedback

**Comment by Djo91** [comment]
It works perfectly on 3.0.17. Thx a lot
