### ISSUE TITLE
Freeradius Functionality

### ISSUE THREAD

**Issue by hiranuk** [FreeRADIUS/freeradius-server#2267]
Hi
Let me explain what i am trying to achieve.

I have a number of Draytek 2862Ln model firewall routers in various shops up and down the country. I want to configure a guest wifi on all those routers. the Draytek Routers has an option for "captive portal" and "MAC authentication". The idea is if a customer goes to 1 shop and connects to the guest wifi on the draytek they will see a splash screen asking them to login using facebook or google and then they will have internet access.

If they then went to another shop they would simply connect to the guest wifi and have internet access they would not need to enter their facebook or google details again as their MAC address of their wireless client will have been captured by freeradius when they previously connected at the other shop.

I have attached screenshots of the Draytek Web GUI. Can anyone tell me if freeradius will allow me to do this or do i need something else?.

![2018-07-26 16_39_18-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43332046-0e995dc4-91bf-11e8-8d8c-a481c64f9790.png)
![2018-07-26 16_39_36-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43332048-10253eb0-91bf-11e8-966d-c6e743cfde55.png)
![2018-07-26 16_39_49-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43332050-11d1698c-91bf-11e8-812d-32b7c5dc75c3.png)
![2018-07-26 16_40_15-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43332051-13f0a34a-91bf-11e8-8b37-be60874edbc5.png)
![2018-07-26 16_40_43-emisnet-hiran vigor2862 series](https://user-images.githubusercontent.com/41695279/43332053-15a48f80-91bf-11e8-8294-844c78fe1b73.png)

Thanks in advance.

Hiran

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
