### ISSUE TITLE
Incorrect type for MIP6-Home-Link-Prefix

### ISSUE THREAD

**Issue by herwinw** [FreeRADIUS/freeradius-server#2269]
# Issue type
- Defect - Non compliance with a standards document, or incorrect API usage.

# Defect/Feature description

The dictionaries list `MIP6-Home-Link-Prefix` as type `ipv6prefix`, just as e.g. `Framed-IPv6-Prefix`. However, there is a subtle difference in the RFCs here.

[`Framed-IPv6-Prefix`](https://tools.ietf.org/html/rfc3162#section-2.3) has a payload of 1 reserved bytes (always 0x00), 1 byte for prefix-length (range 0x00-0x7f) and 0-16 bytes for the address (bytes outside the address mask may be omitted).
[`MIP6-Home-Link-Prefix`](https://tools.ietf.org/html/rfc5447#section-4.2.4) does not have the reserved byte, and always uses 16 bytes for the address.

**Comment by arr2036** [comment]
Wow.  That's just garbage.

**Comment by herwinw** [comment]
Well, wireshark uses the ipv6prefix-format for this attribute as well, so I guess most of the world has got it wrong. Not really surprising

**Comment by alandekok** [comment]
Wireshark copies the FreeRADIUS dictionaries. :(

**Comment by guyharris** [comment]
> Wireshark copies the FreeRADIUS dictionaries.

    $ wc -l radius/dictionary.* | tail -1
       23669 total

The alternative would be worse.

As noted above, Wireshark's picked up the change, and it's been backported to the Wireshark 2.6, 2.4, and 2.2 branches, so the next 2.6.x, 2.4.x, and 2.2.x releases should have the fix.

**Comment by alandekok** [comment]
> On Aug 3, 2018, at 12:38 AM, Guy Harris <notifications@github.com> wrote:
> 
> Wireshark copies the FreeRADIUS dictionaries.

  Yup.  My unhappy face was not about the copying, but about the propagation of the error.

> $ wc -l radius/dictionary.* | tail -1
>    23669 total
> 
> The alternative would be worse.
> 
> As noted above, Wireshark's picked up the change, and it's been backported to the Wireshark 2.6, 2.4, and 2.2 branches, so the next 2.6.x, 2.4.x, and 2.2.x releases should have the fix.

  Thanks.

  Some other projects copy the FR dictionaries, make local changes, and then never send the changes back.  That behaviour should be discouraged.

**Comment by infrastation** [comment]
Besides that, RFC 5447 defines MIP6-Feature-Vector as Unsigned64, not OctetString. Both attributes from RFC 5447 have incorrect types in the registry (already reported).

**Comment by alandekok** [comment]
I've pushed a fix for MIP6-Feature-Vector

**Comment by infrastation** [comment]
Thank you!

**Comment by herwinw** [comment]
Notify to @guyharris You might want to import that change in Wireshark as well

**Comment by guyharris** [comment]
> I've pushed a fix for MIP6-Feature-Vector

It doesn't appear to have shown up in https://github.com/FreeRADIUS/freeradius-server.git yet.

**Comment by herwinw** [comment]
> It doesn't appear to have shown up in https://github.com/FreeRADIUS/freeradius-server.git yet.

It is available in the 3.0-branch

https://github.com/FreeRADIUS/freeradius-server/commit/e4f385f5db3b415c0d10d8b1b8de1fc74e36edb5

**Comment by alandekok** [comment]
I've just pushed it to the master branch.

My $0.02 is that wireshark should be grabbing the dictionaries from the v3.0.x branch.  That's stable.

The master branch is being actively developed, and we're re-working much of the architecture.  Including how dictionaries are handled, parsed, and what data types are allowed.

I don't think Wireshark wants to keep updating their code to stay in sync with a moving target.  So the v3.0.x branch is the best choice for now.

**Comment by guyharris** [comment]
> My $0.02 is that wireshark should be grabbing the dictionaries from the v3.0.x branch. That's stable.

OK, I've picked up the dictionary.rfc5447 file from that branch.

> The master branch is being actively developed, and we're re-working much of the architecture. Including how dictionaries are handled, parsed, and what data types are allowed.

So is the syntax of dictionary files changing?

**Comment by arr2036** [comment]
> So is the syntax of dictionary files changing?

It's being extended.

Keywords are being added to specify complex structural attributes, i.e. those containing multiple fixed fields and variable fields.

Keywords are being added to allow "foreign" attributes i.e. DHCP in RADIUS.

Some dictionary files will also be qualified with protocol blocks, specifying global options for the attributes, and indicating which protocol they belong to.

The majority of keywords will be consistent with v3.0.x, but many files will be moved/reorganised.

As of v4.0.x FreeRADIUS is not a RADIUS server, it's a multi-protocol policy server which implements RADIUS.
