### ISSUE TITLE
inbound RADIUS/TLS connection stalls

### ISSUE THREAD

**Issue by pauldekkers** [FreeRADIUS/freeradius-server#2270]
# Issue type
- if I accept inbound RADIUS/TLS requests and send a lot of requests between servers, the connection stalls on the inbound server. In debug mode I notice SSL errors:
```
(0) Failed writing 0 bytes to SSL BIO: -1
(0) Application data status 4
```

This is on Ubuntu 18.04 LTS with FreeRADIUS 3.0.17 from the website (current stable) or the v3.0.x from github.

Problem also occurs with eg. Radiator or radsecproxy proxy'ing towards FreeRADIUS via RADIUS/TLS. Doing the same test towards Radiator or radsecproxy is not problematic.

***

- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect
## How to reproduce the issue

Two instances of FreeRADIUS, v3.0.x on localhost, from github OR 3.0.17 tarball from the website, in /opt/freeradius1 and /opt/freeradius2

just accept auth's right away in /opt/freeradius1/etc/raddb/sites-enabled/default:
```
authorize {
        if (&User-Name == "test2") {
                accept
        }
```

... and enable inbound RADIUS/TLS on the first instance:
```
cat /opt/freeradius1/etc/raddb/sites-enabled/tls
listen {
        ipaddr = *
        port = 2083
        type = auth+acct
        proto = tcp

        clients = radsec

        virtual_server = default

        limit {
                max_connections = 64
                lifetime = 0
                idle_timeout = 300
        }

        tls {
                private_key_file = /opt/localhost.pem
                certificate_file = /opt/localhost.pem
                dh_file = ${certdir}/dh
                random_file = /dev/urandom
                fragment_size = 8192
                ca_file = /opt/localhost.pem
                cipher_list = "DEFAULT"
                require_client_cert = yes
        }
}

listen {
        ipv6addr = ::
        port = 2083
        type = auth+acct
        proto = tcp

        clients = radsec

        virtual_server = default

        limit {
                max_connections = 64
                lifetime = 0
                idle_timeout = 300
        }

        tls {
                private_key_file = /opt/localhost.pem
                certificate_file = /opt/localhost.pem
                dh_file = ${certdir}/dh
                random_file = /dev/urandom
                fragment_size = 8192
                ca_file = /opt/localhost.pem
                cipher_list = "DEFAULT"
                require_client_cert = yes
        }
}

clients radsec {
        client default-4 {
                ipaddr = 0.0.0.0/0
                proto = tls
                secret = radsec
                org = RADSEC
                limit {
                        max_connections = 64
                        lifetime = 0
                        idle_timeout = 300
                }
        }

        client default-6 {
                ipv6addr = ::/0
                proto = tls
                secret = radsec
                org = RADSEC
                limit {
                        max_connections = 64
                        lifetime = 0
                        idle_timeout = 300
                }
        }
}
```

Change default inbound UDP ports on the second instance (/opt/freeradius2/etc/raddb/sites-enabled/default, to port = 1645 instead of port = 0).

Proxy on the second instance to the first, in /opt/freeradius2/etc/raddb/proxy.conf

```
home_server LOCALHOST {
        type = auth+acct
        ipv4addr = 127.0.0.1
        port = 2083
        secret = "radsec"
        proto = tcp
        tls {
                private_key_file = /opt/localhost.pem
                certificate_file = /opt/localhost.pem
                dh_file = ${certdir}/dh
                random_file = /dev/urandom
                fragment_size = 8192
                ca_file = /opt/localhost.pem
                cipher_list = "DEFAULT"
        }
}

home_server LOCALHOST_UDP {
        type = auth+acct
        ipv4addr = 127.0.0.1
        port = 1645
        secret = testing123
}

home_server_pool LOCALHOST {
        home_server = LOCALHOST
}

realm DEFAULT {
        pool = LOCALHOST
        nostrip
}
```

The LOCALHOST_UDP is to verify things work with UDP. (They do.)

Of course a client to test with towards the 2nd instance,

```
client test {
        ipaddr = 0.0.0.0/0
        secret = testing123
}
```

Now run a lot of requests, eg. via EAPTest (from ermitacode.com) in "Performance Test" (>=10 shows it quickly) or "Performance Report".

## Output of ``[radiusd|freeradius] -X`` showing issue occurring

As soon as things start to break, ``/opt/freeradius1/sbin/radiusd -fxx -l LOG`` shows:
```
Waking up in 253.2 seconds.
(0) Failed writing 0 bytes to SSL BIO: -1
(0) Application data status 4
Waking up in 253.2 seconds.
(0) Failed writing 0 bytes to SSL BIO: -1
(0) Application data status 4
Waking up in 253.2 seconds.
(0) Failed writing 0 bytes to SSL BIO: -1
(0) Application data status 4
Waking up in 253.2 seconds.
(0) Failed writing 0 bytes to SSL BIO: -1
(0) Application data status 4
```

## Full backtrace from LLDB or GDB

The process doesn't crash, so far.

**Comment by alandekok** [comment]
Hmm... try this patch.  It's a work-around, but "writing 0 bytes" does seem to be wrong.

**Comment by pauldekkers** [comment]
Ehm. Neither committed nor attached here, is it? ;-)

**Comment by alandekok** [comment]
[patch.gz](https://github.com/FreeRADIUS/freeradius-server/files/2257691/patch.gz)

Attaching via email didn't work.

The patch just skips the SSL write if there's no data to write.

**Comment by pauldekkers** [comment]
Unfortunately, this file looks empty to me!

**Comment by alandekok** [comment]
[patch.gz](https://github.com/FreeRADIUS/freeradius-server/files/2257783/patch.gz)

this might be better?

**Comment by pauldekkers** [comment]
Yes! That fixes things. Thanks for the patch!
