### ISSUE TITLE
nothing in mysql radius database radacct table 

### ISSUE THREAD

**Issue by onejovi** [FreeRADIUS/freeradius-server#2273]
Hi，
    I successd to access radius server and got ip address from my phone，but i can see nothing about the login account status. So I checked the radacct table, I found it's empty。
    
  Software：freeradius-3.0+daloradius-0.9-9.+mysql
 
Daloradius web account testing log 
Executed:
echo User-Name='jis2admin',User-Password='1234abcd' | radclient -c '1' -n '3' -r '3' -t '3' -x '127.0.0.1:1812' 'auth' 'testing123' 2>&1

Results:
Sent Access-Request Id 152 from 0.0.0.0:59751 to 127.0.0.1:1812 length 49
User-Name = "jis2admin"
User-Password = "1234abcd"
Cleartext-Password = "1234abcd"
Received Access-Accept Id 152 from 127.0.0.1:1812 to 0.0.0.0:0 length 20

**Comment by arr2036** [comment]
https://freeradius.org/support/
