### ISSUE TITLE
rlm_cache does not keep the attribute tag

### ISSUE THREAD

**Issue by SS-T** [FreeRADIUS/freeradius-server#2291]
freeRadius Version 3.0.12

== Cache Configure ==
cache testCache {
    driver = "rlm_cache_rbtree"
    key = "%{request:NAS-IP-Address}"
    ttl = 600
    add_stats = no

    update {
        &reply:User-Name                  := &reply:User-Name
        &reply:ERX-Service-Activate       := &reply:ERX-Service-Activate[*]
        &reply:ERX-Local-Loopback-Interface := &reply:ERX-Local-Loopback-Interface
    }
}

== Auth Log ==
0) Using Autz-Type TEST
(0)   Autz-Type TEST {
(0)     update {
(0)       &control:Cache-Read-Only := yes
(0)     } # update = noop
(0) testCache: EXPAND %{request:NAS-IP-Address}
(0) testCache:    --> 1.2.3.4
(0) testCache: No cache entry found for "1.2.3.4"
(0)     [testCache] = notfound
(0)     if ( notfound || fail ) {
(0)     if ( notfound || fail )  -> TRUE
(0)     if ( notfound || fail )  {
(0)       update reply {
(0)         User-Name := 'testingRlmCache'
(0)         ERX-Service-Activate:1 += 'testingAttrWithTag1'
(0)         ERX-Service-Activate:2 += 'testingAttrWithTag2'
(0)         ERX-Local-Loopback-Interface := 'testingAttr'
(0)       } # update reply = noop
(0) testCache: EXPAND %{request:NAS-IP-Address}
(0) testCache:    --> 1.2.3.4
(0) testCache: No cache entry found for "1.2.3.4"
(0) testCache: Creating new cache entry
(0) testCache:   &reply:User-Name := &reply:User-Name -> 'testingRlmCache'
(0) testCache:   &reply:ERX-Service-Activate := &reply:ERX-Service-Activate[*] -> 'testingAttrWithTag1'
(0) testCache:   &reply:ERX-Service-Activate := &reply:ERX-Service-Activate[*] -> 'testingAttrWithTag2'
(0) testCache:   &reply:ERX-Local-Loopback-Interface := &reply:ERX-Local-Loopback-Interface -> 'testingAttr'
(0) testCache: Merging cache entry into request
(0) testCache:   &reply:User-Name := "testingRlmCache"
(0) testCache:   &reply:ERX-Service-Activate := "testingAttrWithTag1"
(0) testCache:   &reply:ERX-Service-Activate := "testingAttrWithTag2"
(0) testCache:   &reply:ERX-Local-Loopback-Interface := "testingAttr"
(0) testCache: Committed entry, TTL 600 seconds
(0)       [testCache] = updated
(0)     } # if ( notfound || fail )  = updated
(0)   } # Autz-Type TEST = updated
(0) Found Auth-Type = TEST
(0)   Auth-Type TEST {
(0)     [ok] = ok
(0)   } # Auth-Type TEST = ok
(0)   post-auth {
(0)   } # post-auth = noop
(0) Login OK: [] (from client localhost port 0)
(0) Sent Access-Accept Id 203 from 127.0.0.1:1812 to 127.0.0.1:57320 length 0
(0)   User-Name = "testingRlmCache"
(0)   ERX-Service-Activate = "testingAttrWithTag1"
(0)   ERX-Service-Activate = "testingAttrWithTag2"
(0)   ERX-Local-Loopback-Interface = "testingAttr"
(0) Finished request

On line 15 & 16 of Auth Log, the reply list was updated with ERX-Service-Activate:1 & ERX-Service-Activate:2, both having a tag.
However, after the Cache merge, the tag info disappeared.

**Comment by alandekok** [comment]
```
update {
    &reply:User-Name                  := &reply:User-Name
    &reply:ERX-Service-Activate       := &reply:ERX-Service-Activate[*]
    &reply:ERX-Local-Loopback-Interface := &reply:ERX-Local-Loopback-Interface
}
```

Note that there's no tag on the LHS of the `update` section.  So you're telling it to create the cache entry *without* the tag.

Change the configuration to include the tag.

**Comment by SS-T** [comment]
having multiple ERX-Service-Activate attributes and tag number may not be fixed, can you please advise how can I specify the tag on LHS?

**Comment by SS-T** [comment]
having multiple ERX-Service-Activate attributes and tag number may not be fixed, can you please advise how can I specify the tag on LHS?
