### ISSUE TITLE
[3.0.17] Unlang - Return reject in post-proxy section but request not rejected

### ISSUE THREAD

**Issue by Djo91** [FreeRADIUS/freeradius-server#2307]
# Issue type
Request not rejected whereas reject code is returned by post-proxy section

# Virtual server post-proxy configuration : 
```
post-proxy {
        # Circuit ID check
	if (&proxy-request:ADSL-Agent-Circuit-Id) {
		update proxy-reply {
			# Set attributes Alc-Subsc-ID-Str & Alc-Retail-Serv-Id with database
			&proxy-reply:Alc-Subsc-ID-Str = "%{sql:SELECT Subscriber_Id FROM `post_proxy` WHERE (Circuit_Id = \"%{&proxy-request:ADSL-Agent-Circuit-Id}\")}"
			&proxy-reply:Alc-Retail-Serv-Id = "%{sql:SELECT Retailer_Service_Id FROM `post_proxy` WHERE (Circuit_Id = \"%{&proxy-request:ADSL-Agent-Circuit-Id}\")}"
		}
	}
	# Test condition to reject (juste for the exemple)
	if (&proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB ") {
		reject
	}
...
        linelog.postproxy_prx-FTTH
}
```

With this configuration, when the if condition : &proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB " is TRUE a reject code is returned by post-proxy section but the request is not rejected as you can see with radiusd -X (process continue to the next section post-auth) : 

# Radiusd -X output : 
```
(0)   post-proxy {
(0)     if (&proxy-request:ADSL-Agent-Circuit-Id) {
(0)     if (&proxy-request:ADSL-Agent-Circuit-Id)  -> TRUE
(0)     if (&proxy-request:ADSL-Agent-Circuit-Id)  {
(0)       update proxy-reply {
(0)         EXPAND DEFAULT
(0)            --> DEFAULT
(0)         SQL-User-Name set to 'DEFAULT'
rlm_sql (sql): Reserved connection (5)
(0)         Executing select query: SELECT Subscriber_Id FROM `post_proxy` WHERE (Circuit_Id = "0x6f6c742d76616c39322d30322070xxxxxxxxxxxxxxxxxxxxxxxx")
rlm_sql (sql): Released connection (5)
(0)         EXPAND %{sql:SELECT Subscriber_Id FROM `post_proxy` WHERE (Circuit_Id = "%{&proxy-request:ADSL-Agent-Circuit-Id}")}
(0)            --> TEST-REJECT-LAB 
(0)         &proxy-reply:Alc-Subsc-ID-Str = TEST-REJECT-LAB 
(0)         EXPAND DEFAULT
(0)            --> DEFAULT
(0)         SQL-User-Name set to 'DEFAULT'
rlm_sql (sql): Reserved connection (6)
(0)         Executing select query: SELECT Retailer_Service_Id FROM `post_proxy` WHERE (Circuit_Id = "0x6f6c742d76616c39322d30322070xxxxxxxxxxxxxxxxxxxxxxxx")
rlm_sql (sql): Released connection (6)
(0)         EXPAND %{sql:SELECT Retailer_Service_Id FROM `post_proxy` WHERE (Circuit_Id = "%{&proxy-request:ADSL-Agent-Circuit-Id}")}
(0)            --> 413
(0)         &proxy-reply:Alc-Retail-Serv-Id = 413
(0)       } # update proxy-reply = noop
(0)       if (!&proxy-reply:Alc-Subsc-ID-Str || !&proxy-reply:Alc-Retail-Serv-Id ){
(0)       if (!&proxy-reply:Alc-Subsc-ID-Str || !&proxy-reply:Alc-Retail-Serv-Id ) -> FALSE
(0)     } # if (&proxy-request:ADSL-Agent-Circuit-Id)  = noop
(0)     if (&proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB ") {
(0)     if (&proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB ")  -> TRUE
(0)     if (&proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB ")  {
(0)       [reject] = reject
(0)     } # if (&proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB ")  = reject
(0)   } # post-proxy = reject
(0) Found Auth-Type = Accept
(0) Auth-Type = Accept, accepting the user
(0) # Executing section post-auth from file /usr/local/etc/raddb/sites-enabled/prx-FTTH-TEST
(0)   post-auth {
(0) attr_filter.post-auth_prx-FTTH-GPON: EXPAND %{Realm}
(0) attr_filter.post-auth_prx-FTTH-GPON:    --> CORI
(0) attr_filter.post-auth_prx-FTTH-GPON: Matched entry CORI at line 17
(0)     [attr_filter.post-auth_prx-FTTH-GPON] = updated
(0) linelog.postauth_prx-FTTH: EXPAND messages.%{%{reply:Packet-Type}:-default}
(0) linelog.postauth_prx-FTTH:    --> messages.Access-Accept
(0) linelog.postauth_prx-FTTH: EXPAND POSTAUTH Login Ok: [%{User-Name}/pwd] %{reply:Alc-Subsc-ID-Str} %{reply:Framed-IP-Address} %{reply:Framed-IP-Netmask} %{reply:Alc-Default-Router} %{reply:Alc-SLA-Prof-Str} %{reply:Alc-Subsc-Prof-Str} %{reply:Alc-Primary-Dns} %{reply:Alc-Secondary-Dns} %{reply:Alc-Retail-Serv-Id}
(0) linelog.postauth_prx-FTTH:    --> POSTAUTH Login Ok: [xx:xx:xx:xx:6b:f7/pwd] TEST-REJECT-LAB         413
(0)     [linelog.postauth_prx-FTTH] = ok
(0)   } # post-auth = updated
(0) Login OK: [xx:xx:xx:xx:6b:f7/pwd] (from client mpe-val port 0)
```
Maybe it's a normal behaviour and I missunderstand something.

Regards,

**Comment by arr2036** [comment]
Mmm, it's probably because Auth-Type Accept has already been set.  The Reject should definitely cause the user to be rejected.

Try adding

```
update control {
	Auth-Type !* ANY
}
```

Just before calling reject.

**Comment by Djo91** [comment]
Thanks for your reply.
Unfortunately it doesn't work.

# New Virtual server configuration

post-proxy {
        # Circuit ID check
	if (&proxy-request:ADSL-Agent-Circuit-Id) {
		update proxy-reply {
			# Set attributes Alc-Subsc-ID-Str & Alc-Retail-Serv-Id with database
			&proxy-reply:Alc-Subsc-ID-Str = "%{sql:SELECT Subscriber_Id FROM `post_proxy` WHERE (Circuit_Id = \"%{&proxy-request:ADSL-Agent-Circuit-Id}\")}"
			&proxy-reply:Alc-Retail-Serv-Id = "%{sql:SELECT Retailer_Service_Id FROM `post_proxy` WHERE (Circuit_Id = \"%{&proxy-request:ADSL-Agent-Circuit-Id}\")}"
		}
	}
	# Test condition to reject (juste for the exemple)
	if (&proxy-reply:Alc-Subsc-ID-Str == "FTTH-CORIOLIS-LAB ") {
		update control {
			Auth-Type !* ANY
		}
		reject
	}
...
        linelog.postproxy_prx-FTTH
}

# Radiusd - X output : 
(0)   post-proxy {
(0)     if (&proxy-request:ADSL-Agent-Circuit-Id) {
(0)     if (&proxy-request:ADSL-Agent-Circuit-Id)  -> TRUE
(0)     if (&proxy-request:ADSL-Agent-Circuit-Id)  {
(0)       update proxy-reply {
(0)         EXPAND DEFAULT
(0)            --> DEFAULT
(0)         SQL-User-Name set to 'DEFAULT'
rlm_sql (sql): Reserved connection (1)
(0)         Executing select query: SELECT Subscriber_Id FROM `post_proxy` WHERE (Circuit_Id = "0x6f6c742d76616c39322dxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
rlm_sql (sql): Released connection (1)
(0)         EXPAND %{sql:SELECT Subscriber_Id FROM `post_proxy` WHERE (Circuit_Id = "%{&proxy-request:ADSL-Agent-Circuit-Id}")}
(0)            --> TEST-REJECT-LAB 
(0)         &proxy-reply:Alc-Subsc-ID-Str = TEST-REJECT-LAB 
(0)         EXPAND DEFAULT
(0)            --> DEFAULT
(0)         SQL-User-Name set to 'DEFAULT'
rlm_sql (sql): Reserved connection (2)
(0)         Executing select query: SELECT Retailer_Service_Id FROM `post_proxy` WHERE (Circuit_Id = "0x6f6c742d76616c393xxxxxxxxxxxxxxxxxxxxxxxxxx")
rlm_sql (sql): Released connection (2)
(0)         EXPAND %{sql:SELECT Retailer_Service_Id FROM `post_proxy` WHERE (Circuit_Id = "%{&proxy-request:ADSL-Agent-Circuit-Id}")}
(0)            --> 413
(0)         &proxy-reply:Alc-Retail-Serv-Id = 413
(0)       } # update proxy-reply = noop
(0)       if (!&proxy-reply:Alc-Subsc-ID-Str || !&proxy-reply:Alc-Retail-Serv-Id ){
(0)       if (!&proxy-reply:Alc-Subsc-ID-Str || !&proxy-reply:Alc-Retail-Serv-Id ) -> FALSE
(0)     } # if (&proxy-request:ADSL-Agent-Circuit-Id)  = noop
(0)     if (&proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB ") {
(0)     if (&proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB ")  -> TRUE
(0)     if (&proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB ")  {
(0)       update control {
(0)         Auth-Type !* ANY
(0)       } # update control = noop
(0)       [reject] = reject
(0)     } # if (&proxy-reply:Alc-Subsc-ID-Str == "TEST-REJECT-LAB ")  = reject
(0)   } # post-proxy = reject
(0) Found Auth-Type = Accept
(0) Auth-Type = Accept, accepting the user
(0) # Executing section post-auth from file /usr/local/etc/raddb/sites-enabled/prx-FTTH-TEST
(0)   post-auth {
(0) attr_filter.post-auth_prx-FTTH-GPON: EXPAND %{Realm}
(0) attr_filter.post-auth_prx-FTTH-GPON:    --> CORI
(0) attr_filter.post-auth_prx-FTTH-GPON: Matched entry CORI at line 17
(0)     [attr_filter.post-auth_prx-FTTH-GPON] = updated
(0) linelog.postauth_prx-FTTH: EXPAND messages.%{%{reply:Packet-Type}:-default}
(0) linelog.postauth_prx-FTTH:    --> messages.Access-Accept
(0) linelog.postauth_prx-FTTH: EXPAND POSTAUTH Login Ok: [%{User-Name}/pwd] %{reply:Alc-Subsc-ID-Str} %{reply:Framed-IP-Address} %{reply:Framed-IP-Netmask} %{reply:Alc-Default-Router} %{reply:Alc-SLA-Prof-Str} %{reply:Alc-Subsc-Prof-Str} %{reply:Alc-Primary-Dns} %{reply:Alc-Secondary-Dns} %{reply:Alc-Retail-Serv-Id}
(0) linelog.postauth_prx-FTTH:    --> POSTAUTH Login Ok: [xx:xx:xx:xx:6b:f7/pwd] TEST-REJECT-LAB        413
(0)     [linelog.postauth_prx-FTTH] = ok
(0)   } # post-auth = updated
(0) Login OK: [xx:xx:xx:xx:6b:f7/pwd] (from client mpe-val port 0)

**Comment by alandekok** [comment]
The server isn't designed to turn an accept into a reject, much like it's not designed to turn a reject into an accept.

You can do these checks in the `post_auth` section, and return `reject` there.

On a quick inspection of the code, changing the behavior of `post_proxy` will be difficult.  It's not just a simple change, it's ensuring that the change has no problematic side effects.

Since there is already a way to mostly do this in v3, I'm going to close the bug report.

**Comment by Djo91** [comment]
Thanks for your reply, i'll try to do this check in post_auth section.
Regards

**Comment by Djo91** [comment]
It works in the post-auth section.
Thx
