### ISSUE TITLE
Missing Error Check in function BIO_new()

### ISSUE THREAD

**Issue by lc3412** [FreeRADIUS/freeradius-server#2309]
# Issue type
Missing Error Check in function BIO_new()

***

# Defect
- Defect - Non compliance with a standards document, or incorrect API usage.

***

## How to reproduce the issue

Function BIO_new() returns a newly created BIO or NULL if the call fails. However , the return value of function BIO_new() is not checked, before passing as an argument to the function i2a_ASN1_OBJECT(). See the following code:

line: 1057, 1069
https://github.com/FreeRADIUS/freeradius-server/blob/94149dc41360cd8736e6265a1dc03b8ed2ccf018/src/lib/tls/session.c#L1057-L1069

We find the return value of this call been checked in the same file
Such as,
https://github.com/FreeRADIUS/freeradius-server/blob/94149dc41360cd8736e6265a1dc03b8ed2ccf018/src/lib/tls/session.c#L1424-L1433

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by arr2036** [comment]
Yeah, fair point.  It would have been flagged by static analysis tools at some point.

谢谢
