### ISSUE TITLE
Insert CREATE TABLE IF NOT EXISTS in SQL statements

### ISSUE THREAD

**Issue by thiagogomesverissimo** [FreeRADIUS/freeradius-server#2313]
Hi,

This issue is a tip, not a bug.
I am writing some [ansible](https://docs.ansible.com/) tasks to deploy and test freeradius. 
I know that the idea is to change the queries/schemas in sql mode, but to make easier to build an idempotent script to deploy freeradius in sql mode with default configuration (i,e, a script that can be re-runned mutiple times), this change would be useful. 

So, the proposal is to change SQLs in mods-config/sql/main folder. 
Example for mysql and table radacct:
from: 
`CREATE TABLE radacct ` 
to: 
`CREATE TABLE IF NOT EXISTS radacct`

[https://github.com/FreeRADIUS/freeradius-server/blob/master/raddb/mods-config/sql/main/mysql/schema.sql](https://github.com/FreeRADIUS/freeradius-server/blob/master/raddb/mods-config/sql/main/mysql/schema.sql)

If you like this idea, I can send a PR to all dialects fixing this. If not, all right, I can close this issue.

**Comment by alandekok** [comment]
This sounds reasonable.  My only worry would be people who've created the table incorrectly.  But... that's a problem for them to fix.
