### ISSUE TITLE
Dev headers not usable.

### ISSUE THREAD

**Issue by alex-eri** [FreeRADIUS/freeradius-server#2323]
Some other headers missed in packages. See https://packages.debian.org/stretch/amd64/libfreeradius-dev/filelist this headers not usable. Drop it all from `make install` command or add missed pls.

I not found
```
freeradius/threads.h
freeradius/regex.h
freeradius/tcp.h
freeradius/autoconf.h
```

I know freeradius/autoconf.h is generated, but it can be provided for binary releases.

**Comment by alandekok** [comment]
No further comments, so it seems fixed.
