### ISSUE TITLE
radius - run-time variable %l not producing same value in latest compiled source and latest public release 3.0.17.

### ISSUE THREAD

**Issue by ivlovric** [FreeRADIUS/freeradius-server#2327]
We are using run-time variable in our test accounting setup to log time in unix time format with variable %l. 

In version 3.0.17. we are getting value of, for example:  "1537363447", where in latest build from source this variable is returning "2018-10-10T12:57:19.530"
This variable is our last field in radius stop event we are adding as custom field.

Runtime variables used according to this:
https://wiki.freeradius.org/config/run_time_variables

-------------
radiusd -X

proto_radius_udp - Received Accounting-Request ID 97 length 716 proto_radius_udp server * port 1813
Network received packet size 716
proto_radius_udp - cleaning up ID 147
Waking up in 2.9 seconds.
Resetting worker 30 cleanup timer to +0s
(31)  running request
(31)  Received Accounting-Request ID 97
(31)    Acct-Status-Type = Stop
(31)    NAS-IP-Address = 192.168.50.140
(31)    NAS-Port = 5060
(31)    Acct-Session-Id = "180382-22192@192.168.50.102"
(31)    Acme-Session-Ingress-CallId = "180382-22192@192.168.50.102"
(31)    Acme-Session-Egress-CallId = "180382-22192@192.168.50.102"
(31)    Acme-Session-Protocol-Type = "SIP"
(31)    Calling-Station-Id = "sipp <sip:sipp@192.168.50.102:5060>;tag=22192SIPpTag00180382"
(31)    Called-Station-Id = "1000 <sip:1000@192.168.50.13:5060>"
(31)    Acct-Terminate-Cause = User-Error
(31)    Acct-Session-Time = 0
(31)    h323-setup-time = "12:24:32.636 UTC Oct 10 2018"
(31)    h323-disconnect-time = "12:24:32.639 UTC Oct 10 2018"
(31)    h323-disconnect-cause = "5"
(31)    Acme-Egress-Network-Interface-Id = "s1p0"
(31)    Acme-Egress-Vlan-Tag-Value = 0
(31)    Acme-Ingress-Network-Interface-Id = "s0p0"
(31)    Acme-Ingress-Vlan-Tag-Value = 0
(31)    Acme-Session-Egress-Realm = "suppliers"
(31)    Acme-Session-Ingress-Realm = "peer-TEST"
(31)    Acme-Firmware-Version = "XXXX"
(31)    Acme-Local-Time-Zone = "GMT"
(31)    Acme-Post-Dial-Delay = 0
(31)    Acme-Primary-Routing-Number = "sip:1000@192.168.50.13:5060"
(31)    Acme-Ingress-Local-Addr = "192.168.50.13:5060"
(31)    Acme-Ingress-Remote-Addr = "192.168.50.102:5060"
(31)    Acme-Egress-Local-Addr = "192.168.50.140:5060"
(31)    Acme-Egress-Remote-Addr = "192.168.50.151:5060"
(31)    Acme-Session-Disposition = 1
(31)    Acme-Disconnect-Initiator = 2
(31)    Acme-Disconnect-Cause = 21
(31)    Acme-SIP-Status = 603
(31)    Acme-Egress-Final-Routing-Number = "sip:1000@192.168.50.151:5060"
(31)    Acme-CDR-Sequence-Number = 635765
(31)  Running 'recv Accounting-Request' from file /usr/local/etc/raddb/sites-enabled/default
(31)  recv Accounting-Request {
(31)    acct_unique {
(31)      if ("%{string:Class}" =~ /ai:([0-9a-f]{32})/i) {
(31)        EXPAND %{string:Class}
(31)           --> 
(31)        ...
(31)      }
(31)      else {
(31)        update request {
(31)          EXPAND %{User-Name}
(31)            --> (null)
(31)          EXPAND %{Acct-Multi-Session-ID}
(31)            --> ,
(31)          EXPAND %{Acct-Session-ID}
(31)            --> 180382-22192@192.168.50.102
(31)          EXPAND %{NAS-IPv6-Address}
(31)            --> (null)
(31)          EXPAND %{NAS-IP-Address}
(31)            --> 192.168.50.140
(31)          EXPAND %{%{NAS-IPv6-Address}:-%{NAS-IP-Address}}
(31)            --> 192.168.50.140
(31)          EXPAND %{NAS-Identifier}
(31)            --> ,
(31)          EXPAND %{NAS-Port-ID}
(31)            --> ,
(31)          EXPAND %{NAS-Port}
(31)            --> 5060
(31)          EXPAND %{md5:%{User-Name},%{Acct-Multi-Session-ID},%{Acct-Session-ID},%{%{NAS-IPv6-Address}:-%{NAS-IP-Address}},%{NAS-Identifier},%{NAS-Port-ID},%{NAS-Port}}
(31)                (%{md5:,,180382-22192@192.168.50.102,192.168.50.140,,,5060})
(31)            --> 0xbd6f31c8c4c8cff832d9b32f64d8e019
(31)          &Acct-Unique-Session-Id := "\275o1\310\304\310\317\3702ٳ/d\330\340\031"
(31)        } # update request (noop)
(31)      } # else (noop)
(31)    } # acct_unique (noop)
(31)    files (noop)
(31)  } # recv Accounting-Request (noop)
(31)  Running 'send Accounting-Response' from file /usr/local/etc/raddb/sites-enabled/default
(31)  send Accounting-Response {
(31)    detail - EXPAND /var/log/radius/radacct/%{%{Packet-Src-IP-Address}:-%{Packet-Src-IPv6-Address}}/detail-%Y-%m-%d
(31)    detail - --> /var/log/radius/radacct/10.116.28.71/detail-2018-10-10
(31)    detail - /var/log/radius/radacct/%{%{Packet-Src-IP-Address}:-%{Packet-Src-IPv6-Address}}/detail-%Y-%m-%d expands to /var/log/radius/radacct/10.116.28.71/detail-2018-10-10
(31)    detail - EXPAND %t
(31)    detail - --> Wed Oct 10 14:21:30 2018
(31)    detail (ok)
(31)    unix (noop)
(31)    log_accounting - EXPAND Accounting-Request.%{%{Acct-Status-Type}:-unknown}
(31)    log_accounting - --> Accounting-Request.Stop
(31)    log_accounting - EXPAND Stop,%{NAS-IP-Address},%{NAS-Port},%{Acct-Session-Id},%{Acme-Session-Ingress-CallId},%{Acme-Session-Egress-CallId},%{Acme-Session-Protocol-Type},%{Calling-Station-Id},%{Called-Station-Id},%{Acct-Terminate-Cause},%{Acct-Session-Time},%{h323-setup-time},%{h323-connect-time},%{h323-disconnect-time},%{h323-disconnect-cause},%{Acme-P-Asserted-ID},%{Acme-Egress-Network-Interface-Id},%{Acme-Egress-Vlan-Tag-Value},%{Acme-Ingress-Network-Interface-Id},%{Acme-Ingress-Vlan-Tag-Value},%{Acme-Session-Egress-Realm},%{Acme-Session-Ingress-Realm},%{Acme-FlowID_FS1_F},%{Acme-FlowType_FS1_F},%{Acme-Flow-In-Realm_FS1_F},%{Acme-Flow-In-Src-Addr_FS1_F},%{Acme-Flow-In-Src-Port_FS1_F},%{Acme-Flow-In-Dst-Addr_FS1_F},%{Acme-Flow-In-Dst-Port_FS1_F},%{Acme-Flow-Out-Realm_FS1_F},%{Acme-Flow-Out-Src-Addr_FS1_F},%{Acme-Flow-Out-Src-Port_FS1_F},%{Acme-Flow-Out-Dst-Addr_FS1_F},%{Acme-Flow-Out-Dst-Port_FS1_F},%{Acme-Calling-RTCP-Packets-Lost_FS1},%{Acme-Calling-RTCP-Avg-Jitter_FS1},%{Acme-Calling-RTCP-Avg-Latency_FS1},%{Acme-Calling-RTCP-MaxJitter_FS1},%{Acme-Calling-RTCP-MaxLatency_FS1},%{Acme-Calling-RTP-Packets-Lost_FS1},%{Acme-Calling-RTP-Avg-Jitter_FS1},%{Acme-Calling-RTP-MaxJitter_FS1},%{Acme-Calling-Octets_FS1},%{Acme-Calling-Packets_FS1},%{Acme-Calling-R-Factor},%{Acme-Calling-MOS},%{Acme-FlowID_FS1_R},%{Acme-FlowType_FS1_R},%{Acme-Flow-In-Realm_FS1_R},%{Acme-Flow-In-Src-Addr_FS1_R},%{Acme-Flow-In-Src-Port_FS1_R},%{Acme-Flow-In-Dst-Addr_FS1_R},%{Acme-Flow-In-Dst-Port_FS1_R},%{Acme-Flow-Out-Realm_FS1_R},%{Acme-Flow-Out-Src-Addr_FS1_R},%{Acme-Flow-Out-Src-Port_FS1_R},%{Acme-Flow-Out-Dst-Addr_FS1_R},%{Acme-Flow-Out-Dst-Port_FS1_R},%{Acme-Called-RTCP-Packets-Lost_FS1},%{Acme-Called-RTCP-Avg-Jitter_FS1},%{Acme-Called-RTCP-Avg-Latency_FS1},%{Acme-Called-RTCP-MaxJitter_FS1},%{Acme-Called-RTCP-MaxLatency_FS1},%{Acme-Called-RTP-Packets-Lost_FS1},%{Acme-Called-RTP-Avg-Jitter_FS1},%{Acme-Called-RTP-MaxJitter_FS1},%{Acme-Called-Octets_FS1},%{Acme-Called-Packets_FS1},%{Acme-Called-R-Factor},%{Acme-Called-MOS},%{Acme-Firmware-Version},%{Acme-Local-Time-Zone},%{Acme-Post-Dial-Delay},%{Acme-Primary-Routing-Number},%{Acme-Ingress-Local-Addr},%{Acme-Ingress-Remote-Addr},%{Acme-Egress-Local-Addr},%{Acme-Egress-Remote-Addr},%{Acme-Session-Disposition},%{Acme-Disconnect-Initiator},%{Acme-Disconnect-Cause},%{Acme-SIP-Status},%{Acme-Egress-Final-Routing-Number},%{Acme-CDR-Sequence-Number},%{Client-IP-Address},%{Acct-Unique-Session-Id},%l
(31)    log_accounting - --> Stop,192.168.50.140,5060,180382-22192@192.168.50.102,180382-22192@192.168.50.102,180382-22192@192.168.50.102,SIP,sipp <sip:sipp@192.168.50.102:5060>;tag=22192SIPpTag00180382,1000 <sip:1000@192.168.50.13:5060>,User-Error,0,12:24:32.636 UTC Oct 10 2018,,12:24:32.639 UTC Oct 10 2018,5,,s1p0,0,s0p0,0,suppliers,peer-TEST,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,ECZ8.0.0 GA (Build 59),GMT,0,sip:1000@192.168.50.13:5060,192.168.50.13:5060,192.168.50.102:5060,192.168.50.140:5060,192.168.50.151:5060,1,2,21,603,sip:1000@192.168.50.151:5060,635765,,\275o1\310\304\310\317\3702ٳ/d\330\340\031,Oct 10 2018 14:21:30 CEST
(31)    log_accounting - EXPAND /var/log/radius/linelog-accounting
(31)    log_accounting - --> /var/log/radius/linelog-accounting
(31)    log_accounting (ok)
(31)    attr_filter.accounting_response - EXPAND %{User-Name}
(31)    attr_filter.accounting_response - --> 
(31)    attr_filter.accounting_response - Matched entry DEFAULT at line 12
(31)    attr_filter.accounting_response (updated)
(31)  } # send Accounting-Response (updated)
(31)  Sent code 5 Id 97 from 10.116.28.168:1813 to 10.116.28.71:39461 via ens192 length 0
(31)  done request
(31)  finished request.

**Comment by alandekok** [comment]
v4 is different from v3.  You were told that in the last issue you opened.

If you're having issues with v4, then use v3.  If you still want to use v4, then don't open spurious PRs that say "OMG they're different."

**Comment by arr2036** [comment]
%l returns a date type value box, and the presentation format when converted to a string is the ISO date format.  The quick workaround to get a unix timestamp is to assign the date to a date attribute and pass it to the ``%{integer:}`` expansion.
