### ISSUE TITLE
Header installation conflicts in master

### ISSUE THREAD

**Issue by jsynack** [FreeRADIUS/freeradius-server#2331]
# Issue type
* Bug

Recent changes to the header installation has removed `${PROJECT_NAME}` from the header file install location. Not sure if this was desired or not? 

Found this in a round-a-bout way as with default settings as this puts some header files in conflict with system header files. 

As-is right now from `master` - this causes a system-wide compiler breakage with default settings on Ubuntu 16 LTS and 18 LTS. Specifically for the conflicting `features.h`.  

Ref change here: 
https://github.com/FreeRADIUS/freeradius-server/commit/0ea3a4a58c242c853da95bf97f8139191fb4c379#diff-59eb623d3bf60db38c73ebd8f350df63L214

***

- Defect - Installation Conflict

# Defect
## How to reproduce the issue

Running Ubuntu 18.04 LTS as an example (also seen on 16.04.x LTS).

Build from `master`. Perform a `sudo make install`  which will default to installing header files to `/usr/local/include`.

 Try to use your compiler again. Due to conflicting `features.h` - you get all sorts of compiler problems due to the conflict with the system GNU C-lib `/usr/include/features.h` file. Remove the offending `/usr/local/include/features.h` and things return to normal.

Output was not included since this is a compile-time/install-time item versus a radiusd run-time problem. Should be easy to reproduce.

I did a quick change to re-add `${PROJECT_NAME}` to `install.mk` , but it still wasn't getting filled in properly - so it seems `includedirs` may already be set by the time this gets called? 

Probably better for someone who is in tune with all of the `.mk` flow and the desired changes to take a look and adjust as needed.

**Comment by alandekok** [comment]
I've pushed a fix.

The main issue is that the `configure` scripts automatically add a `--includedir` argument, that *doesn't* include the `freeradius` qualification.  So we have to add that ourselves.
