### ISSUE TITLE
freeradius-server/etc/raddb/mods-enabled/ldap[8]: Application and rlm_ldap magic number (prefix) mismatch.  application: 0 module:f4

### ISSUE THREAD

**Issue by yunyexiangfeng** [FreeRADIUS/freeradius-server#2335]
l use freeradius + ldap
step1: ./configure --prefix=<path>  and make && make install the freeradius
step2:yum install freeradius-ldap freeradius-postgresql
step3:cp /lib64/freeradius/rlm_ldap.so /lib64/freeradius/rlm_sql_postgresql.so to the <path>/lib
step4:make a soft link in mod-enable/ldap to mod-available/ldap
step5:run <path>/sbin/radiusd -X

then i get the error message :
/opt/OmniVista_2500_NMS/services/freeradius-server/etc/raddb/mods-enabled/ldap[8]: Failed loading module rlm_ldap from file /opt/OmniVista_2500_NMS/services/freeradius-server/lib/rlm_ldap.so
/opt/OmniVista_2500_NMS/services/freeradius-server/etc/raddb/mods-enabled/ldap[8]: Application and rlm_ldap magic number (prefix) mismatch.  application: 0 module: f4

any one can help me?
i don't know how to do.
thanks at first.

**Comment by alandekok** [comment]
You *cannot* mix libraries you build yourself, and libraries taken from "yum".  You *must* use binaries and libraries which were built all at the same time.

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.  And all of this is documented in the server, and on the Wiki.
