### ISSUE TITLE
Build fails at src/lib/pair.c in 'fr_pair_find_by_num' error: macro "VERIFY_LIST"

### ISSUE THREAD

**Issue by doug-fsu** [FreeRADIUS/freeradius-server#2338]
First time ever entering a bug in Github.  This is a good faith effort to be a good community member.  I got the impression from the listserv that this is preferred to simply reporting the issue through the listserv.  I hope I have not misunderstood.

- Defect - Build fails.

# Defect
download 3.0.x and try to build it.
Do you need to add the "_name" parameter to the second definition of VERIFY_LIST in src/include/libradius.h at line 124?

```
src/lib/pair.c: In function ‘fr_pair_find_by_num’:
src/lib/pair.c:220:20: error: macro "VERIFY_LIST" passed 2 arguments, but takes just 1
  VERIFY_LIST(vp, "");
                    ^
src/lib/pair.c:220:2: error: ‘VERIFY_LIST’ undeclared (first use in this function)
  VERIFY_LIST(vp, "");
  ^
src/lib/pair.c:220:2: note: each undeclared identifier is reported only once for each function it appears in
src/lib/pair.c: At top level:
cc1: error: unrecognized command line option "-Wno-date-time" [-Werror]
cc1: all warnings being treated as errors
make: *** [build/objs/src/lib/pair.lo] Error 1
```

**Comment by alandekok** [comment]
I've pushed a fix for pair.c.

For the other error, either use a recent C compiler, or update `Make.inc` to remove `-Wno-date-time`
