### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by MisterErwin** [FreeRADIUS/freeradius-server#2351]
With the soon(ish) deprecation of python 2 (January 2020) a python 3 supporting module would be very nice. 
Be it by plain replacing the python 2 module or adding a python 3 one. But py2to3 should be usable for most cases (imho).

Apparently there already have been PRs (e.g. #1686 ) but those were closed due to inactivity.

**Comment by herwinw** [comment]
It feels like the current `rlm_python` has support for Python 3, but needs a bit of work to make it really work.

Configure works (output truncated to relevant parts):
```
~/freeradius-server/src/modules/rlm_python$ ./configure --with-rlm-python-bin=$(which python3.6)
configure: Python sys.prefix "/usr"
configure: Python sys.exec_prefix "/usr"
configure: Python sys.version "3.6"
checking for Python.h in /usr/include/python3.6/... yes
checking for Py_Initialize in -lpython3.6m in /usr/lib/python3.6/config... yes
```

Make generates a few warnings that need fixing (but it might be Python 3.6 is too new)

```
src/modules/rlm_python/rlm_python.c:228:19: warning: implicit declaration of function ‘PyString_AsString’; did you mean ‘PyBytes_AsString’? [-Wimplicit-function-declaration]
src/modules/rlm_python/rlm_python.c:287:9: warning: implicit declaration of function ‘PyString_CheckExact’; did you mean ‘PyLong_CheckExact’? [-Wimplicit-function-declaration]
src/modules/rlm_python/rlm_python.c:303:15: warning: implicit declaration of function ‘PyInt_Check’; did you mean ‘PySet_Check’? [-Wimplicit-function-declaration]
src/modules/rlm_python/rlm_python.c:304:10: warning: implicit declaration of function ‘PyInt_AsLong’; did you mean ‘PyLong_AsLong’? [-Wimplicit-function-declaration]
src/modules/rlm_python/rlm_python.c:367:10: warning: implicit declaration of function ‘PyString_FromFormat’; did you mean ‘PyBytes_FromFormat’? [-Wimplicit-function-declaration]
src/modules/rlm_python/rlm_python.c:996:18: warning: implicit declaration of function ‘Py_InitModule3’; did you mean ‘Py_Initialize’? [-Wimplicit-function-declaration]
```

**Comment by arr2036** [comment]
Not closed due to inactivity, closed due to v4.0.x being renamed if the OP could reopen against master branch that'd be great.

**Comment by Deisuan** [comment]
> It feels like the current `rlm_python` has support for Python 3, but needs a bit of work to make it really work.

Well, it has been admittedly about two years since I've worked on the PR, but as far as I can recall, the changes are quite not trivial. The internal cpython implementation for - among others - strings and global interpreter lock have changes substantially. The work of porting the rlm_python to Python3 is basically done (see PR #1686 ), however it fails with more than one instance of the module at the same time. I recall there being similar (or even the same?) issue with rlm_python for Python2. With one module it has been running quite stable for about two years in our production system ;-) 

@arr2036 Would it be an acceptable intermediate solution to change the travis checks such that only one instance is made, merge the PR #1686 (after a rebase by me of course), and expand to two module support at a later time? Just

**Comment by herwinw** [comment]
Before forking the module to create a `rlm_python3`, please keep in mind that #2334 contains some very useful changes for `rlm_python`.

**Comment by alejandro-perez** [comment]
Indeed, if we went for rlm_python3, I would vote for getting rid of the tuple-based interface in favor of the dict-based one, taking advantage that backwards compatibility would not be an issue.

**Comment by cipherboy** [comment]
It'd be nice if these changes were considered for the `v3.0.x` branch as well. It is unlikely we'll be ship `v4.0.x` any time soon at Red Hat or in Fedora, so we'll need Python 3 support in the `v3.0.x`...

**Comment by arr2036** [comment]
I'm not sure we should really concern ourselves with the released schedules of RedHat and Fedora, especially as we provide our own packages.  I'm generally against adding new functionality to older branches, and am definitely against maintaining two versions of rlm_python.  Python's C API is poorly documented and there are existing threading issues with the current rlm_python module.  IMHO this should go into v4.0.x, and we should stick with one python version.  People are going to be reworking their configs during the upgrade anyway.

**Comment by cipherboy** [comment]
Duly noted. I'm not trying to suggest a time frame to have this done by, merely that I'm watching and will fit it into our releases as it gets done. I'll keep this as something I'll likely have to backport.

Thanks!

**Comment by cfrademan** [comment]
Hi there. We implementing some third party software with FreeRadius. We running a bit low on time here and happy to go forward using python2 for time being. However what is the plans moving forward with python3 support? I do not see in the milestones for the 4x branch? We got less than a year left on python2. It makes sense that 4.x only supports python3 and sticking with one module rlm_python.

**Comment by alandekok** [comment]
If you can verify PR #1686, we can pull it into v4.  With a note that rlm_python in v4 is only Python3.

If anyone has time to create an rlm_python3 for v3, we're happy to look at it.

**Comment by MisterErwin** [comment]
Hating to be that guy that only bumps issues (and not really providing anything useful), but after "testing" Deisuans PR (by using it in prod) and the EOF for python2 being in roughly 6 months.... is there any progress?

**Comment by alandekok** [comment]
My $0.02 is to add a `rlm_python3` module to v3.  For backwards compatibility, we don't want to change the existing `rlm_python`.  In v4, `rlm_python` can just be Python3.

The core FreeRADIUS team doesn't have time to do this right now, plus we don't use Python much. 
 So testing is hard.  Patches are welcome.

**Comment by aren** [comment]
We built an `rlm_python3` module for v3 (based off of `rlm_python` from v4). We'll submit a PR soon.

**Comment by alandekok** [comment]
> We built an `rlm_python3` module for v3 (based off of `rlm_python` from v4). We'll submit a PR soon.

Great news, thanks!

**Comment by jeffersonchua** [comment]
On Tue, Sep 10, 2019 at 1:41 AM Alan DeKok <notifications@github.com> wrote:

> We built an rlm_python3 module for v3 (based off of rlm_python from v4).
> We'll submit a PR soon.
>
> Great news, thanks!
>
Will be happy to test it!
Thanks,
Jeff.

**Comment by alejandro-perez** [comment]
Yeah, me too.

**Comment by arr2036** [comment]
Honestly I didn't think the changes were that invasive to support Python 3.  I'd be interested to see what changes you made to the python module in v4, because I thought a lot of the support necessary was already there.  Most of the changes were to support the use of wchar_t which is either a 16bit or 32bit character type.

**Comment by arr2036** [comment]
and it follows if that's the case, then there's probably no need for an rlm_python3, and we can just use the module from v4 backported to v3...

**Comment by alandekok** [comment]
My only concern is compatibility.  Many, many, people use rlm_python with python2.  Changing that in v3 is a non-starter.

**Comment by arr2036** [comment]
Sure, so have the configure script prefer Python 2.7?

**Comment by arr2036** [comment]
My main concern is duplicating an entire module when it can already handle the version differences in the library it's being linked to.  Another option would be multiple configure scripts and multiple all.mk files but using the same source?

**Comment by arr2036** [comment]
520d06a2150dcfcf912ce48e9498895832e60b3a
8c9580662a08afa5cdd79cb17ad2ea586cde467a
0f9ebec4ac044053ba8a58791470ee6bb6503886
4831db429997318e78f748762ecd2b4fb245919c

**Comment by jeffersonchua** [comment]
Compiled fine. Next it to test running it.

My best.,
Jeff

**Comment by arr2036** [comment]
OK as of 2c6d2331bf6761aeff21f880ce6600dac3893875

Tests show rlm_python is still functional for Python 2.7 (all tests pass).  Support for Python 3 strips out "cext_compat" mode, because the upcoming Python 3.8 release should fix the underlying issue, and potentially provide a way of improving multi-threaded performance significantly where GIL contention is an issue.

The only remaining issue for Python 3 is radiusd.config injection, which allows you to create Python dicts from the rlm_python module config is not working, not sure why.  It works fine with Python 2.7.

**Comment by aren** [comment]
We just tested and that seems to work fine in our module. It looks for an inner section called `config` in the `python` module config file.

**Comment by jpereira** [comment]
@aren have you tried to execute shared contexts?

e.g:

1. Change the `example.py` to do something like:

```
class Tapioca:
  def __init__(self, name, age):
    self.tipo = "whatever"

def authorize(p):
  radiusd.log(radiusd.L_INFO, 'authorize: *** log call in authorize ***')
  if not hasattr(Tapioca, 'shared_attribute'):
    radiusd.log(radiusd.L_INFO, 'authorize: *** ######### authorize - hasattr=false')
    setattr(Tapioca, 'shared_attribute', True)
    return radiusd.RLM_MODULE_NOOP
  else:
    radiusd.log(radiusd.L_INFO, 'authorize: *** ######### authorize - hasattr=true')
    return radiusd.RLM_MODULE_OK
```

2. The first execution is fine. but, the next will crash due to can't find the previous state.

**Comment by arr2036** [comment]
Yeah figured out what the problem was. Misunderstanding of how the inittab should work

**Comment by robertpenz** [comment]
Can you please integrate the changes foxpass provided into the 3.0.x, as Python 2.7 will not be supported after 31.12.2019 and the current released version (at the time of writing thats 3.0.19) of a big project like Freeradius does not support Python 3.  I talked with Redhat hat thats also the reason no python binding is provided with RHEL 8.

**Comment by alandekok** [comment]
@robertpenz  Please TEST the changes and report back if they work.

FreeRADIUS is a community project, and relies on the community for help.  The foxpass guys didn't bother to open a PR, which is why we didn't know about it.  And we're not overly familiar with Python, so we rely on the community for help.

If no one replies with "yes it works", then we will release 3.0.20 *without* python3 support.

**Comment by mcnewton** [comment]
IMHO, we shouldn't be adding _any_ new features in at the last minute before a new release. We can always cut another release after it's been merged and well tested. 3.0.20 is overdue as it is.

**Comment by robertpenz** [comment]
will do so and get back to you.

**Comment by arr2036** [comment]
I agree with @mcnewton

**Comment by aren** [comment]
@alandekok, @arr2036 looked at our diff and preferred another way to accomplish python3 support (adding support to the existing python module; now implemented in `master`). See my comment in this thread on Sept 12 offering to open a PR, or spearhead a backport of Arran's work in `master`.

I've squashed our branch down to a single commit and can open a PR if we want to move the discussion there about whether a separate `python3` module is the way to go for the `3.0.x` branch.

**Comment by alandekok** [comment]
The issue for me is that we can do whatever we want in master.  Having one module build for Python2 and Python3 is fine.  Because it's a major release, and it's fine to change behavior.

I'm _much_ more wary of changing behavior in a stable release.  If we create one module to do both Python versions, *and* it changes the behavior of the module, then people will get upset.  Justifiably so.

I would much rather leave `rlm_python` alone, and add a new `rlm_python3`.  Even if it means duplicating code

**Comment by arr2036** [comment]
Yeah I tend to agree... after adding support in master the changes were not as trivial as they first appeared.  It also looks like there's some work required to get Python 3 working asynchronously, so it's not like there's even significant benefit in back porting the code in terms of keeping v3.0.x and master in sync.

**Comment by cipherboy** [comment]
If you want to get this in front of some `v3.0.x` users, I'm happy to push Python 3 support to Fedora Rawhide (Fedora's unstable rolling release) and have people test it there. It might simplify testing and deployment for some of your users and give you a bit more feedback if you want it.

Just something to keep in mind. Mention me in a PR if that's something y'all want.

**Comment by alandekok** [comment]
We're going to release 3.0.20 soon.  I think the consensus is to add `rlm_python3` as a new experimental module.  Then if it works, we can mark it "stable".

**Comment by cipherboy** [comment]
ACK, I'll plan on pushing 3.0.20 to F30+ and shipping the experimental `rlm_python3` in Rawhide.

**Comment by alejandro-perez** [comment]
We've got a Python module for Moonshot that I'll be more than happy to port to Python3 and test this module

**Comment by robertpenz** [comment]
@alandekok: We did some tests and it works.

#Details:
We did the tests on a Fedora 30 with python 3.7.4.

## Dependency
libkqueue which is needed to compile is not in any repo we checked (RHEL7 including EPEL, RHEL8 including EPEL, Fedora30), so we did

```
git clone https://github.com/mheily/libkqueue.git
configure && make && make install
```

## install

```
git clone https://github.com/foxpass/freeradius-server.git
git checkout python3_for_30x
```

the Python.h was not found on our System, we did following:

```
sudo ln -s /usr/include/python3.7m /usr/include/python3.7
```

```
./configure --prefix=/usr
make && sudo make install
```

## Setup of modul
according to https://wiki.freeradius.org/modules/Rlm_python just using python3 instead of python

##Test Examples

```
echo "User-Name=bob,Chap-Password=hello" | radclient -x localhost auth testing123
```


```
Sent Access-Request Id 42 from 0.0.0.0:43227 to 127.0.0.1:1812 length 44
        User-Name = "bob"
        CHAP-Password = 0x4a8f95f1449b60b116b432a83b66ab551f
        Cleartext-Password = "hello"
Received Access-Accept Id 42 from 127.0.0.1:1812 to 127.0.0.1:43227 length 44
        Reply-Message = "Hello from rlm_python3"
```

radius -X

```
  # Instantiating module "python3" from file /etc/raddb/mods-enabled/python3
Python version: 3.7.4 (default, Jul  9 2019, 16:32:37)  [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
*** instantiate ***
None
...
(0) Received Access-Request Id 42 from 127.0.0.1:43227 to 127.0.0.1:1812 length 44
(0)   User-Name = "bob"
(0)   CHAP-Password = 0x4a8f95f1449b60b116b432a83b66ab551f
(0) # Executing section authorize from file /etc/raddb/sites-enabled/default
(0)   authorize {
(0)     policy filter_username {
(0)       if (&User-Name) {
(0)       if (&User-Name)  -> TRUE
(0)       if (&User-Name)  {
(0)         if (&User-Name =~ / /) {
(0)         if (&User-Name =~ / /)  -> FALSE
(0)         if (&User-Name =~ /@[^@]*@/ ) {
(0)         if (&User-Name =~ /@[^@]*@/ )  -> FALSE
(0)         if (&User-Name =~ /\.\./ ) {
(0)         if (&User-Name =~ /\.\./ )  -> FALSE
(0)         if ((&User-Name =~ /@/) && (&User-Name !~ /@(.+)\.(.+)$/))  {
(0)         if ((&User-Name =~ /@/) && (&User-Name !~ /@(.+)\.(.+)$/))   -> FALSE
(0)         if (&User-Name =~ /\.$/)  {
(0)         if (&User-Name =~ /\.$/)   -> FALSE
(0)         if (&User-Name =~ /@\./)  {
(0)         if (&User-Name =~ /@\./)   -> FALSE
(0)       } # if (&User-Name)  = notfound
(0)     } # policy filter_username = notfound
(0)     [preprocess] = ok
(0) auth_log: EXPAND /var/log/radius/radacct/%{%{Packet-Src-IP-Address}:-%{Packet-Src-IPv6-Address}}/auth-detail-%Y%m%d
(0) auth_log:    --> /var/log/radius/radacct/127.0.0.1/auth-detail-20191031
(0) auth_log: /var/log/radius/radacct/%{%{Packet-Src-IP-Address}:-%{Packet-Src-IPv6-Address}}/auth-detail-%Y%m%d expands to /var/log/radius/radacct/127.0.0.1/auth-detail-20191031
(0) auth_log: EXPAND %t
(0) auth_log:    --> Thu Oct 31 08:52:29 2019
(0)     [auth_log] = ok
*** authorize ***
*** radlog call in authorize ***

(('User-Name', 'bob'), ('CHAP-Password', '0x4a8f95f1449b60b116b432a83b66ab551f'), ('Event-Timestamp', 'Oct 31 2019 08:52:29 CET'), ('NAS-IP-Address', '127.0.0.1'), ('CHAP-Challenge', '0xd43153d0a1186b63e66f4e9ce896c35b'))

{}
*{color:red}{color:#DE350B}authorize - 'reply:Reply-Message' = 'Hello from rlm_python3'
authorize - 'config:Cleartext-Password' = 'hello'
(0)     [python3] = ok{color}{color}*
(0) chap:   &control:Auth-Type := CHAP
(0)     [chap] = ok
(0)     [mschap] = noop
(0)     [digest] = noop
(0) suffix: Checking for suffix after "@"
(0) suffix: No '@' in User-Name = "bob", looking up realm NULL
(0) suffix: No such realm "NULL"
(0)     [suffix] = noop
(0) eap: No EAP-Message, not doing EAP
(0)     [eap] = noop
(0)     [files] = noop
(0)     [expiration] = noop
(0)     [logintime] = noop
(0) pap: WARNING: Auth-Type already set.  Not setting to PAP
(0)     [pap] = noop
(0)   } # authorize = ok
(0) Found Auth-Type = CHAP
(0) # Executing group from file /etc/raddb/sites-enabled/default
(0)   Auth-Type CHAP {
(0) chap: Comparing with "known good" Cleartext-Password
(0) chap: CHAP user "bob" authenticated successfully
(0)     [chap] = ok
(0)   } # Auth-Type CHAP = ok
(0) # Executing section post-auth from file /etc/raddb/sites-enabled/default
(0)   post-auth {
(0)     if (session-state:User-Name && reply:User-Name && request:User-Name && (reply:User-Name == request:User-Name)) {
(0)     if (session-state:User-Name && reply:User-Name && request:User-Name && (reply:User-Name == request:User-Name))  -> FALSE
(0)     update {
(0)       No attributes updated for RHS &session-state:
(0)     } # update = noop
(0)     [exec] = noop
(0)     policy remove_reply_message_if_eap {
(0)       if (&reply:EAP-Message && &reply:Reply-Message) {
(0)       if (&reply:EAP-Message && &reply:Reply-Message)  -> FALSE
(0)       else {
(0)         [noop] = noop
(0)       } # else = noop
(0)     } # policy remove_reply_message_if_eap = noop
(0)   } # post-auth = noop
(0) Sent Access-Accept Id 42 from 127.0.0.1:1812 to 127.0.0.1:43227 length 0
(0)   Reply-Message = "Hello from rlm_python3"
(0) Finished request
Waking up in 4.9 seconds.
(0) Cleaning up request packet ID 42 with timestamp +16
Ready to process requests
```

**Comment by cipherboy** [comment]
This has been built in Fedora Rawhide for anyone wishing to test it out there:

https://koji.fedoraproject.org/koji/taskinfo?taskID=39018766
