### ISSUE TITLE
rlm_mschap: Freeradius looks for wrong message when a user password  is expired (ntlm_auth)

### ISSUE THREAD

**Issue by Serophos** [FreeRADIUS/freeradius-server#2360]
# Issue type
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect passchange does not work in all enviroments. 
In a windows domain enviroment when a user password has expired ntlm_auth returns a different message so the check the mschap module does, will not work.

ntlm_auth returns with the message 

"Program returned code (1) and output 'The user password must be changed before logging on the first time. (0x0000224)'

or "... The password has expired ..."

The following patch for src/modules/rlm_mschap/rlm_mschap.c will fix the issue.

@@ -1115,8 +1115,11 @@ static int CC_HINT(nonnull (1, 2, 4, 5 , 6)) do_mschap(rlm_mschap_t const *inst,
 			/*
			 *	look for "Password expired", or "Must change password".
			 *      Fix: Some enviroments report "Password has expired" or "password must be changed"
			 */
			if (strcasestr(buffer, "Password expired") ||
			    strcasestr(buffer, "Password has expired") ||
			    strcasestr(buffer, "password must be changed") ||
			    strcasestr(buffer, "Must change password")) {
				REDEBUG2("%s", buffer);
				return -648;

(https://github.com/Serophos/freeradius-server/commit/2d8f717312f788a3e36a50c6459fbde692b9862a#diff-57f94b2beb1d6fdbe34c85de3f13690d)

**Comment by alandekok** [comment]
I've pushed commit 8ef4848c3 which should help.  It adds the text messages.  And, simplifies some of the checks so that they're less expensive.

Please test and verify that this works.

**Comment by Serophos** [comment]
The patch is working correctly. Thank you.
