### ISSUE TITLE
Free Radius upgrade Issues

### ISSUE THREAD

**Issue by AbhilashSunkad** [FreeRADIUS/freeradius-server#2361]
I recently upgraded my Free Radius code from 2.0 to 3.x build. I am looking for some of the APIs supported by older Free Radius versions. I am looking for APIs ldap_pairget(). Can you please let me know what APIs should be used in place of ldap_pairget. ALso these function include pairmake(), pairadd(), pairdelete() APIs which are not available in newe Free Radius Code. Thanks

**Comment by alandekok** [comment]
Please ask developer questions on the freeradius-devel mailing list.

But, you have to see that if you have a proprietary / custom module that you can't share, it's going to be difficult for us to help you.
