### ISSUE TITLE
nasipaddress unset if connection dies early, leading to stale leased IPs with sqlippool

### ISSUE THREAD

**Issue by Jayd603** [FreeRADIUS/freeradius-server#2368]
When a connection is lost unexpectedly during initial authentication, sqlippool's queries no longer work (missing nasipaddress) leaving the IP that was leased stuck.

Strongswan is on the other end and something is broken with how the connection is being set up (this is because of an incompatible VPN client and possibly strongswan not handling it gracefully), however RADIUS should still be able to clear the IP that was assigned as Acct-Status-Type = Stop is correctly sent by the VPN server.

The IP stays leased to the failed login in the sql radippool table after certain failed logins on the VPN server.  This is a potential DoS issue as an attacker could use up all available IPs by flooding with failed logins.  Assuming a small pool of IPs, someone merely trying to make a client machine work could also use up all available IPs and block further logins from other users.

The good news is if the lease time expires the IPs become available again.

--- SPECIFIC failing query

rlm_sql (sql): Reserved connection (7)
(7) sqlippool_ipv4: EXPAND %{%{Stripped-User-Name}:-%{%{User-Name}:-DEFAULT}}
(7) sqlippool_ipv4:    --> jd
(7) sqlippool_ipv4: SQL-User-Name set to 'jd'
(7) sqlippool_ipv4: EXPAND START TRANSACTION
(7) sqlippool_ipv4:    --> START TRANSACTION
(7) sqlippool_ipv4: Executing query: START TRANSACTION
(7) sqlippool_ipv4: EXPAND UPDATE radippool SET nasipaddress = '', pool_key = 0, callingstationid = '', username = '', expiry_time = NULL WHERE nasipaddress = '%{%{Nas-IP-Address}:-%{Nas-IPv6-Address}}' AND pool_key = '%{NAS-Port}' AND username = '%{User-Name}' AND callingstationid = '%{Calling-Station-Id}' AND framedipaddress = '%{Framed-IP-Address}'
(7) sqlippool_ipv4:    --> UPDATE radippool SET nasipaddress = '', pool_key = 0, callingstationid = '', username = '', expiry_time = NULL WHERE nasipaddress = 'x.x.x.135' AND pool_key = '4' AND username = 'jd' AND callingstationid = 'y.y.y.102=5B58665=5D' AND framedipaddress = ''
(7) sqlippool_ipv4: Executing query: UPDATE radippool SET nasipaddress = '', pool_key = 0, callingstationid = '', username = '', expiry_time = NULL WHERE nasipaddress = 'x.x.x.135' AND pool_key = '4' AND username = 'jd' AND callingstationid = 'y.y.y.102=5B58665=5D' AND framedipaddress = ''
rlm_sql_mysql: Rows matched: 0  Changed: 0  Warnings: 0
(7) sqlippool_ipv4: EXPAND COMMIT
(7) sqlippool_ipv4:    --> COMMIT
(7) sqlippool_ipv4: Executing query: COMMIT
(7) sqlippool_ipv4: EXPAND Released IP Framed-IP-Address (did %{Called-Station-Id} cli %{Calling-Station-Id} user %{User-Name})
(7) sqlippool_ipv4:    --> Released IP Framed-IP-Address (did x.x.x.135[4500] cli y.y.y.102[58665] user jd)
rlm_sql (sql): Released connection (7)

----- FULL -X dump 

ATTACHED in file
[radiusdsqlip_bug_dump_jd.txt](https://github.com/FreeRADIUS/freeradius-server/files/2664577/radiusdsqlip_bug_dump_jd.txt)

**Comment by MinerGuy1111** [comment]
The stop record does appear to have the nas IP?

(7) Received Accounting-Request Id 65 from 127.0.0.1:49280 to 127.0.0.1:1813 length 179
(7)   Acct-Status-Type = Stop
(7)   Acct-Session-Id = "1544462872-4"
(7)   NAS-Port-Type = Virtual
(7)   Service-Type = Framed-User
(7)   NAS-Port = 4
(7)   NAS-Port-Id = "radius-pubkey-ike2"
(7)   NAS-IP-Address = x.x.x.135
(7)   Called-Station-Id = "x.x.x.135[4500]"
(7)   Calling-Station-Id = "y.y.y.102[58665]"
(7)   User-Name = "jd"
(7)   Acct-Output-Octets = 0
(7)   Acct-Output-Packets = 0
(7)   Acct-Input-Octets = 0
(7)   Acct-Input-Packets = 0
(7)   Acct-Session-Time = 0
(7)   Acct-Terminate-Cause = User-Request
(7)   NAS-Identifier = "strongSwan"

**Comment by alandekok** [comment]
The "stop" packet doesn't have a `Framed-IP-Address` attribute:

> (7) sqlippool_ipv4: --> UPDATE radippool SET nasipaddress = '', pool_key = 0, callingstationid = '', username = '', expiry_time = NULL WHERE nasipaddress = 'x.x.x.135' AND pool_key = '4' AND username = 'jd' AND callingstationid = 'y.y.y.102=5B58665=5D' AND framedipaddress = ''

So that's why it's failing.  Strongswan should be sending the `Framed-IP-Address` that was assigned during authentication.

The default queries include `Framed-IP-Address` because it's possible for the user to have multiple sessions, and to be assigned multiple IPs.  That means the accounting packet *must* contain the correct `Framed-IP-Address`, so we know which IP to release.

**Comment by Jayd603** [comment]
Ok, missed that, i'll open an issue on strongswans board.

**Comment by Jayd603** [comment]
Closed
