### ISSUE TITLE
How do I print the detailfile contents to STDOUT

### ISSUE THREAD

**Issue by hmatch** [FreeRADIUS/freeradius-server#2370]
I am trying to print the contents of detailfile into STDOUT because it is easier to send STDOUT to syslog server. Currently, all our logs are collected from STDOUT. How do I change the detail file to print the contents of the logs?

I tried-
	detailfile = ${radacctdir}/%{%{Packet-Src-IP-Address}:-%{Packet-Src-IPv6-Address}}/detail-%Y%m%d
	print detailfile

But it did not work. Please suggest your ideas. Thank you

**Comment by arr2036** [comment]
The first line of the template, the contents of which you removed to add your text states:

- **Questions about the server or its usage MUST be posted to the [users mailing list](http://freeradius.org/list/users.html).  If you post those issues here, they will be closed and locked.**
