### ISSUE TITLE
sqlippool allocate_clear might cause deadlock

### ISSUE THREAD

**Issue by maximumG** [FreeRADIUS/freeradius-server#2395]
# Issue type
- sqlippool module tries to clear leases too many times -> 1 time per second.
- Feature request.

# Feature description

On some heavy load for IP leases reservation, some MySQL server might end with a lot of deadlock transactions and the RADIUS sqlippool module gets blocked because the allocate_clear might be running at the same time as allocate_find queries.

I do understand that most of the times, a deadlock occurs due to a poor MySQL setup with performance issue. However **I think clearing the leases each second might not be useful in all cases**.

**Thus I propose the possibility to configure  a timeout at which we will clear the leases.** (inside the sqlippool module). Default to be 1s in order not to break the current freeradius setup.

Would you be interested in such feature ?

**Comment by alandekok** [comment]
That sounds reasonable.

I also just pushed a change to v3 which ignores `allocate_clear` if it's set to `""`.  That might help.

To be honest, the `allocate_clear` shouldn't be necessary in a well-running system.  If the IPs are expired properly, *and* the same IP is assigned to the same `Calling-Station-Id`, then `allocate_clear` isn't necessary.

**Comment by alandekok** [comment]
e.g.

```
allocate_find = "\
       SELECT framedipaddress \
       FROM ${ippool_table} \
       WHERE (pool_name = '%{control:Pool-Name}' AND expiry_time < 'now'::timestamp(0) ) \
               AND (((username = '%{SQL-User-Name}') AND (callingstationid = '%{Calling-Station-Id}')) OR (callingstationid = '')) \
       ORDER BY callingstationid DESC, username, expiry_time ASC \
       LIMIT 1 \
       FOR UPDATE ${skip_locked}"
```

the only issue with that approach is it *doesn't* fine IPs that have expired, but which still have a non-zero `Calling-Station-Id` field.

TBH, the best approach may be to use a stored procedure.  That way the logic can be:

* allocate same IP if it's not expired, and `Calling-Station-Id` matches, which is what most people want
* otherwise grab any expired IP

Doing that should mean that `allocate_clear` becomes entirely unnecessary.

But even still, adding a timer is useful, and fine for v3.

**Comment by maximumG** [comment]
Thanks for you response. I will work on this issue ASAP. Currently, as the allocate_clear was causing a tremendous number of deadlock with high volume of RADIUS traffic we created the following workarounds.

* *allocate_clear* is empty to avoid clearing all leases every 1s. This function will be performed by an external script running once per hour.
* *allocate_find* is calling a MySQL stored procedure which tries to find an already reserved IP for the user. If an IP is not found, we allocate a free IP from the pool. The stored procedure avoid using the classic order by clause in standard freeradius configuration which is really slowing things down.

**Comment by alandekok** [comment]
If you're OK with getting random IPs, just change the `ORDER BY` to order by expiry time, and nothing else.  The users will get different IPs every time, but the allocation should be faster.

**Comment by maximumG** [comment]
> The users will get different IPs every time, but the allocation should be faster.

Unfortunately, this won't be possible in our use case as we are using FreeRADIUS as DHCP server and can't serve a different IP each time the user is asking to renew its lease.

**Comment by maximumG** [comment]
Thanks for accepting the pull request. Correct me if I'm wrong but it seem that [last commit](https://github.com/FreeRADIUS/freeradius-server/commit/2c590adf7ed9a73aaf92cc46407e2433ed37ec5e#diff-48ebca7ea2a70a8805d3d8fbc28a1d8d), we won't be able to set the allocate_clear_timeout more than 600 seconds ? 

I have some use cases where clearing can be done on a hour or daily basis. Don't you think it would be to the FreeRADIUS administrator to decide the upper limit value ?

**Comment by alandekok** [comment]
It should have a limit which isn't crazy.  i.e. setting it to 2^32 -1 is pointless

I can change it to daily, but anything past that just doesn't make sense.
