### ISSUE TITLE
Historic connection error

### ISSUE THREAD

**Issue by leonardopc1991** [FreeRADIUS/freeradius-server#2459]
Good morning, I have migrated from FreeRadius 2 to FreeRadius 3, and I found the novelty that when carrying the production BD version 2 does not work correctly in version 3, that is, if I do a clean installation of freeradius 3 and I create the user and this connects or disconnects those connection states are saved, but when I carry the production DB that is in FreeRadius 2 and the amount in FreeRadius 3 stops saving this information, probe even using the DB schema found in the sql file of the version, but the part of the connection history still does not work

**Comment by alandekok** [comment]
Configuration questions belong on the freeradius-users mailing list.
