### ISSUE TITLE
freeradius-logrotate: overrides default logrotate config on Debian/RedHat systems

### ISSUE THREAD

**Issue by nqb** [FreeRADIUS/freeradius-server#2461]
# Issue type
- Defect - Unexpected behaviour

The files:
- https://github.com/FreeRADIUS/freeradius-server/blob/master/debian/freeradius.logrotate
- https://github.com/FreeRADIUS/freeradius-server/blob/master/redhat/freeradius-logrotate

define a section "Global options for all logfiles" that overrides default logrotate config file on Debian/RedHat systems. 

For example, on a RedHat system, this mean that: 
```
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
```
are rotate each month in place of each week.

# Defect
## How to reproduce the issue

Run `logrotate` with `-d` option. On a RedHat system:
```
[..]
rotating pattern: /var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
 monthly (4 rotations)                                              <<<
empty log files are rotated, old logs are removed
considering log /var/log/cron
[..]
```

**Comment by mcnewton** [comment]
I've pushed a fix, thanks.
