### ISSUE TITLE
Cache doesn't use Cache-TTL of < 0 if there is no existing entry

### ISSUE THREAD

**Issue by eeverett6** [FreeRADIUS/freeradius-server#2484]
# Issue type

- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect

The cache module configuration file states

> Setting a Cache-TTL of < 0 means expire the existing entry (without merging) and create a new one with TTL set to value * -1.

However, in the 3.0.x branch, if there is no existing entry then the TTL is set to the default TTL value of the cache, instead of `Cache-TTL * -1`

## How to reproduce the issue

Set the control:Cache-TTL attribute to a value < 0, then call the cache module when there is no existing entry matching the key.
 
## Output of ``radiusd -X`` showing issue occurring

```text
(2)     update config {
(2)       &Cache-TTL := -20
(2)     } # update config = noop
(2) cache: EXPAND %{User-Name}
(2) cache:    --> bob
(2) cache: No cache entry found for "bob"
(2) cache: Creating new cache entry
(2) cache:   &reply:Reply-Message += &reply:Reply-Message[*] -> 'Hello, bob'
(2) cache: Merging cache entry into request
(2) cache:   &reply:Reply-Message += "Hello, bob"
(2) cache: Committed entry, TTL 10 seconds
(2)     [cache] = updated
(2)   } # post-auth = updated
```

**Comment by alandekok** [comment]
Fixed by commit 3d4dbd6
