### ISSUE TITLE
Freeradius filter-id + FreeIPA

### ISSUE THREAD

**Issue by rufa11** [FreeRADIUS/freeradius-server#2494]
Hello,
We have a FreeIPA as domain controller and we are planing to use Freeradius as authentication for the Wireless, i configured freeradius with LDAP and i can do authentication with a domain user, now the network team asked me to configure freeradius to return a filter-i of the user group assigned ID, example we have user1:

```
dn: uid=user1,cn=users,cn=accounts,dc=subdmain,dc=domain,dc=com
with the group ID:gid=1471600000
```

I did some research on google and i found that i have to modify the file /etc/raddb/sites-enabled/default like in the link bellow but not exactly the same thing and which command i have to use get this value: FreeIPA_Freeeradius

Any suggestions please ?

Thanks

**Comment by alandekok** [comment]
Github issues are NOT the place to ask questions.  The template you read and ignored says this clearly.
