### ISSUE TITLE
Feature Request: systemd watchdogs 

### ISSUE THREAD

**Issue by shibumi** [FreeRADIUS/freeradius-server#2499]
**Feature Request**

It would be super neat if freeradius would support `systemd watchdogs` via dbus. This way it would be possible to send `watchdog` messages to systemd. You can find a basic watchdog implementation here: https://stackoverflow.com/questions/32947606/calling-a-sd-notify0-watchdog-1-in-a-service

Via watchdogs it would be possible to notify systemd in case of abnormal behavior, crashes, hangs or other errors.

**Comment by arr2036** [comment]
The latest code in master branch already does this.

https://github.com/FreeRADIUS/freeradius-server/blob/master/src/bin/radiusd.c#L534

https://github.com/FreeRADIUS/freeradius-server/blob/4d511c191f2b6d1ee20b7ca20d278f95768bdf53/src/lib/server/process.c#L138

**Comment by alandekok** [comment]
We could likely add that to v3 without too much work, and it would be useful.  I'll re-open this with a v3 tag.

**Comment by mcnewton** [comment]
Maybe @terryburton if you have time and feel like backporting your patches...?

**Comment by terryburton** [comment]
I'm happy to pick this up at the weekend if it's still open.

**Comment by alandekok** [comment]
Fixed for v3 via #2502

**Comment by shibumi** [comment]
Thanks guys! You rock!!! :)

**Comment by jpereira** [comment]
Hi @shibumi, if you don't mind. do more tests and let us know about any issue.

**Comment by shibumi** [comment]
@jpereira sorry for the late reply. I had time to test your newest release now and it seems like `3.0.18` is crashing. We can't start it with `systemctl start freeradius.service on Ubuntu 18.04`:
```
Thu Feb 28 15:03:53 2019 : Warning: Ignoring "response_window = 60.000000", forcing to "response_window = 30.000000"
Thu Feb 28 15:03:53 2019 : Warning: Ignoring "zombie_period = 10", forcing to "zombie_period = 30"
Thu Feb 28 15:03:53 2019 : Warning: Ignoring "response_window = 60.000000", forcing to "response_window = 30.000000"
Thu Feb 28 15:03:53 2019 : Warning: Ignoring "zombie_period = 10", forcing to "zombie_period = 30"
Thu Feb 28 15:03:53 2019 : Info: Debugger not attached
Thu Feb 28 15:03:53 2019 : Info: systemd watchdog interval is 0x55e4e63091d0T secs
Thu Feb 28 15:03:53 2019 : Error: src/main/process.c[381]: Failed to insert event```

When we run the server with `freeradius -X` it runs without any issues... do you have any idea how i can debug this further?

**Comment by arr2036** [comment]
Mmm `0x55e4e63091d0T secs`, that's a lot of secs.

**Comment by mcnewton** [comment]
Testing a fix, see https://github.com/FreeRADIUS/freeradius-server/issues/2541

**Comment by shibumi** [comment]
@mcnewton I am not sure if a fix in the `freeradius.service` file helps here, because when i start the freeradius server on command line via `/usr/sbin/freeradius` i run into the same errors
