### ISSUE TITLE
Support ISC dictionaries for rlm_isc_dhcp

### ISSUE THREAD

**Issue by alandekok** [FreeRADIUS/freeradius-server#2501]
We should ideally support ISC's weird dictionary format documented here:

https://www.isc.org/wp-content/uploads/2017/08/dhcp41options.html

We have a few options:

1) punt the problem to a Perl script, which will read the ISC config and spit out a FreeRADIUS dictionary.
2) write some more C code in `rlm_isc_dhcp` to read the `option new-name code new-code = definition ;` definitions
2.1)  Make the user put these option definitions into a separate file, where they can be parsed by `mod_boostrap()`.  That function can then update the dictionaries.
2.2) Allow these options in the main ISC configuration file, in which case all of the configuration file parsing has to move from `mod_instantiate()` to `mod_bootstrap()`, so that the dictionary definitions are loaded before modules are instantiated.

My inclination is (1), as defining new options is maybe a ~10% case.  I'd do (2.1) second.  Making the user split the ISC config file manually is a tiny inconvenience.

**Comment by arr2036** [comment]
Maybe just do 1.? There's not really much advantage to adding native support for reading them?

**Comment by alandekok** [comment]
@arr2036 Yeah, the only real reason to add them is to make the transition easier from ISC to FreeRADIUS

**Comment by arr2036** [comment]
2.1 seems like it'd support someone wanting to run FreeRADIUS like an ISC DHCP server, defining their own new custom options, and for that... they can just define FreeRADIUS attributes? :)

**Comment by arr2036** [comment]
Also for DHCPv6 options get significantly more complicated.  It'd be interesting to see exactly what ISC did for that.

**Comment by alandekok** [comment]
should (mostly) be in there now.
