### ISSUE TITLE
FreeRadius3.0.16 :: RADSEC call - ERROR: SSL says error 7 : certificate signature failure

### ISSUE THREAD

**Issue by SaurabhBadhai** [FreeRADIUS/freeradius-server#2507]
Hi, 
FreeRadius3.0.16, RADSEC call.
TLS handshake is failing with the below error. 

I uploaded the CA cert in both client and server, set option in sites-enable/tls required_client_cert = no

FreeRadius3.0.16 :: RADSEC call - ERROR: SSL says error 7 : certificate signature failure

Creating attributes from certificate OIDs
Thu Feb 21 05:14:55 2019 : ERROR: (0)   ERROR: SSL says error 7 : certificate signature failure
Thu Feb 21 05:14:55 2019 : ERROR: (0) ERROR: TLS Alert write:fatal:decrypt error

I tried multiple ways and generated certificate using http://deployingradius.com/documents/configuration/certificates.html

Still I am not able to figure  out  where is the issue (Is it Openssl issue or Certificate issue). Any help would be apprciated.

Thanks,
Saurabha

**Comment by alandekok** [comment]
When you created this issue, it included a template.  You deleted the template.  And didn't read it.

FreeRADIUS comes with sample certificates that work, and certificate creation scripts that work.  Use them.  See the raddb/certs directory.

Questions belong on the freeradius-users mailing list.
