### ISSUE TITLE
Missing config file eap.conf mentioned in raddb/certs/README

### ISSUE THREAD

**Issue by Smarre** [FreeRADIUS/freeradius-server#2549]
Hi,

In raddb/certs/README, there is instructions about generating certificates, but also mentions that one should look at eap.conf for further information. For example:

`Once the final certificates have been created, you can delete the
"bootstrap" command from this directory, and delete the
"make_cert_command" configuration from the "tls" sub-section of
eap.conf.`

I can’t find that file anywhere. It either should be added or the README should be modified to not mention nonexistent file.

**Comment by arr2036** [comment]
It's now located at ``raddb/mods-available/eap``, I'll update the README
