### ISSUE TITLE
Docker container inner-tunnel EAP and outer tunnel LDAP

### ISSUE THREAD

**Issue by cyb3rc0d3** [FreeRADIUS/freeradius-server#2577]
# Issue type
Attempting to spin up a docker container to use with FreeIPA and the password + otp
Can get it to work with the default config when I attempt to change to use EAP TLS in default and inner-tunnel it comes up with error message. Have attempted following the man and online pages and any articles I could find.

[Archive.zip](https://github.com/FreeRADIUS/freeradius-server/files/2986368/Archive.zip)

- Defect - Unexpected behaviour (obvious or verified by project member).

See [here](https://github.com/FreeRADIUS/freeradius-server/blob/master/doc/bugs.md) for debugging instructions and how to obtain backtraces.

# Defect
## How to reproduce the issue

A clear and concise list of steps describing how to describe the issue.
Creating a Docker Container for using EAP-TLS in inner-tunnel.
Using the following commands:
```
docker run --name my-radius -v /var/lib/freeradius/raddb/clients.conf:/etc/raddb/clients.conf \
-v /var/lib/freeradius/raddb/mods-enabled/ldap:/etc/raddb/mods-enabled/ldap \
-v /var/lib/freeradius/raddb/mods-enabled/eap:/etc/raddb/mods-enabled/eap \
-v /var/lib/freeradius/raddb/radiusd.conf:/etc/raddb/radiusd.conf \
-v /var/lib/freeradius/raddb/sites-enabled/default:/etc/raddb/sites-enabled/default \
-v /var/lib/freeradius/raddb/sites-enabled/inner-tunnel:/etc/raddb/sites-enabled/inner-tunnel \
-v /var/lib/freeradius/certs/ca.crt:/etc/freeradius/certs/ca.crt \
-v /var/lib/freeradius/certs/dh:/etc/freeradius/certs/dh \
-v /var/lib/freeradius/certs/server.crt:/etc/freeradius/certs/server.crt \
-v /var/lib/freeradius/certs/server.key:/etc/freeradius/certs/server.key \
-p 1812-1813:1812-1813/udp -p 1812-1813:1812-1813/tcp freeradius/freeradius-server -X
```
## Output of ``[radiusd|freeradius] -X`` showing issue occurring
_(you may need to run ``[radiusd|freeradius] -fxx -l stdout`` if using eg RADIUS with TLS)_

```text
FreeRADIUS Version 3.0.18
Copyright (C) 1999-2019 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
Starting - reading configuration files ...
including dictionary file /usr/share/freeradius/dictionary
including dictionary file /usr/share/freeradius/dictionary.dhcp
including dictionary file /usr/share/freeradius/dictionary.vqp
including dictionary file /etc/freeradius/dictionary
including configuration file /etc/freeradius/radiusd.conf
including configuration file /etc/freeradius/clients.conf
including configuration file /etc/freeradius/mods-enabled/eap
including configuration file /etc/freeradius/mods-enabled/ldap
including files in directory /etc/freeradius/policy.d/
including configuration file /etc/freeradius/policy.d/abfab-tr
including configuration file /etc/freeradius/policy.d/accounting
including configuration file /etc/freeradius/policy.d/canonicalization
including configuration file /etc/freeradius/policy.d/control
including configuration file /etc/freeradius/policy.d/cui
including configuration file /etc/freeradius/policy.d/debug
including configuration file /etc/freeradius/policy.d/dhcp
including configuration file /etc/freeradius/policy.d/eap
including configuration file /etc/freeradius/policy.d/filter
including configuration file /etc/freeradius/policy.d/moonshot-targeted-ids
including configuration file /etc/freeradius/policy.d/operator-name
including configuration file /etc/freeradius/policy.d/rfc7542
including configuration file /etc/freeradius/sites-enabled/default
including configuration file /etc/freeradius/sites-enabled/inner-tunnel
main {
 security {
        allow_core_dumps = no
 }
        name = "radiusd"
        prefix = "@prefix@"
        localstatedir = "@localstatedir@"
        logdir = "@logdir@"
        run_dir = "@localstatedir@/run/radiusd"
}
main {
        name = "radiusd"
        prefix = "@prefix@"
        localstatedir = "@localstatedir@"
        sbindir = "@sbindir@"
        logdir = "@logdir@"
        run_dir = "@localstatedir@/run/radiusd"
        libdir = "@libdir@"
        radacctdir = "@radacctdir@"
        hostname_lookups = yes
        max_request_time = 30
        cleanup_delay = 5
        max_requests = 16384
        pidfile = "@localstatedir@/run/radiusd/radiusd.pid"
        checkrad = "@sbindir@/checkrad"
        debug_level = 0
        proxy_requests = yes
 log {
        stripped_names = no
        auth = no
        auth_badpass = no
        auth_goodpass = no
        colourise = yes
        msg_denied = "You are already logged in - access denied"
 }
 resources {
 }
 security {
        max_attributes = 200
        reject_delay = 0.000000
        status_server = no
 }
}
radiusd: #### Loading Realms and Home Servers ####
radiusd: #### Loading Clients ####
 client test {
        ipaddr = 192.168.72.133
        require_message_authenticator = no
        secret = <<< secret >>>
  limit {
        max_connections = 16
        lifetime = 0
        idle_timeout = 30
  }
 }
 client test {
        ipaddr = 192.168.72.133
        require_message_authenticator = no
        secret = <<< secret >>>
  limit {
        max_connections = 16
        lifetime = 0
        idle_timeout = 30
  }
 }
Ignoring duplicate client 192.168.72.133
Debug state unknown (cap_sys_ptrace capability not set)
systemd watchdog is disabled
 # Creating Auth-Type = pap
radiusd: #### Instantiating modules ####
 modules {
  # Loaded module rlm_eap
  # Loading module "eap" from file /etc/freeradius/mods-enabled/eap
  eap {
        default_eap_type = "tls"
        timer_expire = 60
        ignore_unknown_eap_types = no
        cisco_accounting_username_bug = no
        max_sessions = 2048
  }
  # Loaded module rlm_ldap
  # Loading module "ldap" from file /etc/freeradius/mods-enabled/ldap
  ldap {
        server = "ipa.test.local"
        port = 636
        identity = "uid=binder,cn=users,cn=accounts,dc=test,dc=local"
        password = <<< secret >>>
   sasl {
   }
   user {
        scope = "sub"
        access_positive = yes
    sasl {
    }
   }
   group {
        filter = "(objectClass=posixGroup)"
        scope = "sub"
        name_attribute = "cn"
        membership_attribute = "memberOf"
        cacheable_name = no
        cacheable_dn = no
   }
   client {
        scope = "sub"
        base_dn = ""
   }
   profile {
   }
   options {
        ldap_debug = 0
        chase_referrals = yes
        rebind = yes
        net_timeout = 10
        res_timeout = 10
        srv_timelimit = 3
        idle = 60
        probes = 3
        interval = 3
   }
   tls {
        start_tls = no
        require_cert = "allow"
   }
  }
Creating attribute LDAP-Group
  instantiate {
  }
  # Instantiating module "eap" from file /etc/freeradius/mods-enabled/eap
/etc/freeradius/mods-enabled/eap[1]: Failed to find 'Auth-Type EAP' section.  Cannot authenticate users.
/etc/freeradius/mods-enabled/eap[1]: Instantiation failed for module "eap"
```
## Full backtrace from LLDB or GDB

```text
COPY/PASTE OUTPUT HERE (WITHIN BACKTICKS).  NO PASTEBIN (ET AL) LINKS!
```

**Comment by arr2036** [comment]
You've deleted the eap module from the authenticate section in your default virtual serve.

**Comment by cyb3rc0d3** [comment]
Hi I checked and it wasn’t deleted

**Comment by cyb3rc0d3** [comment]
Even does this with the default config on the default file

**Comment by cyb3rc0d3** [comment]
> You've deleted the eap module from the authenticate section in your default virtual server.

its not deleted even with the default config

**Comment by arr2036** [comment]
What about the inner-tunnel virtual server?

**Comment by cyb3rc0d3** [comment]
Seems to have been a discrepancy with the docker container and what it would need to work with the freeipa on the same server. Got it working with the following default as it actually is commented out like @arr2036 said. Uncommenting it in the default site got it working.
My working config
'''
server default {
listen {
		type = auth
		ipaddr = *
		 port = 0
		 limit {
		 	max_connections = 16
		 	lifetime = 0
		 	  idle_timeout = 30
        }
}
listen {
        ipaddr = *
#       ipv6addr = ::
        port = 0
        type = acct
                limit {
                        }
}

listen {
        ipv6addr = ::
        port = 0
        type = acct

        limit {
        }
}

authorize {
			filter_username
			chap
        	mschap
        	suffix
        	eap {
                ok = return
#               updated = return
			}
			-ldap
			expiration
        	logintime
        	pap
        }
}
authenticate {
        #
        #  PAP authentication, when a back-end database listed
        #  in the 'authorize' section supplies a password.  The
        #  password can be clear-text, or encrypted.
        Auth-Type PAP {
                pap
        }
        Auth-Type eap {
               eap {
                       handled = 1
               }
               if (handled && (Response-Packet-Type == Access-Challenge)) {
                       attr_filter.access_challenge.post-auth
                       handled  # override the "updated" code from attr_filter
               }
        }
        Auth-Type LDAP {
               ldap
       }
}

preacct {
        preprocess
        acct_unique
        suffix
}


accounting {
		unix
		#-sql
		exec
		detail
		attr_filter.accounting_response
}

session {
		#sql
}

post-auth {

if (session-state:User-Name && reply:User-Name && request:User-Name && (reply:User-Name == request:User-Name)) {
                update reply {
                        &User-Name !* ANY
                }
        }
        update {
                &reply: += &session-state:
        }
        exec
        remove_reply_message_if_eap
        Post-Auth-Type REJECT {
                #-sql
                attr_filter.access_reject
                eap
                        }

        Post-Auth-Type Challenge {
			    attr_filter.access_challenge.post-auth
        }

}

pre-proxy {
}

post-proxy {
		eap
}
}
'''

**Comment by cyb3rc0d3** [comment]
Needed a completely diff config as it needed to do the eap tls for Windows

**Comment by cyb3rc0d3** [comment]
Will upload when I get home
