### ISSUE TITLE
802.1x users, using Freeradius 2.6 peap/mschapv2 but cannot verification active directory ldap

### ISSUE THREAD

**Issue by uzel42** [FreeRADIUS/freeradius-server#2582]
Hi, 

Iam using freeradius 2.6 and active directory ldap.
My users 802.1x settings is eap ttls/pap. Everythink is ok!

But i want  my users use peap/mschapv2 settings.
Active directory dont accept peap/mschapv2

what should I do? Thank for all answers

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.  The instructions for a new PR tell you this.

You need to READ THE DOCUMENTATION, otherwise you will not be able to solve any problem.
