### ISSUE TITLE
3.0.18 rbtree.c parent variable could be dereferenced when NULL

### ISSUE THREAD

**Issue by ScottShen-Syd** [FreeRADIUS/freeradius-server#2585]
src/lib/rbtree.c

line 478, the **parent** could be NULL, and when it's NULL, the direct dereference inside **delete_fixup** will lead to a core dump.

338 static void delete_fixup(rbtree_t *tree, rbnode_t *x, rbnode_t *parent)
339 {
340
341     while (x != tree->root && x->colour == BLACK) {
342         if (x == **parent**->left) {
...

474     } else {
475         if (tree->free) tree->free(y->data);
476
477         if (y->colour == BLACK)
478             delete_fixup(tree, x, **parent**);
479
480         talloc_free(y);

Checked in the latest Version 3.0.18, the issue is still there.

**Comment by alandekok** [comment]
No, parent can't be NULL.  That's why there's the "sentinel" node, or `NIL`.

**Comment by ScottShen-Syd** [comment]
When the **z** is the root node (BLACK) with two NIL children (BLACK leaves ).

At line 417, **y = z**
At line 432, **parent = y->parent;** isn't that the parent will be NULL

**Comment by ScottShen-Syd** [comment]
Hi Alan

I commented with more details, can you please have a look and confirm?

Thanks
SS

**Comment by alandekok** [comment]
Maybe. I'll push some changes.
