### ISSUE TITLE
3.0.18 Identical code in src/lib/packet.c

### ISSUE THREAD

**Issue by ScottShen-Syd** [FreeRADIUS/freeradius-server#2587]
784 #undef ID_i
 785 #undef ID_j
 786 #undef ID_k
 **787         if (fd >= 0) break;
 788         break;**

Not sure if this is a typo or meant to have some other checks.
In release 3.0.18, line 787 is not necessary? line 788 will break anyway, regardless the value of fd.

**Comment by alandekok** [comment]
While these comments are nice, what is your goal here?

Are there real bugs you are trying to fix?  Are there real features you are trying to add?

**Comment by ScottShen-Syd** [comment]
Thanks Alan
