### ISSUE TITLE
4.0.x - fr_value_box_from_str - incorrect conversion to FR_TYPE_ETHERNET from an integer value

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#2596]
# Issue type
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect

Probably incorrect behaviour in function fr_value_box_from_str, for a conversion to FR_TYPE_ETHERNET from an integer value.

I think there might be a bug here:

https://github.com/FreeRADIUS/freeradius-server/blob/master/src/lib/util/value.c#L3946

```text
uint64_t uint32 = htonll(atoll(in));
```

With this, any integer lower than 65536 is converted to "00:00:00:00:00:00".

Proposed fix:

```text
uint64_t uint32 = htonll(atoll(in) << 16);
```

E.g. 258 => "00:00:00:00:01:02".

Also, why is a uint64_t named "uint32" ? this is... confusing :)

**Comment by alandekok** [comment]
The issue is that the `memcpy()` was copying the high bytes and not the low bytes.  Fixing that is the better approach.

And I've renamed the variable to `lvalue`

**Comment by nchaigne** [comment]
Thanks Alan :)
