### ISSUE TITLE
Unable to start radius service

### ISSUE THREAD

**Issue by suryashetty** [FreeRADIUS/freeradius-server#2612]
Hi
I have insstalled the free radius 3.0.19 version for captive portal integration.
i have created simlinks as below 
sudo ln -s /etc/raddb/mods-available/sql /etc/raddb/mods-enabled/sql
sudo ln -s /etc/raddb/mods-available/sqlcounter /etc/raddb/mods-enabled/sqlcounter
 and exceuted the following command to test the flow
sudo /usr/sbin/radiusd -X

but it is throwing exception with logs:
 
including configuration file /etc/raddb/proxy.conf
including configuration file /etc/raddb/clients.conf
including files in directory /etc/raddb/mods-enabled/
including configuration file /etc/raddb/mods-enabled/attr_filter
including configuration file /etc/raddb/mods-enabled/sradutmp
including configuration file /etc/raddb/mods-enabled/soh
including configuration file /etc/raddb/mods-enabled/unpack
including configuration file /etc/raddb/mods-enabled/always
including configuration file /etc/raddb/mods-enabled/detail.log
including configuration file /etc/raddb/mods-enabled/exec
including configuration file /etc/raddb/mods-enabled/expr
including configuration file /etc/raddb/mods-enabled/pap
including configuration file /etc/raddb/mods-enabled/cache_eap
including configuration file /etc/raddb/mods-enabled/logintime
including configuration file /etc/raddb/mods-enabled/dynamic_clients
including configuration file /etc/raddb/mods-enabled/files
including configuration file /etc/raddb/mods-enabled/digest
including configuration file /etc/raddb/mods-enabled/ntlm_auth
including configuration file /etc/raddb/mods-enabled/date
including configuration file /etc/raddb/mods-enabled/utf8
including configuration file /etc/raddb/mods-enabled/unix
including configuration file /etc/raddb/mods-enabled/chap
including configuration file /etc/raddb/mods-enabled/sqlcounter
**/etc/raddb/mods-enabled/sqlcounter[43]: Reference "${modules.sql.dialect}" not found
/etc/raddb/mods-enabled/sqlcounter[52]: Reference "${modconfdir}/sql/counter/${dialect}/${.:instance}.conf" points to a variable which has not been expanded.**
Errors reading or parsing /etc/raddb/radiusd.conf
I can see the similar issues opened already
(https://github.com/FreeRADIUS/freeradius-server/issues/2020) but i doesnot provide fix. Is the issue still exists, if not can i know how to fix it ?
The instantiate section of radiusd.conf file is as below (added sql first and sqlcounter at next by taking other website references) but still I am getting same issues
instantiate {
     sql
    sqlcounter
    chillispot_max_bytes
     noresetcounter
}

**Comment by alanbuxey** [comment]
hi,

you've defined the dialect in the sql mods-enabled file ?

you have present , in your RADDB directory, the mods-config/sql directory
and all its config?

alan

**Comment by suryashetty** [comment]
Hi Alan,
 Thanks for the reply, Yes I have dialect in the sql mods-enabled file
In /etc/raddb/sql
        # database the logged queries are going to be executed against.
        dialect = "mysql"
        # Connection info:
In /etc/raddb/sqlcounter 
        sqlcounter dailycounter {
        sql_module_instance = sql
        **dialect = ${modules.sql.dialect}**
        ----------
		----------
        $INCLUDE ${modconfdir}/sql/counter/${dialect}/${.:instance}.conf
}

sqlcounter monthlycounter {
        sql_module_instance = sql
        **dialect = ${modules.sql.dialect}**
        ----------
		----------
        reset = monthly
        $INCLUDE ${modconfdir}/sql/counter/${dialect}/${.:instance}.conf
}

sqlcounter noresetcounter {
        sql_module_instance = sql
        **dialect = ${modules.sql.dialect}**
        ----------
		----------
        $INCLUDE ${modconfdir}/sql/counter/${dialect}/${.:instance}.conf
}

and one more point, the above issue is fixed when I surf on other forums one of it suggest as follows 
In /etc/raddb/radiusd.conf file of the module section Instead of 
  $INCLUDE mods-enabled/
Place all the entities individually like
 
           $INCLUDE mods-enabled/always
           $INCLUDE mods-enabled/attr_filter
			$INCLUDE mods-enabled/cache_eap
			$INCLUDE mods-enabled/chap
			$INCLUDE mods-enabled/date
			$INCLUDE mods-enabled/detail
			$INCLUDE mods-enabled/detail.log
			$INCLUDE mods-enabled/dhcp
			$INCLUDE mods-enabled/digest
			$INCLUDE mods-enabled/dynamic_clients
			$INCLUDE mods-enabled/eap
			$INCLUDE mods-enabled/echo
			$INCLUDE mods-enabled/exec
			$INCLUDE mods-enabled/expiration
			$INCLUDE mods-enabled/expr
			$INCLUDE mods-enabled/files
			$INCLUDE mods-enabled/linelog
			$INCLUDE mods-enabled/logintime
			$INCLUDE mods-enabled/mschap
			$INCLUDE mods-enabled/ntlm_auth
			$INCLUDE mods-enabled/pap
			$INCLUDE mods-enabled/passwd
			$INCLUDE mods-enabled/preprocess
			$INCLUDE mods-enabled/radutmp
			$INCLUDE mods-enabled/realm
			$INCLUDE mods-enabled/replicate
			$INCLUDE mods-enabled/soh
			$INCLUDE mods-enabled/sql
			$INCLUDE mods-enabled/sqlcounter
			$INCLUDE mods-enabled/sradutmp
			$INCLUDE mods-enabled/unix
			$INCLUDE mods-enabled/unpack
			$INCLUDE mods-enabled/utf8
Thus,I have modified the radius config file and now after this when i execute the command
 **sudo /usr/sbin/radiusd -X**
  i am getting a different error 
  
 /etc/raddb/mods-enabled/always[35]: Failed loading module rlm_always from file /usr/lib64/freeradius/rlm_always.so
/etc/raddb/mods-enabled/always[35]: Application and rlm_always magic number (prefix) mismatch.  application: 0 module: f4
 do you have any idea about this
 
 thanks
 Surya

**Comment by jpereira** [comment]
As can be seen in.

```
/etc/raddb/mods-enabled/always[35]: Failed loading module rlm_always from file /usr/lib64/freeradius/rlm_always.so
/etc/raddb/mods-enabled/always[35]: Application and rlm_always magic number (prefix) mismatch. application: 0 module: f4
```
Probably you have more than one bundle installed in your system or if you installed from the source code, probably overwrite some old installed version. try something like `find / -name rlm_always.so` to see if have more than one.

ps: It is not an issue/but, then it should be reported in freeradius-users@ mailing list.
