### ISSUE TITLE
eap ttls mschapv2 : after 802.1x client received MS-CHAP2-Success ,client send ack,then can not recevie eap success(received EAP-TTLS request frame)

### ISSUE THREAD

**Issue by ch664** [FreeRADIUS/freeradius-server#2634]
Hi,
I'm using freeradius 3.0.18 .
I used 802.1x client settings eap ttls/mschapv2. 
after received MS-CHAP2-Success request，I sends an EAP-TTLS packet to the TTLS server containing no data .
client can receive a TTLS Request msg, and can't receive EAP Success.
this page not containing the length field:
![image](https://user-images.githubusercontent.com/49938277/56724909-764feb00-677e-11e9-8085-1156f718a1a6.png)
this page containing the length field:
![image](https://user-images.githubusercontent.com/49938277/56725237-10b02e80-677f-11e9-8db7-f25c199e9625.png)

what should I do? Thank for all answers

**Comment by alandekok** [comment]
Please give a better description of the problem.  Which supplicant are you using?  And also post the debug output from FreeRADIUS.

**Comment by ch664** [comment]
The supplicant is my own program, after MS-CHAP2-Success AVP request from radius received，I send an EAP-TTLS packet without data as response,
Now I am not sure the response [packet](url) is rational, because the radius does't reply a EAP-SUCCESS packet.

debug info and frame info see ttls.mschap2.test.zip:
[ttls mschap2 test.zip](https://github.com/FreeRADIUS/freeradius-server/files/3119540/ttls.mschap2.test.zip)

**Comment by herwinw** [comment]
> The supplicant is my own program

Does the setup work with eapol_test as client? I actually expect the error to be on the client side here, given the complexity of the EAP/TTLS-protocol and the fact that these server setups work with other clients.

Also, there is a lot of information in the debug log (as @alandekok already mentioned), it often shows why the server sends a certain type of response.

**Comment by ch664** [comment]
freeradius debug log in "ttl mschap2 test.zip", and from the log ,the code execute enters the  tls_ack_handler() and return  "FR_TLS_REQUEST" ,I think it's wrong to enter this function. @alandekok  @herwinw 
```c
/*
	 *	check for ACK
	 *
	 *	If there's no TLS data, or there's 1 byte of TLS data,
	 *	with the flags set to zero, then it's an ACK.
	 *
	 *	Find if this is a reply to the previous request sent
	 */
	if ((!eaptls_packet) || ((eap_ds->response->length == EAP_HEADER_LEN + 2) &&
	     ((eaptls_packet->flags & 0xc0) == 0x00))) 
	{

		if (prev_eap_ds && (prev_eap_ds->request->id == eap_ds->response->id)) 
		{
			return tls_ack_handler(handler->opaque, request);
		} 
		else 
		{
			REDEBUG("Received Invalid TLS ACK");
			return FR_TLS_INVALID;
		}
	}
```

**Comment by alandekok** [comment]
I'm inclined to put this down to a broken supplicant.  The response shouldn't be an empty ACK.

**Comment by ch664** [comment]
In fact this problem has been bothering me for a long time, I have tried to send a PW_MSCHAP2_SUCCESS avp with no data as response, the packet seem incorrect either, you mean the response shouldn't be an empty ACK, how should I package this response message, can you give me more detailed instructions or referenced documents, thank you very much for your help @alandekok

**Comment by alandekok** [comment]
If you want to see how the exchange should work, use `eapol_test`.  And then run FreeRADIUS in debugging mode.
