### ISSUE TITLE
ERX-Acct-Request-Reason field type?

### ISSUE THREAD

**Issue by raybellis** [FreeRADIUS/freeradius-server#2635]
I'm writing a parser for the RADIUS dictionary files, and observed that the `ERX-Acct-Request-Reason` attribute (4874.210) is defined as `octets` but also appears to have defined values.

This seems inconsistent - surely the field should have one of the integer field types?  Without knowing the field width there'd be no way to match a value.

**Comment by alandekok** [comment]
Yup, that's wrong.  I pushed a fix.  Commit  6091001c51c

**Comment by alandekok** [comment]
Ideally, the FreeRADIUS parser should catch this and complain.  But we're not going to change that in v3.  We will look into fixing that in v4 / "master" branch.
