### ISSUE TITLE
4.0.x - fr_pair_copy - VT_XLAT is not handled properly

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#2672]
# Issue type
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect

In function fr_pair_copy, the following code which handles XLAT is incorrect:

```text
	if (vp->type == VT_XLAT) {
		n->xlat = talloc_typed_strdup(n, n->xlat);
		return n;
	}
```

Two issues:
- the new value pair type is not set to VT_XLAT
- the dup does not use the correct pointer (n->xlat should be vp->xlat)

Proposed fix:

```text
	if (vp->type == VT_XLAT) {
		n->type = VT_XLAT;
		n->xlat = talloc_typed_strdup(n, vp->xlat);
		return n;
	}
```

**Comment by nchaigne** [comment]
Thanks for the commit.

It seems this is not enough. I was focused on the XLAT case, but there is also an issue for other types (e.g. DATA).

I think we should have, in all cases:

	n->type = vp->type;

**Comment by alandekok** [comment]
yes.  I'll push a fix.
