### ISSUE TITLE
sqlcounter expire_on_login mysql freeradius 

### ISSUE THREAD

**Issue by khokooli** [FreeRADIUS/freeradius-server#2675]
### sqlcounter expire_on_login mysql freeradius rlm_sqlcounter

i'm trying to set access period time by first login of client 
first i enable sqlcounter module in mode-enable folder 
os version : ubuntu18.04
freeradius version : 3.0.16
the sqlcounter file contain following :

```
#/etc/freeradius/3.0/mods-enabled/sqlcounter
sqlcounter expire_on_login {
        sql_module_instance = sql
        dialect = mysql

        counter_name = Expire-After-Initial-Login
        check_name = Expire-After
        key = User-Name
        reset = never      
        query = "\
              SELECT IFNULL( MAX(TIME_TO_SEC(TIMEDIFF(NOW(), acctstarttime))),0) \
              FROM radacct \
              WHERE UserName='%{${key}}' \
              ORDER BY acctstarttime \
              LIMIT 1;"
}

```
and in `/etc/freeradius/3.0/sites-available/default` file i add the following under  `authorize {`
`expire_on_login`

after i add restriction in radchceck table in phpmyadmin by following code : 

`INSERT INTO radcheck ( id , UserName , Attribute , op , Value ) VALUES (NULL , 'zaib', 'Expire-After', '=', '3600');`

and finally test the user access by following command : 
`radtest zaib zaib localhost 1812 testing123`

result is : 
```
	User-Name = "zaib"
	User-Password = "zaib"
	NAS-IP-Address = 192.168.22.101
	NAS-Port = 1812
	Message-Authenticator = 0x00
	Cleartext-Password = "zaib"
Received Access-Reject Id 167 from 127.0.0.1:1812 to 0.0.0.0:0 length 20
(0) -: Expected Access-Accept got Access-Reject

```
in `freeradius -xxX` log output i see : 

`Fri May 10 18:56:30 2019 : WARNING: (0) expire_on_login: Couldn't find check attribute, control:Expire-After, doing nothing...`
and also : 
`Fri May 10 18:56:30 2019 : ERROR: (0) No Auth-Type found: rejecting the user via Post-Auth-Type = Reject`

i tried to change `op` option in sql from `= `to `:=` and after that i get following results:
```
Sent Access-Request Id 72 from 0.0.0.0:42845 to 127.0.0.1:1812 length 74
	User-Name = "zaib"
	User-Password = "zaib"
	NAS-IP-Address = 192.168.22.101
	NAS-Port = 1812
	Message-Authenticator = 0x00
	Cleartext-Password = "zaib"
Received Access-Accept Id 72 from 127.0.0.1:1812 to 0.0.0.0:0 length 39
	Mikrotik-Rate-Limit = "1024k/1024k"


```

its seems fine but restriction doesn't work at all , user can access after end of period 

in free radius log i see :
`Fri May 10 18:56:30 2019 : WARNING: (0) expire_on_login: Couldn't find check attribute, control:Expire-After, doing nothing...`

and also in mysql radacct table when user is logged in i can see acctstarttime value its like this : `2019-05-10 15:20:46`

any idea how to fix this ?
please help me , thanks

**Comment by alandekok** [comment]
Debugging questions belong on the freeradius-users mailing list.

For debugging this, read the debug output.   And read the SQL howto:  https://wiki.freeradius.org/guide/SQL%20HOWTO

Hint: don't use `=`.  Use `:=`
