### ISSUE TITLE
reserved c++ keyword

### ISSUE THREAD

**Issue by pavzia** [FreeRADIUS/freeradius-server#2693]
I built freeradius-client-release_1_1_7 from source with no problems.

However when building a c++ starter application:
#include <iostream>

#include <freeradius/libradius.h>
#include <freeradius/conf.h>
#include <freeradius/radpaths.h>

static char  const *radius_dir = RADDBDIR;
static char  const *dict_dir = DICTDIR;

int main(int argc, char **argv)
{
  if (fr_check_lib_magic(RADIUSD_MAGIC_NUMBER) < 0) {
    fr_perror("radclient");
    return 1;
  }
  
  return 0;
}

I get compiler errors:

/usr/include/freeradius/libradius.h:189:25: error: ‘<anonymous>’ declared as a ‘virtual’ field
  unsigned int virtual : 1;    //!< for dynamic expansion

As a C program there is no problem

caused by the fact that the struct element virtual collides with a C++ reserved keyword

**Comment by alandekok** [comment]
I think you mean that you're trying to build using the "libfreeradius" code from FreeRADIUS version 1.1.7.  That code is a decade out of date, and is entirely unsupported.

Please use a modern release, such as https://github.com/FreeRADIUS/freeradius-client/

**Comment by pavzia** [comment]
wow, down the rabbit hole of obsolete but readily available code.  I had used 1.1.7 because it what was on https://freeradius.org/sub_projects/ if that is obsolete it should be removed.

I rebuilt from git hub, and now I can't compile radexample.c

From README.radexample:
You only need to include freeradius-client.h into your applications and link...

That is nice and simple but early in the source code there is:

#include        <includes.h>
#include        <freeradius-client.h>
#include        <pathnames.h>

but includes.h and pathnames.h were never installed.

so where can I find a client example that I can model my application from ?

**Comment by alandekok** [comment]
> I had used 1.1.7 because it what was on https://freeradius.org/sub_projects/

You downloaded the *server* version of 1.1.7.  Not the *freeradius-client* software.

The client comes with radexample.  and full documentation for how to use it.
