### ISSUE TITLE
How to fix 'make'  error

### ISSUE THREAD

**Issue by rupadana** [FreeRADIUS/freeradius-server#2737]
Makefile:25: recipe for target 'eap_tls.lo' failed
make[7]: *** [eap_tls.lo] Error 1
make[7]: Leaving directory '/root/freeradius-server-2.2.10/src/modules/rlm_eap/libeap'
Makefile:54: recipe for target 'libeap' failed
make[6]: *** [libeap] Error 2
make[6]: Leaving directory '/root/freeradius-server-2.2.10/src/modules/rlm_eap'
Makefile:37: recipe for target 'rlm_eap' failed
make[5]: *** [rlm_eap] Error 2
make[5]: Leaving directory '/root/freeradius-server-2.2.10/src/modules'
Makefile:12: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/root/freeradius-server-2.2.10/src/modules'
Makefile:39: recipe for target 'modules' failed
make[3]: *** [modules] Error 2
make[3]: Leaving directory '/root/freeradius-server-2.2.10/src'
Makefile:14: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/root/freeradius-server-2.2.10/src'
Makefile:97: recipe for target 'src' failed
make[1]: *** [src] Error 2
make[1]: Leaving directory '/root/freeradius-server-2.2.10'
Makefile:18: recipe for target 'all' failed
make: *** [all] Error 2

how to fix that error?

**Comment by alandekok** [comment]
You've deleted the *actual* error.  Which makes it impossible to know what's going on.

In short, don't use v2.  It's old and unsupported.  Use v3.   See http://packages.networkradius.com for pre-built packages.
