### ISSUE TITLE
Avoid duplicated policy entries

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#2738]
# Issue type
- Defect - Unexpected behavior (obvious or verified by project member).

# Defect
## How to reproduce the issue

Today we are allowing the user to redeclare a policy entry.

```text
[root@docker-freeradius-ubuntu16 freeradius-server-master.git]# grep ^filter_password -A4 /opt/freeradius4/etc/raddb/policy.d/filter 
filter_password {
	if (&User-Password && \
	   (&User-Password != "%{string:User-Password}")) {
		update request {
			&Tmp-String-0 := "%{string:User-Password}"
--
filter_password {
	accept
}

[root@docker-freeradius-ubuntu16 freeradius-server-master.git]#
```

It will cause a false-positive behavior. then, we should verify and raise an error if exist any policy name duplicated.

**Comment by jpereira** [comment]
What do you think @alandekok ?

**Comment by arr2036** [comment]
It's not clear that this is incorrect behaviour, I'm pretty ambivalent... If the first entry took precedence then I'd be absolutely on the side of it being a defect, as the second entry takes precedence, then there could be some use in keeping this to allow site specific overrides, i.e. for some configurations include a local policy.d directory after the main raddb/policy.d directory.

**Comment by arr2036** [comment]
I guess behaviour with modules sets precedence.  We don't allow two modules with the same instance name? Or at least I hope we don't.

**Comment by jpereira** [comment]
@arr2036 we do not allow to declare the same module instance twice.

e.g: I replicate the `linelog log_accounting { ...}` entry and the result is:

`Tue Jun 11 01:34:11 2019: Duplicate module "log_accounting" in file /opt/freeradius4/etc/raddb/mods-enabled/linelog[405] and file /opt/freeradius4/etc/raddb/mods-enabled/linelog[372]`

so, in my perspective, we should do the same behavior for policies. Based on my experience today, it was terrible to figure out that the same policy was duplicated. (I never imagined that it could be the reason)

**Comment by arr2036** [comment]
That definitely makes it more in favour of disallowing duplicate policies
