### ISSUE TITLE
problem with Simultaneous-Use roaming

### ISSUE THREAD

**Issue by mustafanass** [FreeRADIUS/freeradius-server#2742]
### Issues type .

- **Simultaneous-Use disconnect when client move from ap to other.**
### issues  description .

 have problem with 802.1X , i have multi openwrt access point all it work with wpa2-enterprise and freeradius server with mysql in other side , in freeradius i enable Simultaneous-Use my problem is when my users move from first ap to second or to third ap its disconnect and reconnect and in some time its take over 10-30 second to reconnect successful . i set ideal time-out 1s and life-time 1s . its reconnect faster than first one , but its stay disconnect when they move , any idea ?
Note: when i disable Simultaneous-Use its work fine and client stay connect but when i enable it i see this problem .
Note: I use value 1 for Simultaneous-Use .

**Comment by alandekok** [comment]
The instructions you deleted (and likely didn't read) say that configuration questions belong on the freeradius-users mailing list.

Reading documentation is a good idea.
