### ISSUE TITLE
Freeradius 3.0.19 - openssl 1.1.1 Ubuntu 18.04

### ISSUE THREAD

**Issue by fettfoen** [FreeRADIUS/freeradius-server#2746]
# Issue type
- **Ubuntu 18.04 64 Bit**.
- **Freeradius 3.0.19**.

Hello i have the following issue. I updated my Ubuntu 18.04 (apt update, apt upgrade) server. Openssl was patched from 1.1.0g-2ubuntu4.3 to 1.1.1-1ubuntu2.1~18.04.2.

Now freeradius wont start.

Debug shows:

radiusd -X

**libssl version mismatch.  built: 1010007f linked: 1010100f**

**Comment by arr2036** [comment]
Raise an issue with the ubuntu package managers.  They need to rebuild their FreeRADIUS package against OpenSSL 1.1.1.
