### ISSUE TITLE
Aerohive reference missing

### ISSUE THREAD

**Issue by bjry** [FreeRADIUS/freeradius-server#2756]
# Issue type
- Reference to the aerohive dictionary is missing in the main dictionary file.

***
- Feature request.

**Comment by jpereira** [comment]
the dictionary exists in v3.x https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/share/dictionary.aerohive

**Comment by bjry** [comment]
Yes the dictionary itself exists, but its not referenced in 
https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/share/dictionary
