### ISSUE TITLE
Alpine Image fails to find libpython

### ISSUE THREAD

**Issue by DomAmato** [FreeRADIUS/freeradius-server#2766]
# Issue type

***

- Defect - Crash or memory corruption.

# Defect/Feature description
## How to reproduce issue
The docker image for alpine linux does not seem to work with python modules. It works with the ubuntu bionic image (latest) from dockerhub but ive tried installing python2, py-pip, python2-dev and it always ends up with the output below.

Try adding a python module and getting the server to start. My module looks like so

```
python magic {
	module = radiusauth

	python_path = /usr/app/agent/magic/radius:/usr/lib/python2.7:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages

	mod_authorize = ${.module}
	func_authorize = authorize

	mod_authenticate = ${.module}
	func_authenticate = authenticate

}
```

The library exists, running `ldd /usr/bin/python` produces

```
/lib/ld-musl-x86_64.so.1 (0x7f8c0ef74000)
libpython2.7.so.1.0 => /usr/lib/libpython2.7.so.1.0 (0x7f8c0edca000)
libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f8c0ef74000)
```

`ENV LD_LIBRARY_PATH /usr/lib/python2.7/config:/usr/lib:/lib`

I have tried updating the LD_LIBRARY_PATH like most answers I've come across but to no avail
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring
(you may need to run ``[radiusd|freeradius] -fxx -l stdout`` if using eg RADIUS with TLS)

```text
reading pairlist file /opt/etc/raddb/mods-config/files/pre-proxy
  # Instantiating module "expiration" from file /opt/etc/raddb/mods-enabled/expiration
  # Instantiating module "reject" from file /opt/etc/raddb/mods-enabled/always
  # Instantiating module "fail" from file /opt/etc/raddb/mods-enabled/always
  # Instantiating module "ok" from file /opt/etc/raddb/mods-enabled/always
  # Instantiating module "handled" from file /opt/etc/raddb/mods-enabled/always
  # Instantiating module "invalid" from file /opt/etc/raddb/mods-enabled/always
  # Instantiating module "userlock" from file /opt/etc/raddb/mods-enabled/always
  # Instantiating module "notfound" from file /opt/etc/raddb/mods-enabled/always
  # Instantiating module "noop" from file /opt/etc/raddb/mods-enabled/always
  # Instantiating module "updated" from file /opt/etc/raddb/mods-enabled/always
  # Instantiating module "detail" from file /opt/etc/raddb/mods-enabled/detail
  # Instantiating module "magic" from file /opt/etc/raddb/mods-enabled/python-magic
Python version: 2.7.16 (default, May  6 2019, 19:28:45)  [GCC 8.3.0]
Libpython is not found among linked libraries
Failed loading libpython symbols into global symbol table
Fatal Python error: PyThreadState_Get: no current thread
```

**Comment by mcnewton** [comment]
Please read the README ("Image variants" section). Large or uncommonly used things are not installed in the alpine image to keep it small. You need to pull it in yourself.

**Comment by DomAmato** [comment]
But thats what the issue is... According to the [readme](https://github.com/FreeRADIUS/freeradius-server/tree/v3.0.x/scripts/docker#freeradiusfreeradius-serverversion-alpine) it says you need to add it with `apk add` and its still not working. I thought I was being dumb and missed something and realized there is also the `freeradius-python` alpine package but adding that doesn't fix the issue either. Here is the dockerfile from my most recent build: 

```
FROM freeradius/freeradius-server:latest-alpine

RUN apk update && apk add freeradius-python python2 py-pip

# Fixes ImportError (No module named builtins) for python 2
RUN pip install future

# Set the install location for the agent
ARG MAGIC_LOC=/usr/app/agent
ENV MAGIC_LOC ${MAGIC_LOC}
WORKDIR ${MAGIC_LOC}

# Copy all the files we actually need to run the agents
COPY magic/radius magic/radius
COPY magic/utils/authobject.py magic/radius/authobject.py

# Move the resources into place
COPY magic/resources magic/resources
RUN mv ./magic/resources/inner-tunnel /etc/raddb/sites-enabled/inner-tunnel
RUN mv ./magic/resources/python-magic /etc/raddb/mods-enabled/python-magic
RUN sed -i "s@MAGIC_LOC@"${MAGIC_LOC}"@g" /etc/raddb/mods-enabled/python-magic
RUN mv ./magic/resources/eap /etc/raddb/mods-enabled/eap
RUN mv ./magic/resources/clients.conf /etc/raddb/clients.conf

COPY ssl/* /etc/raddb/certs/

CMD ["freeradius", "-X"] # Set default command
```

Also the documentation isn't clear on what you all need to pull in. I would have thought installing python and the freeradius-python packages would be sufficient but its clearly not and there isn't much to go off of unless its really buried somewhere.

**Comment by mcnewton** [comment]
It won't be freeradius-python (or any other Alpine packages, for that matter) - that's supplied by the Alpine project and is likely to clash with FreeRADIUS built in the docker image.

Have you tried python2-dev? That's what it's built against.

None of us use Alpine, so it's just provided as a convenience for people who really need small images. If you need some of the larger dependencies you're probably better off sticking with the standard Ubuntu-based image.

**Comment by mcnewton** [comment]
A workaround is to `apk add python2-dev` (which is needed for the python library, it's not actually in the `python2` package) and export `LD_PRELOAD=/usr/lib/libpython2.7.so`.

**Comment by DomAmato** [comment]
actually you solved my issue. You don't need python2-dev but the LD_PRELOAD variable is the key. If you install python 2 its named `/usr/lib/libpython2.7.so.1.0` instead.

Here is my working dockerfile: 

``` Dockerfile
FROM freeradius/freeradius-server:latest-alpine

# Using pip is probably ok it only adds about 15% to the image size
#RUN apk update && apk add curl python2-dev py-pip
#RUN pip install future

RUN apk update && apk add curl python2

# Set the install location for the agent
ARG MAGIC_LOC=/usr/app/agent
ENV MAGIC_LOC ${MAGIC_LOC}
WORKDIR ${MAGIC_LOC}

# Fixes ImportError (No module named builtins) for python 2
RUN curl https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz | tar -xz \
    && cd future-0.17.1 && python setup.py install \
    && cd .. && rm -r future-0.17.1

# Copy all the files we actually need to run the agents
COPY magic/radius magic/radius
COPY magic/utils/authobject.py magic/radius/authobject.py

# Move the resources into place
COPY magic/resources/inner-tunnel /etc/raddb/sites-enabled/inner-tunnel
COPY magic/resources/python-magic /etc/raddb/mods-enabled/python-magic
RUN sed -i "s@MAGIC_LOC@"${MAGIC_LOC}"@g" /etc/raddb/mods-enabled/python-magic
COPY magic/resources/eap /etc/raddb/mods-enabled/eap
COPY magic/resources/clients.conf /etc/raddb/clients.conf

# Install the certs
COPY ssl/* /etc/raddb/certs/

# Make sure the library is found
ENV LD_PRELOAD=/usr/lib/libpython2.7.so.1.0

CMD ["freeradius", "-X"] # Set default command
```

Thanks a bunch, if you want I can update the readme section and create a PR to include this tip for python devs :)

**Comment by mcnewton** [comment]
The whole point though is that setting `LD_PRELOAD` _shouldn't_ be required, hence it's a workaround. It pretty much means something isn't linking correctly at runtime. But glad it works though.

The correct PR would be to find and fix the underlying issue, or to document why it can't be solved and only then give the workaround :-)

**Comment by DomAmato** [comment]
Is it possible something doesn't translate over during the part where the slimmed down image gets created? 

Like this step onwards:

https://github.com/FreeRADIUS/freeradius-server/blob/119df87fafaa672966e7edc9dcfa855d1e944ed5/scripts/docker/alpine/Dockerfile#L53
