### ISSUE TITLE
Feature : xlat pairs as json string

### ISSUE THREAD

**Issue by maximumG** [FreeRADIUS/freeradius-server#2771]
# Issue type

- Feature request

# Feature description

I saw that it was possible to serialize attributes as comma-delimited string using the `%{pairs:...}`, which leads to the following format 

```
User-Name = 'Bob', User-Password = 'bar'
```

We have a use case where we want to serialize attributes of specific FreeRADIUS chains (request, response, control) as JSON compatible string with the following format.

```
"User-Name": "Bob", "User-Password": "bar"
```

Would you be interessted in such feature ? If yes I can propose to send a pull request with the following modification in rlm_rest.c file. Add a new XLAT named *pairs_json* which:

* Take the same parameters as the pais_xlat
* return a string which VP encoded as "V":"P",  "V":"P"

**Comment by alandekok** [comment]
The rlm_json module in "master" branch can do this.  You're welcome to back-port it to v3.
