### ISSUE TITLE
Can not start or restart freeradius-server

### ISSUE THREAD

**Issue by simonchahine** [FreeRADIUS/freeradius-server#2794]
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Job for freeradius.service failed because the control process exited with error code.
See "systemctl status freeradius.service" and "journalctl -xe" for details.
invoke-rc.d: initscript freeradius, action "start" failed.
● freeradius.service - FreeRADIUS multi-protocol policy server
   Loaded: loaded (/lib/systemd/system/freeradius.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-07-18 08:02:45 EEST; 16ms ago
     Docs: man:radiusd(8)
           man:radiusd.conf(5)
           http://wiki.freeradius.org/
           http://networkradius.com/doc/
  Process: 13420 ExecStartPre=/usr/sbin/freeradius $FREERADIUS_OPTIONS -Cxm -lstdout (code=exited, status=1/FAILURE)

radius@radius-HP-ProBook-6570b:~$ journalctl -xe
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: FreeRADIUS Version 3.0.16
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: Copyright (C) 1999-2017 The FreeRADIUS server project and contributors
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: PARTICULAR PURPOSE
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: You may redistribute copies of FreeRADIUS under the terms of the
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: GNU General Public License
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: For more information about these matters, see the file named COPYRIGHT
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: Starting - reading configuration files ...
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: /etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf[226]: Reference "${....
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: /etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf[230]: Reference "${..ac
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: /etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf[262]: Reference "${....
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: /etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf[273]: Reference "${....
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: /etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf[296]: Reference "${....
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: /etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf[327]: Reference "${....
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: /etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf[226]: Reference "${....
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: Errors reading or parsing /etc/freeradius/3.0/radiusd.conf
Jul 18 08:15:38 radius-HP-ProBook-6570b systemd[1]: freeradius.service: Control process exited, code=exited status=1
Jul 18 08:15:38 radius-HP-ProBook-6570b systemd[1]: freeradius.service: Failed with result 'exit-code'.
Jul 18 08:15:38 radius-HP-ProBook-6570b systemd[1]: Failed to start FreeRADIUS multi-protocol policy server.

**Comment by alandekok** [comment]
Read the messages you're posting.

```
Jul 18 08:15:38 radius-HP-ProBook-6570b freeradius[14522]: Errors reading or parsing /etc/freeradius/3.0/radiusd.conf
```

This isn't difficult.  You edited the configuration and broke it.

You also need to read the issue template.  It EXPLICITLY says that configuration questions should be posted to the mailing list, and not here.
