### ISSUE TITLE
rlm_rest does not support HTTP/2

### ISSUE THREAD

**Issue by alandekok** [FreeRADIUS/freeradius-server#2821]
# Issue type
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect
## How to reproduce the issue

Have a web server support HTTP/2 ,and use rlm_rest
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

```text
   (1) rest: Processing response header
   (1) rest: ERROR: Malformed HTTP header: Status line too short
   (1) rest: ERROR: Received 13 bytes of response data: HTTP/2 404  
   (1) rest: ERROR: Request failed: 23 - Failed writing received data
   to disk/application
   (1) rest: ERROR: Server returned no data
   rlm_rest (rest): Released connection (0)```
```

We can force libcurl to use a particular HTTP version:

https://curl.haxx.se/libcurl/c/CURLOPT_HTTP_VERSION.html

But we can't *disable* HTTP/2, and allow HTTP/1.1 and HTTP/1.0.

**Comment by theyough** [comment]
any update ?

**Comment by arr2036** [comment]
Yes, this was fixed by: https://github.com/FreeRADIUS/freeradius-server/commit/dc93062c72d8529702ab42383ec903f5827a8c9f#diff-0cca2197649953eab611e29cf27fdcc98624c3b46bed73725b4294674c3fcb44

**Comment by nemesisdesign** [comment]
Hi, is this released yet?

**Comment by jpereira** [comment]
@nemesisdesign yep, the latest version supports HTTP/2.0 as can be seen here https://github.com/FreeRADIUS/freeradius-server/commit/dc93062c72d8529702ab42383ec903f5827a8c9f#diff-d30bc9e01d78ffebbf9b5e080c3e97dc5177751e4e89b7b5427ebb5508136578 so, just use the latest 3.0.23
