### ISSUE TITLE
RADSEC Clients must validate Server Certificates

### ISSUE THREAD

**Issue by mark-grayson** [FreeRADIUS/freeradius-server#2839]
# Issue type
- Defect - Unexpected behaviour.

# Defect

In FreeRADIUS, version 3.0.18, when a RADSEC client initiates a TLS connection to a server listed in a server_pool, a trusted Server responds to the request, and TLS attributes are expanded from the Server certificate OIDs, no expansions occur.  RADSEC clients must be able to verify additional attributes and oids contained in the Server Certificate SAN in the same manner as client certificates do , e.g. 
listen:TLS-Server-Cert-Subject-Alt-Name-Dns .

## Background
This issue is being raised on behalf of Wireless Broadband Alliance.
WBA is currently evolving its WRIX RADIUS Roaming system to enable support of RADSEC.
RADSEC testing has been performed by multiple WBA members, including:
Accuris Networks, BSG Wireless, Cablelabs, Cisco and iPass/Pareteum

**Comment by alandekok** [comment]
I've pushed a fix which should help.  Please verify, and if this OK, close the issue.

The fix will be in 3.0.20 when it is released.

**Comment by alandekok** [comment]
commit dd438bfe948 has more code and documentation changes which should help.

But be aware that home server TLS parameters are available only *after* a connection has been opened to the home server.  And, there's no way to run a policy *during* the connection opening process.

If you could *clearly describe* the packet flow / policy requirements you have, that would help a lot.  Detailed requirements are much more productive than vague descriptions.
