### ISSUE TITLE
Freeradius not executing external shell script

### ISSUE THREAD

**Issue by aliserver** [FreeRADIUS/freeradius-server#2843]
I am using update control under authorize to get Auth Type 
I am running a script for user authorization it has

htpasswd -bv testpassfile $username $password

Through freeradius Script run successful with on option -b or -v but does not work with both option -bv

on shell command I test the script it run successfully with both -bv options

I will be grateful for help in this regard

**Comment by herwinw** [comment]
Questions like this belong on the mailing list: https://freeradius.org/support/
