### ISSUE TITLE
Freeradius is not executing external shell script 

### ISSUE THREAD

**Issue by aliserver** [FreeRADIUS/freeradius-server#2845]
I am using for  user authentication
Under Authorize I am using update control 
And running a shell script that have 
htpasswd -bv testpassfile $username $ password
And return Accept if ok
Script is running fine with one option -b or -v
But with both -bv  or -b -v  it is not running 
I will be grate full for the help.

**Comment by mcnewton** [comment]
You've already been told to ask questions on the freeradius-users mailing list. GitHub issues are for software bug reports as detailed in the issue template. http://wiki.freeradius.org/list-help
