### ISSUE TITLE
file change reload not working as expected

### ISSUE THREAD

**Issue by richardschuetz** [FreeRADIUS/freeradius-server#2846]
# Issue type
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect
If I edit the _users_ file and trigger multiple configuration reloads with SIGHUP afterwards, the _files_ module gets reloaded every time, although configuration has only been changed once.

Additionally changes in files included in _users_ with `$INCLUDE` are not detected at all.
## How to reproduce the issue

1. Edit _users_ file
2. Trigger configuration reload
3. Trigger another configuration reload

The _files_ module gets reloaded both times.

## Output of ``[radiusd|freeradius] -X`` showing issue occurring

```text
Ready to process requests
Received HUP signal
  # Trying to reload module "files"
  files {
        filename = "/etc/freeradius/3.0/mods-config/files/authorize"
        acctusersfile = "/etc/freeradius/3.0/mods-config/files/accounting"
        preproxy_usersfile = "/etc/freeradius/3.0/mods-config/files/pre-proxy"
  }
reading pairlist file /etc/freeradius/3.0/mods-config/files/authorize
reading pairlist file /etc/freeradius/3.0/mods-config/files/accounting
reading pairlist file /etc/freeradius/3.0/mods-config/files/pre-proxy
 Module: Reloaded module "files"
HUP - Files loaded by a module have changed.
Ready to process requests
Ready to process requests
Received HUP signal
  # Trying to reload module "files"
  files {
        filename = "/etc/freeradius/3.0/mods-config/files/authorize"
        acctusersfile = "/etc/freeradius/3.0/mods-config/files/accounting"
        preproxy_usersfile = "/etc/freeradius/3.0/mods-config/files/pre-proxy"
  }
reading pairlist file /etc/freeradius/3.0/mods-config/files/authorize
reading pairlist file /etc/freeradius/3.0/mods-config/files/accounting
reading pairlist file /etc/freeradius/3.0/mods-config/files/pre-proxy
 Module: Reloaded module "files"
HUP - Files loaded by a module have changed.
Ready to process requests
```

**Comment by alandekok** [comment]
Which version?  What OS?  When I try it here, it works for the "users" file.

It ignores files loaded via `$INCLUDE`.  That is unfortunately a limitation, and won't be fixed in the v3 release.  Doing so will require substantial changes, which are impossible at this time.

**Comment by richardschuetz** [comment]
> Which version? What OS? When I try it here, it works for the "users" file.

I am able to reproduce the behavior with both FreeRADIUS 3.0.16 on Ubuntu 18.04.2 LTS and FreeRADIUS 3.0.19 on Arch Linux.
