### ISSUE TITLE
Readme.md points to non existing file Install.md

### ISSUE THREAD

**Issue by Dragas** [FreeRADIUS/freeradius-server#2870]
Your recent change to convert all markdown files to adoc files broke the link to installation guide in project's main readme.md. 

The change itself seems to be unwarranted due to file structure still looking the same.  But that's just me.

**Comment by alandekok** [comment]
I've pushed a fix.  The "unwarranted" comment is inappropriate.

If you're looking at "master" often enough to notice the link broken, you should also have noticed that we're adding tons of documentation, and cleaning up the rest.  Using a *common* documentation format is part of that cleanup.
