### ISSUE TITLE
ASSERT FAILED src/lib/io/master.c[208]: a != NULL

### ISSUE THREAD

**Issue by fffmonkeyking** [FreeRADIUS/freeradius-server#2993]
radius client 127.0.0.1:
./radtest phf 123456 127.0.0.1:1812 0 testing123

radius client : 10.12.32.181:
./radtest phf 123456 10.12.32.147:1812 0 testing123

----> radius server crash:
proto_radius_udp - Received Access-Request ID 221 length 73 proto_radius_udp server * port 1812
-pending_client_cmp()-201: a=(nil), b=(nil), c1->src_ipaddr=[127.0.0.1]
-pending_client_cmp()-205: a=(nil), b=(nil), c2->src_ipaddr=[10.12.32.0]
ASSERT FAILED src/lib/io/master.c[208]: a != NULL
CAUGHT SIGNAL: Aborted
Backtrace of last 13 frames:
/usr/local/lib/libfreeradius-util.so(fr_fault+0x100)[0x7fdbe48755b3]
/usr/local/lib/libfreeradius-util.so(_fr_exit+0x0)[0x7fdbe487622e]
/usr/local/lib/libfreeradius-io.so(+0x133ba)[0x7fdbe4ad93ba]
/usr/local/lib/libfreeradius-util.so(+0x24706)[0x7fdbe4887706]
/usr/local/lib/libfreeradius-util.so(fr_heap_insert+0x12e)[0x7fdbe4887699]
/usr/local/lib/libfreeradius-io.so(+0x16cd1)[0x7fdbe4adccd1]
/usr/local/lib/libfreeradius-io.so(+0xfee1)[0x7fdbe4ad5ee1]
/usr/local/lib/libfreeradius-util.so(fr_event_service+0x464)[0x7fdbe488540b]
/usr/local/lib/libfreeradius-util.so(fr_event_loop+0x45)[0x7fdbe4885a11]
/usr/local/lib/libfreeradius-server.so(main_loop_start+0x2a)[0x7fdbe4f47473]
./radiusd(main+0x14ce)[0x40843f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fdbe3617830]
./radiusd(_start+0x29)[0x404609]
No panic action set
Aborted

///////////////
so:
if two different radius client(different ip) access to the radius server, the radius server crash.

**Comment by alandekok** [comment]
There is no such assert on line 208.

You are likely using an old version.  Upgrade to the latest version from git.

**Comment by fffmonkeyking** [comment]
I add some log print:

![image](https://user-images.githubusercontent.com/25978767/65003829-bfbaf580-d92c-11e9-9919-a8a9d13673d6.png)

**Comment by alandekok** [comment]
What have you changed from the default configuration?  

Can you get a back trace with *line numbers*?  That would help.

**Comment by fffmonkeyking** [comment]
![image](https://user-images.githubusercontent.com/25978767/65103116-cbc3b780-d9ff-11e9-9bc4-37ded822385f.png)

**Comment by fffmonkeyking** [comment]
i do not modify  the default configuration

**Comment by fffmonkeyking** [comment]
I am running a version three months ago, the following is the difference between the old version and the latest version:

maybe the latest version has solved the bug:

![image](https://user-images.githubusercontent.com/25978767/65120267-ee65c880-da1f-11e9-8929-0b43a2600460.png)

**Comment by alandekok** [comment]
When I said use the latest from git, I meant use the latest from git.
