### ISSUE TITLE
use from_unixtime() to become a datetime locally str to set datetime in mysql, so timezone problem happen

### ISSUE THREAD

**Issue by pythonwood** [FreeRADIUS/freeradius-server#3009]
env: ubuntu 18.04 + freeradius3.0.19 + mysql8  (  mytimezone:  +8:00 )

### debug message from `radiusd -X`  let me head into  `from_unixtime()`

[https://database.guide/from_unixtime-examples-mysql/](url)

> `(10) sql: EXPAND INSERT INTO radacct (acctsessionid,        acctuniqueid,       username, realm,            nasipaddress,       nasportid, nasporttype,     acctstarttime,      acctupdatetime, acctstoptime,       acctsessiontime,         acctauthentic, connectinfo_start,   connectinfo_stop,   acctinputoctets, acctoutputoctets,  calledstationid,    callingstationid, acctterminatecause,   servicetype,        framedprotocol, framedipaddress,    framedipv6address,  fram     edipv6prefix, framedinterfaceid,    delegatedipv6prefix) VALUES ('%{Acct-Session-Id}', '%{Acct-Unique-Session-Id}', '%{SQL-User-Name}', '%{Realm}', '%{NAS-IP-Address}', '%{%{NAS-Port-ID}:-%{NAS-Port}}', '%{NAS-Port-Type}', FROM_UNIX     TIME(%{integer:Event-Timestamp}), FROM_UNIXTIME(%{integer:Event-Timestamp}), NULL, '0', '%{Acct-Authentic}', '%{Connect-Info}', '', '0', '0', '%{Called-Station-Id}', '%{Calling-Station-Id}', '', '%{Service-Type}', '%{Framed-Protocol     }', '%{Framed-IP-Address}', '%{Framed-IPv6-Address}', '%{Framed-IPv6-Prefix}', '%{Framed-Interface-Id}', '%{Delegated-IPv6-Prefix}')
1985 (10) sql:    --> INSERT INTO radacct (acctsessionid,        acctuniqueid,       username, realm,            nasipaddress,       nasportid, nasporttype,     acctstarttime,      acctupdatetime, acctstoptime,       acctsessiontime,         acctauthentic, connectinfo_start,   connectinfo_stop,   acctinputoctets, acctoutputoctets,  calledstationid,    callingstationid, acctterminatecause,   servicetype,        framedprotocol, framedipaddress,    framedipv6address,  fram     edipv6prefix, framedinterfaceid,    delegatedipv6prefix) VALUES ('1569548082-12', '4fdcxxxxx6d4e464422ef247ac', '6C9EAxxx-4E17-877D-1F36F6F5FCB5', '', '1xx7.0.3', 'ios_xauth_psk', 'Virtual', FROM_UNIXTIME(1569549260), F     ROM_UNIXTIME(1569549260), NULL, '0', '', '', '', '0', '0', '172.xx5D', '192.x6x.18xx=5D', '', 'Framed-User', '', '1xx.1', '', '', '', '')
1986 (10) sql: Executing query: INSERT INTO radacct (acctsessionid,      acctuniqueid,       username, realm,            nasipaddress,       nasportid, nasporttype,     acctstarttime,      acctupdatetime, acctstoptime,       acctsessiont     ime,    acctauthentic, connectinfo_start,   connectinfo_stop,   acctinputoctets, acctoutputoctets,  calledstationid,    callingstationid, acctterminatecause,   servicetype,        framedprotocol, framedipaddress,    framedipv6addres     s,  framedipv6prefix, framedinterfaceid,    delegatedipv6prefix) VALUES ('15xxx082-12', '4fdc988387277xx64422ef247ac', '6C9EA1E7-xxxD-1F36F6F5FCB5', '', '172.17.0.3', 'ios_xauth_psk', 'Virtual', FROM_UNIXTIME(156954     9260), FROM_UNIXTIME(1569549260), NULL, '0', '', '', '', '0', '0', '172.1xx5D', '1xx.188=5B4500=5D', '', 'Framed-User', '', '10xx0.1', '', '', '', '')
`

**when I check in  radacct ,  acctstarttime is ahead 8 hours !**

`SELECT @@session.time_zone` => SYSTEM

then I add `default-time-zone       = '+0:00'`  in `[mysqld]`  , restart mysqld,  after  doing this, I get the right acctstartime now.

**Comment by arr2036** [comment]
FreeRADIUS isn't generating those timestamps, that'd be your NAS.  Fix the timezones on your NAS so that you get the correct time in the database.

**Comment by dbech** [comment]
I think there might be something to this query. I just upgraded from an older version of freeradius which didn't make use of FROM_UNIXTIME() and had no issue. Now that I've moved to freeradius3 all of my accounting data is 8 hours ahead however radpostauth (which doesn't make use of FROM_UNIXTIME()) is in the correct timezone.

Does anyone know if the code for FROM_UNIXTIME() available somewhere?
