### ISSUE TITLE
openssl-version match

### ISSUE THREAD

**Issue by NageshReddy-lab** [FreeRADIUS/freeradius-server#3014]
When am running "configure" command am facing the following error:

_checking OpenSSL library and header version consistency... no
configure: error: in `/opt/software/freeradius-server-3.0.17':
configure: error: OpenSSL library version does not match header version
See `config.log' for more details_

Already we have openssl 1.1 installed on my server. Also i have downloaded openssl 0.9.7 versiona and installed on server. Can some one please help me finding out the solution .

**Comment by jpereira** [comment]
That questions should be sent to freeradius- users@lists.freeradius.org, But try to use the latest code or the latest release 3.0.19.

**Comment by alandekok** [comment]
> Also i have downloaded openssl 0.9.7 version

That version is a decade of out of date.  There is absolutely no reason to be using it.
