### ISSUE TITLE
[rlm_sql] Check-Attributes from radgroupcheck takes  precedence over radcheck

### ISSUE THREAD

**Issue by Kroki0815** [FreeRADIUS/freeradius-server#3040]
- Defect - Unexpected behaviour.
- Feature request.

# Defect/Feature description
## How to reproduce issue
Place a Check-Attribute like Pool-Name or Simultaneous-Use, with different values and op :=,  in radcheck and radgroupcheck. As result always the check-attribute from radgroupcheck is taken.
That's expected like the docu. There is no possibility to take precedence to radcheck. The '=' operator ist not possible for check-items. With reply-items this work like expected.

So, is there a way to set check-items in radgroupcheck and overwrite it from radchek ?

**Comment by alandekok** [comment]
The documentation in https://wiki.freeradius.org/modules/Rlm_sql is very clear how the SQL module works.  radcheck is run BEFORE radgroupcheck, not after.

Questions about FreeRADIUS belong on the freeradius-users mailing list.
