### ISSUE TITLE
how can I change default accounting (radacct table) update time?

### ISSUE THREAD

**Issue by tuhinhossain** [FreeRADIUS/freeradius-server#3046]
I am using Simultaneous-Use := 1 . When I disconnect wifi or in a power loss, I am facing an issue that I can't connect to the server again. I saw that after 5/6 minutes later, I can connect again.
so I guess after 5/6 minutes later freeradius server check if the user is ideal then disconnect or send a account-stop request or fill "acctstoptime" field.

Now I want to change that 5/6 minutes to seconds or at least 1 minute. How can I archive that? I used Acct-Interim-Interval=5 and Idle-Timeout=20

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
