### ISSUE TITLE
use freeradius as radius translator

### ISSUE THREAD

**Issue by mihanservice** [FreeRADIUS/freeradius-server#3053]
hi
i have configured strongswan (ipsec) to send request to freeradius as eap-radius.
and i configured freeradius to send requests using proxy to another radius server. (IBSng).

but , ipsec sends as EAP and freeradius forwards the original request to ibsng. ibsng didn't understand EAP ! just need clear text password.

how can i translate EAP to clear-text password in proxy?

**Comment by mcnewton** [comment]
Questions belong on the freeradius-users list. This isn't a bug or other issue with FreeRADIUS.
