### ISSUE TITLE
LDAP-UserDN attribute name is not dynamically generated with instance name

### ISSUE THREAD

**Issue by albertuwin** [FreeRADIUS/freeradius-server#3066]
LDAP-Group attribute name is now dynamically created with the format
"%s-LDAP-Group", inst->name

But all ldap module instances use the same "LDAP-UserDN" attribute name to store user DN. If the same username exists in two different LDAP directories with two different DNs, "LDAP-UserDN" attribute will have two values. membership search on the second directory will fail because it searches by the the first directory's "LDAP-UserDN" value.

membership_filter = "(&(objectClass=GroupOfUniqueNames)(uniquemember=%{control:Ldap-UserDn}))"

**Comment by jpereira** [comment]
Which version are you running? As the Github issue template says https://github.com/FreeRADIUS/freeradius-server/blob/master/.github/ISSUE_TEMPLATE/bug_report.md please, share the debug output.

**Comment by albertuwin** [comment]
I found out the membership search problem with version 3.0.17 on CentOS 8. And then I read the main branch source code. I guess the behavior of the following code need to change to dynamically generate ("%s-LDAP-UserDN", inst->name) attribute name. This will be a breaking change because the attribute name is referenced in membership_filter of ldap instance configuration.

src/modules/rlm_ldap/user.c
line 42:
* Retrieves the DN of a user and adds it to the control list as LDAP-UserDN. Will also retrieve any
--
 * attributes passed and return the result in *result.

line 199:
	MEM(pair_update_control(&vp, attr_ldap_userdn) >= 0);
	fr_pair_value_strcpy(vp, dn);

**Comment by jpereira** [comment]
@albertuwin That snip of code is related to the v4.0.x (*master* branch) version that still on development. Therefore, you're looking at the wrong place. 

Have you tried to do your tests using the latest stable version 3.0.19 or using the latest v3.0.x code https://github.com/FreeRADIUS/freeradius-server/commits/v3.0.x, if not. please, try it.

Again, probably it will be impossible to help you without the debug output.

**Comment by arr2036** [comment]
@jpereira if it's not fixed in master, it's extremely unlikely to work in v3.0.x

**Comment by albertuwin** [comment]
The source codes/behaviors are the same for v3.0.x and v4.0.x. 

The change I am suggesting is to add user DN to the control list as "instancename-LDAP-UserDN", instead of LDAP-UserDN. So that different user DNs of the same user from different LDAP instances are store in separate attributes  in the control list. 

And membership search will work in this multiple ldap instances config.
membership_filter = "(&(objectClass=GroupOfUniqueNames)(uniquemember=%{control:instancename-Ldap-UserDn}))"

Thank you very much for looking at this issue.

**Comment by alandekok** [comment]
> The change I am suggesting is to add user DN to the control list as "instancename-LDAP-UserDN

v3 does that already.  The default configuration in git v3.0.x branch has:

```
	#	${.:instance}-LDAP-UserDn
	#
	#  That change allows the modules to set their own
	#  User DN, and to not conflict with each other.
	#
	user_dn = "LDAP-UserDn"
```

so everything you want is there.  You're just using an old version, with an old configuration.
