### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [FreeRADIUS/freeradius-server#3076]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/FreeRADIUS/freeradius-server/blob/57239961ebf2bc7b66695593cc4c962b9796ef7b/configure.ac#L706 "Update candidate")?

**Comment by alandekok** [comment]
Our pthread checks work across multiple systems.  It's not clear what's to be gained (if anything) by switching out the autoconf macros.

If there are actual issues, please articulate them here.  Otherwise I think that the code is fine.

**Comment by elfring** [comment]
Do you care for safer build checks because of any more variations for this software library?

**Comment by alandekok** [comment]
I care to do things which are important to the project.  You should *not* try to lord it over other people. 

Your comments show an inability to communicate meaningfully in a professional environment.
