### ISSUE TITLE
v3.0.x HEAD cannot send packets when run under systemd

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#3081]
# Issue type

- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect
## How to reproduce the issue

Start FreeRADIUS under systemd on Centos 7.  Send test packet.  Observe that debug output is produced, but no response is received by the test utility.

**Comment by arr2036** [comment]
If this is an selinux issue then we need to fix the packages to add the appropriate rules, because as it is v3.0.x is unusable when started as a service.

**Comment by arr2036** [comment]
As a bonus issue, request logging as enabled from radmin is also completely non-functional in this configuration.  You enable output to a file, and set a debug level and no detailed request debug output is written to the file.  

Additionally, when you specify the debug file and debug level again, the radiusd process will crash...

**Comment by arr2036** [comment]
Adding as a comment here because I don't know if this is actually a seprate issue, or related to some permissions thing in systemd.

**Comment by mcnewton** [comment]
Sure, I'll take a look.

**Comment by alandekok** [comment]
I think this is the only gating issue for 3.0.20 at this time.

**Comment by mcnewton** [comment]
Tested a couple of systems including a full install from CentOS7 ISO, everything is working as expected and I don't see any of the problems. I can't see that we can do anything apart from leave this until it's reported again and is reproducible, or put it down to a problem on the system itself.
