### ISSUE TITLE
Radacct mysql table: modify value length of columns nasportid and callingstationid

### ISSUE THREAD

**Issue by rusgiu** [FreeRADIUS/freeradius-server#3101]
# Issue type
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect/Feature description
In the mysql redacct table the default length of the varchar value for the columns NASPORTID and CALLINGSTATIONID it's not compatible with the values sent by the NAS of the operator Telecom Italia.
The default nasportid length is 15 but Telecom Italia send a larger value (atm 8/3.10114:1.114). The same for callingstationid: default length 50. Value from Telecom Italia NAS (=23r-ct062=23PORTA X MultiServizio Wholesale=231=23114)

Sun Nov  3 21:31:11 2019 : ERROR: (11) sql: ERROR: rlm_sql_mysql: 1406: Data too long for column 'nasportid' at row 1
Sun Nov  3 21:31:11 2019 : ERROR: (11) sql: ERROR: rlm_sql_mysql: ERROR 1406 (Data too long for column 'nasportid' at row 1): 22001

**Comment by alandekok** [comment]
The short answer is to update the table to allow for more data in those columns.  This is why the defaults are editable.

I don't see much value in changing the defaults in the server.  They work well enough for most people, and increasing the defaults can negatively impact others.
