### ISSUE TITLE
rlm_sql_mysql: ERROR 1406 (Data too long for column 'nasportid' at row 1): 

### ISSUE THREAD

**Issue by Hadronx** [FreeRADIUS/freeradius-server#3141]
# Issue type

- Defect - Unexpected behaviour 

# Defect description
## How to reproduce issue
Use a switch Cisco 2960-x as autenticator 
 
## Output of ``[freeradius] -X`` showing issue occurring
[...]
(27) sql: SQL-User-Name set to 'host/user1'

(27) sql: EXPAND INSERT INTO radacct (acctsessionid,		acctuniqueid,		username, realm,			nasipaddress,		nasportid, nasporttype,		acctstarttime,		acctupdatetime, acctstoptime,		acctsessiontime, 	acctauthentic, connectinfo_start,	connectinfo_stop, 	acctinputoctets, acctoutputoctets,	calledstationid, 	callingstationid, acctterminatecause,	servicetype,		framedprotocol, framedipaddress,	framedipv6address,	framedipv6prefix, framedinterfaceid,	delegatedipv6prefix) VALUES ('%{Acct-Session-Id}', '%{Acct-Unique-Session-Id}', '%{SQL-User-Name}', '%{Realm}', '%{NAS-IP-Address}', '%{%{NAS-Port-ID}:-%{NAS-Port}}', '%{NAS-Port-Type}', FROM_UNIXTIME(%{integer:Event-Timestamp}), FROM_UNIXTIME(%{integer:Event-Timestamp}), NULL, '0', '%{Acct-Authentic}', '%{Connect-Info}', '', '0', '0', '%{Called-Station-Id}', '%{Calling-Station-Id}', '', '%{Service-Type}', '%{Framed-Protocol}', '%{Framed-IP-Address}', '%{Framed-IPv6-Address}', '%{Framed-IPv6-Prefix}', '%{Framed-Interface-Id}', '%{Delegated-IPv6-Prefix}')
(27) sql:    --> INSERT INTO radacct (acctsessionid,		acctuniqueid,		username, realm,			nasipaddress,		nasportid, nasporttype,		acctstarttime,		acctupdatetime, acctstoptime,		acctsessiontime, 	acctauthentic, connectinfo_start,	connectinfo_stop, 	acctinputoctets, acctoutputoctets,	calledstationid, 	callingstationid, acctterminatecause,	servicetype,		framedprotocol, framedipaddress,	framedipv6address,	framedipv6prefix, framedinterfaceid,	delegatedipv6prefix) VALUES ('00000018', 'f0bbd8901ee22142062d3a1c0e600989', 'host/user1', '', '10.20.0.10', 'GigabitEthernet1/0/13', 'Ethernet', FROM_UNIXTIME(1574173010), FROM_UNIXTIME(1574173010), NULL, '0', '', '', '', '0', '0', '00-62-5A-63-60-0D', 'C4-65-16-B9-86-E2', '', '', '', '', '', '', '', '')

(27) sql: Executing query: INSERT INTO radacct (acctsessionid,		acctuniqueid,		username, realm,			nasipaddress,		nasportid, nasporttype,		acctstarttime,	acctupdatetime, acctstoptime,		acctsessiontime, 	acctauthentic, connectinfo_start,	connectinfo_stop, 	acctinputoctets, acctoutputoctets,	calledstationid, 	callingstationid, acctterminatecause,	servicetype,		framedprotocol, framedipaddress,	framedipv6address,	framedipv6prefix, framedinterfaceid,	delegatedipv6prefix) VALUES ('00000018', 'f0bbd8901ee22142062d3a1c0e600989', 'host/user1', '', '10.20.0.10', 'GigabitEthernet1/0/13', 'Ethernet', FROM_UNIXTIME(1574173010), FROM_UNIXTIME(1574173010), NULL, '0', '', '', '', '0', '0', '00-62-5A-63-60-0D', 'C4-65-16-B9-86-E2', '', '', '', '', '', '', '', '')
(27) sql: ERROR: rlm_sql_mysql: ERROR 1406 (Data too long for column 'nasportid' at row 1): 22001
(27) sql: SQL query returned: server error

[...]

It is necessary to modify the nasportid field in varchar (30).

**Comment by jpereira** [comment]
Which version are you running?

**Comment by mcnewton** [comment]
Updated by @jpereira in #3143.
