### ISSUE TITLE
[rlm_python] can't access openssl

### ISSUE THREAD

**Issue by shibumi** [FreeRADIUS/freeradius-server#3180]
# Issue type

- Defect - Unexpected behaviour (obvious or verified by project member).

Distribution: Ubuntu 18.04
Radius Version: 3.0.20

# Defect
## How to reproduce the issue
* install python2.7 + python-requests
* enable python module (python 2.7)
* activate `python` module in `sites-enabled/defaults` in the `accounting` section
* use the following `mods-enabled/python` file:
```
python {
        python_path = ${modconfdir}/${.:name}:/usr/lib/python2.7/:/usr/lib/python2.7/dist-packages

	module = example
	mod_accounting = ${.module}
	func_accounting = accounting
}
```

Use this file in `/mods-config/python/example.py` for testing:
```
#!/usr/bin/env python2
#-*- encoding; utf8 -*-

import radiusd
import requests

def accounting(p):
    # dummy payload for test purpose
    payload = {}
    try:
        req = requests.put("https://XXXX.de:8443/api/v1.0/user/XXX, verify=True, json=payload)
    except Exception, err:
        print(Exception, err)
    return radiusd.RLM_MODULE_OK
```

When I start a modified version of the script on the server locally, it works fine.
When I start it with freeradius, it seems it is not able to access the openssl library.

My first thought has been the systemd service file (many hardening is happening there), but even with no hardening it doesn't work. Maybe it's an issue with the python_path?
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring
```
(<type 'exceptions.Exception'>, SSLError(MaxRetryError('HTTPSConnectionPool(host=\'XXX\', port=8443): Max retries exceeded with url: /api/v1.0/user/XXX (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",))',),))
```

**Comment by jpereira** [comment]
Have you tried to test separated?

e.g:

```
[jpereira@sugarloaf freeradius-server.git]$ pip install requests
[jpereira@sugarloaf freeradius-server.git]$ cat r.py
#!/usr/bin/env python2
import requests

url = "https://ifconfig.co/ip"
req = requests.get(url, verify=True)

print(req.text)
[jpereira@sugarloaf freeradius-server.git]$
[jpereira@sugarloaf freeradius-server.git]$ ./r.py
186.213.16.211
[jpereira@sugarloaf freeradius-server.git]$
```

**Comment by shibumi** [comment]
@jpereira yes, separately it works, but as I said. If you try to invoke this via freeradius, for example in /sites-enabled/default, it doesn't.

**Comment by jpereira** [comment]
@shibumi please, append into `python_path` the output of: `python2 -c "import sys; print(':'.join(sys.path))"` and check if still failing.

e.g:

```
[root@devbox /]# python2 -c "import sys; print(':'.join(sys.path))"
:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/gtk-2.0
[root@devbox /]#
```

Pay attention to the `:` in the beginning.

**Comment by shibumi** [comment]
@jpereira Thanks, I am going to test this today and will notify you if this helps.

**Comment by shibumi** [comment]
@jpereira This has fixed the issue for me. Thank you so much for your help :)

**Comment by jpereira** [comment]
We appreciate your help @shibumi !
