### ISSUE TITLE
Docker - command from docker hub examples

### ISSUE THREAD

**Issue by RubyHuntsman** [FreeRADIUS/freeradius-server#3203]
# Issue type
- Defect - Crash or memory corruption.

# Defect
It's not posible to run container by folowing docker run command with port forward

```text
docker run --name my-radius -p 1812-1813:1812-1813/udp freeradius/freeradius-server
```
## The same docker run command with -X param (last lines of output)

```text
Listening on auth address * port 1812 bound to server default
Listening on acct address * port 1813 bound to server default
Listening on auth address :: port 1812 bound to server default
Listening on acct address :: port 1813 bound to server default
Listening on auth address 127.0.0.1 port 18120 bound to server inner-tunnel
Listening on proxy address * port 48381
Listening on proxy address :: port 51642
Ready to process requests
```

**Comment by jpereira** [comment]
@RubyHuntsman first of all, you could get more information about the first steps to use the container in https://github.com/FreeRADIUS/freeradius-server/tree/v3.0.x/scripts/docker

therefore, _maybe_ that extra parameters requested in https://github.com/FreeRADIUS/freeradius-server/pull/3206 could simplify the first contact.

**Comment by mcnewton** [comment]
Checked this and it all works as expected. I've updated the README to make it clearer that the default image is useless without supplying a local config.
