### ISSUE TITLE
failed to add attribute on freeradius to authenticate devices from LDAP database 

### ISSUE THREAD

**Issue by shyam303** [FreeRADIUS/freeradius-server#3228]
HI Team,
we are using freeradius to authentication for all device i.e- Router,Switch,checkpoint firewall,A10, IDPS
and saving the all database i.e username&password on LDAP , and freeradius connected with LDAP ,
so problem is this every device has own attributes to authenticate and take a privilege(L1,L2,L3) from LDAP so for Router&Switch&Checkpoint freeradius is working fine we are able to add attribute from this location (vi /etc/freeradius/3.0/mods-enabled/ldap) but for IDPS& A10 we are getting some error log, when we are adding attribute on freeradius server it is not accepting the attribute and not able to restart freeradius service ,we have added attribute i.e
                control:                        += 'radiusControlAttribute'
                request:                        += 'radiusRequestAttribute'
                 reply:CP-Gaia-SuperUser-Access  += 'radiusLoginLATGroup'
                reply:Fortinet-Access-Profile   += 'radiusUserCategory'
                reply:GUI-Role               += 'radiusFilter'
                reply:CP-Gaia-User-Role         += 'radiusLoginService'
                reply:User-Access-Level         += 'radiusAuthType'

so GUI Role& User Access Role is A10&IDPS for both we are facing issue ,
#freeradius -X is showing >>>>>
/etc/freeradius/3.0/mods-enabled/ldap[125]: Unknown attribute User-Access-Level
/etc/freeradius/3.0/mods-enabled/ldap[8]: Instantiation failed for module "ldap"

so please look in to this and reply.

**Comment by alandekok** [comment]
Reading the documentation is useful.  It's also rude to spam the repo with the same issue.

```
Questions about the server or its usage MUST be posted to the users mailing list. If you post those issues here, they will be closed and locked.
```
