### ISSUE TITLE
Invalid work of module 'files' parser with Framed-IP-Address with plus sign

### ISSUE THREAD

**Issue by Ghost99** [FreeRADIUS/freeradius-server#3243]
# Issue type
- Invalid work of config parser for ``/etc/raddb/mods-config/files/authorize``
- Probably ancient regression from 2.2.* to 3.0.*
- Defect - Unexpected behaviour.

***

# Defect description
## How to reproduce issue
On a plain installation edit ``/etc/raddb/mods-config/files/authorize`` and uncomment any of examples with ``Framed-IP-Address`` with address pool with plus sign. For example
```text
DEFAULT Service-Type == Framed-User, Huntgroup-Name == "alphen"
                Framed-IP-Address = 192.0.2.32+,
                Fall-Through = Yes
```
When you'll try to run ``radiusd -C``, you will get an error 
```text
Error: /etc/raddb/mods-config/files/authorize[159]: Parse error (reply) for entry DEFAULT: Failed resolving "192.0.2.32+" to IPv4 address: Name or service not known
Error: Failed reading /etc/raddb/mods-config/files/authorize
Error: /etc/raddb/mods-enabled/files[9]: Instantiation failed for module "files"
```
Tested on freeradius-3.0.17 on Gentoo. Last time it worked correctly on 2.2.9 and probably on other 2.2.*
Either documentation is outdated or parser working incorrectly.

## Output of ``radiusd -X -C`` showing issue occurring
```text
FreeRADIUS Version 3.0.17

--- skipped ok part ---

  # Instantiating module "reply_log" from file /etc/raddb/mods-enabled/detail.log
  # Instantiating module "pre_proxy_log" from file /etc/raddb/mods-enabled/detail.log
  # Instantiating module "post_proxy_log" from file /etc/raddb/mods-enabled/detail.log
  # Instantiating module "files" from file /etc/raddb/mods-enabled/files
reading pairlist file /etc/raddb/mods-config/files/authorize
/etc/raddb/mods-config/files/authorize[159]: Parse error (reply) for entry DEFAULT: Failed resolving "192.0.2.32+" to IPv4 address: Name or service not known
Failed reading /etc/raddb/mods-config/files/authorize
/etc/raddb/mods-enabled/files[9]: Instantiation failed for module "files"
```

**Comment by alandekok** [comment]
`Probably ancient regression from 2.2.* to 3.0.*`

The server is allowed to change behavior across major versions.  This functionality is no longer supported.  We will remove these examples from the default configuration.
