### ISSUE TITLE
Does the license of src/lib/util/rbtree.c be GPL-2.0+?

### ISSUE THREAD

**Issue by roycyt** [FreeRADIUS/freeradius-server#3249]
The license notice in the file says it is licensed under GPL-2.1+.
But there is no such GPL-2.1+.
https://github.com/FreeRADIUS/freeradius-server/blob/master/src/lib/util/rbtree.c
```
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or
 *   (at your option) any later version.
 ```

**Comment by alandekok** [comment]
That's left over text from when `src/lib` was under the LGPL 2.1.  We'll push a fix.
