### ISSUE TITLE
module sqlippool error

### ISSUE THREAD

**Issue by SeeVPN** [FreeRADIUS/freeradius-server#3268]
I followed the documentation https://wiki.freeradius.org/modules/Rlm_sqlippool

And configured sites-enable
 accounting {
        sqlippool
 }
 post-auth {
        sqlippool
 }

Run freeradius -X
FreeRADIUS Version 3.0.20
Copyright (C) 1999-2019 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
Starting - reading configuration files ...
including dictionary file /usr/share/freeradius/dictionary
including dictionary file /usr/share/freeradius/dictionary.dhcp
including dictionary file /usr/share/freeradius/dictionary.vqp
including dictionary file /etc/freeradius/dictionary
including configuration file /etc/freeradius/radiusd.conf
including configuration file /etc/freeradius/proxy.conf
including configuration file /etc/freeradius/clients.conf
including configuration file /etc/freeradius/mods-enabled/sql
including configuration file /etc/freeradius/mods-config/sql/main/mysql/queries.conf
including files in directory /etc/freeradius/mods-enabled/
including configuration file /etc/freeradius/mods-enabled/cache_eap
including configuration file /etc/freeradius/mods-enabled/sqlippool
including configuration file /etc/freeradius/mods-config/sql/ippool/mysql/queries.conf
/etc/freeradius/mods-config/sql/ippool/mysql/queries.conf[117]: Parse error: Unterminated string
Errors reading or parsing /etc/freeradius/radiusd.conf

/etc/freeradius/mods-config/sql/ippool/mysql/queries.conf: 112-118
{
allocate_update = "\
        UWHERE framedipaddress = '%I'
PDATE ${ippool_table} \
        SET \
                nasipaddress = '%{NAS-IP-Address}', pool_key = '${pool_key}', \
                callingstationid = '%{Calling-Station-Id}', \
                username = '%{User-Name}', expiry_time = NOW() + INTERVAL ${lease_duration} SECOND \
        WHERE framedipaddress = '%I'
}

**Comment by SeeVPN** [comment]
By the way, how should the mysql data of sqlippool be filled, and finding documents is extremely difficult! If you can, please recommend several places to learn freeradius

**Comment by alandekok** [comment]
I've pushed a fix.

The documentation should be easy to find.  Go to the wiki, and search for sqlippool:

https://wiki.freeradius.org/modules/Rlm_sqlippool

**Comment by SeeVPN** [comment]
@alandekok 
Sorry to bother you, the structure of radippool under 3.x 
/etc/freeradius/mods-config/sql/ippool/mysql/schema.sql
CREATE TABLE radippool (
  id                    int(11) unsigned NOT NULL auto_increment,
  pool_name             varchar(30) NOT NULL,
  framedipaddress       varchar(15) NOT NULL default '',
  nasipaddress          varchar(15) NOT NULL default '',
  calledstationid       VARCHAR(30) NOT NULL,
  callingstationid      VARCHAR(30) NOT NULL,
  expiry_time           DATETIME NULL default NULL,
  username              varchar(64) NOT NULL default '',
  pool_key              varchar(30) NOT NULL default '',
  PRIMARY KEY (id),
  KEY radippool_poolname_expire (pool_name, expiry_time),
  KEY framedipaddress (framedipaddress),
  KEY radippool_nasip_poolkey_ipaddress (nasipaddress, pool_key, framedipaddress)
) ENGINE=InnoDB;

But Wiki Examples ??
INSERT INTO radippool (pool_name, framedipaddress) VALUES ('main_pool', '192.168.0.1');
 INSERT INTO radippool (pool_name, framedipaddress) VALUES ('main_pool', '192.168.0.2');
 INSERT INTO radippool (pool_name, framedipaddress) VALUES ('main_pool', '192.168.0.3');
 INSERT INTO radippool (pool_name, framedipaddress) VALUES ('main_pool', '192.168.0.4');

**Comment by SeeVPN** [comment]
I am completely unable to configure and run correctly as documented ... I have been tossing about this for 1 day

**Comment by SeeVPN** [comment]
My current project requirement is to allow expired users to be assigned to the specified IP pool for DNS hijacking to recharge pages, so according to my ideas, I have to be able to assign IP to users through RADIUS.
