### ISSUE TITLE
Second sqlippool(sqlippool2) No Pool-Name defined

### ISSUE THREAD

**Issue by tcruzf** [FreeRADIUS/freeradius-server#3289]
I have two sql, two virtual servers.
I use two sqlippool, linked to :
sqlippol (enabled in mods-enable --> mods-available) sqlippol
sqlippol2(mods-enable) --> sqlipool2(mods-available)
For example, my config for first virtual server post-auth{ sql sqlippool ...} Ok, its work
For example, my second config, derived of first, post-auth{sql2 sqlippool2...} Its work using Framed-ip-Address in database.
For example, i use the same database in servers. Yes, Server "First" have ip 10.x.x.2 and server Second i set ip 10.x.x.3, change ports, change others params...
My first server using  database "xxx" send pool ip address for user after  after auth. Its work fine!
For testes, i export the database of first server and import in second server database.
In server First send pool addres and all ok.
In server Second not send Pool address.

```text
(0)   post-auth {
(0)     update {
(0)       No attributes updated
(0)     } # update = noop
(0) sqlippool2: No Pool-Name defined
(0) sqlippool2: EXPAND No Pool-Name defined (did %{Called-Station-Id} cli %{Calling-Station-Id} port %{NAS-Port} user %{User-Name})
(0) sqlippool2:    --> No Pool-Name defined (did SERVIDORQUEST cli xx:E0:xx:CA:0B:07 port 2159017987 user 20)
(0)     [sqlippool2] = noop
```
I have pool name defined, i have all config ok. And if i export this database for example and import in the first, its work fine.
Its is a Issue? Or config?
Sorry for my english, dont use translate.

**Comment by jpereira** [comment]
Please, https://wiki.freeradius.org/guide/Users-Mailing-List

**Comment by jpereira** [comment]
Please, https://wiki.freeradius.org/guide/Users-Mailing-List

**Comment by tcruzf** [comment]
Im write new code and solved the problem.
Use this for ref-> https://github.com/FreeRADIUS/freeradius-server/issues/2282
