### ISSUE TITLE
freeradius centos 7 + mikotik don´t connect

### ISSUE THREAD

**Issue by Jullito25** [FreeRADIUS/freeradius-server#3294]
I am trying to connect my freeradius server mounted in centos 7 with Mikrotik router os v6.40.4, I already added the client to the clients.conf file, I also added a user with a password to the users, on the router I added the freeradius ip by pinging between The server's ip and router respond correctly, but when connecting my cell phone to the mikrotik's network it doesn't connect.

**Comment by jpereira** [comment]
@Jullito25 you're on the wrong way. your question should go to mailing list. https://wiki.freeradius.org/guide/Users-Mailing-List

**Comment by alandekok** [comment]
questions belong on the freeradius-users mailing list.
