### ISSUE TITLE
CoA/DM over RADSEC - FreeRadius server ignores the CoA/DM request as Invalid when receives over TLS

### ISSUE THREAD

**Issue by SaurabhBadhai** [FreeRADIUS/freeradius-server#3356]
# Issue type
Ehhancement:

- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect
## How to reproduce the issue
Initiate CoA/DM request to freeradius server which is listening on port 3799, on receiving the request, server will proxy the request to another server over TLS, so here need to change the proxy.conf file home_server configuration, so that it can initiate TLS handshake towards second server.
Once TLS handshake is done, second server will get the CoA/DM message over TLS and ignored it.
 

A clear and concise list of steps describing how to describe the issue.
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring
radiusd -fxxx -l stdout

Error logs as below:
Error: Invalid packet code 45 sent to a proxy port from home server 10.174.75.66 port 2084 - ID 154 : IGNORED
## Full backtrace from LLDB or GDB

```text
NA
```
Observation/Workaround:

When I see the code where the error happens, I found like in /src/main/tls_listen.c under function dual_tls_recv we may required to include below two cases to solve this.

  case PW_CODE_COA_REQUEST:
                FR_STATS_INC(coa, total_requests);
                fun = rad_coa_recv;
                break;

  case PW_CODE_DISCONNECT_REQUEST:
                FR_STATS_INC(dsc, total_requests);
                fun = rad_coa_recv;
                break;

After I added this above lines in the same place, CoA/DM works fine.
My asking is to help to review this changes and check if we can we include this changes in newer release.

**Comment by alandekok** [comment]
This should work now.  if it's fine, please comment and close this issue.

**Comment by SaurabhBadhai** [comment]
Thanks for the response, can you help to commit this changes to github so that in future release will have this changes included.

**Comment by alandekok** [comment]
Please see the links above.  The changes have already been committed to github.

**Comment by SaurabhBadhai** [comment]
Closing this as its fixed.
