### ISSUE TITLE
rlm_sql_oracle

### ISSUE THREAD

**Issue by andreymarkin80** [FreeRADIUS/freeradius-server#3361]
1) server not start if use redundant and first use rlm_sql_oracle (if connection to db is can't be established)
2) server stop recive and answer to clients in same cause writed upper, but if connection is restore server continue to work.

freeradius 3.0.21

**Comment by jpereira** [comment]
@andreymarkin80 please provide the `radiusd -XXxx` output.

**Comment by alandekok** [comment]
Please read the documentation for the `sql` module.  You can edit the `pool` section, and set `start=0`.  This is documented.
