### ISSUE TITLE
wrong username simultaneous-use not working

### ISSUE THREAD

**Issue by ddxs** [FreeRADIUS/freeradius-server#3436]
# BUG

BUG look at the **BLACK**

9) sql: EXPAND SELECT groupname FROM radusergroup WHERE username = '%{SQL-User-Name}' ORDER BY priority
(9) sql:    --> SELECT groupname FROM radusergroup WHERE username = 'ddxs' ORDER BY priority
(9) sql: Executing select query: SELECT groupname FROM radusergroup WHERE username = 'ddxs' ORDER BY priority
(9) sql: User found in the group table
(9) sql: EXPAND SELECT id, groupname, attribute, Value, op FROM radgroupcheck WHERE groupname = '%{SQL-Group}' ORDER BY id
(9) sql:    --> SELECT id, groupname, attribute, Value, op FROM radgroupcheck WHERE groupname = 'VPN' ORDER BY id
(9) sql: Executing select query: SELECT id, groupname, attribute, Value, op FROM radgroupcheck WHERE groupname = 'VPN' ORDER BY id
(9) sql: Group "VPN": Conditional check items matched
(9) sql: Group "VPN": Merging assignment check items
(9) sql:   Simultaneous-Use := 1
(9) sql: EXPAND SELECT id, groupname, attribute, value, op FROM radgroupreply WHERE groupname = '%{SQL-Group}' ORDER BY id
(9) sql:    --> SELECT id, groupname, attribute, value, op FROM radgroupreply WHERE groupname = 'VPN' ORDER BY id
(9) sql: Executing select query: SELECT id, groupname, attribute, value, op FROM radgroupreply WHERE groupname = 'VPN' ORDER BY id
(9) sql: Group "VPN": Merging reply items
rlm_sql (sql): Released connection (8)
(9)     [sql] = ok
(9) expiration: Account will expire at 'Feb 21 2021 15:46:09 CST'
(9)     [expiration] = ok
(9)     [logintime] = noop
(9)     [pap] = updated
(9)   } # authorize = updated
(9) Found Auth-Type = PAP
(9) # Executing group from file /etc/freeradius/3.0/sites-enabled/default
(9)   Auth-Type PAP {
(9) pap: Login attempt with password
(9) pap: Comparing with "known good" Cleartext-Password
(9) pap: User authenticated successfully
(9)     [pap] = ok
(9)   } # Auth-Type PAP = ok
(9) # Executing section session from file /etc/freeradius/3.0/sites-enabled/default
(9)   session {
(9) sql: EXPAND %{User-Name}
(9) sql:    --> ddxs
(9) sql: SQL-User-Name set to 'ddxs'
rlm_sql (sql): Reserved connection (6)
(9) sql: EXPAND SELECT COUNT(*) FROM radacct WHERE username = '%{SQL-User-Name}' AND acctstoptime IS NULL
(9) sql:    --> SELECT COUNT(*) FROM radacct WHERE username = 'ddxs' AND acctstoptime IS NULL
(9) sql: Executing select query: SELECT COUNT(*) FROM radacct WHERE username = 'ddxs' AND acctstoptime IS NULL
(9) sql: EXPAND SELECT radacctid, acctsessionid, username, nasipaddress, nasportid, framedipaddress, callingstationid, framedprotocol FROM radacct WHERE **# username = '%{SQL-Group}'** AND acctstoptime IS NULL
(9) sql:    --> SELECT radacctid, acctsessionid, username, nasipaddress, nasportid, framedipaddress, callingstationid, framedprotocol FROM radacct WHERE **# username = ''** AND acctstoptime IS NULL
(9) sql: Executing select query: SELECT radacctid, acctsessionid, username, nasipaddress, nasportid, framedipaddress, callingstationid, framedprotocol FROM radacct WHERE username = '' AND acctstoptime IS NULL
rlm_sql (sql): Released connection (6)
(9)     [sql] = ok
(9)   } # session = ok
(9) # Executing section post-auth from file /etc/freeradius/3.0/sites-enabled/default
(9)   post-auth {
(9)     update {
(9)       No attributes updated for RHS &session-state:
(9)     } # update = noop
(9) sql: EXPAND .query
(9) sql:    --> .query
(9) sql: Using query template 'query'
rlm_sql (sql): Reserved connection (9)
(9) sql: EXPAND %{User-Name}
(9) sql:    --> ddxs
(9) sql: SQL-User-Name set to 'ddxs'
(9) sql: EXPAND INSERT INTO radpostauth (username, pass, reply, authdate) VALUES ( '%{SQL-User-Name}', '%{%{User-Password}:-%{Chap-Password}}', '%{reply:Packet-Type}', '%S')
(9) sql:    --> INSERT INTO radpostauth (username, pass, reply, authdate) VALUES ( 'ddxs', '12345678', 'Access-Accept', '2020-05-07 13:38:54')
(9) sql: Executing query: INSERT INTO radpostauth (username, pass, reply, authdate) VALUES ( 'ddxs', '12345678', 'Access-Accept', '2020-05-07 13:38:54')
(9) sql: SQL query returned: success
(9) sql: 1 record(s) updated
rlm_sql (sql): Released connection (9)
(9)     [sql] = ok
(9)     [exec] = noop
(9)     policy remove_reply_message_if_eap {
(9)       if (&reply:EAP-Message && &reply:Reply-Message) {
(9)       if (&reply:EAP-Message && &reply:Reply-Message)  -> FALSE
(9)       else {
(9)         [noop] = noop
(9)       } # else = noop
(9)     } # policy remove_reply_message_if_eap = noop
(9)   } # post-auth = ok
(9) Sent Access-Accept Id 115 from 127.0.0.1:1812 to 127.0.0.1:49421 length 0

**Comment by ddxs** [comment]
FreeRadius 3.0.x MySQL

**Comment by alandekok** [comment]
> 9) sql: EXPAND SELECT radacctid, acctsessionid, username, nasipaddress, nasportid, framedipaddress, callingstationid, framedprotocol FROM radacct WHERE # username = '%{SQL-Group}' AND acctstoptime IS NULL

You edited the configuration and broke it.  Don't do that.

You can't do that.  SQL-Group is a virtual attribute, like LDAP-Group.  You can use it for comparisons only.  It doesn't have a static value you can check.

**Comment by ddxs** [comment]
I did not edit the config file, so I report you the bug, please seriously, I am not a noob.

**Comment by alandekok** [comment]
The default configurations do not have:

`WHERE # username = '%{SQL-Group}'`

a) you edited the configuration and broke it
b) someone else edited the configuration and broke it

The default queries DO have the following entry for Simultaneous-Use checks:

```
simul_verify_query = "\
	SELECT \
		radacctid, acctsessionid, username, nasipaddress, nasportid, framedipaddress, \
		callingstationid, framedprotocol \
	FROM ${acct_table1} \
	WHERE username = '%{SQL-User-Name}' \
	AND acctstoptime IS NULL"
```

which is the query you're running.

Now go fix it to use the defaults.

**Comment by alandekok** [comment]
And just to close this out.  The query you're running is this:

`WHERE # username = '%{SQL-Group}'  `

The SQL query has  a`#` character in the middle of it, which makes no sense.  And it's comparing a _username_ to a _group_.  That also doesn't make sense.
