### ISSUE TITLE
ARM docker builds

### ISSUE THREAD

**Issue by varac** [FreeRADIUS/freeradius-server#3513]
Please provide ARM / ARM64 builds of the [freeradius server docker image](https://hub.docker.com/r/freeradius/freeradius-server/tags). ARM architecture is getting more and more popular (raspberry pi i.e.) and it would be great to have pre-built images on docker hub. Thanks !

**Comment by shivamb** [comment]
I would be happy to get pre built images for ARM

**Comment by mcnewton** [comment]
Duplicate of #2780

**Comment by helmiaqmarr** [comment]
Hi , is it freeradius is compatible with Linux ARM64 infrastructure ?
