### ISSUE TITLE
FreeRadius Configuration

### ISSUE THREAD

**Issue by dfox1787** [FreeRADIUS/freeradius-server#3515]
Hi

I am trying to get setup with free radius on Ubuntu and the service wont start. The error is in relation to the cert directory. I have searched online and cant find anything to help. 

can anyone help?

see photo
![freerad](https://user-images.githubusercontent.com/28814095/86481890-c3e3c280-bd48-11ea-9256-d7b828735dbf.PNG)

**Comment by herwinw** [comment]
Please use the [mailing list](https://freeradius.org/support/) for questions regarding configuration.
