### ISSUE TITLE
Container quits after start 

### ISSUE THREAD

**Issue by Matthias1992** [FreeRADIUS/freeradius-server#3518]
Hello all,

Well it is a kind of strange, on my Ubuntu server 20 machine, weh i try to create a new container with

docker run --name my-radius -d freeradius/freeradius-server

Its is just exiting after am moment. 

When I try to  start it manually ist just hanging in a restart loop,

I mean there is no config loaded or something that would cause the crash.

Its is just the basic container 

regards Matthias

**Comment by alanbuxey** [comment]
HI,

look at the docker logs, tweak the container so radius is running in debug
mode (I cant recall but think you pass it parameters to add to the server
flags).
what is your container using as its main process (the one that , if dies,
causes the container to quit) - freeradius daemon itself?

alan

**Comment by Matthias1992** [comment]
radiusd: #### Opening IP addresses and Ports ####
listen {
      type = "auth"
      ipaddr = *
      port = 0
   limit {
       max_connections = 16
       lifetime = 0
       idle_timeout = 30
   }
}
listen {
      type = "acct"
      ipaddr = *
      port = 0
   limit {
       max_connections = 16
       lifetime = 0
       idle_timeout = 30
   }
}
listen {
      type = "auth"
      ipv6addr = ::
      port = 0
   limit {
       max_connections = 16
       lifetime = 0
       idle_timeout = 30
   }
Failed opening auth address :: port 1812 bound to server default: Address family not supported by protocol
/etc/freeradius/sites-enabled/default[245]: Error binding to port for :: port 1812

yeahh well of course :D

The reason is I stopped all ipV6 stuff, because the Max View Storage manager has problems with it .... it starts its web port default on ipv6 and you cant access it anymore after an restart

solution would be to restore ipv6 on system again :)
