### ISSUE TITLE
Pluggable Authentication Module (PAM) "pam_radius-release_1_4_0.tar.gz" [ How load balncing works]

### ISSUE THREAD

**Issue by Ashok103606** [FreeRADIUS/freeradius-server#3533]
# Hi,

I have a question about the Pluggable Authentication Module (PAM) "pam_radius-release_1_4_0.tar.gz", load balancing work flow.

If in this following  raddb file when we configure or add the Radius server like this

/etc/raddb/server

Server          Secret         Timeout
Xxxxxxx        xxxxxxx         60seconds
Xxxxxxx      xxxxxxxx        90secnods
;;;
10 servers

Then How the radius authentication request flow works, like I mean if a user request hits the free radius client, then first it goes to the first server in the list if it does not respond then it goes to the second server in the list and so on. Literally how load balancing works between the servers.

Thanks,
Ashok.

**Comment by alandekok** [comment]
read pam_radius_auth.conf.  This is documented.
