### ISSUE TITLE
freeradius cross-compile problem: --with-threads, what is it?

### ISSUE THREAD

**Issue by yabxingzi** [FreeRADIUS/freeradius-server#3562]
my cross tools:
arm-linux-gnueabihf

It's not OK, and then have some error
./configure --host=arm-linux --prefix=/home/pan/project/cusk-camel/ssl-freeradius/compile-arm-test/install_free  CC=/home/pan/toolchain/host/bin/arm-linux-gnueabihf-gcc  --with-talloc-include-dir=../install_talloc/include  --with-talloc-lib-dir=../install_talloc/lib --with-openssl-lib-dir=../install_openssl/lib --with-openssl-include-dir=../install_openssl/include

It is OK
It's not OK, and then have some error
./configure ....... --with-threads=no --with-openssl=no

'--with-threads', what is it?

**Comment by alandekok** [comment]
It is "with threads".  The server uses threads internally.
