### ISSUE TITLE
Ignoring request to auth address * port 1812 bound to server default from unknown client 127.0.0.1 port 58198 proto udp

### ISSUE THREAD

**Issue by SuperCatss** [FreeRADIUS/freeradius-server#3570]
I am a novice and I am learning radius.
I am using freeradius-server in docker, but I currently have some problems.
I am doing the first test.
This is my configuration。
![image](https://user-images.githubusercontent.com/24800663/90363133-b2564000-e094-11ea-97a9-60dd986f9e50.png)
When I execute the following command

>  radtest bob test localhost 0 testing123

I got this output.

> SentAccess-Request Id 225 from 0.0.0.0:58466 to 127.0.0.1:1812 length 73
User-Name = "bob"
User-Password = "test"
NAS-IP-Address = 172.17.0.2
NAS-Port = 0
Message-Authenticator = 0x00
Cleartext-Password = "test"

I got this result.
![image](https://user-images.githubusercontent.com/24800663/90363306-07925180-e095-11ea-8520-07834876d1b9.png)

Can I get some help? Thank you for your help.

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.

And PLEASE post test.  There is absolutely no reason to post an image of text.
