### ISSUE TITLE
[Unlang + SQL] - Multiple Result

### ISSUE THREAD

**Issue by watchix** [FreeRADIUS/freeradius-server#3579]
Hi,

I'm having a problem when a user belong to two or more groups (more than one)

When my SQL SELECT contain more than one result, Unlang compare only the first result (sorted by ID)

Is there a solution to compare a variable from multiple SQL results ?
```
if (&Huntgroup-Name == "%{sql:SELECT groupname FROM radusergroup WHERE username=\"%{User-Name}\"}") {
     ok
}
```

Regards.

**Comment by alandekok** [comment]
questions belong on the freeradius-users mailing list.

And if it's not documented as working, then it's not working.

**Comment by watchix** [comment]
Hi alandekok,

Thx for your quick reply.
Is it possible to add this functionality in the futur dev process ?

Regards.

**Comment by alandekok** [comment]
v4 will have this functionality.
