### ISSUE TITLE
Password contains special character

### ISSUE THREAD

**Issue by lijinlongpq** [FreeRADIUS/freeradius-server#3604]
I found an issue when user password contains special character.
Our AD user has its password set with: Passw0rd!0606
The user able to login to all other application. But cannot login to our VPN (using radius protocol). 
Use the radtest command to test also failed. Then I found that the password in the output is different with the one key in. 
**_radtest test1 Passw0rd!0606 127.0.0.1 0 testing123
radtest test1 Passw0rdls 127.0.0.1 0 testing123
Sent Access-Request Id 99 from 0.0.0.0:38615 to 127.0.0.1:1812 length 75
        User-Name = "test1"
        User-Password = "Passw0rdls"
        NAS-IP-Address = 192.168.2.119
        NAS-Port = 0
        Message-Authenticator = 0x00
        Cleartext-Password = "Passw0rdls"
Received Access-Reject Id 99 from 127.0.0.1:1812 to 127.0.0.1:38615 length 20
(0) -: Expected Access-Accept got Access-Reject**_**

The real password is Passw0rd!0606. But in the output the Cleartext-Password is Passw0rdls.

**Comment by mcnewton** [comment]
Questions belong on the freeradius-users mailing list.

This isn't an issue. You haven't quoted the password and the ! mean your shell is substituting in a command from your history.
