### ISSUE TITLE
Include dictionary raises "Expecting section start brace '{' after "ATTRIBUTE"

### ISSUE THREAD

**Issue by dizaar** [FreeRADIUS/freeradius-server#3610]
OS: CentOS 7.8
freeradius - 3.0.13 (from centos repo) or 3.0.21 (built from sources)
radiusd.conf - last line
**$INCLUDE /usr/share/freeradius/dictionary** 
gives an error:
**Expecting section start brace '{' after "ATTRIBUTE** 

**$INCLUDE /usr/local/ share/freeradius/dictionary.fortinet**
gives an error:
**Expecting section start brace '{' after "VENDOR Fortinet"**

**Comment by alandekok** [comment]
You edited the default configuration and broke it.  Don't do that.

The default github template says that configuration questions belong on the mailing list.  It helps to read documentation and follow it.
