### ISSUE TITLE
Is there a tutorial for docker to build radius? And operate some functions of MySQL database.

### ISSUE THREAD

**Issue by bbhxwl** [FreeRADIUS/freeradius-server#3649]
Is there a tutorial for docker to build radius? And operate some functions of MySQL database.

I want to use docker to build FreeRADIUS, which may be simpler. I want to authenticate the VPN protocol, but I don't know how MySQL should read the database.

**Comment by alandekok** [comment]
As the github template tells you, questions belong on the freeradius-users mailing list.
