### ISSUE TITLE
Make problem 3.0.21

### ISSUE THREAD

**Issue by micron10** [FreeRADIUS/freeradius-server#3655]
Hi i have small build system and try to build new freeradius 3.0.x i migrate from 2.2.10 and when migrate have this build problem 

make[2]: Entering directory '/build'
make -j 16 -C /build/buildorig/freeradius-server-3.0.21
make[3]: Entering directory '/build/buildorig/freeradius-server-3.0.21'
scripts/boiler.mk:628: /build/raddb/all.mk: No such file or directory
make[3]: *** No rule to make target '/build/raddb/all.mk'.  Stop.
make[3]: Leaving directory '/build/buildorig/freeradius-server-3.0.21'
make[2]: *** [package/freeradius/freeradius.mk:137: /build/buildorig/freeradius-server-3.0.21/.built] Error 2
make[2]: Leaving directory '/build'
make[1]: *** [Makefile:38: cross] Error 2
make[1]: Leaving directory '/build/'
make: *** [Makefile:32: all] Error 2

any help

**Comment by jpereira** [comment]
Such comments belongs to the mailing list as can be seen in https://wiki.freeradius.org/guide/Users-Mailing-List

**Comment by alandekok** [comment]
The standard process of `configure`, `make`, and `make install` works.  I suspect you're not following that process.  Or, you're patching the make files.

Please explain _exactly_ what you're doing.

**Comment by micron10** [comment]
Hi  Alan

it is sample build system same that buildroot or other crosstool build
system.

i dont patch any in source .
Yes when i go im directory and run make all is fine

but when i run from outside script
check pwd and script run make in radius dir
but not set path for submake file

**Comment by micron10** [comment]
I find a problem
in new Makefile freeradius use same variables that i use in my build system
( BUILD_DIR, TARGET_DIR ....)
and when i run from build system override this in radius Make..

hm..
how to easy fix this problem ..



На пн, 21.09.2020 г. в 8:21 Martin Zaharinov <micron10@gmail.com> написа:

> Hi  Alan
>
> it is sample build system same that buildroot or other crosstool build
> system.
>
> i dont patch any in source .
> Yes when i go im directory and run make all is fine
>
> but when i run from outside script
> check pwd and script run make in radius dir
> but not set path for submake file
>
>
>

**Comment by alandekok** [comment]
The solution is to spawn a shell with limited environment variables.  You can see the `make` documentation for how to *not* pass variables to a subshell.
