### ISSUE TITLE
Radreply attributes

### ISSUE THREAD

**Issue by GenRockeR** [FreeRADIUS/freeradius-server#3687]
I've one project with Freeradius and rlm_python. Now I use mysql database for Cisco AVPair ACLs. If I've less than 69 ACL all ok. Radius sends a Accept-Accept packet with ACL like this:

"radius.Cisco_AVPair: ip:inacl#100=permit tcp any host 10.99.2.115 eq 80"

But If I've more than 70 ACL Freeradius sends Frafmented IP protocol like this:

"Fragmented IP protocol (proto=UDP 17, off=0, ID=c22d) [Reassembled in #6]"

I have about 600 ACL per user.

As I know I need send Accept-Challenge packet, but I doesn't know how send radreply with Accept-Challenge and by 50 ACL in cycle.

Help me please with unlang or python code in rlm_python.

**Comment by alandekok** [comment]
As the issue template makes clear, questions belong on the freeradius-users mailing list.
