### ISSUE TITLE
unable to compile with -frecord-gcc-switches

### ISSUE THREAD

**Issue by ZeroChaos-** [FreeRADIUS/freeradius-server#3693]
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect
## How to reproduce the issue

build with CFLAGS="-frecord-gcc-switches" and try to compile rlm_python3
 
I can't explain this based on reading configure or configure.ac in src/modules/rlm_python3, but this is the output in src/modules/rlm_python3/config.log
```
configure:2778: python3.7-config's cflags were "-I/usr/include/python3.7m -I/usr/include/python3.7m  -Wno-unused-result -Wsign-compare -Os -march=native -mtune=native -pipe -frecord-gcc-switches -fwrapv -DNDEBUG "
configure:2790: Sanitized cflags were "-isystem/usr/include/python3.7m -isystem/usr/include/python3.7m    -march=native -mtune=native -pipe -frecord -fwrapv "
```

As you can see, somehow -frecord-gcc-switches gets sanitized to -frecord.  I was able to find the sanitize sed lines in configure and configure.ac, but I couldn't reproduce the results...  Hopefully this is more obvious to someone else.

**Comment by jpereira** [comment]
@ZeroChaos- could you please share the output of `python3-config --cflags --ldflags`?

**Comment by ZeroChaos-** [comment]
zero@theprophet ~ % python3-config --cflags --ldflags
-I/usr/include/python3.7m -I/usr/include/python3.7m  -Wno-unused-result -Wsign-compare -Os -march=native -mtune=native -pipe -frecord-gcc-switches -fwrapv -DNDEBUG 
-L/usr/lib64 -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm 


https://github.com/FreeRADIUS/freeradius-server/issues/3693 looks like it would fix the issue to me.  Although that would fix the issue, I'm more curious to fix how half a cflag got stripped out instead of the whole cflag.....  this fix is papering over the issue caused by something else.

**Comment by jpereira** [comment]
@ZeroChaos- you mean that changes in https://github.com/jpereira/freeradius-server/commits/v3/python3 ?

**Comment by ZeroChaos-** [comment]
Correct, yes.

From what I can see, you are pulling in the cflags used to compile python, and then filtering out some things you don't like.  Something is going horribly wrong and part of a cflag is being removed causing breakage.  Finding out what is actually causing this breakage will prevent the next user from hitting a similar bug with a slightly different cflag.

Alternatively, rather than filtering out a few cflags, maybe just whitelist what you actually want from python's cflags and include only those, trusting that if the user wants other things, they will pass them while building freeradius-server.  I feel this would be the saner solution all around, as I would expect it to be significantly more robust.  I am honestly not even sure the purpose of building with *nearly* the same cflags and ldflags as python rather than just the ones passed for the freeradius builds (which are being respected and in my case are identical from a user requested cflags perspective)

**Comment by arr2036** [comment]
@ZeroChaos- can't replicate it here with local sed.  Maybe you could dig into it and submit patches?

**Comment by ZeroChaos-** [comment]
@arr2036 as I said when I opened the bug, I couldn't replicate it running the sed line, only during the build.  I have dug as far as I can, I don't know what is wrong beyond what I've said here.  The proposed solution, while incomplete and not addressing the actual cause, should fix my situation...  I don't know what else I can offer here.

**Comment by arr2036** [comment]
You're in the apparently unique situation where you have a configure script, which, on your system, produces incorrect output.  Maybe you could edit the configure.ac python for rlm_python3 and rebuild the script with autoconf, and see if you can track down what's causing half the flag to be removed...

**Comment by ZeroChaos-** [comment]
I have already tested as much as I can figure.  If no one else has a python built with this or another problematic flag then I guess it's all good.  I edited the configure script and confirmed it's the sed line that breaks it (again, in the original comment) but I cannot narrow it down any further (when I keep editing from this point it doesn't break for me)
