### ISSUE TITLE
FreeRadius Redundancy on a Virtual Machine

### ISSUE THREAD

**Issue by obi1953** [FreeRADIUS/freeradius-server#3739]
I have a question.

I would like to set up a central radius server that is supposed to be redundant via a virtual machine. If one Radius server fails, the other should continue to function automatically. Both Radius servers should syronize throughout.

Can you help me and write instructions. How can I set up all of this?

You're welcome.

It is very important that both should be redundant on one virtual machine. So two Radius servers in one virtual machine.

**Comment by arr2036** [comment]
Support queries are not permitted in GitHub issues, as clearly stated by the [issue template](https://github.com/FreeRADIUS/freeradius-server/blob/master/.github/issue_template.md) shown when you created this ticket.

This issue will now be closed.

Please post support queries on the [user's mailing list](https://freeradius.org/support/)
