### ISSUE TITLE
Radius Server Connection issue from the client installed on Linux 64 bit platform.

### ISSUE THREAD

**Issue by swatibedse123** [FreeRADIUS/freeradius-server#3769]
# Issue type
-Unable to establish UDP connection of our client application  with Radius Server from Linux 64 bit platform. 
Whereas the same application works fine on windows 32 and 64 bit OS,  and Linux 32 bit OS. 
On Linux 64 , we are getting below errors:
-Timeout reached while selecting socket (no.) for reading
- "No response from Server" Error.

- Defect - Unexpected behaviour .

# Defect/Feature description

We have used below code for UDP connection :
       inet_ntop(AF_INET,&(sock->remote_addr.sin_addr),ntopbuffer,sizeof(ntopbuffer)));
        sent = sendto(sock->id, to_send, buf_size, 0,
                (struct sockaddr *)&sock->remote_addr, sizeof(sock->remote_addr));

We have enabled debug logs on Radius Server and getting below error: 
Error: Receive - Malformed RADIUS packet from host XXX: Invalid attribute 0

Please let us know about the solutions.Thanks in advance for the support.

**Comment by alandekok** [comment]
There is a bug in your code, not in FreeRADIUS.  If you want to debug malformed RADIUS packets, use Wireshark.

We are not here to support or debug proprietary RADIUS clients.  You are unwilling to share your application with us, but you want us to work for you, for free, to debug your private code.  Such behavior is not appropriate.
