### ISSUE TITLE
3.0.22 EAP-TLS (tls13)

### ISSUE THREAD

**Issue by ruslan-gennadievich** [FreeRADIUS/freeradius-server#3775]
Im compiled last version from source code. As i see this:

FreeRADIUS 3.0.22 Tue 24 Mar 2020 12:00:00 EDT urgency=low
> 	* Support TLS 1.3 in TLS-based EAP methods.  This has been tested
> 	  to work with hostap and Windows.  Thanks to Jorge Vergara
> 	  for assistance.

Okey, so i want test it.

My /etc/freeradius/mods-enabled/eap
```

tls-config tls-common {
...
		enable_tlsv1_3 = yes
		disable_tlsv1_2 = yes
		disable_tlsv1_1 = yes
		disable_tlsv1 = yes
		tls_min_version = "1.3"
		tls_max_version = "1.3"	
}
```
But if i started freeradius -X i have:
```
Please use tls_min_version and tls_max_version instead of disable_tlsv1
Please use tls_min_version and tls_max_version instead of disable_tlsv1_2
Please use tls_min_version and tls_max_version instead of disable_tlsv1_2
tls: You have disabled all available TLS versions.  EAP will not work
rlm_eap_tls: Failed initializing SSL context
rlm_eap (EAP): Failed to initialise rlm_eap_tls
/etc/freeradius/mods-enabled/eap[14]: Instantiation failed for module "eap"
```

How i can enable eap-tls with tls1.3 ?

**Comment by alandekok** [comment]
The short answer is to delete the `enable_tls1_3` flag.  It isn't used and does nothing.

Then, delete the `disable_tls1*` lines.  If you're using min/max version, then the `disable` flags should not be used.  This is what the debug output is trying to tell you.

I've also fixed the code to handle the (incorrect) case of using both `min/max` and `disable` flags.

**Comment by ruslan-gennadievich** [comment]
Okey, thankyou!

I used it with strongswan (tls13 branch),what you think about this lines:
https://github.com/strongswan/strongswan/blob/tls13/src/libtls/tls.c#L358
it's bug detect TLS version?

**Comment by ruslan-gennadievich** [comment]
src/modules/rlm_eap/libeap/mppe_keys.c: In function 'eaptls_gen_eap_key':
src/modules/rlm_eap/libeap/mppe_keys.c:289:7: error: 'TLS1_3_VERSION' undeclared (first use in this function)
  case TLS1_3_VERSION:
       ^~~~~~~~~~~~~~
src/modules/rlm_eap/libeap/mppe_keys.c:289:7: note: each undeclared identifier is reported only once for each function it appears in
scripts/boiler.mk:635: recipe for target 'build/objs/src/modules/rlm_eap/libeap/mppe_keys.lo' failed

**Comment by alandekok** [comment]
the `TLS1_3_VERSION` macro is defined only if you're using a recent version of OpenSSL.  And those versions all have `TLS1_3_VERSION` defined, _unless_ something went wrong.  I'll push a fix, but that's really a different issue than the previous one reported here.
