### ISSUE TITLE
Freeradius2 openssl1.1.1

### ISSUE THREAD

**Issue by predators46** [FreeRADIUS/freeradius-server#3838]
is there a way so that freeradius2 can use openssl1.1.1? I want to use it on openwrt. currently I am using freeradius-server-2.2.9

**Comment by arr2036** [comment]
Not unless you want to write your own patches. v2.2.x is no longer under active development.  If you want to use FreeRADIUS with OpenSSL 1.1.1, use one of the v3.0.x releases.

**Comment by alandekok** [comment]
OpenWRT supports v3.  Use that.

https://openwrt.org/docs/guide-user/network/wifi/freeradius

**Comment by alandekok** [comment]
Version 2 is end of life.  2.2.10 was a security release, and was released almost 4 years ago.  2.2.9 was released almost 6 years ago.

OpenWRT supports version 3, which is compatible with OpenSSL 1.1.1.  I suggest using *supported* software.

Your choices are:

a) use v3

b) fix version 2 yourself.  We will not be accepting patches for version 2, as it is end of life.

Pick one.

**Comment by predators46** [comment]
> Version 2 is end of life. 2.2.10 was a security release, and was released almost 4 years ago. 2.2.9 was released almost 6 years ago.
> 
> OpenWRT supports version 3, which is compatible with OpenSSL 1.1.1. I suggest using _supported_ software.
> 
> Your choices are:
> 
> a) use v3
> 
> b) fix version 2 yourself. We will not be accepting patches for version 2, as it is end of life.
> 
> Pick one.

i like freeradius2. I wish you could give me a patch for freeradius-2.2.10

**Comment by arr2036** [comment]
It's not build system patches, later versions of OpenSSL made many of the structures we previously had access to, private.  It's a significant amount of effort to backport the fixes to v2.2.x.

**Comment by alandekok** [comment]
> I wish you could give me a patch for freeradius-2.2.10

Since you can't (or won't) understand simple sentences, I'm locking this issue.  I see no point in engaging further.
