### ISSUE TITLE
SQL counter default config does not work with PostgreSQL 12

### ISSUE THREAD

**Issue by nemesisdesign** [FreeRADIUS/freeradius-server#3867]
- Defect - sqlcounter module doesn't work with PostgreSQL 12

# Defect
## How to reproduce the issue

Install freeradius with the postgresql module and postgresql server version 12, enable the sqlcounter module and ensure dailycounter is enabled.
 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

```text
(0) dailycounter: Executing select query: SELECT SUM(AcctSessionTime - GREATER((1611187200 - EXTRACT(epoch FROM AcctStartTime)), 0)) FROM radacct WHERE UserName='openwisp' AND EXTRACT(epoch FROM AcctStartTime) + AcctSessionTime > '1611187200'
rlm_sql_postgresql: Status: PGRES_FATAL_ERROR
rlm_sql_postgresql: 42883: UNDEFINED FUNCTION
(0) dailycounter: ERROR: rlm_sql_postgresql: ERROR:  function greater(double precision, integer) does not exist
(0) dailycounter: ERROR: rlm_sql_postgresql: LINE 1: SELECT SUM(AcctSessionTime - GREATER((1611187200 - EXTRACT(e...
(0) dailycounter: ERROR: rlm_sql_postgresql:                                      ^
(0) dailycounter: ERROR: rlm_sql_postgresql: HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
(0) dailycounter: ERROR: SQL query failed: server error
```

After solving that issue, another one pops up:

```
(0) dailycounter: ERROR: rlm_sql_postgresql: ERROR:  function greater(double precision, integer) does not exist
```

`ABSTIME` is deprecated since PostgreSQL 7 and has been removed in PostgreSQL 12.

I think `GREATER` is a mistake, looks like it should be `GREATEST`.

I suggest replacing occurrences of `AcctStartTime::ABSTIME::INT4` with `EXTRACT(epoch FROM AcctStartTime)` and `GREATER` with `GREATEST`, that's what we're using in @openwisp.

Let me know if this suggestion sounds good and I'll send a patch.

**Comment by alandekok** [comment]
That sounds good.  I'm not sure what was going on there.  The use of `GREATER` goes back to at least 2015, and likely a lot more than that.  So perhaps no one has used `sqlcounter` with PG since then?

**Comment by nemesisdesign** [comment]
> That sounds good. I'm not sure what was going on there. The use of `GREATER` goes back to at least 2015, and likely a lot more than that. So perhaps no one has used `sqlcounter` with PG since then?

That's a good point. I think it's tither one of the following:

- they do not notice this error in their logs (since it doesn't crash the system but only fails the final part of the authorization phase)
- they did notice it, fix it and didn't report it (I think this problem with GREATER/GREATEST happened to me in the past and I didn't report it, but I'm not 100% sure)
- they aren't using PostgreSQL and any of those counters involving GREATER

**Comment by nemesisdesign** [comment]
One question @alandekok, to which branch should the PR be sent?

**Comment by alandekok** [comment]
v3.0.x.  We can do the rest.

**Comment by nemesisdesign** [comment]
Thanks @alandekok, #3873 is up.
