### ISSUE TITLE
Simultaneous Use attribute ! not working on wireless need help

### ISSUE THREAD

**Issue by vijaytejak** [FreeRADIUS/freeradius-server#3939]
Hi I am using the Simultaneous Use attribute in freeradius, it is working when I check with the radtest command.

but any number of clients are able to connect to WiFi, I have enabled accounting as well, using UniFi Access points.

am I missing anything more?

Need help.

**Comment by alandekok** [comment]
The issue template you deleted says that questions belong on the freeradius-users mailing list.

It helps to read documentation.
