### ISSUE TITLE
mschap NT-Domain not correctly parsed

### ISSUE THREAD

**Issue by tomglx** [FreeRADIUS/freeradius-server#3944]
# Issue type
Incorrect code in module rlm_mschap.c. 

***
- Defect - Unexpected behaviour (obvious or verified by project member).

# Defect
## How to reproduce the issue
Microsoft Windows 10 host logons, will result in errors like:

    Auth: (171410)   Login incorrect (mschap_default: FAILED: No NT-Password.  Cannot perform authentication): [host/NBELEKS2.intra.cvk.de/<via Auth-Type = eap>]

PC-Name here is NBELEKS2, correct NT-Domain suffix is intra.cvk.de
The call to ntlm_auth gets only the "intra" part of the domain name from the NT-Domain variable of mschap module.
Therefore the authentication must fail.

I'm guessing that modifying the code of rlm_mschap.c this way, would fix the issue by returning the entire domain suffix.
What's your opinion of to this?

    --- rlm_mschap.c.orig   2021-02-18 11:19:47.640602084 +0100
    +++ rlm_mschap.c        2021-02-18 11:20:40.747224078 +0100
    @@ -351,14 +351,14 @@
                                strlcpy(out, user_name->vp_strvalue + 5, outlen);
                        } else {
                                p++;    /* skip the period */
    -                               q = strchr(p, '.');
    +//                             q = strchr(p, '.');
                                /*
                                 * use the same hack as below
                                 * only if another period was found
                                 */
    -                               if (q) *q = '\0';
    +//                             if (q) *q = '\0';
                                strlcpy(out, p, outlen);
    -                               if (q) *q = '.';
    +//                             if (q) *q = '.';
                        }
                } else {
                        p = strchr(user_name->vp_strvalue, '\\');

**Comment by alandekok** [comment]
Arg... MS changed the format without telling us.

My worry is that we can't really change the behavior for everyone.  It would be much better to add a new expansion, like:

* `%{mschap:Host}` and `%{mschap:Domain-Name}`

in order to deal with this.  v3 is the "stable" release, and changing how it works has large impact on millions of systems.

**Comment by tomglx** [comment]
Why should MS ask us. :-)

As a workaround I'm currently already building my own attribute by using
unlang. In inner-tunnel -> authorize I've inserted

  if (request:User-Name =~ /^host\/([a-z0-9\-]*)\.(.*)$/i) {
     update request {
         AD-Domain := "%{2}"
     }
  }

I've also defined the attribute in the local dictionary.

ATTRIBUTE       AD-Domain               3001    string

It works and is also proof that the change is necessary.
That is also the reason, why my installation relies so heavily on pcre in
freeradius.
I've mentioned this, so that you can plan the change. I'm happy with my
workaround, but there may
be others, who need such a correction to make it work again. Hard to say.


Am Do., 18. Feb. 2021 um 14:54 Uhr schrieb Alan DeKok <
notifications@github.com>:
