### ISSUE TITLE
Upgrading freeradius server version 3.0.xx to latest

### ISSUE THREAD

**Issue by victorgourbiliere** [FreeRADIUS/freeradius-server#3965]
Hello everyone,

There is a way to upgrade a freeradius server to the latest version released ? 

I'm trying to find a solution in the official doc but there no detail about how to upgrade the server.

I'm looking for a step-by-step method if it exist.

Thank you all for spending time to help me.

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
