### ISSUE TITLE
root@proxy:/etc/freeradius/3.0/mods-available# wbinfo -a FBS-00002%Pa%%w0rd@03 plaintext password authentication failed Could not authenticate user FBS-00002%Pa%%w0rd@03 with plaintext password challenge/response password authentication failed wbcAuthenticateUserEx(gksvp.com\FBS-00002): error code was NT_STATUS_WRONG_PASSWORD (0xc000006a, authoritative=1) error message was: When trying to update a password, this return status indicates that the value provided as the current password is not correct. Could not authenticate user FBS-00002 with challenge/response

### ISSUE THREAD

**Issue by thirusubash** [FreeRADIUS/freeradius-server#3972]
HI , Issue with freeradius Samba AD  has big bug , where i tried lot of it not working ,

i am not understanding the password why got changing , Pa$$w0rd@03 is my password , but not working 

root@proxy:/etc/freeradius/3.0/mods-available# wbinfo -a FBS-00002
Enter FBS-00002's password:
plaintext password authentication failed
Could not authenticate user FBS-00002 with plaintext password
Enter FBS-00002's password:
challenge/response password authentication succeeded

when i use wbinfo -a  FBS-00002%Pa$$word@03    changes to this why  FBS-0002%Pa13243w0rd@03

*****NTLM *****

(30) mschap: ERROR: Program returned code (1) and output 'The attempted logon is invalid. This is either due to a bad username or authentication information. (0xc000006d)'
(30) mschap: External script failed
(30) mschap: ERROR: External script says: The attempted logon is invalid. This is either due to a bad username or authentication information. (0xc000006d)
(30) mschap: ERROR: MS-CHAP2-Response is incorrect

******** WINBIND ************

rlm_mschap (mschap): Released connection (2)
Need 3 more connections to reach 10 spares
rlm_mschap (mschap): Opening additional connection (7), 1 of 25 pending slots used
(39) mschap: ERROR: When trying to update a password, this return status indicates that the value provided as the current password is not correct. [0xC000006A]
(39) mschap: ERROR: MS-CHAP2-Response is incorrect

**Comment by alandekok** [comment]
questions belong on the freeradus-users mailing list.
