### ISSUE TITLE
unable disable logs with - Auth Invalid User

### ISSUE THREAD

**Issue by d-mihaylenko** [FreeRADIUS/freeradius-server#4034]
Hello, my FreeRADIUS Version 3.0.21 (git #af428abda), for host x86_64-pc-linux-gnu. I cant disable logs about - Auth Invalid User. Help please.

My logs section in radiusd.conf
<img width="297" alt="Screenshot 2021-03-27 at 21 49 43" src="https://user-images.githubusercontent.com/17220673/112733349-41d7a180-8f48-11eb-8bb1-85c379a01f42.png">
and my radiusd.log
<img width="908" alt="Screenshot 2021-03-27 at 21 37 56" src="https://user-images.githubusercontent.com/17220673/112733367-5ae05280-8f48-11eb-9398-404490e8c410.png">

**Comment by alandekok** [comment]
Already fixed in commit 69eb74fb1f and commit 6c863ae3cf0

**Comment by d-mihaylenko** [comment]
> Already fixed in commit [69eb74f](https://github.com/FreeRADIUS/freeradius-server/commit/69eb74fb1f66e111ec0c8d458eae3752cf3c5260) and commit [6c863ae](https://github.com/FreeRADIUS/freeradius-server/commit/6c863ae3cf0be67341171d3fdb6cc70686e66863)

Please tell me, when the release will be released for installation on Debian 10 in from deb with this commit?

**Comment by alandekok** [comment]
We plan on releasing 3.0.22 in the next month.
