### ISSUE TITLE
Freeradius setup.sql issue

### ISSUE THREAD

**Issue by waffle1992** [FreeRADIUS/freeradius-server#4035]
Hello,

There is an issue with FreeRADIUS Version 3.0.20 and Mysql Ver 8.0.23, 

setup.sql file in mods-config/sql/main/mysql/setup.sql can't create database radius user cause syntax is not up to date for Mysql version 8.

If you are using mysql version 8, please change setup.sql syntax 
old : SET PASSWORD FOR 'radius'@'localhost' = PASSWORD('radpass');

new : SET PASSWORD FOR 'radius'@'localhost' = 'radpass';

**Comment by mcnewton** [comment]
Already fixed in HEAD.
