### ISSUE TITLE
mysql schema import error.

### ISSUE THREAD

**Issue by pizu** [FreeRADIUS/freeradius-server#4048]
Hi,

when trying to import the  the schema am having the below error:

ERROR 1064 (42000) at line 141: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY  (id),
  KEY username (username' at line 6

using FreeRadius v3.0.21

Thanks.

**Comment by alandekok** [comment]
Please read the comments in that file:

```
# Note: MySQL versions since 5.6.4 support fractional precision timestamps
#        which we use here. Replace the authdate definition with the following
#        if your software is too old:
#
#   authdate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
```
