### ISSUE TITLE
3.0.x - Hardware and radiusd.conf requirements best practices

### ISSUE THREAD

**Issue by Djo91** [FreeRADIUS/freeradius-server#4076]
Hello,

This post is not about an issue but just a request.

It takes me about 1h to handle 13k users with radiusd.conf default's configuration.

I would like to know hardware & radiusd.conf (thread pool, cleanup delay...) requirements/specifications that are recommanded to handle more than 500 users by seconde.

I'm looking for an array like the following : 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="Classeur1_fichiers/filelist.xml">
<style id="Classeur1_23550_Styles">

</style>
</head>

<body>

<div id="Classeur1_23550" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=901 style='border-collapse:
 collapse;table-layout:fixed;width:676pt'>
 <col width=115 style='mso-width-source:userset;mso-width-alt:4205;width:86pt'>
 <col width=59 style='mso-width-source:userset;mso-width-alt:2157;width:44pt'>
 <col width=80 style='mso-width-source:userset;mso-width-alt:2925;width:60pt'>
 <col width=53 style='mso-width-source:userset;mso-width-alt:1938;width:40pt'>
 <col width=87 style='mso-width-source:userset;mso-width-alt:3181;width:65pt'>
 <col width=85 style='mso-width-source:userset;mso-width-alt:3108;width:64pt'>
 <col width=125 style='mso-width-source:userset;mso-width-alt:4571;width:94pt'>
 <col width=127 style='mso-width-source:userset;mso-width-alt:4644;width:95pt'>
 <col width=170 style='mso-width-source:userset;mso-width-alt:6217;width:128pt'>
 <tr height=20 style='height:15.0pt'>
  <td rowspan=2 height=40 class=xl6523550 width=115 style='height:30.0pt;
  width:86pt'>Users by seconde</td>
  <td colspan=3 class=xl6523550 width=192 style='border-left:none;width:144pt'>Hardware
  specification</td>
  <td colspan=5 class=xl6523550 width=594 style='border-left:none;width:446pt'>Radiusd.conf</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6523550 style='height:15.0pt;border-top:none;
  border-left:none'>CPU</td>
  <td class=xl6523550 style='border-top:none;border-left:none'>Memory</td>
  <td class=xl6523550 style='border-top:none;border-left:none'>Disk</td>
  <td class=xl6523550 style='border-top:none;border-left:none'>start_servers</td>
  <td class=xl6523550 style='border-top:none;border-left:none'>max_servers</td>
  <td class=xl6523550 style='border-top:none;border-left:none'>min_spare_servers</td>
  <td class=xl6523550 style='border-top:none;border-left:none'>max_spare_servers</td>
  <td class=xl6523550 style='border-top:none;border-left:none'>max_requests_per_server</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6623550 style='height:15.0pt;border-top:none'>up to 10</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6623550 style='height:15.0pt;border-top:none'>up to 50</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6623550 style='height:15.0pt;border-top:none'>up to 100</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6623550 style='height:15.0pt;border-top:none'>up to 500</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6623550 style='height:15.0pt;border-top:none'>up to
  1000</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6623550 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=115 style='width:86pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=80 style='width:60pt'></td>
  <td width=53 style='width:40pt'></td>
  <td width=87 style='width:65pt'></td>
  <td width=85 style='width:64pt'></td>
  <td width=125 style='width:94pt'></td>
  <td width=127 style='width:95pt'></td>
  <td width=170 style='width:128pt'></td>
 </tr>
 <![endif]>
</table>

</div>

</body>

</html>

I'm sorry if this kind of request it's not the first but I didn't find a answer in Freeradius documention and Github website.

Regards

**Comment by alandekok** [comment]
As the issue template says, questions belong on the freeradius-users mailing list.

Performance depends on a huge number of factors.  It is naive to expect that there is one simple number for every situation.

And if you think we're doing to fill out a large table for you, that's not going to happen.  This is not an appropriate request.
