### ISSUE TITLE
current freeradius-git version can not be built on linux since kqueue

### ISSUE THREAD

**Issue by andy-igoshin** [FreeRADIUS/freeradius-server#4077]
current freeradius-git version can not be built on linux since kqueue.

**Comment by alandekok** [comment]
I'm not sure what that means.  If you're building git `master` branch, please don't.  Just use `v3.0.x`, which does work.

**Comment by mcnewton** [comment]
Yes, you need libkqueue for the development version (https://github.com/mheily/libkqueue/). This is documented: https://wiki.freeradius.org/building/Home#hard-dependencies_libkqueue-or-native-kqueue-support-since-v4-0-x

**Comment by andy-igoshin** [comment]
yes, i tried to build master.

i tried to build 3.0.21 + commit 382de65e764e95a69fc2afb3f79289ba52ee34e0 on ubuntu

but this commit depends on early modified structures.
