### ISSUE TITLE
Double Free Bug

### ISSUE THREAD

**Issue by luke-goddard** [FreeRADIUS/freeradius-server#4081]
https://github.com/FreeRADIUS/freeradius-server/blob/1e6136cddc71c38461cefc42966d3da9a81cdc40/src/modules/rlm_unbound/log.c#L163-L186

**Comment by alandekok** [comment]
Where's the double free?  There are two references to `free(val)`, but the `val` attribute gets updated by the lines doing

```
	ret = ub_ctx_get_option(ub, opt, &val);
```

Some additional explanation would be useful.  Simply pointing to a particular bit of code with no explanation is not particularly helpful.

**Comment by arr2036** [comment]
Agreed, there doesn't appear to be a double free here...
