### ISSUE TITLE
New rules w.r.t. certificates used in WPA2-EAP ?

### ISSUE THREAD

**Issue by pe1chl** [FreeRADIUS/freeradius-server#4108]
For some time I have been using freeradius to authenticate users of WiFi against a user/password list maintained in freeradius.
I generated CA and SERVER certificates for the RADIUS server and distributed the CA to most of the clients, and set some other clients to "do not verify certificate".   I know the security implications of that.
From the documentation I have always understood that this is the proper way of doing it, and that it is NOT a good idea to use e.g. a letsencrypt-generated certificate for the server.

But now it appears the panels are moving.  I was configuring WiFi on a recently updated Samsung Android phone, and imported the certificate (the procedure for that has been made more difficult).  After doing that and connecting to the WiFi, the UI asks for a "domain" under the selected certificate.
It is unclear to me what I am supposed to enter there, as the generated SERVER or CA certificates do not have a domain.  And, as is to be expected, the device cannot connect.
When I select "do not verify certificate", it still works OK.

However, when trying to google for this problem to see how to proceed, I see that the next step (in the upcoming Android version) apparently is going to be to remove that option.  All for security.

From the question "domain" I am now guessing that they now do like to an officially signed SERVER certificate and that I need to specify for what domain that was issued.  Entering that domain name would prevent the problem that was the base for the recommendation to setup your own CA and issue your own cert.  And indeed, one of the options is now to use the officially trusted CA list instead of the imported CA.

Is it time to review those recommendations and the script distributed with freeradius to setup the certs?
And if so, what would be a workaround for now to keep both existing clients (that use the imported CA or no CA at all) and the new clients (that would require an officially signed cert) working on the same server/realm?

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.

The example certs and scripts distributed with the server include domain names in the certificates.  If you delete those, it can cause issues.  So don't do that.

You can specify any domain name you want for self-signed CAs, and for server certificates that they generate.  But it's good practice to use your own domain names.

**Comment by pe1chl** [comment]
The certificates I have generated with the supplied scripts do not contain a domain name.
I am using the package distruibuted with Debian Buster, which is freeradius 3.0.17
I will try getting the scripts for the latest version, hopefully it has been fixed there.
