### ISSUE TITLE
why we got unix: IPv6 is not supported error in freeradius?

### ISSUE THREAD

**Issue by tejas-easyfi** [FreeRADIUS/freeradius-server#4123]
I am trying to provide static IPv6 address over PPOE on mikrotik where response is

`(6)   Framed-Compression = Van-Jacobson-TCP-IP
(6)   Framed-IPv6-Address = 2407:7140:0:xxxx::xxx
(6)   MS-CHAP2-Success = 0x01533d32343635413034324646303634343932423443413642344335363942444530314137343038313534
(6)   MS-MPPE-Recv-Key = 0xb999a9473b9aa8cb380a8322c001aaa7
(6)   MS-MPPE-Send-Key = 0xaa3c11f70a75232ac676a0bbd1b28d0d
(6)   MS-MPPE-Encryption-Policy = Encryption-Allowed
(6)   MS-MPPE-Encryption-Types = RC4-40or128-bit-Allowed`

But unable to assign the same and getting following error
`(7)     [detail] = ok
(7) unix: IPv6 is not supported!
(7)     [unix] = noop`

where Freeradius claims it supports IPv6 Freeradius version : 3.0.20

Can somebody help with this. Thanks in advance

**Comment by alandekok** [comment]
The `unix` module does not support IPv6 for the `radwtmp` file.

This has nothing to do with static IPv6 address assignment.
