### ISSUE TITLE
TLS1.3 HandShake Failure on Free Radius Server For Radsec Connection

### ISSUE THREAD

**Issue by praneethgit** [FreeRADIUS/freeradius-server#4124]
-  I see TLS1.3 hanshake failure on Free radius server.
- This is a very simple TLS handshake, Not using any EAP Methods.
- Just client server TLS1.3 connection.
- I am trying to connect to the server using python socket ( TLS1.3 handshake is successful with my python sever program)
- But It is not working with Free Radius.

###########Free Radius Version #####
FreeRADIUS Version 3.0.23 
OpenSSL 1.1.1g FIPS  21 Apr 2020

Radius Client openssl version
OpenSSL 1.1.1g FIPS  21 Apr 2020
########################

When there is a connection request from client I see the below Error on server. We can see that client is sending TLS1.3 Request, but server is throwing error. 

Below are the settings I am using in eap file.

tls_min_version = "1.2"
tls_max_version = "1.3"

(0) (TLS) Initiating new session
(0) (TLS) Setting verify mode to require certificate from client
(0) (TLS) Handshake state - before SSL initialization
(0) (TLS) Handshake state - Server before SSL initialization
(0) (TLS) Handshake state - Server before SSL initialization
(0) (TLS) recv TLS 1.3 Handshake, ClientHello
(0) (TLS) send TLS 1.2 Alert, fatal protocol_version
(0) ERROR: (TLS) Alert write:fatal:protocol version
(0) ERROR: (TLS) Server : Error in error
(0) ERROR: (TLS) Failed reading from OpenSSL: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol
(0) ERROR: (TLS) System call (I/O) error (-1)
(0) FAILED in TLS handshake receive

####################

Is this expected ?

**Comment by praneethgit** [comment]
Working fine. settings were required to change on one more location.

**Comment by csmadhu** [comment]
What is the config to make it working. I am also getting the same error

**Comment by praneethgit** [comment]
Are you trying on python client?

In python program we need to start TLS for TLS1. 3.

Regards
Praneeth

**Comment by csmadhu** [comment]
Hi Praneeth,

I am trying using eapol_client.

Regards,
--Madhu C S

**Comment by alandekok** [comment]
TLS 1.3 did not work in version 3.0.23, for the simple reason that the standards for EAP-TLS and TLS 1.3 were not yet written.

If you need TLS 1.3, use 3.2.0.
