### ISSUE TITLE
'eap: No mutually acceptable types found' when authenticating an android device with WIFI/Freeradius

### ISSUE THREAD

**Issue by IJsblok** [FreeRADIUS/freeradius-server#4137]
Hello,

So I'm new to Freeradius.
My first goal is to setup a Freeradius server which authenticates devices via my Cisco WLC. There are about a zillion howto's to be found on the internet, so no problem. So I have a basic setup with the clients.conf file filled with the necessary NAS info (my WLC) and de USERS file filled with a single simple user; just username an an cleartext-password. I configured RADIUSD.CONF to log all authentication attempts. Then I configured my WLC with the Freeradius info, and created a new WLAN with 802.1x authentication (WPA2 with AES)

Result: I can login to the WLC with the user on the freeradius server (no admin, but that's ok);
I can authenticate a Windows 10 machine with the new WLAN using the Freeradius user;
I CANNOT authenticate any android device on the new WLAN.  

In the RADIUS.LOG are the next entries to seen:

_Sun Jul 11 00:08:44 2021 : Auth: (9)   Login OK: [radius/<via Auth-Type = eap>] (from client Cisco port 0 via TLS tunnel)
Sun Jul 11 00:08:44 2021 : Auth: (10) Login OK: [radius/<via Auth-Type = eap>] (from client Cisco port 1 cli c0-b5-d7-3d-5f-b3)
Sun Jul 11 00:10:07 2021 : Auth: (14) Login incorrect (eap: No mutually acceptable types found): [radius/<via Auth-Type = eap>] (from client Cisco port 1 cli 64-89-f1-f8-cf-6b)_

The first two are from my Windows 10 machine authenticating to the new WLAN.
The last one is from my Android device (Android 10). On the Android device, I get a choice to which EAP Method is to be used. I chose PWD (EAP-PWD) since that's the only one not requiring a certificate. Something similar happens too on my Android 11 device. 

The last line does not mention a password (radius=user). To be clear: I did NOT leave that out on purpose. I filled in the PW on the Android device, maybe the password does not come through or something. 

Googled my ass of for this, found nothing. Any help is appreciated.

**Comment by mcnewton** [comment]
As per the issue template: Questions about the server or its usage MUST be posted to the [users mailing list](http://freeradius.org/list/users.html).  If you post those issues here, they will be closed and locked.

"eap: No mutually acceptable types found" means you need to choose a different EAP type.
