### ISSUE TITLE
READ THE MESSAGE BELOW BEFORE SUBMITTING AN ISSUE

### ISSUE THREAD

**Issue by kholud2017** [FreeRADIUS/freeradius-server#4142]
### Message

Hi
I'm starting to use freeradius application and . I installed freeradius 3.0.21
but  the service becomes freeze/killed after some time (1day, or 3days or 6days..different time )

with error 
logic error in talloc_memlimit_shrink

talloc abort: logic error in talloc_memlimit_shrink

systemd-coredump[476119]: Resource limits disable core dumping for process 4181255 (radiusd).
]: Process 4181255 (radiusd) of user 0 dumped core.

**Comment by alandekok** [comment]
Please use the 3.0.23 packages from http://packages.networkradius.com

They have this, and other issues fixed.
