### ISSUE TITLE
[defect]: radiusd[2808]: segfault 

### ISSUE THREAD

**Issue by xuejinwang63** [FreeRADIUS/freeradius-server#4194]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

kernel: [5133757.133687] radiusd[2808]: segfault at 7f7475b68ade ip 00007f75163c0d90 sp 00007f74adbf3d70 error 4 in libaceclnt.so[7f7516399000+5f000]

Could not be reproduced. we are running 3.0.13. 

### Log output from the FreeRADIUS daemon

```shell
could not capture it
```

### Relevant log output from client utilities

NA

**Comment by alandekok** [comment]
The SEGV is in `libaceclnt.so`, which is not part of FreeRADIUS.

Version 3.0.13 is years out of date.  We don't debug issues which have already been found and fixed.  Use the packages for 3.0.23 from http://packages.networkradius.com

And if there's no information other than "it crashed once", then there's insufficient information for us to do anything about it.

As a result, we cannot take any action on this bug report.
