### ISSUE TITLE
[defect]: smsotp - Failed reading from socket - smsotpd.pl daemon works, and socketfile ist working.

### ISSUE THREAD

**Issue by fuco809** [FreeRADIUS/freeradius-server#4219]
### What type of defect/bug is this?

incorrect 3rd party API usage

### How can the issue be reproduced?

running a freeradius 3.0.20 on ubuntu 20.04lts
with compiled rlm_smsotp module and extra smsotpd.pl
testet smsotpd.pl servvice with netcat , and socket works and runs (/var/run/smsotp_socket)
same ist configured in freeradius smsotp module, but if i try to login i get the "Failed reading from socket"

### Log output from the FreeRADIUS daemon

```shell
# freeradius -ftfxxl stdout

(0) ntlm_auth: Program returned code (0) and output 'NT_STATUS_OK: The operation completed successfully. (0x0)'
(0) ntlm_auth: Program executed successfully
(0)     [ntlm_auth] = ok
rlm_smsotp (smsotp): Reserved connection (0)
(0) smsotp: ERROR: Failed reading from socket
rlm_smsotp (smsotp): Released connection (0)
(0)     [smsotp] = fail
(0)   } # Auth-Type smsotp = fail
(0) Failed to authenticate the user

```

//Relevant log output from client utilities

//started daemon without errors
# ./smsotpd.pl

// testing socket of daemon, which works
# nc -q 1 -U /var/run/smsotp_socket
HELLO

generate otp for DOMAIN\USER
892895536

quit

// Backtrace from LLDB or GDB

_No response_

**Comment by alandekok** [comment]
There are many reasons why reading the socket could fail.  Please try the v3.0.x branch from github, where I've made it print more / better error messages.

**Comment by fuco809** [comment]
after speaking with a developer of smsotpd.pl it seems rlm_smsotp has no working delivery-daemon, because the provided one isnt compatible with that module now, i think the module seems to be outdated, or has anyone a running daemon for it?

**Comment by alandekok** [comment]
You'll have to ask the smsotpd.pl developer for an older version of their software.  Or, see if you can update the rlm_smsotp code in order to be compatible with the newer module.
