### ISSUE TITLE
[defect] Cann't use @ as a username.How to use @ as a ppoe username in freeradius v3

### ISSUE THREAD

**Issue by Soiket** [FreeRADIUS/freeradius-server#4235]
### What type of defect/bug is this?

Non compliance with a standards document

### How can the issue be reproduced?

[defect] Cann't use @ as a username.How to use @ as a ppoe username in freeradius

### Log output from the FreeRADIUS daemon

```shell
[defect] Cann't use @ as a username.How to use @ as a ppoe username in freeradius
```

### Relevant log output from client utilities

[defect] Cann't use @ as a username.How to use @ as a ppoe username in freeradius

### Backtrace from LLDB or GDB

```shell
[defect] Cann't use @ as a username.How to use @ as a ppoe username in freeradius
```

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.  The `User-Name` is allowed to be any character, including `@`.
