### ISSUE TITLE
[defect]: sqlcounter queries for sqlite not compliant with sql

### ISSUE THREAD

**Issue by nemesisdesign** [FreeRADIUS/freeradius-server#4304]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

Queries defined in sqlcounter for sqlite use the greatest function, which is not available in sqlite.

https://github.com/FreeRADIUS/freeradius-server/blob/269b9dfbf54d650201d38e7ba4be1b97b926a945/raddb/mods-config/sql/counter/sqlite/dailycounter.conf#L7-L11

A few months ago I sent a [patch for a similar problem in PostgreSQL queries](https://github.com/FreeRADIUS/freeradius-server/pull/3873), now during the implementation of a [feature of OpenWISP RADIUS](https://github.com/openwisp/openwisp-radius/pull/334) I found out also the default queries of sqlite seem to be erroneous so I am reporting it here.

### Log output from the FreeRADIUS daemon

```shell
no such function: GREATEST
```

### Relevant log output from client utilities

no such function: GREATEST

**Comment by arr2036** [comment]
We don't support external users of the SQL queries.   We provide `GREATEST` for our own sqlite queries.

https://github.com/FreeRADIUS/freeradius-server/blob/master/src/modules/rlm_sql/drivers/rlm_sql_sqlite/rlm_sql_sqlite.c#L396

**Comment by alandekok** [comment]
If you're trying to use the `sql` configuration files from something other than FreeRADIUS, that really won't work.  The solution is to just use FreeRADIUS.

**Comment by nemesisdesign** [comment]
Ah ok, thanks for clarifying that.

**Comment by nemesisdesign** [comment]
BTW, `MAX()` should be able to replace the `GREATEST` function shipped by freeradius, leaving this info here in case anybody finds it useful.
