### ISSUE TITLE
Multiple NAS-IP-Address check attributes in FreeRadius 3.x

### ISSUE THREAD

**Issue by poctopus** [FreeRADIUS/freeradius-server#4325]
### Message

In 2.x I can add a attributes in radcheck table  use the =~ operator, and a regex xxx.xxx.xxx.1|xxx.xxx.xxx.2  

insert into radcheck (username,attribute,op,value) values
('username','NAS-IP-Address','=~','xxx.xxx.xxx.1|=xxx.xxx.xxx.2');

but in 3.x it failed 
(1) sql: ERROR: Error parsing value: Failed resolving "=xxx.xxx.xxx.1|=xxx.xxx.xxx.2" to IPv4 address: Name or service not known 
(1) sql: ERROR: Error parsing user data from database result 
(1) sql: ERROR: Error getting check attributes

what can I do?

**Comment by alandekok** [comment]
As the github template says, questions belong on the freeradius-users mailing list.  And the upgrade process from v2 to v3 is documented, including behavior changes.
