### ISSUE TITLE
Is it possible to Query FreeRadius for User existence or Search user from some custom attribute

### ISSUE THREAD

**Issue by KamranShahid** [FreeRADIUS/freeradius-server#4329]
### Message

I am searching for an option where i might search FreeRAdius for some user existence or find user who have some specific attribute (let's say msisdn with certain number)
I wanted to do these searching from some admin user who's username/password i will configure.
I am able to do user authenticate related functionality from my .net application but above scenarios are not yet achieved

**Comment by mcnewton** [comment]
Questions belong on the mailing list.

**Comment by KamranShahid** [comment]
> Questions belong on the mailing list.

Can't get what is mean't by this? I just need to know is it technically possible or not
