### ISSUE TITLE
[defect]: data structure p empty when called from dynamic-clients server

### ISSUE THREAD

**Issue by misch42** [FreeRADIUS/freeradius-server#4344]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

When I call the python3 module from the authorize section of the default server the module, by default, lists the data structure p that is passed to the module. The python code is

```
def authorize(p):
  print("*** authorize ***")
  radiusd.radlog(radiusd.L_INFO, '*** radlog call in authorize ***')
  print(p)
  return (radiusd.RLM_MODULE_OK, reply)
```

The output is:

```
*** authorize ***
*** radlog call in authorize ***

(('User-Name', 'user'), ('User-Password', 'password'), ('NAS-IP-Address', '127.0.0.1'), ('NAS-Port', '1'), ('Message-Authenticator', '0x2e80a0a398d496156e832cee0408f4cb'), ('Event-Timestamp', 'Dec 19 2021 17:50:31 CET'))
```

But when I call the same python3 module from the authorize section of the dynamic-clients server I get the following log:

```
(0) server dynamic_clients {
(0) # Executing section authorize from file /etc/raddb/sites-enabled/dynamic-clients
(0)   authorize {
*** authorize ***
*** radlog call in authorize ***
None
```

So the data structure p passed to the module seems to be empty. But I need at least the Packet-Src-IP-Address (or IPv6) to use in my python module. 

### Log output from the FreeRADIUS daemon

```shell
(0) server dynamic_clients {
(0) # Executing section authorize from file /etc/raddb/sites-enabled/dynamic-clients
(0)   authorize {
*** authorize ***
*** radlog call in authorize ***
None
```
```


### Relevant log output from client utilities

_No response_

### Backtrace from LLDB or GDB

_No response_

**Comment by jpereira** [comment]
Which version of FreeRADIUS? Please, share the entire "radiusd -X"

**Comment by misch42** [comment]
I think I found the problem. I have to set

```
pass_all_vps_dict = yes
```

The other problem that bothers me at the moment is that I did not find a way to return control attributes from the python3 module to the server. But exactly control attributes are needed in the dynamic-clients server

**Comment by mcnewton** [comment]
It's the `config` list (the historical name for the `control` list), as shown in the example script: https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/modules/rlm_python3/example.py
