### ISSUE TITLE
[defect]: mods-config/sql/main/mssql

### ISSUE THREAD

**Issue by JCarvajal1973** [FreeRADIUS/freeradius-server#4353]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

freeradius version 3.0.25

When you configure freeradius for use mssql there is a little bug in the sql syntax...

in the file queries.conf line 212 and above with same sql....
original:   ${..class.column_name}) \
should be:  ${....class.column_name}) \      # with two dots more 
![freeradiuserror](https://user-images.githubusercontent.com/97259209/148458124-4ceb7861-8ce6-486e-841d-fb16a0ccda5c.jpg)

### Log output from the FreeRADIUS daemon

```shell
/usr/local/etc/raddb/mods-config/sql/main/mssql/queries.conf[239]: Reference "${..class.column_name}" not found
Errors reading or parsing /usr/local/etc/raddb/radiusd.conf
```

### Relevant log output from client utilities

Not necesary

**Comment by jpereira** [comment]
@JCarvajal1973 Please check if the `/usr/local/etc/raddb/mods-config/sql/main/mssql/queries.conf` has this content https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/mods-config/sql/main/mssql/queries.conf#L65

**Comment by JCarvajal1973** [comment]
Hello jpereira, yes, i check and ... yes have the error that i have post.

**Comment by alandekok** [comment]
Pushed in commit 23298f7d7c
