### ISSUE TITLE
[defect]: CHAP challenge issues

### ISSUE THREAD

**Issue by dd1245** [FreeRADIUS/freeradius-server#4390]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

Allowing CPE equipment running PPP to connect to its LNS, which is using a FreeRADIUS server for authentication.

Regardless of using the correct password on the CPE equipment, We seem to have an issue where the CHAP challenge calculation determines an authentication failure. We have tested multiple accounts and checked both the password on the FreeRADIUS server and CPE device is 100% correct. 

I'm happy to be told it's a problem with the LNS network device if this could not be a FreeRADIUS issue.

### Log output from the FreeRADIUS daemon

```shell
Wed Feb  2 11:14:27 2022 : Debug: (1) chap: Using challenge from &request:CHAP-Challenge
Wed Feb  2 11:14:27 2022 : Debug: (1) chap:   CHAP challenge : 8996061b29633535f4cb64104a2c6873
Wed Feb  2 11:14:27 2022 : Debug: (1) chap:   Client sent    : 07527ea2492af5999375b85af362fe84
Wed Feb  2 11:14:27 2022 : Debug: (1) chap:   We calculated  : 59798bf3541393bd0eed5855ffc81838
Wed Feb  2 11:14:27 2022 : ERROR: (1) chap: Password comparison failed: password is incorrect
```

### Relevant log output from client utilities

radtest on the server itself authenticates fine, which would lead me to believe its the network hardware, but could this be an issue with CHAP? We are running version FreeRADIUS version 3.0.20.

**Comment by alandekok** [comment]
Realistically, the CPE / LNS is broken.  Or, the packets are going through a RADIUS proxy, and the RADIUS proxy is broken.  Or, the passwords have magic characters in them, and they're not being escaped properly by the client and/or the DB.

FreeRADIUS has been doing CHAP for 20+ years.  The specs are simple and clear.  The code in FreeRADIUS is well tested, with every single CHAP implementation on the planet.

In addition, you've given insufficient information for us to verify the problem.  For example, we'd need a password to check the CHAP-Challenge and CHAP-Password.

But in any case, this cannot possibly be an issue in FreeRADIUS.  We have tests which run on every commit which verify that the CHAP implementation is correct:

```
$ ls src/tests/auth/chap*
src/tests/auth/chap			src/tests/auth/chap_header
src/tests/auth/chap.attrs		src/tests/auth/chap_header.attrs
```

If FreeRADIUS didn't do CHAP properly, then every single server administrator on the planet would be complaining.

Here's how to check:

1) set the password to something simple, like "hellothere".

2) to authenticate

3) if it succeeds, then the password is likely escaped incorrectly

4) if it fails, then see above for a list of what else could be wrong

This is not FreeRADIUS.
