### ISSUE TITLE
Dynamic VLAN Assignement depending on the ip source

### ISSUE THREAD

**Issue by Ben0606** [FreeRADIUS/freeradius-server#4407]
### Message

Hello,
I have configured a freeradius V3 with automatic VLAN assignement, all work fine.

I want to know how it is possible to assign a VLAN depending on the source IP. 

For exemple :

If User A connect freeradius from 18.18.18.18 (public ip) => assign VLAN 1
If User A connect freeradius from 20.20.20.20 (public ip) => assign VLAN 3
If User A connect freeradius from 30.30.30.30 (public ip) => assign VLAN 4

Could you help me please ?

thanks for your help, I'm French so excuse my English.

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.  You get told this when opening a github issue.
