### ISSUE TITLE
[defect]: Error when restarting freeradius after sql configuration

### ISSUE THREAD

**Issue by arty0mflv** [FreeRADIUS/freeradius-server#4409]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

Hi, new to github so apologize if my issue is not correctly formuled i'm in a rush and i need support about an error i'm getting on a debian 11 vm running freeradius-server.
I followed this tutorial to set it up : https://www.youtube.com/watch?v=JffiXdMFkOc

At 15:55 after configuring freeradius to use mysql i need to configure the virtual server in the mods files etc... when restarting i get an error, after a journalctl -xe (i think ? new to linux and IT in general sorry i'm not used to the basic commands) i get this screen :

![PXL_20220309_155902660](https://user-images.githubusercontent.com/101279094/157492541-1e536db1-4ac2-42f8-b345-f416fb9786c1.jpg)

From what i understand it's because of the dialect thing that is not found in the /mods-enabled/sql file + the radiusd.conf not reading, that's where i'm getting lost i replicated everything from the video and it worked until now sooo, from a quick search all i found was an instances order problem but i don't think it is cause the logs people getting this issue and fixing it post are different.

If i receive answers today i won't be able to test it until i get back to my desk at work, anyways i thank you for your help and will keep you up to date.

### Log output from the FreeRADIUS daemon

```shell
/etc/freeradius/3.0/mods-enabled/sql[340]: Reference "${dialect}" not found
Errors reading or parsing /etc/freeradius/3.0/radiusd.conf
freeradius.service: Control process exited, code=exited, status=1/FAILURE
```

**Comment by mcnewton** [comment]
This is a config error, not a bug. Questions belong on the freeradius-users list, as you are told when opening a Github issue.
