### ISSUE TITLE
Ubuntu version used for docker images 

### ISSUE THREAD

**Issue by AlessioCasco** [FreeRADIUS/freeradius-server#4410]
### Message

Hello

In this repo I see multiple dockerfiles, based on different Linux flavours. 
On dockerhub I see this line:
```The de-facto image which should be used unless you know you need another image. It is based on [Ubuntu Linux](https://hub.docker.com/_/ubuntu/) Docker images.```

Where can I see what dockerfile is used for the de-facto image? I'm interested in understanding what exact verison of ubuntu the images are built from.

Thanks
Alessio

**Comment by jpereira** [comment]
@AlessioCasco Questions belong on the freeradius-users list, as you are told when opening a Github issue.

**Comment by AlessioCasco** [comment]
Ok, sorry about that
