### ISSUE TITLE
[defect]: Failed to start FreeRADIUS multi-protocol policy server

### ISSUE THREAD

**Issue by Rajkumar2468** [FreeRADIUS/freeradius-server#4420]
### What type of defect/bug is this?

Failed to start FreeRADIUS multi-protocol policy server

### How can the issue be reproduced?

I was used ubuntu 20.04  

But I found that path was changed. In documentation says /etc/freeradius/mods-enabled but I have only /etc/freeradius/3.0/mods-enabled 
I follewed all instructions, but I have problem with restarting freeradius
[https://wiki.freeradius.org/building/Debian%20and%20Ubuntu#building-development-versions-v4-0_building]

From the output of systemctl status freeradius.service

![image](https://user-images.githubusercontent.com/58545041/158746748-fbefe8a9-8eba-4dce-b370-eea969b2db0e.png)

### Log output from the FreeRADIUS daemon

```shell
I was checked log output from the FreeRadius using this command - $radiusd -X
I followed the instructions but I have problem with restarting freeradius

  # Loaded module rlm_files
  # Loading module "files" from file /usr/local/etc/raddb/mods-enabled/files
  files {
        filename = "/usr/local/etc/raddb/mods-config/files/authorize"
Unable to check file "/usr/local/etc/raddb/mods-config/files/authorize": Permission denied
/usr/local/etc/raddb/mods-enabled/files[9]: Failed parsing configuration item "filename"
/usr/local/etc/raddb/mods-enabled/files[9]: Invalid configuration for module "files"
```

### Relevant log output from client utilities

From the output of radiusd -X

<img width="936" alt="Capture4" src="https://user-images.githubusercontent.com/58545041/158746455-297fc778-6a36-4d9a-9d4c-f182ad8cd55d.PNG">

Iam using systemd hould look at the logs using the command    journalctl -b 0 -u freeradius very long, there last lines

![image](https://user-images.githubusercontent.com/58545041/158747009-cbff87d4-0cf0-4e80-bc55-176337b44521.png)

From the logs you pasted the configuration seems good so the problem could be that freeradius returns this error.

Anyone know how I can resolve this?

**Comment by alandekok** [comment]
> But I found that path was changed. In documentation says /etc/freeradius/mods-enabled but I have only /etc/freeradius/3.0/mods-enabled

Debian / Ubuntu changes the files, and doesn't update the documentation.  The web site, etc. contains documentation for the normal configuration.

As for the rest, configuration issues belong on the freeradius-users mailng list.  But you have enough information to solve the problem yourself.  All you need to do is to *read* the error messages.

And posting screen captures of text output?  Really?  Why would that ever be a good idea?
