### ISSUE TITLE
NetworkRadius official package repos for Ubuntu and Debian lacks freeradius-perl and freeradius-python3 packages

### ISSUE THREAD

**Issue by r-duran** [FreeRADIUS/freeradius-server#4451]
### Message

NetworkRadius official package repos for Ubuntu and Debian lacks freeradius-perl and freeradius-python3 packages. Is there a reason why these modules are not included in official repos?

**Comment by mcnewton** [comment]
Perl and Python modules are in the main `freeradius` DEB package, whereas with RPM they are packaged separately, for historical reasons.

`rlm_python3` isn't packaged for anything. PR's welcome. We hardly ever recommend using any of the language modules, so it doesn't make it up the priority list.

**Comment by JqckB** [comment]
@mcnewton It is available for Debian Bullseye for 3.2.0 but not for Ubuntu 22.04 (but available for Ubuntu 20.04).
I know that you are not recommending it, but it is inconsistent between OS or version of OS.

Can you help to release a Ubuntu Jammy release with rlm_python.so built inside it ?
