### ISSUE TITLE
[defect]: compilation failed using --without-tcp

### ISSUE THREAD

**Issue by heiko3** [FreeRADIUS/freeradius-server#4484]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

$ ./configure --without-tcp --disable-developer
$ make -j 36

src/main/process.c: In function 'event_new_fd':
src/main/process.c:5472:3: error: label 'listener_is_eol' used but not defined
 5472 |   goto listener_is_eol;

-----------------------------------------------------------------------------
And even more problems if --disable-developer is left out.

$ ./configure --without-tcp
$ make -j 36

In file included from src/main/listen.c:28:
src/main/listen.c: In function 'listen_coa_add':
src/main/listen.c:3982:19: error: 'rad_listen_t' {aka 'struct rad_listen'} has no member named 'parent'
 3982 |  rad_assert(this->parent);

### Log output from the FreeRADIUS daemon

```shell
If it compiled, it would come up with:

FreeRADIUS 3.2.0 (release)
FreeRADIUS 3.2.1 (git HEAD commit c2be62c4eb3d6b133e1207ca4a3092e02ed18030)
```

**Comment by alandekok** [comment]
This is fairly low priority.  The default is to build with TCP.  If you could supply a patch to fix this, that would be useful.
