### ISSUE TITLE
sha512 value for freeradius-server source download for 3.0.25 has changed

### ISSUE THREAD

**Issue by stvshw** [FreeRADIUS/freeradius-server#4489]
### Message

We have a process where we pull the source code for the freeradius server as part of our build process. We have used other versions, but the current version is 3.0.25. We use the following command:

wget https://github.com/FreeRADIUS/freeradius-server/archive/release_3_0_25.zip

As part of this process, we have the sha512 value for the zip checked in, and we do a compare to ensure there are no changes or issues with the download.

Recently, the process started failing because the sha512 value changed for the downloads of the zip.

Our checked in value: 4dc07698469a8cf16853250c26140fe6c5f0b59e5167a9019190af241fc2670fc6dd7f470b72030441c381eebb7b2613894e7031754be0cead2747f5238ffce8

Current value:  b844545f51b0e703e47e23346a7e9d2de39155a375aad3cb177f8e95c9576353a19ab303c71d082fad264cd8601bc027a843ac03dc2c29d2dc55c756a53b7bc3

An evaluation of a previous download and the current download seems to show that the changes are only in rlm_couchbase. However, everything internal to the zip seems to be dated the same (Oct 7, 2021). 

From what we can find, there is no mention of a change to the existing release on the freeradius site. We would like to know if it is intentional, or if something else is be going on.

I have attached a copy of a previous download and the current download.

[current_download_release_3_0_25.zip](https://github.com/FreeRADIUS/freeradius-server/files/8621520/current_download_release_3_0_25.zip)

[previous_download_release_3_0_25.zip](https://github.com/FreeRADIUS/freeradius-server/files/8621500/previous_download_release_3_0_25.zip)

**Comment by stvshw** [comment]
Hi @alandekok. I don't understand why this issue was closed without comment. Having the sha512 hash change for a release download is concerning.  Please let me know if I did not submit this correctly or to the right location.

**Comment by alandekok** [comment]
This was discussed on the mailing list today.

https://lists.freeradius.org/pipermail/freeradius-users/2022-May/101854.html

**Comment by mcnewton** [comment]
To be completely clear on this - **we do not release *any* .zip files**. GitHub adds them. The official releases are the signed .tar.gz and .tar.bz2 files, which are (I just checked) identical on both the GitHub releases page and the FreeRADIUS ftp site. You can check the GPG signature in the .sig files to make sure they have been released by us.

Ignore the zip files. We don't release them and they are not signed by us.

**Comment by stvshw** [comment]
Thank you for the clarification. That makes sense and we are making the needed changes.
