### ISSUE TITLE
Freeradius cassandra driver not available in latest stable version

### ISSUE THREAD

**Issue by danielserrao** [FreeRADIUS/freeradius-server#4527]
### Message

Hi,

I would like to make my Freeradius environment to store data in a Cassandra DB, but the following branches don't have this driver:
- release_3_0_25 (STABLE)
- release_3_2_0 (LATEST STABLE)
- branch_4_0_0 (NOT STABLE)

The branches that have this driver but are NOT STABLE:
- master
- python-v4-rework

The last time the cassandra driver was worked on was 3 years ago according to what I see on both of the above branches but it was never actually released, so I don't think that is a good sign.

So, I would like to know if the Freeradius developers intend to eventually release a stable version with the Cassandra driver or not and when it is estimated for this release to happen? I couldn't find this information anywhere.

**Comment by danielserrao** [comment]
I have no idea why the label "close" was created automatically, but it would still be nice to have an answer to my question.

**Comment by mcnewton** [comment]
Because you ignored the message about only reporting actual bugs in the GitHub issue system, ignored the issue templates and the questionnaire, ignored all the message that say please ask questions on the mailing list, and chose to ask here anyway.

It would be very useful to know how we could make it clearer?

**Comment by danielserrao** [comment]
It's not clear where I should post this kind of questions. I saw the "users mailing list", but on that page it says "This list is for technical discussions", so is not clear where non-technical questions should be posted. Could you please clarify?

**Comment by alandekok** [comment]
Once again, how could we make the documentation any clearer?  The list is for discussions around FreeRADIUS.  So... is your question about FreeRADIUS?  Then there should be no confusion.
