### ISSUE TITLE
[defect]: The typo in the website docs 

### ISSUE THREAD

**Issue by JoyHusky** [FreeRADIUS/freeradius-server#4545]
### What type of defect/bug is this?

Non compliance with a standards document

### How can the issue be reproduced?

https://networkradius.com/doc/3.0.10/unlang/regex.html

The =~ operator evaluates to true when data matches the /regex/ expression. Otherwise, it evaluates to false.

The !~ operator evaluates to true when data does not match the /regex/ expression. Otherwise, it evaluates to **true**.

There is must be false, not true.

### Log output from the FreeRADIUS daemon

```shell
-
```

**Comment by arr2036** [comment]
NetworkRADIUS != FreeRADIUS

**Comment by arr2036** [comment]
Because we link to useful documentation from the FreeRADIUS website.  If you have an issue with something NetworkRADIUS publish then contact them directly.
