### ISSUE TITLE
Request for modification function 'sql_select_query()' in file rlm_sql_oracle.c.

### ISSUE THREAD

**Issue by lucian75** [FreeRADIUS/freeradius-server#4609]
### Message

Hello.

 I have a question about function 'sql_select_query()' in file rlm_sql_oracle.c.

 I want to add a query like %{sql1:select ...} to the config, but the code below seems to give me an error.
 After execute one of select query in query.conf, when %{sql1:select ...} is called I can see error.
 My guess is that the error looks like to occurs because the number of columns returned is different.

 In the function there are some codes like below.

	 /*
	 *	We only need to do this once per result set, because
	 *	the number of columns won't change.
	 */
	if (conn->col_count == 0) {
		conn->col_count = sql_num_fields(handle, config);

		if (conn->col_count == 0) return RLM_SQL_ERROR;
	}

So I want to know the code can be modified to 

	 conn->col_count = sql_num_fields(handle, config);
	 if (conn->col_count == 0) return RLM_SQL_ERROR;

Thank you.

**Comment by lucian75** [comment]
Hello. @alandekok 

I cannot find any changes in code. and there are any mentions about my issue.
Does it mean that it's written for your intent and doesn't need to be modified?

I had wrote extra sql modules and am using that.

Thank you for thinking about it more.

https://wiki.freeradius.org/modules/rlm_sql
   
    %{sql:SELECT mytable.field1 FROM `mytable` WHERE 1}

**Comment by lucian75** [comment]
Hello. @alandekok

I cannot find any changes in code. and there are any mentions about my
issue.
Does it mean that it's written for your intent and doesn't need to be
modified?

I had wrote extra sql modules and am using that.

Thank you for thinking about it more.

https://wiki.freeradius.org/modules/rlm_sql

    %{sql:SELECT mytable.field1 FROM `mytable` WHERE 1}

2022년 7월 11일 (월) 오후 9:10, Alan DeKok ***@***.***>님이 작성:

**Comment by lucian75** [comment]
It seems I have found the cause of the error.
 I'm using sqlmap , and it seems to be happening in the mod_map() function in the rlm_sql_map.c file.

	res = inst->sql_inst->sql_select_query(inst->sql_inst, request, &handle, query);
	talloc_free(query);
	if (res != RLM_SQL_OK) {
		if (handle) fr_connection_release(inst->sql_inst->pool, handle);

		return RLM_MODULE_FAIL;
	}

	fr_assert(handle != NULL);

	if (sql_map_do(inst, request, &handle) > 0) rcode = RLM_MODULE_UPDATED;

	if (handle) {
		(inst->sql_inst->module->sql_finish_query)(handle, inst->sql_inst->config);

		fr_connection_release(inst->sql_inst->pool, handle);
	}

 The source code appears to be written to terminate the process by calling the sql_select_query() function and then the sql_finish_query() function.
 However, if I look at the rlm_sql_oracle.c file where the sql_finish_query() function is defined, there is no code for finishing processing as follows.


	static sql_rcode_t sql_finish_query(UNUSED rlm_sql_handle_t *handle, UNUSED rlm_sql_config_t *config)
	{
		return 0;
	}

This part seems to be a bug, can you please fix it?

**Comment by alandekok** [comment]
This issue contains a bunch of code, and a bunch of comments about things went wrong, and "I can see an error".  But there's no description of what went wrong.  You haven't included any error message.

I don't see why you think we can do anything as a result of these comments.  Even the comment about `sql_finish_query()` is empty.  So?  Check out that function in the other SQL drivers.  Some drivers need a function there, others don't.

Many people use Oracle without an issue.  Your comments here are a lot of running around in circles, with essentially zero content.

There is no way we can do anything as a result of vague descriptions.

**Comment by lucian75** [comment]
Hello, @alandekok 

Like your comment, I ask again by adding a description and log.

 First, explain the error again, the error does not occur when using the sql module.
 Because it calls the SELECT function and then the sql_finish_select_query() function.

 But when I use sql_map I get an error. This is because, unlike the sql module, in sql_map,
the sql_finish_query() function is called after the select query function is called, but
that function does not have an exit code like sql_finish_select_query().

So if you add code to set col_count to 0 in sql_finish_query() it doesn't seem to get error.

In my case, this error occurs frequently. Below is a part of the log for your understanding.

Thanks.


* Test Log

 This is the log just before the error occurred, and the query was executed normally.

	Fri Jul 15 16:09:02 2022 : Debug: (67)         if ("%{ora1:select 1 from dual}") {
	Fri Jul 15 16:09:02 2022 : Debug: %{User-Name}
	Fri Jul 15 16:09:02 2022 : Debug: Parsed xlat tree:
	Fri Jul 15 16:09:02 2022 : Debug: attribute --> User-Name
	Fri Jul 15 16:09:02 2022 : Debug: (67)         EXPAND %{User-Name}
	Fri Jul 15 16:09:02 2022 : Debug: (67)            --> testmobile01
	Fri Jul 15 16:09:02 2022 : Debug: (67)         SQL-User-Name set to 'testmobile01'
	Fri Jul 15 16:09:02 2022 : Debug: rlm_sql (ora1): Reserved connection (3)
	Fri Jul 15 16:09:02 2022 : Debug: (67)         Executing select query: select 1 from dual
	Fri Jul 15 16:09:02 2022 : Debug: rlm_sql (ora1): Released connection (3)
	Fri Jul 15 16:09:02 2022 : Debug: (67)         EXPAND %{ora1:select 1 from dual}
	Fri Jul 15 16:09:02 2022 : Debug: (67)            --> 1
	Fri Jul 15 16:09:02 2022 : Debug: (67)         if ("%{ora1:select 1 from dual}")  -> TRUE
	Fri Jul 15 16:09:02 2022 : Debug: (67)         if ("%{ora1:select 1 from dual}")  {
	Fri Jul 15 16:09:02 2022 : Debug: (67)           modsingle[authorize]: calling ora_map1 (rlm_sql_map)
	Fri Jul 15 16:09:02 2022 : Debug: rlm_sql (ora1): Reserved connection (4)
	Fri Jul 15 16:09:02 2022 : Debug: %{User-Name}
	Fri Jul 15 16:09:02 2022 : Debug: Parsed xlat tree:
	Fri Jul 15 16:09:02 2022 : Debug: attribute --> User-Name
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: EXPAND %{User-Name}
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1:    --> testmobile01
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: SQL-User-Name set to 'testmobile01'
	Fri Jul 15 16:09:02 2022 : Debug: SELECT SqlExecResult, PasswordWithHeader, Class, ReplyMessage, AirespaceACLName, TunnelType, TunnelMediumType, TunnelPrivateGroupId FROM RADATTRMAP
	Fri Jul 15 16:09:02 2022 : Debug: Parsed xlat tree:
	Fri Jul 15 16:09:02 2022 : Debug: literal --> SELECT SqlExecResult, PasswordWithHeader, Class, ReplyMessage, AirespaceACLName, TunnelType, TunnelMediumType, TunnelPrivateGroupId FROM RADATTRMAP
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: EXPAND SELECT SqlExecResult, PasswordWithHeader, Class, ReplyMessage, AirespaceACLName, TunnelType, TunnelMediumType, TunnelPrivateGroupId FROM RADATTRMAP
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1:    --> SELECT SqlExecResult, PasswordWithHeader, Class, ReplyMessage, AirespaceACLName, TunnelType, TunnelMediumType, TunnelPrivateGroupId FROM RADATTRMAP
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: Executing select query: SELECT SqlExecResult, PasswordWithHeader, Class, ReplyMessage, AirespaceACLName, TunnelType, TunnelMediumType, TunnelPrivateGroupId FROM RADATTRMAP
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: control:SQL-Exec-Result := OK
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: control:Password-With-Header := {MD4}AD6DBBAE701FF72E0DE949D975C3F718
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: reply:Class := 0x
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: reply:Reply-Message := OK
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: reply:Airespace-ACL-Name := setup
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: reply:Tunnel-Type := VLAN
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: reply:Tunnel-Medium-Type := 802
	Fri Jul 15 16:09:02 2022 : Debug: (67) ora_map1: reply:Tunnel-Private-Group-Id := 213
	Fri Jul 15 16:09:02 2022 : Debug: rlm_sql (ora1): Released connection (4)
	Fri Jul 15 16:09:02 2022 : Debug: (67)           modsingle[authorize]: returned from ora_map1 (rlm_sql_map)
	Fri Jul 15 16:09:02 2022 : Debug: (67)           [ora_map1] = updated
	Fri Jul 15 16:09:02 2022 : Debug: (67)         } # if ("%{ora1:select 1 from dual}")  = updated


  At this part, an error 'rlm_sql_oracle: ORA-24334: no descriptor for this position' occurred.
  The cause of the error seems to be that the number of columns is different from the previous query result.

	Fri Jul 15 16:09:02 2022 : Debug: (68)         if ("%{ora1:select 1 from dual}") {
	Fri Jul 15 16:09:02 2022 : Debug: %{User-Name}
	Fri Jul 15 16:09:02 2022 : Debug: Parsed xlat tree:
	Fri Jul 15 16:09:02 2022 : Debug: attribute --> User-Name
	Fri Jul 15 16:09:02 2022 : Debug: (68)         EXPAND %{User-Name}
	Fri Jul 15 16:09:02 2022 : Debug: (68)            --> testmobile01
	Fri Jul 15 16:09:02 2022 : Debug: (68)         SQL-User-Name set to 'testmobile01'
	Fri Jul 15 16:09:02 2022 : Debug: rlm_sql (ora1): Reserved connection (0)
	Fri Jul 15 16:09:02 2022 : Debug: (68)         Executing select query: select 1 from dual
	Fri Jul 15 16:09:02 2022 : Error: rlm_sql_oracle: OCIParamGet() failed in sql_select_query
	Fri Jul 15 16:09:02 2022 : ERROR: (68)         rlm_sql_oracle: ORA-24334: no descriptor for this position 
	Fri Jul 15 16:09:02 2022 : ERROR: (68)         SQL query failed: server error
	Fri Jul 15 16:09:02 2022 : Debug: rlm_sql (ora1): Released connection (0)
	Fri Jul 15 16:09:02 2022 : Debug: (68)         EXPAND %{ora1:select 1 from dual}
	Fri Jul 15 16:09:02 2022 : Debug: (68)            --> 
	Fri Jul 15 16:09:02 2022 : Debug: (68)         if ("%{ora1:select 1 from dual}")  -> FALSE
	Fri Jul 15 16:09:02 2022 : Debug: (68)         else {
	Fri Jul 15 16:09:02 2022 : Debug: (68)           update control {
	Fri Jul 15 16:09:02 2022 : Debug: (68)             &Auth-Type := Reject
	Fri Jul 15 16:09:02 2022 : Debug: (68)             Overwriting value "eap" with "Reject"
	Fri Jul 15 16:09:02 2022 : Debug: (68)             &SQL-Exec-Result := 'FAILURE'
	Fri Jul 15 16:09:02 2022 : Debug: (68)           } # update control = noop
	Fri Jul 15 16:09:02 2022 : Debug: (68)         } # else = noop

**Comment by alandekok** [comment]
Try this patch. It's untested, as we don't have resources to purchase Oracle.  But based on the description, it might work.

[patch.gz](https://github.com/FreeRADIUS/freeradius-server/files/9120839/patch.gz)

**Comment by alandekok** [comment]
You have the ability to edit the source and fix things.  How about doing that?
