### ISSUE TITLE
[defect]: Rocky linux free radius python module not supported

### ISSUE THREAD

**Issue by clintonwu2013** [FreeRADIUS/freeradius-server#4638]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

I am trying to install free radius with python(python2)  module on Rocky linux 8.5. 

I tried the following installation commands:
(1) yum -y install freeradius
(2) yum -y install freeradius-utils
(3) yum -y install freeradius-python

(1)(2) are good, but (3) shows the following error message on the console:
No match for argument: freeradius-python
Error: Unable to find a match: freeradius-python

Also when I key in the "radiusd -X" command for debugging. The console shows the following error message:
etc/raddb/mods-enabled/python[59]: Failed to link to module 'rlm_python': /usr/lib64/freeradius/rlm_python.so: cannot open shared object file: No such file or directory

I wonder if there is any possible way to use free radius with python(python2)  module on Rocky linux 8.5 ???

THANKS !!!!

### Log output from the FreeRADIUS daemon

```shell
/etc/raddb/mods-enabled/python[59]: Failed to link to module 'rlm_python': /usr/lib64/freeradius/rlm_python.so: cannot open shared object file: No such file or directory
```

**Comment by alandekok** [comment]
You don't say which package repository you're using.  If it's the main Rocky Linux one, then go ask them why they're not shipping a freeradius-python package.
