### ISSUE TITLE
[defect]: SQL-User-Name not available on first query in a unlang SQL/MySQL xlat

### ISSUE THREAD

**Issue by pamribeirox** [FreeRADIUS/freeradius-server#4702]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

In a stock Debian 11 install (3.0.25 or 3.2.0) enable SQL and tune the parameters for the MySQL/MariaDB server/DB used.

Uncomment some example from the "users" file: (example)
**lameuser        Auth-Type := Reject
                          Reply-Message = "Your account has been disabled."**

Add this lines (bold) in the beginning of the "authorize" section (just to show the problem)
...
authorize {
  **update control {
                        &Tmp-String-0 = "%{sql:SELECT '%{SQL-User-Name}' AS val}"
                        &Tmp-String-1 = "%{sql:SELECT '%{SQL-User-Name}' AS val}"
   }**
...

Run the server in debug mode and do a simple "radtest":

**radtest -t pap lameuser anypass 127.0.0.1 0 testing123**

### Log output from the FreeRADIUS daemon

```shell
The freeradius -X shows (relevant lines below only)
Behavior: The SQL-User-Name seems to be created in the first %{sql: ... } but is expanded to a null '' string on the query and copied to Tmp-String-0 (in the p.o.c. code)
In the second (and following) %{sql: ...} uses the correct expansion is done and Tmp-String-1 has the SQL-User-Name copied.

...
Ready to process requests
(0) Received Access-Request Id 65 from 127.0.0.1:53928 to 127.0.0.1:1812 length 78
(0)   User-Name = "lameuser"
(0)   User-Password = "nopass"
(0)   NAS-IP-Address = 127.0.1.1
(0)   NAS-Port = 0
(0)   Message-Authenticator = 0xfca03c1c853d861789ff20f5b9cd9cd5
(0) # Executing section authorize from file /etc/freeradius/sites-enabled/default
(0)   authorize {
(0)     update control {
(0)       EXPAND %{User-Name}
(0)          --> lameuser
(0)       SQL-User-Name set to 'lameuser'
rlm_sql (sql): Reserved connection (0)
(0)       Executing select query: SELECT '' AS val
rlm_sql (sql): Released connection (0)
Need more connections to reach 10 spares
rlm_sql (sql): Opening additional connection (5), 1 of 27 pending slots used
rlm_sql_mysql: Starting connect to MySQL server
rlm_sql_mysql: Connected to database 'radlocal' on db1.net.ipl.pt via TCP/IP, server version 10.5.16-MariaDB-1:10.5.16+maria~buster-log, protocol version 10
(0)       EXPAND %{sql:SELECT '%{SQL-User-Name}' AS val}
(0)          --> 
(0)       &Tmp-String-0 = 
rlm_sql (sql): Reserved connection (1)
rlm_sql (sql): Released connection (1)
(0)       EXPAND %{User-Name}
(0)          --> lameuser
(0)       SQL-User-Name set to 'lameuser'
rlm_sql (sql): Reserved connection (2)
(0)       Executing select query: SELECT 'lameuser' AS val
rlm_sql (sql): Released connection (2)
(0)       EXPAND %{sql:SELECT '%{SQL-User-Name}' AS val}
(0)          --> lameuser
(0)       &Tmp-String-1 = lameuser
(0)     } # update control = noop
(0)     policy filter_username {
...
```

### Relevant log output from client utilities

Not relevant for the problem.

**Comment by alandekok** [comment]
The `"%{sqllSELECT...}"` string is expanded _before_ the SQL module is called to run the `SELECT`.  So the `SQL-User-Name` attribute does not exist when the string is expanded.  The SQL module then creates the `SQL-User-Name` attribute before running the `SELECT` statement, but by then it doesn't matter.

What issue are you running into with this?  This is a toy example.

This will be difficult to fix "perfectly".  The short-term fix is to just run a minimal `SELECT` statement as in the first example, and then put the real SQL query into the second expansion.

**Comment by pamribeirox** [comment]
Thank you for the quick analysis and answer.

At our eduroam+VPNs RADIUS setup we have the need to fetch some extra 
information besides the basic provided by the common SQL schema.

Some examples:
	* Fetching the user password hashes in NTLM or CRYPT formats dependent 
on the auth protocol being used (no cleartext password available)
	* Deciding the wireless assigned VLAN ( Tunnel-Private-Group-ID ) in 
realtime using a sql query

For this and other %{sql: ...} uses, after the migration of our system 
from FreeRADIUS 2.x to 3.x some of this querys failed due to the 
SQL-User-Name not being expanded.

I've identified a possible solution that would be to use a SQL user 
defined variable with the SQL-User-Name, defined everytime the 
SQL-User-Name generation is done, with something like:
SET @SQL-User-Name = '<escaped_username>';

Then in the SQL querys we should be able to use the variable directly 
instead of the string expansion:

	Tunnel-Private-Group-ID:0 := "%{%{sql:SELECT 
***@***.***,'%{Huntgroup-Name}','%{Calling-Station-Id}') 
AS VLAN}:-1003}"

Regards.

**Comment by alandekok** [comment]
Thanks for the update.  For now, we can't really fix this in v3.
