### ISSUE TITLE
[defect]: Incorrect reference is used in /mods-config/sql/ippool-dhcp/mysql/queries.conf

### ISSUE THREAD

**Issue by drpacmanhu** [FreeRADIUS/freeradius-server#4720]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

Dear All,

I'm pretty new to freeradius and I wanted to start it with dhcp with sqlippool option. When I enabled the required modules I was keep getting error messages when I wanted to start the application. After 5days of debugging I think I've found the issue.

Error1: 
in the file /mods-config/sql/ippool-dhcp/mysql/queries.conf the pool_name variable is referenced as '%{control:${pool_name}}' but it cannot be resolved. Based on my experience it should be ${pool_name} or '&{control:pool_name}'

Also the same issue in mods-enabled/dhcp_sqlippool file at the bottom when  '%{control:${pool_name}}' used.

Error2:
If I do not uncomment pool_name variable in file mods-enabled/dhcp_sqlippool then I get the Error2 when starting the app

sqlippool dhcp_sqlippool {
        sql_module_instance = "sql"

        ippool_table = "radippool"
        # Name of the check item attribute to be used as a key in the SQL queries
        pool_name = "nas_pool_dhcp_sqlippool"

I checked it on on Ubuntu 22 [3.0.26] and Kinetic as Kinetic comes with 3.2.x freeradius and I wanted to get some help from the newer version but it had the same issue. Also check master on github - it is a bit different but still not good as it uses the reference '%{control.${pool_name}}' and leads to Error1.

If I'm wrong sorry to take your time...

### Log output from the FreeRADIUS daemon

```shell
freeradius - X
.
.
.
Error1:
/etc/freeradius/3.0/mods-config/sql/ippool-dhcp/mysql/queries.conf[59]: Reference "${pool_name}" not found

Error2:
  # Instantiating module "dhcp_sqlippool" from file /etc/freeradius/3.0/mods-enabled/dhcp_sqlippool
/etc/freeradius/3.0/mods-enabled/dhcp_sqlippool[15]: Unknown attribute 'pool_name = nas_pool_dhcp_sqlippool'
/etc/freeradius/3.0/mods-enabled/dhcp_sqlippool[15]: Instantiation failed for module "dhcp_sqlippool"
```

**Comment by alandekok** [comment]
Either you're using an old version of the server, or someone edited the configuration and broke it.  The 3.2.0 version has `${config:..pool_name}`, which is correct.

When you install a new version of the server, it does *not* over-write your existing configuration.  So if your configuration is broken, then a new install won't fix it.

The solution is to delete the incorrect configuration, and use the correct files from the 3.2.0 distribution.

**Comment by drpacmanhu** [comment]
Hello, 

Thanks for the quick reply! My fault that I did not mention that all test servers were installed before the command
sudo ap-get install freeradius freeradius-mysql freeradius-dhcp was executed.

But I'm happy that is fixed, looking forward to see it in the central repo.

Regards,
drpacmanhu
