### ISSUE TITLE
freeradius and active directory and mikrotik router for AAA

### ISSUE THREAD

**Issue by hshokri** [FreeRADIUS/freeradius-server#4744]
### Message

Hello every one
I am working on project to use **active directory** users with free radius and **Mikrotik** router to allow clients to limit and monitor access to the internet
the **authentication** part is complete now users can login and access the internet
now for limiting the bandwidth and weekly volume that each user is allowed we have some trouble
I wonder is there any way to use current active users that they can login to limit the bandwidth and weekly volume of the internet for each user? and if there is how can we do it.

(i have been search for the answer for over a week)

**Comment by jpereira** [comment]
questions belong to FreeRADIUS mailing list. https://wiki.freeradius.org/guide/Users-Mailing-List

**Comment by jpereira** [comment]
questions belong to FreeRADIUS mailing list. https://wiki.freeradius.org/guide/Users-Mailing-List
