### ISSUE TITLE
[defect]: openwrt freeradius sqlcouter

### ISSUE THREAD

**Issue by killerwake** [FreeRADIUS/freeradius-server#4749]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

openwrt
freeradius
sqlcouter

### Log output from the FreeRADIUS daemon

```shell
root@playland:~# radiusd -Xx
Wed Sep 28 21:53:11 2022 : Debug:    # Linked to sub-module rlm_eap_ttls
Wed Sep 28 21:53:11 2022 : Debug:    ttls {
Wed Sep 28 21:53:12 2022 : Debug:       tls = "tls-common"
Wed Sep 28 21:53:12 2022 : Debug:       default_eap_type = "md5"
Wed Sep 28 21:53:12 2022 : Debug:       copy_request_to_tunnel = no
Wed Sep 28 21:53:12 2022 : Debug:       use_tunneled_reply = no
Wed Sep 28 21:53:12 2022 : Debug:       virtual_server = "inner-tunnel"
Wed Sep 28 21:53:12 2022 : Debug:       include_length = yes
Wed Sep 28 21:53:12 2022 : Debug:       require_client_cert = no
Wed Sep 28 21:53:12 2022 : Debug:    }
Wed Sep 28 21:53:12 2022 : Debug: tls: Using cached TLS configuration from previous invocation
Wed Sep 28 21:53:12 2022 : Debug:    # Linked to sub-module rlm_eap_peap
Wed Sep 28 21:53:12 2022 : Debug:    peap {
Wed Sep 28 21:53:12 2022 : Debug:       tls = "tls-common"
Wed Sep 28 21:53:12 2022 : Debug:       default_eap_type = "mschapv2"
Wed Sep 28 21:53:12 2022 : Debug:       copy_request_to_tunnel = no
Wed Sep 28 21:53:12 2022 : Debug:       use_tunneled_reply = no
Wed Sep 28 21:53:12 2022 : Debug:       proxy_tunneled_request_as_eap = yes
Wed Sep 28 21:53:12 2022 : Debug:       virtual_server = "inner-tunnel"
Wed Sep 28 21:53:12 2022 : Debug:       soh = no
Wed Sep 28 21:53:12 2022 : Debug:       require_client_cert = no
Wed Sep 28 21:53:12 2022 : Debug:    }
Wed Sep 28 21:53:12 2022 : Debug: tls: Using cached TLS configuration from previous invocation
Wed Sep 28 21:53:12 2022 : Debug:   # Instantiating module "pap" from file /etc/freeradius3/mods-enabled/pap
Wed Sep 28 21:53:12 2022 : Debug:   # Instantiating module "mschap" from file /etc/freeradius3/mods-enabled/mschap
Wed Sep 28 21:53:12 2022 : Debug: rlm_mschap (mschap): using internal authentication
Wed Sep 28 21:53:12 2022 : Error: /etc/freeradius3/mods-config/sql/main/sqlite/queries.conf[348]: Failed parsing expanded string:
Wed Sep 28 21:53:12 2022 : Error: /etc/freeradius3/mods-config/sql/main/sqlite/queries.conf[348]: ...otocol}', '%{Framed-IP-Address}', '%{Framed-IPv6-Address}', '%{Framed-IPv6-Prefix}', '%{Fram...
Wed Sep 28 21:53:12 2022 : Error: /etc/freeradius3/mods-config/sql/main/sqlite/queries.conf[348]:                                         ^ Unknown attribute
```

**Comment by alandekok** [comment]
Are you using 3.0.26 or 3.2.0?

Did you edit the dictionaries?

The `Framed-IPv6-Address` attribute is defined in the default dictionaries.  The default configuration works.  We run tests on it multiple times a day.

So... what did you do?  What changes did you make to the default installation?

**Comment by killerwake** [comment]
I made this installation until the end: https://openwrt.org/docs/guide-user/network/wifi/freeradius

freeradius-server 3.0.21

`Wed Sep 28 22:18:51 2022 : Debug: Server was built with:
Wed Sep 28 22:18:51 2022 : Debug:   accounting               : yes
Wed Sep 28 22:18:51 2022 : Debug:   authentication           : yes
Wed Sep 28 22:18:51 2022 : Debug:   ascend-binary-attributes : yes
Wed Sep 28 22:18:51 2022 : Debug:   coa                      : yes
Wed Sep 28 22:18:51 2022 : Debug:   control-socket           : yes
Wed Sep 28 22:18:51 2022 : Debug:   detail                   : yes
Wed Sep 28 22:18:51 2022 : Debug:   dhcp                     : yes
Wed Sep 28 22:18:51 2022 : Debug:   dynamic-clients          : yes
Wed Sep 28 22:18:51 2022 : Debug:   osfc2                    : no
Wed Sep 28 22:18:51 2022 : Debug:   proxy                    : yes
Wed Sep 28 22:18:51 2022 : Debug:   regex-pcre               : yes
Wed Sep 28 22:18:51 2022 : Debug:   regex-posix              : no
Wed Sep 28 22:18:51 2022 : Debug:   regex-posix-extended     : no
Wed Sep 28 22:18:51 2022 : Debug:   session-management       : yes
Wed Sep 28 22:18:51 2022 : Debug:   stats                    : yes
Wed Sep 28 22:18:51 2022 : Debug:   systemd                  : no
Wed Sep 28 22:18:51 2022 : Debug:   tcp                      : yes
Wed Sep 28 22:18:51 2022 : Debug:   threads                  : yes
Wed Sep 28 22:18:51 2022 : Debug:   tls                      : yes
Wed Sep 28 22:18:51 2022 : Debug:   unlang                   : yes
Wed Sep 28 22:18:51 2022 : Debug:   vmps                     : yes
Wed Sep 28 22:18:51 2022 : Debug:   developer                : no
Wed Sep 28 22:18:51 2022 : Debug: Server core libs:
Wed Sep 28 22:18:51 2022 : Debug:   freeradius-server        : 3.0.21
Wed Sep 28 22:18:51 2022 : Debug:   talloc                   : 2.3.*
Wed Sep 28 22:18:51 2022 : Debug:   ssl                      : 1.1.1q release
Wed Sep 28 22:18:51 2022 : Debug:   pcre                     : 8.45 2021-06-15
Wed Sep 28 22:18:51 2022 : Debug: Endianness:
Wed Sep 28 22:18:51 2022 : Debug:   big
Wed Sep 28 22:18:51 2022 : Debug: Compilation flags:
Wed Sep 28 22:18:51 2022 : Debug:   cppflags : -isystem /builder/shared-workdir/build/sdk/staging_dir/target-mips_24kc_musl/usr/include/ -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/usr/include -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/include/fortify -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/include
Wed Sep 28 22:18:51 2022 : Debug:   cflags   : -I. -Isrc -include src/freeradius-devel/autoconf.h -include src/freeradius-devel/build.h -include src/freeradius-devel/features.h -include src/freeradius-devel/radpaths.h -fno-strict-aliasing -Wno-date-time -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-mips_24kc_musl/freeradius-server-release_3_0_21=freeradius-server-release_3_0_21 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DHAVE_OPENSSL_RAND_H -Wall -std=c99 -D_GNU_SOURCE -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -DOPENSSL_NO_KRB5 -DNDEBUG -DIS_MODULE=1
Wed Sep 28 22:18:51 2022 : Debug:   ldflags  :  -L/builder/shared-workdir/build/sdk/staging_dir/target-mips_24kc_musl/usr/lib -Wl,-rpath,/builder/shared-workdir/build/sdk/staging_dir/target-mips_24kc_musl/usr/lib -L/builder/shared-workdir/build/sdk/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/usr/lib -L/builder/shared-workdir/build/sdk/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/lib -znow -zrelro
Wed Sep 28 22:18:51 2022 : Debug:   libs     : -lcrypto -lssl -ltalloc -lpcre -lcap -lresolv -ldl -lpthread -latomic -lcrypto -lssl -lcrypto -lssl -lcrypto -lssl -lcrypto -lssl -lreadline
Wed Sep 28 22:18:51 2022 : Debug:
`

**Comment by alandekok** [comment]
Please use 3.0.26.  It is very likely that this issue has already been fixed.

a `git diff` shows many changes.

```
git diff release_3_0_21 raddb/mods-config/sql/main/sqlite/queries.conf
```

This issue does not appear in the version of FreeRADIUS we distribute.  So either it's due to using an older version, or it's due to OpenWRT changing things.

Either way, the fix is to upgrade to 3.0.26.  It's not useful for us to track down and debug issues which were already found and fixed many years ago.

You should be able to use the `queries.conf` file from 3.0.26 in your current installation.  Just using that may fix the issue.

**Comment by killerwake** [comment]
it worked! Thank you!

Wed Sep 28 23:00:14 2022 : Warning: /etc/freeradius3/sites-enabled/inner-tunnel[297]: Please change attribute reference to '&User-Name := ...'

Do you know why this happens?

**Comment by alandekok** [comment]
Change the attribute reference from `User-Name` to `&User-Name`?  That's what the message says.
