### ISSUE TITLE
[defect]:  doc.freeradius.org reports Nginx error  500 Internal Server Error

### ISSUE THREAD

**Issue by bneyjr** [FreeRADIUS/freeradius-server#4776]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

try to open any web page on the documentation server

### Log output from the FreeRADIUS daemon

```shell
500 Internal Server Error
```

**Comment by mcnewton** [comment]
Fixed, thanks.
