### ISSUE TITLE
[defect]: cbtls_verify treat intermediate CA as client cert by mistake

### ISSUE THREAD

**Issue by zhangyoufu** [FreeRADIUS/freeradius-server#4785]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

For my typical EAP-TLS setup (using official Docker image), with FreeRADIUS 3.2.X, my unlang policy referencing `TLS-Client-Cert-Common-Name` got intermediate CA attributes instead of leaf certificate from client. While FreeRADIUS 3.0.26 is working fine.

### Log output from the FreeRADIUS daemon

```shell
(0) eap_tls: (TLS) EAP Got final fragment (618 bytes)
(0) eap_tls: (TLS) EAP Done initial handshake
(0) eap_tls: (TLS) Handshake state - Server SSLv3/TLS write server done
(0) eap_tls: (TLS) recv TLS 1.2 Handshake, Certificate
(0) eap_tls: (TLS) Creating attributes from TLS-Client-Cert-Serial certificate
(0) eap_tls: (TLS) Creating attributes from client certificate
(0) eap_tls:   TLS-Client-Cert-Serial := "1000"
(0) eap_tls:   TLS-Client-Cert-Expiration := "260720000000Z"
(0) eap_tls:   TLS-Client-Cert-Valid-Since := "160720000000Z"
(0) eap_tls:   TLS-Client-Cert-Subject := "/CN=Example Intermediate CA"
(0) eap_tls:   TLS-Client-Cert-Issuer := "/CN=Example Root CA"
(0) eap_tls:   TLS-Client-Cert-Common-Name := "Example Intermediate CA"
(0) eap_tls:   TLS-Client-Cert-X509v3-Subject-Key-Identifier += "22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22"
(0) eap_tls:   TLS-Client-Cert-X509v3-Authority-Key-Identifier += "keyid:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11:11\n"
(0) eap_tls:   TLS-Client-Cert-X509v3-Basic-Constraints += "CA:TRUE, pathlen:0"
(0) eap_tls: (TLS) Creating attributes from client certificate
(0) eap_tls:   TLS-Client-Cert-Serial := "0123456789abcdef0123456789abcdef01234567"
(0) eap_tls:   TLS-Client-Cert-Expiration := "230810000000Z"
(0) eap_tls:   TLS-Client-Cert-Valid-Since := "220810000000Z"
(0) eap_tls:   TLS-Client-Cert-Subject := "/CN=user@example.com"
(0) eap_tls:   TLS-Client-Cert-Issuer := "CN=Example Intermediate CA"
(0) eap_tls:   TLS-Client-Cert-Common-Name := "user@example.com"
(0) eap_tls:   TLS-Client-Cert-X509v3-Extended-Key-Usage += "TLS Web Client Authentication"
(0) eap_tls:   TLS-Client-Cert-X509v3-Basic-Constraints += "CA:FALSE"
(0) eap_tls:   TLS-Client-Cert-X509v3-Subject-Key-Identifier += "33:33:33:33:33:33:33:33:33:33:33:33:33:33:33:33:33:33:33:33"
(0) eap_tls:   TLS-Client-Cert-X509v3-Authority-Key-Identifier += "keyid:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22:22\n"
(0) eap_tls:   TLS-Client-Cert-X509v3-Extended-Key-Usage-OID += "1.3.6.1.5.5.7.3.2"
```

**Comment by zhangyoufu** [comment]
introduced in commit 3d46024acba525086e44c271379eaa706c4b08ea

`FR_TLS_EX_INDEX_FIX_CERT_ORDER` is never set on inbound session, `lookup` was set to 0 for `depth` 0/1.

**Comment by zhangyoufu** [comment]
@alandekok PTAL, thanks.

**Comment by alandekok** [comment]
The checks for `FR_TLS_EX_INDEX_FIX_CERT_ORDER` are only done when `lookup==0`.

So the checks can't set change a `1` value to a `0`, value.  They can only change a `0` value to a `1` value.  And then only for outbound connections, when the `fix_cert_order` configuration flag is set.

For inbound connections, the checks are exactly the same as before:

Old: `if ((lookup > 1) && !my_ok) lookup = 1;`  Which doesn't change `0` values, and only changes `>1` to `1` in some cases.

New:

```
	if (lookup > 1) {
		if (!my_ok) lookup = 1;
	} else {
		lookup = (SSL_get_ex_data(ssl, FR_TLS_EX_INDEX_FIX_CERT_ORDER) != NULL);
	}
```

Which only changes `>1` to `1` in some cases (the same as before), and changes `0` to `1` _only_ if the `fix_cert_order` flag is set.

So I'm not sure what your comment means.

**Comment by zhangyoufu** [comment]
The new code changes `lookup == 1` to `0` in the `else` branch for inbound connections, while old code doesn't.
