### ISSUE TITLE
[defect]: Potential memory leak in src/listen/ldap_sync/proto_ldap_sync_ldap.c

### ISSUE THREAD

**Issue by icy17** [FreeRADIUS/freeradius-server#4864]
### What type of defect/bug is this?

incorrect 3rd party API usage

### How can the issue be reproduced?

Potential memory leak in [proto_ldap_sync_ldap.c](https://github.com/FreeRADIUS/freeradius-server/blob/master/src/listen/ldap_sync/proto_ldap_sync_ldap.c#L626) line 626. Calling ldap_result() without calling ldap_msgfree() to free the memory will cause a memory leak. [Doc](https://linux.die.net/man/3/ldap_result) says "The ldap_msgfree() routine is used to free the memory allocated for result(s) by ldap_result() or [ldap_search_ext_s](https://linux.die.net/man/3/ldap_search_ext_s)(3) and friends."
![image](https://user-images.githubusercontent.com/39425646/214830792-c03387dc-d873-4a1f-9df2-96d7fdd2b81e.png)

### Log output from the FreeRADIUS daemon

```shell
None
```

**Comment by ndptech** [comment]
If `ldap_result()` returns 0 or -1 then it has not returned an LDAPMessage to free.

There were two unlikely error paths in the callbacks used for RFC4533 servers which were not freeing the LDAPMessage which I will fix
