### ISSUE TITLE
READ THE MESSAGE BELOW BEFORE SUBMITTING AN ISSUE

### ISSUE THREAD

**Issue by Abelito-A** [FreeRADIUS/freeradius-server#4889]
### Message

I have details with the users, it allows several connections changing only one letter, example: created user: abcd, allows the connection for Abcd, aBcd, abCd, abcD, ABCD and more. I use mikrotik, I have "Simultaneous-Use" configured with a value of 1 but it continues to allow connections by changing only one letter.

**Comment by mcnewton** [comment]
Questions belong on the freeradius-users mailing list.
