### ISSUE TITLE
Freeradius with MikroTik

### ISSUE THREAD

**Issue by Abelito-A** [FreeRADIUS/freeradius-server#4891]
### Message

I have details with the users, it allows several connections changing only one letter, example: created user: abcd, allows the connection for Abcd, aBcd, abCd, abcD, ABCD and more. I use mikrotik, I have "Simultaneous-Use" configured with a value of 1 but it continues to allow connections by changing only one letter.

**Comment by mcnewton** [comment]
You already opened another issue with the same message, and were told this is not the appropriate place for questions. This is not a bug. If you don't understand how the server works, you should ask on the freeradius-users mailing list.
