### ISSUE TITLE
freeradius unknown attribute error with EAP-AKA

### ISSUE THREAD

**Issue by subhajit-cdot** [FreeRADIUS/freeradius-server#4932]
I was trying to configure EAP-AKA in freeradius server (radiusd version 4.0, compiled using master branch ) to test with strongswan. However, radius daemon is not getting started and showing unknown attribute error.

**Entry in /usr/local/etc/raddb/users**

 `0262073961704408 EAP-Type := AKA, EAP-Sim-AUTN := 0x30000000000000000000000000000000, EAP-Aka-IK := 0x33333333333333333333333333333333, EAP-Aka-CK := 0x34343434343434343434343434343434, EAP-Sim-RES := 0x35353535353535353535353535353535, EAP-Sim-RAND := 0x30000000000000000000000000000000`

**Logs attached:-**

```
Thu Mar 16 09:41:30 2023: Debug : Compiling policies in - send Access-Accept {...}
    Thu Mar 16 09:41:30 2023: Warn  : /usr/local/etc/raddb/sites-enabled/inner-tunnel[267]: Ignoring "-sql" as the "sql" module is not enabled.
    Thu Mar 16 09:41:30 2023: Debug : Compiling policies in - send Access-Reject {...}
    Thu Mar 16 09:41:30 2023: Warn  : /usr/local/etc/raddb/sites-enabled/inner-tunnel[302]: Ignoring "-sql" as the "sql" module is not enabled.
    Thu Mar 16 09:41:30 2023: Debug : Compiling policies in - authenticate pap {...}
    Thu Mar 16 09:41:30 2023: Debug : Compiling policies in - authenticate chap {...}
    Thu Mar 16 09:41:30 2023: Debug : Compiling policies in - authenticate mschap {...}
    Thu Mar 16 09:41:30 2023: Debug : Compiling policies in - authenticate eap {...}
    Thu Mar 16 09:41:30 2023: Warn  : radius  { ... } section is unused
    Thu Mar 16 09:41:30 2023: Debug : #### Instantiating rlm modules ####
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_attr_filter "attr_filter.access_challenge"
    Thu Mar 16 09:41:30 2023: Debug : Reading file /usr/local/etc/raddb/mods-config/attr_filter/access_challenge
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_attr_filter "attr_filter.access_reject"
    Thu Mar 16 09:41:30 2023: Debug : Reading file /usr/local/etc/raddb/mods-config/attr_filter/access_reject
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_attr_filter "attr_filter.accounting_response"
    Thu Mar 16 09:41:30 2023: Debug : Reading file /usr/local/etc/raddb/mods-config/attr_filter/accounting_response
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_attr_filter "attr_filter.post-proxy"
    Thu Mar 16 09:41:30 2023: Debug : Reading file /usr/local/etc/raddb/mods-config/attr_filter/post-proxy
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_attr_filter "attr_filter.pre-proxy"
    Thu Mar 16 09:41:30 2023: Debug : Reading file /usr/local/etc/raddb/mods-config/attr_filter/pre-proxy
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_detail "auth_log"
    Thu Mar 16 09:41:30 2023: Debug : auth_log - 'User-Password' suppressed, will not appear in detail output
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_cache "cache_eap"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_chap "chap"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_detail "detail"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_digest "digest"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_always "disallow"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_eap "eap"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_exec "echo"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_passwd "etc_passwd"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_exec "exec"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_always "fail"
    Thu Mar 16 09:41:30 2023: Debug : Instantiating rlm_files "files"
    Thu Mar 16 09:41:30 2023: Debug : Reading file /usr/local/etc/raddb/mods-config/files/authorize
    Thu Mar 16 09:41:30 2023: Error : /usr/local/etc/raddb/mods-config/files/authorize[1]: Unknown attribute 'EAP-Sim-AUTN'
    Thu Mar 16 09:41:30 2023: Error : Failed reading /usr/local/etc/raddb/mods-config/files/authorize
    Thu Mar 16 09:41:30 2023: Error : /usr/local/etc/raddb/mods-enabled/files[18]:
```
Please guide how to enable EAP-AKA and provide quintuplets in radiusd.

Regards,
Subhajit

**Comment by subhajitchatu** [comment]
Hi alandekok,
I have checked the dictionary files related to EAP-AKA but didn't find attributes CK,IK,XRES etc. These quintuplets need to be provided as per **sites-available/eap-aka-sim**. I tried with some attributes from **share/dictionary/eap/aka-sim/dictionary.rfc4187** like AUTN, RAND etc but same **unknown attribute error** is coming. While running EAP-SIM, I gave the below attributes in users file, although these attributes are not mentioned in the dictionary files but **it is working fine**.

`228060123456001 EAP-Type := SIM, EAP-SIM-RAND1 := 0x30000000000000000000000000000000, EAP-SIM-SRES1 := 0x30112233, EAP-SIM-KC1 := 0x305566778899AABB, EAP-SIM-RAND2 := 0x31000000000000000000000000000000, EAP-SIM-SRES2 := 0x31112233, EAP-SIM-KC2 := 0x315566778899AABB, EAP-SIM-RAND3 := 0x32000000000000000000000000000000, EAP-SIM-SRES3 := 0x32112233, EAP-SIM-KC3 := 0x325566778899AABB`

Is there any example or configuration files available related to EAP-AKA/EAP-AKA' attributes?  Please guide.
Thanks
Subhajit

**Comment by alandekok** [comment]
`grep -ir xres share/dictionary`

It's there if you bother to look for it.

But realistically, v4 isn't released.  If it works, great.  If it doesn't work. please supply either a code patch or documentation updates.

**Comment by subhajitchatu** [comment]
I have tested eap-sim and eap-aka successfully using your pointers. Thanks
for the support!

**Comment by Nawzadalsalo** [comment]
hello, can tell me how u are maked
