### ISSUE TITLE
READ THE MESSAGE BELOW BEFORE SUBMITTING AN ISSUE

### ISSUE THREAD

**Issue by nickabocker171** [FreeRADIUS/freeradius-server#4939]
### Message

I was recently testing freeradius with daloRadius and ran into an issue where the device i was using was trying to utilize tls 1.3 I decided to upgrade from 3.0.2 to 3.2.2 with a really basic config but when. i try to start the process now I get 

```
Unable to check file "/etc/freeradius/certs/server.pem": No such file or directory
/etc/freeradius/mods-enabled/eap[177]: Failed parsing configuration item "private_key_file"
rlm_eap_tls: Failed initializing SSL context
rlm_eap (EAP): Failed to initialise rlm_eap_tls
/etc/freeradius/mods-enabled/eap[14]: Instantiation failed for module "eap"
```

I can't seem to figure out where i need to update the config to work properly.

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.

I really don't see how those error messages could be any clearer.   They tell you which file the server is trying to load.  They tell you which configuration file and line number is causing the error.
