### ISSUE TITLE
[defect]: Some modules not compiling on deb build -  rlm_smsotp.so missing

### ISSUE THREAD

**Issue by LeadManPL** [FreeRADIUS/freeradius-server#4955]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

Download source and follow [instructions to build packages](https://wiki.freeradius.org/building/Debian-and-Ubuntu#building-the-stable-release-v3-0_building-packages) 

Building process ends with generating proper Debian packages, but after installing it witk "dpkg -i"  module rlm_smsotp is NOT available in /usr/lib/freeradius

According to docs: "On recent releases you should ensure the source tree is completely clean before running make deb, **e.g. do not run ./configure first.**"

How can I force FreeRadius co configure and build rlm_smsotp.so?

### Log output from the FreeRADIUS daemon

```shell
# journalctl -xe
[...]
Identyfikator zadania: 76020.
kwi 03 18:50:48 frad freeradius[66496]: FreeRADIUS Version 3.0.21
kwi 03 18:50:48 frad freeradius[66496]: Copyright (C) 1999-2019 The FreeRADIUS server project and contributors
kwi 03 18:50:48 frad freeradius[66496]: There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
kwi 03 18:50:48 frad freeradius[66496]: PARTICULAR PURPOSE
kwi 03 18:50:48 frad freeradius[66496]: You may redistribute copies of FreeRADIUS under the terms of the
kwi 03 18:50:48 frad freeradius[66496]: GNU General Public License
kwi 03 18:50:48 frad freeradius[66496]: For more information about these matters, see the file named COPYRIGHT
kwi 03 18:50:48 frad freeradius[66496]: Starting - reading configuration files ...
kwi 03 18:50:48 frad freeradius[66496]: Debug state unknown (cap_sys_ptrace capability not set)
kwi 03 18:50:48 frad freeradius[66496]: Creating attribute Unix-Group
kwi 03 18:50:48 frad freeradius[66496]: /etc/freeradius/3.0/mods-enabled/smsotp[39]: Failed to link to module 'rlm_smsotp': /usr/lib/freeradius/rlm_smsotp.so: cannot open shared object file: No such file or directory
kwi 03 18:50:48 frad systemd[1]: freeradius.service: Control process exited, code=exited, status=1/FAILURE
```

**Comment by alandekok** [comment]
You need to use ` --with-experimental-modules` to build the `smsotp` module from source.  As the module is not widely used, it's not build as part of the debian packages.

i.e. even if you did build the module, it needs the `smsotpd` utility.  That software is not part of FreeRADIUS, and it seems to have mostly disappeared from the net.

**Comment by LeadManPL** [comment]
Hi @alandekok,

thanks for pointing that out, and for quick response. I did some research and found that there is `./debian/rules` file in sources, containing ./configure section, so I just added `--with-experimental-modules` at the end of section and it compiled rlm_smsotp.so :)

In `freeradius -X` debug mode i see 
`Compiling Auth-Type smsotp for attr Auth-Type`
`Compiling Auth-Type smsotp-reply for attr Auth-Type`
but unfortunately socket file is not created in /run ....

Regarding smsotpd I am aware of that. I know it is ancient (~10 years old) but its [here](http://thomas.glanzmann.de/smsotpd.2012-10-05.tar.bz2), together with manuals at [bottom of page](https://wiki.freeradius.org/modules/Rlm_smsotp) if someone struggles to find it. Don't know if it works yet, but anyways its a good starting point to write something on your own

For smsotpd, on Debian 11 you need to additionally install:
`apt install libterm-readpassword-perl libauthen-radius-perl`
