### ISSUE TITLE
Can not start or restart freeradius-server

### ISSUE THREAD

**Issue by ken74114** [FreeRADIUS/freeradius-server#4964]
### Message

 4月 06 15:39:32 google-auth systemd[1]: Stopped FreeRADIUS multi-protocol policy server.
 4月 06 15:39:32 google-auth systemd[1]: Starting FreeRADIUS multi-protocol policy server...
 4月 06 15:39:32 google-auth freeradius[16328]: FreeRADIUS Version 3.0.26
 4月 06 15:39:32 google-auth freeradius[16328]: Copyright (C) 1999-2021 The FreeRADIUS server project and contributors
 4月 06 15:39:32 google-auth freeradius[16328]: There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
 4月 06 15:39:32 google-auth freeradius[16328]: PARTICULAR PURPOSE
 4月 06 15:39:32 google-auth freeradius[16328]: You may redistribute copies of FreeRADIUS under the terms of the
 4月 06 15:39:32 google-auth freeradius[16328]: GNU General Public License
 4月 06 15:39:32 google-auth freeradius[16328]: For more information about these matters, see the file named COPYRIGHT
 4月 06 15:39:32 google-auth freeradius[16328]: Starting - reading configuration files ...
 4月 06 15:39:32 google-auth freeradius[16328]: Debug state unknown (cap_sys_ptrace capability not set)
 4月 06 15:39:32 google-auth freeradius[16328]: Creating attribute Unix-Group
 4月 06 15:39:32 google-auth freeradius[16328]: rlm_detail (auth_log): 'User-Password' suppressed, will not appear in detail output
 4月 06 15:39:32 google-auth freeradius[16328]: rlm_mschap (mschap): using internal authentication
 4月 06 15:39:32 google-auth freeradius[16328]: tls: Using cached TLS configuration from previous invocation
 4月 06 15:39:32 google-auth freeradius[16328]: tls: Using cached TLS configuration from previous invocation
 4月 06 15:39:32 google-auth freeradius[16328]: rlm_cache (cache_eap): Driver rlm_cache_rbtree (module rlm_cache_rbtree) loaded and linked
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Auth-Type PAP for attr Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Auth-Type CHAP for attr Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Auth-Type MS-CHAP for attr Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Ignoring "sql" (see raddb/mods-available/README.rst)
 4月 06 15:39:32 google-auth freeradius[16328]: Ignoring "ldap" (see raddb/mods-available/README.rst)
 4月 06 15:39:32 google-auth freeradius[16328]:  # Skipping contents of 'if' as it is always 'false' -- /etc/freeradius/3.0/sites-enabled/inner-tunnel:336
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Post-Auth-Type REJECT for attr Post-Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Auth-Type PAP for attr Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Auth-Type CHAP for attr Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Auth-Type MS-CHAP for attr Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Autz-Type New-TLS-Connection for attr Autz-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Post-Auth-Type REJECT for attr Post-Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Post-Auth-Type Challenge for attr Post-Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: Compiling Post-Auth-Type Client-Lost for attr Post-Auth-Type
 4月 06 15:39:32 google-auth freeradius[16328]: radiusd: #### Skipping IP addresses and Ports ####
 4月 06 15:39:32 google-auth freeradius[16328]: Configuration appears to be OK
 4月 06 15:39:33 google-auth systemd[1]: freeradius.service: Main process exited, code=exited, status=1/FAILURE
 4月 06 15:39:33 google-auth systemd[1]: freeradius.service: Failed with result 'exit-code'.
 4月 06 15:39:33 google-auth systemd[1]: Failed to start FreeRADIUS multi-protocol policy server.
 4月 06 15:39:33 google-auth systemd[1]: freeradius.service: Consumed 1.061s CPU time.

**Comment by jpereira** [comment]
Questions belongs to the users mailing list.
