### ISSUE TITLE
READ THE MESSAGE BELOW BEFORE SUBMITTING AN ISSUE

### ISSUE THREAD

**Issue by hs-abhijeet-gurav** [FreeRADIUS/freeradius-server#4965]
### Message

I am unable to authenticate with the help of
![WhatsApp Image 2023-04-06 at 7 54 46 PM](https://user-images.githubusercontent.com/104225326/230415596-d5d15513-bc49-4b28-bbb0-ed177dbad75d.jpeg)
 Google
<img width="1440" alt="Screenshot 2023-04-06 at 8 06 47 PM" src="https://user-images.githubusercontent.com/104225326/230415424-5c5397c6-1550-4639-8d30-5ba155fa7e32.png">
 LDAP. I have configured Free Radius on Ubuntu Machine

**Comment by jpereira** [comment]
Questions belong to the user's mailing list. https://wiki.freeradius.org/project/Mailing-list
