### ISSUE TITLE
freeradius 3.x.x (+Daloradius) vs some AD groups

### ISSUE THREAD

**Issue by Alexix84** [FreeRADIUS/freeradius-server#4975]
### Message

Hello!
Freeradius 3.x.x does not use the old ldap module. The system ntlm_auth is used instead

The question arose about filtering users by domain groups. In the "mschap" file, you can put only one filter "ntlm_auth –require-membership-of" and it works perfectly. But what if you need to filter several groups? The "mschap" file does not imply logic, and when trying to add an if/else comparison, it gives an error that this file should not contain "if".
In the /sites-enabled/defaults file, also do not add 2 modules "mschap1" "mschap2", reports that the double "mschap". Adding mschap2 to /mods-enabled/ also does not lead to success, swears at /usr/lib/freeradius/mschap2.so (I created it, but it does not help)

How to filter AD groups now?

**Comment by alandekok** [comment]
Questions belong on the mailing list
