### ISSUE TITLE
[defect]: make install fails on master

### ISSUE THREAD

**Issue by mcr** [FreeRADIUS/freeradius-server#4977]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

```
git clone ...
./configure
make 
sudo make install
```

It looks like there is a missing / on when $top_builddir has been canonicalized.
(I notice that it must use the SHELL $PWD, because it does not notice when there is a symlink in the path to the source, so it never called /bin/pwd )

### Log output from the FreeRADIUS daemon

```shell
devuan:


riemann-[/home/src/freeradius-server] mcr 107 %sudo make install
scripts/boiler.mk:730: home/src/freeradius-server/doc/all.mk: No such file or directory
make: *** No rule to make target 'home/src/freeradius-server/doc/all.mk'.  Stop.
[1]    10691 exit 2     sudo make install
```

ubuntu22.04:
```
dooku-[projects/trentonio/freeradius-server](2.6.6) mcr 6583 %sudo make install
[sudo] password for mcr: 
scripts/boiler.mk:730: corp/projects/trentonio/freeradius-server/doc/all.mk: No such file or directory
make: *** No rule to make target 'corp/projects/trentonio/freeradius-server/doc/all.mk'.  Stop.
```
```


### Relevant log output from client utilities

_No response_

### Backtrace from LLDB or GDB

_No response_

**Comment by mcr** [comment]
Stupid work around:

```
mkdir home
cd home
ln -s . src
ln -s /home/src/freeradius-server freeradius-server 
```

**Comment by alandekok** [comment]
What is the local directory structure which has this issue?

The CI tests do these builds on every commit, so they should work.  But those tests all build from normal directories, and not from ones where the source is symlinked in from elsewhere.

**Comment by mcr** [comment]
I started with a git clone in /usr/local/src, which was too small, so I did mkdir /home/src, ln -s /home/src /usr/local/src.
But my shell had $PWD set to /usr/local/src/freeradius-server, and that's why I think that whatever is canoncalizing cwd, isn't using /bin/pwd, but rather depending upon a shell variable to tell it stuff.  That's totally irrelevant.
I cd /home/src/freeradius-server, and try again, which I showed above, and the make install fails.

This was on devuan with ZSH as a shell. I also tried on two ubuntu machines (20.04 and 22.04) with ZSH, and the same result, and I could try with BASH if you prefer.

**Comment by alandekok** [comment]
Yeah, `scripts/boiler.mk` uses `$(PWD)`.  So if that's not set to the current directory, I guess things can go wrong.

The issue is likely 

```
define CANONICAL_PATH
$(patsubst $(PWD)/%,%,$(patsubst ${CURDIR}/%,%,$(abspath ${1})))
endef
```

perhaps if `$(PWD)` isn't set, the resulting makefile rule is stripping the first `/` from the directory.

**Comment by mcr** [comment]
Probably should be calling $(shell /bin/pwd)

**Comment by mcr** [comment]
Yes, it's some dependancy upon bash:

```
riemann-[/home/src/freeradius-server] mcr 140 %sudo -s 
[sudo] password for mcr: 
riemann# pwd
/home/src/freeradius-server
riemann# echo $SHELL
/bin/zsh
riemann# exec bash
root@riemann:/home/src/freeradius-server# mv home h
root@riemann:/home/src/freeradius-server# make install
INSTALL -d -m 755 /usr/local/lib
INSTALL -d -m 755 /usr/local/bin
INSTALL -d -m 755 /usr/local/sbin
root@riemann:/home/src/freeradius-server# 
```

**Comment by mcr** [comment]
```
riemann-[/home/src/freeradius-server] mcr 141 %git pull
   f63e7df7af..3c34351405  master     -> origin/master
 scripts/boiler.mk                     |  2 +-

riemann-[/home/src/freeradius-server] mcr 143 %sudo make install
INSTALL -d -m 755 /usr/local/lib
CC src/lib/server/auth.c
CC src/lib/server/state.c
CC src/lib/server/virtual_servers.c
```

and you seem to have fixed it.
