### ISSUE TITLE
read_group=yes but radgroupreply doesnot work

### ISSUE THREAD

**Issue by krajdyal** [FreeRADIUS/freeradius-server#499]
sql {
        driver = "rlm_sql_mysql"
        server = "localhost"
        port = "3306"
        login = "root"
        password = "XYZXYZXYZ"
        radius_db = "radius"
        read_groups = yes
        read_clients = yes
        delete_stale_sessions = yes
        sql_user_name = "%{User-Name}"
        default_user_profile = "DEFAULT"
        client_query = "SELECT id, nasname, shortname, type, secret, server FROM nas"
        authorize_check_query = "SELECT id, username, attribute, value, op FROM radcheck WHERE username = '%{SQL-User-Name}' ORDER BY id"
        authorize_reply_query = "SELECT id, username, attribute, value, op FROM radreply WHERE username = '%{SQL-User-Name}' ORDER BY id"
        authorize_group_check_query = "SELECT id, groupname, attribute, Value, op FROM radgroupcheck WHERE groupname = '%{Sql-Group}' ORDER BY id"
        authorize_group_reply_query = "SELECT id, groupname, attribute, value, op FROM radgroupreply WHERE groupname = '%{Sql-Group}' ORDER BY id"
        group_membership_query = "SELECT groupname FROM radusergroup WHERE username = '%{SQL-User-Name}' ORDER BY priority"
        simul_count_query = "SELECT COUNT(*) FROM radacct WHERE username = '%{SQL-User-Name}' AND acctstoptime IS NULL"
        simul_verify_query = "SELECT radacctid, acctsessionid, username, nasipaddress, nasportid, framedipaddress, callingstationid, framedprotocol FROM radacct WHERE username = '%{SQL-User-Name}' AND acctstoptime IS NULL"
        safe_characters = "@abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-_: /"
  }

---

(0) sql :       expand: "%{User-Name}" -> 'parsa'
(0) sql : SQL-User-Name set to 'parsa'
rlm_sql (sql): Reserved connection (19)
(0) sql :       expand: "SELECT id, username, attribute, value, op FROM radcheck WHERE username = '%{SQL-User-Name}' ORDER BY id" -> 'SELECT id, username, attribute, value, op FROM radcheck WHERE username = 'parsa' ORDER BY id'
rlm_sql (sql): Executing query: 'SELECT id, username, attribute, value, op FROM radcheck WHERE username = 'parsa' ORDER BY id'
(0) sql : User found in radcheck table
(0) sql : Check items matched
(0) sql :       expand: "SELECT id, username, attribute, value, op FROM radreply WHERE username = '%{SQL-User-Name}' ORDER BY id" -> 'SELECT id, username, attribute, value, op FROM radreply WHERE username = 'parsa' ORDER BY id'
rlm_sql (sql): Executing query: 'SELECT id, username, attribute, value, op FROM radreply WHERE username = 'parsa' ORDER BY id'
(0) sql : User found in radreply table
(0) sql :       expand: "SELECT groupname FROM radusergroup WHERE username = '%{SQL-User-Name}' ORDER BY priority" -> 'SELECT groupname FROM radusergroup WHERE username = 'parsa' ORDER BY priority'
rlm_sql (sql): Executing query: 'SELECT groupname FROM radusergroup WHERE username = 'parsa' ORDER BY priority'
rlm_sql (sql): Released connection (19)
(0)   [-sql] = ok
(0) expiration : Account will expire at 'Jan 22 2014 00:00:00 NPT'
## (0)   [expiration] = ok

Doesnot process radgroupreply

**Comment by ShakyShip** [comment]
Thanks brother, finally my freeradius sent group reply to my Mikrotik
but you should put the fixed one on CentOS 7 repo, cause before I change to 3.0.2 I've installed 3.0.2 from repo

**Comment by arr2036** [comment]
We don't control what CentOS do.
