### ISSUE TITLE
Bad DEFAULT entry processing in rlm_files/users in FR3.2.3

### ISSUE THREAD

**Issue by KozlikCZ** [FreeRADIUS/freeradius-server#5035]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

I have this simply config of users in /etc/raddb/users in freeradius 3.2.3:

DEFAULT Framed-Protocol == PPP
        Framed-Protocol = PPP,
        Framed-Compression = Van-Jacobson-TCP-IP

DEFAULT
        Fortinet-Group-Name = vpn-user

The second DEFAULT entry is not processed even if Framed-Protocol is not PPP. No match in log file. When I commented the first DEFAULT entry, it works. This config works well in freeradius 3.0.20.

### Log output from the FreeRADIUS daemon

```shell
...
Tue Jun  6 16:12:39 2023 : Debug: (0)     modsingle[authorize]: calling files (rlm_files)
Tue Jun  6 16:12:39 2023 : Debug: (0)     modsingle[authorize]: returned from files (rlm_files)
Tue Jun  6 16:12:39 2023 : Debug: (0)     [files] = noop
...

When the first DEFAULT entry is commented:
...
Tue Jun  6 16:24:11 2023 : Debug: (0)     modsingle[authorize]: calling files (rlm_files)
Tue Jun  6 16:24:11 2023 : Debug: (0) files: users: Matched entry DEFAULT at line 5
Tue Jun  6 16:24:11 2023 : Debug: (0) files: ::: FROM 1 TO 0 MAX 1
Tue Jun  6 16:24:11 2023 : Debug: (0) files: ::: Examining Fortinet-Group-Name
Tue Jun  6 16:24:11 2023 : Debug: (0) files: ::: APPENDING Fortinet-Group-Name FROM 0 TO 0
Tue Jun  6 16:24:11 2023 : Debug: (0) files: ::: TO in 0 out 0
Tue Jun  6 16:24:11 2023 : Debug: (0)     modsingle[authorize]: returned from files (rlm_files)
Tue Jun  6 16:24:11 2023 : Debug: (0)     [files] = ok
...
```

### Relevant log output from client utilities

Output from radtest with 2 DEFAULT entries:

Sent Access-Request Id 90 from 0.0.0.0:aeb6 to 127.0.0.1:1812 length 79
        User-Name = "user"
        User-Password = "password"
        NAS-IP-Address = ipaddr
        NAS-Port = 0
        Message-Authenticator = 0x00
        Cleartext-Password = "password"
Received Access-Accept Id 90 from 127.0.0.1:714 to 127.0.0.1:44726 length 20

Output from radtest with 1 DEFAULT entry:

Sent Access-Request Id 57 from 0.0.0.0:9f19 to 127.0.0.1:1812 length 79
        User-Name = "user"
        User-Password = "password"
        NAS-IP-Address = ipaddr
        NAS-Port = 0
        Message-Authenticator = 0x00
        Cleartext-Password = "password"
Received Access-Accept Id 57 from 127.0.0.1:714 to 127.0.0.1:40729 length 36
        Fortinet-Group-Name = "vpn-user"

**Comment by alandekok** [comment]
I also added a test to be sure that this behavior does not come back.
