### ISSUE TITLE
OpenSSL header/version mismatch, actual version has correct headers

### ISSUE THREAD

**Issue by Tyrexionibus** [FreeRADIUS/freeradius-server#505]
I'm having an issue when ./configuring freeRADIUS 2.2.3:

checking for OpenSSL version >= 0.9.7... yes
checking OpenSSL library and header version consistency... library: 90819f header: 90812f... no
configure: error: in `/Users/tyrexionibus/Downloads/freeradius-server-2.2.3':
configure: error: OpenSSL library version does not match header version
See`config.log' for more details

Actual version of OpenSSL is 1.0.1f, installed with Homebrew with all configuration correct. However, there seems to be a header mismatch because "90819f" tells that the version is 0.9.8 .

How do I fix this? A website suggests to manually correct the header file with the actual version; however this is risky: OpenSSL has more than one file where the version is written, I would need to correct all of them. Plus, 0.9.8 is not clear as it is but it's "90819f" which is not so immediate to conceive and write.

I'm assuming freeRADIUS is doing something wrong in the ./configuration .

![schermata 01-2456678 alle 23 25 19](https://f.cloud.github.com/assets/6455207/1959172/7edb77ea-8227-11e3-9ca8-ec50740f8033.JPG)

**Comment by scorpiozj** [comment]
Also met this problem.   Using `./configure --with-openssl-includes=/usr/local/include --with-openssl-libraries=/usr/local/lib ` has no use:  
>checking OpenSSL library and header version consistency... library: 9081cf header: 1000200f... no
configure: error: in `/Users/xxxxx/Desktop/Radius/FreeRadius/freeradius-server-3.0.6':
configure: error: OpenSSL library version does not match header version

By the way, I also try this [link](http://stackoverflow.com/a/28638516/371974), and it also failed .

**Comment by arr2036** [comment]
``--with-openssl-includes`` and ``--with-openssl-libraries`` are not valid configure script arguments for 3.0.6. Check ``./configure --help``
