### ISSUE TITLE
[defect]: Public CA cert request procedure gone

### ISSUE THREAD

**Issue by ckbaker10** [FreeRADIUS/freeradius-server#5067]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

The readme describes a makefile entry for server.csr for a public CA

https://github.com/FreeRADIUS/freeradius-server/blob/release_3_2_3/raddb/certs/README.md#making-a-certificate-for-a-public-ca

`make: *** No rule to make target 'server.csr'.  Stop.`

I'm trying to add radius to a Windows CA, will update with working configuration.

Taking into consideration this as well: https://github.com/FreeRADIUS/freeradius-server/blob/release_3_2_3/raddb/certs/xpextensions

### Log output from the FreeRADIUS daemon

```shell
Non relevant
```

### Relevant log output from client utilities

`make: *** No rule to make target 'server.csr'.  Stop.`

**Comment by alandekok** [comment]
```
$ cd raddb/certs
$ make server.csr
make: 'server.csr' is up to date.
```

Don't do it from the top-level source directory.  Do it from the `certs` directory.
