### ISSUE TITLE
[defect]: autconf doesn't recurse

### ISSUE THREAD

**Issue by Spongman** [FreeRADIUS/freeradius-server#5082]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

(v3.2.2)

```
$ autoconf --version
autoconf (GNU Autoconf) 2.69
$ find . -name configure | xargs rm
$ aclocal && autoconf
$ find . -name configure
./configure
````

https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Subdirectories.html says

>  please do not use:
          AC_CONFIG_SUBDIRS([$my_subdirs])

and yet:
```
$ grep AC_CONFIG_SUBDIRS configure.ac
AC_CONFIG_SUBDIRS($mysubdirs)
```

### Log output from the FreeRADIUS daemon

```shell
n/a
```

**Comment by Spongman** [comment]
`autoreconf -fiv` gives:
```
configure.ac:2569: warning: AC_CONFIG_SUBDIRS: you should use literals
../../lib/autoconf/status.m4:1097: AC_CONFIG_SUBDIRS is expanded from...
configure.ac:2569: the top level
autoreconf: configure.ac: subdirectory $mysubdirs not present
```

**Comment by mcnewton** [comment]
Don't wipe the configure files first; do

    ./configure
    make reconfig

If you really want to wipe them first (why) then do

    aclocal && autoconf
    ./configure
    make reconfig
