### ISSUE TITLE
READ THE MESSAGE BELOW BEFORE SUBMITTING AN ISSUE

### ISSUE THREAD

**Issue by AXLancelot** [FreeRADIUS/freeradius-server#5101]
### Message

I had config the clients.conf as follow:
client sitelocal_ipv4 {
	ipv4addr	= *
	secret  = testing123
}
# All IPv6 Site-local clients
client sitelocal_ipv6 {
	ipv6addr = ::
	secret   = testing123
}

When I use another host to test freeradius sever by ipv4 address, it works well. But when I test by ipv6 address, it doesn't work.
ipv4 test command: 
echo "User-Name=steve,User-Password=testing" | radclient 192.168.56.104 auth testing123
reslut:
Sent Access-Request Id 78 from 0.0.0.0:33013 to 192.168.56.104:1812 length 45
Received Access-Accept Id 78 from 192.168.56.104:1812 to 192.168.56.105:33013 length 71

ipv6 test command: 
echo "User-Name=steve,User-Password=testing" | radclient [fe80::c6bb:7752:c867:67c6] auth testing123
reslut:
Sent Access-Request Id 223 from [::]:55988 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
Sent Access-Request Id 223 from [::]:55988 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
Sent Access-Request Id 223 from [::]:55988 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
(0) No reply from server for ID 223 socket 3

on the server, the debug output is:
Ignoring request to auth address :: port 1812 bound to server default from unknown client fe80::4004:2433:9b65:1f0 port 55988 proto udp
Ready to process requests
Ignoring request to auth address :: port 1812 bound to server default from unknown client fe80::4004:2433:9b65:1f0 port 55988 proto udp
Ready to process requests
Ignoring request to auth address :: port 1812 bound to server default from unknown client fe80::4004:2433:9b65:1f0 port 55988 proto udp
Ready to process requests

I don't know what is the problem.

**Comment by alandekok** [comment]
Configuration questions belong on the mailing list.

Hint: `ipv4addr = *` is a /32.  It's not "accept packets from all IP addresses".

This is well documented.

**Comment by AXLancelot** [comment]
But even I modify the clients.conf as follows, the result is the same that ipv4 works, and ipv6 doesn't work. Is it my fault? If so, which document should I learn, please?

client sitelocal_ipv4 {
	ipv4addr = 192.168.56.105
	secret   = testing123
}

# All IPv6 Site-local clients
client sitelocal_ipv6 {
	ipv6addr = fe80::c6bb:7752:c867:67c6
	secret   = testing123
}

reslut:
Sent Access-Request Id 69 from 0.0.0.0:41635 to 192.168.56.104:1812 length 45
Received Access-Accept Id 69 from 192.168.56.104:1812 to 192.168.56.105:41635 length 71

Sent Access-Request Id 234 from [::]:48348 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
Sent Access-Request Id 234 from [::]:48348 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
Sent Access-Request Id 234 from [::]:48348 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
(0) No reply from server for ID 234 socket 3

**Comment by AXLancelot** [comment]
But even I modify the clients.conf as follows, the result is the same that ipv4 works, and ipv6 doesn't work. Is it my fault? If so, which document should I learn, please?

client test_ipv4 {
	ipv4addr = 192.168.56.105
	secret   = testing123
}

client test_ipv6 {
	ipv6addr = fe80::4004:2433:9b65:1f0
	secret   = testing123
}

reslut:
Sent Access-Request Id 21 from 0.0.0.0:35304 to 192.168.56.104:1812 length 45
Received Access-Accept Id 21 from 192.168.56.104:1812 to 192.168.56.105:35304 length 71

Sent Access-Request Id 102 from [::]:50957 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
Sent Access-Request Id 102 from [::]:50957 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
Sent Access-Request Id 102 from [::]:50957 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
(0) No reply from server for ID 102 socket 3

the sever log is as below:
Ignoring request to auth address :: port 1812 bound to server default from unknown client fe80::4004:2433:9b65:1f0 port 50957 proto udp

**Comment by AXLancelot** [comment]
> Configuration questions belong on the mailing list.
> 
> Hint: `ipv4addr = *` is a /32. It's not "accept packets from all IP addresses".
> 
> This is well documented.

But even I modify the clients.conf as follows, the result is the same that ipv4 works, and ipv6 doesn't work. Is it my fault? If so, which document should I learn, please?

client test_ipv4 {
ipv4addr = 192.168.56.105
secret = testing123
}

client test_ipv6 {
ipv6addr = fe80::4004:2433:9b65:1f0
secret = testing123
}

reslut:
Sent Access-Request Id 21 from 0.0.0.0:35304 to 192.168.56.104:1812 length 45
Received Access-Accept Id 21 from 192.168.56.104:1812 to 192.168.56.105:35304 length 71

Sent Access-Request Id 102 from [::]:50957 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
Sent Access-Request Id 102 from [::]:50957 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
Sent Access-Request Id 102 from [::]:50957 to [fe80::c6bb:7752:c867:67c6]:1812 length 45
(0) No reply from server for ID 102 socket 3

the sever log is as below:
Ignoring request to auth address :: port 1812 bound to server default from unknown client fe80::4004:2433:9b65:1f0 port 50957 proto udp

**Comment by AXLancelot** [comment]
https://github.com/FreeRADIUS/freeradius-server/issues/4954
It seems that my issue is similar to this issue.

**Comment by AXLancelot** [comment]
> 

Thank you so much! This is useful. 
And I know that it may be my configuration fault, but I don't which document can help me. Could please tell me where is mailing list?
