### ISSUE TITLE
User not disconnecting After plan end.

### ISSUE THREAD

**Issue by nandish486** [FreeRADIUS/freeradius-server#5115]
### Message

[max-session, accessperiod, sessiontimeout, terminate-session] etc has been used

my configuration in coa, openvpn server config, clients.conf etc is working.

also accounting section is up and running everything works well

but the bug is whenever the plan ends the user not gets disconnected,

on using command, radiusd -X '' some disconnect command '' it just sends request to radius and shows receive request "accept"
but the user is still connected,. i checked many formus but i not yet solved it, please help me,(as it took 4 weeks to search solution, 14 hours/day seat, now i am tired)

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
