### ISSUE TITLE
Error on sudo make command

### ISSUE THREAD

**Issue by ranaaditya** [FreeRADIUS/freeradius-server#5122]
### Message

Hi team,

I have server with ubunutu 20.04 LTS , on running ``sudo make`` its giving me error:

``
CC src/modules/rlm_python3/rlm_python3.c
cc1: error: invalid argument '/build/python3.8' to '-fdebug-prefix-map'
make: *** [scripts/boiler.mk:635: /home/luser/freeradius-server/build/objs/src/modules/rlm_python3/rlm_python3.lo] Error 1
``

Before sudo make, i run ``sudo ./configure --with-openssl=no``

any idea how I can fix this ?

Thanks for the help in advance !

Thanks,
Aditya

**Comment by alandekok** [comment]
Don't do `sudo make` or `sudo configure`.  It's not necessary.

The Wiki has instructions for building the server,  It works fine.
