### ISSUE TITLE
[defect]: https://freeradius.org/documentation/ 404 error

### ISSUE THREAD

**Issue by KoRORland** [FreeRADIUS/freeradius-server#5129]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

Visit https://freeradius.org/documentation/ , it shows sad octopus instead of documentation

### Log output from the FreeRADIUS daemon

```shell
not a FreeRADIUS bug per se
```

**Comment by mcnewton** [comment]
Fixed, thanks.
