### ISSUE TITLE
[defect]:  rlm_securid wont compile

### ISSUE THREAD

**Issue by SGC1990** [FreeRADIUS/freeradius-server#5159]
### What type of defect/bug is this?

Non compliance with a standards document

### How can the issue be reproduced?

./configure --with-rlm-securid-lib-dir=/root/Freeradius/Build/AuthSDK_C_v8.6.1/lib/32bit/lnx/Release

Running tests for rlm_securid

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for acexport.h... yes
checking for SD_Init in -laceclnt in /root/Freeradius/Build/AuthSDK_C_v8.6.1/lib/32bit/lnx/Release... no
checking for SD_Init in -laceclnt... no
checking for SD_Init in -laceclnt in /usr/local/lib... no
checking for SD_Init in -laceclnt in /opt/lib... no
checking for SD_Init in -laceclnt in /usr/local/aceclnt/lib... no
checking for SD_Init in -laceclnt in /opt/homebrew/lib... no
checking for SD_Init in -laceclnt in /opt/homebrew/opt/aceclnt/lib... no
configure: WARNING: securid libraries not found. Use --with-rlm-securid-lib-dir=<path>.
configure: WARNING: silently not building rlm_securid.
configure: WARNING: FAILURE: rlm_securid requires:  libaceclnt.
configure: creating ./config.status
config.status: creating all.mk

When I try to compile I get this error and dont know how to fix

### Log output from the FreeRADIUS daemon

```shell
Can even build the package
```

**Comment by alandekok** [comment]
Is this a 32-bit system?  `/root/Freeradius/Build/AuthSDK_C_v8.6.1/lib/32bit/lnx/Release`

You can also look at the output of `config.log` to see why it fails.

However, the securid module is not really supported.  If it works, great.  But we don't have access to the securid libraries etc.  So it is very difficult for us to help you debug it.

**Comment by SGC1990** [comment]
I have tried both 32- and 64-bit versions nothing is working. here is the log
[config.log](https://github.com/FreeRADIUS/freeradius-server/files/12446482/config.log)

**Comment by alandekok** [comment]
The errors are:

```
configure:3488: gcc -o conftest -g -O2 -L/root/Freeradius/Build/AuthSDK_C_v8.6.1/lib/64bit/lnx/Release -Wl,-rpath,/root/Freeradius/Build/AuthSDK_C_v8.6.1/lib/64bit/lnx/Release     conftest.c -laceclnt  >&5
/usr/bin/ld: warning: libnsl.so.1, needed by /root/Freeradius/Build/AuthSDK_C_v8.6.1/lib/64bit/lnx/Release/libaceclnt.so, not found (try using -rpath or -rpath-link)
/root/Freeradius/Build/AuthSDK_C_v8.6.1/lib/64bit/lnx/Release/libaceclnt.so: undefined reference to `pthread_rwlock_rdlock'
/root/Freeradius/Build/AuthSDK_C_v8.6.1/lib/64bit/lnx/Release/libaceclnt.so: undefined reference to `pthread_rwlock_init'

```

You will have to add `-lnsl -pthread` to the `rlm_securid/all.mk` file.  This can be done manually.  The `configure` script is a way to auto-generate that file.  But nothing stops you from editing that file manually.

i.e. run `configure` as above.  Ignore the errors about `rlm_securid`.  Then edit `src/modules/rlm_securid/all.mk`, and make it look like this:

````
TARGETNAME	:= rlm_securid

ifneq "$(TARGETNAME)" ""
TARGET		:= $(TARGETNAME).a
endif

SOURCES		:= $(TARGETNAME).c mem.c

SRC_CFLAGS	:= -I/root/Freeradius/Build/AuthSDK_C_v8.6.1/lib/32bit/lnx/Release
TGT_LDFLAGS:= -lnsl -pthread
TGT_LDLIBS

ifneq "$(TARGETNAME)" ""
install: $(R)$(raddbdir)/mods-available/securid

$(R)$(raddbdir)/mods-available/securid: src/modules/rlm_securid/securid | $(R)$(raddbdir)/mods-available
	@$(ECHO) INSTALL $(notdir $<)
	@$(INSTALL) -m 640 $< $(R)$(raddbdir)/mods-available
endif
```

Then `make` as normal.  And see if it builds.  That _should_ work.  If not, you will have to play with the `SRC_FLAGS` variable to add in the correct path for `aceexport.h`.  And you will habe to edit the `TGT_LDFLAGS` variable to add in the correct libraries.

**Comment by SGC1990** [comment]
Now I am getting make: *** No targets specified and no makefile found.  Stop. when doing make

**Comment by alandekok** [comment]
You have to run `configure`.  Then `make`.  Don't run `make` from the `src/modules/rlm_securid` directory.  Run it from the top level of the source, where you ran `configure`.  The Wiki has more instructions on how to build from source.

**Comment by alandekok** [comment]
Oh, and please don't use the git `master` branch.  That's v4, and is unreleased, and unsupported.  You should be using the v3.2.x branch.  That is the currently supported release.

**Comment by SGC1990** [comment]
> You have to run `configure`. Then `make`. Don't run `make` from the `src/modules/rlm_securid` directory. Run it from the top level of the source, where you ran `configure`. The Wiki has more instructions on how to build from source.

So if I understand this I need not to use the configure in the rlm_securid folder and use the one in the base directory so do I need to uninstall the freeradius rpm package I installed

**Comment by alandekok** [comment]
You shouldn't have multiple versions of the server installed.

**Comment by SGC1990** [comment]
> You shouldn't have multiple versions of the server installed.

I have freeradius-server-3.2.3 installed, and I have the source files in the root directory on the server, I thought I just need to compile the module and it would install in the mods-available.

**Comment by alandekok** [comment]
I gave my recommendations for a reason.

1) don't install an RPM and then try to install it from source on top of that.  It very likely won't work.

2) don't use the git `master` branch.  use the v3.2.x branch

Follow the instructions and get it to work.  Or ignore the instructions and create problems for yourself.  The choice is up to you.
