### ISSUE TITLE
[defect]: EAP-TEAP Compile Warning

### ISSUE THREAD

**Issue by dhpark21** [FreeRADIUS/freeradius-server#5162]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

Hi.
When 3.2.x GIT compile time below warning happen.

CC src/modules/rlm_eap/types/rlm_eap_teap/rlm_eap_teap.c
CC src/modules/rlm_eap/types/rlm_eap_teap/eap_teap.c
src/modules/rlm_eap/types/rlm_eap_teap/eap_teap.c:64: warning: missing braces around initializer
src/modules/rlm_eap/types/rlm_eap_teap/eap_teap.c:64: warning: (near initialization for ‘imck_zeros.simck’)
cc1: warning: unrecognized command line option "-Wno-date-time"
CC src/modules/rlm_eap/types/rlm_eap_teap/eap_teap_crypto.c
LINK build/lib/rlm_eap_teap.la

### Log output from the FreeRADIUS daemon

```shell
.
```

### Relevant log output from client utilities

.

### Backtrace from LLDB or GDB

```shell
.
```

**Comment by alandekok** [comment]
Compiler warnings aren't bugs, segvs, or memory corruption.
