### ISSUE TITLE
freeradius failure status=1/FAILURE

### ISSUE THREAD

**Issue by danijuntak** [FreeRADIUS/freeradius-server#5171]
### Message

journalctl -xe

Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Creating attribute SQL-Group
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql_mysql: libmysql version: 8.0.34
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql (sql): Attempting to connect to database "radius"
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql (sql): Initialising connection pool
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql (sql): Processing generate_sql_clients
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql (sql) in generate_sql_clients: query is SELECT id, nasname, shortname, type, secret, server FROM nas
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql (sql): 0 of 0 connections in use.  You  may need to increase "spare"
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql (sql): Opening additional connection (0), 1 of 1 pending slots used
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql_mysql: Starting connect to MySQL server
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql (sql): Reserved connection (0)
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_sql (sql): Released connection (0)
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: tls: Using cached TLS configuration from previous invocation
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: tls: Using cached TLS configuration from previous invocation
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_mschap (mschap): using internal authentication
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_detail (auth_log): 'User-Password' suppressed, will not appear in detail output
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: rlm_cache (cache_eap): Driver rlm_cache_rbtree (module rlm_cache_rbtree) loaded and linked
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Auth-Type PAP for attr Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Auth-Type CHAP for attr Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Auth-Type MS-CHAP for attr Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Ignoring "ldap" (see raddb/mods-available/README.rst)
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Autz-Type New-TLS-Connection for attr Autz-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Post-Auth-Type REJECT for attr Post-Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Post-Auth-Type Challenge for attr Post-Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Post-Auth-Type Client-Lost for attr Post-Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Auth-Type PAP for attr Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Auth-Type CHAP for attr Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Auth-Type MS-CHAP for attr Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]:  # Skipping contents of 'if' as it is always 'false' -- /etc/freeradius/3.0/sites-enabled/inner-tunnel:336
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Compiling Post-Auth-Type REJECT for attr Post-Auth-Type
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: radiusd: #### Skipping IP addresses and Ports ####
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115422]: Configuration appears to be OK
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115423]: WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115423]: WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115423]: WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115423]: WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115423]: WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
Sep 07 02:33:18 pid-jkt-svr-radius freeradius[115423]: WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
Sep 07 02:33:18 pid-jkt-svr-radius systemd[1]: freeradius.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStart= process belonging to unit freeradius.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Sep 07 02:33:18 pid-jkt-svr-radius systemd[1]: freeradius.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit freeradius.service has entered the 'failed' state with result 'exit-code'.
Sep 07 02:33:18 pid-jkt-svr-radius systemd[1]: Failed to start FreeRADIUS multi-protocol policy server.
░░ Subject: A start job for unit freeradius.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit freeradius.service has finished with a failure.
░░ 
░░ The job identifier is 1010468 and the job result is failed.

root@pid-jkt-svr-radius:/home/netadmin#

**Comment by alandekok** [comment]
The template for the github issue tells you what information we need.  Without that information we can't help you.

On top of that, this isn't a crash or a bug.  You've most likely misconfigured the server.  i.e. your configuration is wrong, and the server is trying to tell you that.

Read the documentation and follow the instructions.  Failing to do that means you won't be able to solve any issues, and we won't be able to help you.
