### ISSUE TITLE
[defect]: https://github.com/FreeRADIUS/freeradius-server/tree/master/doc

### ISSUE THREAD

**Issue by jringoot** [FreeRADIUS/freeradius-server#5174]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

the link to the introduction:
https://github.com/FreeRADIUS/freeradius-server/blob/master/doc/introduction/index.adoc

is broken

### Log output from the FreeRADIUS daemon

```shell
click on the link "introduction on the doc startpage:
https://github.com/FreeRADIUS/freeradius-server/tree/master/doc
it points to https://github.com/FreeRADIUS/freeradius-server/blob/master/doc/introduction/index.adoc
and that doesn't exist
```

**Comment by alandekok** [comment]
It's a soft link.

You're not supposed to read the documentation by wandering around GitHub.  The documentation is built from source, with links / CSS / etc. added.  It's online at https://freeradius.org/documentation/freeradius-server/3.2.4/
