### ISSUE TITLE
[defect]: make docsite

### ISSUE THREAD

**Issue by jringoot** [FreeRADIUS/freeradius-server#5177]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

I follow the instructions here to  make the docsite (installed node.js and antora)
https://github.com/FreeRADIUS/freeradius-server/tree/master/doc

make docsite
gives this output
**make: *** No rule to make target 'docsite'.  Stop.**

### Log output from the FreeRADIUS daemon

```shell
make: *** No rule to make target 'docsite'.  Stop.
```

**Comment by alandekok** [comment]
You also need asciidoctor.  If you read the output of `configure`, it will give you warnings about this:

```
  AC_MSG_WARN([asciidoctor not found - Please install if you want build the docs])
...
  AC_MSG_WARN([antora not found - Please install if you want build the site])

```
