### ISSUE TITLE
[defect]: FreeRADIUS v4/pyfr

### ISSUE THREAD

**Issue by mrozhnov** [FreeRADIUS/freeradius-server#5190]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

Hello!
I'm using Ubuntu 22.04, I made a build of the branch v4/pyfr using "make deb". After that I installed packages:
```
dpkg -i libfreeradius4_4.0~30229+git_amd64.deb
dpkg -i freeradius-common_4.0~30229+git_all.deb
dpkg -i freeradius-config_4.0~30229+git_amd64.deb
apt install -y ssl-cert
dpkg -i libfreeradius4_4.0~30229+git_amd64.deb

```
freeradius -X showed that everything was OK

I have a python module witch sends a POST request and gets response for authentication. The configuration of the python is the following in the default config file:
```
recv Access-Request {
          update {
                &control.Auth-Type := fra
          }

}

authenticate fra {
        python
}

```

The fra.py file contains:
 ```
data = {"login": login, "passcode": passcode, "agent": "radius"}
    try:
        url = "https://10.79.63.23/auth"
        response = requests.post(url, data=data, verify=False, timeout=30)
    except requests.exceptions.RequestException:
        return radiusd.RLM_MODULE_REJECT`

```
The /etc/freeradius/mods-available/python includes:
`python_path = ${modconfdir}/${.:name}:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/usr/local/lib/python3.10/dist-packages:/usr/lib/python3/dist-packages
`

When I try with freeradius -X and radtest tool I get the issue

### Log output from the FreeRADIUS daemon

```shell
ERROR : (0)    python -   ERROR: <class 'ImportError'> (Can't connect to HTTPS URL because the SSL module is not available.)
ERROR : (0)    python -   ERROR: [0] /etc/freeradius/mods-config/python/example.py:36 at authenticate()
ERROR : (0)    python -   ERROR: [1] /etc/freeradius/mods-config/python/requests/api.py:73 at get()
ERROR : (0)    python -   ERROR: [2] /etc/freeradius/mods-config/python/requests/api.py:59 at request()
ERROR : (0)    python -   ERROR: [3] /etc/freeradius/mods-config/python/requests/sessions.py:589 at request()
ERROR : (0)    python -   ERROR: [4] /etc/freeradius/mods-config/python/requests/sessions.py:703 at send()
ERROR : (0)    python -   ERROR: [5] /etc/freeradius/mods-config/python/requests/adapters.py:527 at send()
ERROR : (0)    python -   ERROR: [6] /etc/freeradius/mods-config/python/urllib3/connectionpool.py:867 at urlopen()
ERROR : (0)    python -   ERROR: [7] /etc/freeradius/mods-config/python/urllib3/connectionpool.py:295 at _get_conn()
ERROR : (0)    python -   ERROR: [8] /etc/freeradius/mods-config/python/urllib3/connectionpool.py:1056 at _new_conn()
Debug : (0)    default -   python (fail)
```

### Relevant log output from client utilities

Sent Access-Request Id 68 from 0.0.0.0:50987 to 10.79.63.17:1812 length 78
        User-Name = "mrozhnov"
        User-Password = "123456"
        NAS-IP-Address = 127.0.1.1
        NAS-Port = 0
        Message-Authenticator = 0x00
        Cleartext-Password = "123456"
Received Access-Reject Id 68 from 10.79.63.17:1812 to 10.79.63.112:50987 length 20

**Comment by alandekok** [comment]
This is really a python issue:

> ERROR : (0)    python -   ERROR: <class 'ImportError'> (Can't connect to HTTPS URL because the SSL module is not available.)

The path needs to be set properly.  I've updated the documentation in `mods-available/python` to explain how to do this.

**Comment by mrozhnov** [comment]
Hi @alandekok!
We have rebuilt a master branch with new commit. But now after config settings the python module could not be found.
default file contains:
```
recv Access-Request {
         update {
                &control.Auth-Type := fra
         }
}

authenticate fra {
        python
}
```

mods-available/python contains:

```
python {
        module = example
...

```
We tried both  `path=${modconfdir}/${.:name}` and `# path=${modconfdir}/${.:name}`

But we have the same issue:
```
Debug : Instantiating rlm_python "python"
Error : python - python_function_load - Module 'example' load failed
Error : python - <class 'ModuleNotFoundError'> (No module named 'example')
Error : /etc/freeradius/mods-enabled/python[27]: Instantiation failed for module "python"

```

Changing path could not help to find out example.py location

Best regards,
Mikhail




```

**Comment by jpereira** [comment]
@mrozhnov Please, just use the branch `v3.2.x/HEAD` where is the current latest stable code. That branch `v4/pyfr` is related to a _alpha_ Python bind library for some API functions in `libfreeradius-*`
