### ISSUE TITLE
Advice 32 Bits Counter - Acct-Input-Octets And Acct-Output-Octets 

### ISSUE THREAD

**Issue by K-razy** [FreeRADIUS/freeradius-server#5197]
### Message

Hello, hope you are fine, 

I'm currently looking for reporting usage of my network using Freeradius

I followed, this excellent topic, working very well ==> https://wiki.freeradius.org/guide/Data-Usage-Reporting
However I have a problem : 

The NAS used which is a OPNSENSE firewall is not compatible with Gigawords
That means, when Acct-Input-Octets And Acct-Output-Octets counters reach their max value, the counter reset to 0
This limit can be reached so fast nowadays and it makes wrong all data in the reporting system.

Do you have any advice on this case ?
I've opened a case at OPNSENSE but it seems they don't want to implement it.

Thanks in advance for your time given in this case.

Kind Regards

**Comment by alandekok** [comment]
The only way to fix this is if opensense fixes it.
