### ISSUE TITLE
mschap password expiration date check question

### ISSUE THREAD

**Issue by dhpark21** [FreeRADIUS/freeradius-server#5204]
### Message

Hi. 
I hope to use as like below
1. FR3.2.3, Local MysqlDB
2. Windows10 PEAP/mschapv2 auth.
3. if local user password account are expired(30day) , then Windows 10 wifi connect time popup change Password screen
4. how can i config FR3.2.3?
5. Thanks. now PEAP/mschapv2 fork fine. but not config "user password expiration date check.., and another config.."

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.
