### ISSUE TITLE
[defect]: reject_delay decimal value < 1 is ignored

### ISSUE THREAD

**Issue by swoga** [FreeRADIUS/freeradius-server#5207]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

The documentation in `radiusd.conf` states that decimal values are allowed for `reject_delay`.
It contains a sentence about useful values, but I would have considered these as suggestions and not limits.
However, values between 0 and 1 are ignored and replaced with 1 by the bounds check.

example config excerpt:
```
security {
[...]
        #
        #  reject_delay: When sending an Access-Reject, it can be
        #  delayed for a few seconds.  This may help slow down a DoS
        #  attack.  It also helps to slow down people trying to brute-force
        #  crack a users password.
        #
        #  Setting this number to 0 means "send rejects immediately"
        #
        #  If this number is set higher than 'cleanup_delay', then the
        #  rejects will be sent at 'cleanup_delay' time, when the request
        #  is deleted from the internal cache of requests.
        #
        # This number can be a decimal, e.g. 3.4
        #
        #  Useful ranges: 1 to 5
        reject_delay = 0.5
[...]
}
```

relevant source code line:
https://github.com/FreeRADIUS/freeradius-server/blob/8ac05b50a7b9148767374012200cb702663ad921/src/main/mainconfig.c#L1145

### Log output from the FreeRADIUS daemon

```shell
FreeRADIUS Version 3.2.1
[...]
Ignoring "reject_delay = 0.500000", forcing to "reject_delay = 1.000000"
[...]
```

**Comment by alandekok** [comment]
You're welcome to consider them as whatever you want.

We would much prefer to have a pull request which makes the comments clearer.  It's not much more work than opening a bug report.

As it is, the documentation seems fairly clear.  If this is an issue which needs fixing, then there are literally hundreds of little things which could be tweaked.

Until such time as either we have a full-time documentation person, or we get patches from the community, this is a very low-priority issue.
