### ISSUE TITLE
[defect]: The ftp url to fetch the 3.0.19 freeradius server pckage si not working i.e. ftp://ftp.freeradius.org/pub/freeradius/freeradius-server-3.0.19.tar.gz

### ISSUE THREAD

**Issue by abhigpt548** [FreeRADIUS/freeradius-server#5214]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

Description: The ftp url to fetch the 3.0.19 freeradius server pckage si not working i.e. ftp://ftp.freeradius.org/pub/freeradius/freeradius-server-3.0.19.tar.gz

While downloading this ftp tar , its failing and it was working earlier
![image](https://github.com/FreeRADIUS/freeradius-server/assets/52811688/285e2756-159a-473f-a5d0-3b98c3f43722)

### Log output from the FreeRADIUS daemon

```shell
>>> freeradius: Fetching ftp://ftp.freeradius.org/pub/freeradius/freeradius-server-3.0.19.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
curl: (7) Failed to connect to ftp.freeradius.org port 21: Connection refused
>>> ERROR: freeradius: fetch failed
```

**Comment by mcnewton** [comment]
Working fine here. Note that old versions have been moved to an `old/` directory.

    $ curl -o f ftp://ftp.freeradius.org/pub/freeradius/old/freeradius-server-3.0.19.tar.gz
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 4772k  100 4772k    0     0  2888k      0  0:00:01  0:00:01 --:--:-- 2888k
    $

**Comment by abhigpt548** [comment]
@mcnewton   i tried to run my gitlab pipeline and getting below :
![image](https://github.com/FreeRADIUS/freeradius-server/assets/52811688/abfa44d4-a671-4348-bf5f-02d92521efac)
![image](https://github.com/FreeRADIUS/freeradius-server/assets/52811688/5a4b83f3-6634-4c71-8976-67cdf643d55b)


and i tried to get the the server package on my local machine as well but as getting the same but when i disconnected the VM i was able to fetch the package 

Could you please help me with this?

**Comment by mcnewton** [comment]
You have something misconfigured in your setup, probably a bad proxy server. FTP doesn't give HTTP "503 Service Unavailable" error codes.
