### ISSUE TITLE
[defect]: dynamic_clients can get into an endless loop (consuming 100% cpu) when the value is ""

### ISSUE THREAD

**Issue by uedvt359** [FreeRADIUS/freeradius-server#5228]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

When using `client dynamic`, credentials can be fetched from an exernal source like a database or API using expansions. Below is a simplified example how this can look:

```
server dynamic_clients {
    authorize {
            update control {
                &FreeRADIUS-Client-IP-Address = "%{Packet-Src-IP-Address}"
                &FreeRADIUS-Client-Shortname = "%{rest: http://localhost:5001/shortname?ipaddress=%{Packet-Src-IP-Address}}"
                &FreeRADIUS-Client-Secret = "%{rest: http://localhost:5001/secret?ipaddress=%{Packet-Src-IP-Address}}"
            }
            ok
    }
}   
```

This works, as long as the expansion returns a value. If for example the API were to die, it would return nothing, triggering a bug in radiusd's linked list implementation.

Note that while I'm using `%{rest:}` here, this should be reproducible by any expansion module that can fail and not return a value. A failure in an external (to radiusd) service should not cause a DoS.

Even worse, this can even trigger if the value simply is the empty string:

```
server dynamic_clients {
    authorize {
            update control {
                &FreeRADIUS-Client-IP-Address = "%{Packet-Src-IP-Address}"
                &FreeRADIUS-Client-Shortname = ""
                &FreeRADIUS-Client-Secret = ""
            }
            ok
    }
}   
```

C.f. the following snippet from 3.0.x's `src/main/client.c`:

```c
RADCLIENT *client_afrom_request(RADCLIENT_LIST *clients, REQUEST *request)
// ...
        CONF_PAIR       *cp = NULL;
// ...
        for (i = 0; dynamic_config[i].name != NULL; i++) {
// ...
                case PW_TYPE_STRING:
//...
                        if (!vp->vp_strvalue[0]) break;
// ...
                        cp = cf_pair_alloc(c->cs, parse->name, strvalue, T_OP_SET, T_BARE_WORD, T_SINGLE_QUOTED_STRING);
// ...
                cf_pair_add(c->cs, cp);
```

Using the example above, it first parses `FreeRADIUS-Client-IP-Address` successfully and stores it in `cp`. then, it attempts to parse `FreeRADIUS-Client-Shortname` (or `FreeRADIUS-Client-Secret`, for that matter).

here it encounters `""`; if `vp_strvalue` is the empty string, the `switch` exits before `cp` is updated so `cp` still contains the previous list element, `FreeRADIUS-Client-IP-Address`. after the `switch` it calls `cf_pair_add()` and appends the already existing item into `c->cs`. 

C.f. `src/main/conffile.c`: `cf_pair_add` calls `cp_item_add`.

```c
void cf_item_add(CONF_SECTION *cs, CONF_ITEM *ci)
// ...
                cs->tail->next = ci;
// ...
        for (/* nothing */; ci != NULL; ci = ci->next) {
// ...
```

right at the start, it sets the last item's `next` pointer to the new element. if these refer to the same memory location, the linked list becomes a loop. then it iterates through the linked list, which never ends. this is CPU bound, fully consuming a single CPU core. In the `-X` log below, you can see that the line `ipv4addr = 10.10.10.10` is printed twice; this is not a copy-paste error but caused by the `RDEBUG2("%s = %s",` line of `client_afrom_request` reading the broken item before the fatal call to `cf_pair_add`.

I've managed to reproduce this with both the latest freeradius versions shipped with RHEL8 (`freeradius-3.0.20-14.module+el8.8.0+17558+3f8a93b9.x86_64`) and alpine 3.18 (`freeradius-3.0.26-r2 aarch64`). I've also stumbled upon a potential fix in radius 3.2, but can't test if this completely fixes the problem (https://github.com/FreeRADIUS/freeradius-server/commit/0f50abeb0ed15707862563dd080007638545b4a2). However, given the prevalence of 3.0, I hope this bug can be fixed in the old/maintanace branch.

### Log output from the FreeRADIUS daemon

```shell
Listening on auth address * port 1812 bound to server default
Listening on acct address * port 1813 bound to server default
Listening on proxy address * port 60235
Ready to process requests
(0) server dynamic_clients {
(0) # Executing section authorize from file /etc/raddb/sites-enabled/dvt
(0)   authorize {
(0)     update control {
(0)       EXPAND %{Packet-Src-IP-Address}
(0)          --> 10.10.133.125
(0)       &FreeRADIUS-Client-IP-Address = 10.10.10.10
(0)       &FreeRADIUS-Client-Shortname = ""
(0)       &FreeRADIUS-Client-Secret = ""
(0)     } # update control = noop
(0)     [ok] = ok
(0)   } # authorize = ok
(0) } # server dynamic_clients
(0) Converting control list to client fields
(0)   ipv4addr = 10.10.10.10
(0)   ipv4addr = 10.10.10.10
^C # hangs forever
```

### Backtrace from LLDB or GDB

```
Program received signal SIGINT, Interrupt.
0x0000fffff7e295c8 in pair_cmp (a=<optimized out>, b=0xfffff6b167b0) at src/main/conffile.c:237
237	src/main/conffile.c: No such file or directory.
(gdb) bt
#0  0x0000fffff7e295c8 in pair_cmp (a=<optimized out>, b=0xfffff6b167b0) at src/main/conffile.c:237
#1  0x0000fffff7de06ec in rbtree_insert_node (tree=0xfffff6b166e0, data=data@entry=0xfffff6b167b0) at src/lib/rbtree.c:275
#2  0x0000fffff7de08e4 in rbtree_insert (tree=<optimized out>, data=data@entry=0xfffff6b167b0) at src/lib/rbtree.c:333
#3  0x0000fffff7e29ab0 in cf_item_add (ci=0xfffff6b167b0, cs=0xfffff6b03c90) at src/main/conffile.c:833
#4  cf_item_add (cs=0xfffff6b03c90, ci=<optimized out>) at src/main/conffile.c:801
#5  0x0000aaaaaaab8950 in client_afrom_request (clients=clients@entry=0xfffff7fee5f0, request=request@entry=0xfffff6ae4850) at src/main/client.c:1431
#6  0x0000aaaaaaabf6bc in client_listener_find (listener=listener@entry=0xfffff6ae4280, ipaddr=ipaddr@entry=0xfffffffffb08, src_port=49278) at src/main/listen.c:329
#7  0x0000aaaaaaac034c in auth_socket_recv (listener=0xfffff6ae4280) at src/main/listen.c:1642
#8  0x0000fffff7de771c in fr_event_loop (el=0xfffff7680220) at src/lib/event.c:654
#9  0x0000aaaaaaad8bf0 in radius_event_process () at src/main/process.c:6121
#10 0x0000aaaaaaab5508 in main (argc=2, argv=<optimized out>) at src/main/radiusd.c:641

(gdb) x ci
0xfffff6b167b0:	0xf6b167b0
(gdb) p *ci
$1 = {next = 0xfffff6b167b0, parent = 0xfffff6b03c90, lineno = 0, filename = 0x0, type = CONF_ITEM_PAIR}
(gdb) p ci->next
$2 = (struct conf_item *) 0xfffff6b167b0
```

**Comment by alandekok** [comment]
I've pushed a fix in b0b7026ff.  It's just cherry-picking the relevant patch from the v3.2.x branch.

We'll release a new version of 3.0 before the end of the year.
