### ISSUE TITLE
The email I sent did not receive a response. I will repeat the question here.

### ISSUE THREAD

**Issue by zisain** [FreeRADIUS/freeradius-server#5229]
### Message

Hello, I would like to ask about the configuration method of radius issuing dynamic IP addresses to VPN dial-up users.
The situation is this:
The vpn server is xl2tpd, and users pass freeradius-server authentication when dialing.
Now you can only specify the IP in /etc/freeradius/3.0/users configuration
"test   Cleartext-Password := '12345678'
       Framed-IP-Address = 172.16.18.33,
       Framed-IP-Netmask = 255.255.255.0  "
But what I hope is to get a random address from the ippool, but I don't know how to configure it.
After reading the manual([github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/mods-available/ippool](http://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/mods-available/ippool))
After configuration, freeradius-server cannot be started directly. I modified it.
"test     Cleartext-Password := '123456'
       Pool-Name := 'test' "

There are two points here that I don’t quite understand.
![QQ图片20231124101242](https://github.com/FreeRADIUS/freeradius-server/assets/110014640/069c96a3-d179-4680-89ca-20526508bc61)

1. radiusd.conf: ippool students { [...] }      Do you want me to define the user group in /etc/freeradius/3.0/radiusd.conf? So how do I configure it?
2. users file  : DEFAULT Group == students, Pool-Name := "students"   Do you want me to define the default associated user group and address pool in /etc/freeradius/3.0/users?

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.  The template for github issues tells you this.

I really don't understand why anyone thinks it's productive to ignore documentation.
