### ISSUE TITLE
Freeradius gets password in ascii code not in characters 

### ISSUE THREAD

**Issue by rovshan91** [FreeRADIUS/freeradius-server#5269]
### Message

When i'm authetificate from routers in debug i see that Freeradius gets password in ascii code not in characters , so it can't autheticate no one.
`
(0) Received Access-Request Id 22 from 10.10.81.254:1645 to 10.10.81.31:1812 length 71
(0)   User-Name = "rovshan"
(0)   User-Password = "\254\323c\253\360\214\315g\321\3035 :4\314\""
(0)   NAS-Port = 2
(0)   NAS-Port-Id = "tty2"
(0)   NAS-Port-Type = Virtual
(0)   NAS-IP-Address = 10.10.81.254
(0) # Executing section authorize from file /etc/freeradius/3.0/sites-enabled/default
(0)   authorize 
`
update - i`m ssory it's not ascii but very strange symbols

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.

If you keep opening github issues for configuration mistakes, we will simply block you from the github repository.
