### ISSUE TITLE
Mariadb error

### ISSUE THREAD

**Issue by drcyberg** [FreeRADIUS/freeradius-server#5305]
### Message

Hi Masters!

After setting up a new NAS device, I encountered this error. Fortunately, restarting the VM solved the problem.
What do you think this could be?:

![Screenshot_2024-03-11_17-41-26](https://github.com/FreeRADIUS/freeradius-server/assets/48408000/c2e68e45-c6da-4369-9277-a96328675d4c)

OS: Ubuntu 22.04 Server LTS
Freeradius: 3.2.3

On Cliens Site error: `RADIUS Access-Request timed out after 4 attempts` 

Thank you!

Regards: DrCyberg

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.

There is no need to post images of text. It's not *that* hard to cut & paste text.
