### ISSUE TITLE
freeradius 3.0.1: No "reference" password added

### ISSUE THREAD

**Issue by xiaomu** [FreeRADIUS/freeradius-server#531]
Output of "radiusd -X" is

```
(0) ldap : Waiting for search result...
(0) ldap : User object found at DN "CN=x,OU=y,OU=z,OU=a,DC=b,DC=domain"
(0) ldap : Processing user attributes
(0) WARNING: ldap : No "reference" password added. Ensure the admin user has permission to read the password attribute
(0) WARNING: ldap : PAP authentication will *NOT* work with Active Directory (if that is what you were trying to configure)
rlm_ldap (ldap): Released connection (4)
(0)   [-ldap] = ok
(0)   [expiration] = noop
(0)   [logintime] = noop
(0) WARNING: pap : No "known good" password found for the user.  Not setting Auth-Type.
(0) WARNING: pap : Authentication will fail unless a "known good" password is available.
(0)   [pap] = noop
(0)  } #  authorize = ok
(0) ERROR: No Auth-Type found: rejecting the user via Post-Auth-Type = Reject
(0) Failed to authenticate the user.
(0) Using Post-Auth-Type Reject
```

My "mods-enabled/ldap" is https://gist.githubusercontent.com/xiaomu/c3b23fc804cf0cf99be8/raw/dea0d21a680a46686182b87740526c6003c8acd7/ldap 
and "sites-enabled/default" is https://gist.githubusercontent.com/xiaomu/c3b23fc804cf0cf99be8/raw/70e6dbc09639605334a795163f8bea3aa11a2d1f/default 

Actually, I am not very clear about how to configure ldap authenticate with freeradius3.
I will be grateful if you can give me some advices.

**Comment by FelixOCL** [comment]
This was the only version 3 related post that helped us to solve our "No 'known good pass'" problem.

Thanks a lot.
