### ISSUE TITLE
Attribute non-existent or inconsistency in your vendor/attribute dictionary

### ISSUE THREAD

**Issue by VVsta** [FreeRADIUS/freeradius-server#5319]
### Message

I have a new installation under debian 12 with Freeradius 3 and Daloradius 2.1, when I try to assign Dynmische VLANs with RFC2868, I get the following error:

Error:

Warning. Attribute non-existent or inconsistency in your vendor/attribute dictionary.

What can I do?

**Comment by alandekok** [comment]
That error comes from Daloradius, and has nothing to do with FreeRADIUS.

Please ask the daloradius people how their software works.
