### ISSUE TITLE
Freeradius for device that need PEAP0 MSCHAPv2 authentication using TLS 1.0

### ISSUE THREAD

**Issue by anujgaba** [FreeRADIUS/freeradius-server#5334]
### Message

Attached configuration.
[eap.txt](https://github.com/user-attachments/files/15596369/eap.txt)
[openssl.txt](https://github.com/user-attachments/files/15596370/openssl.txt)

Getting this message-
(25) eap_peap: ERROR: (TLS) Alert write:fatal:internal error
(25) eap_peap: ERROR: (TLS) Server : Error in error
(25) eap_peap: ERROR: (TLS) Failed reading from OpenSSL: error:0A000076:SSL routines::no suitable signature algorithm
(25) eap_peap: ERROR: (TLS) System call (I/O) error (-1)
(25) eap_peap: ERROR: (TLS) EAP Receive handshake failed during operation
(25) eap_peap: ERROR: [eaptls process] = fail
(25) eap: ERROR: Failed continuing EAP PEAP (25) session.  EAP sub-module failed

Any help would be much appreciated.

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.  And it helps to read the documentation:  http://wiki.freeradius.org/list-help, and most specificially mods-available/eap.  This issue is addressed there.
