### ISSUE TITLE
[defect]: radclient return value incorrect when network unreachable

### ISSUE THREAD

**Issue by WhiteCat0214** [FreeRADIUS/freeradius-server#5338]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

Execute radclient at device which network unreachable. (Failed to send packet)
packet is not send but return value is 0 (success).

At end of radclient.c, it only verify stats.lost and stats.failed values.
`if ((stats.lost > 0) || (stats.failed > 0)) {
		exit(1);
	}
`
I think it's better to add a judgment when all values ​​​​are 0.
`if ((stats.lost > 0) || (stats.failed > 0) || (stats.accepted == 0 && stats.rejected == 0 && stats.lost == 0 && stats.passed == 0 && stats.failed == 0)) {
		exit(1);
	}
`

### Log output from the FreeRADIUS daemon

```shell
no matter
```

### Relevant log output from client utilities

root@Router:~# /usr/bin/radclient -sxF -n 1 -f /tmp/test -t 1 192.168.214.55:1812 auth testing123 && echo 1 || echo 0
(0) Failed to send packet for ID 85: sendto failed: Network unreachable
Packet summary:
        Accepted      : 0
        Rejected      : 0
        Lost          : 0
        Passed filter : 0
        Failed filter : 0
1

I except it will echo 0

### Backtrace from LLDB or GDB

```shell
no matter
```

**Comment by alandekok** [comment]
I've pushed a different fix.  Please verify.

**Comment by WhiteCat0214** [comment]
> I've pushed a different fix. Please verify.

root@TEW-929DRU:~# /usr/bin/radclient -sxF -n 1 -f /tmp/test -t 1 192.168.214.55
:1812 auth testing123 && echo 1 || echo 0
(0) Failed to send packet for ID 177: sendto failed: Network unreachable
Packet summary:
        Accepted      : 0
        Rejected      : 0
        Lost          : 1
        Passed filter : 0
        Failed filter : 0
0

It works, thanks!
