### ISSUE TITLE
Understand how to check client certificate for revocation

### ISSUE THREAD

**Issue by AndryAsh** [FreeRADIUS/freeradius-server#5364]
### Message

Hello, please help me to understand how to check client certificate for revocation:

Freeradius 3.0 is configured for authorization via EAP-TLS.
A self-signed CA certificate is created and server and user certificates are signed with it.
Authorization works successfully.
A list of revoked cert.crl certificates in DER format was created.
In the configuration of the eap module settings for sending a request to localhost are made:
``
ocsp {
	enable = yes
	url = "http://127.0.0.1/ocsp/"
}
``
We need to implement the OCSP server ourselves using the python cryptography library.
Help us to understand what request freeradius sends to OCSP server (headers, request body) and what response should be generated.
This information is not available in freeradius documentation.

**Comment by alandekok** [comment]
Questions belong on the freeradius-users list.
