### ISSUE TITLE
Build fails with parallel building

### ISSUE THREAD

**Issue by bernhardschmidt** [FreeRADIUS/freeradius-server#5365]
### Message

When you build the FreeRADIUS source in parallel (something the Debian buildsystem does automatically, and most likely other distributions as well) building sometimes (more often with a higher number of jobs) fails with

```
/<<PKGBUILDDIR>>/install-sh -c -m 644 man/man8/rlm_sqlippool_tool.8.subst debian/tmp/usr/share/man/man8/rlm_sqlippool_tool.8
gcc scripts//jlibtool.c -o build/make/jlibtool 
HEADER src/include/attributes.h
[...]
HEADER src/include/freeradius.h
INSTALL raddb/mods-config
INSTALL radsecret
build/make/jlibtool --silent --mode=install /<<PKGBUILDDIR>>/install-sh -c -c -m 755 /<<PKGBUILDDIR>>/src/main/radsecret debian/tmp//usr/bin/radsecret
make[2]: build/make/jlibtool: No such file or directory
make[2]: *** [src/main/radsecret.mk:5: debian/tmp//usr/bin/radsecret] Error 127
make[2]: *** Waiting for unfinished jobs....
```

Adding an echo to the place where jlibtool is built from

```
--- a/scripts/libtool.mk
+++ b/scripts/libtool.mk
@@ -50,6 +50,7 @@ ifeq "${LIBTOOL}" "JLIBTOOL"
        $(Q)mkdir -p $(dir $@)
        $(Q)echo CC jlibtool.c
        $(Q)${CC} $< -o $@ ${JLIBTOOL_DEFS}
+       $(Q)echo CC-DONE jlibtool.c

     clean: jlibtool_clean
```

shows that the compilation of libjtool indeed only finishes after the build system has already tried to use it

```
INSTALL raddb/mods-config
INSTALL radsecret
build/make/jlibtool --silent --mode=install /<<PKGBUILDDIR>>/install-sh -c -c -m 755 /<<PKGBUILDDIR>>/src/main/radsecret debian/tmp//usr/bin/radsecret
make[2]: build/make/jlibtool: No such file or directory
make[2]: *** [src/main/radsecret.mk:5: debian/tmp//usr/bin/radsecret] Error 127
make[2]: *** Waiting for unfinished jobs....
echo CC-DONE jlibtool.c
CC-DONE jlibtool.c
```

So the obvious fix would be to add a dependency on jlibtool, but I'm not exactly sure how to do that given that  jlibtool is only conditionally compiled. Also I don't know why radsecret is the only .mk in src/main using ${PROGRAM_INSTALL} instead of ${INSTALL}

**Comment by alandekok** [comment]
The parallel builds seem to be fine here, and in CI.

If the parallel build fails with `radsecret`, then the issue there is that it should use `INSTALL`, and not `PROGRAM_INSTALL`.

**Comment by bernhardschmidt** [comment]
It appears to be quite random. It never happened to me on my local machine except by artificially forcing the jobcount to be higher than the physical CPU count, nor in CI, but on the Debian buildds it broke on 10 out of 16 architectures.

https://buildd.debian.org/status/logs.php?pkg=freeradius&ver=3.2.5%2Bdfsg-1

Yeah I thought INSTALL instead of PROGRAM_INSTALL as well. I have patched this up and sent -2 to the buildds.

**Comment by alandekok** [comment]
is the build error _always_ with radsecret? If so, I've pushed a fix.

**Comment by bernhardschmidt** [comment]
Yes, it's always with radsecret, and the same fix like you did in https://github.com/FreeRADIUS/freeradius-server/commit/99402cfdee6cc974e46864a1469d33ae3bba1e77 made FreeRADIUS 3.2.5 build on all Debian architectures. So this can be considered fixed, thanks.
