### ISSUE TITLE
[defect]: installation issue ubuntu 22: libfreeradius4 : Depends: libkqueue (= 2.6.1.23) but it is not installable

### ISSUE THREAD

**Issue by fchen-vsat** [FreeRADIUS/freeradius-server#5395]
### What type of defect/bug is this?

Non compliance with a standards document

### How can the issue be reproduced?

I compiled the project master tip (022ff5c36ad25663ae4f491142b68a79895d5890) using ./scripts/docker/build/ubuntu22/Dockerfile.cb (with some additions, for copying out the images). When I try to install the first pkg, it emits errors below: 

> \# apt install ./libfreeradius4_4.0_amd64.deb
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Note, selecting 'libfreeradius4' instead of './libfreeradius4_4.0_amd64.deb'
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  libfreeradius4 : Depends: libkqueue (= 2.6.1.23) but it is not installable
> E: Unable to correct problems, you have held broken packages.

I cannot find libkqueue-2.6.1.23 anywhere. I downloaded a copy of libkqueue source code for release 2.6.1. Compiled, installed. Libfreeradius not happy about the version 2.6.1. I looked libkqueue source code. Versioning is a 3-number schema. Required 2.6.1.23 seems being a non-standard version. 

My question: what is a quick way to get a copy of libkqueue-2.6.1.23 or compile one?

### Log output from the FreeRADIUS daemon

```shell
n/a
```

### Relevant log output from client utilities

n/a

### Backtrace from LLDB or GDB

```shell
n/a
```

**Comment by ndptech** [comment]
The relevant packages for libkqueue are available on the Network RADIUS "extras" repo.

You will see in the Docker script you referenced:

```
#
#  Set up NetworkRADIUS extras repository
#
RUN install -d -o root -g root -m 0755 /etc/apt/keyrings && \
    wget -O /etc/apt/keyrings/packages.networkradius.com.asc "https://packages.networkradius.com/pgp/packages%40networkradius.com" && \
    echo "deb [signed-by=/etc/apt/keyrings/packages.networkradius.com.asc] http://packages.networkradius.com/extras/ubuntu/jammy jammy main" > /etc/apt/sources.list.d/networkradius-extras.l
ist && \
    apt-get update
```

Which gives the steps done in the Docker image to add the repo - just do the same without `RUN`
