### ISSUE TITLE
Is the FreeRADIUS Mailing List freeradius-users@lists.freeradius.org discontinued or broken?

### ISSUE THREAD

**Issue by vo-va** [FreeRADIUS/freeradius-server#5402]
### Message

Hi,

Is the mailing list still supported, or has it been discontinued or is something not working on the server side? I've tried to send an email to the mailing list, but it hasn't appeared on the archive page. The last email listed on the archive page is from July 24. If the mailing list has been discontinued, what would be the best place to ask questions about FreeRADIUS?

Thanks!

**Comment by mcnewton** [comment]
Server issues, it's back up now.

**Comment by rodrigoaantunes** [comment]
Is it up now?

**Comment by arr2036** [comment]
Haven't seen any traffic since 22/08/2024

**Comment by arr2036** [comment]
But some today... weirdly.
