### ISSUE TITLE
Failed binding to auth address 127.0.0.1 port 18120 bound to server inner-tunnel: Address already in use

### ISSUE THREAD

**Issue by Mamunahmedbd** [FreeRADIUS/freeradius-server#5409]
### Message

 I installed FreeRADIUS Version 3.2.3 on my Ubuntu server 24.04
 
 I have faced a problem which is Address already in use binding to port for 127.0.0.1 port 18120
I had many times freshly installed freeradius but can't pass this virtual server port binding error

Can anyone tell me where my wrong configuration?
 
 # server default
radiusd: #### Opening IP addresses and Ports ####
listen {
        type = "auth"
        ipaddr = 127.0.0.1
        port = 18120
Failed binding to auth address 127.0.0.1 port 18120 bound to server inner-tunnel: Address already in use
/etc/freeradius/3.0/sites-enabled/inner-tunnel[33]: Error binding to port for 127.0.0.1 port 18120

![image](https://github.com/user-attachments/assets/6bd96573-2969-4067-a702-1f5f9f9830de)

**Comment by alandekok** [comment]
`Address already in use` is pretty clear.

The instructions for github issues say that you should post configuration problems to the list, and not to github.

Please read the documentation.
