### ISSUE TITLE
Website Links Broken

### ISSUE THREAD

**Issue by neleknok** [FreeRADIUS/freeradius-server#5414]
### Message

Many areas of the website are displaying errors like this:

Error 503 Backend is unhealthy

Backend is unhealthy

Error 54113

Details: cache-dfw-kdal2120036-DFW [1725334421] [3363393888]

Varnish cache server

**Comment by arr2036** [comment]
Can you give an example? All the FreeRADIUS pages work fine for me.

**Comment by arr2036** [comment]
ok, so it's networkradius.com pages.  We'll take a look...

**Comment by arr2036** [comment]
Issue with backend not automatically renewing its cert.  Put in a workaround.  Thanks again for reporting this.
