### ISSUE TITLE
[defect]: Expired GPG Key

### ISSUE THREAD

**Issue by macmandr197** [FreeRADIUS/freeradius-server#5419]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

following instructions on the network radius website to install the repository on Ubuntu, the GPG cannot be used: EXPKEYSIG

### Log output from the FreeRADIUS daemon

```shell
N/A, app cannot be installed as the GPG key is expired.
```

**Comment by arr2036** [comment]
Seeing this in CI too

**Comment by arr2036** [comment]
@mcnewton

**Comment by simeononsecurity** [comment]
Saw this as well, still an issue.

**Comment by TheRealTripleB** [comment]
i have the same problem

**Comment by arr2036** [comment]
Our key master is aware, he'll be refreshing the keys today.

**Comment by mcnewton** [comment]
Expiry has been bumped - please refresh with updated key from https://packages.networkradius.com/pgp/packages%40networkradius.com
