### ISSUE TITLE
[defect]: [doc][unlang] behaviour of `&Attribute-Name[*] != "foo"` is unspecified in docs

### ISSUE THREAD

**Issue by filimonic** [FreeRADIUS/freeradius-server#5454]
### What type of defect/bug is this?

behaviour undocumented in documents

### Details

https://www.freeradius.org/radiusd/man/unlang.html

Currently, usage of `[*]` is very superficial: 

> If there is more than one instance of an attribute, the following syntax should be used:
>
>         (&Attribute-Name[*] == "foo")
> 
> Using the "[*]" syntax means that it checks all of the instances of the named attribute. If one attribute matches, the condition succeeds. If none match, the condition fails.

There are two ways of negating this condition: 

```
(&Attribute-Name[*] != "foo")
(!(&Attribute-Name[*] == "foo"))
```
It is unclear what `(&Attribute-Name[*] != "foo")` logically means: 
* If all of values mismatch then condition succeeds
* If any of values mismatches then condition succeeds

Possible usage in real-world: 

```
  post-auth {
    # Deny request if client certificate does not have EAPoL EKU
    if (&request:TLS-Client-Cert-X509v3-Extended-Key-Usage-OID[*] != "1.3.6.1.5.5.7.3.14") {
      update request {
        &Module-Failure-Message += 'Rejected: No EAPoL EKU'
      }
      reject
    }
```

**Comment by alandekok** [comment]
Internally, `(&Attribute-Name[*] != "foo")` is converted to `(!(&Attribute-Name[*] == "foo"))`, so they mean the same thing.

And then it is very clear as to what this means.
