### ISSUE TITLE
proxied reply without message-authenticator (but with proxy-state attribute) are passed to client

### ISSUE THREAD

**Issue by chiouss** [FreeRADIUS/freeradius-server#5464]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

I use FreeRADIUS 3.0.27, and I set `require_ma = false` but `limit_proxy_state = true` to make it compatiable to old RADIUS servers.

```
security {
  allow_core_dumps = yes
  max_attributes = 200
  reject_delay = 0
  status_server = yes
  require_message_authenticator = no
  limit_proxy_state = yes
  allow_vulnerable_openssl = no
}
```

but I found I can still receives response from proxied server:

```
(0) !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(0) BlastRADIUS check: Received packet without Message-Authenticator from home_server ext_portal_auth_2_1_1
(0) !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(0) The packet does not contain Message-Authenticator, which is a security issue
(0) UPGRADE THE HOME SERVER AS YOUR NETWORK IS VULNERABLE TO THE BLASTRADIUS ATTACK.
(0) Once the home server is upgraded, set "require_message_authenticator = true" for home_server ext_portal_auth_2_1_1
(0) !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(0) Marking home server 10.253.31.238 port 1812 alive
(0) Clearing existing &reply: attributes
(0) Received Access-Accept Id 65 from 10.253.31.238:1812 to 192.168.13.129:34181 length 87
(0)   Proxy-State = 0x3131
(0)   Filter-Id = "SVD"
(0)   Framed-Protocol = PPP
(0)   Service-Type = Framed-User
(0)   Class = 0xb30009820000013700011700fe80000000000000613141dbb939c4b201db364ac0674e430000000000000188
(0) server default {
(0) }
(0) Found Auth-Type = Accept
(0) Auth-Type = Accept, accepting the user
```

is this behavior intended or it is a bug?

### Log output from the FreeRADIUS daemon

```shell
(0) !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(0) BlastRADIUS check: Received packet without Message-Authenticator from home_server ext_portal_auth_2_1_1
(0) !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(0) The packet does not contain Message-Authenticator, which is a security issue
(0) UPGRADE THE HOME SERVER AS YOUR NETWORK IS VULNERABLE TO THE BLASTRADIUS ATTACK.
(0) Once the home server is upgraded, set "require_message_authenticator = true" for home_server ext_portal_auth_2_1_1
(0) !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(0) Marking home server 10.253.31.238 port 1812 alive
(0) Clearing existing &reply: attributes
(0) Received Access-Accept Id 65 from 10.253.31.238:1812 to 192.168.13.129:34181 length 87
(0)   Proxy-State = 0x3131
(0)   Filter-Id = "SVD"
(0)   Framed-Protocol = PPP
(0)   Service-Type = Framed-User
(0)   Class = 0xb30009820000013700011700fe80000000000000613141dbb939c4b201db364ac0674e430000000000000188
(0) server default {
(0) }
(0) Found Auth-Type = Accept
(0) Auth-Type = Accept, accepting the user
```
```


### Relevant log output from client utilities

_No response_

### Backtrace from LLDB or GDB

_No response_

**Comment by alandekok** [comment]
Please read the documentation for the `limit_proxy_state` configuration item.  The documentation says that it applies only to Access-Request packets from a client.  It doesn't apply to packets from home servers.

Or, read the BlastRADIUS paper which says that the `limit_proxy_state` only applies to packets from a client.  That paper also gives long and detailed reasons why this limitation is fine.

**Comment by alandekok** [comment]
The code is the same in both branches.  What is the problem?

When you set `require_message_authenticator=no` globally, then it doesn't require `Message-Authenticator` in replies from home servers.  Which is what the documentation says it does.  It also complains about it, as you see in the note above.

Setting `limit_proxy_state` has no effect on `Access-Accept` packets. 

Please explain what problem you see, and why you think the code or documentation is wrong.

**Comment by alandekok** [comment]
I get the impression that you aren't reading my replies.

> I get a non-EAP RADIUS auth reply packet (Access-Accept) I proxied from server that has proxy-state attribute but without message-authenticator attribute.

As I said, you set `require_message_authenticator = no`.  And I also said that `limit_proxy_state` doesn't apply to Access-Accept packets.

What part of this is unclear?

This packet shouldn't be dropped.

The documentation for `limit_proxy_state` is VERY clear that it applies to Access-Request packets.

My messages here are VERY VERY VERY VERY clear that `limit_proxy_state` doesn't apply to packets from home servers.

What part of this is unclear?

Why are you still arguing about this?

Since this message isn't getting across, I'll stop wasting my time here.
