### ISSUE TITLE
[defect]: Error: libssl version mismatch.  built: 30000070 linked: 30200020

### ISSUE THREAD

**Issue by cunliffe** [FreeRADIUS/freeradius-server#5469]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

Install the latest version of OpenSSL (3.2.2-6.el9_5) and Freeradius (3.2.6-1.el9).

### Log output from the FreeRADIUS daemon

```shell
radiusd -X
libssl version mismatch.  built: 30000070 linked: 30200020
```

### Backtrace from LLDB or GDB

```shell
Starting program: /usr/sbin/radiusd -fxx
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[Inferior 1 (process 35829) exited with code 01]
No threads.
```

**Comment by alandekok** [comment]
Duplicate.  See #5467
