### ISSUE TITLE
[defect]: FreeRADIUS 3.2.6 + ldap with windows dc, FreeRADIUS reject all request after dc server rebooted

### ISSUE THREAD

**Issue by david187** [FreeRADIUS/freeradius-server#5475]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

- FreeRADIUS + ldap (windows dc) is work fine
- reboot windows dc (server 2022)
- FreeRADIUS reject all radius request with

  ERROR: (8237185) mschap: ERROR: Program returned code (1) and output 'The attempted logon is invalid. This is either due to a bad username or authentication information. (0xc000006d)'

- reboot the freeradius VM
- everything work fine

### Log output from the FreeRADIUS daemon

```shell
-
```

### Relevant log output from client utilities

-

### Backtrace from LLDB or GDB

```shell
-
```

**Comment by alandekok** [comment]
1) this isn't a FreeRADIUS issue

2) the documentation you read when opening this report says that you should ask configuration questions on the mailing list.

i.e. you're running ntlm_auth, and ntlm_auth says that there's an issue.  We didn't write ntlm_auth, and we can't help debugging that issue.   Look at the Samba logs to see what's up.
