### ISSUE TITLE
Replace rlm_passwd with something better

### ISSUE THREAD

**Issue by alandekok** [FreeRADIUS/freeradius-server#584]
The code is pretty much impossible to maintain.

We should have a new "csv" or "map" module, which reads maps.

The input files could be pretty similar (e.g. /etc/passwd), but the configuration should be better.

Instead of passwd's weird  * = ~, etc. characters, we could just use value-pair templates.   e.g. control:Cleartext-Password.

The file would be parsed into templates, for later conversion to VALUE_PAIRs.

**Comment by arr2036** [comment]
@alandekok is that rlm_csv? :)

**Comment by alandekok** [comment]
Mostly.  rlm_csv doesn't do /etc/group files.  But it does everything else.

    foo,bar,baz

works

    foo:bar:baz,baz1,baz2,baz3

doesn't work.  It probably shouldn't, TBH.  We could re-implement it via a "split" command, and a map. :)
