### ISSUE TITLE
Crash when receiving conflicting DHCP packets (when calling vmodule_failure_msg)

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#798]
FreeRADIUS crashes when receiving conflicting DHCP packets, ie:
- same source IP and port, same destination IP and port, and same xid
- but a different vector (for DHCP this is the MAC address + the opcode)

The crash occurs when function "request_done" calls "radlog_request_error".

The following call causes the crash (doesn't crash anymore when I comment this out):

		RERROR("Received conflicting packet from "
			       "client %s port %d - ID: %u due to "
			       "unfinished request.  Giving up on old request.",
			       request->client->shortname,
			       request->packet->src_port, request->packet->id);

And more precisely, it doesn't crash when I comment out the following line from function "radlog_request_error" (log.c)

	//vmodule_failure_msg(request, msg, ap);

See backtrace below:

	Thread 18 (Thread 0x7f9109f02700 (LWP 30719)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc646e0) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc646e0
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 17 (Thread 0x7f9109501700 (LWP 30720)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc64880) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc64880
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 16 (Thread 0x7f9108b00700 (LWP 30721)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc64a20) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc64a20
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 15 (Thread 0x7f91080ff700 (LWP 30722)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc64bc0) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc64bc0
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 14 (Thread 0x7f91076fe700 (LWP 30723)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc64d60) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc64d60
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 13 (Thread 0x7f9106af3700 (LWP 30724)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc6b450) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc6b450
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 12 (Thread 0x7f91060f2700 (LWP 30725)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc6b5f0) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc6b5f0
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 11 (Thread 0x7f91056f1700 (LWP 30726)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc6b790) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc6b790
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 10 (Thread 0x7f9104cf0700 (LWP 30727)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc6cb50) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc6cb50
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 9 (Thread 0x7f90e7fff700 (LWP 30728)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc6e1b0) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc6e1b0
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 8 (Thread 0x7f90e75fe700 (LWP 30729)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc6e1f0) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc6e1f0
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 7 (Thread 0x7f90e6bfd700 (LWP 30730)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc72430) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc72430
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 6 (Thread 0x7f90e61fc700 (LWP 30731)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc73a90) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc73a90
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 5 (Thread 0x7f90e57fb700 (LWP 30732)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc6e320) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc6e320
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 4 (Thread 0x7f90e4dfa700 (LWP 30733)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc7f9b0) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc7f9b0
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 3 (Thread 0x7f90c7fff700 (LWP 30734)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc7e950) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc7e950
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 2 (Thread 0x7f90c75fe700 (LWP 30735)):
	#0  0x00000030fcc0d720 in sem_wait () from /lib64/libpthread.so.0
	No symbol table info available.
	#1  0x0000000000431c61 in request_handler_thread (arg=0xc7ff50) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/threads.c:609
			self = 0xc7ff50
	#2  0x00000030fcc07851 in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#3  0x00000030fc4e890d in clone () from /lib64/libc.so.6
	No symbol table info available.

	Thread 1 (Thread 0x7f910fd017e0 (LWP 30718)):
	#0  0x00000030fc4ac7ad in waitpid () from /lib64/libc.so.6
	No symbol table info available.
	#1  0x00000030fc43e889 in do_system () from /lib64/libc.so.6
	No symbol table info available.
	#2  0x00000030fc43ebc0 in system () from /lib64/libc.so.6
	No symbol table info available.
	#3  0x00007f9110136ebc in fr_fault (sig=6) at /home/admwpdhcp/freeradius-server-3.0.x/src/lib/debug.c:646
			disable = false
			cmd = "gdb -silent -x /opt/application/mwpdhcp/products/freeradius/3.0.x-NCH/etc/raddb/panic.gdb /opt/application/mwpdhcp/products/freeradius/3.0.x-NCH/sbin/radiusd 30718 2>&1 | tee /opt/application/mwpdhcp/"...
			out = 0x7fff87a16266 ".log"
			left = 270
			ret = 99
			p = 0x7f911036c9c0 ".log"
			q = 0x0
			code = 48
	#4  0x00007f9110136fa9 in _fr_talloc_fault (reason=0x7f910fd13378 "Bad talloc magic value - unknown value") at /home/admwpdhcp/freeradius-server-3.0.x/src/lib/debug.c:682
	No locals.
	#5  0x00007f910fd0ddf1 in talloc_get_name () from /usr/lib64/libtalloc.so.2
	No symbol table info available.
	#6  0x00007f910fd107eb in _talloc_get_type_abort () from /usr/lib64/libtalloc.so.2
	No symbol table info available.
	#7  0x00007f9110137748 in fr_verify_vp (file=0x7f9110163ec0 "/home/admwpdhcp/freeradius-server-3.0.x/src/lib/valuepair.c", line=302, vp=0x7f9100002970) at /home/admwpdhcp/freeradius-server-3.0.x/src/lib/debug.c:945
	No locals.
	#8  0x00007f911015362f in pairadd (first=0xc92a78, add=0xc978f0) at /home/admwpdhcp/freeradius-server-3.0.x/src/lib/valuepair.c:302
			i = 0x7f9100002970
	#9  0x00007f9110156323 in pairmake (ctx=0xc92a00, vps=0xc92a78, attribute=0x7f911039951b "Module-Failure-Message", value=0x0, op=T_OP_ADD) at /home/admwpdhcp/freeradius-server-3.0.x/src/lib/valuepair.c:1890
			da = 0xab84e0
			vp = 0xc978f0
			tc = 0x7fff87a16848 "\222\260\070\020\221\177"
			ts = 0x0
			tag = -128 '\200'
			found_tag = false
			buffer = "\000\000\000\000\004", '\000' <repeats 35 times>, "^\231G\374\060", '\000' <repeats 35 times>"\377, \377\377\377\000\000\000\000\003", '\000' <repeats 15 times>, "@\304x\374\060", '\000' <repeats 27 times>, "\r\000\000\000\063\000\000\000[\000\000\000|\000\000\000w\000\000\000n", '\000' <repeats 11 times>"\340, f\241\207\377\177\000\000\304\000\000\000\000\000\000\000\200\356x\374\060\000\000\000t\000\000\000\000\000\000\000\340f\241\207\377\177\000\000\240\203\311\000\000\000\000\000\360\203\311\000\000\000\000\000t", '\000' <repeats 15 times>, "h\345E\000\000\000\000\000\067\005\321\017\221\177\000"
			attrname = 0x7f911039951b "Module-Failure-Message"
	#10 0x00007f911038c6ac in vmodule_failure_msg (request=0xc93100, fmt=0x45e568 "Received conflicting packet from client %s port %d - ID: %u due to unfinished request.  Giving up on old request.", ap=0x7fff87a16750) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/valuepair.c:798
			p = 0xc983f0 "Received conflicting packet from client dhcp port 67 - ID: 48 due to unfinished request.  Giving up on old request."
			vp = 0x30fc478d5e
			aq = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fff87a16840, reg_save_area = 0x7fff87a16770}}
	#11 0x00007f911038128a in radlog_request_error (type=L_DBG_ERR, lvl=L_DBG_LVL_OFF, request=0xc93100, msg=0x45e568 "Received conflicting packet from client %s port %d - ID: %u due to unfinished request.  Giving up on old request.") at /home/admwpdhcp/freeradius-server-3.0.x/src/main/log.c:752
			ap = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fff87a16840, reg_save_area = 0x7fff87a16770}}
	#12 0x00000000004346e2 in request_done (request=0xc93100, action=4) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/process.c:565
			now = {tv_sec = 13100960, tv_usec = 4406287}
			when = {tv_sec = 13201296, tv_usec = 13100960}
			buffer = "\200\356x\374\060\000\000\000\220?\310\000\000\000\000\000\330\356x\374\060\000\000\000\301\243G\374\060\000\000\000\360\360\307\000\000\000\000\000)\b\321\017\221\177\000\000\300h\241\207\377\177\000\000\303\001\000\000\000\000\000\000\t\000\000\000\377\177\000\000\002", '\000' <repeats 15 times>"\260, ", '\000' <repeats 31 times>, "\t\000\000\000\062\000\000"
			__FUNCTION__ = "request_done"
	#13 0x0000000000435b18 in request_common (request=0xc93100, action=4) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/process.c:1118
			buffer = "\002\000\000C\n\243خ\000\000\000\000\000\000\000\000\200i\241\207\377\177\000\000ό\025\020\221\177\000\000\b1\311\000\000\000\000\000\360i\241\207\377\177\000\000\360i\241\207\377\177\000\000\b1\311\000\000\000\000\000\260i\241\207\377\177\000\000\212\371\024\020\221\177\000\000\360i\241\207\377\177\000\000\260\070\305\000\000\000\000\000\200\063\311\000\000\000\000\000P\344\224\000\000\000\000\000\340i\241\207\377\177\000\000#\372\024\020\221\177\000"
			__FUNCTION__ = "request_common"
	#14 0x00000000004367bf in request_running (request=0xc93100, action=4) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/process.c:1466
			__FUNCTION__ = "request_running"
	#15 0x0000000000436c74 in request_receive (listener=0xc65640, packet=0xc97cf0, client=0xc65880, fun=0x7f9106af67e2 <dhcp_process>) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/process.c:1641
			count = 805306368
			packet_p = 0xc93108
			request = 0xc93100
			now = {tv_sec = 1411051532, tv_usec = 926537}
			sock = 0xc65760
	#16 0x00007f9106af770c in dhcp_socket_recv (listener=0xc65640) at /home/admwpdhcp/freeradius-server-3.0.x/src/modules/proto_dhcp/dhcpd.c:700
			packet = 0xc97cf0
			sock = 0xc65760
	#17 0x000000000043d2a0 in event_socket_handler (xel=0x94e450, fd=19, ctx=0xc65640) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/process.c:4081
			listener = 0xc65640
	#18 0x00007f911015aa4f in fr_event_loop (el=0x94e450) at /home/admwpdhcp/freeradius-server-3.0.x/src/lib/event.c:494
			ef = 0x94e4a0
			i = 1
			rcode = 1
			maxfd = 20
			when = {tv_sec = 1411051533, tv_usec = 249582}
			wake = 0x7fff87a16d30
			read_fds = {fds_bits = {524288, 0 <repeats 15 times>}}
			master_fds = {fds_bits = {1638400, 0 <repeats 15 times>}}
	#19 0x000000000043ec65 in radius_event_process () at /home/admwpdhcp/freeradius-server-3.0.x/src/main/process.c:4986
	No locals.
	#20 0x000000000042aef6 in main (argc=1, argv=0x7fff87a16ef8) at /home/admwpdhcp/freeradius-server-3.0.x/src/main/radiusd.c:582
			rcode = 0
			status = 1
			argval = -1
			spawn_flag = true
			write_pid = true
			display_version = false
			flag = 0
			from_child = {16, 17}
			autofree = 0x932060
	A debugging session is active.

**Comment by alandekok** [comment]
I've pushed a fix for this today.  I've been working off-line with some other people to reproduce this.

See commit 846f3365e.
