### ISSUE TITLE
clients not picked up correctly from SQL

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#840]
hi,

2.2.6 - clients in DB - not picked up (though debug shows them being added) - come up as unknown client

all working okay in 2.2.4  (looks like it might be a 2.2.5 change actually...) 

also, if there is a duplicate on disk and DB, 2.2.4 errors, 2.2.6 allows this to happen and dosnt complain (noted when degrading to 2.2.4) - is this related to 'can have duplicate clients but for different virtual servers' feature change?)

alan

**Comment by alandekok** [comment]
Unless I see more information, I'm going to close this as a configuration mistake.
