### ISSUE TITLE
Please update Debian logrotate file

### ISSUE THREAD

**Issue by Obramko** [FreeRADIUS/freeradius-server#846]
Please update Debian logrotate (debian/freeradius.logrotate) file as it does not contains HUP/reload and sometimes causes logging issues.

Upstream Debian logrotate entry is:
```
/var/log/freeradius/*.log {
        weekly
        rotate 52
        compress
        delaycompress
        notifempty
        missingok
        postrotate
                /etc/init.d/freeradius reload > /dev/null
        endscript
}
```

**Comment by alandekok** [comment]
For v2, this is better done via "radmin hup main.log", and the control socket.  Sending the entire server a HUP signal is not recommended.

The control socket should also be enabled by default, which isn't currently done.

**Comment by arr2036** [comment]
Nope, it's best done by the copytruncate option in logrotated.

```
      copytruncate
              Truncate  the  original log file to zero size in place after creating a copy, instead of moving the old
              log file and optionally creating a new one.  It can be used when some program cannot be told  to  close
              its  logfile  and  thus might continue writing (appending) to the previous log file forever.  Note that
              there is a very small time slice between copying the file and truncating it, so some logging data might
              be lost.  When this option is used, the create option will have no effect, as the old log file stays in
              place.
```

**Comment by arr2036** [comment]
I'm not sure when this option was introduced, but it's the best way to deal with this now.

**Comment by Lantizia** [comment]
Hi,

We've experienced problems with the logrotate file provided by debian 7 for freeradius (by default it looks exactly like the one Obramko posted above)... basically we found every Sunday 6:25am it'll reload the modules and then the process just dies.

If there is a new option - does anyone know where I can get a replacement, more sensible logrotate file?  At the moment I've just replaced reload with restart.

Steven

**Comment by alanbuxey** [comment]
as per the closure of this case, use copytruncate in the logrotate file   -
i too wonder when this option appeared as it really does sort out the
classic issue

**Comment by arr2036** [comment]
Been there since 2010 at least. That's the earliest i've found references to it.

**Comment by Lantizia** [comment]
Well I could have gone for...
https://github.com/FreeRADIUS/freeradius-server/blob/master/scripts/logrotate/freeradius
or...
https://github.com/FreeRADIUS/freeradius-server/blob/master/debian/freeradius.logrotate

In the end I've just removed postrotate and endscript lines from the file I already have just replaced it with copytruncate.

Hopefully we'll soon find out if that is sufficient, it's odd Debian haven't seen the updated method.
