### ISSUE TITLE
pam_radius configure fails on modern solaris

### ISSUE THREAD

**Issue by tsoome** [FreeRADIUS/freeradius-server#872]
hi!

modern solaris needs security/pam_appl.h included to use pam_modules.h, so the configure.ac needs update like:
```
AC_CHECK_HEADERS(security/pam_modules.h pam/pam_modules.h, [], [],
  [
    #ifdef HAVE_SECURITY_PAM_APPL_H
    #  include <security/pam_appl.h>
    #endif
  ]
)
```

**Comment by arr2036** [comment]
So you want the configuration check for pam_appl.h to fail if ```HAVE_SECURITY_PAM_APPL_H``` is defined?

**Comment by arr2036** [comment]
Ah no, you just don't know how to use github formatting... ok

**Comment by tsoome** [comment]
um, i just did copy/paste from my update and did not think it was needing some formatting;) and no, the issue is that to check pam_modules.h, you need to include pam_appl.h, as pam_handle_t is defined in pam_appl.h
