### ISSUE TITLE
acctsessionid

### ISSUE THREAD

**Issue by arielrovito** [FreeRADIUS/freeradius-server#874]
Hi, i have a problem with acctsessionid, i create one table with resulset of radacct and two servers using a acctsessionid identicaly. 
this a normal error ? example: (the first col is my col, in radacct2, a copy of radacct more col identity)
'1', '4931990', '81a09556', '60412447c5f4cc7f', 'adsl-gargiulon', '', '', '181.192.0.137', '231', 'Ethernet', '2015-01-14 09:57:43', NULL, '0', 'RADIUS', '', '', '0', '0', 'PPPoE_3_231', 'A0:F3:C1:06:35:75', '', 'Framed-User', 'PPP', '181.192.16.232', '0', '0', ''
'2', '4905286', '81a09556', '24737b1c2bccf4a3', 'adsl-rojash', '', '', '181.192.0.138', '251', 'Ethernet', '2015-01-13 07:45:42', NULL, '0', 'RADIUS', '', '', '0', '0', 'PPPoE_4_251', '4C:09:B4:A1:C4:07', '', 'Framed-User', 'PPP', '181.192.11.166', '0', '0', ''
'3', '4906440', '81a0966d', '744012ed33656bdf', 'adsl-hcarretto', '', '', '181.192.0.138', '102', 'Ethernet', '2015-01-13 08:39:37', NULL, '0', 'RADIUS', '', '', '0', '0', 'PPPoE_4_102', '20:89:86:99:70:64', '', 'Framed-User', 'PPP', '181.192.11.237', '0', '0', ''
'4', '4933369', '81a0966d', '66258b36ee604724', 'adsl-reyesm', '', '', '181.192.0.137', '201', 'Ethernet', '2015-01-14 11:07:48', NULL, '0', 'RADIUS', '', '', '0', '0', 'PPPoE_3_201', '00:0E:50:E3:69:97', '', 'Framed-User', 'PPP', '181.192.22.67', '0', '0', ''
'8', '4906583', '81a09693', '7c64472cd381eba6', 'adsl-dboan', '', '', '181.192.0.138', '102', 'Ethernet', '2015-01-13 08:45:32', NULL, '0', 'RADIUS', '', '', '0', '0', 'PPPoE_4_102', 'C8:D5:FE:32:E5:8A', '', 'Framed-User', 'PPP', '181.192.11.25', '0', '0', ''
'9', '4933591', '81a09693', '54ce69cdc8950ed0', 'adsl-jaimehugo', '', '', '181.192.0.137', '103', 'Ethernet', '2015-01-14 11:19:17', NULL, '0', 'RADIUS', '', '', '0', '0', 'PPPoE_3_103', '00:18:02:5E:46:72', '', 'Framed-User', 'PPP', '172.23.1.171', '0', '0', ''

thanks for you attention

**Comment by alandekok** [comment]
This isn't the place to ask for help.  Please ask questions on the freeradius-users mailing list.
