### ISSUE TITLE
freeradius 2.2.6 fails to compile from source on cygwin

### ISSUE THREAD

**Issue by avivs-at-arx** [FreeRADIUS/freeradius-server#875]
This file fails to compile:
C:\cygwin\home\avivs\FreeRadius\freeradius-server-2.2.6\src\modules\rlm_eap\radeapclient.c
1. the included files 
#include "eap_types.h"
#include "eap_sim.h"

not found by gcc. So I changed to 

#include "modules/rlm_eap/libeap/eap_types.h"
#include "modules/rlm_eap/libeap/eap_sim.h"

and got :

gcc -I/home/avivs/FreeRadius/freeradius-server-2.2.6 -I/home/avivs/FreeRadius/freeradius-server-2.2.6/src -g -O2 -Wall -D_GNU_SOURCE -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -DNDEBUG -I/home/avivs/FreeRadius/freeradius-server-2.2.6/libltdl -I/home/avivs/FreeRadius/freeradius-server-2.2.6/src -I/home/avivs/FreeRadius/freeradius-server-2.2.6/libltdl -DOPENSSL_NO_KRB5   radeapclient.c   -o radeapclient
radeapclient.c: In function ‘respond_eap_md5’:
radeapclient.c:776:11: warning: variable ‘name’ set but not used [-Wunused-but-set-variable]
  uint8_t *name;
           ^
radeapclient.c:773:20: warning: variable ‘namesize’ set but not used [-Wunused-but-set-variable]
  size_t valuesize, namesize;
                    ^
radeapclient.c: In function ‘main’:
radeapclient.c:978:6: warning: variable ‘count’ set but not used [-Wunused-but-set-variable]
  int count = 1;
      ^
/tmp/ccdKREvq.o: In function `debug_packet':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:182: undefined reference to `fr_packet_codes'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:195: undefined reference to `vp_prints'
/tmp/ccdKREvq.o: In function `cleanresp':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:300: undefined reference to `pairdelete'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:301: undefined reference to `pairdelete'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:314: undefined reference to `pairbasicfree'
/tmp/ccdKREvq.o: In function `process_eap_start':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:337: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:396: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:397: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:398: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:413: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:415: undefined reference to `pairreplace'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:418: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:423: undefined reference to `pairreplace'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:435: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:441: undefined reference to `fr_rand'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:442: undefined reference to `fr_rand'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:443: undefined reference to `fr_rand'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:444: undefined reference to `fr_rand'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:446: undefined reference to `pairreplace'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:458: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:464: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:472: undefined reference to `pairreplace'
/tmp/ccdKREvq.o: In function `main':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:983: undefined reference to `fr_debug_flag'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1012: undefined reference to `fr_debug_flag'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1090: undefined reference to `dict_init'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1095: undefined reference to `rad_alloc'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1148: undefined reference to `ip_hton'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1221: undefined reference to `pairfree'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1223: undefined reference to `readvp2'
/tmp/ccdKREvq.o: In function `sendrecv_eap':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:851: undefined reference to `pairfind'
/tmp/ccdKREvq.o: In function `map_eap_types':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1257: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1264: undefined reference to `pairfind'
/tmp/ccdKREvq.o: In function `sendrecv_eap':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:912: undefined reference to `fr_md5_calc'
/tmp/ccdKREvq.o: In function `send_packet':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:212: undefined reference to `rad_send'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:268: undefined reference to `rad_verify'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:273: undefined reference to `rad_decode'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:279: undefined reference to `fr_debug_flag'
/tmp/ccdKREvq.o: In function `unmap_eap_types':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1331: undefined reference to `eap_vp2packet'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1337: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1339: undefined reference to `pairadd'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1341: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1343: undefined reference to `pairadd'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1380: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1383: undefined reference to `pairadd'
/tmp/ccdKREvq.o: In function `respond_eap_sim':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:673: undefined reference to `paircopy2'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:678: undefined reference to `paircopy2'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:687: undefined reference to `pairfind'
/tmp/ccdKREvq.o: In function `unmap_eapsim_types':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1410: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1416: undefined reference to `unmap_eapsim_basictypes'
/tmp/ccdKREvq.o: In function `respond_eap_sim':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:701: undefined reference to `pairfind'
/tmp/ccdKREvq.o: In function `process_eap_challenge':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:502: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:503: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:521: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:522: undefined reference to `pairfind'
/tmp/ccdKREvq.o:/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:523: more undefined references to `pairfind' follow
/tmp/ccdKREvq.o: In function `respond_eap_sim':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:721: undefined reference to `sim_subtype2name'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:741: undefined reference to `sim_state2name'
/tmp/ccdKREvq.o: In function `respond_eap_md5':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:782: undefined reference to `paircopy2'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:788: undefined reference to `paircopy2'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:795: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:819: undefined reference to `fr_MD5Init'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:820: undefined reference to `fr_MD5Update'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:821: undefined reference to `fr_MD5Update'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:822: undefined reference to `fr_MD5Update'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:823: undefined reference to `fr_MD5Final'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:825: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:830: undefined reference to `pairreplace'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:832: undefined reference to `pairreplace'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:835: undefined reference to `pairreplace'
/tmp/ccdKREvq.o: In function `respond_eap_sim':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:757: undefined reference to `pairreplace'
/tmp/ccdKREvq.o: In function `map_eapsim_types':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1397: undefined reference to `map_eapsim_basictypes'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1401: undefined reference to `eap_basic_compose'
/tmp/ccdKREvq.o: In function `respond_eap_sim':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:763: undefined reference to `pairreplace'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:751: undefined reference to `sim_state2name'
/tmp/ccdKREvq.o: In function `send_packet':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:226: undefined reference to `rad_recv'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:242: undefined reference to `ip_ntoh'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:243: undefined reference to `ip_ntoh'
/tmp/ccdKREvq.o: In function `map_eap_types':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1306: undefined reference to `pairdelete'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1315: undefined reference to `eap_basic_compose'
/tmp/ccdKREvq.o: In function `respond_eap_sim':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:741: undefined reference to `sim_subtype2name'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:690: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:692: undefined reference to `pairreplace'
/tmp/ccdKREvq.o: In function `sendrecv_eap':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:916: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:854: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:859: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:920: undefined reference to `pairfind'
/tmp/ccdKREvq.o: In function `main':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1148: undefined reference to `ip_hton'
/tmp/ccdKREvq.o: In function `process_eap_challenge':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:574: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:575: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:576: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:588: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:589: undefined reference to `pairfind'
/tmp/ccdKREvq.o:/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:590: more undefined references to `pairfind' follow
/tmp/ccdKREvq.o: In function `process_eap_challenge':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:603: undefined reference to `eapsim_calculate_keys'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:610: undefined reference to `eapsim_checkmac'
/tmp/ccdKREvq.o: In function `main':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1091: undefined reference to `fr_perror'
/tmp/ccdKREvq.o: In function `process_eap_challenge':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:635: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:637: undefined reference to `pairreplace'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:643: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:649: undefined reference to `pairreplace'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:651: undefined reference to `paircreate'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:654: undefined reference to `pairreplace'
/tmp/ccdKREvq.o: In function `sendrecv_eap':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:924: undefined reference to `pairfind'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:928: undefined reference to `rad_chap_encode'
/tmp/ccdKREvq.o: In function `send_packet':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:274: undefined reference to `fr_perror'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:269: undefined reference to `fr_perror'
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:251: undefined reference to `fr_perror'
/tmp/ccdKREvq.o: In function `main':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:1096: undefined reference to `fr_perror'
/tmp/ccdKREvq.o: In function `process_eap_challenge':
/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap/radeapclient.c:606: undefined reference to `eapsim_dump_mk'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'radeapclient' failed
make[6]: *** [radeapclient] Error 1
make[6]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_eap'
Makefile:37: recipe for target 'rlm_eap' failed
make[5]: *** [rlm_eap] Error 2
make[5]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules'
Makefile:12: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules'
Makefile:39: recipe for target 'modules' failed
make[3]: *** [modules] Error 2
make[3]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src'
Makefile:14: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src'
Makefile:97: recipe for target 'src' failed
make[1]: *** [src] Error 2
make[1]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6'
Makefile:18: recipe for target 'all' failed
make: *** [all] Error 2

avivs@AVIVS-PC ~/FreeRadius/freeradius-server-2.2.6
$

Please help.

I am compiling on winndows 7 64bit machine,

Thanks in advance,

Aviv Simionovici, ARX

**Comment by alandekok** [comment]
It looks like the build is completely broken on cygwin.  I have no idea why, as I don't use cygwin.

**Comment by avivs-at-arx** [comment]
its not entirely broken - some files get compiled.

Anybody with cygwin experience?

I need to run my Radius Server from windows since I want to extend it with existing functionality that is available only in some windows dlls. porting them to Linux is not an option.

thanks again,

Aviv

**Comment by spaetow** [comment]
At some point I might look at it. :-)

**Comment by alandekok** [comment]
Hmm... it looks like the Makefile could use a minor tweak.  Edit src/modules/rlm_eap/Makefile, and change:

    RLM_UTILS   = radeapclient

to

    RLM_UTILS   = radeapclient$(EXEEXT)

That should fix it.

**Comment by avivs-at-arx** [comment]
Thanks!!! 

I also made the same trick at src\modules\rlm_ippool\Makefile:

#RLM_UTILS   = rlm_ippool_tool
RLM_UTILS   = rlm_ippool_tool$(EXEEXT)

 it helped but now I have this one:

make[6]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_passwd'
Making all in rlm_perl...
/usr/bin/make -w -C rlm_perl all
make[6]: Entering directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_perl'
/home/avivs/FreeRadius/freeradius-server-2.2.6/libtool --mode=compile --tag=CC gcc -I/home/avivs/FreeRadius/freeradius-server-2.2.6 -I/home/avivs/FreeRadius/freeradius-server-2.2.6/src -g -O2 -Wall -D_GNU_SOURCE -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -DNDEBUG -I/home/avivs/FreeRadius/freeradius-server-2.2.6/libltdl -I/home/avivs/FreeRadius/freeradius-server-2.2.6/src -I/home/avivs/FreeRadius/freeradius-server-2.2.6/libltdl `perl -MExtUtils::Embed -e ccopts` -c rlm_perl.c
mkdir .libs
 gcc -I/home/avivs/FreeRadius/freeradius-server-2.2.6 -I/home/avivs/FreeRadius/freeradius-server-2.2.6/src -g -O2 -Wall -D_GNU_SOURCE -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -DNDEBUG -I/home/avivs/FreeRadius/freeradius-server-2.2.6/libltdl -I/home/avivs/FreeRadius/freeradius-server-2.2.6/src -I/home/avivs/FreeRadius/freeradius-server-2.2.6/libltdl -DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -g -fno-strict-aliasing -pipe -fstack-protector -I/usr/lib/perl5/5.14/i686-cygwin-threads-64int/CORE -c rlm_perl.c  -DDLL_EXPORT -DPIC -o .libs/rlm_perl.o
rlm_perl.c: In function 'rlm_perl_get_handles':
rlm_perl.c:172:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   handle = (void *)SvIV(handle_sv);
            ^
rlm_perl.c: In function 'rlm_perl_make_key':
rlm_perl.c:243:26: warning: passing argument 2 of 'pthread_key_create' from incompatible pointer type
  pthread_key_create(key, rlm_destroy_perl);
                          ^
In file included from /home/avivs/FreeRadius/freeradius-server-2.2.6/src/freeradius-devel/radiusd.h:39:0,
                 from rlm_perl.c:27:
/usr/include/pthread.h:145:5: note: expected 'void (*)(void *)' but argument is of type 'void (*)(struct PerlInterpreter *)'
 int pthread_key_create (pthread_key_t *, void (*)(void *));
     ^
In file included from rlm_perl.c:40:0:
rlm_perl.c: At top level:
rlm_perl.c:282:11: error: external linkage required for symbol 'XS_radiusd_radlog' because of 'dllexport' attribute
 static XS(XS_radiusd_radlog)
           ^
/usr/lib/perl5/5.14/i686-cygwin-threads-64int/CORE/XSUB.h:110:28: note: in definition of macro 'XSPROTO'
 #define XSPROTO(name) void name(pTHX_ CV* cv)
                            ^
rlm_perl.c:282:8: note: in expansion of macro 'XS'
 static XS(XS_radiusd_radlog)
        ^
rlm_perl.c: In function 'perl_instantiate':
rlm_perl.c:411:7: warning: variable 'rad_request_proxy_reply_hv' set but not used [-Wunused-but-set-variable]
  HV  *rad_request_proxy_reply_hv;
       ^
rlm_perl.c:410:7: warning: variable 'rad_request_proxy_hv' set but not used [-Wunused-but-set-variable]
  HV  *rad_request_proxy_hv;
       ^
rlm_perl.c:409:7: warning: variable 'rad_request_hv' set but not used [-Wunused-but-set-variable]
  HV  *rad_request_hv;
       ^
rlm_perl.c:408:7: warning: variable 'rad_config_hv' set but not used [-Wunused-but-set-variable]
  HV  *rad_config_hv;
       ^
rlm_perl.c:407:7: warning: variable 'rad_check_hv' set but not used [-Wunused-but-set-variable]
  HV  *rad_check_hv;
       ^
rlm_perl.c:406:7: warning: variable 'rad_reply_hv' set but not used [-Wunused-but-set-variable]
  HV  *rad_reply_hv;
       ^
rlm_perl.c: In function 'perl_store_vps':
rlm_perl.c:553:8: warning: assignment discards 'const' qualifier from pointer target type
   name = nvp->name;
        ^
In file included from /usr/lib/perl5/5.14/i686-cygwin-threads-64int/CORE/perl.h:5022:0,
                 from rlm_perl.c:39:
rlm_perl.c: In function 'rlmperl_call':
/usr/lib/perl5/5.14/i686-cygwin-threads-64int/CORE/pp.h:125:16: warning: value computed is not used [-Wunused-value]
 #define POPs  (*sp--)
                ^
rlm_perl.c:738:3: note: in expansion of macro 'POPs'
   POPs;
   ^
../rules.mak:66: recipe for target 'rlm_perl.lo' failed
make[6]: *** [rlm_perl.lo] Error 1
make[6]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules/rlm_perl'
Makefile:37: recipe for target 'rlm_perl' failed
make[5]: *** [rlm_perl] Error 2
make[5]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules'
Makefile:12: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src/modules'
Makefile:39: recipe for target 'modules' failed
make[3]: *** [modules] Error 2
make[3]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src'
Makefile:14: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6/src'
Makefile:97: recipe for target 'src' failed
make[1]: *** [src] Error 2
make[1]: Leaving directory '/home/avivs/FreeRadius/freeradius-server-2.2.6'
Makefile:18: recipe for target 'all' failed
make: *** [all] Error 2

avivs@AVIVS-PC ~/FreeRadius/freeradius-server-2.2.6
$ ^C

avivs@AVIVS-PC ~/FreeRadius/freeradius-server-2.2.6
$

can you help me with this (I think the error is here)

In file included from rlm_perl.c:40:0:
rlm_perl.c: At top level:
rlm_perl.c:282:11: error: external linkage required for symbol 'XS_radiusd_radlog' because of 'dllexport' attribute
 static XS(XS_radiusd_radlog)

thanks again,

Aviv

**Comment by alandekok** [comment]
If you don't use rlm_perl, just delete the directory src/modules/rlm_perl.  It's not required by the server for anything.

**Comment by avivs-at-arx** [comment]
Thanks, 
I removed the rlm_perl and I manged to finish make & make_install successfully.
Perhaps you will consider to change the makefile, so users will be able to compile out of the box without the above modifications.
Thanks again,
Aviv

**Comment by arr2036** [comment]
No, of course not. We're not going to prevent rlm_perl from compiling just to mask an error when building under cygwin.

**Comment by avivs-at-arx** [comment]
Ok,

I understand, but what about Makefiles errors such as:

#RLM_UTILS = rlm_ippool_tool
RLM_UTILS = rlm_ippool_tool$(EXEEXT)

I am not familiar with Makefile language but I would expect that 'make' will work in cygwin 'out of the box'.

Thanks,

Aviv

**Comment by arr2036** [comment]
The error is:

```
^
In file included from rlm_perl.c:40:0:
rlm_perl.c: At top level:
rlm_perl.c:282:11: error: external linkage required for symbol 'XS_radiusd_radlog' because of 'dllexport' attribute
static XS(XS_radiusd_radlog)
^
```

So that's what needs fixing.
