### ISSUE TITLE
conf variables not expanded in templates

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#877]
either variables should be expanded before the template is applied or after, but they need to be done....

```
templates {
    foo {
        uri = 'baz'
    }
    bar {
        uri = "${templates.foo.uri}" 
    }
}
```

If bar template is used, uri is set to the literal value '${templates.foo.uri}'.

**Comment by alandekok** [comment]
I get:

    No such configuration item templates.foo.uri
    ./raddb/templates.conf[112]: Reference "${templates.foo.uri}" not found
    Errors reading or parsing ./raddb/radiusd.conf

Are you sure that the $INCLUDE of the templates.conf is before anything else?

Looking at conffile.c, the expansion of ${...} happens as it's parsing the configuration files.  i.e. before any modules are loaded, and before any module configuration is checked.

Is there a larger example to use for testing?

**Comment by arr2036** [comment]
This appears to be more a feature request for double expansion, and a bit of confusion on how single quoted strings are handled. So i'll close this one for now.
