### ISSUE TITLE
radclient: Packet-Src-IP-Address is not working anymore

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#887]
When calling radclient with Packet-Src-IP-Address, we have the following error:

	radclient: Can't add new socket: Too many open sockets

This happens because the address "prefix" is not initialized, in src/main/radclient.c (starting at line 465):

			case PW_PACKET_SRC_IP_ADDRESS:
				request->packet->src_ipaddr.af = AF_INET;
				request->packet->src_ipaddr.ipaddr.ip4addr.s_addr = vp->vp_ipaddr;
				break;

This causes the address comparison in fr_packet_list_id_alloc to fail.
Then radclient retries with new sockets until the max is reached, at which point the error is logged.

I think the following fix is needed:

			case PW_PACKET_SRC_IP_ADDRESS:
				request->packet->src_ipaddr.af = AF_INET;
				request->packet->src_ipaddr.ipaddr.ip4addr.s_addr = vp->vp_ipaddr;
				request->packet->src_ipaddr.prefix = 32;
				break;

Also, in the case PW_PACKET_SRC_IPV6_ADDRESS I believe the prefix should be set to 128.

And there is the same code in dhcpclient.c, it probably needs the same fix (I didn't test).

**Comment by arr2036** [comment]
Yep should be 128 as well. Thanks for reporting.
