### ISSUE TITLE
Issues encoding and printing a raw "Vendor-Specific"

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#894]
There are issues when handling a value pair attribute created directly as a "Vendor-Specific".
This is required because I'm dealing with a vendor which does not respect the RFC (expecting an exotic encoding), hence it is not possible to create a FreeRADIUS dictionary for this.
I resort to preparing a raw buffer, which I use to create the "Vendor-Specific" attribute with pairmake.

There are (at least) two issues:
- When trying to print the attribute (e.g. through vp_prints_value or vp_prints), in function vp_data_prints_value type PW_TYPE_VSA falls in the default case, which triggers a soft assert in print.c at line 684.
- When trying to encode the attribute before sending (rad_send -> rad_encode -> rad_vp2attr -> rad_vp2rfc -> vp2attr_rfc -> vp2data_any), it fails because function vp2data_any does not handle the case PW_TYPE_VSA (default case "unknown type: ignore it").

I've modified the code as follows.
This was enough to correct the problems I had, but there may be other issues with PW_TYPE_VSA...

Alternatively, changing the dictionary type of "Vendor-Specific" from vsa to octets seems to work also.
But I don't know if this could have unwanted side effects...

Can you look into this ?

Thanks.

1)
In src/lib/print.c, function vp_data_prints_value:

I removed line 680:

	case PW_TYPE_VSA:

Which I moved to line 585, so it is handled the same way as PW_TYPE_OCTETS:

	case PW_TYPE_OCTETS:
	case PW_TYPE_TLV:
	case PW_TYPE_VSA:

2)
In src/lib/radius.c, function vp2data_any:

At line 833, I added PW_TYPE_VSA so it is handled the same way as PW_TYPE_OCTETS:

	switch (vp->da->type) {
	case PW_TYPE_STRING:
	case PW_TYPE_OCTETS:
	case PW_TYPE_TLV:
	case PW_TYPE_VSA:

**Comment by arr2036** [comment]
I think that assert is correct. If it's a weird encoding then it should be an octets type attribute?

**Comment by arr2036** [comment]
Unless it's a weird way of encoding the vendor type/length? What do these attributes look like?

**Comment by alandekok** [comment]
> There are issues when handling a value pair attribute created directly as a "Vendor-Specific.

The simplest response is "don't do that".  It's a bad idea.

> This is required because I'm dealing with a vendor which does not respect the RFC (expecting an exotic encoding), hence it is not possible to create a FreeRADIUS dictionary for this.

If we know what the encoding is, we can probably help.

> Alternatively, changing the dictionary type of "Vendor-Specific" from vsa to octets seems to work also.
> But I don't know if this could have unwanted side effects...

It will break decoding of *all* VSAs.

Your patches are correct.  I'll push a fix.

**Comment by nchaigne** [comment]
This is attribute 26 (Vendor-Specific) which is defined as "vsa" in dictionary.rfc2865.
The weirdness is the following:
There is no "vendor length". The length is deduced from the "vendor type".

I've found another solution which does not require change in the code or the dictionary:
Instead of creating the attribute with "Vendor-Specific", use "Attr-26" instead.
This works.

**Comment by alandekok** [comment]
Ah... yes... I had forgotten about that.  Good point.  I'll push a fix which prevents people from creating Vendor-Specific.  That should help.

**Comment by alandekok** [comment]
> There is no "vendor length". The length is deduced from the "vendor type".

Yes.  Vendor-Specific is *defined* to contain a 4-octet vendor type.  Followed by vendor-specific data.

IIRC, It's Breezecom (now Alvarion) who were the most ridiculous examples of this.  It's like they read the RFCs, and decided to do everything the opposite way.

**Comment by nchaigne** [comment]
Yeah, technically my vendor doesn't break the RFC, they just ignored a "should" for no good reason. 

Anyhow, thanks for the fix !

**Comment by arr2036** [comment]
Just FYI. The attribute you create won't really exist as far as most VALUE_PAIR searching functions are concerned. You won't be able to overwrite it, you won't be able to remove it (except with list remove), you don't be able to iterate over it, and you won't be able to use it in conditions. Filters may work because they use older code.

**Comment by nchaigne** [comment]
OK thanks for the warning. This should not be an issue, I just need to add these attributes before sending the request to a proxy server.
