### ISSUE TITLE
radmin ideas

### ISSUE THREAD

**Issue by alandekok** [FreeRADIUS/freeradius-server#902]
Injecting packets good. It's hard to test policies with many different kinds of NAS. For this it'd be nice to accept piped input into radmin (like is currently possible with radclient), instead of introducing new command syntax.
- Multiline input for certain commands (like packet injection)
- Persistent command history via readline.
- Connection pool status 'ping'. Time execution of the status callback. Probably want to do this asynchronously.
- Injecting outbound packets (is this already there)? Start with CoA/DM.
- Triggering home-server status checks as FreeRADIUS isn't allowed to do keepalives. 
- Connection pool stats.
- Forcing rolling re-establishment of connection pool connections.
- Forcing connection pools to return no connection available - now they're shared we need a way of disabling all modules which use a given pool.
- Toggle whether listeners respond to new requests (graceful removal from proxy or load balance group)
- Dynamic discard filters. Firewalls generally can't filter on RADIUS attributes.

**Comment by jpereira** [comment]
isn't "radmin".... this will be "super-radmin"

**Comment by alandekok** [comment]
No longer relevant with the v4 re-design.  We will re-do this as a separate issue, when that becomes relevant.

The goal for v4 is to fix these by design, not by "new features".  i.e. these features should be part of the server core, accessible to everything.
