### ISSUE TITLE
radmin needs to be smarter about finding sockets in configuration files

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#903]
For monitoring it's a good idea to use two control sockets. One accessible by the monitoring process (ro) and another for actual administration.

radmin seems to pick the socket path from the first virtual server/listen section it finds. A smarter way of doing it, would be to loop over the socket listen sections, using the first one with a user/group which matches euid/egid.

This isn't difficult to do. But no time now...

**Comment by alandekok** [comment]
> For monitoring it's a good idea to use two control sockets. One accessible by the monitoring process (ro) and another for actual administration.

  That works.

> radmin seems to pick the socket path from the first virtual server/listen section it finds. A smarter way of doing it, would be to loop over the socket listen sections, using the first one with a user/group which matches euid/egid.

  That�s harder.  People can use �radmin -f socket� to point to a specific socket.

**Comment by alandekok** [comment]
Fixed by commit c3444a94
