### ISSUE TITLE
Seg fault in event.c

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#910]
Hello,

I have encountered a segmentation fault in event.c.

This happens during load tests with proxy, and using rlm_rest module.

The RADIUS logs show the following:

	Fri Feb 20 10:08:22 2015 : Info: SOFT ASSERT FAILED /home/admwpsrs/src/freeradius-server-3.0.6-c9/src/lib/event.c[191]: *(ev->parent) == ev
	Fri Feb 20 10:08:22 2015 : Info: SOFT ASSERT FAILED /home/admwpsrs/src/freeradius-server-3.0.6-c9/src/lib/event.c[197]: ret == 1

And the backtrace associated:

	#0 0x0000003535a0f3cb in raise () from /lib64/libpthread.so.0
	No symbol table info available.
	#1 0x00007f4872ba06c6 in skgesigOSCrash () from /opt/oracle/instantclient_11_2/libclntsh.so.11.1
	No symbol table info available.
	#2 0x00007f4872e51f79 in kpeDbgSignalHandler () from /opt/oracle/instantclient_11_2/libclntsh.so.11.1
	No symbol table info available.
	#3 0x00007f4872ba08d6 in skgesig_sigactionHandler () from /opt/oracle/instantclient_11_2/libclntsh.so.11.1
	No symbol table info available.
	#4 
	No symbol table info available.
	#5 0x00000035352328a5 in raise () from /lib64/libc.so.6
	No symbol table info available.
	#6 0x0000003535234085 in abort () from /lib64/libc.so.6
	No symbol table info available.
	#7 0x00007f48743dd169 in talloc_abort (reason=0x7f48743e1b38 "Bad talloc magic value - access after free") at ../talloc.c:338
	No locals.
	#8 0x00007f48743dd1f5 in talloc_abort_access_after_free () at ../talloc.c:357
	No locals.
	#9 0x00007f48743dd273 in talloc_chunk_from_ptr (ptr=0x5e056e0) at ../talloc.c:378
	pp = 0x5e056e0 "\360\251B"
	tc = 0x5e05680
	#10 0x00007f48743df4e5 in _talloc_free (ptr=0x5e056e0, location=0x7f4874829a80 "/home/admwpsrs/src/freeradius-server-3.0.6-c9/src/lib/event.c:198")
	at ../talloc.c:1548
	tc = 0x7f4874803172
	#11 0x00007f487481e310 in fr_event_delete (el=0x2656720, parent=) at /home/admwpsrs/src/freeradius-server-3.0.6-c9/src/lib/event.c:198
	ret = 0
	ev = 0x5e056e0
	#12 0x00007f487481e3bc in fr_event_run (el=0x2656720, when=) at /home/admwpsrs/src/freeradius-server-3.0.6-c9/src/lib/event.c:288
	callback = 0x42a9f0 
	ctx = 0x6f30e20
	ev = 0x0
	#13 0x00007f487481e6ad in fr_event_loop (el=0x2656720) at /home/admwpsrs/src/freeradius-server-3.0.6-c9/src/lib/event.c:605
	i = 
	rcode = 2
	when = {tv_sec = 1424423302, tv_usec = 650222}
	wake = 
	maxfd = 275
	read_fds = {fds_bits = {32, 0, 0, 0, 16384, 0 }}
	master_fds = {fds_bits = {32, 0, 0, 0, 1036288, 0 }}
	#14 0x000000000042356c in main (argc=, argv=) at /home/admwpsrs/src/freeradius-server-3.0.6-c9/src/main/radiusd.c:574
	rcode = 0
	status = 
	argval = 
	spawn_flag = true
	write_pid = false
	display_version = false
	flag = 0
	from_child = {4, 5}
	autofree = 0x241b070

**Comment by arr2036** [comment]
I'm seeing it too. Low traffic rate, originating CoA requests.

**Comment by alandekok** [comment]
I finally have a test case where I can reproduce this.  I hope to have a patch soon.

**Comment by alandekok** [comment]
The issue seems to be internal talloc weirdness.  If I allocate a REQUEST with a NULL parent, then talloc will allocate a real parent.  Because we have the global NULL context turned off.

But if we free this parent, something weird happens.  Memory gets borked, and everything dies.

The solution is to allocate a real parent instead of relying on talloc to create a fake one.  We can then free the real parent, and everyone is happy.

**Comment by nchaigne** [comment]
I'll test this.
Thank you !

**Comment by lrstx** [comment]
We confirm that your fix solved the issue. Thank you !
