### ISSUE TITLE
segfault on LDAP auth to AD

### ISSUE THREAD

**Issue by sandereerd** [FreeRADIUS/freeradius-server#916]
Hi,

On migrating from freeradius v2 to v3, I have a problem getting LDAP auth against an Active Directory to work. Every time freeradius tries to connect to the AD, I get a segmentation violation, and the server crashes with a coredump.

I first experienced this issue on a Solaris 11 server.
To rule out any Solaris-weirdness, I set up an Ubuntu machine, but this gives me the same error.

I created this coredump on a Ubuntu 14.04 LTS OS, with the latest updates.
I built the freeradius 3.0.x server from git source.

Steps to reproduce the problem:
- Compile and build/instal (used compile option --prefix=/usr/local/freeradius3)
- modify the standard ldap config slightly, to enable auth against AD.
- start freeradius server, and try to auth a client -> coredump.

Included are output from gdb, and some more info.
gdb-radius.log: http://pastebin.com/65yLUn0A
radius server output: http://pastebin.com/MfGRismi
radiusd -xv: http://pastebin.com/dV9EVqD0
installed libldap2-dev version is 2.4.31-1+nmu2ubuntu8
ldap config file: http://pastebin.com/XLUZztfQ
Is this all the info required, or did I forget something?

What is also strange:
It need to set base_dn twice,
setting "base_dn = '${..base_dn}'" does not work.

also:
setting a non-existing baseDN does not crash the server.
It seems only when getting an ldap response does the server crash.
Is a wireshark capture file helpful?

Kind regards
And thank you very much in advance
Sander Eerdekens

**Comment by arr2036** [comment]
Default config works fine. You broke it by commenting out ``user.base_dn``. The server shouldn't SEGV though. Thanks for the bug report.
