### ISSUE TITLE
Tagged tunnel attributes (RFC 2868) not supported in rlm_perl

### ISSUE THREAD

**Issue by usr29614** [FreeRADIUS/freeradius-server#917]
With Freeradius 2.2.6 and enabled rlm_perl module we still cannot use tagged tunnel attributes which are defined in and allowed by the RFC 2868 (RADIUS Attributes for Tunnel Protocol Support). Though the BUG had been already known years ago and reported several times (e.g. "Handle tagged attributes with multiple values in rlm_perl"), it is not yet fixed in the current 2.x version (2.2.6).

The attributes are all the standard RADIUS attributes (not VSAs!) which can be specified for LNS1, LNS2, etc in a user's profile in a manner like this:

    Tunnel-Server-Endpoint:1 += 212.49.21.31,
    Tunnel-Server-Endpoint:2 += 212.49.21.32,
    Tunnel-Password:1 += tunnpas1,
    Tunnel-Password:2 += tunnpas2,
    Tunnel-Preference:1 += 10,
    Tunnel-Preference:2 += 20
    ...

Correct handling of tagged tunnel standard RADIUS attributes according to the RFC 2868 is NOT ultimately a task of rlm_perl module intended to be for extended(!) functionality support in Perl, but rather should be a core function of FreeRadius.

Please revise the Freeradius implementation 2.x and please provide a core support for RFC 2868 tagged attributes in the next 2.x release. The support for RFC 2868 tagged attributes is needed for L2TP on LAC and should work normally in Freeradius 2.x, regardless the rlm_perl module is enabled or not. Thank you!

**Comment by alandekok** [comment]
Bug reports should be kept simple, technical, and give information to reproduce it.
> Correct handling of tagged tunnel standard RADIUS attributes according to the RFC 2868 is NOT ultimately a task of rlm_perl module 

Yes, it is.  You don't know how the server works.

Bug reports should not contain whining complaints or attempts to "school" us in being developers.  Those complaints are rude and unproductive.

**Comment by arr2036** [comment]
The modules are not bound to any RFCs, so I would argue this is a feature request . v2.x.x is in feature freeze, you're welcome to re-open this issue for v3.0.x.
