### ISSUE TITLE
Bareword 0xffffff should probably be cast to an unit8_t value

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#925]
Doesn't really apply to to single quoted or double quoted strings, but barewords starting with 0x should probably be interpreted as hex strings.

```
if ('foo' == 0x666f6f) {
// should be true
}
```

That's consistent with update blocks.

The actual failing test is more like:

```
update control {
Tmp-String-0 := 'foo'
}

if ("%{hex:&control:Tmp-String-0}" == 0x666f6f) {
// should be true
}
```

Might be specific to that. Just don't have time to investigate.

**Comment by alandekok** [comment]
Sure� if the LHS isn�t an integer or integer-type attribute.

      if (NAS-Port-Id == 0x0000abcd)

  should cast the hex numbers to a 32-bit integer.

  This type of automatic casting needs to be done VERY carefully, and ONLY in certain specific circumstances.  Otherwise it has the potential to break all kinds of things.

**Comment by arr2036** [comment]
I think if the parser just generated a tmpl with value_data of type octets from bareword hex strings the auto casting will work.

Might just need to modify value_data_afrom_str.

**Comment by alandekok** [comment]
The problem is that this is wrong:

	NAS-Port-Id == 0xffffffffffffffffffffffffffff

  It can�t be cast to an integer.

  So whatever happens behind the scenes, the above MUST be a parse error.

  My concern is that changing this now means changing ALL uses of it.  I don�t want to bork the server because there�s an attempt for �purity"

**Comment by arr2036** [comment]
```c
		/*
		 *	No attribute names start with 0x, and if they did, the user
		 *	can just use the explicit & prefix.
		 */
		if ((in[0] == '0') && (in[1] == 'x')) {
			size_t binlen, len;

			/*
			 *	Hex strings must contain even number of characters
			 */
			if (inlen & 0x01) {
				fr_strerror_printf("Hex string %.*s not even length", (int) inlen, in);
				return -inlen;
			}

			binlen = (inlen - 2) / 2;

			vpt = tmpl_alloc(ctx, TMPL_TYPE_DATA, in, inlen);
			vpt->tmpl_data_value.ptr = talloc_array(vpt, uint8_t, binlen);
			vpt->tmpl_data_length = binlen;
			vpt->tmpl_data_type = PW_TYPE_OCTETS;

			len = fr_hex2bin(vpt->tmpl_data_value.ptr, binlen, in + 2, inlen - 2);
			if (len != binlen) {
				talloc_free(vpt);
				return -(len + 2);
			}
			slen = len;
			break;
		}
```

Unfortunately, errors elsewhere... I'll look at it more later. Looks like it's not that simple.

**Comment by alandekok** [comment]
There is a test for this in `src/tests/keywords/integer-overflow-error`
