### ISSUE TITLE
Should exec results be treated as literal values?

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#926]
Currently \n\r and others are unescaped by the server if they're output by an execed program

```
update request {
    Tmp-String-0 := `echo '\n'`
}
if ("%{hex:&Tmp-String-0}" == '0a') {
// probably should be 5c6e
}
```

**Comment by arr2036** [comment]
@alandekok thoughts?  Fairly certain they should be literal?

**Comment by alandekok** [comment]
the new tmpl code should mostly handle this by default, along with the tainted flag.  the output of `exec` is really just a blob, _until_ such time as it's interpreted by something else.
