### ISSUE TITLE
freeradius stops using proxy-home-server

### ISSUE THREAD

**Issue by Maheine** [FreeRADIUS/freeradius-server#933]
Every 2-4 weeks one of our freeradius server (not always the same) do not use the proxy-home-server for foreign realms anymore, it tries to find the users from foreign realms in the local ldap server. The authentication and accounting for the local realm users is working fine. After a restart of the radius daemon the foreign realm authenticaiton is also fine again. 

The only error in the logfile is: 
"Auth: Login incorrect (  [ldap-primaer] User not found): [user@foreign-realm]"

Due to the working authentication of the local realm users, we don't realise whether the foreign realm authentication is working or not. 

Edit:
FreeRADIUS Version 2.2.5, for host x86_64-redhat-linux-gnu

**Comment by alandekok** [comment]
There's very little we can do with a vague report like that.
