### ISSUE TITLE
No EAP and Message-Authenticator in Access-Reject when rejecting based on invalid identity

### ISSUE THREAD

**Issue by sbren** [FreeRADIUS/freeradius-server#937]
When FreeRADIUS 2.2.6 rejects a client based on his outer identity, e.g. in case of a wrong realm, it does not include the EAP and Message-Authenticator attributes in the RADIUS Access-Reject message.
Therefore the wireless access point does not submit an EAP Failure message to the client.

Used setup: 802.1X authentication with hostapd 2.3 as wireless access point and FreeRADIUS 2.2.6.
WAs used with following authentication methods:
- EAP-TTLS
- PEAP

Expected behavior:
Since the identity is submitted in a EAP attribute / EAP Identity response message, FreeRADIUS should recognise the usage of EAP and include the missing EAP Failure message in an EAP attibute in RADIUS Access-Reject and also the according Message-Authenticator

Issue can be seen in traffic captures or in the access point log.
Output from hostapd:
```
Configuration file: hostapd_wireless.conf
Using interface wlan0 with hwaddr a0:f3:c1:28:1d:1f and ssid "testnet"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: CTRL-EVENT-EAP-STARTED 38:e7:d8:db:0b:69
wlan0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
wlan0: STA 38:e7:d8:db:0b:69 IEEE 802.1X: could not extract EAP-Message from RADIUS message
wlan0: STA 38:e7:d8:db:0b:69 IEEE 802.1X: authentication failed - EAP type: 0 ((null))
```

**Comment by arr2036** [comment]
Not a bug. Unlang can be used to hack together a solution.

If you don't want to use unlang, switch to v3.0.x and call EAP in post-auth.

https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/modules/rlm_eap/rlm_eap.c#L713

**Comment by sbren** [comment]
Thanks, I'll take a look.
