### ISSUE TITLE
No check for zero data / on misplaced ACK messages in EAP-TTLS and PEAP?

### ISSUE THREAD

**Issue by sbren** [FreeRADIUS/freeradius-server#938]
FreeRADIUS 2.2.6 seems not to check for data presence and does not discard misplaced ACK messages in TTLS and PEAP.
ACK messages are expected, when packets with the M flag set were sent previously by the server.

According to Microsoft's PEAP documentation, misplaced or wrong formatted messages should be silently discarded.

When sending an ACK message as inner identity response in PEAP / MSCHAPv2
or directly after the TLS handshake in TTLS instead of inner method messages, FreeRADIUS answers as follows:
PEAP: FreeRADIUS responds with empty TTLS packet with no flags send
TTLS: FreeRADIUS responds with empty TTLS packet with length field set to zero

**Comment by alandekok** [comment]
On Mar 26, 2015, at 1:31 PM, sbren <notifications@github.com> wrote:
> FreeRADIUS 2.2.6 seems not to check for data presence and does not discard misplaced ACK messages in TTLS and PEAP.
> ACK messages are expected, when packets with the M flag set were sent previously by the server.

  To be honest, if the client send crap, the server should discard the connection.  I am VERY wary of butchering the server to deal with retarded clients.

> According to Microsoft's PEAP documentation, misplaced or wrong formatted messages should be silently discarded.

  And then what?  Not send an Access-Challenge?  How will the EAP conversation continue?

> When sending an ACK message as inner identity response in PEAP / MSCHAPv2
> or directly after the TLS handshake in TTLS instead of inner method messages, FreeRADIUS answers as follows:
> PEAP: FreeRADIUS responds with empty TTLS packet with no flags send
> TTLS: FreeRADIUS responds with empty TTLS packet with length field set to zero

  So� what�s wrong with that?  It works for all known clients.

**Comment by sbren** [comment]
> And then what? Not send an Access-Challenge? How will the EAP conversation continue?

In worst case: By waiting for timeout, although it might not be the best solution.

> So� what�s wrong with that? It works for all known clients.

They discard it (at least wpa_supplicant does) and the AP keeps retransmitting.
It's just an unnecessary reply from server side.

**Comment by alandekok** [comment]
On Mar 26, 2015, at 1:53 PM, sbren <notifications@github.com> wrote:

> And then what? Not send an Access-Challenge? How will the EAP conversation continue?
> 
> In worst case: By waiting for timeout, although it might not be the best solution.

  No.  The NAS will re-send the exact same RADIUS packet.

> They discard it (at least wpa_supplicant does) and the AP keeps retransmitting.
> It's just an unnecessary reply from server side.

  Well, blame it on OpenSSL.  We�re at the mercy of their code.
