### ISSUE TITLE
radwho doesn't filter user and doesn't show full mac

### ISSUE THREAD

**Issue by nicraMarcin** [FreeRADIUS/freeradius-server#943]
radwho doesn't filter with -u or -U and mac isn't full 
#v+
marcin@radius01:~$ sudo radwho 
Login      Name       What  TTY  When      From     Location
bobpppoe   bobpppoe          PPP   >999 Tue 08:41 172.21.7.176    10.5.4.3
marcin@radius01:~$ sudo radwho -u bob -c -r -s
bobpppoe,08:00:27:D6:04:,PPP,S15728640,Tue 08:41,172.21.7.176,10.5.4.3
marcin@radius01:~$ sudo radwho -u bob -c -s
Login      Name       What  TTY  When      From     Location
bobpppoe   08:00:27:D6:04:   PPP   >999 Tue 08:41 172.21.7.176    10.5.4.3
marcin@radius01:~$ sudo radwho -U bob -c -s
Login      Name       What  TTY  When      From     Location
bobpppoe   08:00:27:D6:04:   PPP   >999 Tue 08:41 172.21.7.176    10.5.4.3
#v-

**Comment by alandekok** [comment]
The name comparisons are done on the prefix of the name.  It doesn't show the full MAC because the utmp fields aren't large enough to store the full MAC.

I suggest using SQL for utmp users instead of radutmp.
