### ISSUE TITLE
SEGV with long 'TLS-Cert-Subject' on fr 3.0.7

### ISSUE THREAD

**Issue by etokaoru** [FreeRADIUS/freeradius-server#949]
I got a SEGV with long 'TLS-Cert-Subject' on fr 3.0.7.

I checked with static string with following codes.
So, I got a SEGV with over 227 octets 'TLS-Cert-Subject'.

tls.c
<pre><code>
	/*
	 *	Get the Subject & Issuer
	 */
	subject[0] = issuer[0] = '\0';
	X509_NAME_oneline(X509_get_subject_name(client_cert), subject,
			  sizeof(subject));

	sprintf(subject,"12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567");	//Add this line.
	subject[sizeof(subject) - 1] = '\0';
	RDEBUG("subject strlen = %d",  strlen(subject));	//Add this line.
	if (certs && identity && (lookup <= 1) && subject[0]) {
		vp = pairmake(talloc_ctx, certs, cert_attr_names[FR_TLS_SUBJECT][lookup], subject, T_OP_SET);
		rdebug_pair(L_DBG_LVL_2, request, vp, "&request:");
	}
</code></pre>

pair.c
<pre><code>
void rdebug_pair(log_lvl_t level, REQUEST *request, VALUE_PAIR *vp, char const *prefix)
{
	char buffer[256];

	if (!vp || !request || !request->log.func) return;

	if (!radlog_debug_enabled(L_DBG, level, request)) return;

	vp_prints(buffer, sizeof(buffer), vp);

	RDEBUG("buffer strlen = %d",  strlen(buffer));		//Add this line.
	RDEBUGX(level, "%s%s", prefix ? prefix : "",  buffer);
}
</code></pre>

Debug with EAP-TLS.

<pre>
Debug: (7) eap_tls: TLS Verify adding attributes
Debug: (7) eap_tls:   buffer strlen = 48
Debug: (7) eap_tls:   &request:TLS-Client-Cert-Serial := '12345678'
Debug: (7) eap_tls:   buffer strlen = 45
Debug: (7) eap_tls:   &request:TLS-Client-Cert-Expiration := '160316042321Z'
Debug: (7) eap_tls:   subject strlen = 227
Debug: (7) eap_tls:   buffer strlen = 256
Debug: (7) eap_tls:   &request:TLS-Client-Cert-Subject := '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567'
->SEGV
</pre>

The subject length is good, but the buffer length in rdebug_pair is increased!

**Comment by alandekok** [comment]
> The subject length is good, but the buffer length in rdebug_pair is increased!

Yes, because the buffer in rdebug_pair includes the attribute name and "=" sign, too.

I can't reproduce this in the v3.0.x branch.
