### ISSUE TITLE
segment failure Huntgroup SQL 

### ISSUE THREAD

**Issue by jihadfee** [FreeRADIUS/freeradius-server#950]
Get a Segment Failure when doing a Huntgroup SQL Query

then the match fails ie the huntgroup does not match it crash's

these are the gdb result's

warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fffd3600000
0x00007f2e8d5ec65d in __libc_waitpid (pid=<value optimized out>, stat_loc=<value optimized out>, options=<value optimized out>)
    at ../sysdeps/unix/sysv/linux/waitpid.c:41
41	  int result = INLINE_SYSCALL (wait4, 4, pid, stat_loc, options, NULL);
(gdb) backtrace
#0  0x00007f2e8d5ec65d in __libc_waitpid (pid=<value optimized out>, stat_loc=<value optimized out>, options=<value optimized out>)
    at ../sysdeps/unix/sysv/linux/waitpid.c:41
#1  0x00007f2e8d57e609 in do_system (line=<value optimized out>) at ../sysdeps/posix/system.c:149
#2  0x00007f2e8d57e940 in __libc_system (line=<value optimized out>) at ../sysdeps/posix/system.c:190
#3  0x00007f2e8edfb12d in fr_fault (sig=11) at src/lib/debug.c:746
#4  <signal handler called>
#5  rlm_sql_process_groups (inst=0xd02580, request=0xd6a640, handle=0x7fffd3564fc0, do_fall_through=0x7fffd3564fcc) at src/modules/rlm_sql/rlm_sql.c:680
#6  0x00007f2e898d4fbc in mod_authorize (instance=0xd02580, request=0xd6a640) at src/modules/rlm_sql/rlm_sql.c:1167
#7  0x000000000042452f in call_modsingle (request=0xd6a640, component=RLM_COMPONENT_AUTZ, depth=1, entry=0x7fffd3565548) at src/main/modcall.c:303
#8  modcall_recurse (request=0xd6a640, component=RLM_COMPONENT_AUTZ, depth=1, entry=0x7fffd3565548) at src/main/modcall.c:575
#9  0x0000000000424d81 in modcall_child (request=<value optimized out>, component=<value optimized out>, depth=<value optimized out>, entry=0x7fffd3565530,
    c=<value optimized out>, result=0x7fffd35654ec) at src/main/modcall.c:409
#10 0x0000000000423b48 in modcall_recurse (request=0xd6a640, component=RLM_COMPONENT_AUTZ, depth=0, entry=0x7fffd3565530) at src/main/modcall.c:779
#11 0x0000000000424d1d in modcall (component=<value optimized out>, c=<value optimized out>, request=<value optimized out>) at src/main/modcall.c:1123
#12 0x000000000041ea75 in indexed_modcall (comp=RLM_COMPONENT_AUTZ, idx=<value optimized out>, request=0xd6a640) at src/main/modules.c:887
#13 0x000000000040ea35 in rad_authenticate (request=0xd6a640) at src/main/auth.c:490
#14 0x0000000000432b6b in request_running (request=0xd6a640, action=<value optimized out>) at src/main/process.c:1571
#15 0x000000000042fb25 in request_queue_or_run (request=0xd6a640, process=<value optimized out>) at src/main/process.c:1101
#16 0x0000000000430297 in request_receive (ctx=<value optimized out>, listener=0xd68b00, packet=0xd6a4b0, client=0xd3be00, fun=0x40e770 <rad_authenticate>)
    at src/main/process.c:1796
#17 0x000000000041b19a in auth_socket_recv (listener=0xd68b00) at src/main/listen.c:1529
#18 0x000000000043370b in event_socket_handler (xel=<value optimized out>, fd=<value optimized out>, ctx=<value optimized out>) at src/main/process.c:4263
#19 0x00007f2e8ee1589b in fr_event_loop (el=0xc98890) at src/lib/event.c:623
#20 0x000000000042573c in main (argc=2, argv=<value optimized out>) at src/main/radiusd.c:576
(gdb)

**Comment by alandekok** [comment]
Fixed by committ 455cfe145183
