### ISSUE TITLE
FreeRADIUS shouldn't use gettimeofday in the event code, should use monotonic clock

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#951]
Should use clock_gettime() on most POSIX systems http://pubs.opengroup.org/onlinepubs/9699919799/

or mach_absolute_time on OSX

Examples here:
https://github.com/ThomasHabets/monotonic_clock

**Comment by alandekok** [comment]
I'll close this as "fix in progress.  All of the new worker / network code in v4 uses `fr_time()` everywhere.

**Comment by alandekok** [comment]
This is done as of June 2019.
