### ISSUE TITLE
Something is messing up the name of the LHS template in update section maps, when the RHS is an octets (hex) string

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#952]
```text
update {
	control:Tmp-Octets-0 := 0xf000
}
```

Is printed as
```text
update {
	Tmp-Octets-0 := 0xf000
}
```

Name is fine when the template is created with ``tmpl_afrom_attr_str``, must get messed up in one of the fixup functions.

**Comment by alandekok** [comment]
printed how?  Debug mode?  With what function?

**Comment by arr2036** [comment]
Well there's nothing else that would print the pair with update and braces, so yes, debug mode.

The function, after some hunting, is ``map_debug_log``.

**Comment by alandekok** [comment]
It's been fixed.
