### ISSUE TITLE
3.1.x - radclient - filter not working

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#957]
I'm trying to use a filter with radclient, with a filter that matches exactly the actual attribute returned.
It doesn't work as expected.
I get the following message:

	Received Access-Accept Id 195 from 10.67.106.9:42812 to 0.0.0.0:0 length 32
			Reply-Message = 'Hello, bob'
	(0) in-bob-pap.vps: Response for failed filter: Attribute value "Hello, bob" didn't match filter: Reply-Message = "Hello, bob"

I've tried the following change, which fixes the issue.
Can you check if it's correct ?

In function value_data_cmp_op (file: src\lib\value.c):
After line 384, I've added "case T_OP_EQ", as follows:

	switch (op) {
	case T_OP_CMP_EQ:
	case T_OP_EQ:
		return (compare == 0);

**Comment by arr2036** [comment]
Use == in the filter

**Comment by nchaigne** [comment]
Damn. Stupid me.
Thanks :)

**Comment by arr2036** [comment]
We could fixup all T_OP_EQ to be T_OP_CMP_EQ in radclient, but that prevents us from ever using the assignment operator in future, and we may actually want to use the assignment operator, to allow writing of statefull tests, for things like OTP.

There's actually documentation for ``raduat`` I wrote a couple of weeks ago
http://wiki.freeradius.org/guide/raduat

I'd recommend using the script, it makes managing the tests simpler

**Comment by nchaigne** [comment]
Nice guide. I'll keep it in mind, thanks.

**Comment by nchaigne** [comment]
A small error in the doc:

*= ANY - Present

This should be "=*".

**Comment by arr2036** [comment]
ah, yep, thanks... though you can edit it too :)

**Comment by nchaigne** [comment]
I can't authenticate... do I need to make my email address from GitHub public for this ?

(The match operator also is inverted, it should be "=~".)

**Comment by arr2036** [comment]
yes, so that it goes in the commit log, and we can yell at you if you make bad commits :P

**Comment by arr2036** [comment]
I've fixed the two operators you noted
