### ISSUE TITLE
Possible ideas for ldap & mschap modules

### ISSUE THREAD

**Issue by ether42** [FreeRADIUS/freeradius-server#959]
Hi,

Some times ago, I 'forked' the *ldap* & *mschap* modules to add some specific behaviours that were required in the environment where I set up a FreeRADIUS server.

To be brief, the added functionality was, for the *ldap* module, to allow users to authenticate without a domain suffix (*@ realm* part). The goal was to try to find the user in a corresponding Active Directory and if the user was found in the LDAP directory, to forward the request to the NPS server of the Active Directory domain that could verify the credentials of the user. It simply append the *@ realm* part specified in the configuration to the username. If the *suffix* and *proxy* modules were correctly configured, the request would be handled without any special effort.
You can see the code [here](https://github.com/ether42/freeradius-ldap-kerberos/blob/master/radius/freeradius-server-3.1.0/src/modules/rlm_ldap_forwarder/rlm_ldap.c#L941).

For the *mschap* module, I was inspired by this blog [entry](https://fuhry.com/blog/2012/01/01/mschapv2-against-mit-kerberos-yes-you-can/): we used a MIT Kerberos KDC with a LDAP backend and to allow PEAP to work, I had to retrieve the necessary hash from the Kerberos database.
The important part of the code may be found [here](https://github.com/ether42/freeradius-ldap-kerberos/blob/master/radius/freeradius-server-3.1.0/src/modules/rlm_mschapv2_kerberos/rlm_mschap.c#L2034).

The source was retrieved as a tarball a long time ago from FreeRADIUS' website (sorry, that was not the best idea I had...).

The code is not as clean as I wanted, and I understand that it may feel hackish and maybe not that useful (for example, the Kerberos part could be more generic and I'm sure the custom code added to the old MIT Kerberos sources may not be required these days for it to function properly).
But today, I was asking myself if you could find that little additions interesting/useful for some people/... If you want or think it may be useful, I could take some time to make these modifications available as commits on top of the current FreeRADIUS project state. If you think it is complete garbage or simply not worth the effort, you could close this issue, it is here just to know what you think about the functionalities that were added :)

Thanks for your time.

Regards.

**Comment by arr2036** [comment]
The LDAP modifications don't sound useful. It seems the same thing can be achieved in unlang with very little effort. Unless i've missed something?

```
ldap
if (ok || updated) {
	if (User-Name !~ /@/) {
		update request {
			User-Name := "%{User-Name}@nps-realm"
		}
	}
}
```

or just

```
ldap
if (ok || updated) {
	if (User-Name !~ /@/) {
		update control {
			Proxy-To-Realm := "nps-realm"
		}
	}
}
```

The kerberos changes seem useful, but are definitely in the wrong module. They would belong in an authorize method of rlm_kerberos. It should add ``control:NT-Password`` to the current request. I'd be interested in seeing that in a pull request.

Cheers,
Arran

**Comment by arr2036** [comment]
Yeah
```c
unsigned char* ntlm = kerberos_ntlm_hash(inst, principal);
if (ntlm) {
		smbdes_mschap(ntlm, mschapv1_challenge, calculated);
```

See kerberos_ntlm_hash must be producing the NT-Password, as that's what smbdes_mschap takes as its first argument.

**Comment by ether42** [comment]
Oh, yes, I never really used unlang, that's why it was more natural for me to simply append the realm to the username in a module but your solution is simpler and more elegant, of course.

I'll give a look at the Kerberos module later, thanks for your answer.

**Comment by ether42** [comment]
I think you can close this issue, I don't want to bother you with one that may be open for a while.
I'll try what you suggested (add these changes in the authorize method of the existing kerberos module) and surely come back to you with a pull request.

Thank you.
Regards.

**Comment by arr2036** [comment]
Sounds good.

-Arran
