### ISSUE TITLE
bufferes-sql segmentation fault

### ISSUE THREAD

**Issue by nicraMarcin** [FreeRADIUS/freeradius-server#960]
in buffered-sql config:
#v+
                #  Useful range of values: 1 to 60
                poll_interval = 60
#v-

/etc/freeradius/sites-enabled/buffered-sql[40]: poll_interval must be between 1 and 20
Segmentation fault

**Comment by alandekok** [comment]
See doc/bugs

**Comment by nicraMarcin** [comment]
I think that debugging is not necessary, debug from "freeradius -X" says what to do. if i set pool_interval to 20 it works. But there is misconfiguration in config or in code.

**Comment by alandekok** [comment]
If you think debugging isn't necessary, why did you open a bug report?

The purpose of reading doc/bugs is to have you give MORE information, so that we can fix the problem.  If you're not going to do that, you're wasting everyone's time.

**Comment by nicraMarcin** [comment]
I see that it was corrected, thanks.
