### ISSUE TITLE
rewrite_called_station_id should not strip SSID

### ISSUE THREAD

**Issue by gvde** [FreeRADIUS/freeradius-server#982]
RFC 3580 says:

3.20.  Called-Station-Id

   For IEEE 802.1X Authenticators, this attribute is used to store the
   bridge or Access Point MAC address in ASCII format (upper case only),
   with octet values separated by a "-".  Example: "00-10-A4-23-19-C0".
   In IEEE 802.11, where the SSID is known, it SHOULD be appended to the
   Access Point MAC address, separated from the MAC address with a ":".
   Example "00-10-A4-23-19-C0:AP1".

Currently, rewrite_called_station_id strips the SSID from Called-Station-Id and puts it into Called-Station-SSID. While it's useful to have the SSID separately, it should not be removed from Called-Station-Id as the RFC says the SSID "SHOULD be appended" to the attribute.

Of course, to extract the SSID from a RFC conform Called-Station-Id the regex should check for the ":" between MAC address and SSID.

**Comment by alandekok** [comment]
The policy is *optional*, and isn't enabled in the default configuration.  If users want to re-write the Called-Station-Id attribute, they should be allowed to do that.

> Of course, to extract the SSID from a RFC conform Called-Station-Id the regex should check for the ":" between MAC address and SSID.

Go read the regex again.  It correctly strips off the SSID, as is also seen in the debug output you posted to the list.

The regex does *not* look for a ":" character because many NAS vendors don't read the RFC, and use something else as a delimiter.

Writing and maintaining a RADIUS server is a lot more complicated than just a blind adherence to the RFCs.

**Comment by gvde** [comment]
The comment before the policy says: "Makes Called-Station-ID conform to what RFC3580 says should
#  be provided by 802.1X authenticators." So I would assume it would do something like that. In particular, I would also assume that the policy won't change a value which is like the RFC says it "SHOULD" be. The policy takes a valid which is like it SHOULD be and makes a value out of it how it shouldn't be.
Of course, the policy is optional but "examples" like this makes the whole thing more confusing.
If a user wants to strip off the SSID from the Called-Station-Id attribute the user can do so in its own policies. But a policy which "Makes Called-Station-ID conform to what RFC3580 says" should not make a value conform to RFC3580 less conform, even if it's only a "SHOULD" requirement in the RFC.

**Comment by alandekok** [comment]
The policy *also* re-writes the Calling-Station-Id to use the RFC suggested format.  Many vendors use ":" instead of "-" as octet separators, or don't use separators at all.

If you're going to nit-pick about things, it helps to have *correct* comments.

**Comment by arr2036** [comment]
I agree with Alan, you're being needlessly pedantic. The vast majority of users want this split out. There is greater harm (unless proxying) in keeping the BSSID and SSID concatenated, and having them inserted into databases as one value. The use cases where you want to query on a combined BSSID and SSID are very few, whereas querying on SSID, or using GROUP BY Called-Station-ID is very common.

Also note that the RFC is describing the format of the value sent from the NAS, it does not comment on how they should be processed by policies on the RADIUS server.
