### ISSUE TITLE
rlm_caching query

### ISSUE THREAD

**Issue by alanbuxey** [FreeRADIUS/freeradius-server#987]
forgive my rusty coding...but line 323 of rlm_caching.c in version 2.2.x

data_datum.dptr = (rlm_caching_data *) &cache_data;

isn't that supposed to be

data_datum.dptr = (char *) &cache_data;

?

**Comment by arr2036** [comment]
yes, but, no one uses rlm_caching, and v2.x.x is meant to be security fix only.
