### ISSUE TITLE
DHCPv6 on FreeRadius v3.0.7

### ISSUE THREAD

**Issue by Thefirstricheur** [FreeRADIUS/freeradius-server#998]
Hello.

I've some troubles to perform a DHCPv6 on FreeRadius v3.0.7.
In fact, in the file sites-available/dhcp, I wrote:
server dhcp6 {
	listen {
		type = dhcp
		port = 547
		ipv6addr = ::
		interface = eth0
		broadcast = yes
	}

	dhcp6 Solicit {
		update reply {
		       DHCPv6-Message-Type = DHCPv6-Advertisement
		}

		update reply {
			##&DHCP-Domain-Name-Server = 192.168.10.253
			##&DHCP-Domain-Name-Server += 192.168.10.252
			##&DHCP-Subnet-Mask = 255.255.255.0
			##&DHCP-Router-Address = 192.168.10.254
			##&DHCP-IP-Address-Lease-Time = 60
			##&Delegated-IPv6-Prefix = 2001:db8:a000:ff::/64
			&Framed-IPv6-Prefix += 2001:db8:a000::/56
			&Framed-IPv6-Address = 2001:db8:a000:ff::abc
			&DNS-Server-IPv6-Address = 2001:db8:a000:ff::252
			&DNS-Server-IPv6-Address += 2001:db8:a000:ff::253
		}
		
		##update control {
		##	&Pool-Name := "test_pool"
		##}
		##dhcp_sqlippool.post-auth
		ok
	}

	dhcpv6 Request {
		update reply {
		       DHCPv6-Message-Type = DHCPv6-Reply
		}
	
		update reply {
			#&DHCP-Domain-Name-Server = 192.168.10.253
			#&DHCP-Domain-Name-Server += 192.168.10.252
			#&DHCP-Subnet-Mask = 255.255.255.0
			#&DHCP-Router-Address = 192.168.10.254
			#&DHCP-IP-Address-Lease-Time = 60
			#&Delegated-IPv6-Prefix = 2001:db8:a000:ff::/64
			&Framed-IPv6-Prefix += 2001:db8:a000::/56
			&Framed-IPv6-Address = 2001:db8:a000:ff::abc
			&DNS-Server-IPv6-Address = 2001:db8:a000:ff::252
			&DNS-Server-IPv6-Address += 2001:db8:a000:ff::253
		}
	
		#update control {
		#	&Pool-Name := "test_pool"
		#}
		##dhcp_sqlippool.post-auth
		ok
	}
}		

and then, when I launch radiusd -X and my client, which is a simple debian 7.6, start to ask an IP, there is only ''Solicit'' message and no response from the server. I don't understand why he doesn't reply.
Can someone help me ?

Simon Mesnage
Student of UIT N&T of Caen, France

**Comment by arr2036** [comment]
> 
> and then, when I launch radiusd -X and my client, which is a simple debian 7.6, start to ask an IP, there is only ''Solicit'' message and no response from the server. I don't understand why he doesn't reply.
> Can someone help me ?

FreeRADIUS doesn't support DHCPv6.

Arran Cudbard-Bell <a.cudbardb@freeradius.org>
FreeRADIUS development team

FD31 3077 42EC 7FCD 32FE 5EE2 56CF 27F9 30A8 CAA2

**Comment by Thefirstricheur** [comment]
Thank you for your reply. 
But, last question, it's also impossible to do Delegation-IPv6-Prefix like the rfc6911 and rfc4818 say ?

**Comment by Thefirstricheur** [comment]
Other question, does it works in PPP ? Because I heard that some people can make this

**Comment by arr2036** [comment]
Yes, it'll work with PPP, but you'll need to modify the sqlippool queries, and yes, FreeRADIUS supports IPv6 address and prefix attribute types.

Please ask any further questions on the mailing lists. The bug tracker is not a support forum.
